import { SIMULATION_RULE_PRESETS, DEFAULT_SIMULATION_RULES, ENGINE_GATED_VIRTUAL_RULE_KEYS, ENGINE_GATED_DORMANT_RULE_KEYS, normalizeSimulationRules, newCampaignSimulationRules } from '/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/laneLDEFAULT/src/domain/worldPulse/simulationRules.js';
console.log('PRESET IDS:', Object.keys(SIMULATION_RULE_PRESETS).join(', '));
console.log('DEFAULT keys:', Object.keys(DEFAULT_SIMULATION_RULES).length);
console.log('REGISTER len:', ENGINE_GATED_VIRTUAL_RULE_KEYS.length);
console.log(JSON.stringify(ENGINE_GATED_VIRTUAL_RULE_KEYS));
console.log('DORMANT len:', ENGINE_GATED_DORMANT_RULE_KEYS.length);
console.log(JSON.stringify(ENGINE_GATED_DORMANT_RULE_KEYS));
for (const [id, p] of Object.entries(SIMULATION_RULE_PRESETS)) console.log(' preset', id, 'rulekeys=', Object.keys(p.rules).length);
const born = newCampaignSimulationRules();
console.log('BIRTH keys:', Object.keys(born).length, 'presetId=', born.presetId);
const rr = normalizeSimulationRules(SIMULATION_RULE_PRESETS.realistic_regional.rules);
console.log('normalized realistic_regional keys:', Object.keys(rr).length, 'presetId=', rr.presetId);
