import json
C=[]
def add(**k):
    d=dict(page="",kind="analysis",polarity="asserts",date="",routeHint="",registerHint="dossier-archivist",confidence="high")
    d.update(k); C.append(d)
OU="https://dc.swosu.edu/mythlore/vol41/iss1/4/"
OS="Matthew Oliver, \"History in the Margins: Epigraphs and Negative Space in Robin Hobb's Assassin's Apprentice\", Mythlore 41.1 (141), Fall/Winter 2022, pp. 45-66"
OR="PDF already on disk at sweep/hobb-raw/oliver-mythlore.pdf, text extracted; open-access SWOSU Digital Commons"
add(feature="civic record register",claim="Oliver characterises the chapter epigraphs of Assassin's Apprentice as excerpts from a public document written in a distant, scholarly voice.",source=OS,url=OU,quote="largely a formal history written in a distant, scholarly voice",page="p. 45",date="2022-10",routeHint=OR)
add(feature="place and institution description",claim="Oliver calls the epigraph that opens chapter 13, describing Patience, dry, impersonal and objective by contrast with the personal encounter that follows.",source=OS,url=OU,quote="the dry, impersonal, but objective history beginning the chapter",page="pp. 56-57",date="2022-10",routeHint=OR)
add(feature="omission as information",claim="Oliver notes that the lengthy chapter 13 epigraph about Patience contains no hint of the narrator's own relationship to her.",source=OS,url=OU,quote="This lengthy excerpt contains no hint of the author",page="p. 56",date="2022-10",routeHint=OR,registerHint="dossier-archivist")
add(feature="register modulation",claim="Oliver argues that as Assassin's Apprentice proceeds the epigraphs become increasingly infected by the style of imaginative fiction rather than scholarly discourse.",source=OS,url=OU,quote="the epigraphs become increasingly infected",page="p. 62",date="2022-10",routeHint=OR)
add(feature="register modulation",claim="Oliver names the style that displaces the scholarly register in the late epigraphs as that of imaginative fiction.",source=OS,url=OU,quote="by the style of imaginative fiction in place of the style",page="p. 62",date="2022-10",routeHint=OR)
add(feature="point of view and distance",claim="Oliver identifies chapter 22 of Assassin's Apprentice as an inexplicable narrative intrusion into the epigraphs, the epigraph describing a dream-vision of Fitz's.",source=OS,url=OU,quote="an inexplicable narrative intrusion into the epigraphs",page="p. 62",date="2022-10",routeHint=OR)
add(feature="cadence and rhythm",claim="Oliver identifies chapter 15's epigraph as the best example of the blurring, a poetic lyricism creeping into the narrator's epigraph style.",source=OS,url=OU,quote="a poetic lyricism creeps into his style in the epigraph",page="p. 62",date="2022-10",routeHint=OR)
add(feature="naming and forms of address",claim="Oliver concedes that the chapter epigraphs of Assassin's Apprentice carry no separate attributions and are written by the first-person narrator.",source=OS,url=OU,quote="and have no separate attributions",page="p. 56",date="2022-10",routeHint=OR,polarity="disputes")
EU="https://www.jstor.org/stable/48645160"
ES="Stefan Ekman and Audrey Isabel Taylor, \"Between World and Narrative: Fictional Epigraphs and Critical World-Building\", Journal of the Fantastic in the Arts 32.2 (2021), pp. 245-265"
ER="PDF already on disk at sweep/hobb-acad/ekman-taylor.pdf, text extracted"
add(feature="civic record register",claim="Ekman and Taylor define world-intrinsic epigraphs as epigraphs referring to fictional sources inside a secondary world.",source=ES,url=EU,quote="epigraphs that refer to fictional sources in secondary worlds",page="Abstract",date="2021",routeHint=ER,confidence="medium (the article discusses Le Guin, Jones, McKillip and Brust; it does not discuss Hobb)")
add(feature="place and institution description",claim="Ekman and Taylor give as the second function of world-intrinsic epigraphs the supply of details that extend, explain and familiarise the fictional world.",source=ES,url=EU,quote="give details that extend, explain, and familiarize the fictional world",page="Abstract",date="2021",routeHint=ER,confidence="medium (Hobb is not discussed in the article)")
add(feature="point of view and distance",claim="Ekman and Taylor give as the third function of world-intrinsic epigraphs the provision of perspectives with complementary or conflicting worldviews.",source=ES,url=EU,quote="provide perspectives with complementary or conflicting worldviews",page="Abstract",date="2021",routeHint=ER,confidence="medium (Hobb is not discussed in the article)")
FU="https://elliottrwi.com/research/hobb-bibliography/"
add(feature="civic record register",claim="Elliott's annotated Hobb bibliography summarises Oliver as noting that epigraphs function as ethos-enforcing paratexts.",source="Geoffrey B. Elliott, \"The Fedwren Project: A Robin Hobb Annotated Bibliography\", elliottrwi.com",url=FU,quote="he notes the function of epigraphs as ethos-enforcing paratexts",page="Oliver entry",kind="analysis",date="fetched 2026-09-06",routeHint="curl with browser user agent, HTTP 200",registerHint="none")
add(feature="other: secondary-source scarcity",claim="Elliott's annotated Hobb bibliography lists exactly one entry whose title names the epigraphs of Hobb's novels, Oliver's Mythlore article.",source="Geoffrey B. Elliott, \"The Fedwren Project: A Robin Hobb Annotated Bibliography\", elliottrwi.com",url=FU,quote="",page="entries list",kind="measurement",date="fetched 2026-09-06",routeHint="curl with browser user agent, HTTP 200; grep for 'epigraph' returns 3 hits, 2 of them in the Oliver entry",registerHint="none",confidence="medium (the bibliography's own coverage, not a claim about the literature as a whole)")
OUU="https://jeffreydavidoutcalt.substack.com/p/extra-credit-continued-reading-for"
add(feature="civic record register",claim="A reader-critic writing on Substack points to Ekman and Taylor's article as the second body of work on fictional epigraphs after Oliver's.",source="Jeffrey David Outcalt, \"Extra Credit: Continued Reading for Hobb's Farseer trilogy\", Substack",url=OUU,quote="Between World and Narrative: Fictional Epigraphs and Critical World-Building",page="reading list",kind="reader",date="fetched 2026-09-06",routeHint="curl with browser user agent, HTTP 200",registerHint="none",confidence="medium (a reader's reading list; it misattributes Oliver's first name as Andrew)")
RU="https://rpgstorytellers.com/the-assassins-canvas-a-comprehensive-analysis-of-narrative-interiority-magic-systems-and-cultural-anthropology-in-robin-hobbs-farseer-trilogy/"
add(feature="civic record register",claim="An uncredited content site asserts that every Farseer chapter opens with an in-world snippet ranging from historical treatises and herbalist journals to folklore and political propaganda.",source="RPG StoryTellers (uncredited house byline), \"The Assassin's Canvas\"",url=RU,quote="a snippet of in-world text ranging from historical treatises and herbalist journals",page="section 2.2",kind="analysis",polarity="asserts",date="fetched 2026-09-06",routeHint="curl with browser user agent, HTTP 200",registerHint="none",confidence="low (house byline with no named author and machine-generated cadence; the census of Elliott's 100 Farseer entries records 0 journals and 0 herbals, and only 2 treatises in all 314 entries, so this claim is not corroborated)")
json.dump(C,open("claims_part2.json","w"),indent=1); print(len(C))
