# -*- coding: utf-8 -*-
import json
src=json.load(open('chunks/ai-01.json'))
claims=src['claims']
V=[
 (210,"VERIFIED_VERBATIM","trends toward overly positive or uninspired endings",
  "arXiv 2509.04239 (Valdivia & Burelli). Quote exact in Sec. I: 'with some studies identifying trends toward overly positive or uninspired endings [13], or uneven output quality across sessions [14]'. 'unconvincing, repetitive, or misaligned with the desired tone' is also verbatim earlier in Sec. I. Wrong genre is Sec. V-A: 'producing a hard-boiled detective story when a fantasy narrative is requested, was identified as a significant quality failure' -- genre alignment is a 'must-be' requirement. CAVEAT ON ATTRIBUTION: only the genre item comes from the n=10 Delphi expert panel; the endings/uneven-quality items are the paper citing prior studies [13][14], and 'unconvincing, repetitive' is the authors' own intro framing. Cite the four items as documented failures, not as one expert list."),
 (211,"VERIFIED_VERBATIM","game design and narrative (63 percent) hold the most unfavorable views",
  "Game Developer on the 2026 State of the Game Industry report, 'based on responses from over 2,300 industry professionals'. Both figures exact: 'Workers in visual and technical art (64 percent), game design and narrative (63 percent), and game programming (59 percent) hold the most unfavorable views' about generative AI 'having a negative impact'; and 'About 7 percent of them expressed that view, which is down from 13 percent in 2025.' Quote verbatim from a senior US-based respondent. Context worth carrying: the industry-wide negative figure is 52 percent, not 63."),
 (212,"VERIFIED_VERBATIM","the most ordinary, middle-of-the-road adventure text you could possibly get",
  "H. Tucker Cobey, Epic Table Games, 'Last updated: July 24, 2023'. Quote verbatim. The ceiling half of the claim is the next sentence, also verbatim: 'while there's a very real floor to the quality level of the text you get, there's just as much of a ceiling.' The lead-in is 'this just means that you're gonna get the most average text possible.' Page flags the passage as the author's personal opinion, not Epic Table Games policy."),
 (213,"VERIFIED_SUBSTANCE","made of 'primarily' of AI-generated writing will not be allowed",
  "NOT VERBATIM: 'language generators' appears zero times in the fetched HTML (grep -c = 0). The EN World thread (Jul 25, 2023) reports the policy as: 'starting on July 31, any content that is made of \"primarily\" of AI-generated writing will not be allowed.' Everything else in the claim is confirmed on the page -- DMs Guild plus the DriveThru Marketplaces; the 2023-07-31 effective date (thread dated Jul 25, 2023); and tagged AI art allowed: 'AI-generated art is permitted for use in rulebooks and adventures, but it must be tagged as such.' The quoted phrase may be OneBookShelf's own policy-page wording, but it is not on the cited URL -- requote or recite."),
 (214,"VERIFIED_VERBATIM","we don't use AI to generate text for our game design",
  "Wolfgang Baur, Kobold Press CEO. Quote verbatim inside the fuller sentence: 'We don't use generative AI art, we don't use AI to generate text for our game design, and we don't believe that AI is magical pixie dust that makes your tabletop games better.' The chatbots-versus-friends framing is verbatim too: 'we've seen LLM text prompts work ok for chatbots. But we play RPGs to play with our friends, not software.'"),
 (215,"VERIFIED_VERBATIM","describe algorithmic generation as the 'exact opposite of inspiration'",
  "Geeknative roundup by Andrew Girdwood, January 15, 2026. Quote verbatim; all six named publishers are on the page with bans on AI text and/or art (Free League's stated policy is against AI ART specifically). CAVEAT: 'ethics and livelihood grounds' is explicit for only two entries -- Free League 'citing ethical concerns regarding the livelihoods of professional illustrators' and Three Sale Studios 'considering it unethical'; Paizo, Chaosium, WotC, Renegade and Stonemaier are listed with policy content but no stated grounds, and the ethics framing otherwise comes from the article's intro and closing. 'Only Monte Cook Games gives a quality verdict' holds across the roster, though the intro separately credits Games Workshop with positioning 'human-made craftsmanship as the ultimate luxury'."),
 (216,"VERIFIED_VERBATIM","it isn't getting any better, it's been at the same level for three years",
  "EN World thread 'AI is destroying crowdfunding', post by Agamon dated Aug 25, 2026. Quote verbatim: 'Art, music, and I'm getting good at catching AI writing now, too. And it isn't getting any better, it's been at the same level for three years.' The second half of the claim is the same poster's earlier post: any product with 'that \"AI slop\" look to it may be instantly ignored, even when human artists are being used... I need to be very careful about art styles and anything that may trigger the AI \"spidey sense\".' Note that fear is voiced about ART styles specifically, not prose."),
 (217,"VERIFIED_VERBATIM","Grok had been generating outlines from the same foundational documents",
  "Jon Del Arroz, AI Central, Mar 16, 2026. All three quoted fragments verbatim: 'was producing repetitive story beats'; 'the prose has that particular quality of competent but slightly mechanical writing that characterizes current LLM output'; 'The occasional \"not X but Y\" construction.' Mechanism is as claimed -- Claude flagged book two's outline as too similar to book one because Grok drew from the same foundational documents. Source is a self-reported experiment by an author selling the resulting books."),
 (218,"VERIFIED_SUBSTANCE","an AI prompt asking for a rewrite in another author's voice",
  "No quote was supplied with the claim, so no verbatim test is possible; the substance checks out. Book Riot (Jun 30, 2025): 'an AI prompt asking for a rewrite in another author's voice was accidentally left in the published version of Darkhollow Academy: Year 2, a reverse harem romance by Lena McDonald', sourced to Reddit users and Futurism. Disclosure half verbatim: 'While there is a requirement to disclose AI usage to Kindle, that disclosure is not made to users.' TWO GAPS: the page never states the book's own publication date (June 2025 is the ARTICLE's date), and it never says this specific title is in Kindle Unlimited -- KU is the article's frame."),
 (219,"VERIFIED_VERBATIM","stereotypical patterns at a frequency that is usually only seen in AI slop",
  "Goodreads Listopia 'Obviously AI-generated (296 books)' -- the count is in the page title. Quote verbatim in the list description: 'well-established frequent common denominators in AI books, including use of AI image generators and stereotypical text patterns; these are the basis for identifying a book as AI generated or \"AI slop.\"' The claim's 'at slop-level frequency' is also near-verbatim from the closing line: 'if your book reproduces stereotypical patterns at a frequency that is usually only seen in AI slop'. 296 is a live user-voted count and will drift."),
 (220,"VERIFIED_VERBATIM","a 'vibe' that the story felt artificial",
  "Outlook Respawn, Krishna Goswami, 15 Dec 2025. Quote verbatim. Shrine's Legacy by Positive Concept Games; devs state they 'worked exclusively with human talent for everything from writing to coding' and 'do not endorse generative AI and will never use it'. Page supplies the false-positive frame directly: 'A 2024 Microsoft study found that users can correctly identify AI-generated content only about 62% of the time, suggesting that \"gut feelings\" about art or dialogue are frequently wrong.' Precision note: the ChatGPT accusation came from one 'belligerent review' saying the narrative was 'made in ChatGPT'; the felt-artificial vibe is from OTHER reviews, so 'because' overstates a single causal chain."),
 (221,"VERIFIED_VERBATIM","I haven't seen any hard evidence that chatbots use more em dashes",
  "The Ringer, Brian Phillips, Aug. 20, 2025. Quote verbatim. First half of the claim verbatim too: 'I haven't seen any hard evidence that chatbots, in practice, use more em dashes than anyone else.' Training half: 'If generative AI does have a predilection for em dashes, though, the reason is simply that many human writers use em dashes'; 'all the material they were fed was the work of human writers, and much of it was the work of professionals.' Small precision: the page says 'than anyone else', not 'than professional human writers'."),
 (222,"VERIFIED_VERBATIM","Later editors put the dashes back -- because they weren't accidents",
  "Focus Lab, Nadine Kavanaugh, February 9, 2026, 'The Em Dash Is Not an AI Tell'. Quote verbatim. Dickinson history verbatim: 'She littered her poems with bold dashes. Her original publishers hated them; they scrubbed her poems clean... Later editors put the dashes back -- because they weren't accidents. They were architecture.' Tool-versus-intent half is the Dickinson coda: her editors 'mistook unfamiliar form for flawed thinking... the dash wasn't excess. It was intention.' Page calls Dickinson 'the patron saint of the em dash' rather than saying it was her signature mark."),
 (223,"VERIFIED_SUBSTANCE","the em dash still far outstrips the semi-colon and the exclamation mark",
  "SALT.agency, Sarah Mitchell, January 29, 2026. The supplied quote IS on the page word for word, but it supports a DIFFERENT point (detector unreliability), not the Ngram claim -- so it cannot be cited as evidence for this claim. The Ngram substance is on the page: a 'Google Books Ngram graph comparing the frequencies of the em dash (in blue), semi-colon (red) and exclamation point (green) in books published between 1500 and 2022', plus 'precious little evidence that ChatGPT does use the em dash too frequently; or at least more frequently than the average professional writer' and the training-data argument about professionally edited pre-internet text. CONTRADICTS 'stayed high for centuries': the page states 'the frequency in usage of the em dash does drop away after the mid-'90s' -- what survives is relative dominance, not a flat curve. Re-cut the claim to the dominance wording."),
 (224,"VERIFIED_VERBATIM","they are so ubiquitous in AP lingo, we just call them dashes",
  "Robert Roy Britt, The Writer's Guide, Jul 28, 2026, 'AI's Assault on the Em Dash Should Worry All Writers'. Quote verbatim ('You see, em dashes aren't the problem.' and again later). AP attribution exact: Anna Jo Bratton, editor of the Associated Press Stylebook -- 'that tell is not the em dash, which has been around for many years. In fact, they are so ubiquitous in AP lingo, we just call them dashes.' Feedback loop is set out explicitly as 'the inane circular logic in four simple steps' ending 'Human writers stop using em dashes', with 'If we let AI tell us how to write... we've entered a linguistic looking glass'."),
]
assert len(V)==15
idx=[c['index'] for c in claims]
assert idx==[v[0] for v in V], (idx,[v[0] for v in V])
out={'name':'ai','chunk':7,'claims':claims,
     'verdicts':[{'index':i,'verdict':v,'trueWording':t,'note':n} for i,v,t,n in V]}
p='verdicts-ai-i210-224.json'
json.dump(out,open(p,'w'),ensure_ascii=False,indent=1)
print('wrote',p)
d=json.load(open(p))
print('reread ok: claims=%d verdicts=%d'%(len(d['claims']),len(d['verdicts'])))
from collections import Counter
print(Counter(x['verdict'] for x in d['verdicts']))
print('indices:',[x['index'] for x in d['verdicts']])
