import { pathToFileURL } from 'node:url'; import path from 'node:path';
const DOCK='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/skepINSTR';
const m=await import(pathToFileURL(path.join(DOCK,'src/data/institutionServices.js')).href);
const names=new Set();
for(const inst of Object.values(m.INSTITUTION_SERVICES)) for(const k of Object.keys(inst)) names.add(k);
const NOW=/\b(tithe|dues|tax|taxation|toll|customs|custom commissions?|record keeping|records?|register|registration|census|levy|muster|rolls?)\b/i;
const WITHCUSTOM=/\b(tithe|dues|tax|taxation|toll|customs|custom|custom commissions?|record keeping|records?|register|registration|census|levy|muster|rolls?)\b/i;
const now=[...names].filter(n=>NOW.test(n)).sort();
const old=[...names].filter(n=>WITHCUSTOM.test(n)).sort();
console.log('MENU distinct service names:', names.size);
console.log('admitted NOW ('+now.length+'):'); now.forEach(n=>console.log('   '+n));
console.log('dropped by removing bare `custom` ('+old.filter(n=>!now.includes(n)).length+'):');
old.filter(n=>!now.includes(n)).forEach(n=>console.log('   '+n));
console.log('names containing "custom" (any case):', [...names].filter(n=>/custom/i.test(n)).sort().join(' · '));
