# -*- coding: utf-8 -*-
def C(**k): return k
W="https://locusmag.com/review/gary-k-wolfe-reviews-a-brightness-long-ago-by-guy-gavriel-kay/"
E="https://elitistbookreviews.com/2019/05/14/a-brightness-long-ago/"
H="https://historicalnovelsociety.org/reviews/a-brightness-long-ago/"
F="https://fantasy-faction.com/2011/the-world-of-guy-gavriel-kay"
S="https://www.salonfutura.net/2025/04/written-on-the-dark/"
G="https://gregcookland.com/wonderland/2019/04/28/guy-gavriel-kay/"
B="https://bookwormex.com/brightness-long-ago-guy-gavriel-kay-review/"
CLAIMS=[
# --- Gary K. Wolfe, Locus, May 2019
C(file="locuswolfe-brightness", feature="point of view and distance",
  claim="Gary K. Wolfe writes that A Brightness Long Ago carries a further narrative voice that is almost invisible for most of the tale.",
  source="Gary K. Wolfe, Locus, May 2019, review of A Brightness Long Ago", url=W,
  quote="another narrative voice, almost invisible for most of the tale",
  page="paragraph beginning 'While Kay occasionally shifts'", kind="analysis", polarity="asserts", date="2019-05",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="locuswolfe-brightness", feature="point of view and distance",
  claim="Wolfe compares that half-hidden voice to the framing seaman who relays Marlow's tale in Conrad's Heart of Darkness.",
  source="Gary K. Wolfe, Locus, May 2019", url=W,
  quote="this mysterious voice reminded me of nothing so much as Conrad’s",
  page="paragraph beginning 'While Kay occasionally shifts'", kind="analysis", polarity="asserts", date="2019-05",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="locuswolfe-brightness", feature="other: design and shaping",
  claim="Wolfe reports Kay's distinction that stories are told but novels are shaped.",
  source="Gary K. Wolfe, Locus, May 2019", url=W,
  quote="Stories, he reminds us, are told, but novels are shaped.",
  page="final paragraph", kind="analysis", polarity="asserts", date="2019-05",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="locuswolfe-brightness", feature="register modulation",
  claim="Wolfe writes that Kay is a master at reminding readers that past world views differed from ours as much as past worlds did.",
  source="Gary K. Wolfe, Locus, May 2019", url=W,
  quote="past world views were as different from ours as past worlds",
  page="paragraph beginning 'Kay, of course, is a master'", kind="analysis", polarity="asserts", date="2019-05",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="locuswolfe-brightness", feature="plainness and economy",
  claim="Wolfe writes that Kay renders battle pageants and sieges with extraordinary clarity.",
  source="Gary K. Wolfe, Locus, May 2019", url=W,
  quote="of the sort Kay writes with extraordinary clarity",
  page="paragraph beginning 'Kay then shifts the point of view'", kind="analysis", polarity="asserts", date="2019-05",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="locuswolfe-brightness", feature="point of view and distance",
  claim="Wolfe calls the novel as elegantly polyphonic as ever.",
  source="Gary K. Wolfe, Locus, May 2019", url=W,
  quote="as elegantly polyphonic as ever",
  page="paragraph beginning 'Kay, of course, is a master'", kind="analysis", polarity="asserts", date="2019-05",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# --- Elitist Book Reviews, 14 May 2019
C(file="elitist", feature="point of view and distance",
  claim="Elitist Book Reviews notes that first person is rare in adult speculative fiction because it demands a sustained character voice and limits context.",
  source="Elitist Book Reviews, review of A Brightness Long Ago, 14 May 2019", url=E,
  quote="it requires a sustained character voice and doesn’t allow a lot",
  page="paragraph beginning 'Danio’s reflections are the major POV'", kind="analysis", polarity="asserts", date="2019-05-14",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="elitist", feature="point of view and distance",
  claim="The reviewer likens Danio's first-person perspective to a Browning-style dramatic monologue.",
  source="Elitist Book Reviews, 14 May 2019", url=E,
  quote="reminded me of a Browning-style dramatic monologue",
  page="paragraph beginning 'Danio’s reflections are the major POV'", kind="analysis", polarity="asserts", date="2019-05-14",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="elitist", feature="per-speaker register",
  claim="The reviewer notes that Kay's other viewpoints are in third person and so read as immediately distinct from Danio's first-person musings.",
  source="Elitist Book Reviews, 14 May 2019", url=E,
  quote="these are presented in third person, so they are immediately distinct",
  page="paragraph beginning 'Danio’s reflections are the major POV'", kind="analysis", polarity="asserts", date="2019-05-14",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="elitist", feature="other: counter-reception of the register",
  claim="The reviewer, a self-described completist fan, says Kay's books tend towards a certain sameness.",
  source="Elitist Book Reviews, 14 May 2019", url=E,
  quote="his books tend towards a certain… sameness",
  page="paragraph beginning 'Even as a fan'", kind="analysis", polarity="disputes", date="2019-05-14",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="elitist", feature="other: counter-reception of the register",
  claim="The reviewer lists the recurring archetypes Kay works with as the poet, the warrior, the artist, the lover and the priest.",
  source="Elitist Book Reviews, 14 May 2019", url=E,
  quote="He works with archetypes — the poet, the warrior, the artist",
  page="paragraph beginning 'Even as a fan'", kind="analysis", polarity="disputes", date="2019-05-14",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# --- Judith Starkston, Historical Novel Society, 1 May 2019
C(file="hns-brightness", feature="point of view and distance",
  claim="Judith Starkston writes that Danio narrates in first person as an old man looking back and carries the main job of pulling the reader in.",
  source="Judith Starkston (novelist), Historical Novel Society review of A Brightness Long Ago, 1 May 2019", url=H,
  quote="Danio, as an old man looking back in first person, carries",
  page="final paragraph of the review", kind="analysis", polarity="asserts", date="2019-05-01",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="hns-brightness", feature="point of view and distance",
  claim="Starkston writes that Kay also places the reader in a series of close-third narrators without creating confusion.",
  source="Judith Starkston, Historical Novel Society, 1 May 2019", url=H,
  quote="a series of close-third narrators without creating any confusion",
  page="final paragraph of the review", kind="analysis", polarity="asserts", date="2019-05-01",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="hns-brightness", feature="naming and forms of address",
  claim="Starkston writes that Kay shifts the names of cities and famous people while retaining the qualities that identify them.",
  source="Judith Starkston, Historical Novel Society, 1 May 2019", url=H,
  quote="but the qualities that identify them are retained",
  page="first paragraph of the review", kind="analysis", polarity="asserts", date="2019-05-01",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),

# --- Fantasy-Faction, 2011
C(file="ffworld", feature="metaphor discipline",
  claim="Fantasy-Faction writes that Kay's writing is lyrical without being flowery.",
  source="Fantasy-Faction, 'The World of Guy Gavriel Kay', 2011", url=F,
  quote="His writing is lyrical without being flowery.",
  page="paragraph beginning 'In spite of frequently hitting Canada’s bestseller lists'", kind="reception", polarity="asserts", date="2011",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="ffworld", feature="cadence and rhythm",
  claim="The Fantasy-Faction writer reports pausing while reading Under Heaven to savour a crafted sentence or metaphor.",
  source="Fantasy-Faction, 'The World of Guy Gavriel Kay', 2011", url=F,
  quote="I often paused simply to savor a beautifully crafted sentence or",
  page="paragraph beginning 'In spite of frequently hitting Canada’s bestseller lists'", kind="reader", polarity="asserts", date="2011",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# --- Cheryl Morgan, Salon Futura, April 2025
C(file="salonfutura", feature="other: episodic structure",
  claim="Salon Futura describes Written on the Dark as a series of vignettes from Thierry's life rather than a unifying plot.",
  source="Salon Futura, review of Written on the Dark, April 2025", url=S,
  quote="a series of vignettes – key moments from Thierry’s life that",
  page="paragraph beginning 'The other thing I should note'", kind="analysis", polarity="asserts", date="2025-04",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),

# --- Greg Cook, Wonderland, 28 April 2019 (Kay own words)
C(file="wonderland", feature="other: revision method",
  claim="Kay says the Silmarillion year taught him that a bad draft was not a death sentence to a work.",
  source="Guy Gavriel Kay, interviewed by Greg Cook for Wonderland, 28 April 2019", url=G,
  quote="a bad draft was not a death sentence to a work",
  page="answer to the first question, on Tolkien", kind="own-words", polarity="asserts", date="2019-04-28",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# --- Bookwormex
C(file="bookwormex", feature="point of view and distance",
  claim="Bookwormex writes that no character in A Brightness Long Ago feels like a throwaway.",
  source="Bookwormex, review of A Brightness Long Ago", url=B,
  quote="Nobody feels like a throwaway character, all of them successfully humanized",
  page="review body", kind="reception", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
]
