# -*- coding: utf-8 -*-
BW="https://brightweavings.com/"
def C(**k): return k
CLAIMS=[
# ===== Richard Marcus / Leap in the Dark interview (Kay own words), Ysabel era (2007)
C(file="bw-leapdark", feature="cadence and rhythm",
  claim="Kay says he used mythic, Biblical cadences in the Fionavar books to reach for an operatic effect.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus for 'Leap in the Dark', reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="I used mythic, Biblical cadences to try to achieve that",
  page="answer to question 6", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-leapdark", feature="register modulation",
  claim="Kay says the language of his later books has varied because he fits it to the setting.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="The language in the later books has varied as I try",
  page="answer to question 6", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-leapdark", feature="diction (native vs latinate)",
  claim="Kay describes the language of The Last Light of the Sun as harder, terser and less lyric than his earlier books.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="is harder, terser, less lyric than the books before",
  page="answer to question 6", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-leapdark", feature="annalist voice and deep time",
  claim="Kay lists the historian-writer's power to shape later understanding of a period's leaders among the things that drew him to Byzantium.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="The power of the historian/writer to shape later understanding of even",
  page="answer to question 4", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-leapdark", feature="consequence on a household",
  claim="Kay names the way the deeds of the great can feel trivial to people facing their own calamities as one of his subjects.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="the deeds of the ‘great’ can feel trivial to those going",
  page="answer to question 4", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-leapdark", feature="naming and forms of address",
  claim="Kay cites the fairy-tale formula naming a person only by trade and relation as what links every listener to the story.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="the only daughter of a fisherman walked down to the strand",
  page="answer to question 12", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-leapdark", feature="point of view and distance",
  claim="Kay says folktales work by erasing the distance between listener and story.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="erasing the distance between reader/listener and story",
  page="answer to question 12", kind="own-words", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-leapdark", feature="other: influence and imitation",
  claim="Kay denies that his language is a linguistic attempt to echo any other writer.",
  source="Guy Gavriel Kay, interviewed by Richard Marcus, reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="Certainly not a linguistic attempt to echo anyone else.",
  page="answer to question 6", kind="own-words", polarity="rejects", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-leapdark", feature="other: reception of the prose",
  claim="Interviewer Richard Marcus describes Kay's language as having an almost opulence that elevates events above the mundane.",
  source="Richard Marcus (interviewer), 'Leap in the Dark', reproduced at BrightWeavings",
  url=BW+"leapinthedark/", quote="the almost opulence of your language",
  page="question 6", kind="analysis", polarity="asserts", date="2007",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# ===== Peter Halasz / NYRSF interview 2000 (Kay own words)
C(file="bw-halasz", feature="register modulation",
  claim="Kay says he worries that the diction, style and rhythms of the last book will bleed into the next.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz for the New York Review of Science Fiction, 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="the last book will bleed into the next one, the diction",
  page="answer on script writing as a bridge between books", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-halasz", feature="register modulation",
  claim="Kay states that the writing changes in every book.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="the writing changes in every book",
  page="answer on style and tone changing between books", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-halasz", feature="opening sentence",
  claim="Kay says the prologue of Sailing to Sarantium was written as contrasting tiles, one a charioteer and one a senator.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="a strong “tile” of a charioteer, a strong “tile” of a",
  page="answer on the prologue as mosaic", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-halasz", feature="other: contrast rather than blending",
  claim="Kay says the mosaic form does not blend colours but contrasts them so blending appears only at a distance.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="you don’t blend colours – you contrast them to form an",
  page="answer on the prologue as mosaic", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-halasz", feature="register modulation",
  claim="Kay says the style of Sailing to Sarantium was influenced by its protagonist being a mosaicist.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="The style of this book, is influenced by the metaphor and",
  page="answer on the prologue as mosaic", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-halasz", feature="civic record register",
  claim="Kay says the formal brief lives of two troubadours frame A Song for Arbonne to signal that the whole book is a song.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="The formal, brief lives of the two troubadours at the beginning",
  page="answer on style and tone changing between books", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-halasz", feature="other: elegiac register",
  claim="Kay says The Lions of Al-Rassan is elegiac because it is about the demise of a civilisation.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="Lions is elegiac in nature because it is really, as much",
  page="answer on style and tone changing between books", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-halasz", feature="concrete sensory noun",
  claim="Kay says details are critical, and describes asking of each drafted scene what details it needs.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="Details are critical.",
  page="answer on layering up a scene", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-halasz", feature="other: revision method",
  claim="Kay says a scene is layered up sometimes ten or fifteen times.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="sometimes ten or fifteen times for a scene",
  page="answer on layering up a scene", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-halasz", feature="omission as information",
  claim="Kay says Sailing to Sarantium ends with things left just offstage that the reader knows will happen.",
  source="Guy Gavriel Kay, interviewed by Peter Halasz, NYRSF 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="There are other things, just offstage, that the reader knows will",
  page="answer on the splitting of the diptych", kind="own-words", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-halasz", feature="diction (native vs latinate)",
  claim="Interviewer Peter Halasz characterises Kay's writing as showing a punctilious choice of word and image.",
  source="Peter Halasz (interviewer), New York Review of Science Fiction, 2000, reproduced at BrightWeavings",
  url=BW+"nyrsf_halasz/", quote="the punctilious choice of word and image",
  page="question preceding the answer on rewriting", kind="analysis", polarity="asserts", date="2000",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# ===== Jean-Louis Trudel / Solaris 1995 (Kay own words)
C(file="bw-trudel", feature="withheld information and inference",
  claim="Kay says he wants a book's themes to register from underneath, slipping in beneath the narrative flow.",
  source="Guy Gavriel Kay, interviewed by Jean-Louis Trudel for Solaris (Quebec), 1995, reproduced at BrightWeavings",
  url=BW+"trudel/", quote="to have them slip in, behind or beneath the page-turning narrative",
  page="answer on storytelling, narrative and character", kind="own-words", polarity="asserts", date="1995",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-trudel", feature="other: no authorial gloss",
  claim="Kay says he dislikes books where he feels hammered on the head with the author's didactic point.",
  source="Guy Gavriel Kay, interviewed by Jean-Louis Trudel, Solaris 1995, reproduced at BrightWeavings",
  url=BW+"trudel/", quote="hammered on the head with the author’s didactic or pedantic point",
  page="answer on storytelling, narrative and character", kind="own-words", polarity="rejects", date="1995",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-trudel", feature="withheld information and inference",
  claim="Kay says he likes books where the point slips in quietly and tries to write that kind.",
  source="Guy Gavriel Kay, interviewed by Jean-Louis Trudel, Solaris 1995, reproduced at BrightWeavings",
  url=BW+"trudel/", quote="I like books where the point slips in quietly.",
  page="answer on storytelling, narrative and character", kind="own-words", polarity="asserts", date="1995",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-trudel", feature="cadence and rhythm",
  claim="Kay says he worked through Dante in Italian to get a sense of the rhythms of that language.",
  source="Guy Gavriel Kay, interviewed by Jean-Louis Trudel, Solaris 1995, reproduced at BrightWeavings",
  url=BW+"trudel/", quote="a sense of what the rhythms in Italian were",
  page="answer on languages and Provence", kind="own-words", polarity="asserts", date="1995",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-trudel", feature="other: allusive ambience",
  claim="Kay says he expected readers to miss his specific myth sources and hoped only that a mythic ambience would emerge.",
  source="Guy Gavriel Kay, interviewed by Jean-Louis Trudel, Solaris 1995, reproduced at BrightWeavings",
  url=BW+"trudel/", quote="an ambience, a generally mythic flavour and realm would emerge",
  page="answer on Tolkien and mythic sources", kind="own-words", polarity="asserts", date="1995",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# ===== Dictionary of Imaginary Places entry (gazetteer register applied to Kay's world)
C(file="bw-dictionary", feature="civic record register",
  claim="The Dictionary of Imaginary Places entry glosses Fionavar as a land of undetermined location.",
  source="Alberto Manguel and Gianni Guadalupi, The Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="a land of undetermined location",
  page="first line of the entry", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="civic record register",
  claim="The entry attributes a built work to a named maker and a named reign inside a parenthesis.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="(designed by the gifted T’Varen in the reign of Thallason)",
  page="paragraph on Cathal and Larai Rigal", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="civic record register",
  claim="The entry states access to a sacred site as an administrative fact rather than a scene.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="Access to the Godwood and the tree is strictly controlled",
  page="paragraph on the Mornirwood", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="annalist voice and deep time",
  claim="The entry declares the region's prehistory hazy rather than narrating it.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="Fionavar’s prehistory is hazy.",
  page="paragraph beginning 'Fionavar’s prehistory'", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="annalist voice and deep time",
  claim="The entry records an unresolved dispute about which race came first instead of settling it.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="it is a matter of some dispute which race came first",
  page="paragraph beginning 'Fionavar’s prehistory'", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="omission as information",
  claim="The entry notes that the only two visitors to a place have given no account of what they saw.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="neither has offered an account of what they saw there",
  page="paragraph on the Dwarves and Calor Diman", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="civic record register",
  claim="The entry hedges a change in conditions as an unconfirmed report and advises accordingly.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="There have been reports of a lessening of this sentient forest’s",
  page="paragraph on Pendaran Wood", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-dictionary", feature="edition and house style",
  claim="The entry closes with a parenthetical source list naming the three novels with city and year.",
  source="Manguel and Guadalupi, Dictionary of Imaginary Places, entry on Fionavar, reprinted at BrightWeavings",
  url=BW+"dictionary/", quote="(Guy Gavriel Kay, The Summer Tree, Toronto, 1984;",
  page="closing line of the entry", kind="analysis", polarity="applies", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),

# ===== Bill Capossere, Fantasy Literature (Children of Earth and Sky)
C(file="bw-capossere", feature="civic record register",
  claim="The passage Capossere quotes states the Rector's Council's membership in the present tense as of that morning.",
  source="Guy Gavriel Kay, Children of Earth and Sky, quoted by Bill Capossere for Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="There are sixty-five members of the Rector’s Council as of this",
  page="block quotation following 'we shift immediately into a wholly different voice'",
  kind="analysis", polarity="applies", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="civic record register",
  claim="The same quoted passage enumerates the other councils and committees that govern the city-state.",
  source="Guy Gavriel Kay, Children of Earth and Sky, quoted by Bill Capossere, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="There are other councils and committees governing Dubrava, smaller groups for",
  page="block quotation of the Council passage",
  kind="analysis", polarity="applies", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="place and institution description",
  claim="The quoted passage lists the city's business, from quarantine against plague to arranging a widow's remarriage.",
  source="Guy Gavriel Kay, Children of Earth and Sky, quoted by Bill Capossere, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="from quarantining some visitors against the arrival of the plague to",
  page="block quotation of the Council passage",
  kind="analysis", polarity="applies", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="register modulation",
  claim="Capossere writes that entering the Council chamber shifts the novel immediately into a wholly different voice and tone.",
  source="Bill Capossere, Fantasy Literature, review of Children of Earth and Sky, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="we shift immediately into a wholly different voice and tone",
  page="paragraph beginning 'Stylistically, there are few authors'",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="civic record register",
  claim="Capossere writes that the passage runs for several pages using passive voice to report civic facts such as the Rector's Palace being rebuilt twice.",
  source="Bill Capossere, Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="often employing passive voice, as we’re informed that the Rector’s Palace",
  page="paragraph following the block quotation",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="annalist voice and deep time",
  claim="Capossere writes that the omniscient voice sometimes intrudes to say what became of a character years later.",
  source="Bill Capossere, Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="let us know what happened to this or that particular character",
  page="paragraph following the block quotation",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-capossere", feature="consequence on a household",
  claim="Capossere writes that Kay moves the reader between the grand scope of history and grounded domestic detail.",
  source="Bill Capossere, Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="between grand scope of history and the more grounded domestic detail",
  page="paragraph beginning 'Stylistically, there are few authors'",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="point of view and distance",
  claim="Capossere writes that Kay achieves the shift of scale by switching tenses or by intruding into the narrative.",
  source="Bill Capossere, Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="by switching tenses or by intruding more forcefully into the narrative",
  page="paragraph beginning 'Stylistically, there are few authors'",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="register modulation",
  claim="Capossere writes that Kay's prose is always under control and shifts as needed.",
  source="Bill Capossere, Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="The prose is always under control, shifting as needed, often lyrical",
  page="paragraph beginning 'Stylistically, there are few authors'",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="withheld information and inference",
  claim="Capossere writes that the characters' personalities are often revealed by little things.",
  source="Bill Capossere, Fantasy Literature, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="their personalities often revealed by little things",
  page="paragraph introducing Marin and the harbour procession",
  kind="analysis", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-capossere", feature="repetition and refrain",
  claim="The line Capossere quotes repeats the phrase 'Small things' as its own sentence.",
  source="Guy Gavriel Kay, Children of Earth and Sky, quoted by Bill Capossere, reproduced at BrightWeavings",
  url=BW+"review-by-bill-capossere-for-fantasy-literature/",
  quote="Small things. Small things you do to not be the same",
  page="block quotation on Marin at the harbour",
  kind="analysis", polarity="applies", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="herald-pools", confidence="high"),

# ===== Desi Stern, Petrichor Machine (River of Stars)
C(file="bw-stern", feature="point of view and distance",
  claim="Desi Stern describes the River of Stars narrator as a third person omniscient voice that first seems distant and quiet.",
  source="Desi Stern, Petrichor Machine, review of River of Stars, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="a third person, omniscient narrator, which at first blush seems distant",
  page="paragraph beginning 'The narrator in River of Stars'",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-stern", feature="annalist voice and deep time",
  claim="Stern writes that the narrator manages to be omniscient and unreliable at once.",
  source="Desi Stern, Petrichor Machine, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="it manages to be omniscient and unreliable at once",
  page="paragraph beginning 'The narrator in River of Stars'",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-stern", feature="annalist voice and deep time",
  claim="Stern writes that the narration undermines itself by questioning whether history as fact matches the history told.",
  source="Desi Stern, Petrichor Machine, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="The narration often undermines itself, questioning whether or not history",
  page="paragraph beginning 'The narrator in River of Stars'",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
C(file="bw-stern", feature="plainness and economy",
  claim="Stern writes that the narrative voice uses a quiet, restrained expression of emotional and poignant things.",
  source="Desi Stern, Petrichor Machine, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="using a quiet, restrained expression of things emotional and poignant",
  page="paragraph beginning 'The narrative voice is also reflective'",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-stern", feature="per-speaker register",
  claim="Stern writes that Kay chooses tense according to which character the novel is following.",
  source="Desi Stern, Petrichor Machine, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="his choice of tense, depending on which character the novel is",
  page="paragraph beginning 'Another way that Kay’s mastery of craft'",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-stern", feature="per-speaker register",
  claim="Stern reports that most sections of River of Stars are past tense while the sections following Shan are present tense.",
  source="Desi Stern, Petrichor Machine, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="Most sections are written in the past tense, except for those",
  page="paragraph beginning 'Most sections are written'",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-stern", feature="per-speaker register",
  claim="Stern reports one scene where a male character's narration shifts to present tense.",
  source="Desi Stern, Petrichor Machine, reproduced at BrightWeavings",
  url=BW+"review-by-desi-stern-for-petrichor-machine/",
  quote="his narration shifts to present tense for the scene",
  page="parenthetical paragraph after the discussion of Shan",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),

# ===== Natalie Zina Walschots, National Post (River of Stars)
C(file="bw-walschots", feature="diction (native vs latinate)",
  claim="Natalie Zina Walschots describes the language of River of Stars as formal and poetic.",
  source="Natalie Zina Walschots, National Post, review of River of Stars, reproduced at BrightWeavings",
  url=BW+"review-by-natalie-zina-walschots-for-national-post/",
  quote="The language in River of Stars is formal and poetic",
  page="paragraph beginning 'The language in River of Stars'",
  kind="analysis", polarity="asserts", date="2013",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-walschots", feature="sentence length variation",
  claim="Walschots describes Kay's sentences as laid out like layers of diaphanous fabric.",
  source="Natalie Zina Walschots, National Post, reproduced at BrightWeavings",
  url=BW+"review-by-natalie-zina-walschots-for-national-post/",
  quote="the sentences laid out like layers of diaphanous fabric",
  page="paragraph beginning 'The language in River of Stars'",
  kind="analysis", polarity="asserts", date="2013",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-walschots", feature="register modulation",
  claim="Walschots writes that even in moments of violence Kay's prose stays cool and collected.",
  source="Natalie Zina Walschots, National Post, reproduced at BrightWeavings",
  url=BW+"review-by-natalie-zina-walschots-for-national-post/",
  quote="the prose is always cool and collected",
  page="paragraph beginning 'The language in River of Stars'",
  kind="analysis", polarity="asserts", date="2013",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),

# ===== Ilana Teitelbaum, Huffington Post
C(file="bw-teitelbaum", feature="cadence and rhythm",
  claim="Ilana Teitelbaum writes that each sentence seems shaped to enhance the book's themes.",
  source="Ilana Teitelbaum, Huffington Post, review reproduced at BrightWeavings",
  url=BW+"review-by-ilana-teitelbaum-for-huffington-post/",
  quote="each sentence seems shaped to further enhance the book’s themes",
  page="paragraph on craftsmanship and the peony blossom",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# ===== Locus (Gary K. Wolfe) on Children of Earth and Sky
C(file="bw-locuschildren", feature="plainness and economy",
  claim="The Locus review calls Kay's use of supernatural elements deliberately and tactically restrained.",
  source="Locus review of Children of Earth and Sky, reproduced at BrightWeavings",
  url=BW+"children-review-by-locus/",
  quote="deliberately, even tactically, restrained",
  page="paragraph on supernatural elements",
  kind="reception", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-locuschildren", feature="point of view and distance",
  claim="The Locus review credits Kay with lending surprising depth to walk-on figures.",
  source="Locus review of Children of Earth and Sky, reproduced at BrightWeavings",
  url=BW+"children-review-by-locus/",
  quote="lending surprising depth to even walk-on figures",
  page="paragraph on the young people carrying the narrative",
  kind="reception", polarity="asserts", date="2016",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),

# ===== Doug Barbour, Edmonton Journal
C(file="bw-barbour", feature="other: prose reception",
  claim="Doug Barbour calls the telling of the novel narration of a high quality.",
  source="Doug Barbour, The Edmonton Journal, review reproduced at BrightWeavings",
  url=BW+"review-by-doug-barbour-for-the-edmonton-journal/",
  quote="This is narration of a high quality, indeed.",
  page="review body",
  kind="reception", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-barbour", feature="metaphor discipline",
  claim="Barbour writes that Kay has quietly and consistently moved his narratives away from easy magic.",
  source="Doug Barbour, The Edmonton Journal, reproduced at BrightWeavings",
  url=BW+"review-by-doug-barbour-for-the-edmonton-journal/",
  quote="quietly but consistently moved his narratives ever further away from the",
  page="review body",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# ===== Thomas Wagner, SF Site
C(file="bw-wagner", feature="place and institution description",
  claim="Thomas Wagner writes that Kay builds his series' foundation through tale-spinning rather than dry exposition.",
  source="Thomas Wagner, review of Sailing to Sarantium, reproduced at BrightWeavings",
  url=BW+"review-by-thomas-wagner/",
  quote="Kay builds the foundation of his new series through tale-spinning rather",
  page="first paragraph",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-wagner", feature="opening sentence",
  claim="Wagner writes that the 40-page prologue to Sailing to Sarantium could stand alone as a story.",
  source="Thomas Wagner, reproduced at BrightWeavings",
  url=BW+"review-by-thomas-wagner/",
  quote="could stand alone as a story in its own right",
  page="first paragraph",
  kind="analysis", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),

# ===== N.R. Alexander, The Speculative Scotsman
C(file="bw-specscot", feature="cadence and rhythm",
  claim="N.R. Alexander describes Kay's prose in Tigana as poetic, protracted and powerful.",
  source="N.R. Alexander, The Speculative Scotsman, review of Tigana, reproduced at BrightWeavings",
  url=BW+"review-by-n-r-alexander-of-the-speculative-scotsman/",
  quote="His prose is poetic, protracted and powerful",
  page="review body",
  kind="reception", polarity="asserts", date="",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
]
