# -*- coding: utf-8 -*-
CLAIMS = [
# ---- C2C Journal, Bob Tarantino, 2016-09-07
dict(file="c2c", feature="place and institution description",
 claim="Bob Tarantino writes that Kay's narrating voice reads as a lens on a place that already exists rather than one being invented.",
 source="Bob Tarantino, 'The fantastic fiction of Guy Gavriel Kay', C2C Journal, 7 September 2016",
 url="https://c2cjournal.ca/2016/09/the-fantastic-fiction-of-guy-gavriel-kay/",
 quote="his narrator’s voice often feels like a lens on an existing place",
 page="body, paragraph beginning 'Kay is famed for his extensive research'",
 kind="analysis", polarity="asserts", date="2016-09-07", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="c2c", feature="plainness and economy",
 claim="Tarantino characterises Kay's style as compact and spare, expressed in short stand-alone books rather than sprawling series.",
 source="Bob Tarantino, C2C Journal, 7 September 2016",
 url="https://c2cjournal.ca/2016/09/the-fantastic-fiction-of-guy-gavriel-kay/",
 quote="His compact, spare style finds expression in succinct stand-alone books",
 page="body, paragraph on 'His preferred approach lies outside the dominant modes'",
 kind="analysis", polarity="asserts", date="2016-09-07", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="c2c", feature="other: elegiac register",
 claim="Tarantino describes the pervading tone of Kay's writing as elegiac and quietly valedictory.",
 source="Bob Tarantino, C2C Journal, 7 September 2016",
 url="https://c2cjournal.ca/2016/09/the-fantastic-fiction-of-guy-gavriel-kay/",
 quote="suffused with an elegiac tone and the gentle melancholy of farewells",
 page="body, paragraph beginning 'These are novels about the importance'",
 kind="analysis", polarity="asserts", date="2016-09-07", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="c2c", feature="metaphor discipline",
 claim="Tarantino contrasts Kay's delivery with bombast, calling the stories meditative instead.",
 source="Bob Tarantino, C2C Journal, 7 September 2016",
 url="https://c2cjournal.ca/2016/09/the-fantastic-fiction-of-guy-gavriel-kay/",
 quote="They are meditative rather than bombastic.",
 page="closing section 'A conservative would say that words strung together'",
 kind="analysis", polarity="asserts", date="2016-09-07", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="c2c", feature="consequence on a household",
 claim="Tarantino states that in Kay's stories the present is always shown as a product of the past.",
 source="Bob Tarantino, C2C Journal, 7 September 2016",
 url="https://c2cjournal.ca/2016/09/the-fantastic-fiction-of-guy-gavriel-kay/",
 quote="the present of his stories is always a product of their past",
 page="section 'The essence of conservative storytelling'",
 kind="analysis", polarity="asserts", date="2016-09-07", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),

# ---- MetaStellar, Amira Loutfi, 2022-10-04
dict(file="metastellar", feature="place and institution description",
 claim="Amira Loutfi draws from Tigana the lesson that a vast world can be created with few words.",
 source="Amira Loutfi (author and MetaStellar reviews editor), 'Tigana by Guy Gavriel Kay: 9 Lessons', MetaStellar, 4 October 2022",
 url="https://www.metastellar.com/nonfiction/tigana-by-guy-gavriel-kay-lessons-from-the-best-stand-alone-fantasy-novel-of-all-time/",
 quote="you can create a vast world with few words",
 page="lesson 1, 'You Can Go Big'",
 kind="analysis", polarity="asserts", date="2022-10-04", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="metastellar", feature="other: counter-reception of lyrical prose",
 claim="Loutfi reports that she personally finds Kay's prose annoying, placing herself among readers who dislike it.",
 source="Amira Loutfi, MetaStellar, 4 October 2022",
 url="https://www.metastellar.com/nonfiction/tigana-by-guy-gavriel-kay-lessons-from-the-best-stand-alone-fantasy-novel-of-all-time/",
 quote="many other readers find it to be annoying",
 page="lesson 3, 'Beautiful Prose is a double-edged Sword'",
 kind="reader", polarity="disputes", date="2022-10-04", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="metastellar", feature="point of view and distance",
 claim="Loutfi observes that Tigana gives no warning of when a chapter will switch viewpoint.",
 source="Amira Loutfi, MetaStellar, 4 October 2022",
 url="https://www.metastellar.com/nonfiction/tigana-by-guy-gavriel-kay-lessons-from-the-best-stand-alone-fantasy-novel-of-all-time/",
 quote="there was no telling when we were going to switch viewpoints",
 page="lesson 9, 'Unpredictable Viewpoints are Fine'",
 kind="analysis", polarity="asserts", date="2022-10-04", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- LitHub, Kay's own essay, 2016-07-06
dict(file="writeclub", feature="other: craft rules and prescription",
 claim="Kay lists 'No sentence fragments' and 'One narrator only' among writing rules he says he has broken.",
 source="Guy Gavriel Kay, 'The First Rule of Write Club Is...', Literary Hub, 6 July 2016",
 url="https://lithub.com/the-first-rule-of-write-club-is/",
 quote="No sentence fragments. One narrator only. (Yes, I’ve broken all of these.)",
 page="paragraph beginning 'But there might be harm'",
 kind="own-words", polarity="rejects", date="2016-07-06", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="writeclub", feature="other: craft rules and prescription",
 claim="Kay argues that the notion that art has rules to be followed may itself do harm.",
 source="Guy Gavriel Kay, Literary Hub, 6 July 2016",
 url="https://lithub.com/the-first-rule-of-write-club-is/",
 quote="there might be harm in the very notion that there are rules",
 page="paragraph beginning 'But there might be harm'",
 kind="own-words", polarity="rejects", date="2016-07-06", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="writeclub", feature="other: craft rules and prescription",
 claim="Kay separates the rules of commercial success from the rules of writing as well as one can.",
 source="Guy Gavriel Kay, Literary Hub, 6 July 2016",
 url="https://lithub.com/the-first-rule-of-write-club-is/",
 quote="The rules of smart commerce are not identical to the rules",
 page="paragraph beginning 'And there is nothing wrong with it'",
 kind="own-words", polarity="asserts", date="2016-07-06", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- W.A. Hamilton blog
dict(file="wahamil", feature="point of view and distance",
 claim="W.A. Hamilton notes that A Brightness Long Ago divides its narration between a first-person account and a third-person account.",
 source="W.A. Hamilton, 'Guy Gavriel Kay Books: From Best to Worst', wahamiltron.com (undated)",
 url="https://wahamiltron.com/guy-gavriel-kay-books/",
 quote="The narrative is split between a first-person account and a third-person account",
 page="entry for A Brightness Long Ago",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="medium: undated blog post by a self-published author, no editorial venue"),

# ---- Midori Snyder (novelist) on Under Heaven
dict(file="bw-snyder", feature="place and institution description",
 claim="Novelist Midori Snyder writes that the historical detail in Under Heaven gives the writing texture without weighing it down.",
 source="Midori Snyder (novelist), review of Under Heaven, reproduced at BrightWeavings (Kay's official site)",
 url="https://brightweavings.com/review-by-novelist-midori-snyder/",
 quote="The historical details give the writing texture without ever weighing it down",
 page="final paragraphs of the review",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-snyder", feature="diction (native vs latinate)",
 claim="Snyder attributes the sensual, vivid language of Under Heaven to the influence of the T'ang poets.",
 source="Midori Snyder (novelist), review of Under Heaven, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-novelist-midori-snyder/",
 quote="as though ever mindful of the inspirational influence of the T’ang poets",
 page="final paragraphs of the review",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-snyder", feature="place and institution description",
 claim="Snyder calls Kay's descriptions of the remote landscape in the opening chapter of Under Heaven lavish.",
 source="Midori Snyder (novelist), review of Under Heaven, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-novelist-midori-snyder/",
 quote="Kay’s lavish descriptions of the remote landscape",
 page="third paragraph, on the opening chapter",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),

# ---- Michael Dirda, Washington Post
dict(file="bw-dirda", feature="register modulation",
 claim="Michael Dirda describes the style Kay chose for Under Heaven as spare and slightly courtly.",
 source="Michael Dirda, The Washington Post, review of Under Heaven, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-michael-dirda-of-the-washington-post/",
 quote="Kay has chosen a spare, slightly courtly style",
 page="penultimate section, paragraph beginning 'Guy Gavriel Kay is a much honored Canadian writer'",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-dirda", feature="omission as information",
 claim="Dirda writes that Kay's minor characters suggest a great deal happening outside the narrative's field of vision.",
 source="Michael Dirda, The Washington Post, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-michael-dirda-of-the-washington-post/",
 quote="much else is going on just outside our narrative field of vision",
 page="paragraph beginning 'Guy Gavriel Kay is a much honored Canadian writer'",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-dirda", feature="annalist voice and deep time",
 claim="Dirda names the voice telling Under Heaven a historian-like narrator.",
 source="Michael Dirda, The Washington Post, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-michael-dirda-of-the-washington-post/",
 quote="As Kay’s historian-like narrator observes",
 page="paragraph introducing the quoted passage on branching tales",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-dirda", feature="omission as information",
 claim="The passage Dirda quotes from Under Heaven says every tale carries others noted in passing or overlooked.",
 source="Guy Gavriel Kay, Under Heaven, quoted by Michael Dirda in The Washington Post, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-michael-dirda-of-the-washington-post/",
 quote="Every single tale carries within it many others, noted in passing",
 page="block quotation attributed to Kay's narrator",
 kind="analysis", polarity="applies", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-dirda", feature="closing sentence",
 claim="Dirda writes that Under Heaven ends with everything fading quietly into history.",
 source="Michael Dirda, The Washington Post, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-michael-dirda-of-the-washington-post/",
 quote="Everything quietly, ineluctably fades into history",
 page="final paragraph",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),

# ---- Adam Whitehead, The Wertzone
dict(file="bw-wertzone", feature="other: prose reception",
 claim="Adam Whitehead of The Wertzone characterises River of Stars as told with elegant prose.",
 source="Adam Whitehead, The Wertzone, review of River of Stars, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-adam-whitehead-of-the-wertzone/",
 quote="told with flair, passion and elegant prose",
 page="final paragraph",
 kind="reception", polarity="asserts", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- Indrapramit Das, Strange Horizons
dict(file="bw-das", feature="plainness and economy",
 claim="Indrapramit Das writes that River of Stars is never showy despite its length and research.",
 source="Indrapramit Das (novelist), Strange Horizons review of River of Stars, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-indrapramit-das-for-strange-horizons/",
 quote="River of Stars is never showy",
 page="second paragraph",
 kind="analysis", polarity="asserts", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-das", feature="adjective and adverb discipline",
 claim="Das writes that in over six hundred pages not a word of River of Stars feels gratuitous.",
 source="Indrapramit Das, Strange Horizons, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-indrapramit-das-for-strange-horizons/",
 quote="not a word of this novel feels gratuitous",
 page="paragraph beginning 'Not only are Shan and Daiyan wonderfully drawn'",
 kind="analysis", polarity="asserts", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-das", feature="cadence and rhythm",
 claim="Das writes that Kay's lyrical prose keeps a contemplative calm even during battles and ambushes.",
 source="Indrapramit Das, Strange Horizons, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-indrapramit-das-for-strange-horizons/",
 quote="Kay’s lyrical prose retains a sense of contemplative calm",
 page="paragraph beginning 'Not only are Shan and Daiyan wonderfully drawn'",
 kind="analysis", polarity="asserts", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-das", feature="point of view and distance",
 claim="Das notes that some of River of Stars's large cast appear for a single scene before receding.",
 source="Indrapramit Das, Strange Horizons, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-indrapramit-das-for-strange-horizons/",
 quote="appear for a mere scene before fading back into the narrative",
 page="first paragraph",
 kind="analysis", polarity="asserts", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-das", feature="concrete sensory noun",
 claim="Das writes that Kay keeps returning the novel to the small moments that lie between the momentous ones.",
 source="Indrapramit Das, Strange Horizons, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-indrapramit-das-for-strange-horizons/",
 quote="the small moments that linger between the momentous ones",
 page="paragraph beginning 'Any historical period, any story'",
 kind="analysis", polarity="asserts", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-das", feature="annalist voice and deep time",
 claim="The passage Das quotes from River of Stars opens by saying small events can matter in the unfolding of a world.",
 source="Guy Gavriel Kay, River of Stars p.315, quoted by Indrapramit Das in Strange Horizons, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-indrapramit-das-for-strange-horizons/",
 quote="Small events can be important in the unfolding, like a pleated sail",
 page="block quotation cited as p. 315",
 kind="analysis", polarity="applies", date="2013", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),

# ---- Robert J. Wiersema, Globe and Mail
dict(file="bw-wiersema", feature="withheld information and inference",
 claim="Robert J. Wiersema calls the way Under Heaven releases information about Tai a balanced dance of careful revelation.",
 source="Robert J. Wiersema, The Globe and Mail, review of Under Heaven, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-robert-j-wiersema-for-the-globe-and-mail/",
 quote="It’s a beautifully balanced dance of careful revelation",
 page="paragraph beginning 'His student days'",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-wiersema", feature="place and institution description",
 claim="Wiersema writes that Under Heaven's research does not make the book labour under historical veracity or trivia.",
 source="Robert J. Wiersema, The Globe and Mail, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-robert-j-wiersema-for-the-globe-and-mail/",
 quote="it doesn’t labour under historical veracity or trivia",
 page="paragraph beginning 'The novel, which comes as a result'",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-wiersema", feature="civic record register",
 claim="Wiersema writes that the invented country of Kitai arrives with its own clearly delineated systems and traditions.",
 source="Robert J. Wiersema, The Globe and Mail, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-robert-j-wiersema-for-the-globe-and-mail/",
 quote="with its own clearly delineated systems and traditions, values and beliefs",
 page="paragraph beginning 'The novel, which comes as a result'",
 kind="analysis", polarity="asserts", date="2010", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),

# ---- Kate Nepveu, Sailing to Sarantium
dict(file="bw-nepveu", feature="point of view and distance",
 claim="Kate Nepveu writes that Sailing to Sarantium shows its major plot events through multiple points of view, some dominant and many minor.",
 source="Kate Nepveu, review of Sailing to Sarantium, originally posted to rec.arts.sf.written, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu/",
 quote="shown through multiple points of view, where some dominate but are",
 page="paragraph beginning 'However, Crispin is not the sole focus'",
 kind="analysis", polarity="asserts", date="1998", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-nepveu", feature="withheld information and inference",
 claim="Nepveu writes that small details placed in one part of the book refer to and reflect larger ones elsewhere.",
 source="Kate Nepveu, rec.arts.sf.written, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu/",
 quote="small details relayed in one area refer to and reflect larger",
 page="paragraph beginning 'However, Crispin is not the sole focus'",
 kind="analysis", polarity="asserts", date="1998", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-nepveu", feature="place and institution description",
 claim="Nepveu writes that the chariot races and the pagan sacrifices are rendered with equal vividness and precision.",
 source="Kate Nepveu, rec.arts.sf.written, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu/",
 quote="sacrifices to pagan gods are rendered equally vividly and precisely",
 page="paragraph beginning 'A “half-world” of supernatural beings'",
 kind="analysis", polarity="asserts", date="1998", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-nepveu", feature="opening sentence",
 claim="The epigraph Nepveu quotes opens with a definition formula, saying what it meant to say of a man that he was sailing to Sarantium.",
 source="Guy Gavriel Kay, Sailing to Sarantium, quoted by Kate Nepveu, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu/",
 quote="To say of a man that he was sailing to Sarantium",
 page="epigraph quotation at head of review",
 kind="analysis", polarity="applies", date="1998", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),

# ---- Kate Nepveu, Lord of Emperors
dict(file="bw-nepveu2", feature="consequence on a household",
 claim="The passage Nepveu quotes says the great events of an age appear to those living through them as backdrops to their own lives.",
 source="Guy Gavriel Kay, Lord of Emperors, quoted by Kate Nepveu (31 July 2000), reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu-2/",
 quote="The great events of an age appear, to those living through",
 page="epigraph quotation at head of review",
 kind="analysis", polarity="applies", date="2000-07-31", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-nepveu2", feature="consequence on a household",
 claim="A passage Nepveu quotes registers a labourer's death by the farm it leaves undermanned at ploughing time.",
 source="Guy Gavriel Kay, Lord of Emperors, quoted by Kate Nepveu, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu-2/",
 quote="somewhere a labourer died, leaving a farm grievously undermanned",
 page="block quotation, 'Somewhere in the world, just then'",
 kind="analysis", polarity="applies", date="2000-07-31", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-nepveu2", feature="annalist voice and deep time",
 claim="A passage Nepveu quotes dates the destruction of a charioteer's statues seven hundred years after his career.",
 source="Guy Gavriel Kay, Lord of Emperors, quoted by Kate Nepveu, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu-2/",
 quote="seven hundred years after, when the great changes came",
 page="final block quotation of the review",
 kind="analysis", polarity="applies", date="2000-07-31", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-nepveu2", feature="point of view and distance",
 claim="Nepveu writes that the Sarantine Mosaic is composed of a number of different narrators and narratives.",
 source="Kate Nepveu, review of Lord of Emperors, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-kate-nepveu-2/",
 quote="composed of a number of different narrators and narratives",
 page="paragraph beginning 'In Sarantium, the mosaicist Caius Crispus'",
 kind="analysis", polarity="asserts", date="2000-07-31", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- Victoria Hoyle, Sailing to Sarantium
dict(file="bw-hoyle", feature="cadence and rhythm",
 claim="Victoria Hoyle describes Kay's prose as mixing a Tolkienian weight of cadence with a contemporary wryness.",
 source="Victoria Hoyle (Eve's Alexandria), review of Sailing to Sarantium, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="mixing the weighty cadence of Tolkien with a contemporary wryness",
 page="paragraph beginning 'What to say?'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-hoyle", feature="parataxis vs hypotaxis",
 claim="Hoyle writes that Kay's sentences are often convoluted and their meanings often obscured.",
 source="Victoria Hoyle, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="sentences are often convoluted, meanings often obscured",
 page="paragraph beginning 'What to say?'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-hoyle", feature="archaism",
 claim="Hoyle writes that Kay's phrasing is sometimes flavoured with an archaism that makes the reader slow down.",
 source="Victoria Hoyle, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="flavoured with an archaism that prompts a second glance",
 page="paragraph beginning 'What to say?'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-hoyle", feature="civic record register",
 claim="Hoyle describes Kay's post-Fionavar novels as marrying chronicle and record with high fantasy.",
 source="Victoria Hoyle, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="marrying chronicle and record with high fantasy",
 page="paragraph beginning 'But the book is much more than'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-hoyle", feature="withheld information and inference",
 claim="Hoyle observes that a Kay chapter will often end on a puzzle or a mystery.",
 source="Victoria Hoyle, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="Often a chapter will end on a puzzle, a mystery",
 page="paragraph beginning 'Yet it isn’t simple analogy'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-hoyle", feature="point of view and distance",
 claim="Hoyle observes that a new Kay chapter often opens on a completely new and apparently inconsequential individual.",
 source="Victoria Hoyle, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="opens from the point of view of some completely new and",
 page="paragraph beginning 'Yet it isn’t simple analogy'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-hoyle", feature="cadence and rhythm",
 claim="Hoyle reports reading passages of Sailing to Sarantium aloud to herself.",
 source="Victoria Hoyle, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle/",
 quote="I often found myself pausing to read sections out loud",
 page="paragraph beginning 'What to say?'",
 kind="reader", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- Victoria Hoyle, Lord of Emperors
dict(file="bw-hoyle2", feature="withheld information and inference",
 claim="Hoyle writes that Kay's style is often obtuse and his characters' motives obscured.",
 source="Victoria Hoyle, review of Lord of Emperors, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle-of-eves-alexandria/",
 quote="Kay’s style is often obtuse, his character’s motives obscured",
 page="opening paragraph",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-hoyle2", feature="point of view and distance",
 claim="Hoyle writes that Kay breaks a scene's momentum into half a dozen point-of-view fragments.",
 source="Victoria Hoyle, review of Lord of Emperors, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle-of-eves-alexandria/",
 quote="fractures it into half a dozen POV fragments",
 page="paragraph beginning 'Lord of Emperors does not have the exact same flavour'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-hoyle2", feature="repetition and refrain",
 claim="Hoyle names recurring concrete images, among them a cloak on a pebble beach and a leather bird in wet grass.",
 source="Victoria Hoyle, review of Lord of Emperors, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle-of-eves-alexandria/",
 quote="a cloak discarded on a pebble beach, a leather bird",
 page="paragraph beginning 'Lord of Emperors does not have the exact same flavour'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-hoyle2", feature="repetition and refrain",
 claim="Hoyle writes that those recurring images act as indexes of the book's emotional register.",
 source="Victoria Hoyle, review of Lord of Emperors, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-victoria-hoyle-of-eves-alexandria/",
 quote="acting as indexes of the book’s emotional register",
 page="paragraph beginning 'Lord of Emperors does not have the exact same flavour'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- Joe Milicia, NYRSF
dict(file="bw-milicia", feature="point of view and distance",
 claim="Joe Milicia writes that Kay likes exercising tricks belonging to the narrator's trade rather than the dramatist's.",
 source="Joe Milicia, The New York Review of Science Fiction, review of Sailing to Sarantium, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="Kay likes exercising tricks of the narrator’s trade",
 page="paragraph beginning 'First, Kay likes exercising'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-milicia", feature="other: prolepsis and foreshadowing",
 claim="Milicia writes that Kay's foreshadowing is elaborate and delivered with a detached amusement.",
 source="Joe Milicia, NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="elaborate foreshadowing with a sort of detached amusement",
 page="paragraph beginning 'First, Kay likes exercising'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-milicia", feature="other: prolepsis and foreshadowing",
 claim="The sample Milicia quotes shows Kay's narrator speculating in the conditional about consequences of an event that did not happen.",
 source="Guy Gavriel Kay, Sailing to Sarantium, quoted by Joe Milicia in NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="This, in turn, might have occasioned a significant change in various",
 page="parenthetical sample quotation of Kay's text",
 kind="analysis", polarity="applies", date="", routeHint="curl with browser user agent, live URL",
 registerHint="chronicle-line", confidence="high"),
dict(file="bw-milicia", feature="place and institution description",
 claim="Milicia writes that the novel supplies all the data a reader might want on tesserae and hippodromes.",
 source="Joe Milicia, NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="all the data we might possibly want on tesserae and hippodromes",
 page="paragraph beginning 'Along the way there as many dramatic surprises'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="dossier-archivist", confidence="high"),
dict(file="bw-milicia", feature="point of view and distance",
 claim="Milicia reads the mosaic as Kay's analogy for a novel built in discrete units whose picture appears only at a distance.",
 source="Joe Milicia, NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="a novel might be constructed in discrete units with the",
 page="paragraph beginning 'Along the way there as many dramatic surprises'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-milicia", feature="other: chronology handling",
 claim="Milicia praises a chapter of Sailing to Sarantium for its intricately rearranged chronology.",
 source="Joe Milicia, NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="an intricately rearranged chronology and a wittily drawn-out suspense",
 page="paragraph beginning 'Kay is also extremely skilled'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-milicia", feature="other: opening pacing",
 claim="Milicia calls the long Prologue of Sailing to Sarantium a bit plodding.",
 source="Joe Milicia, NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="the long Prologue is a bit plodding",
 page="paragraph beginning 'Kay is also extremely skilled'",
 kind="analysis", polarity="disputes", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
dict(file="bw-milicia", feature="point of view and distance",
 claim="Milicia argues the fantasy frame places a veil of more than historical distance between the reader's world and the novel's.",
 source="Joe Milicia, NYRSF, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-joe-milicia-for-the-new-york-review-of-science-fiction/",
 quote="a veil of more than historical distance between our world and",
 page="paragraph beginning 'One could ask, why not call everything'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),

# ---- Dena Taylor
dict(file="bw-denataylor", feature="other: historical fidelity",
 claim="Dena Taylor writes that Sailing to Sarantium shows Kay at his most historical, reshaping the reign of Justinian and Theodora.",
 source="Dena Taylor, review of Sailing to Sarantium for a Nimrod Press Babel Handbooks volume, reproduced at BrightWeavings",
 url="https://brightweavings.com/review-by-dena-taylor-sailing-to-sarantium/",
 quote="Here is Kay at his most historical, reshaping the reign of",
 page="paragraph beginning 'As a first volume'",
 kind="analysis", polarity="asserts", date="", routeHint="curl with browser user agent, live URL",
 registerHint="none", confidence="high"),
]
