# -*- coding: utf-8 -*-
UH="https://brightweavings.com/books/under-heaven-tour-journal/"
YS="https://brightweavings.com/books/ysabel-journal/"
LL="https://brightweavings.com/books/last-light-of-the-sun-tour-journal/"
def C(**k): return k
CLAIMS=[
# --- Under Heaven tour journal: Kay's own craft post on register and culture
C(file="bw-uhjournal", feature="register modulation",
  claim="Kay states that language needs to suit setting, and that the handling of emotion does too.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="just as language needs to suit setting, so does playing with",
  page="journal entry on emotion and craft", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-uhjournal", feature="per-speaker register",
  claim="Kay says that making characters of a controlled society emote as moderns do feels like a betrayal of them.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="feels like a betrayal (even a large one) of the characters",
  page="journal entry on emotion and craft", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-uhjournal", feature="register modulation",
  claim="Kay says a baseline must be established before contrasting character types can be offered.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="to offer contrasting types, one needs to establish the baseline",
  page="journal entry on emotion and craft", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-uhjournal", feature="plainness and economy",
  claim="Kay says he admires writers whose effects are deliberately quiet and less intense.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="whose effects are deliberately quiet, less intense",
  page="journal entry on emotion and craft", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-uhjournal", feature="register modulation",
  claim="Kay says some cultures and characters must be drawn in heightened tones while others would be wrong that way.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="Some cultures and characters need to be drawn in such tones",
  page="journal entry on emotion and craft", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-uhjournal", feature="register modulation",
  claim="Kay says the world and people of The Last Light of the Sun cannot be the same as those of The Lions of Al-Rassan.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="The world and people of Last Light cannot be the same",
  page="journal entry on emotion and craft", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-uhjournal", feature="other: punctuation as craft",
  claim="Kay's production editor at Penguin Group (Canada) writes that he forges his own rules of punctuation.",
  source="Guy Gavriel Kay's production editor at Penguin Group (Canada), guest post in the Under Heaven tour journal, BrightWeavings",
  url=UH, quote="he forges his own rules when it comes to punctuation",
  page="guest post by the production editor", kind="analysis", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-uhjournal", feature="cadence and rhythm",
  claim="That production editor writes that each point of punctuation in Kay's text signifies how the passage should be read.",
  source="Kay's production editor at Penguin Group (Canada), guest post in the Under Heaven tour journal, BrightWeavings",
  url=UH, quote="each point of punctuation is there to signify how that passage",
  page="guest post by the production editor", kind="analysis", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-uhjournal", feature="edition and house style",
  claim="That production editor writes that Kay's punctuation is exactly as he wants it when the manuscript is submitted.",
  source="Kay's production editor at Penguin Group (Canada), guest post in the Under Heaven tour journal, BrightWeavings",
  url=UH, quote="It’s exactly as he wants it when he submits the manuscript.",
  page="guest post by the production editor", kind="analysis", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-uhjournal", feature="edition and house style",
  claim="Kay reports that italics look louder in page proofs than on screen and that he drops more of them at that stage.",
  source="Guy Gavriel Kay, Under Heaven tour journal, BrightWeavings",
  url=UH, quote="I get caught up in small tinkerings with the text, word",
  page="journal entry on page proofs", kind="own-words", polarity="asserts", date="2010",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="medium: the quotation supports the tinkering and italics-dropping half; the 'louder in page proofs' phrasing appears in a separate sentence on the same page"),

# --- Ysabel journal: sentence-level copy-edit craft
C(file="bw-ysjournal", feature="per-speaker register",
  claim="Kay says he uses punctuation variably depending on context, speaker and rhythms.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="I’ll use punctuation varaibly depending on context, speaker, rhythms.",
  page="entry on the proofreader over-punctuating speech", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="edition and house style",
  claim="Kay states that The Last Light of the Sun is punctuated differently from the Sarantine Mosaic.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="LAST LIGHT is punctuated differently than the MOSAIC was.",
  page="entry on the proofreader over-punctuating speech", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="cadence and rhythm",
  claim="Kay says too many technically viable commas undermine the effect of a passage of rapid speech.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="too many technically viable commas undermines the EFFECT of the passage",
  page="entry on the proofreader over-punctuating speech", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-ysjournal", feature="dialogue register",
  claim="Kay says he has certain characters speak rapidly under stress.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="I have certain characters speaking rapidly at times, under stress",
  page="entry on the proofreader over-punctuating speech", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-ysjournal", feature="edition and house style",
  claim="Kay says italics look louder in galleys than on his screen and he consistently deletes them there.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="italics look LOUDER in galleys than they do on my computer",
  page="entry on deleting italics in the galleys", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="opening sentence",
  claim="Kay says he had not wanted the hard break of a colon at the outset of the novel.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="the hard break of a colon at the outset of the",
  page="entry on Catherine's query about the Prologue's first sentence", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="other: punctuation as craft",
  claim="Kay accepts that a colon better sets off the list that follows in his opening sentence.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="a colon better sets off the ‘list’ that follows",
  page="entry on Catherine's query about the Prologue's first sentence", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="metaphor discipline",
  claim="Kay reports deleting the word 'taste' after his copy-editor found the sustained metaphor tangled.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="the sentence simply read better after deleting the word ‘taste’",
  page="entry on the Prologue copy-edit", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="repetition and refrain",
  claim="Kay says removing the earlier use of a word energised its later appearance by making it no longer a repetition.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="gets heightened and energized by not being a repetition",
  page="entry on the Prologue copy-edit", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="place and institution description",
  claim="Kay says he always fears making his novels sound over-burdened with their sources.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="I always fear making my novels sound over-burdened with the sources",
  page="entry on writing the Acknowledgements", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="register modulation",
  claim="Kay says he asked his copy-editor to watch for stylistic elements of Last Light slipping into Ysabel out of habit.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="I don’t want them slipping into Ysabel, out of carried-over habit",
  page="entry explaining the copy-editing stage", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="dossier-archivist", confidence="high"),
C(file="bw-ysjournal", feature="edition and house style",
  claim="Kay describes copy-editors changing some semi-colons to colons or commas when an author overuses them.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="If an author is overusing semi-colons they change some to colons",
  page="entry explaining the copy-editing stage", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="none", confidence="high"),
C(file="bw-ysjournal", feature="closing sentence",
  claim="Kay says Ysabel carries a tag quotation at the end of the book as The Last Light of the Sun did.",
  source="Guy Gavriel Kay, Ysabel journal, BrightWeavings",
  url=YS, quote="it also has a tag quote at the end, as LAST",
  page="entry on the epigraph question", kind="own-words", polarity="asserts", date="2006",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),

# --- Last Light journal: the admired narrating voice
C(file="bw-lljournal", feature="point of view and distance",
  claim="Kay calls splendid and accurate a description of a narrative voice in which authorial omniscience is qualified by human kindness.",
  source="Joyce Carol Oates on Anne Tyler, quoted approvingly by Guy Gavriel Kay in the Last Light of the Sun tour journal, BrightWeavings",
  url=LL, quote="authorial omniscience is qualified by human kindness of the sort we",
  page="journal entry of 27 February 2004", kind="own-words", polarity="applies", date="2004-02-27",
  routeHint="curl with browser user agent, live URL", registerHint="chronicle-line", confidence="high"),
]
