BW="https://brightweavings.com/"
SOURCES=[
 dict(title="Post-Romantic Romance / student essays landing pages (mythinfantasy)", url=BW+"mythinfantasy/", kind="analysis", substantive=False, date="", route="curl browser UA, live URL; undergraduate thesis chapter, thematic not prose-level"),
 dict(title="How Are Heroes Born? (Patricia Gagne, translated)", url=BW+"howareheroesborn/", kind="analysis", substantive=False, date="", route="curl browser UA, live URL; thematic student essay"),
 dict(title="Fate and Free Will in The Fionavar Tapestry", url=BW+"fate_freewill/", kind="analysis", substantive=False, date="", route="curl browser UA, live URL; thematic student essay"),
 dict(title="Just a Game (BrightWeavings)", url=BW+"justagame/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; no prose-craft content"),
 dict(title="Mondegreens (BrightWeavings)", url=BW+"mondegreens/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; no prose-craft content"),
 dict(title="Hitchhiker (BrightWeavings)", url=BW+"hitchhiker/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL"),
 dict(title="Phantastes (BrightWeavings)", url=BW+"phantastes/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL"),
 dict(title="Too Much GGK (BrightWeavings)", url=BW+"toomuchggk/", kind="reader", substantive=False, date="", route="curl browser UA, live URL"),
 dict(title="A Word from Guy Gavriel Kay", url=BW+"a-word-from-guy-gavriel-kay/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL"),
 dict(title="What Do We Lose and Gain as Book Tours Move Online (BrightWeavings landing)", url=BW+"what-do-we-lose-and-gain-as-book-tours-move-online/", kind="own-words", substantive=False, date="2020", route="curl browser UA, live URL; stub linking out"),
 dict(title="What Do We Lose and Gain as Book Tours Move Online (Literary Hub)", url="https://lithub.com/what-do-we-lose-and-gain-as-book-tours-move-online/", kind="own-words", substantive=False, date="2020", route="curl browser UA, live URL; on touring, no prose-craft content"),
 dict(title="Guy Gavriel Kay author page (Literary Hub)", url="https://lithub.com/author/guygavrielkay/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; index used for discovery"),
 dict(title="Andrews interview page (BrightWeavings)", url=BW+"andrews/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL"),
 dict(title="The Annotated GGK (BrightWeavings)", url=BW+"scholarship/the-annotated-ggk/", kind="analysis", substantive=False, date="", route="curl browser UA, live URL; annotation index"),
 dict(title="George R.R. Martin on Under Heaven (BrightWeavings)", url=BW+"martin/", kind="reception", substantive=False, date="", route="curl browser UA, live URL; blurb page"),
 dict(title="Barnes & Noble interview page (BrightWeavings)", url=BW+"barnes-noble/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; no prose-craft content in fetched page"),
 dict(title="Audio interview with Rick Kleffel of The Agony Column (BrightWeavings)", url=BW+"audio-interview-with-rick-kleffel-of-the-agony-column/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; audio only, no transcript"),
 dict(title="GGK in conversation with Nancy Pearl (BrightWeavings)", url=BW+"university-book-store-presents-guy-gavriel-kay-in-conversation-with-nancy-pearl/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; video link only"),
 dict(title="GGK in conversation with Paul Blezard, Lockdown LitFest (BrightWeavings)", url=BW+"watch-ggk-in-conversation-with-paul-blezard-at-the-lockdown-litfest/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; video link only"),
 dict(title="Guest editor for LoveReading (BrightWeavings)", url=BW+"guest-editor-for-lovereading/", kind="own-words", substantive=False, date="", route="curl browser UA, live URL; link only"),
 dict(title="Reviews of A Brightness Long Ago (BrightWeavings roundup)", url=BW+"reviews-of-a-brightness-long-ago/", kind="reception", substantive=False, date="", route="curl browser UA, live URL; index only"),
 dict(title="Writing Excuses tag page for Guy Gavriel Kay", url="https://writingexcuses.com/tag/guy-gavriel-kay/", kind="analysis", substantive=False, date="", route="curl browser UA, live URL; two episode pages tagged, neither transcript discusses Kay's prose"),
 dict(title="Writing Excuses 10.21: Q&A on World Building", url="https://writingexcuses.com/writing-excuses-10-21-qa-on-world-building/", kind="analysis", substantive=False, date="2015-05-24", route="curl browser UA, live URL; no Kay content in the page text"),
 dict(title="Writing Excuses 5.36: Non-Traditional Settings with Saladin Ahmed", url="https://writingexcuses.com/writing-excuses-5-36-non-traditional-settings-with-saladin-ahmed/", kind="analysis", substantive=False, date="2011-05-08", route="curl browser UA, live URL; no Kay content in the page text"),
 dict(title="Some Writing Advice: Don't Take Others' Advice (Literary Hub) - re-fetched to confirm it is a different essay from 'The First Rule of Write Club Is...'", url="https://lithub.com/some-writing-advice-dont-take-others-advice/", kind="own-words", substantive=False, date="2019-05-15", route="curl browser UA, live URL; already in the predecessor's roster, re-read only to prove non-duplication"),
]
CLAIMS=[]
