import re
SC='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/4e3d2f70-f45f-4e14-b571-514c339cfa17/scratchpad'
rows=[]; cur=None
for line in open(f'{SC}/rt2-compact.txt',encoding='utf-8'):
    m=re.match(r'=== (RT2\.\S+) \[\*\*(\w+)\*\*\] noun: (.*)',line)
    if m:
        cur={'id':m.group(1),'verdict':m.group(2),'noun':m.group(3).strip()[:70]}; rows.append(cur); continue
C='CONFIRMED'; P='PLAUSIBLE'
N={}
def ok(i,n): N[i]=('OK',n)
def ch(i,n): N[i]=('CHALLENGE',n)
def rv(i,n): N[i]=('REVERSE',n)
S='{settlement}'
# ---- 2.1 defense
ok('RT2.1-01',C+' kept half: forces.walls.present / hasWalls priorityHelpers.js:52; struck half (muster-holder layer, "the line") safe with the stated unwalled qualifier.')
ok('RT2.1-02',C+' R-7: institutionVocabulary.js fixes material; struck half (blanket material bar) safe.')
ok('RT2.1-03',C+' hasGates :53 includes palisade; DS-DEF-5 walls ABSENT on the same desk. Permission safe.')
ok('RT2.1-04',C+' a slot mechanic; nothing false licensed.')
ok('RT2.1-05',C+' :46 and defenseStateProse.js:655 read garrison; R-3.')
ok('RT2.1-06',C+' :46 "barracks" in hasGarrison; buckets :89; safetyProfile.js:281 prints "The garrison" off the flag. Worst sentence ("the garrison drills") is the engine\'s own word.')
rv('RT2.1-07',C+' should be SPLIT | institutionalCatalog.js:1352 (Town watch = "Part-time guards"), safetyProfile.js:300, priorityHelpers.js:46 | floor 1. "use the phrase as flavour; it asserts no row" is false: "professional guard" asserts a professional body. Worst: "a professional guard keeps the gate" on a Town-watch-only town (F1-27) or a bodiless thorp (F1-04).')
ok('RT2.1-08',C+' holderTable.js:279-288 (muster kind = Citizen militia only).')
ok('RT2.1-09',C+' defenseStateProse.js:1284.')
ok('RT2.1-10',C+' :51.')
ch('RT2.1-11',C+' the strike is right (bucket read in code); the permission "on DS-DEF-5\'s arcane pools" must be the PRESENT pool only: the ABSENT pool and defenseDisplay.js:225 "Magical Capability: None" deny arcane provision (F1-17).')
ok('RT2.1-12',C+' token fact; label traps carried by body rows.')
ok('RT2.1-13',C+' kept: :48 + safetyProfile.js:300; struck pay-gate bar: defenseGenerator.js:177-178 counts hasWatch; fieldSynonyms.js:51. Permission qualified.')
ch('RT2.1-14',C+' should be SPLIT: the noun row is "court · courthouse" and RT2.5-11/F1-12 keep the courthouse BUILDING; the WORD is rightly free — and the closing essay\'s premise ("a hall and no court") is defeated by defenseDisplay.js:231 printing "Court only"/"Courts without detention" off hasCourtSystem, safetyProfile.js:330 "A court exists", and the engine\'s own DS-DEF-6 face "'+S+' tries and cannot hold" (defense.generated.js:2858). The permission cell as written licenses no false sentence.')
ok('RT2.1-15',C+' :54; defenseDisplay.js:231 prints "Legal Infrastructure: None".')
ok('RT2.1-16',C+' W24 struck; F2-01 bars any sum; F1-24 keeps only the unresolved-holder citation. No field denies "the purse".')
ok('RT2.1-17',C+' provenance rule.')
ok('RT2.1-18',C+' :63 kept.')
ok('RT2.1-19',C+' :64 catches "healer"; AND defenseDisplay.js:237 prints "Medical Readiness: Hospital present" off the same flag — the engine\'s own word (rule 3), which the closing essay §5 omits. NOTE the CT\'s F1-14 keeps "a HOSPITAL or infirmary BUILDING" on the same evidence: the fold contradicts itself; see CHALLENGE list.')
ok('RT2.1-20',C+' :65 fires on "priest","shrine", and on Access to parish church (institutionalCatalog.js:50-54 "Walk 2-5km to village church").')
ok('RT2.1-21',C+' PORT_INFRA_RE :32, :61.')
ok('RT2.1-22',C+' conditional on a naval row; safe.')
ok('RT2.1-23',C+' holder-layer bar.')
ok('RT2.1-24',C+' rulingStructure.js:284, :452.')
ok('RT2.1-25',C+' class word.')
ok('RT2.1-26',C+' rulingStructure.js:762-767; holderTable.js:661.')
ok('RT2.1-27',C+' no defense pool reads per-faction captureState (holderTable.js:136-141 reads it for capture only); template harmless.')
ok('RT2.1-28',C+' wiring; nothing handed back.')
ok('RT2.1-29',C+' floor 3.')
ok('RT2.1-30',C+' defenseDisplay.js:183-195; label "Organized Syndicate" at :162.')
ok('RT2.1-31',P+' no landed pool; VIS-01 governs.')
ok('RT2.1-32',P+' not a defense read.')
ok('RT2.1-33',C+' person rule relaxed; DS-DEF-9 reads magicDependency so a practitioner exists where it fires.')
ok('RT2.1-34',C+' engine string; RT2.1-24 keeps the label.')
ch('RT2.1-35',C+' "put men on the wall of a walled town" on a walls-only town sits beside the "NO organized force at all" pool (defenseStateProse.js:1273-1274); the permission should carry the force label trap.')
ch('RT2.1-36',C+' "the column on the road" asserted as PRESENT contradicts an empty besiegedBy (holderTable.js:196 → warStatus.js:297); the threat pools are hypothetical (F1-34). Qualify to the hypothetical frame.')
ch('RT2.1-37',P+' "use the line for either" must carry F1-07\'s qualifier ("a line around the town" is a wall claim) on unwalled towns; the closing essay\'s join argument is a page-grain finding of NF-10\'s class, not a per-face one. Strike stands; permission under-qualified.')
ok('RT2.1-38',C+' forces.charter.present.')
ok('RT2.1-39',C+' institutionalCatalog.js:104; defenseStateProse.js:1273-1274; and threatDefensePolicy.js:13 lists Household levy as a force the buckets miss. Engine contradiction; nothing handed back.')
ok('RT2.1-40',C+' wiring.')
ok('RT2.1-41',C+' wiring.')
ok('RT2.1-42',C+' occupationStatus.js:95-103 has no garrison field; permission split correctly.')
ok('RT2.1-43',C+' organ word.')
ok('RT2.1-44',C+' safetyProfile.js:281 bakes the function word.')
ok('RT2.1-45',C+' defenseDisplay.js:189.')
ok('RT2.1-46',C+' corrected cell hands back nothing; the nouns are governed by RT2.1-19/-20. Verdict as a restatement is fine.')
ok('RT2.1-47',C+' safetyProfile.js:56-62 community bonus; permission qualified "where the town has them".')
ok('RT2.1R-01',C+' research.')
ok('RT2.1R-02',C+' defenseGenerator.js:177-178.')
ok('RT2.1R-03',C+' safetyProfile.js:281/:288/:297/:307 bake "The watch".')
ok('RT2.1R-04',C+' wiring.')
ok('RT2.1R-05',C+' :1273.')
ok('RT2.1R-06',C+' fieldSynonyms.js:51.')
ok('RT2.1R-07',C+' count.')
ok('RT2.1R-08',C+' role bar; slot label binds via RT2.1-24.')
ok('RT2.1R-09',C+' tooling.')
ok('RT2.1R-10',C+' :300.')
ch('RT2.1R-11',C+' the "no field denies it" template is false on a watchless town (hasWatch :48 / safetyProfile.js:300); RT2.1-13\'s KEPT half governs and the cell should say so.')
ok('RT2.1R-12',C+' research.')
ok('RT2.1R-13',C+' citation machinery.')
ok('RT2.1R-14',C+' a citation on a captured watch reveals no capture; the covert model (F4-13) still binds the capture itself.')
# ---- 2.2 general
ok('RT2.2-01',C+' kept :48; duty bar struck is silence.')
ok('RT2.2-02',C+' :46.'); ok('RT2.2-03',C+' holderTable.js:280-287.')
ok('RT2.2-04',C+' :49-51 (hireling hall in hasMercenary AND hasCharterHall) vs buckets :98-104 (in neither). NF-1.')
ok('RT2.2-05',C+' :51.'); ok('RT2.2-06',C+' :52-53.')
ok('RT2.2-07',C+' noun is "the court" only; defenseDisplay.js:231 prints "Court only" off the hall; safetyProfile.js:330. See RT2.1-14 for the courthouse noun.')
ok('RT2.2-08',C+' :54.')
ok('RT2.2-09',C+' institutionServices.js:1625 "before a magistrate" is the engine\'s own; an unnamed person is a hook.')
ok('RT2.2-10',C+' institutionServices.js:1448-1453 consensus below town; Town hall row at institutionalCatalog.js:1550 (town section).')
ok('RT2.2-11',C+' holderTable.js:332-336; governanceNarrative.js:101-105.')
ok('RT2.2-12',C+' person rule relaxed.')
ok('RT2.2-13',C+' citation rule.'); ok('RT2.2-14',C+' citation rule.')
rv('RT2.2-15',C+' should be SPLIT | priorityHelpers.js:53 hasGates false; safetyProfile.js:464 prints "no gates to bribe and no checkpoints to avoid" | floor 1. The template "no field in the record denies it" is false; the CT\'s own F1-08 keeps "a GATE, a checkpoint, a toll-bar". Worst: "the toll-bar takes its cut of everything that comes in" on an ungated village.')
ok('RT2.2-16',C+' record word; R-8 (a roll CITED needs the holder) still binds via F1-24.')
ok('RT2.2-17',C+' citation bar.'); ok('RT2.2-18',C+' layer bar.')
ok('RT2.2-19',C+' generalStateProse.js:1109/:1138-1152 — Black market matches MARKET_NAME.')
ok('RT2.2-20',C+' :65-67.')
rv('RT2.2-21',C+' should be SPLIT | priorityHelpers.js:63; no granary row below town (F1-09) | floor 1. The CT\'s F1-09 lists RT2.2-21 in its FOLDED column as a surviving id while this file strikes it with the blanket template. Worst: "the storehouse is full" on a hamlet.')
ok('RT2.2-22',C+' :64; defenseDisplay.js:237 "Hospital present" off the same flag. Same CT/F1-14 tension as RT2.1-19.')
ok('RT2.2-23',C+' :32, :61-62.'); ok('RT2.2-24',C+' :57-58.'); ok('RT2.2-25',C+' :68-71.'); ok('RT2.2-26',C+' :72-76.')
ok('RT2.2-27',C+' wiring.'); ok('RT2.2-28',C+' slots.')
ok('RT2.2-29',C+' institutionServices.js:1561-1565; "watchtower".includes("watch") satisfies hasMilitaryInst :45 but not hasWatch :48.')
ok('RT2.2-30',C+' research.')
ch('RT2.2-31',P+' role-word family: "the sexton" presupposes a church row, "the warden" a Warden\'s Lodge — a role inherits its body\'s label trap (F1-11); the template does not say so.')
ok('RT2.2-32',C+' wiring.'); ok('RT2.2-33',C+' wiring.'); ok('RT2.2-34',C+' wiring.'); ok('RT2.2-35',C+' wiring.')
ok('RT2.2-36',C+' holderTable.js:141, :661; rulingStructure.js:762-767.')
ok('RT2.2-37',C+' floor 3.'); ok('RT2.2-38',C+' the pool reads the tie.')
ok('RT2.2-39',C+' label trap kept.')
ok('RT2.2R-01',C+' safetyProfile.js:300; factionDynamics.js:232.')
ok('RT2.2R-02',C+' Barracks is a row (:46, buckets :89).')
ok('RT2.2R-03',C+' :1109.'); ok('RT2.2R-04',C+' citation machinery.'); ok('RT2.2R-05',C+' role bar.')
ok('RT2.2R-06',C+' research; floor 3 holds the person rule.'); ok('RT2.2R-07',C+' research (the gloss "about the layer vocabulary" is wrong of it — F8 — but the verdict is right).')
ok('RT2.2R-08',C+' computation detail.'); ok('RT2.2R-09',C+' research.')
ch('RT2.2R-10',C+' defenseGenerator.js:467-472 publishes FOUR gates (military, monster, internal, economic); "one purse" is true of the MILITARY gate only (wall maintenance + wages, :182). The permission is right for that gate; the ground should name it.')
ok('RT2.2R-11',C+' corrected: a cite correction, nothing handed back.')
# ---- 2.3 economy
ok('RT2.3-01',C+' the fill names a row the town has.'); ok('RT2.3-02',C+' wiring.'); ok('RT2.3-03',C+' wiring.'); ok('RT2.3-04',C+' wiring.')
rv('RT2.3-05',C+' should be SPLIT | priorityHelpers.js:63; foodStockpile.js:192-194 computes the stock band with NO granary row (falls to the tier default), so DS-ECO-2 fires granary-less (CT §1.6 W-07) | floor 1. "write the granary doors on a stock read" licenses a building the roster denies. Worst: "the granary doors are barred" on a village. RT2.1-18, RT2.4-04, RT2.5-07, RT2.6-20 all keep this trap.')
ok('RT2.3-06',C+' :56.'); ok('RT2.3-07',C+' foodStockpile.js:194 substring "mill".'); ok('RT2.3-08',C+' :57.')
rv('RT2.3-09',C+' should be SPLIT | institutionServices.js:1448-1453 (consensus, not a room); no hall row in the village section (institutionalCatalog.js:451-922; Town hall at :1550 is town) | floor 1. "the hall as the place a trade leans on" is a place claim below town; RT2.2-10, RT2.4-02, RT2.6-12 keep this half. Worst: "the weavers lean on the hall for their charter" at a hamlet.')
ok('RT2.3-10',C+' never fires.'); ok('RT2.3-11',C+' :52.'); ok('RT2.3-12',C+' :48.')
rv('RT2.3-13',C+' should be SPLIT | priorityHelpers.js:60 (hasWarehouse; F1-19 folds RT2.5-09); generalStateProse.js:1109 MARKET_NAME includes "stalls" so "the stalls" asserts a market (F1-10) | floor 1. The generics (yard, house, quarter, workings, stores) are free; "the warehouses" and "the stalls" are not. Worst: "the warehouses along the quay stand empty" at a village.')
ok('RT2.3-14',C+' W24 struck as a class; F2-01/F1-24 keep the truth-bearing cases.')
ok('RT2.3-15',C+' standpoint words.'); ok('RT2.3-16',C+' citation question.'); ok('RT2.3-17',C+' oblique naming.')
ok('RT2.3-18',C+' research.'); ok('RT2.3-19',C+' permission qualified "where the town has it".')
ok('RT2.3-20',C+' safetyProfile.js:619-638 computes blackMarketCapture off criminalEffective + stress, independent of the ladder.')
ok('RT2.3-21',C+' holderTable.js:166 incomeSources → treasury.')
ch('RT2.3-22',C+' the "write the sentence" template is applied to a READ path, not a noun; the cell should read "nothing handed back — a read, not a noun". Harmless.')
ch('RT2.3-23',C+' as RT2.3-22.')
ok('RT2.3R-01',C+' layer.'); ok('RT2.3R-02',C+' unwired.'); ok('RT2.3R-03',C+' layer.'); ok('RT2.3R-04',C+' W24.'); ok('RT2.3R-05',C+' vocabulary.')
ok('RT2.3R-06',C+' EconomicsTab.jsx:664 is a frozen literal; nothing handed back.')
for i in ['RT2.3R-07','RT2.3R-08','RT2.3R-09','RT2.3R-10']: ok(i,C+' corrected: cite correction, nothing handed back.')
# ---- 2.4 power
ok('RT2.4-01',C+' :48; :300.'); ok('RT2.4-02',C+' as RT2.2-10.'); ok('RT2.4-03',C+' :52.'); ok('RT2.4-04',C+' :63.')
ok('RT2.4-05',C+' institutionServices.js:530.'); ok('RT2.4-06',C+' criminalOpRole.js:38-46.')
ok('RT2.4-07',C+' the assembly sense; the seat exists at every tier.')
ok('RT2.4-08',P+' governingName rulingStructure.js:787 confirmed; the council-lens read not resolved.')
ch('RT2.4-09',C+' should be SPLIT: the row bundles the prison/gaol (kept at RT2.1-15/RT2.2-08; priorityHelpers.js:54; defenseDisplay.js:231 prints the denial) and the temple (kept at RT2.6-29; :65) with the clearinghouse. The permission cell licenses only the clearinghouse, so no false sentence is handed back — but the VERDICT strikes a five-noun row outright. Fidelity 9c asked for this in the closing; it was not added.')
ok('RT2.4-10',C+' a verb on this desk.'); ok('RT2.4-11',C+' R-vi struck.'); ok('RT2.4-12',C+' vocabulary.'); ok('RT2.4-13',C+' shipped word.'); ok('RT2.4-14',C+' class word.'); ok('RT2.4-15',C+' layer.'); ok('RT2.4-16',C+' person rule relaxed.'); ok('RT2.4-17',C+' floor 3.')
ch('RT2.4-18',P+' "the captain" — the engine emits Watch Captain only with linkToInst /watch|garrison|barracks|militia/ (RT2.6-38 verbatim): the role presupposes the body and inherits F1-01/F1-02. The template should say so.')
ok('RT2.4-19',C+' rulingStructure.js:787, :792.'); ok('RT2.4-20',C+' powerStateProse.js:860, :875-876.')
ok('RT2.4-21',C+' stressFactions.js:105-107.'); ok('RT2.4-22',C+' settlementPolitics.js:461-465; brokeragePatronage.js:60.'); ok('RT2.4-23',C+' factionDynamics.js:132-133.')
ok('RT2.4R-01',C+' floor 3.'); ok('RT2.4R-02',C+' :300; rulingStructure.js:596.')
rv('RT2.4R-03',C+' should be SPLIT | priorityHelpers.js:48 hasWatch; safetyProfile.js:300; the engine itself gates the role on the body (Watch Captain linkToInst /watch|garrison|barracks|militia/) | floor 1. "write a watch captain" unqualified. Worst: "the watch captain takes the bribe" on a thorp with no law body.')
ok('RT2.4R-04',C+' wiring.'); ok('RT2.4R-05',C+' unwired.'); ok('RT2.4R-06',C+' wiring (NF-3).'); ok('RT2.4R-07',C+' research.'); ok('RT2.4R-08',C+' count.'); ok('RT2.4R-09',C+' corrected: cite correction.')
# ---- 2.5 stressors
ok('RT2.5-01',C+' :52.'); ok('RT2.5-02',C+' :52-53.'); ok('RT2.5-03',C+' :46.'); ok('RT2.5-04',C+' person plural.')
ok('RT2.5-05',C+' safetyProfile.js:30-35 watchLabel.')
ch('RT2.5-06',C+' activeConditions.js:342 is the engine\'s word on the army_deployed condition ONLY; "the town\'s army" on a town on the "NO organized force at all" pool (defenseStateProse.js:1274) contradicts the same dossier (F1-25). Qualify.')
ok('RT2.5-07',C+' :63.'); ok('RT2.5-08',C+' :56.'); ok('RT2.5-09',C+' :60.')
ch('RT2.5-10',C+' the KEPT half says "at thorp/hamlet" — VILLAGE is omitted, and no hall row is seated at village either (institutionalCatalog.js village section :451-922 carries none; Town hall :1550). RT2.2-10/F1-20 say "below town tier". A village hall is licensed by this row and denied by its siblings.')
ok('RT2.5-11',C+' :55; institutionVocabulary.js:284 defines Courthouse as a building.')
ch('RT2.5-12',C+' stressorDynamics.js:844 is verbatim; but "run dry" beside "Economic Backing: Well-funded" on the Defense panel is a cross-tab contradiction under R-12. Qualify to the treasury-strained reads.')
ok('RT2.5-13',C+' religious BODY kept; floor 3.'); ok('RT2.5-14',C+' route word.'); ok('RT2.5-15',C+' generic craft class.'); ok('RT2.5-16',C+' research.'); ok('RT2.5-17',C+' archetype class word.'); ok('RT2.5-18',C+' asserts no row.')
ok('RT2.5-19',C+' institutionalCatalog.js:845; npcGenerator.js:1035.'); ok('RT2.5-20',C+' never rendered (the corpus counts are the survey\'s own; not re-counted).')
ok('RT2.5-21',C+' self-qualified on quarantine.'); ok('RT2.5-22',C+' class word.'); ok('RT2.5-23',C+' class word.'); ok('RT2.5-24',C+' class words.')
ch('RT2.5-25',P+' "the ruler" (a singular person) beside a governingName of "Town council" / "Democratic assembly" printed on the page — the seat label binds (RT2.1-24/RT2.4-19). Qualify: a ruler where the seat renders a person-shaped label.')
ok('RT2.5-26',C+' class word; the pool fires only on the occupied token.'); ok('RT2.5-27',C+' class words.'); ok('RT2.5-28',C+' person rule relaxed.')
ch('RT2.5-29',P+' "captain" — as RT2.4-18: the role presupposes the body.')
ok('RT2.5-30',C+' unnamed persons.'); ok('RT2.5-31',C+' stressorDynamics.js:850 is the engine\'s own "The streets rose".'); ok('RT2.5-32',C+' wiring.')
ok('RT2.5-33',C+' stressorDynamics.js:790-796.'); ok('RT2.5-34',C+' :877 palace_coup default.'); ok('RT2.5-35',C+' research (gloss wrong — F8 — verdict right).')
ok('RT2.5-36',C+' "the town\'s own furniture" is self-limiting to bodies the town has.')
ok('RT2.5R-01',C+' count.'); ok('RT2.5R-02',C+' corrected.'); ok('RT2.5R-03',C+' corrected.'); ok('RT2.5R-04',C+' R-6; the flag on THIS town.'); ok('RT2.5R-05',C+' research.'); ok('RT2.5R-06',C+' research.'); ok('RT2.5R-07',C+' research.'); ok('RT2.5R-08',C+' bars removed; the rows exist.'); ok('RT2.5R-09',C+' corrected.'); ok('RT2.5R-10',C+' wiring.'); ok('RT2.5R-11',C+' research (gloss wrong — F8).'); ok('RT2.5R-12',C+' research.'); ok('RT2.5R-13',C+' safetyProfile.js:30-35.'); ok('RT2.5R-14',C+' count.'); ok('RT2.5R-15',C+' defenseGenerator.js:244-253 "watch wages, court and gaol funding".'); ok('RT2.5R-16',C+' vocabulary.'); ok('RT2.5R-17',C+' stressorDynamics.js:844 etc are the engine\'s own.'); ok('RT2.5R-18',C+' patrols free (F1-01).'); ok('RT2.5R-19',C+' corrected.')
# ---- 2.6 warFaith
ok('RT2.6-01',C+' On campaign is the engine\'s own label.'); ok('RT2.6-02',C+' the occupier\'s men; occupationStatus.js:95-103.')
ok('RT2.6-03',C+' treatyDocument.js:58 vs :63.'); ok('RT2.6-04',C+' treatyDocument.js:58 "the compelled banner".')
ok('RT2.6-05',C+' occupationStatus.js:95-103 has no garrison field; the TOWN\'s garrison needs :46.'); ok('RT2.6-06',C+' treatyDocument.js:68.')
ok('RT2.6-07',C+' "militia" 0 hits in warFaith.generated.js — template true here.'); ok('RT2.6-08',C+' NF-1 wiring.'); ok('RT2.6-09',C+' "charter hall" 0 hits — template true.')
ok('RT2.6-10',C+' qualified "where the town has one".'); ok('RT2.6-11',C+' "barracks" 0 hits — template true.'); ok('RT2.6-12',C+' as RT2.2-10.'); ok('RT2.6-13',C+' rulingStructure.js:762-767.')
ok('RT2.6-14',C+' treatyDocument.js:72-76 "the installed seat" vs religionState.js:620 (patron/seat referent); two referents on one page.')
ok('RT2.6-15',C+' occupationStatus.js:96 (occupier settlement) vs warStatus.js:333-335 (installed governingName).')
ok('RT2.6-16',C+' surround the phrase.'); ok('RT2.6-17',C+' vocabulary.'); ok('RT2.6-18',C+' corrected: pool unroutable, nothing ships.')
rv('RT2.6-19',C+' should be CONTRADICTION | priorityHelpers.js:56 hasMarket / generalStateProse.js:1109 MARKET_NAME; faces at warFaith.generated.js:58 ("the hall still sits, the market still opens") and :4559 ("the season and the market") | floor 1. The template "no shipped face here uses the word" is FALSE (finding 4\'s shape on a row the fidelity pass did not name). Worst: "the market still opens" on an occupied hamlet with no market row.')
ok('RT2.6-20',C+' :63.'); ok('RT2.6-21',C+' standpoint.'); ok('RT2.6-22',C+' qualified "where the roster seats them".')
rv('RT2.6-23',C+' permission should be RT2.1-46\'s corrected cell (nothing handed back; the noun is governed by RT2.1-20/RT2.2-20) | priorityHelpers.js:65 fires on "Access to parish church" = "Walk 2-5km to village church" (institutionalCatalog.js:50-54); governanceNarrative.js:128-130 | floor 1. The blanket "no field in the record denies it" is false — the exact shape fidelity finding 5 corrected on RT2.1-46, uncorrected here. Worst: "the parish keeps the register of the dead" at a hamlet whose church is 2-5 km away.')
ch('RT2.6-24',C+' the template "no shipped face here uses the word" is false for "the road" (7 hits in warFaith.generated.js; the row\'s own verbatim says the pilgrim pools speak of it); the toll-bar/census/tradition halves are true (0 hits). Harmless — a road asserts nothing the roster denies — but the claim about the corpus is false.')
ok('RT2.6-25',C+' treatyDocument.js:359-361; treatyOrientation.js:166-176.'); ok('RT2.6-26',C+' the label arrives through the slot.'); ok('RT2.6-27',C+' floor 3 as ADDENDUM 15 amends it.')
ok('RT2.6-28',C+' religionState.js:620 isPatron vs brokeragePatronage.js:60.'); ok('RT2.6-29',C+' :65.')
rv('RT2.6-30',C+' should be SPLIT | priorityHelpers.js:65; institutionalCatalog.js:50-54 ("Walk 2-5km to village church") | floor 1. "the parish church" is a BUILDING the F1-11 trap keeps (RT2.6-29 on the same desk); the graveyard half is free. Worst: "the parish church\'s roof lets the rain in" at a hamlet whose church is in another settlement.')
ok('RT2.6-31',C+' governanceNarrative.js:128-130.'); ok('RT2.6-32',C+' person plural; F2-01 bars the count.')
ch('RT2.6-33',C+' "the fabric of the place" presupposes a religious building; on a town with no religious row F1-11/RT2.6-29 deny the roof, the stonework. The slot never fills today so nothing ships, but a NEW face written on this permission would.')
ok('RT2.6-34',C+' corrected.'); ok('RT2.6-35',C+' the CULTS pool fires only with cults.'); ok('RT2.6-36',C+' inside the authored phrase.'); ok('RT2.6-37',C+' wiring.')
ch('RT2.6-38',P+' "write any of them, acting" — the guildmaster, the sexton, the high priestess, the watch captain each presuppose a body the roster may deny (F1-16, F1-11, F1-01); the role-word strike is right, the permission is unqualified.')
ok('RT2.6-39',C+' vocabulary.'); ok('RT2.6-40',C+' holderTable.js:599-615 resolves on the settlement passed.')
ok('RT2.6R-01',C+' consistent with RT2.1-42; treatyDocument.js:68 bakes "The garrison keeps the walls" for the occupier.'); ok('RT2.6R-02',C+' governanceNarrative.js:98, :148; :300.'); ok('RT2.6R-03',C+' research feeding NF-1.')
ok('RT2.6R-04',P+' treatyDocument.js:359-361 confirmed; warFaithStateProse.js:690-694 not resolved.'); ok('RT2.6R-05',C+' as RT2.6-15.'); ok('RT2.6R-06',C+' as RT2.6-03.'); ok('RT2.6R-07',C+' floor 3.'); ok('RT2.6R-08',C+' holderTable.js:141, :661.'); ok('RT2.6R-09',C+' wiring.'); ok('RT2.6R-10',C+' licence question.'); ok('RT2.6R-11',C+' vocabulary.'); ok('RT2.6R-12',C+' holderTable.js:199, :599-615.'); ok('RT2.6R-13',C+' citation rule.'); ok('RT2.6R-14',C+' governanceNarrative.js:128-130.')
ch('RT2.6R-15',P+' as RT2.5-25.')
ok('RT2.6R-16',C+' corrected.'); ok('RT2.6R-17',C+' research.'); ok('RT2.6R-18',C+' count.'); ok('RT2.6R-19',C+' corrected.')

missing=[r['id'] for r in rows if r['id'] not in N]
assert not missing, missing
from collections import Counter
byv=Counter(r['verdict'] for r in rows); marks=Counter(N[r['id']][0] for r in rows)
byvm=Counter((r['verdict'],N[r['id']][0]) for r in rows)
out=[]
out.append('| id | recorded verdict | noun | VALIDATION | note (label · evidence) |\n|---|---|---|---|---|')
for r in rows:
    mark,note=N[r['id']]
    out.append(f"| {r['id']} | {r['verdict']} | {r['noun'].replace('|','/')} | **{mark}** | {note.replace('|','¦')} |")
open(f'{SC}/validation-rows.md','w',encoding='utf-8').write('\n'.join(out)+'\n')
print(len(rows), dict(byv), dict(marks))
for k,v in sorted(byvm.items()): print(k,v)
