import json
base="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep"
src=json.load(open(base+"/chunks/dnd-22.json"))
V=[
 (484,"VERIFIED_VERBATIM","Room descriptions in thick, indigestible paragraphs",None,"Raw HTML fetched (200, 51KB) and tag-stripped. Body: 'These are the usual early TSR bugaboos with the module; Room descriptions in thick, indigestible paragraphs and notes on monster placement in rooms other then the one where the monster is actually placed...' Byline PrinceofNothing, dated 2021/07/31."),
 (485,"VERIFIED_VERBATIM","There are also the odd Victorian room catalogs",None,"Same paragraph: 'There are also the odd Victorian room catalogs (i.e. this room has 23 halbeards, 315 arrows and 5 casks of oil).' The parenthetical confirms the 'itemised room contents' limb."),
 (486,"VERIFIED_VERBATIM","A vast catalogue of seemingly mundane NPCs are presented",None,"Verbatim in the village paragraph: 'A vast catalogue of seemingly mundane NPCs are presented, but underneath the facade of rural simplicity is a web of intrigue, espionage...'"),
 (487,"VERIFIED_VERBATIM","creates the appearance of a world in flux, a continuous place, a living world",None,"Paragraph opens 'Little details in the village. Unscrupulous merchants that sell broken down nags... Stores with prices that are a few percentage points higher or lower then standard, availability, a lengthy list of drinks and meals at the inn. It affects gameplay but it also creates the appearance of a world in flux, a continuous place, a living world.' Both the commercial-detail limb and the continuous/living-world limb are on the page."),
 (488,"VERIFIED_VERBATIM","subsequent module design would be considerably sparser on their starting town details",None,"Verbatim: '...up almost half the adventure, and subsequent module design would be considerably sparser on their starting town details, but I suspect this level of detail... will come'. 'after T1' = 'subsequent'."),
 (489,"VERIFIED_VERBATIM","Author Carl Sargent was a master at implying terrifying things with a few carefully chosen words",None,"Raw HTML fetched (200, 74KB). Byline 'by John Roy', Oct 21, 2024, title 'Greyhawk Returns in the 2024 Dungeon Master's Guide'. Sentence follows three paragraphs on the Greyhawk supplement 'Iuz the Evil', so the 'Greyhawk author' limb is supported; full page wording adds 'that suggested more than they described.'"),
 (490,"VERIFIED_VERBATIM","descriptions of Oerth's nations in the chapter's Greyhawk Gazetteer, along with their history of conflict",None,"Verbatim, in the 'A Battle-Ready World' section, whose preceding sentence names 'The Greyhawk campaign setting in the 2024 Dungeon Master's Guide', supporting the '2024 DMG's' limb; page continues 'and what strife they're currently facing.'"),
 (491,"VERIFIED_VERBATIM","He provided each nation's imports and exports and the trade routes they used to transport them",None,"Verbatim in the 'Keeping It Real' section, subject 'Gygax' established two sentences earlier ('Gygax laid out not only the current nations of Oerik...'). Section heading is 'Keeping It Real', not the claim's page hint 'wargamer's setting', but the hint is not a limb of the claim."),
 (492,"VERIFIED_VERBATIM","The first part is the gazetteer proper, covering the history, politics, and society of the Grand Duchy, including descriptions of its most important locales and NPCs",None,"Raw HTML fetched (200, 23KB). Preceding sentence 'The module is divided into two sections' supports the 'half' limb; posted by James Maliszewski."),
 (493,"PARTIAL","the module boasted of providing 'a complete historical, economical [sic], geographical, and sociological overview'","that the quoted boast is GAZ1's cover copy","The quotation is verbatim on the page (with a bracketed [sic] after 'economical'), and the four adjectives plus 'complete... overview' all match. But the page attributes it only to 'the module boasted of providing' — it never says the wording is the cover/back-cover copy, so that attribution limb rests on outside knowledge, not this page."),
 (494,"PARTIAL","Scattered throughout the module are numerous maps for use in play, like typical taverns and manor houses","rather than only named ones","'typical taverns and manor houses' is verbatim. The page draws no contrast with named/specific taverns; the only contrast it makes is with the poster-sized map ('This is in addition to the large, poster-sized map of the Grand Duchy, its capital city of Specularum, and the frontier town of Threshold'), which is a different contrast from the one the claim asserts."),
 (495,"VERIFIED_VERBATIM","the focus of Gaz 1 is not on all the exciting adventure locations... but rather, everything around those adventures, setting up the framework",None,"Raw HTML fetched (200, 57KB), princeofnothingblogs 2020/03/30. Both limbs (not the adventure locations / everything around them) are in the same sentence."),
 (496,"VERIFIED_VERBATIM","In the hands of a lesser man, a boring encyclopedic recitation of meaningless and sometimes mutually contradictory drivel",None,"Verbatim, immediately after the sentence verified for 484-index 495; 'In the hands of a lesser man' establishes it as the form's failure mode, contrasted with 'In the hands of Aaron Allston... the whole becomes compelling'."),
 (497,"VERIFIED_VERBATIM","Setting history is given in broad sweeping strokes",None,"Verbatim at the start of its paragraph, continuing 'that serve the goal of hinting at prior ages from which the GM may readibly draw inspiration for a whole flock of dungeons.'"),
 (498,"VERIFIED_VERBATIM","The capital city of Specularum gets an extensive treatment in terms of neighborhoods, main streets, ducal palace etc.",None,"Verbatim; the paragraph does begin 'Contrary to what you might believe there's actual content in this damn Gazzeteer as well', matching the page hint."),
]
verdicts=[]
for idx,v,tw,ul,note in V:
    d={"index":idx,"verdict":v,"trueWording":tw,"note":note}
    if ul: d["unsupportedLimb"]=ul
    verdicts.append(d)
assert [d["index"] for d in verdicts]==src["indices"], "index mismatch"
out={"name":"dnd","chunk":22,"claims":src["claims"],"verdicts":verdicts}
p=base+"/verdicts-dnd-i484-498.json"
json.dump(out,open(p,"w"),indent=1,ensure_ascii=False)
print("wrote",p,len(json.dumps(out)))
