import json
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/ai-12.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-ai-i678-692.json"
d=json.load(open(src,encoding="utf-8"))
V=[
(678,"VERIFIED_VERBATIM","Leaving aside the quality of the prose entirely, the sheer repetition of elements will remove the material from serious consideration.","Raw live page (curl, browser UA, HTTP 200). Quote exact. Editorial framing supported by the same paragraph: 'if you're an editor, you'll see the current AI tropes dozens of times with each new iteration.'"),
(679,"VERIFIED_VERBATIM","If you want a fast, infinite generator of competently-assembled bullshit, AI is your go-to source.","Raw live page. Quote exact. Second limb supported in the same paragraph: 'it has no ability to differentiate between truth and nonsense.'"),
(680,"VERIFIED_VERBATIM","The amount of work required by a human to make AI-generated text go from 'serviceable on the sentence level' to 'actually good' is enough that one wonders why one wouldn't just skip the AI-generating text part entirely. It would be less work.","Raw live page. Quote exact and both limbs (the serviceable/actually-good gap, and skipping the generation step being less work) are in one sentence pair."),
(681,"VERIFIED_VERBATIM","But mostly, it's because I write better than 'AI' can or ever will, and I can do it with far less energy draw.","Raw live page, dated 'Posted on February 14, 2026', numbered point 1, which opens 'I don't and won't use \"AI\" in the text of any of my published work.' Page says 'mostly'; the claim's weaker 'partly' is still supported since the post lists several reasons."),
(682,"VERIFIED_VERBATIM","There is no statistical model that can create what is uniquely you.","Raw live page. Quote exact, and it is the final sentence of the point-10 closing paragraph, immediately preceding the '- JS' sign-off, as the claim's page hint states."),
(683,"VERIFIED_VERBATIM","Over the past couple of years, LLMs have improved considerably in performing patter-recognition tasks. ... But more powerful software has so far not led to better machine-generated fiction.","Raw live page comment thread; comment byline 'Fatman / February 15, 2026, 9:50 am' matches exactly. Quote exact. The pattern-recognition limb is the preceding sentence (original contains the typo 'patter-recognition')."),
(684,"VERIFIED_VERBATIM","No, John. You do not write better than AI ever will. At some point, perhaps in two years, perhaps in seven, AI will be better at writing than you are.","Raw live page. Original is Quill's own comment, 'February 15, 2026, 1:01 am'; Fatman re-quotes it verbatim at 9:50 am, so the claim's 'quoted by another commenter' also holds. Note the page hedges ('At some point, perhaps in two years, perhaps in seven'); the claim's 'within roughly two to seven years' is a fair but slightly tighter rendering."),
(685,"VERIFIED_VERBATIM","It is you giving it the parameters of a block of text, and saying, 'Fill this space with the shape of the thing I'm asking about.' It will conjure not an answer, but an answer-shaped thing.","Live URL soft-404s to the site homepage for non-browser clients (HTTP 200 but wrong document; a nonsense slug returns the same page). Verified on the Wayback raw capture 20260618213915id_ and confirmed identical in captures 20250524060542id_ and 20250530191023id_. Quote exact; both limbs in consecutive sentences."),
(686,"VERIFIED_VERBATIM","It is, almost literally, a super-fancy lorum ipsum generator.","Wayback raw captures (three, identical). Quote exact including the post's own misspelling 'lorum', and 'almost literally' is Wendig's own wording."),
(687,"VERIFIED_VERBATIM","The paragraphs have words, sometimes big words, and lots of sentences, but they frequently say nothing.","Wayback raw captures. Comment byline 'bluespiderwort says:' timestamped 'May 21, 2025 - 6:51 PM' on that post's thread. Quote exact; the full sentence carries the 'lots of sentences, but frequently say nothing' limb."),
(688,"VERIFIED_VERBATIM","Paragraphs into my nascent mystery, it had no idea what was happening; or at least, not enough of an idea to 'participate' in any meaningful way.","Raw live page (robinsloan.com, HTTP 200). Quote exact. Supporting limbs on the same page: the story was 'commissioned by Google and produced using a new AI-powered editor called Wordcraft'; Sloan 'liked the idea of giving the AI the role of the detective' in 'some kind of locked-room mystery'."),
(689,"VERIFIED_VERBATIM","It knew I was writing a mystery; it reached for the appropriate terms and tropes; but that wasn't anywhere close to being sufficient.","Raw live page. Quote exact and every limb of the claim is in this single sentence."),
(690,"VERIFIED_VERBATIM","Then, I cracked it, by establishing a fenced-in space for the AI to contribute what it could.","Raw live page. Quote exact. Next paragraph supplies the assignment limbs: 'very good at riffing', 'This new story called for a litany of grisly deaths, so, I asked the AI to dream up grisly deaths. I asked it, also, to tell me the names of the dead: characters from a fantasy saga.' 'Rather than any structural role' is not phrased that way on the page but is entailed by the abandoned detective role that 'didn't work at all' immediately above."),
(691,"VERIFIED_VERBATIM","But, third: I have to report that the AI did not make a useful or pleasant writing partner. Even a state-of-the-art language model cannot presently 'understand' what a fiction writer is trying to accomplish in an evolving draft.","Raw live page. Quote exact, and it is indeed the third of the 'Three thoughts, to close.' Both limbs are consecutive sentences."),
(692,"VERIFIED_VERBATIM","forwarding the transcripts of those sessions doubly so (perhaps triply so, given the verbosity of chatbot responses)","Raw live page (pluralistic.net, HTTP 200), 'No one wants to read your AI slop (02 Mar 2026)', byline Cory Doctorow, March 2, 2026. Quote exact, inside the paragraph that begins 'The same is true of your conversations with chatbots', and it is genuinely a parenthetical aside - 'in passing' is accurate."),
]
verdicts=[{"index":i,"verdict":v,"trueWording":t,"note":n} for (i,v,t,n) in V]
assert [x["index"] for x in verdicts]==d["indices"], "index mismatch"
json.dump({"name":"ai","chunk":12,"claims":d["claims"],"verdicts":verdicts},open(out,"w",encoding="utf-8"),ensure_ascii=False,indent=1)
print("wrote",out)
