#!/bin/sh
# run-registers-904.sh <dock> — the §904 register acts at the L-UI-MAT tip (2 cars over dd5f13218), LAST, in DESK-LANDING-PLAN.md §3 order
# with the dirty-tree doors FIRST (the lighting door refuses porcelain): lighting → commit (register car 1) → mounts baseline door,
# prose-numerics re-key, writer-reach --write, plain re-runs as receipts → the chair commits register car 2 by hand after reading the diff.
# Drafted 2026-09-06 18:00 from run-registers-903.sh. DIFFERENCES FROM §903, each a prediction from predict-904.log (taken at c2337220a):
#   • NO OSR --write (the plain read matched the frozen inventory exactly and no execution input drifted; a scanned source — flagRegistry.js —
#     may change freely under provenanceDriftOf); the CLI dry read + the walker's plain run are the receipts, and a non-zero here is a STOP.
#   • TUNING: no refreeze door (no tuning table moved); the walker's PLAIN run is the receipt.
# Every door under the gate mutex; refreeze doors exit NON-ZERO on success by design. Prints a PREDICTIONS line first (E4).
SC=/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad
BASE=dd5f1321825b58fed2db54e9473440a310195eed
D=$1; [ -d "$D" ] || { echo "usage: <dock>"; exit 9; }; cd "$D" || exit 9
[ -z "$(git status --porcelain -uall)" ] || { echo "REFUSED: dock dirty"; exit 8; }
[ "$(git rev-list --count $BASE..HEAD)" = "2" ] || { echo "REFUSED: expected 2 cars over dd5f13218 before the register cars, found $(git rev-list --count $BASE..HEAD)"; exit 8; }
[ -f "$SC/whole-904.log" ] && grep -q '^PROOF_EXIT=' "$SC/whole-904.log" || { echo "REFUSED: the §904 proof has not finished (no PROOF_EXIT in whole-904.log) — registers are taken AFTER the proof"; exit 8; }
M="sh scripts/gate-mutex.sh --run --"
echo "REGISTER_HEAD=$(git rev-parse HEAD) $(date '+%H:%M:%S')"
echo "PREDICTIONS (E4, §904, derived at c2337220a in predict-904.log, re-asserted for the chair car which touches src/lib/flagRegistry.js, src/lib/flags.js and two docs — no test, no writer string, no tuning table, no mount): lighting — NO movement: the farmed probe reads files 2543 / parked 373 / credited 2170 / titles 23653 / suiteTitles 6333 identical to the register (two titles RENAMED by L-UI-MAT, none added); the door re-takes provenance only · OSR — the plain read exits 0 'exactly matching the frozen inventory' (1972 findings) with NO input-drift line; NO --write; the walker's plain run exits 0 · mounts — NO movement (the door's porcelain must be EMPTY; a change is a STOP) · prose-numerics — nothing to re-key (dry: baseline=225 live=225 exact=225 rekeyed=0 relocated=0 FELL=0 NEW=0) · writer-reach — the dry run exits 0 with nothing STALE (judged 6532 · LIT 560 · LIT-NAME 4646 · DARK 1326); --write moves provenance (frozenAtSha / digests) only, identity set and every figure unchanged · tuning — NO movement (plain walker green; no door) · wizard-news — nothing (green in the proof)"
F=src/domain/display/stateProse/dossierMounts.js; node -e "import('$PWD/$F').then(m=>console.log('registry: mounts',m.DOSSIER_MOUNTS.length,'dark',m.UNMOUNTED_BLOCKS.length))"
echo "--- lighting: probe vs register"; PR=$(PROBE_FARM_ROOT=$SC/.farms node $SC/chair-tools/lighting-probe.mjs "$D" 2>/dev/null | tail -1); RG=$(python3 -c "import json;d=json.load(open('tests/lint/.lighting-census-baseline.json'));print(json.dumps({k:d[k] for k in ('files','parked','credited','titles','suiteTitles')}))"); echo "  probe   : $PR"; echo "  register: $RG"
echo "=== 1. LIGHTING (refuses a dirty tree — first):"; $M env LIGHTING_CENSUS_REFREEZE='Fable 5.1 chair — §904 L-UI-MAT landing' LIGHTING_CENSUS_NOTE='the L-UI-MAT consist (the L-UI car + the CHAIR-904 retirement car over the §903 CAS) at the tip; re-derived by the farmed probe (printed in run-registers-904.sh); provenance only — no test file added, two titles renamed' npx vitest run tests/lint/sovereigntyLightingContract.walker.test.js > $SC/reg904-lighting.log 2>&1; echo "LIGHTING_DOOR_EXIT=$? (non-zero EXPECTED)"; $M npx vitest run tests/lint/sovereigntyLightingContract.walker.test.js > $SC/reg904-lighting-plain.log 2>&1; echo "LIGHTING_PLAIN_EXIT=$? (must be 0)"; grep -E 'Tests ' $SC/reg904-lighting-plain.log | cut -c1-60
git add tests/lint/.lighting-census-baseline.json && git commit -q -m "§904 L-UI-MAT landing (register car 1): the lighting census refreezes at the tip

Derived by the farmed read-only probe before the door (the PREDICTIONS line and the probe/register pair in run-registers-904.sh's log): no movement in any figure — provenance only; the door exited non-zero by design and the plain re-run is the receipt.

Seat: Fable 5.1 — validated

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" && echo "REGISTER CAR 1 (lighting) -> $(git rev-parse --short HEAD)"
echo "=== 1b. OSR — READ ONLY (predicted: exact match, no drift; a non-zero exit or a drift line is a STOP — the chair rules before any door):"; node scripts/check-observed-shape-readers.mjs > $SC/reg904-osr-dry.log 2>&1; echo "OSR_DRY_EXIT=$? (must be 0)"; head -1 $SC/reg904-osr-dry.log | cut -c1-160; grep -c 'INPUT changed' $SC/reg904-osr-dry.log | sed 's/^/  drift lines (must be 0): /'; $M npx vitest run tests/lint/observedShapeReaders.walker.test.js > $SC/reg904-osr-walker.log 2>&1; echo "OSR_WALKER_PLAIN_EXIT=$? (must be 0)"; grep -E "Tests " $SC/reg904-osr-walker.log | cut -c1-60
echo "=== 2. MOUNTS BASELINE (predicted: no change):"; $M env UPDATE_MOUNT_BASELINE=1 npx vitest run tests/lint/dossierMountRegistry.walker.test.js > $SC/reg904-mounts.log 2>&1; echo "MOUNTS_DOOR_EXIT=$?"; echo "  changed (must be empty): [$(git status --porcelain -uall | awk '{print $2}' | tr '\n' ' ')]"
echo "=== 3. PROSE-NUMERICS re-key (dry, then --write; predicted 225 exact, nothing re-keyed):"; node $SC/prose-numerics-rekey.mjs "$D" > $SC/reg904-pn-dry.log 2>&1; echo "PN_DRY_EXIT=$?"; tail -2 $SC/reg904-pn-dry.log | cut -c1-160; node $SC/prose-numerics-rekey.mjs "$D" --write > $SC/reg904-pn.log 2>&1; echo "PN_WRITE_EXIT=$?"; tail -1 $SC/reg904-pn.log | cut -c1-160
echo "=== 4. WRITER-REACH --write (shrink-only; predicted NO refresh, provenance only — the dry run decides):"; node scripts/check-writer-reach.mjs > $SC/reg904-wr-dry.log 2>&1; echo "WR_DRY_EXIT=$? (read the refusal text if any)"; grep -E "DARK and unregistered|STALE|BANK THE WIN" $SC/reg904-wr-dry.log | head -6 | cut -c1-160; node scripts/check-writer-reach.mjs --write > $SC/reg904-wr.log 2>&1; echo "WRITER_REACH_WRITE_EXIT=$?"; tail -2 $SC/reg904-wr.log | cut -c1-200; node scripts/check-writer-reach.mjs > $SC/reg904-wr-plain.log 2>&1; echo "WR_PLAIN_EXIT=$? (must be 0)"
echo "=== 5. TUNING INVENTORY — PLAIN walker only (predicted green; no door at this landing):"; $M npx vitest run tests/lint/tuningRegister.walker.test.js > $SC/reg904-tuning.log 2>&1; echo "TUNING_PLAIN_EXIT=$? (must be 0)"; grep -E 'Tests ' $SC/reg904-tuning.log | cut -c1-60
echo "=== 6. WIZARD-NEWS: nothing predicted (green in the proof); the hand re-sign is NOT run."
echo "REGISTER_PORCELAIN=[$(git status --porcelain -uall | awk '{print $2}' | tr '\n' ' ')]"
echo "NEXT: review each changed register against PREDICTIONS (expected: ONLY scripts/.writer-reach-baseline.json, provenance fields); commit register car 2 by hand; then the ratchet (run-ratchet-904.sh), after-ratchet-904.sh <2489> <3>, the kit re-stamp, texts-904, payload, run-gate-904.sh, after-cas-904.sh, collect."
exit 0
