import json, io
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/kay-05.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-kay-i75-89.json"
d=json.load(io.open(src,encoding='utf-8'))
V=[
 (75,"VERIFIED_VERBATIM","Since one of the characters who reacts to the news of the reconquest at the end is one of the first characters that is introduced in the novel, the novel also comes full circle.","Raw HTML fetched live (200, browser UA) from brightweavings.com/worldbuilding/, byline 'by Holly E. Ordway / May 13, 1998'. Quote 'the novel also comes full circle' present verbatim. Both limbs hold: the reactor is named in the next sentence ('Alvar de Pellino begins the novel as a horseman in Rodrigo Belmonte's company') and the essay calls him 'one of the first characters that is introduced in the novel'; his reaction closes the discussion ('His response to the news is a painful one').",None),
 (76,"VERIFIED_VERBATIM","what happened that night in a burning hamlet near Fezana became legendary","Same raw page. The block quote Ordway sets off is the surgery passage: ben Yonannon, blind and mute, 'carved an opening in the skull of Diego Belmonte' and removed the bone fragment. Its first sentence ends 'became legendary' (quote verbatim), and the passage is explicitly retrospective/legend-framing ('In Al-Rassan, in Esperana, Ferrieres, Karch, Batiara - even, in time, in the far-off eastern homelands of the Asharites -'). Minor: the sentence opens with that place-list before reaching 'what happened that night', so 'opens' means the opening sentence, not the first words.",None),
 (77,"VERIFIED_VERBATIM","It is this facing-up to the consequences of actions glossed over or ignored in other fantasy texts that gives Tigana its unique flavor.","Raw HTML fetched live (200) from brightweavings.com/the-other-side-of-the-mirror-tigana/, 'by James Gunn', headnote naming the Easton Press leatherbound Tigana introduction, signed 'James Gunn / Lawrence, Kansas / July 30, 1998'. Quote verbatim. The enslaved-wizard limb is the immediately preceding paragraph: the magician's 'I am not a tool! ... I am a free and living soul with my own destiny!' and 'Before the sun went down I was a free man on an open road. I am now a slave.'",None),
 (78,"VERIFIED_VERBATIM","Tigana reads like a richly tapestried historical novel dense with character and detail","Same raw page; the sentence appears verbatim and continues 'but it occurs in a world the reader does not know, a world with two moons, one white, one blue.'",None),
 (79,"VERIFIED_VERBATIM","Kay surprises his readers by his willingness to kill off major characters, even his most attractive ones, and this, too, gives the edge of reality","Same raw page. Quote verbatim; both the 'attractive' limb ('even his most attractive ones') and the 'edge of reality' limb ('gives the edge of reality to what might otherwise be airily fantastic') are in the same sentence.",None),
 (80,"VERIFIED_VERBATIM","[Kay] attempts to create a grittier, harsher world than is common within fantasy","Same raw page. Quote verbatim, attributed on the page to Kuzca, who is identified earlier as 'Peter Kuzca writing in The Encyclopedia Of Fantasy'. The TV limb is present: 'Kuzca speculates that Kay may have learned much about scene-setting and the use of dialogue from his television experience.' Note the speculation is Kuzca's, reported by Gunn, not Gunn's own; the claim's grammar leaves the subject ambiguous but the page supports the substance either way. (Page also spells 'flavor'; the 'grittier' remark is made 'In describing The Fionavar Tapestry' but framed as 'about the nature of all Kay fantasies'.)",None),
 (81,"VERIFIED_VERBATIM","a work of 1300 pages ... with many characters and many narrative points of view, so that it is difficult to summarize","Raw HTML fetched live (200) from brightweavings.com/justinian-visited-and-revisited/, 'by Pierre-Louis Malosse, translated by Morgon Mills', headnote 'This French paper first appeared in the French academic journal Anabases (Toulouse), 5 (2007), p. 229-235.' Quote verbatim; the 1300-page and difficulty-of-summary limbs are in the same sentence.",None),
 (82,"VERIFIED_VERBATIM","to give his characters the knowledge and the conceits of the time, and in particular the superstitions appropriate to them","Same raw page. Quote verbatim. Superstitions limb explicit; the anachronism limb is the preceding clause: 'the lapses are nevertheless quite limited and more of nuance than of fact'.",None),
 (83,"VERIFIED_VERBATIM","Its false Byzantium is more real than the 'real' Byzantium of the time-travellers","Same raw page. Quote verbatim. Preceding sentence carries every limb: 'the Sarantine Mosaic, which is unfaithful to history and deliberately inverts and reconstructs historical matter, evokes the Late Antique and Eastern Mediaeval world much more exactly than the novels of de Camp and Silverberg, which endeavour to respect history's givens.' Both comparators are time-travel novels on this page (Lest Darkness Fall; Up the Line / Les temps paralleles).",None),
 (84,"VERIFIED_VERBATIM","A good number of real places and people are easily recognizable, under the new names - often transparent - that have been given to them","Same raw page. Quote verbatim (en dashes match). All three substitutions listed: 'Rhodias is Rome, Varena Ravenna ... Pertennius of Eubulus Procopius of Caesarea himself'. Undisguised-debt limb: 'The debt to the real sixth-century Byzantium is not at all disguised.'",None),
 (85,"VERIFIED_VERBATIM","worth citing a passage to provide a sense of Guy Gavriel Kay's style, especially as compared with the narrative supplied by Procopius","Same raw page. Quote verbatim (note 17 cites Bell. pers. I, 24, 37-41). Porphyry/shroud limb: \"'I would sooner die clothed in porphyry in this palace' ... 'The vestments of Empire are seemly for a shroud'\". Witness limb: 'A senator, Plautus Bonosus, remembers the scene as it unfolded before him'.",None),
 (86,"VERIFIED_VERBATIM","resolutions are produced by both individual action and the whims of history","Raw HTML fetched live (200) from brightweavings.com/denalions/, title 'Three Glasses of Wine: The Accommodation of Culture in The Lions of Al-Rassan', 'by Dena Taylor', headnote naming NIMROD PRESS's BABEL HANDBOOKS series. Quote verbatim. Preclusion limb in the same sentence: 'with its postmodern sensibilities that preclude both magic and the power of heroism alone to determine outcomes'.",None),
 (87,"VERIFIED_VERBATIM","the epilogue, and the final image of the novel: Three full glasses of wine, intentionally left standing together","Same raw page. Quote verbatim; 'culminating' is the page's own frame too ('Sorenica - serenity - is the culmination of the process of harmonization').",None),
 (88,"PARTIAL","The title refers to ... 'his life was on the cusp of change'; Kay drew Yeats's vision","Raw HTML fetched live (200) from brightweavings.com/denasailing/, 'by Dena Taylor', headnote 'first published as a review in TransVersions 10, Toronto: Orchid Press, 1999'. The quote 'Kay at his most historical' is on the page verbatim ('Here is Kay at his most historical'), and the idiom limb is fully supported verbatim: \"To say of a man that he was sailing to Sarantium was to say that his life was on the cusp of change\". The vision limb is supported ('what he has drawn from Yeats's vision of Byzantium'). But the page names exactly ONE Yeats poem, 'Sailing to Byzantium', never a plural set of Byzantium poems, and never states that any title DERIVES from Yeats - it attributes the title to the in-world idiom instead. (That derivation is asserted elsewhere, in Malosse's note 12, not in Taylor.) Graded PARTIAL on the plural/derivation limb.","the Sarantine titles derive from Yeats's Byzantium poems - the page names one poem ('Sailing to Byzantium'), discusses one title, and attributes only the VISION to Yeats, never the title's derivation"),
 (89,"VERIFIED_VERBATIM","This cyclical style of narrative creates a sense of cause and effect in history, rather than a timeline of historical events.","Raw HTML fetched live (200) from brightweavings.com/creative_history/, title 'The Creative Construction of History in Guy Gavriel Kay's The Sarantine Mosaic', 'by Jillian Hatch, 2005', filed under Student Papers. Quote verbatim and the full 'rather than a timeline' contrast is the same sentence. Antecedent limbs: 'Kay's narrative is not organised in a purely chronological fashion. It incorporates flashbacks and often uses several focalizers to emphasize an event.' and 'This multi-focalized narrative'.",None),
]
verdicts=[]
for idx,v,tw,note,limb in V:
    e={"index":idx,"verdict":v,"trueWording":tw,"note":note}
    if limb: e["unsupportedLimb"]=limb
    verdicts.append(e)
assert [x["index"] for x in verdicts]==d["indices"], "index mismatch"
res={"name":"kay","chunk":5,"claims":d["claims"],"verdicts":verdicts}
io.open(out,'w',encoding='utf-8').write(json.dumps(res,indent=1,ensure_ascii=False))
print("wrote",out,len(res["claims"]),len(res["verdicts"]))
