import { sample63 } from './lib.mjs';
import { generate } from './seam.mjs';
const row = sample63().find(r => r.settType === 'city');
const rec = generate(row);
const show = (p, v) => console.log(`\n-- ${p}  (len=${Array.isArray(v) ? v.length : '?'})\n   ${JSON.stringify(Array.isArray(v) ? v.slice(0, 2) : v).slice(0, 700)}`);
show('economicState.incomeSources', rec.economicState.incomeSources);
show('economicState.tradeDependencies', rec.economicState.tradeDependencies);
show('history.legacyAnnotations', rec.history.legacyAnnotations);
show('simulationTrace', rec.simulationTrace);
show('resourceAnalysis.gaps', rec.resourceAnalysis.gaps);
show('resourceAnalysis.exports', rec.resourceAnalysis.exports);
show('resourceAnalysis.resourceChains', rec.resourceAnalysis.resourceChains);
show('resourceAnalysis.exploitation', rec.resourceAnalysis.exploitation);
show('conflicts', rec.conflicts);
show('relationships', rec.relationships);
show('powerStructure', { ...rec.powerStructure, factions: undefined, factionRelationships: undefined, conflicts: undefined });
show('powerStructure.factions[0]', rec.powerStructure.factions?.[0]);
show('generationCoherenceReceipt', { ...rec.generationCoherenceReceipt, checks: undefined, judgments: undefined });
show('generationCoherenceReceipt.checks[0]', rec.generationCoherenceReceipt.checks?.[0]);
show('generationCoherenceReceipt.judgments[0]', rec.generationCoherenceReceipt.judgments?.[0]);
show('activeConditions', rec.activeConditions);
show('settlementReason', rec.settlementReason);
show('stress', rec.stress);
show('economicState(top keys)', Object.keys(rec.economicState));
show('defenseProfile', { ...rec.defenseProfile, institutions: undefined });
show('economicViability', { ...rec.economicViability, dependencies: undefined, plotHooks: undefined, warnings: undefined });
show('prominentRelationship', rec.prominentRelationship);
show('isolationSupport', rec.isolationSupport);
show('spatialLayout', { ...rec.spatialLayout, quarters: undefined });
show('culturalIdentity', rec.culturalIdentity);
show('history(top)', { ...rec.history, eventsTimeline: undefined, historicalEvents: undefined, currentTensions: undefined, legacyAnnotations: undefined });
show('id/seed/version', { id: rec.id, _seed: rec._seed, generatorVersion: rec.generatorVersion, schemaVersion: rec.schemaVersion, simulationVersion: rec.simulationVersion, tier: rec.tier, population: rec.population });
