/* eslint-disable */
// GENERATED by scripts/generate-custom-content-manifest.mjs. Do not edit by hand.
// Every set below is DERIVED by measuring a renderer, never hand-typed.

function deepFreeze<T>(value: T): T {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value as object)) deepFreeze(child);
  return value;
}

export const CUSTOM_CONTENT_CHARSET = deepFreeze({
  "manifestVersion": "2026-08-02.1",
  "policy": {
    "enforcement": "report",
    "nonLatin": "undecided",
    "embeddedFont": "Lora"
  },
  "surfaces": {
    "web-display": {
      "ranges": "",
      "count": 0,
      "method": "unbounded",
      "inputs": [],
      "inputsSha256": ""
    },
    "dossier-pdf": {
      "ranges": "D 20-7E A0-AC AE-132 134-137 139-17E 18F 192 1A0-1A1 1AF-1B0 1CD-1CE 1D4 1E5-1E7 1E9 1EF 1FE-1FF 218-21B 21F 237 259 292 2BB-2BC 2C6-2C7 2C9 2D8-2DD 300-304 306-30C 312 31B 323 326-328 335 394 3A9 3BC 3C0 400-45F 462-463 46A-46B 472-475 48A-4A5 4A8-4FF 510-513 51A-51D 524-529 52E-52F 1E80-1E85 1E9E 1EA0-1EF9 2010 2013-2014 2018-201A 201C-201E 2020-2022 2026 2030 2032-2033 2039-203A 2044 2052 2074 20AC 20AE 20B4 20B8 20BA 20BD 2113 2116 2122 2126 212E 2202 2206 220F 2211-2212 2215 2219-221A 221E 222B 2248 2260 2264-2265 25CA 27E8-27E9 FB01-FB02 FFFF",
      "count": 759,
      "method": "fontkit-intersection",
      "inputs": [
        "public/fonts/Lora-Regular.ttf",
        "public/fonts/Lora-Bold.ttf",
        "public/fonts/Lora-Italic.ttf",
        "public/fonts/Lora-BoldItalic.ttf",
        "public/fonts/Nunito-Regular.ttf",
        "public/fonts/Nunito-Bold.ttf",
        "public/fonts/Nunito-ExtraBold.ttf",
        "public/fonts/Nunito-Italic.ttf"
      ],
      "inputsSha256": "d879390789c8f2c501bd3ad7ae90745e58e062be5ab90b7c57cc27ae0e7a3463"
    },
    "campaign-pdf": {
      "ranges": "20-7E A1-AC AE-137 139-17F 18F 192 1A0-1A1 1AF-1B0 1B7 1CD-1CE 1D3-1D4 1E4-1E9 1EE-1EF 1FE-1FF 218-21B 21E-21F 237 259 292 2BB-2BC 2C6-2C7 2C9 2D8-2DD 300-304 306-30C 312 31B 323 326-328 335-336 393-394 3A0 3A9 3BC 3C0 400-45F 462-463 46A-46D 472-475 48A-4FF 510-513 51A-51D 524-529 52E-52F 1C81 1C85 1E80-1E85 1E9E 1EA0-1EF9 2010 2013-2014 2018-201A 201C-201E 2020-2022 2026 2030 2032-2033 2039-203A 2044 2052 2074 20AC 20AE 20B4 20B8 20BA 20BD 2113 2116 2122 2126 212A-212B 212E 2202 2206 220F 2211-2212 2215 2219-221A 221E 222B 2248 2260 2264-2265 25CA 27E8-27E9 EFFD FB01-FB02",
      "count": 776,
      "method": "embedded-roster-and-textpass",
      "inputs": [
        "public/fonts/Lora-Regular.ttf",
        "public/fonts/Lora-Bold.ttf",
        "public/fonts/Lora-Italic.ttf",
        "src/utils/jsPdfBookFont.js",
        "src/utils/jsPdfText.js"
      ],
      "inputsSha256": "9d57d4b3a17c8d9aa0a56d30e709bd8a296f10933003d3a2769a6751c49fdcee"
    },
    "foundry": {
      "ranges": "",
      "count": 0,
      "method": "unbounded",
      "inputs": [],
      "inputsSha256": ""
    },
    "json-export": {
      "ranges": "",
      "count": 0,
      "method": "unbounded",
      "inputs": [],
      "inputsSha256": ""
    },
    "world-book": {
      "ranges": "20-7E A1-AC AE-137 139-17F 18F 192 1A0-1A1 1AF-1B0 1B7 1CD-1CE 1D3-1D4 1E4-1E9 1EE-1EF 1FE-1FF 218-21B 21E-21F 237 259 292 2BB-2BC 2C6-2C7 2C9 2D8-2DD 300-304 306-30C 312 31B 323 326-328 335-336 393-394 3A0 3A9 3BC 3C0 400-45F 462-463 46A-46D 472-475 48A-4FF 510-513 51A-51D 524-529 52E-52F 1C81 1C85 1E80-1E85 1E9E 1EA0-1EF9 2010 2013-2014 2018-201A 201C-201E 2020-2022 2026 2030 2032-2033 2039-203A 2044 2052 2074 20AC 20AE 20B4 20B8 20BA 20BD 2113 2116 2122 2126 212A-212B 212E 2202 2206 220F 2211-2212 2215 2219-221A 221E 222B 2248 2260 2264-2265 25CA 27E8-27E9 EFFD FB01-FB02",
      "count": 776,
      "method": "embedded-roster-and-textpass",
      "inputs": [
        "public/fonts/Lora-Regular.ttf",
        "public/fonts/Lora-Bold.ttf",
        "public/fonts/Lora-Italic.ttf",
        "src/utils/jsPdfBookFont.js",
        "src/utils/jsPdfText.js"
      ],
      "inputsSha256": "9d57d4b3a17c8d9aa0a56d30e709bd8a296f10933003d3a2769a6751c49fdcee"
    }
  },
  "bans": {
    "control": "0-1F 7F-9F",
    "bidi": "61C 200E-200F 202A-202E 2066-2069",
    "invisible": "A0 AD 180E 200B-200D 2060-2064 FEFF FFF9-FFFB",
    "noncharacter": "FDD0-FDEF FFFE-FFFF 1FFFE-1FFFF 2FFFE-2FFFF 3FFFE-3FFFF 4FFFE-4FFFF 5FFFE-5FFFF 6FFFE-6FFFF 7FFFE-7FFFF 8FFFE-8FFFF 9FFFE-9FFFF AFFFE-AFFFF BFFFE-BFFFF CFFFE-CFFFF DFFFE-DFFFF EFFFE-EFFFF FFFFE-FFFFF 10FFFE-10FFFF"
  },
  "fields": {
    "institutions": {
      "name": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "world-book",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": "name on institutions"
      },
      "category": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 100,
        "osrIdentity": "category on institutions"
      },
      "tags": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": "tags on institutions"
      },
      "satisfies": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 100,
        "osrIdentity": "satisfies on institutions"
      },
      "description": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "foundry"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": "description on institutions"
      },
      "produces": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "produces on institutions"
      },
      "requires": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "requires on institutions"
      },
      "subsumes": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "subsumes on institutions"
      }
    },
    "services": {
      "name": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": "name on services"
      },
      "category": {
        "surfaces": [
          "web-display",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 100,
        "osrIdentity": "category on services"
      },
      "description": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "foundry"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": "description on services"
      },
      "providedBy": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "providedBy on services"
      },
      "requires": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "requires on services"
      }
    },
    "resources": {
      "name": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": "name on resources"
      },
      "category": {
        "surfaces": [
          "web-display",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 100,
        "osrIdentity": "category on resources"
      },
      "commodities": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": "commodities on resources"
      },
      "description": {
        "surfaces": [
          "web-display",
          "dossier-pdf",
          "foundry"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": "description on resources"
      },
      "yields": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "yields on resources"
      },
      "enables": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "enables on resources"
      }
    },
    "stressors": {
      "name": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": null
      },
      "description": {
        "surfaces": [
          "web-display"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": null
      },
      "disablesInstitutions": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": null
      },
      "disablesGoods": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": null
      }
    },
    "tradeGoods": {
      "name": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": "name on tradeGoods"
      },
      "category": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 100,
        "osrIdentity": "category on tradeGoods"
      },
      "satisfies": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 100,
        "osrIdentity": "satisfies on tradeGoods"
      },
      "description": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": "description on tradeGoods"
      },
      "requiredInstitution": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "requiredInstitution on tradeGoods"
      },
      "requiredResources": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": "requiredResources on tradeGoods"
      }
    },
    "factions": {
      "name": {
        "surfaces": [
          "web-display",
          "campaign-pdf",
          "foundry"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": null
      },
      "archetype": {
        "surfaces": [
          "web-display"
        ],
        "multiline": true,
        "maxCodepoints": 300,
        "osrIdentity": null
      },
      "agenda": {
        "surfaces": [
          "web-display"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": null
      },
      "methods": {
        "surfaces": [
          "web-display"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": null
      },
      "description": {
        "surfaces": [
          "web-display",
          "campaign-pdf",
          "foundry"
        ],
        "multiline": true,
        "maxCodepoints": 2000,
        "osrIdentity": null
      },
      "controls": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": null
      },
      "rivals": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 240,
        "osrIdentity": null
      }
    },
    "deities": {
      "name": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": null
      },
      "portfolio": {
        "surfaces": [
          "web-display"
        ],
        "multiline": false,
        "maxCodepoints": 500,
        "osrIdentity": null
      },
      "domain": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": true,
        "maxCodepoints": 300,
        "osrIdentity": null
      }
    },
    "traditions": {
      "name": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": false,
        "maxCodepoints": 160,
        "osrIdentity": null
      },
      "epithet": {
        "surfaces": [
          "web-display",
          "dossier-pdf"
        ],
        "multiline": true,
        "maxCodepoints": 300,
        "osrIdentity": null
      }
    }
  }
} as const);
