/**
 * home/landingFixture.js — FROZEN real engine output for the landing artifacts.
 *
 * GENERATED by scripts/generate-landing-fixture.mjs — do not hand-edit. The
 * one authored field is voice.narrated: owner-sanctioned STOCK prose (no AI
 * credits spent on a fixture), written in the narrative layer's register and
 * grounded EXCLUSIVELY in the derived receipts in voice.receipts. It lives in
 * the generator script (STOCK_NARRATION) and must be re-grounded whenever the
 * fixture is regenerated. Regenerate with:
 *   npx vite-node scripts/generate-landing-fixture.mjs -- --seed lf-033 --emit
 *
 * Provenance: seed `lf-033`, 12 one-week ticks of advanceCampaignWorld
 * over a 5-settlement region (fixture town + 4 neighbors), engine
 * generatorVersion 0.9.0 / simulationVersion 1.
 * The town is a village — within the anon tier ceiling by design: the
 * "Forge this exact town" button replays { seed, config } through the SAME
 * store forge action as every other generation, so the artifact is a promise
 * an anonymous visitor can verify in one click. REGEN POLICY: regenerate this
 * fixture whenever engine generation output changes (goldens regen = signal),
 * or the frozen artifact and the button's live output will drift apart.
 *
 * Consumed ONLY by the lazy landing chunk (LandingBelowFold) — never imported
 * eagerly (first-paint budget).
 */

export const fixture = {
  "seed": "lf-033",
  "weeks": 12,
  "engine": {
    "generatorVersion": "0.9.0",
    "simulationVersion": 1
  },
  "forge": {
    "mode": "basic",
    "randomSliderMode": true,
    "importedNeighbour": null,
    "config": {
      "settType": "village",
      "population": 1500,
      "tradeRouteAccess": "random_trade",
      "culture": "random_culture",
      "settlementAgeMode": "auto",
      "settlementAgeYears": 0,
      "monsterThreat": "random_threat",
      "priorityEconomy": 50,
      "priorityMilitary": 50,
      "priorityMagic": 50,
      "priorityReligion": 50,
      "priorityCriminal": 50,
      "magicExists": true,
      "nearbyResourcesRandom": true,
      "nearbyResources": null,
      "nearbyResourcesDepleted": [],
      "nearbyResourcesState": {},
      "selectedStresses": [],
      "selectedStressesRandom": true,
      "customName": "",
      "customInstitutions": [],
      "customResources": [],
      "customTradeRoutes": [],
      "powerDynamicsConfig": null,
      "defenseScenarioConfig": null
    }
  },
  "town": {
    "name": "Cnocby",
    "population": 412,
    "tier": "village",
    "eyebrow": "road village · mountain",
    "prose": "The road into Cnocby becomes a street at a point you can't precisely identify. The settlement grows around you gradually.",
    "pressure": "Rónnat Sullivan is about to call it in.",
    "hooks": [
      {
        "kind": "NPC",
        "tone": "success",
        "tag": "derived · npcs",
        "lead": "Odhrán MacCarthy, mayor",
        "rest": " · goal: use current stability to address structural vulnerabilities before conditions change."
      },
      {
        "kind": "Hook",
        "tone": "warning",
        "tag": "derived · factions",
        "text": "A neutral figure is being pressured by both The Free Alliance and The Establishment to take a side before the next council session."
      }
    ],
    "hooksMore": 9
  },
  "voice": {
    "receipts": [
      {
        "label": "conflict",
        "text": "The Free Alliance × The Establishment · succession to a council seat · stakes: political influence"
      },
      {
        "label": "route",
        "text": "road · Picked from pool: road, road, road, isolated, isolated."
      },
      {
        "label": "resource",
        "text": "mountain_timber · present but depleted (Tier-weighted depletion (20%) marked this resource as depleted.)"
      },
      {
        "label": "institution",
        "text": "travelers_inn · selected (Base chance 59% lifted by ×1.56 from nearby resources + terrain.)"
      }
    ],
    "narrated": "The road made Cnocby by a coin’s width, three chances of it against two of nothing, and the mountain timber that raised the travelers’ inn is mostly cut out. What remains worth holding is the seat: the Free Alliance and the Establishment both want the council chair, and both are leaning on the same neutral name to declare before the session. Rónnat Sullivan is about to call something in, and half the inn seems to know what. The mayor wants the cracks mended while the weather holds; no one asks which cracks he means."
  },
  "realm": {
    "whyTrace": [
      {
        "axis": "Trade connectivity",
        "from": "adequate",
        "to": "critical",
        "tone": "danger",
        "reason": "Wartime pressure disrupts trade flows. Criminal pressure disrupts trade flows."
      },
      {
        "axis": "Religious authority",
        "from": "strained",
        "to": "adequate",
        "tone": "success",
        "reason": "Vael (major) anchors religious authority (piety ×1.35). Religious Authorities carries power 13."
      },
      {
        "axis": "Social trust",
        "from": "adequate",
        "to": "strained",
        "tone": "warning",
        "reason": "Public legitimacy 25 colors trust. Criminal pressure erodes communal trust."
      }
    ],
    "chronicle": [
      {
        "kind": "faith",
        "tone": "faith",
        "week": "Week 1",
        "text": "After a long contest of devotion, Korl has become the patron creed of Aryagrad."
      },
      {
        "kind": "stressor",
        "tone": "war",
        "week": "Week 2",
        "text": "Cnocby shows enough conflict pressure for a new condition to emerge."
      },
      {
        "kind": "trade",
        "tone": "economic",
        "week": "Week 2",
        "text": "Penshaw shows enough trade pressure for a new condition to emerge."
      }
    ],
    "relationships": [
      {
        "from": "Cnocby",
        "to": "Keshigordu",
        "type": "trade partner",
        "tone": "neutral"
      },
      {
        "from": "Penshaw",
        "to": "Cnocby",
        "type": "border incident",
        "tone": "danger",
        "week": "Week 12"
      }
    ],
    "pins": [
      {
        "name": "Cnocby",
        "dotTone": "gold"
      },
      {
        "name": "Penshaw",
        "dotTone": "danger",
        "tag": "Border incident",
        "tagTone": "danger"
      },
      {
        "name": "Keshigordu",
        "dotTone": "warning",
        "tag": "Criminal pressure",
        "tagTone": "warning"
      }
    ],
    "neighbors": [
      {
        "name": "Keshigordu",
        "tier": "town"
      },
      {
        "name": "Skáloy",
        "tier": "city"
      },
      {
        "name": "Aryagrad",
        "tier": "town"
      },
      {
        "name": "Penshaw",
        "tier": "village"
      }
    ]
  }
};
