# -*- coding: utf-8 -*-
import sys, json, os
sys.path.insert(0, "/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/kay-craft-raw")
from build import check, D

WO = "https://locusmag.com/2022/06/gary-k-wolfe-reviews-all-the-seas-of-the-world-by-guy-gavriel-kay/"
WZ = "https://thewertzone.blogspot.com/2025/06/written-on-dark-by-guy-gavriel-kay.html"
CA = "https://fantasyliterature.com/reviews/all-the-seas-of-the-world/"
SC = "https://strangecurrencies.org/2022/06/07/review-of-all-the-seas-of-the-world-by-guy-gavriel-kay/"
GL = "https://www.theglobeandmail.com/arts/books/reviews/article-guy-gavriel-kay-novel-written-on-the-dark/"
BP = "https://www.bookpage.com/reviews/all-the-seas-of-the-world-review/"
CT = "https://www.christianitytoday.com/2025/06/author-doomscroll-guy-gavriel-kay-written-on-the-dark/"

S_WO = "Gary K. Wolfe, review of All the Seas of the World, Locus (May 2022 issue; posted 2022-06-25)"
S_WOK = "Guy Gavriel Kay's novel All the Seas of the World, quoted by Gary K. Wolfe in Locus, 2022"
S_WZ = "Adam Whitehead, review of Written on the Dark, The Wertzone, 2025"
S_CA = "Bill Capossere, 'All the Seas of the World: A master working at the top of his craft', Fantasy Literature, 2022"
S_CAK = "Guy Gavriel Kay's novel All the Seas of the World, quoted by Bill Capossere at Fantasy Literature, 2022"
S_CAR = "'Ilana', reader comment on Bill Capossere's Fantasy Literature review, 2022-04-19"
S_SC = "Dan Ruffolo, review of All the Seas of the World, Strange Currencies, 2022"
S_GL = "David Moscrop, review of Written on the Dark, The Globe and Mail, 2025"
S_GLK = "Guy Gavriel Kay's novel Written on the Dark, closing words quoted by David Moscrop in The Globe and Mail, 2025"
S_BP = "Noah Fram, starred review of All the Seas of the World, BookPage, 2022"
S_CT = "Haley Byrd Wilt, 'The Author Who Pulled Me out of the Doomscroll', Christianity Today, 2025 (reporter's paraphrase of Kay's remarks)"
S_CTK = "Guy Gavriel Kay, interviewed in Toronto by Haley Byrd Wilt, Christianity Today, 2025"

C = []
def add(**kw): C.append(kw)

add(_file="wolfe-locus", feature="register modulation", claim="Wolfe says Kay deploys an impressive variety of narrative voices in All the Seas of the World.", source=S_WO, url=WO, quote="Kay deploys an impressive variety of such narrative voices", page="body, paragraph beginning 'As usual'", kind="analysis", polarity="asserts", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="wolfe-locus", feature="per-speaker register", claim="Wolfe says the occasional shift into first person has something of the effect of hearing a skilled soloist in a symphony.", source=S_WO, url=WO, quote="the occasional shift into first-person has something of the effect", page="body, paragraph beginning 'As usual'", kind="analysis", polarity="asserts", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="wolfe-locus", feature="naming and forms of address", claim="Wolfe says Kay's devoted readers have come to learn his invented nomenclature for nations, cities and geographical features.", source=S_WO, url=WO, quote="his invented nomenclature for nations, cities, geographical features", page="body, first paragraph", kind="analysis", polarity="asserts", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="wolfe-locus", feature="plainness and economy", claim="Wolfe says that despite an intimidating character list at the front, the on-the-ground tale is a model of clarity and focus.", source=S_WO, url=WO, quote="the on-the-ground tale is a model of clarity and focus", page="body, final paragraph", kind="analysis", polarity="asserts", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="wolfe-locus", feature="annalist voice and deep time", claim="Wolfe says even secondary figures gain a haunting presence when the reader is offered brief glimpses into their future lives.", source=S_WO, url=WO, quote="brief glimpses into their future lives", page="body, paragraph beginning 'As his isolated and exiled figures'", kind="analysis", polarity="asserts", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="wolfe-locus", feature="repetition and refrain", claim="Wolfe says the novel reminds the reader more than once that lives pivot on small things and accidents of timing.", source=S_WOK, url=WO, quote="Lives change, turn, pivot on small things, accidents of timing", page="body, paragraph beginning 'Not uncharacteristically'", kind="analysis", polarity="asserts", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")

add(_file="wertzone", feature="register modulation", claim="Whitehead says Kay's measured prose is sometimes minimalist and sometimes ornate.", source=S_WZ, url=WZ, quote="his measured prose, sometimes minimalist, sometimes ornate", page="body, paragraph beginning 'The traditional strengths of Kay'", kind="analysis", polarity="asserts", date="2025-06", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="wertzone", feature="diction (native vs latinate)", claim="Whitehead says Kay knows when to deploy words like bludgeons and when like scalpels.", source=S_WZ, url=WZ, quote="when to deploy words like bludgeons and when like scalpels", page="body, paragraph beginning 'The traditional strengths of Kay'", kind="analysis", polarity="asserts", date="2025-06", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="wertzone", feature="civic record register", claim="Whitehead says Kay provides a list of historical sources at the end of Written on the Dark.", source=S_WZ, url=WZ, quote="Kay provides a list of historical sources at the end", page="body, paragraph beginning 'This book is set'", kind="analysis", polarity="asserts", date="2025-06", routeHint="direct curl with browser user agent", registerHint="dm-page", confidence="high")
add(_file="wertzone", feature="humour", claim="Whitehead says there is more humour in Written on the Dark than in some of Kay's previous books.", source=S_WZ, url=WZ, quote="There is more humour in this book than perhaps some", page="body, paragraph beginning 'The traditional strengths of Kay'", kind="analysis", polarity="asserts", date="2025-06", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="capossere", feature="other: flash-forward tells the outcome early", claim="Capossere says Kay takes the suspense out of dangerous scenes with a flash-forward so the reader already knows the character survives.", source=S_CA, url=CA, quote="the reader knows immediately, or already, that the character will", page="body, paragraph beginning 'But Kay more often than not'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="withheld information and inference", claim="Capossere says Kay's plot evokes a who-are-they-now response rather than a what-happens-next one.", source=S_CA, url=CA, quote="a “who are they now” response", page="body, paragraph beginning 'But Kay more often than not'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="dossier-archivist", confidence="high")
add(_file="capossere", feature="omission as information", claim="Capossere quotes the novel's narrator saying in a meta-fictional aside that some tales are told and most are not.", source=S_CAK, url=CA, quote="Some tales are told, most are not", page="body, paragraph beginning 'In a somewhat similar vein'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="omission as information", claim="Capossere says Kay gives the reader more of those untold tales than most authors do.", source=S_CA, url=CA, quote="Kay gives us more of those untold tales than most authors", page="body, paragraph beginning 'In a somewhat similar vein'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="annalist voice and deep time", claim="Capossere says Danio Cerra's older recalling voice layers an aching sense of time's passage over the book's present moments.", source=S_CA, url=CA, quote="an aching sense of time’s passage", page="body, paragraph beginning 'I could go on rapturously'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="opening sentence", claim="Capossere reports that the novel opens with the line about the memory of home being too far away.", source=S_CAK, url=CA, quote="The memory of home can be too far away", page="body, paragraph beginning 'Beyond character and plot'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="consequence on a household", claim="Capossere names as a Kay-ism a few lines of gentle dignity granted to a character at the moment of death.", source=S_CA, url=CA, quote="a few lines of gentle dignity, of respect accorded by the", page="body, paragraph beginning 'But Kay also is quick to show'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="withheld information and inference", claim="Capossere says Kay drops many seeds into the text to prepare the reader for what is to come.", source=S_CA, url=CA, quote="so many seeds to carefully prepare us for what’s to come", page="body, paragraph beginning 'Finally, the craft is'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="none", confidence="high")
add(_file="capossere", feature="repetition and refrain", claim="Capossere says characters or the narrator reflect repeatedly on how easily one could die.", source=S_CA, url=CA, quote="Repeatedly characters (or the narrator) reflect on how", page="body, paragraph beginning 'The world Kay creates'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="chronicle-line", confidence="high")
add(_file="capossere", feature="plainness and economy", claim="Capossere says some of Kay's characters are given just two or three paragraphs and are still richly drawn.", source=S_CA, url=CA, quote="are given just two or three paragraphs", page="body, paragraph beginning 'What I'm trying to say here'", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="dossier-archivist", confidence="high")
add(_file="capossere", feature="other: structure and shape", claim="Capossere says the novel is meticulously crafted in structure, pace, language and dialogue.", source=S_CA, url=CA, quote="meticulously crafted in structure, pace, language, dialogue", page="body, final paragraph", kind="analysis", polarity="asserts", date="2022-04", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="none", confidence="high")
add(_file="capossere", feature="omission as information", claim="A reader commenting on the review says she found Tigana on the whole to be telling rather than showing.", source=S_CAR, url=CA, quote="I found it on the whole to be telling rather than", page="comments, 'Ilana', 2022-04-19", kind="reader", polarity="disputes", date="2022-04-19", routeHint="live URL 403; Wayback raw capture 20250803031327id_", registerHint="none", confidence="high")

add(_file="strangecurr", feature="register modulation", claim="Ruffolo says All the Seas of the World takes in places a more explicit storytelling tone than he expects from Kay.", source=S_SC, url=SC, quote="a more explicit storytelling tone than I’ve come to expect", page="body, first paragraph", kind="analysis", polarity="asserts", date="2022-06-07", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="strangecurr", feature="annalist voice and deep time", claim="Ruffolo says the narration lets the reader know the impacts the characters had and the lives they touched.", source=S_SC, url=SC, quote="we can know through the narration, of the impacts they had", page="body, paragraph beginning 'This theme feels especially important'", kind="analysis", polarity="asserts", date="2022-06-07", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")

add(_file="globe", feature="plainness and economy", claim="Moscrop says Written on the Dark is equally impressive for its accessibility and its density.", source=S_GL, url=GL, quote="equally as impressive for its accessibility and its density", page="body, final paragraph", kind="analysis", polarity="asserts", date="2025", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="globe", feature="closing sentence", claim="Moscrop opens his review by citing the closing words of Written on the Dark.", source=S_GL, url=GL, quote="the closing words of Written on the Dark", page="body, first paragraph", kind="analysis", polarity="asserts", date="2025", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="globe", feature="closing sentence", claim="The closing words of Written on the Dark, as Moscrop quotes them, are a four-word sentence repeated once.", source=S_GLK, url=GL, quote="I did that. I did that.", page="body, first paragraph", kind="analysis", polarity="asserts", date="2025", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="globe", feature="omission as information", claim="Moscrop says the novel makes sense even for the mysteries it refuses to explain.", source=S_GL, url=GL, quote="even for the mysteries it refuses to explain", page="body, paragraph beginning 'The brilliance of Written on the Dark'", kind="analysis", polarity="asserts", date="2025", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="bookpage", feature="consequence on a household", claim="Fram calls Kay a master of telling small stories in a big world.", source=S_BP, url=BP, quote="A master of telling small stories in a big world", page="review, final paragraph", kind="reception", polarity="asserts", date="2022-05-17", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="bookpage", feature="place and institution description", claim="Fram says Kay's characters see their homes fade from the map and their lives taken for the pettiest of causes.", source=S_BP, url=BP, quote="see their homes fade from the map", page="review, first body paragraph", kind="reception", polarity="asserts", date="2022-05-17", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")

add(_file="ctoday", feature="register modulation", claim="Wilt reports Kay saying his seniority frees him from the modern rule against jumping from past tense to present tense.", source=S_CT, url=CT, quote="Don’t jump from the past tense to the present tense", page="body, paragraph beginning 'It helps that Kay'", kind="analysis", polarity="rejects", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: the reporter's list of rules paraphrased from Kay's remarks, not his transcribed words")
add(_file="ctoday", feature="point of view and distance", claim="Wilt reports Kay naming the rule against hopping between characters' heads as one he does not have to obey.", source=S_CT, url=CT, quote="just choose one perspective per chapter", page="body, paragraph beginning 'It helps that Kay'", kind="analysis", polarity="rejects", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: the reporter's paraphrase of Kay's remarks")
add(_file="ctoday", feature="consequence on a household", claim="Wilt reports Kay naming the rule against writing a whole chapter from the viewpoint of a plot-irrelevant medieval courier.", source=S_CT, url=CT, quote="an entire chapter from the viewpoint of a grizzled medieval courier", page="body, paragraph beginning 'It helps that Kay'", kind="analysis", polarity="rejects", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="medium: the reporter's paraphrase of Kay's remarks")
add(_file="ctoday", feature="withheld information and inference", claim="Kay says simply that he trusts his readers.", source=S_CTK, url=CT, quote="I trust my readers", page="body, paragraph beginning 'Still, Kay has resisted'", kind="own-words", polarity="asserts", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="ctoday", feature="annalist voice and deep time", claim="Kay says every book he has written has been in part an attempt to look at how different and how similar the past is.", source=S_CTK, url=CT, quote="how different the past is and how similar it is", page="body, quotation beginning 'Every book I've ever written'", kind="own-words", polarity="asserts", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="ctoday", feature="concrete sensory noun", claim="Kay characterises the people of the past with concrete wants: security, a roof, a harvest.", source=S_CTK, url=CT, quote="wanted security, wanted a roof, wanted a harvest", page="body, quotation beginning 'The people of the past are strange'", kind="own-words", polarity="applies", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="ctoday", feature="other: magic system withheld", claim="Wilt says there are no elaborate, concrete magic systems in Kay's books, which are instead haunted by the transcendent.", source=S_CT, url=CT, quote="There are no elaborate, concrete magic systems here", page="body, paragraph beginning 'Kay's characteristic'", kind="analysis", polarity="asserts", date="2025-06-03", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

bad = check(C)
print("MISMATCHES:", len(bad))
for b in bad: print("   ", b)
json.dump(C, open(os.path.join(D, "kay-craft-raw", "claims3.json"), "w"), ensure_ascii=False, indent=1)
print("claims3:", len(C))
