# -*- coding: utf-8 -*-
import sys, json, os
sys.path.insert(0, "/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/kay-craft-raw")
from build import check, D

OD = "https://soden.substack.com/p/a-quarter-turn"
RP = "https://forum.rpg.net/index.php?threads/talk-to-me-of-guy-gavriel-kay.898766/"
B3 = "https://b3en.substack.com/p/ggk-in-transition"
PH = "http://fantasyhotlist.blogspot.com/2019/05/new-guy-gavriel-kay-interview.html"
NH = "https://brightweavings.com/on-the-strengths-of-fiction-done-as-near-history/"
AQ = "https://brightweavings.com/children-of-earth-and-sky-author-questions/"
DL = "https://brightweavings.com/danica-and-leonora/"
BI = "https://whatever.scalzi.com/2025/05/28/the-big-idea-guy-gavriel-kay-4/"
PB = "https://www.pmb.ox.ac.uk/news/just-enough-light-guy-gavriel-kay-delivers-jrr-tolkien-lecture"
DR = "https://brightweavings.com/drabbles/"

S_OD = "Scott Oden (novelist), 'A Quarter Turn', Towers of Spider-Haunted Mystery (Substack), 2026"
S_UQ = "'Uqbarian', post #19 in 'Talk to me of Guy Gavriel Kay', RPGnet forum, 2022"
S_GB = "'Gavin Bennett', quoted post in 'Talk to me of Guy Gavriel Kay', RPGnet forum, 2022"
S_DZ = "'Daztur', post #10 in 'Talk to me of Guy Gavriel Kay', RPGnet forum, 2022"
S_B3 = "'Brok3n Engines', review of Tigana, Brok3n Engines (Substack), 2025"
S_PH = "Guy Gavriel Kay, interviewed by Patrick St-Denis, Pat's Fantasy Hotlist, 2019"
S_PHI = "Patrick St-Denis (interviewer), paraphrasing Kay's earlier answer, Pat's Fantasy Hotlist, 2019"
S_NH = "Guy Gavriel Kay, 'On the Strengths of Fiction Done as Near-History' (first published at boingboing.net, 2016), Bright Weavings"
S_AQ = "Guy Gavriel Kay, 'Children of Earth and Sky Author Questions', Bright Weavings, 2017"
S_DL = "Guy Gavriel Kay, 'Danica and Leonora', Bright Weavings, 2017"
S_BI = "Guy Gavriel Kay, 'The Big Idea: Guy Gavriel Kay', Whatever (John Scalzi's blog), 2025"
S_PB = "Pembroke College, Oxford (report of Kay's Tolkien Lecture 'Just Enough Light'), 2021"
S_PBK = "Guy Gavriel Kay, quoted from the 2021 Tolkien Lecture in Pembroke College's report, 2021"
S_DR = "Guy Gavriel Kay, 'Aliana in the West' (a 100-word Drabble, (c)2014), reproduced at Bright Weavings, 2025"
S_DRB = "Bright Weavings (Alec Lynch), editorial note on Kay's Drabbles, 2025"

C = []
def add(**kw): C.append(kw)

add(_file="oden", feature="place and institution description", claim="Oden says Kay's invented religions are reflections and echoes that rhyme with the real ones without being identical.", source=S_OD, url=OD, quote="reflections, echoes, versions that rhyme with the real thing", page="body, paragraph beginning 'The Asharites worship the stars'", kind="analysis", polarity="asserts", date="2026-02-23", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="oden", feature="place and institution description", claim="Oden says Kay's worlds feel real in that the reader believes the politics, the cultural tensions and the way power flows through institutions.", source=S_OD, url=OD, quote="you believe in the politics, the cultural tensions, the way power", page="body, paragraph beginning 'Kay walks that line'", kind="analysis", polarity="asserts", date="2026-02-23", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="oden", feature="metaphor discipline", claim="Oden says Kay's fantasy is functional, present to create space rather than to take over the story.", source=S_OD, url=OD, quote="Kay’s fantasy is functional", page="body, paragraph beginning 'Kay's fantasy is functional'", kind="analysis", polarity="asserts", date="2026-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="oden", feature="cadence and rhythm", claim="Oden says Kay's prose can get lyrical in a way that reminds him of Tolkien.", source=S_OD, url=OD, quote="His prose can get lyrical in ways that remind me of", page="body, paragraph beginning 'Critics sometimes hit Kay'", kind="analysis", polarity="asserts", date="2026-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="oden", feature="other: sentimentality as a named risk", claim="Oden reports that critics sometimes fault Kay for being too sentimental and too romantic, and partly concedes the charge.", source=S_OD, url=OD, quote="Critics sometimes hit Kay for being too sentimental, too romantic", page="body, paragraph beginning 'Critics sometimes hit Kay'", kind="analysis", polarity="mentions", date="2026-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="rpgnet", feature="point of view and distance", claim="A tabletop-RPG forum reader says Kay's narrator commentary and foreshadowing often felt heavy-handed to him.", source=S_UQ, url=RP, quote="his narrator commentary and foreshadowing often felt really heavy-handed to me", page="post #19, 2022-06-26", kind="reader", polarity="disputes", date="2022-06-26", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="rpgnet", feature="plainness and economy", claim="The same reader says Kay is a top-notch prose stylist who goes on rather more than he needs to.", source=S_UQ, url=RP, quote="he just goes on rather more than he needs to", page="post #19, 2022-06-26", kind="reader", polarity="disputes", date="2022-06-26", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="rpgnet", feature="other: portent and stated import", claim="The same reader reports a scene in The Lions of Al-Rassan of characters thinking portentous thoughts for five and a half pages.", source=S_UQ, url=RP, quote="thinking portentous thoughts for five and a half pages", page="post #19, 2022-06-26", kind="reader", polarity="disputes", date="2022-06-26", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="rpgnet", feature="naming and forms of address", claim="Another forum reader says the renamed real cities of The Last Light of the Sun left him constantly mixing up not-Constantinople and not-Jerusalem.", source=S_DZ, url=RP, quote="constantly get not-Constantinople and not-Jerusalem mixed up", page="post #10, 2022-06-25", kind="reader", polarity="disputes", date="2022-06-25", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="rpgnet", feature="register modulation", claim="A forum reader says The Lions of Al-Rassan moves between an adventure story and a people-living-through-history story.", source=S_GB, url=RP, quote="a sort of adventure story and a people living through history", page="post quoted at #19, 2022-06-26", kind="reader", polarity="asserts", date="2022-06-26", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")

add(_file="b3en", feature="plainness and economy", claim="A reviewer says that while he enjoys Kay's prose he often wishes there was less of it.", source=S_B3, url=B3, quote="while I enjoy his prose, I often wish there was less", page="final body paragraph", kind="reader", polarity="disputes", date="2025-04-16", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="pathotlist", feature="point of view and distance", claim="Kay says the subject engaging him is that a novel you read is a story being told to you by someone.", source=S_PH, url=PH, quote="a story being told to you by someone", page="answer to 'So what interests a more mature ... Kay nowadays?'", kind="own-words", polarity="asserts", date="2019-05-08", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="pathotlist", feature="annalist voice and deep time", claim="Kay says he is fascinated by how we examine and remember the past and shape the narratives we need from it.", source=S_PH, url=PH, quote="how we examine and remember the past", page="answer to 'So what interests a more mature ... Kay nowadays?'", kind="own-words", polarity="asserts", date="2019-05-08", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="pathotlist", feature="other: structure and shape", claim="Kay says he would be more an architect than a gardener because the shape of a novel matters a lot to him.", source=S_PH, url=PH, quote="the shape of a novel matters a lot to me", page="answer to the architect-or-gardener question", kind="own-words", polarity="asserts", date="2019-05-08", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="pathotlist", feature="place and institution description", claim="Kay says setting came first for A Brightness Long Ago.", source=S_PH, url=PH, quote="I think setting came first here", page="answer about A Brightness Long Ago's arc of emergence", kind="own-words", polarity="asserts", date="2019-05-08", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="pathotlist", feature="place and institution description", claim="The interviewer reports Kay having said that in general setting precedes theme, which grows out of learning about time and place.", source=S_PHI, url=PH, quote="in general setting precedes theme", page="interviewer's question about A Brightness Long Ago", kind="analysis", polarity="mentions", date="2019-05-08", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="medium: the interviewer's paraphrase of an earlier answer, not Kay's transcribed words")

add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="other: writing-advice stance", claim="Kay warns readers to be sceptical when writers present intuitive processes as thought-out planning.", source=S_NH, url=NH, quote="be skeptical when writers present intuitive processes as thought-out planning", page="body, paragraph beginning 'There are a multiplicity of reasons'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="civic record register", claim="Kay says he always includes starter bibliographies in his novels.", source=S_NH, url=NH, quote="And I always include starter bibliographies", page="body, paragraph beginning 'And I found that I liked'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", routeHint="direct curl with browser user agent", registerHint="dm-page", confidence="high")
add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="withheld information and inference", claim="Kay says each reader makes the book they read.", source=S_NH, url=NH, quote="each reader makes the book they read", page="body, paragraph beginning 'And I found that I liked'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", registerHint="none", routeHint="direct curl with browser user agent", confidence="high")
add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="withheld information and inference", claim="Kay says the quarter turn means even a reader who knows the real history cannot be sure where the novel is going.", source=S_NH, url=NH, quote="he or she cannot be sure they know where the novel", page="body, paragraph beginning 'I had come to realize'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="annalist voice and deep time", claim="Kay says he telescoped the Reconquista in The Lions of Al-Rassan so a culture's demise plays out in one or two generations.", source=S_NH, url=NH, quote="I telescoped the Reconquista in Lions", page="body, paragraph beginning 'It was with Lions'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="civic record register", claim="Kay says the Sarantine Mosaic let him develop thoughts about Procopius the historian and about the writers of history and chroniclers.", source=S_NH, url=NH, quote="about the writers of history, chroniclers and artists", page="body, paragraph beginning 'I suppose I've never looked back'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="bw-on-the-strengths-of-fiction-done-as-near-history", feature="other: dates and figures withheld", claim="Kay names as a cost of his method that readers will never learn the year of the Treaty of Utrecht in his novels.", source=S_NH, url=NH, quote="Readers will never learn the year of the Treaty of Utrecht", page="body, paragraph beginning 'So, briefly told'", kind="own-words", polarity="asserts", date="2016 (posted to Bright Weavings 2016-12-10)", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")

add(_file="bw-children-of-earth-and-sky-author-questions", feature="register modulation", claim="Kay says he believes in varying the tension, drama and type of scenes in a book, and even the language the story is told in.", source=S_AQ, url=AQ, quote="even the langiuage in which the story is told", page="answer 4", kind="own-words", polarity="asserts", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="bw-children-of-earth-and-sky-author-questions", feature="civic record register", claim="Kay says artists are the recorders and chroniclers of a time and can become the emblems of a day for later eras.", source=S_AQ, url=AQ, quote="the recorders, chroniclers of a time", page="answer 5", kind="own-words", polarity="asserts", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="bw-children-of-earth-and-sky-author-questions", feature="annalist voice and deep time", claim="Kay says he is interested in shaping a long view, a sense for the reader of time passing across periods.", source=S_AQ, url=AQ, quote="shaping a long view, a sense for the reader of time", page="answer 1", kind="own-words", polarity="asserts", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="bw-children-of-earth-and-sky-author-questions", feature="other: dates and figures withheld", claim="Kay says knowing the themes of history does not necessarily mean the minutiae of dates and places.", source=S_AQ, url=AQ, quote="That doesn’t necessarily mean the minutiae of dates and places", page="answer 2", kind="own-words", polarity="asserts", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="bw-children-of-earth-and-sky-author-questions", feature="plainness and economy", claim="Kay says that if a book is done well readers can be moved by a single line, because they know why the character acted.", source=S_AQ, url=AQ, quote="readers can be moved by a single line", page="answer 4", kind="own-words", polarity="asserts", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="bw-children-of-earth-and-sky-author-questions", feature="point of view and distance", claim="Kay says he is not a detached writer and is very much engaged as he writes intense or quietly moving scenes.", source=S_AQ, url=AQ, quote="I am not a ‘detached’ writer", page="answer 4", kind="own-words", polarity="rejects", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="bw-children-of-earth-and-sky-author-questions", feature="consequence on a household", claim="Kay says Children of Earth and Sky was deliberately set up to be about people who are not important in the scheme of things.", source=S_AQ, url=AQ, quote="about people who are not important in the scheme of things", page="answer 5", kind="own-words", polarity="asserts", date="2017-07-15", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")

add(_file="bw-danica-and-leonora", feature="consequence on a household", claim="Kay says catching something about our own lives, even if less dramatic, is what he is always trying to do in a book.", source=S_DL, url=DL, quote="it catches something about our own lives", page="body, paragraph beginning 'I went with my own feeling'", kind="own-words", polarity="asserts", date="2017-07-04", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="bw-danica-and-leonora", feature="other: early-reader and editorial objection", claim="Kay reports that an experienced early reader from the book trade objected that his two women connect awfully fast.", source=S_DL, url=DL, quote="They connect awfully fast, don’t they?", page="body, paragraph beginning 'Here's where it got interesting'", kind="own-words", polarity="mentions", date="2017-07-04", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="scalzi-bigidea", feature="withheld information and inference", claim="Kay says he is focused on nuance and on letting readers decide what they find in or take away from a book.", source=S_BI, url=BI, quote="letting readers decide what they find in or take away", page="body, paragraph beginning 'Truth is'", kind="own-words", polarity="asserts", date="2025-05-28", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="scalzi-bigidea", feature="other: didacticism refused", claim="Kay says he is offering a story and not giving a lecture, and does not write for lessons.", source=S_BI, url=BI, quote="I’m offering a story not giving a lecture", page="body, paragraph beginning 'You can write about yesterday's snows'", kind="own-words", polarity="asserts", date="2025-05-28", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="scalzi-bigidea", feature="other: summary refused", claim="Kay says a major novel can be made to sound trivial, silly or shallow if boiled down to a paragraph of sound bite.", source=S_BI, url=BI, quote="can be made to sound trivial, silly, shallow if boiled down", page="body, paragraph beginning 'Of course you don't'", kind="own-words", polarity="asserts", date="2025-05-28", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="pembroke", feature="omission as information", claim="Pembroke College reports that Kay's Tolkien Lecture discussed the vital importance of the unsaid and the unexplained in fiction.", source=S_PB, url=PB, quote="the vital importance of the unsaid and the unexplained in fiction", page="news item, second paragraph", kind="analysis", polarity="asserts", date="2021-05", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="medium: a college news report's paraphrase of the lecture, not the lecture text")
add(_file="pembroke", feature="withheld information and inference", claim="Kay asked in the lecture how comfortable we are in our responses to art with mystery and with not knowing.", source=S_PBK, url=PB, quote="how comfortable in our responses to art are we with mystery", page="news item, second paragraph (quotation from the lecture)", kind="own-words", polarity="asserts", date="2021-05-11", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="bw-drabbles", feature="opening sentence", claim="Kay's hundred-word Sarantine Mosaic Drabble opens with a ten-word sentence of plain diction that repeats its final phrase.", source=S_DR, url=DR, quote="She is lying beside her love dreaming of her love.", page="'Aliana in the West', first line", kind="own-words", polarity="applies", date="2014 (reproduced 2025-10-04)", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="medium: the ten-word count and the repetition are countable on the page; 'plain diction' is my characterisation")
add(_file="bw-drabbles", feature="plainness and economy", claim="Bright Weavings records that Kay wrote two Drabbles in 2014, a Drabble being a 100 word short story.", source=S_DRB, url=DR, quote="A Drabble is a 100 word short story", page="editorial note above the stories", kind="analysis", polarity="mentions", date="2025-10-04", routeHint="direct curl with browser user agent", registerHint="herald-pools", confidence="high")

bad = check(C)
print("MISMATCHES:", len(bad))
for b in bad: print("   ", b)
json.dump(C, open(os.path.join(D, "kay-craft-raw", "claims2.json"), "w"), ensure_ascii=False, indent=1)
print("claims2:", len(C))
