# -*- coding: utf-8 -*-
import sys, json
sys.path.insert(0, "/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/kay-craft-raw")
from build import check, D
import os

P = "https://reactormag.com/altering-the-familiar-tigana-by-guy-gavriel-kay/"
Q = "https://thequilltolive.com/2016/01/07/the-masters-of-prose/"
O = "https://onelastsketch.wordpress.com/2011/12/12/flippant-reviews-guy-gavriel-kay/"
LA = "https://lithub.com/some-writing-advice-dont-take-others-advice/"
L5 = "https://lithub.com/guy-gavriel-kay-5-books-in-my-life/"
M = "https://transmissionsfromtomorrow.substack.com/p/meeting-guy-gavriel-kay-what-he-told"
RW = "https://therowanwoodchronicles.blog/2025/12/24/fantasy-as-memory-the-historical-imagination-of-guy-gavriel-kay/"
AB = "https://www.eyrie.org/~eagle/reviews/books/0-698-18327-4.html"
FA = "https://ericfalden.substack.com/p/you-should-read-tigana"
FF = "https://fantasy-faction.com/2013/tigana-by-guy-gavriel-kay"
QC = "https://thequilltolive.com/2016/05/17/children-of-earth-and-sky-a-quiet-and-ponderous-story/"
LB = "https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/"

SRC_P = "Joshua Palmatier (novelist), 'Altering the Familiar: Tigana by Guy Gavriel Kay', Reactor/Tor.com 'That Was Awesome! Writers on Writing', 2016"
SRC_Q = "Andrew Mather, 'The Masters Of Prose', The Quill to Live (review blog), 2016"
SRC_O = "Michal, 'Flippant Reviews: Guy Gavriel Kay', One Last Sketch (blog), 2011"
SRC_LA = "Guy Gavriel Kay, 'Some Writing Advice: Don't Take Others' Advice', Literary Hub, 2019"
SRC_L5 = "Guy Gavriel Kay, '5 Books in My Life', Literary Hub, 2016"
SRC_M = "Guy Gavriel Kay, quoted from a Morrin Centre talk by Joel Miller, 'I Drove 12 Hours to Meet Guy Gavriel Kay', Transmissions from Tomorrow (Substack), 2026"
SRC_MR = "David McMillan, reader comment on Joel Miller's 'I Drove 12 Hours to Meet Guy Gavriel Kay', Transmissions from Tomorrow (Substack), 2026"
SRC_RW = "Chris McBean, 'Fantasy as Memory: The Historical Imagination of Guy Gavriel Kay', The Rowanwood Chronicles (blog), 2025"
SRC_AB = "Russ Allbery, review of Children of Earth and Sky, eyrie.org, reviewed 2022-02-21"
SRC_FA = "Eric Falden, 'You Should Read Tigana', Falden's Forge (Substack), 2024"
SRC_FF = "Alister Davison (aspiring novelist/reviewer), 'Tigana by Guy Gavriel Kay', Fantasy-Faction Classics Corner, 2013"
SRC_QC = "Andrew Mather, 'Children of Earth and Sky - A Quiet and Ponderous Story', The Quill to Live, 2016"
SRC_LB = "Christine Fischer Guy (interviewer), 'The Fantastic Worlds of Guy Gavriel Kay', Los Angeles Review of Books, 2016"

C = []
def add(**kw): C.append(kw)

add(_file="palmatier", feature="place and institution description", claim="Palmatier says the Italian flavour of Tigana's invented world is carried by its word structure, place names and characters.", source=SRC_P, url=P, quote="the flavor of Italy is there—in the word structure, the place names", page="body, paragraph beginning 'In Tigana'", kind="analysis", polarity="asserts", date="2016-07-06", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="palmatier", feature="metaphor discipline", claim="Palmatier disputes the common view that Kay's art lies in his use of language, locating it instead in the alteration of a familiar setting.", source=SRC_P, url=P, quote="not in the use of language, but in the subtle way", page="final body paragraph", kind="analysis", polarity="disputes", date="2016-07-06", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="palmatier", feature="place and institution description", claim="Palmatier says Kay alters the familiar world at the level of everyday ritual, myth, legend and superstition rather than by cosmetic changes.", source=SRC_P, url=P, quote="down to arbitrary everyday rituals, including myths and legends and superstitions", page="body, paragraph beginning 'How he does is it arcane'", kind="analysis", polarity="asserts", date="2016-07-06", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")

add(_file="quilltolive", feature="plainness and economy", claim="Mather says Kay's poetic style is not so dense that passages require hours of thought to decipher.", source=SRC_Q, url=Q, quote="incredibly poetic but also not too dense", page="entry for Guy Gavriel Kay", kind="reception", polarity="asserts", date="2016-01-07", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: an uncredentialed review blog's list entry")
add(_file="quilltolive", feature="place and institution description", claim="Mather calls Kay the most transportive writer he has read, attributing it to years of study of the cultures and places written about.", source=SRC_Q, url=Q, quote="Kay is the most transportive writer I have ever read", page="entry for Guy Gavriel Kay", kind="reception", polarity="asserts", date="2016-01-07", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="medium: an uncredentialed review blog's list entry")

add(_file="onelastsketch", feature="sentence length variation", claim="Michal says The Last Light of the Sun cuts Kay's ornate style down to a rougher language full of sentence fragments.", source=SRC_O, url=O, quote="rife with sentence fragments and strong images recounting the frozen north", page="entry for The Last Light of the Sun", kind="reader", polarity="asserts", date="2011-12-12", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: a self-described flippant survey by a blog reader-critic")
add(_file="onelastsketch", feature="closing sentence", claim="Michal says The Last Light of the Sun has one of the most beautiful closing sentences he has encountered anywhere.", source=SRC_O, url=O, quote="one of the most beautiful closing sentences I’ve encountered anywhere", page="entry for The Last Light of the Sun", kind="reader", polarity="asserts", date="2011-12-12", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="medium: a blog reader-critic's judgment, no analysis of the sentence given")
add(_file="onelastsketch", feature="withheld information and inference", claim="Michal faults Tigana for telling the reader how to feel rather than leaving the feeling to be inferred.", source=SRC_O, url=O, quote="We’re all too often told how to feel", page="entry for Tigana", kind="reader", polarity="disputes", date="2011-12-12", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="onelastsketch", feature="annalist voice and deep time", claim="Michal names as a flaw Kay's tendency to digress into long passages describing the vast import of a historical moment.", source=SRC_O, url=O, quote="off on long tangents describing the vast import of some historical moment", page="entry for Tigana", kind="reader", polarity="disputes", date="2011-12-12", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")

add(_file="lithub-advice", feature="other: writing-advice stance", claim="Kay states in his own essay that there are no rules for writing, offering his own practice as anecdote rather than prescription.", source=SRC_LA, url=LA, quote="There are no rules", page="body, paragraph beginning 'There are no rules'", kind="own-words", polarity="rejects", date="2019-05-15", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="lithub-5books", feature="other: sentence-level craft as a value", claim="Kay names sentence-by-sentence insight and brilliance in Shirley Hazzard's The Transit of Venus as the object of his extreme admiration.", source=SRC_L5, url=L5, quote="the sentence by sentence insight and brilliance is extreme", page="answer to 'Is there a book you wish you had written?'", kind="own-words", polarity="asserts", date="2016-05-24", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="lithub-5books", feature="other: influence and reading", claim="Kay says he does not write like Shirley Hazzard even though he admires her craft.", source=SRC_L5, url=L5, quote="I don’t write like that", page="answer to 'Is there a book you wish you had written?'", kind="own-words", polarity="asserts", date="2016-05-24", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="lithub-5books", feature="cadence and rhythm", claim="Kay says the books he rereads most are the poetry of Yeats or George Seferis.", source=SRC_L5, url=L5, quote="the poetry of Yeats or George Seferis", page="answer to 'What's the book you reread the most?'", kind="own-words", polarity="mentions", date="2016-05-24", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: the page records the rereading, not any effect on his sentences")

add(_file="tft-miller", feature="other: exposition without prerequisite knowledge", claim="Kay says it is important to him that readers who know nothing of the actual history never feel behind the curve.", source=SRC_M, url=M, quote="don’t ever feel they’re behind the curve or missing something", page="section 'You Don't Need a Course in the 100 Years War'", kind="own-words", polarity="asserts", date="2026-05-03", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="tft-miller", feature="other: no template", claim="Kay says he has no pattern, template or system for writing a novel.", source=SRC_M, url=M, quote="I don’t have a pattern, a template, or a system", page="section 'On Craft: There Is No System'", kind="own-words", polarity="asserts", date="2026-05-03", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="tft-miller", feature="annalist voice and deep time", claim="Kay says writing characters who are aware of their own past and their country's and culture's past is what lets him work with historical awareness.", source=SRC_M, url=M, quote="aware of their own past and the past of their country", page="section 'The Past Isn't Even Past'", kind="own-words", polarity="asserts", date="2026-05-03", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="tft-miller", feature="plainness and economy", claim="A reader commenting on the piece describes Kay's writing as seeming casual yet perfect.", source=SRC_MR, url=M, quote="it seems so casual yet so perfect", page="comments, David McMillan, May 25", kind="reader", polarity="asserts", date="2026-05-25", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="rowanwood", feature="plainness and economy", claim="McBean says Kay does not bury the reader in invented terminology or ornate description, unlike much epic fantasy.", source=SRC_RW, url=RW, quote="he does not bury the reader in invented terminology or ornate description", page="section 'Lyrical clarity rather than baroque fantasy'", kind="analysis", polarity="asserts", date="2025-12-24", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="medium: a personal blog with no critical standing; wording is unsourced assertion")
add(_file="rowanwood", feature="cadence and rhythm", claim="McBean says the beauty of Kay's prose comes from rhythm and precision rather than spectacle.", source=SRC_RW, url=RW, quote="The beauty of the prose comes from rhythm and precision, not spectacle", page="section 'Lyrical clarity rather than baroque fantasy'", kind="analysis", polarity="asserts", date="2025-12-24", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: a personal blog with no critical standing")
add(_file="rowanwood", feature="cadence and rhythm", claim="McBean says Kay's sentences are musical but rarely flashy.", source=SRC_RW, url=RW, quote="Kay’s sentences are musical, but they are rarely flashy", page="section 'Lyrical clarity rather than baroque fantasy'", kind="analysis", polarity="asserts", date="2025-12-24", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: a personal blog with no critical standing")
add(_file="rowanwood", feature="dialogue register", claim="McBean says Kay's characters speak with restraint, implication and subtext.", source=SRC_RW, url=RW, quote="People speak with restraint, implication, and subtext", page="section 'Dialogue as character and culture'", kind="analysis", polarity="asserts", date="2025-12-24", routeHint="direct curl with browser user agent", registerHint="none", confidence="medium: a personal blog with no critical standing")
add(_file="rowanwood", feature="consequence on a household", claim="McBean says triumphs in Kay are provisional and victories costly.", source=SRC_RW, url=RW, quote="Triumphs are provisional. Victories are costly", page="section 'Melancholy as a narrative tone'", kind="analysis", polarity="asserts", date="2025-12-24", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="medium: a personal blog with no critical standing")
add(_file="rowanwood", feature="point of view and distance", claim="McBean says Kay's melancholy shows stylistically as frequent use of memory, foreknowledge and reflective distance.", source=SRC_RW, url=RW, quote="his frequent use of memory, foreknowledge, and reflective distance", page="section 'Melancholy as a narrative tone'", kind="analysis", polarity="asserts", date="2025-12-24", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="medium: a personal blog with no critical standing")

add(_file="allbery", feature="point of view and distance", claim="Allbery calls Kay the master of a specific type of omniscient tight third person narration.", source=SRC_AB, url=AB, quote="the master of a specific type of omniscient tight third person", page="body, paragraph beginning 'Guy Gavriel Kay is'", kind="analysis", polarity="asserts", date="2022-02-21", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="allbery", feature="point of view and distance", claim="Allbery says the reader gets narrative commentary, foreshadowing and emotional emphasis separate from the character's thoughts.", source=SRC_AB, url=AB, quote="narrative commentary, foreshadowing, and emotional emphasis apart from the character's thoughts", page="body, paragraph beginning 'Guy Gavriel Kay is'", kind="analysis", polarity="asserts", date="2022-02-21", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="allbery", feature="omission as information", claim="Allbery says Kay states explicitly, and sometimes repetitively, what is important rather than leaving it to the reader.", source=SRC_AB, url=AB, quote="if something is important, Kay tells you, explicitly and sometimes", page="body, paragraph beginning 'Guy Gavriel Kay is'", kind="analysis", polarity="rejects", date="2022-02-21", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="allbery", feature="point of view and distance", claim="Allbery says the narrative commentary functions like a movie soundtrack, telling the reader when to pay attention.", source=SRC_AB, url=AB, quote="The narrative commentary functions like a soundtrack in a movie", page="body, paragraph beginning 'Guy Gavriel Kay is'", kind="analysis", polarity="asserts", date="2022-02-21", routeHint="direct curl with browser user agent", registerHint="dm-page", confidence="high")
add(_file="allbery", feature="other: competing perspectives on one moment", claim="Allbery says Kay switches viewpoint mid-scene without replaying the scene, giving only a moment of doubled perspective.", source=SRC_AB, url=AB, quote="just a moment of doubled perspective or retrospective commentary", page="body, paragraph beginning 'Kay also strikes'", kind="analysis", polarity="asserts", date="2022-02-21", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")

add(_file="falden", feature="other: exposition through character memory", claim="Falden says circumstances in Tigana are explained through the eyes or memory of the relevant characters.", source=SRC_FA, url=FA, quote="usually through the eyes or memory of the relevant characters", page="section 'World-Building & Exposition'", kind="analysis", polarity="asserts", date="2024-02-23", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="falden", feature="point of view and distance", claim="Falden says Kay uses a limited omniscience that alternates between inhabiting a head and standing more objectively outside it.", source=SRC_FA, url=FA, quote="Kay employs a limited omniscience that vacillates between being in someone’s head", page="section 'Writing Style'", kind="analysis", polarity="asserts", date="2024-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="falden", feature="point of view and distance", claim="Falden says Kay varies narrative distance, zooming in and out, with some scenes detailed and others sparse.", source=SRC_FA, url=FA, quote="Kay changes narrative distance incredibly well, zooming in and out", page="section 'Writing Style'", kind="analysis", polarity="asserts", date="2024-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="falden", feature="naming and forms of address", claim="Falden faults some of Kay's invented names in Tigana as poor.", source=SRC_FA, url=FA, quote="And frankly, some of his names are poor", page="section 'Why You Might Not Love It'", kind="analysis", polarity="disputes", date="2024-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="falden", feature="withheld information and inference", claim="Falden says people and things that seem innocuous in Tigana's opening turn out later to be Chekhov's guns.", source=SRC_FA, url=FA, quote="turn out—all at once—to be Chekhov’s guns", page="section 'Why You Might Not Love It', Slow Start", kind="analysis", polarity="asserts", date="2024-02-23", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="ffaction", feature="civic record register", claim="Davison says Tigana can feel quite academic in its structure and descriptions.", source=SRC_FF, url=FF, quote="Tigana can feel quite academic in its structure and descriptions", page="body, paragraph beginning 'The notes about the author'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="ffaction", feature="plainness and economy", claim="Davison says Kay's prose in Tigana often felt cold and clinical, even lacking in emotion.", source=SRC_FF, url=FF, quote="the prose often felt cold and clinical, even lacking in emotion", page="body, paragraph beginning 'While the technical aspects'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="ffaction", feature="per-speaker register", claim="Davison says Tigana's characters often sounded the same as one another.", source=SRC_FF, url=FF, quote="Characters often sounded the same", page="body, paragraph beginning 'While the technical aspects'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")
add(_file="ffaction", feature="dialogue register", claim="Davison says Tigana's dialogue is sometimes little more than a summary of history between speech marks.", source=SRC_FF, url=FF, quote="little more than a summary of history between speech marks", page="body, paragraph beginning 'While the technical aspects'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="ffaction", feature="point of view and distance", claim="Davison reports a feeling of detachment from Tigana's story, as if it happened long ago rather than now.", source=SRC_FF, url=FF, quote="a certain feeling of detachment from the story", page="body, paragraph beginning 'Yet, despite the achievements'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")
add(_file="ffaction", feature="concrete sensory noun", claim="Davison says Tigana's final battle gives the armies' strengths and tactics but little else, so the soldiers are numbers rather than men.", source=SRC_FF, url=FF, quote="They are numbers, not men", page="body, paragraph beginning 'The notes about the author'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="ffaction", feature="annalist voice and deep time", claim="Davison says Tigana read to him as a dry slice of history rather than an immediate story.", source=SRC_FF, url=FF, quote="a dry slice of history", page="body, paragraph beginning 'Yet, despite the achievements'", kind="reception", polarity="disputes", date="2013-07-06", routeHint="direct curl with browser user agent", registerHint="chronicle-line", confidence="high")

add(_file="quill-coes", feature="consequence on a household", claim="Mather says Kay always tells the story of the person rather than of the people.", source=SRC_QC, url=QC, quote="Kay always tells the story of the person not the people", page="body, paragraph beginning 'Children of Earth and Sky is a story'", kind="reception", polarity="asserts", date="2016-05-17", routeHint="direct curl with browser user agent", registerHint="dossier-archivist", confidence="high")
add(_file="quill-coes", feature="withheld information and inference", claim="Mather says the messages of Children of Earth and Sky are more subtle and quietly spoken than in Kay's other books.", source=SRC_QC, url=QC, quote="much more subtle and quietly spoken than Kay’s other books", page="body, final paragraph", kind="reception", polarity="asserts", date="2016-05-17", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

add(_file="larb", feature="cadence and rhythm", claim="Fischer Guy states that Kay was a poet first and still publishes poetry from time to time.", source=SRC_LB, url=LB, quote="he was a poet first, and still publishes poetry", page="interview introduction", kind="analysis", polarity="mentions", date="2016-06", routeHint="direct curl with browser user agent", registerHint="none", confidence="high")

bad = check(C)
print("MISMATCHES:", len(bad))
for b in bad: print("  ", b)
json.dump(C, open(os.path.join(D, "kay-craft-raw", "claims1.json"), "w"), ensure_ascii=False, indent=1)
print("claims:", len(C))
