"""G0-FOLD batch 2 — CHARSET (§882.4). Marks ⟦G0-20⟧ … ⟦G0-31⟧."""
from foldlib import Folder, fold_json
F = Folder()

# ── §8.0 ───────────────────────────────────────────────────────────────────
F.rep("where every allowed set is DERIVED by the existing manifest compiler from the renderers' own bytes (§1.11: 759 · 218 · 191)",
      "where every allowed set is DERIVED by the existing manifest compiler from the renderers' own bytes (§1.11: 759 · 218 · **190** — ⟦G0-20⟧ CHARSET Car 0 CONFIRMED 759 and 218 to the byte and measured `S` = 190 under the context-anchored reading, ⟦G0-3⟧)")

# ── §8.1 ───────────────────────────────────────────────────────────────────
F.rep("`CharsetSurface` (six = WRWALKER's seven minus `news`)",
      "`CharsetSurface` (six = WRWALKER's eight minus `news` and `web-transitive`, `web` spelled `web-display` — ⟦G0-2⟧)")
F.rep("invisible (U+00AD, U+180E, U+200B-200D, U+2060-2064, U+FEFF, U+FFF9-FFFB)",
      "invisible (⟦G0-3⟧⟦CHAIR §882.4⟧ **U+00A0** — the NBSP both jsPDF passes silently collapse to a space, measured by Car 0 probe 3 — U+00AD, U+180E, U+200B-200D, U+2060-2064, U+FEFF, U+FFF9-FFFB)")
F.rep("the runtime PATH is PLAUSIBLE — Car 0 probe 1 settles it, fallback §8.7 R1) = **218**;",
      "~~the runtime PATH is PLAUSIBLE — Car 0 probe 1 settles it, fallback §8.7 R1~~ ⟦G0-20⟧ **the runtime PATH is CONFIRMED** — CHARSET Car 0 probe 1 on jspdf 4.2.1 in the dock: `metadata.Unicode` present, Helvetica bound to `WinAnsiEncoding`, `|W|` **27** with `U+20AC → 128`, `W ∩ ({20..7E} ∪ {A0..FF}) = ∅`, and the recon's decode of the dependency's own compressed block yields the SAME 27 pairs byte for byte (`CROSS-ASSERT A === B: true`) — §8.7 R1 RETIRED, §14 E27 SETTLED) = **218** (CONFIRMED: 95 + 96 + 27; `|D ∩ C|` 217, `C \\ D = {U+00AD}`);")
F.rep(r"`S = { cp ∈ C : sanitizeJsPdfText(String.fromCodePoint(cp)) === String.fromCodePoint(cp) }` — the text pass MEASURED by execution = **191** today (`s()` strips all 27 of `W`; its class is `\x20-\x7E\xA0-\xFF`);",
      r"`S = { cp ∈ C : sanitizeJsPdfText('a' + String.fromCodePoint(cp) + 'a') === 'a' + String.fromCodePoint(cp) + 'a' }` — ⟦G0-3⟧⟦G0-20⟧ the CONTEXT-ANCHORED whole pass, MEASURED by execution = **190** today (volume 191 → measured 190; the bare single-codepoint predicate the volume wrote reads 189 because `' '.trim()` is empty; `s()` strips all 27 of `W` — its class is `\x20-\x7E\xA0-\xFF` — and its `\s+` collapse turns `U+00A0` into `U+0020`, which is why NBSP is now banned);")
F.rep("(`institutions.name` = `D ∩ S` = 190; `U+00AD` is in `S`, not in `D`, and banned anyway)",
      "(`institutions.name` = `D ∩ S` = **189** (volume 190 → 189); `U+00AD` is in `S`, not in `D`, and banned anyway; `U+00A0` is in `D`, not in `S`, and banned now too — ⟦G0-3⟧)")

# ── §8.2 ───────────────────────────────────────────────────────────────────
F.rep("`custom-charset` · 0 B; excluded from OSR's scan by name (`isObservedShapeScanPath` excludes `.generated.js`, `:210`)",
      "`custom-charset` · 0 B; excluded from OSR's SCAN by name (`isObservedShapeScanPath` excludes `.generated.js`, `:210`) — ⟦G0-4⟧⟦G0-22⟧ but NOT from its INPUT manifest (`isObservedShapeSubjectPath :213` has no exclusion): a new generated file under `src/` reds `check:observed-shape-readers` on execution-INPUT provenance and costs the commit → `--write` → commit ritual (§1.13), measured by Car 0 probe 4")
F.rep(r"`sanitizeJsPdfText(v)` — Car 1: the hoisted `s()` body, byte-identical (`String(v||'').replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g,' ').replace(/\s+/g,' ').trim()`);",
      r"`sanitizeJsPdfText(v)` — Car 1: the hoisted `s()` body, byte-identical (`String(v||'').replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g,' ').replace(/\s+/g,' ').trim()`) — ⟦G0-21⟧ byte-identical to `generateCampaignPDF.js:88`'s spelling; `generateWorldBook.js:61`'s differs by whitespace only (`String(v || '') … replace(/\s+/g, ' ')`) and the two bodies agree on `S` (measured `true`; exactly two copies of the class exist in the tree), so Car 1 hoists the CAMPAIGN spelling and SAYS SO — 'byte-identical' is a claim about one file;")
F.rep("`surfaceClasses` (the six), `charsetPolicy`, per free-text field `surfaces: [...]` (41 fields;",
      "`surfaceClasses` (the six, `web` spelled `web-display` — ⟦G0-2⟧), `charsetPolicy`, per free-text field `surfaces: [...]` (41 fields;")
F.rep("`customContentSliceRuntime-*` (lazy) · 0 B PLAUSIBLE — ⟦A5 B5⟧ the slice's OWN dynamic edge writes to the SLICE chunk's map; the real risk is the STATIC edge `customContentManifest.js → leaf` joining an ENTRY-owned dynamic import's transitive closure; Car 0 probe 6 measures; cure §8.7 R2",
      "`customContentSliceRuntime-*` (lazy) · 0 B — ⟦A5 B5⟧ the slice's OWN dynamic edge writes to the SLICE chunk's map; the real risk is the STATIC edge `customContentManifest.js → leaf` joining an ENTRY-owned dynamic import's transitive closure; ⟦G0-23⟧⟦CHAIR §882.4⟧ Car 0 probe 6 MEASURED the static graph over 2,154 modules (`@babel/parser`, the eager set taken from `vite.config.js`'s own `EAGER_FIRST_PAINT_MODULES` — 263): **FOURTEEN** static importers of `customContentManifest.js`, not five; `|R|` = 56 modules reach it transitively; EAGER modules reaching it **0** (so '0 eager bytes' holds); **FIVE entry-owned dynamic imports land in `R`** with witness chains (`AppViews.jsx → CompendiumPanel.jsx → compendium/CustomContent.jsx → customContentManifest.js`, 2 hops; `AppViews.jsx → AccountPage.jsx → … → lib/contentPacks.js → …`; `neighbourSlice.js → userRouteCharter.js → … → contentPacks.js → …`; `accountImportSlice.js → accountImportBody.js → contentPacks.js → …`; `settlementPendingEditActions.js → pendingEditCommitRuntime.js → … → contentPacks.js → …` — fold re-run of `charset-p6.probe.mjs`/`p6b`, TRUE_EXIT 0, the same five), so on R2's own mechanism the ENTRY's `__vite__mapDeps` WOULD gain the filename — **R2's `import()` cure is Car 1's DEFAULT from its first byte**, and the byte half (~40 B against the closure margin) rides the ONE G5 probe build")
F.rep("`surfaces['campaign-pdf'].count === |{cp ∈ C : sanitizeJsPdfText(cp) === cp}|` recomputed live; `D ∩ S` for `institutions.name` = 190 as ARITHMETIC over the two live sets (not a literal)",
      "`surfaces['campaign-pdf'].count === |{cp ∈ C : sanitizeJsPdfText('a' + cp + 'a') === 'a' + cp + 'a'}|` recomputed live (⟦G0-3⟧⟦G0-24⟧ the context-anchored predicate — 190; the derivation and this arm agree BY CONSTRUCTION only under this reading); `D ∩ S` for `institutions.name` = **189** as ARITHMETIC over the two live sets (not a literal); ⟦G0-3⟧ a `U+00A0` in a name → `invisible_format` on every surface, with `s('a\\u00A0a') === 'a a'` pinned in the test body as the REASON; ⟦G0-25⟧ the face roster read from `theme.js` equals the `public/fonts` `readdirSync` set (`ROSTER == DIR listing: true` at C′ — a silent divergence is a font the dossier will not embed)")

# ── §8.3 ───────────────────────────────────────────────────────────────────
F.rep("HONESTY → the one derivation step not executable read-only (the jsPDF runtime path) is PLAUSIBLE with Car 0 probe 1 and a data-driven fallback that is still not a hand-typed list.",
      "HONESTY → the one derivation step not executable read-only (the jsPDF runtime path) ~~is PLAUSIBLE with Car 0 probe 1~~ ⟦G0-20⟧ is CONFIRMED by Car 0 probe 1 (both methods agree byte for byte), the data-driven fallback surviving as a cross-assert that is still not a hand-typed list.")

# ── §8.5 Car 0 ─────────────────────────────────────────────────────────────
F.rep("STOP: probe 4 > 0 (redesign the reads before any bytes); probe 2 ≠ 8 faces (the roster parse is wrong, not the fonts).",
      "STOP: probe 4 > 0 (redesign the reads before any bytes); probe 2 ≠ 8 faces (the roster parse is wrong, not the fonts). ⟦G0-25⟧ **DISCHARGED at C′** (receipt `$SP/laneG0CHARSET-receipt.md`, ~04:37–05:03 ET; 31 logs `$SP/charset-car0-*.log`; probes `laneG0CHARSET-tree/charset-p*.probe.mjs`; zero bytes; every vitest under the shared mutex with `TRUE_EXIT` captured, no exit 3) — **no §8.5 STOP fired. PREDICTED → MEASURED:** probe 1 `metadata.Unicode` PLAUSIBLE → **present**; `|W|` 27 · `W[0x20AC]` 128 → **27 · 128**; fallback decode 27 and `A ≡ B` → **true**; `|C|` 218 → **218** · probe 2 faces 8 (STOP if ≠ 8) → **8** (AST walk and comment-stripped regex agree; `Lora-{Regular,Bold,Italic,BoldItalic}`, `Nunito-{Regular,Bold,ExtraBold,Italic}` `?v=2`, `Font.register` ×2); `|D|` 759 → **759**; per-face 779 ×4 / 939 ×4, union 959 → **exact**; `U+00AD ∉ D`, `W ⊂ D`, `|D ∩ C|` 217 → **true · true · 217**; comment-stripping a no-op on `theme.js` at C′ (`raw-source regex count: 8`) — the MINT is correct by construction, recorded so nobody removes the stripper as 'unnecessary' · probe 3 `|S|` 191 → **191 class-alone / 190 context-anchored / 189 bare** (⟦G0-3⟧); `s()` at `:88`/`:61`, exactly 2 copies → **CONFIRMED**, bodies differing by whitespace (⟦G0-21⟧) · probe 4 new scanned leaves → OSR findings 0 (STOP if > 0) → **0**, gate output byte-identical to the unmodified control (`1993 finding(s), exactly matching the frozen inventory`, 15.3 s); the non-vacuity plant → **reds by name** (`NEW zzzCharsetProbeKey on powerStructure — 1 read(s) … ceiling 0`); the gate with the `.generated.js` present (unpriced) → **RED on execution-INPUT provenance**, the `--write` absorb **REFUSED ×2 until committed** (⟦G0-4⟧⟦G0-22⟧) · probe 5 lighting `files/parked/credited` +4/+1/+3 → **2499 / 371 / 2128 = +4 / +1 / +3** (⟦A18 E2⟧ CONFIRMED by execution) and `titles/suiteTitles` ≈ 25–35 → **22454 / 6072 = +17 / +3** with the four charted arms drafted (⟦G0-26⟧) · probe 6 (build-free half; the build half declared OWED to the ONE G5 probe build — the brief forbade a build in the read-only wave, RATIFIED §882.4): static importers 5 → **14**; EAGER reaching the manifest 0 → **0**; entry-owned dynamic imports landing in `R` 'none hoped' → **5 with witness chains** (⟦G0-23⟧).")

# ── §8.5 Car 1 ─────────────────────────────────────────────────────────────
F.rep("`jsPdfText.js` + the two painters importing it (byte-identical), the vite pin, the three tests (`customContentCharset`, `namingDataCharset`, `customContentCharsetLazy`).",
      "`jsPdfText.js` + the two painters importing it (byte-identical to the campaign spelling, ⟦G0-21⟧), the vite pin, the three tests (`customContentCharset`, `namingDataCharset`, `customContentCharsetLazy`), ⟦G0-23⟧⟦CHAIR §882.4⟧ **and the manifest → leaf edge as `import()` at the admission call FROM THE FIRST BYTE** (R2's cure is the DEFAULT, not a contingency — cutting the static edge and re-cutting after the probe build is strictly more expensive and the static graph already says which way it goes; Car 1 proof 6 then confirms the ENTRY's `__vite__mapDeps` unchanged by filename), ⟦G0-3⟧ `S` derived by the context-anchored predicate (190) and `U+00A0` in `bans.invisible`, ⟦G0-2⟧ the surface token `web-display`.")
F.rep("(6) a full `npm run build` + `matseam-closure.mjs` on the dock vs the base: the eight closure chunks byte- and hash-identical, engine 675,764 unchanged, a new `custom-charset-*.js` present.",
      "(6) a full `npm run build` + `matseam-closure.mjs` on the dock vs the base: the eight closure chunks byte- and hash-identical, engine unchanged (675,339 at T13's `594c7521f`; re-measured at boarding), a new `custom-charset-*.js` present, ⟦G0-23⟧ **and the ENTRY chunk's `__vite__mapDeps` array diffed BY FILENAME against the base — unchanged, the `import()` cure holding** (the build half of probe 6 the read-only wave could not run; it rides the ONE G5 probe build, no separate build owed).")
F.rep("STOP: any closure byte moved (find the eager edge); proof 4's plants do not red; the hoist changes a painted byte.",
      "STOP: any closure byte moved (find the eager edge); proof 4's plants do not red; the hoist changes a painted byte; ⟦G0-22⟧ the OSR gate red on anything OTHER than the execution-INPUT provenance of the generated file (that red is expected and absorbed by the §1.13 ritual; a FINDING is not).")
F.rep("OSR 0 findings (probe 4), `.generated.js` excluded from OSR;",
      "OSR 0 findings (⟦G0-25⟧ probe 4 CONFIRMED — the two scanned leaves produce 0 new findings, gate output byte-identical, and a planted resolver-visible read reds by name: §8.7 R8 RETIRED on the findings axis), ~~`.generated.js` excluded from OSR~~ ⟦G0-4⟧⟦G0-22⟧ `.generated.js` excluded from the SCAN but NOT the input manifest — **the provenance ritual (commit → `--write` → commit) is Car 1's and is listed in this bill**;")
F.rep("test-side — three new test files: lighting `files +3`, `parked +1`, `credited +2` (⟦A18 E2⟧ `customContentCharsetLazy.test.js` is dist-gated and parks), titles/suiteTitles per probe 5 → ONE refreeze at the landing tip;",
      "test-side — three new test files: lighting `files +3`, `parked +1`, `credited +2` (⟦A18 E2⟧ `customContentCharsetLazy.test.js` is dist-gated and parks — PROVEN by execution in probe 5), titles/suiteTitles per probe 5 → ONE refreeze at the landing tip — ⟦G0-26⟧⟦CHAIR §882.4⟧ **MEASURED through the walker's own assertions with the four charted arms drafted: Cars 1 + 2 together `files +4 / parked +1 / credited +3 / titles +17 / suiteTitles +3`, so a CHARSET train landing Cars 1 + 2 as one consist owes ONE refreeze at `2499 / 371 / 2128 / 22454 / 6072` over C′'s `2495 / 370 / 2125 / 22437 / 6069`** — the triple is HARD (the build test's 5 titles / 1 suite are parked, never credited), the title pair is DRAFT-DEPENDENT (22 authored, 17 credited; every extra `it()` moves it one-for-one) and E30's '≈ 25–35' read HIGH; the refreeze runs on the CLEAN COMMITTED tip (it refuses a dirty tree and exits non-zero by design — the green re-run afterwards is the proof, not the refreeze run);")

# ── §8.5 Car 3 ─────────────────────────────────────────────────────────────
F.rep("`S` converges to `C` (218) on the next regen; `world-book` fields grow by the 27 (`institutions.name` 190 → 217);",
      "`S` converges to `C` minus the collapsed NBSP — **217** (⟦G0-3⟧⟦G0-27⟧ volume 218 → 217: `\\s+` and `trim` survive Car 3, and `U+00A0` is banned regardless) on the next regen; `world-book` fields grow by the 27 (`institutions.name` **189 → 216**, volume 190 → 217);")
F.rep("the owner vetoes (then `S` stays 191 and the table records it — honest in both states).",
      "the owner vetoes (then `S` stays 190 — ⟦G0-3⟧ — and the table records it — honest in both states).")

# ── §8.6 ───────────────────────────────────────────────────────────────────
F.rep("| Car 0 | any time after COUPLED lands (it READS the coupled tip's `s()` lines and the GLYPH arm) | the chair |",
      "| Car 0 | any time after COUPLED lands (it READS the coupled tip's `s()` lines and the GLYPH arm) — ⟦G0-25⟧ DISCHARGED at C′ (Opus 5, ~04:37–05:03 ET; probe 6's build half rides the G5 probe build) | the chair |")

# ── §8.7 ───────────────────────────────────────────────────────────────────
F.rep("| R1 | the jsPDF runtime table is not reachable in node the way `:3011-3027` suggests | 25 % · half a day | Car 0 probe 1; fallback: decode the dependency's own compressed block with its own `uncompress` (CONFIRMED (recon) to yield 27) — still never a typed list; a third check cross-asserts both methods when both exist |",
      "| R1 | ~~the jsPDF runtime table is not reachable in node the way `:3011-3027` suggests~~ ⟦G0-28⟧ **RETIRED** — CHARSET Car 0 probe 1: reachable on jspdf 4.2.1, 27 keys, `CROSS-ASSERT A === B: true` against the decoded compressed block (§14 E27 SETTLED) | volume '25 % · half a day' → 0 % · nothing owed | the decode method survives as Car 1's cheap cross-assert arm (both are pure reads of `node_modules`) |")
F.rep("| ⟦A5 B5⟧ LIKELY, MEASURED (was '20 %') · one edit |",
      "| ⟦A5 B5⟧ LIKELY → ⟦G0-23⟧ **CONFIRMED structurally at C′** (five entry-owned dynamic targets reach `customContentManifest.js` statically; fourteen static importers, not five) · the cure is Car 1's DEFAULT, so the residual is the byte half (~40 B) on the G5 probe build |")
F.rep("and `customContentManifest.js` has FIVE static importers at `60255ca8e` (`contentEffectProjection`, `contentReview`, `contentSampleCategoryFixtures`, `contentVocabulary`, `customContentUsage`),",
      "and `customContentManifest.js` has FIVE static importers at `60255ca8e` (`contentEffectProjection`, `contentReview`, `contentSampleCategoryFixtures`, `contentVocabulary`, `customContentUsage`) — ⟦G0-23⟧ **FOURTEEN at C′**; the nine the list omitted: `compendium/CustomContent.jsx`, `CustomContentEditor.jsx`, `CustomItemAttributes.jsx`, `customCategories.js`, `contentStudio/ContentDraftEntry.jsx`, `aiCharter.js`, `aiOutputSchema.js`, `content/livingContentRoster.js`, **`lib/contentPacks.js`** — the hub of four of the five entry-owned chains, the importer the five-item census missed and what hid R2's blast radius —,")
F.rep("| R8 | OSR: two new `src/domain/content` files enter the scan; a resolver-visible read would be a finding with ceiling 0 | 10 % · a `--write` re-freeze | probe 4 dry-runs it; the leaf reads only its own table and a caller-supplied `Record<string, unknown>` |",
      "| R8 | OSR: two new `src/domain/content` files enter the scan; a resolver-visible read would be a finding with ceiling 0 — ⟦G0-22⟧ **RETIRED on the findings axis** (probe 4: 0 new findings, byte-identical gate output — `definition[field]` is an element access the detector never counts, `legacy-reader-shape-scan.mjs:532`, and `table`/`cls`/`entry` never resolve to a corpus shape) **and REPLACED on the provenance axis**: the `.generated.js` reds the gate on execution-INPUT provenance and needs the commit → `--write` → commit ritual (§1.13) | volume '10 % · a `--write` re-freeze' → 100 % · one governed ABSORB write, priced | the ritual in Car 1's bill; a plant proves the scan still reds by name |")

# ── §10.1 G5 admission clause ───────────────────────────────────────────────
F.rep("(⟦A25 E9⟧ the expected reading is 0 new findings — the 'per-file sha' write the volume feared was a phantom);",
      "(⟦A25 E9⟧ the expected reading is 0 new findings — the 'per-file sha' write the volume feared was a phantom; ⟦G0-4⟧⟦CHAIR §882.4⟧ HALF a phantom: CHARSET Car 1's `.generated.js` moves the execution-INPUT digest and costs a governed ABSORB `--write` by the §1.13 ritual — ruled NOT growth and NOT a STOP, priced into the G5 bill);")

# ── §11 ────────────────────────────────────────────────────────────────────
F.rep("OSR 0 new findings (⟦A25 E9⟧; `.generated.js` excluded by name)",
      "OSR 0 new findings (⟦A25 E9⟧; `.generated.js` excluded from the SCAN by name — ⟦G0-4⟧ but it moves the input digest: the commit → `--write` → commit ritual)")
F.rep("titles per Car 0 probe 5 (PLAUSIBLE ≈ 25–35)",
      "titles per Car 0 probe 5 (⟦G0-26⟧ MEASURED with the charted arms drafted: +17 credited / +3 suite titles, the build test's 5/1 parked; the ≈ 25–35 band read high)")
F.rep("new literal titles ≈ **250** (PLAUSIBLE: CAPACITY 27 · TUNEREG 42 · SOAKCHAIN ≈ 37 · READERREVIEW 15 · COVERAGE 19 · WRWALKER ≈ 39 · CHARSET ≈ 30 · WORKER 42)",
      "new literal titles ≈ **247 authored, ≈ 242 credited** (PLAUSIBLE: CAPACITY 27 · TUNEREG 42 · SOAKCHAIN ≈ 37 · READERREVIEW 15 · COVERAGE 19 · WRWALKER ≈ 43 (⟦G0-2⟧⟦G0-10⟧⟦G0-12⟧) · CHARSET 22 authored / 17 credited (⟦G0-26⟧ measured with drafts) · WORKER 42 — the two parked build files' titles never count)")
F.rep("`check:observed-shape-readers` RUN at every src car's tip; 0 new findings and no sentinel/rowTag movement expected (PLAUSIBLE per car; probe 4 for CHARSET); ⟦CHAIR-R1⟧ after T13's mint act (the LAST OSR write of the arc, §879.11 R8) a HORIZON car that needs OSR growth is a STOP, never a `--write` |",
      "`check:observed-shape-readers` RUN at every src car's tip; 0 new findings and no sentinel/rowTag movement expected (PLAUSIBLE per car; ⟦G0-22⟧ CHARSET's probe 4 CONFIRMED 0 findings); ⟦CHAIR-R1⟧ after T13's mint act (the LAST OSR write of the arc, §879.11 R8) a HORIZON car that needs OSR growth is a STOP, never a `--write` — ⟦G0-4⟧⟦CHAIR §882.4⟧ **but an execution-INPUT provenance ABSORB for a new generated/JSON src artifact is NOT growth** (0 findings, no ceiling, no identity) and is a priced governed `--write` inside HORIZON-DARK by the commit → `--write` → commit ritual (§1.13) |")

# ── §14 ────────────────────────────────────────────────────────────────────
F.rep("| E27 | the jsPDF runtime WinAnsi table is reachable at `getFont().metadata.Unicode.encoding.WinAnsiEncoding` in node (§8.1) | CHARSET Car 0 probe 1; fallback decodes the dependency's own compressed block |",
      "| E27 | ~~the jsPDF runtime WinAnsi table is reachable at `getFont().metadata.Unicode.encoding.WinAnsiEncoding` in node (§8.1)~~ ⟦G0-29⟧ **SETTLED, CONFIRMED** (CHARSET Car 0 probe 1, jspdf 4.2.1 at C′): reachable, 27 keys, `U+20AC → 128`, byte-identical to the dependency's own decoded compressed block; §8.7 R1 retired | none owed; both methods become Car 1's cross-assert |")
F.rep("| E28 | the `custom-charset` mapDeps row stays out of the ENTRY's map (§8.2) — ⟦A5 B5⟧ the row is owned by whichever chunk holds a dynamic import whose transitive STATIC closure reaches `customContentManifest.js`, not by 'the dynamic importer of the leaf' | Car 0 probe 6 (the entry's `__vite__mapDeps` array diffed by filename), then Car 1 proof 6; cure = `import()` at the admission call inside `customContentManifest.js`, never the slice-runtime edge |",
      "| E28 | ~~the `custom-charset` mapDeps row stays out of the ENTRY's map (§8.2)~~ ⟦G0-30⟧ **SETTLED AGAINST the hoped-for reading at the static-graph level (CONFIRMED for the structural half; PLAUSIBLE for the byte cost)** — ⟦A5 B5⟧ was right: five entry-owned dynamic targets have `customContentManifest.js` (fourteen static importers) in their transitive static closure, so with a static edge the ENTRY's array gains the filename; **R2's `import()` cure is Car 1's DEFAULT** | the byte half rides the ONE G5 probe build: Car 1 proof 6 confirms the entry's `__vite__mapDeps` unchanged by filename with the `import()` edge; no separate build owed |")
F.rep("| E30 | CHARSET's four new test files' title/suite counts (≈ 25–35 titles) (§11.1) | Car 0 probe 5 through the walker's own `classify()` |",
      "| E30 | ~~CHARSET's four new test files' title/suite counts (≈ 25–35 titles) (§11.1)~~ ⟦G0-31⟧ **SETTLED for the classification triple (CONFIRMED: `files +4 / parked +1 / credited +3`, ⟦A18 E2⟧'s park proven by execution); PLAUSIBLE and draft-dependent for the counts** — +17 credited titles / +3 suite titles over the volume's own enumerated arms (22 authored; the parked build test's 5 never count); the ≈ 25–35 band read HIGH | Car 1's drafts re-counted through the walker before the refreeze; a count inside 25–35 means the drafts grew, not that E30 was right |")

F.checkpoint(31, '~52')
F.save('batch2 CHARSET')
fold_json(folded=[f'G0-{i}' for i in range(20, 32)],
          chair=['CR-5 S = context-anchored 190 + U+00A0 in bans.invisible (§882.4)',
                 'CR-6 the generated-src provenance ritual priced into every minting car (§882.4)',
                 'CR-7 R2 import() cure is CHARSET Car 1 default (§882.4)'],
          settled14=['E27 (CONFIRMED)', 'E28 (structural half CONFIRMED against; byte half PLAUSIBLE)', 'E30 (triple CONFIRMED; counts draft-dependent)'])
