"""BATCH 5 — the READERREVIEW Car 0 receipt (the fifth and last G0 probe) folded into §5 and §11.4.
Receipt: $SP/laneG0RR-receipt.md. Chair rulings: ODQ §882.8. Marks G0-59 … G0-72.
"""
import foldlib

R = '(READERREVIEW Car 0 receipt, `$SP/laneG0RR-receipt.md`)'
f = foldlib.Folder()

# ── ⟦G0-59⟧ §5.2 — the runner is vite.ssrLoadModule, not npx vite-node ──
f.rep(
    '(`vite-node` because `SettlementPDF.jsx` is JSX; precedent `scripts/audit/simulate-world.mjs`)',
    '''⟦G0-59⟧ **the runner is `vite.createServer({ configFile: false, server: { middlewareMode: true } }).ssrLoadModule(...)`, NOT `npx vite-node` — RATIFIED (§882.8, vetoable).** A JSX transform is genuinely required (plain `node` is the negative control and it convicts: `ERR_UNKNOWN_FILE_EXTENSION: Unknown file extension ".jsx"`, TRUE_EXIT 1), and both instruments render — but **`vite-node` is NOT a dependency of this repo**: `require.resolve` → `MODULE_NOT_FOUND`, 0 hits in `package.json` AND in `package-lock.json`, no global install; `npx --no-install vite-node` resolved `vite-node/6.0.0` **only from this machine's npx cache**, i.e. on CI, a fresh clone or offline it is an UNPINNED NETWORK INSTALL — a false-green habitat of exactly the kind this program hunts — and adding it is not free (⚠ ANY `package.json` BYTE CHANGE is a MINT TRIGGER, §349.2). The in-lock path costs ZERO new dependencies and ZERO `package.json` bytes (`vite@7.3.6` is already a declared devDependency and already in the lock), boots in 18 ms, is the same mechanism (`vite-node` is a thin CLI wrapper over this very API), and its PDFs are **BYTE-IDENTICAL across all four variants** (347,870 / 345,061 / 45,398 / 135,481) ''' + R + ' §2. `SettlementPDF.jsx` is JSX; precedent `scripts/audit/simulate-world.mjs`)',
)

# ── ⟦G0-60⟧ §5.1 — characterDriftEnabled is OUT, by measurement ──
f.rep(
    '`characterDriftEnabled` (read at `characterDrift.js:155` but not in the roster — PLAUSIBLE that a rules overlay reaches it; **Car 0 P0.3 settles it** by one lit month and a grep of the receipt; §13 C23 on the WRWALKER consequence)',
    '`characterDriftEnabled` — ⟦G0-60⟧ **SETTLED AND OUT (RULED §882.8): `PREVIEW_OVERLAY` is the FOUR-key form `{ warMemoryEnabled, espionageEnabled, demographicsEnabled, neutralNeighborsEnabled }`, and §1.1\'s conditional "+ `characterDriftEnabled` iff Car 0 proves the read" resolves to NO.** Black-box: 0 new census paths at one month AND at one year, no `characterDrift` ledger. White-box: `grep -rn characterDriftEnabled src/` returns FIVE hits and **not one is a read** — `characterDrift.js:155` DEFINES `CHARACTER_DRIFT_FLAG_KEY`; `:86` and `:150` are docblocks saying the door is "putting `characterDriftEnabled` into `ENGINE_GATED_VIRTUAL_RULE_KEYS`, which has not happened"; `subsystemRowsLives.js:16-26` says that leaf awaits the flag\'s respelling. **No gate anywhere reads it, so setting it is a no-op that READS AS INTENT** ' + R + ' §6 (recon fact 4 CONFIRMED: it is not in the 29-key virtual roster; §13 C23 on the WRWALKER consequence stands)',
)

# ── ⟦G0-61⟧ §5.1 — the per-key reach table, and the two corrections it forces ──
f.rep(
    "the volume's first frozen list — `warMemoryEnabled` (`concludedWars.js:91`), `espionageEnabled` (5 files read it `=== true`; W-OPS voice in COUPLED), `demographicsEnabled` (`demographicsRates.js:102-105`), `neutralNeighborsEnabled` (the small-N stasis medicine — PLAUSIBLE that a 4-member region wants it; Car 0 measures both ways) — is the PRE-wave overlay",
    '''the volume's first frozen list — `warMemoryEnabled` (`concludedWars.js:91`), `espionageEnabled` (5 files read it `=== true`; W-OPS voice in COUPLED), `demographicsEnabled` (`demographicsRates.js:102-105`), `neutralNeighborsEnabled` (the small-N stasis medicine) — is the PRE-wave overlay, and ⟦G0-61⟧ **Car 0 MEASURED each key's reach, LIT vs DARK on an identical fixture, by two sound detectors** ''' + R + ''' §6:

| key | @ one MONTH | @ one YEAR | the named ledger | verdict |
|---|---|---|---|---|
| `warMemoryEnabled` | **0 new paths — SILENT** | **102 new paths — REACHED** | `$.worldState.concludedWars : object{3}` (lit) / NONE (dark), a complete record with `casusReasons[]`, `concludedTick`, `cost.exhaustionBands` | **REACHED, but never within a month** |
| `demographicsEnabled` | 66 new / 196 gone — REACHED | — | `$.worldState.spatialLedgers.demographicPlans : object{4}` | REACHED |
| `neutralNeighborsEnabled` | 83 new / 3 gone — REACHED | — | ❌ NONE under that name | **REACHED, at a DIFFERENT address** |
| `espionageEnabled` | 0 new — silent | 0 new — silent (5 y and 30 y likewise) | ❌ NONE, ever | **NOT REACHED** |
| `characterDriftEnabled` | 0 new — silent | 0 new — silent | ❌ NONE | **OUT** (⟦G0-60⟧) |

⟦G0-61⟧ ⚠ **A DETECTOR THE CAR MUST NOT USE, recorded because it would have fooled it.** The lane's first pass scored 5/5 REACHED on "the world composite hash moved" — which is **VACUOUS**, because the flag's own value lives at `worldState.simulationRules.<flag>`, INSIDE the hashed object; and the named-ledger search must SKIP `simulationRules` or it finds the switch it just flipped and calls it evidence. Only STRUCTURAL detectors (new census paths) and the named ledger are sound. *(A dormancy claim is a BIT claim, §713.2, wearing a new coat.)*

⟦G0-61⟧ ⛔ **`neutralNeighbourEdges` IS NOT A LEDGER — a Car 1 probe grepping the world for it gets a FALSE NEGATIVE.** It appears NOWHERE in the threaded world; the reach lands in **`regionalGraph.edges`** (grown to `array[7]` with a new `edges[].evidence[]` carrying `{source, reason}`, plus a new `relationshipStates.edge.soak_a.soak_d`). `src/domain/region/neutralNeighbourEdges.js` exports `withNeutralNeighbourEdges(graph, …)`: it is an edge MINTER into the regional graph, not a persisted ledger. **The correct detector is `regionalGraph.edges[].evidence[].source === \'neutral_default\'`** (`NEUTRAL_DEFAULT_EDGE_SOURCE`, `neutralNeighbourEdges.js:124`). ⚠ Note the spelling split: the FLAG is US (`neutralNeighborsEnabled`), the module and this volume's ledger name are UK.

⟦G0-61⟧ ⛔ **`espionageEnabled` DOES NOT REACH, AND THE GATE IS NOT THE PROBLEM — this is the finding that opens an owner row (§19).** (1) The gate is a **THREE-PART CONJUNCTION** (`espionageGate.js:75-82`): `espionageActive` requires `beliefsActive(worldState)` ∧ `rules.errandSpineEnabled === true` ∧ `rules.espionageEnabled === true`, and the header states the lighting ORDER outright ("`espionageEnabled` lights only AFTER `errandSpineEnabled`") — **so `PREVIEW_OVERLAY` as §1.1 spells it is MISSING `errandSpineEnabled` and its espionage member is dead on arrival**. (2) With the whole conjunction lit the gate genuinely OPENS (`beliefsActive: true`, `espionageActive: true` at start AND end). (3) **And the layer still writes NOTHING**: at 5 years the census is 8,807 lit vs 8,807 dark, 0 new paths; at 30 years the worlds diverge (10,293 vs 10,205 paths) but by ordinary chaotic drift — `embattlement`/`tradeOverture` ledgers gained, `campaignPlans` lost, all unrelated. Because ES-3 writes into the SHARED container `spatialLedgers.beliefMaps` as synthetic reports, a name search can never settle it, so the container was counted directly: **`beliefMaps` observers 4 = 4, deep entry count 268 = 268, IDENTICAL over thirty years; zero `espionage|covert|operative|infiltrat` paths on either side.** This is consistent with the estate's own certification row (the ES-Da rider mints a covert mission only inside an accepted-peace dispatch, still UNOBSERVED at C′). **⇒ The LIT-PREVIEW corpus CANNOT make OPERATIONS readable — Q-OPS-1/Q-OPS-2 score `dark_by_flag` on the PREVIEW posture as well as on LAUNCH, defeating the very purpose §5.1 gives the preview corpus. An OWNER ROW, opened not decided (§19); three options are priced in the receipt and none is a lane\'s to pick.** Left PLAUSIBLE and said so: whether espionage would EVER write at a larger realm scale — four horizons (1 month, 1 year, 5 y, 30 y) were falsified at FOUR settlements; settlement count was not varied''',
)

# ── ⟦G0-62⟧ §5.1 / §5.5 — "one lit MONTH per key" is measured insufficient ──
f.rep(
    "P0.2 which eslint rules bind `scripts/**` (the runner must pin `now`, use no `Math.random`)",
    '''P0.2 which eslint rules bind `scripts/**` (the runner must pin `now`, use no `Math.random`) — ⟦G0-62⟧ **SETTLED, and the parenthetical's implicature is REFUTED: eslint does NOT enforce determinism on `scripts/**`.** MEASURED by `npx eslint --print-config scripts/audit/whole-world-soak.mjs` (TRUE_EXIT 0): **88 rules, 87 enabled, the ONE disabled being `no-console`**; `no-restricted-syntax` (the `Math.random` / `new Date()` / `Date.now()` / `import.meta` ban) **ABSENT**; `max-lines` / `max-lines-per-function` / `complexity` **ABSENT**; `no-restricted-globals` / `-properties` / `-imports` **ABSENT**; `no-unused-vars` is a WARN. Only two blocks match (`eslint.config.js:87` and `:820`), and the determinism ban lives at `:299-313` over `src/domain/**` with `determinismBanCoverage.test.js:56-120` enumerating six layers — `src/generators`, `src/domain`, `src/workers`, `src/kernel`, `src/pdf`, `src/lib/instantWorld` — **none of them `scripts/**`**. ⇒ **the runner's `now` pin and its freedom from `Math.random` are enforced by NOTHING at C′ except the corpus manifest's own `--verify` determinism bit**, which is a good instrument but a POST-HOC one. **RULED (§882.8): recorded as a WRWALKER/READERREVIEW HANDOVER row and cured by the `--verify` bit, NOT by widening the ban** — widening `no-restricted-syntax` to `scripts/**` would convict the ~40 existing audit scripts that legitimately read wall-clock for timing. ⚠ A second, unasked fact: both blocks glob `.js`/`.mjs`/`.cjs` and **never `.jsx`**, so a reader renderer written as `scripts/review/*.jsx` would be linted by NO block — every producer needing JSX must be `.mjs` with `React.createElement` ''' + R + ' §1)',
)

# ── ⟦G0-63⟧ §5.1 / §5.5 — the wall-clock is 14–19× over-priced ──
f.rep(
    "**Cost and corpus size (measured figures, PLAUSIBLE arithmetic).** One year of a 4-settlement `full_simulation` world ≈ 27–38 s on this Mac (SOAKCHAIN's on-disk receipts); 30 years ≈ 14–19 min per campaign;",
    "**Cost and corpus size (measured figures, PLAUSIBLE arithmetic).** ⟦G0-63⟧ **RE-PRICED DOWNWARD BY MORE THAN AN ORDER OF MAGNITUDE, MEASURED: one full 30-year 4-settlement campaign costs 61.88 s real (1.02 min; 68.84 user, 2.03 sys), not 14–19 min** — of which the advance loop is 60,997 ms and the fixture build (4 × `generateSettlementPipeline`) 157 ms; peak heap 450,141,384 B (≈ 450 MB), peak RSS 786,923,520 B (≈ 787 MB, `/usr/bin/time -l` agreeing exactly). ⚠ **Per-year cost FALLS** — 2,673 ms (y1) → 1,851 ms (y30), mean 2,033 ms — consistent with the two retention caps bounding the working set; no runaway over 30 years. ⚠ **SCOPE, stated plainly:** this is the ADVANCE + composite hashing only; it excludes document rendering (P0.1 measures that separately at **3.46 s per settlement for all four PDF variants**, `canon_dossier` alone 1.58 s) and the soak's own per-year observation legs, some of which the reader runner will pay. ⇒ **the 11-campaign roster costs ≈ 11 min of advance SERIAL, before rendering and with no parallelism at all**; Car 2's \"> 45 min for one campaign\" STOP is ~44× away from firing, and §11.4's bill and §5.7 R6's parallelism risk are both re-priced here " + R + " §3. The volume's believed figures, for the record: one year of a 4-settlement `full_simulation` world ≈ 27–38 s on this Mac (SOAKCHAIN's on-disk receipts); 30 years ≈ 14–19 min per campaign;",
)
f.rep(
    "P0.4 one full 30-year campaign's wall-clock (expect 14–19 min) and peak heap",
    "P0.4 one full 30-year campaign's wall-clock (expect 14–19 min) and peak heap — ⟦G0-63⟧ **MEASURED 61.88 s / 787 MB RSS**",
)

# ── ⟦G0-64⟧ §5.1 — the control hash composite, pinned, and the equality proof pre-paid ──
f.rep(
    "(PLAUSIBLE that the soak hashes a different object by a field — Car 0 P0.5 names the hashed object; if it differs, a second control hash of the soak's object is added;",
    '''(⟦G0-64⟧ **SETTLED BY EXECUTION AND THE REMEDY IS UNNECESSARY.** The soak hashes `sha256(JSON.stringify({ worldState, regionalGraph, settlements }))` — three keys in that literal order, `settlements` being the THREADED saves' settlements post-`settlementUpdates` merge, never the fixture's originals (`whole-world-soak.mjs:453-457`, `sha` at `:187`); five candidate objects were hashed at year 1 and **only the three-key composite matches** (`2409ea4ec9a9f788ecca243d2ea480909463b0ec859a1bf4a5c9a08347dc8daf`), with `hashedObjectKeys` returning `["worldState","regionalGraph","settlements"]`. `sha(worldState)` ALONE is `da2d4a3c…` and is NOT it. ⭐ **And the equality proof is PRE-PAID: the REAL soak run in the dock at `--years 1` reproduces the control campaign's hash EXACTLY** (`yearlyHashes[0]` `2409ea4e…` both sides; `directFirstResultSha256` `848e7272…` both sides, TRUE_EXIT 0), so Car 1's proof is DISCHARGEABLE and the exact composite it must hash is pinned — hashing `result`, or `worldState` alone, silently produces a different, plausible-looking hash. All 30 yearly hashes were distinct: the world genuinely moves every year ''' + R + ''' §4. The volume's contingency, retired: PLAUSIBLE that the soak hashes a different object by a field — Car 0 P0.5 names the hashed object; if it differs, a second control hash of the soak's object is added;''',
)

# ── ⟦G0-65⟧ §5.1 — the live address-chain figure, and the two defects it conceals ──
f.rep(
    "and `measureAddressChain(rawEntries)` (`behavioral-observation.mjs:775`) — which answers the recon's open question about the live `fullyAddressedRateMilli` per campaign per year.",
    '''and `measureAddressChain(rawEntries)` (`behavioral-observation.mjs:775`) — which answers the recon's open question about the live `fullyAddressedRateMilli` per campaign per year. ⟦G0-65⟧ **ANSWERED, AND THE HEADLINE HIDES A REAL DEFECT** ''' + R + ''' §5: live year 1 on the control campaign reads **`fullyAddressedRateMilli` 958‰ raw** (429 rows) / 950‰ on the 240-row feed — far above the fixture's 700–783 — with `subjectAddressedRateMilli` 993, `typedActionRateMilli` **1000** and `reasonRateMilli` 965. **But `depthHistogram = {0: 3, 1: 426, 2: 0, 3: 0, 4: 0}`: 426 of 429 rows stop at depth 1 — settlement only — and ZERO rows reach depth 2, 3 or 4.** `measureAddressChain` counts depth CONTIGUOUSLY over `ADDRESS_LEVELS` = settlement → power → faction → npc (`:757-762`, `:784-793`) and `fullyAddressed` requires only `depth >= 1 && hasAction && hasSettlements && hasReason` (`:805`) — so **958‰ measures a THREE-part claim ("a settlement, a typed action, a reason"), not the NEWS ADDRESS LAW's four parts: the NAMED ACTOR is absent from every single row.** ⇒ **Car 3's rubric must NOT quote `fullyAddressedRateMilli` as the address-law score; the honest live figure for "the actor is named" is `depthHistogram[2..4] = 0 of 429 = 0‰`.** ⚠ This is a SECOND, independent gap from the recon's predicted Herald gap (`heraldFeed.js:132` → `outcomeSubjectDescriptor` reads singular `npcId`/`factionId` while entries carry plural `npcIds[]`/`factionIds[]`, bridged only at `WizardNewsPanel.jsx:96-99`): `measureAddressChain` never touches `heraldFeed`, so this is the LEDGER ENTRIES themselves failing to carry a contiguous actor chain. Whether the two share one cure is Car 3/Car 4's to establish.''',
)

# ── ⟦G0-66⟧ §5.1 — the retention cap saturates at year 1, not year 30 ──
f.rep(
    '(`wizardNews.MAX_ENTRIES = 240`, `pulseHistory.MAX_HISTORY = 80` — recon fact 7, CONFIRMED (recon))',
    '(`wizardNews.MAX_ENTRIES = 240`, `pulseHistory.MAX_HISTORY = 80` — recon fact 7, CONFIRMED (recon); ⟦G0-66⟧ **MEASURED, AND THE STAKES ARE HIGHER THAN THE DESIGN PRICED: the 240-entry cap is SATURATED AT YEAR 1, not late** — `yearlyNewsRows` measured **240 at every one of the 30 years** while year 1 ALONE minted **429** raw entries, so `MAX_ENTRIES` (`src/domain/region/wizardNews.js:21`) is already truncating in the FIRST year. ⇒ **per-year capture through `onTickObservation` is MANDATORY, not a year-30 nicety (RULED §882.8): a reader who opens the year-30 world and reads `wizardNews.entries` sees at most the last 240 of ~12,900 authored rows — under 2 %, and any Car 2 producer that reads the final feed instead of the per-year capture is silently reading a 2 % sample** ' + R + ' §5)',
)

# ── ⟦G0-67⟧ §5.2 — the lighting bill, one figure measured and four derived ──
f.rep(
    'lighting predicted `files +2, credited +2, parked +0, titles +20, suiteTitles +2`',
    '''lighting predicted `files +2, credited +2, parked +0, titles +20, suiteTitles +2` → ⟦G0-67⟧ **the base at C′ is `files 2495 · parked 370 · credited 2125 · titles 22437 · suiteTitles 6069`, the target is `2497 / 370 / 2127 / 22457 / 6071`, and ONE figure is MEASURED — `files = 2497`, quoted from the walker's own assertion text ("expected 2497 to be 2495") — with the other FOUR DERIVED, not measured** ''' + R + ''' §7.1. The reason is two mechanisms, not laziness: (1) **the walker FAILS FAST** — `sovereigntyLightingContract.walker.test.js:7388-7405` asserts the five figures in sequence with `files` FIRST, so the run throws there and the other four are never evaluated *(the recorded hazard "a contract that throws on the FIRST mismatch under-reports its own drift", met live)*; (2) **the refreeze — the only path that writes all five — REFUSES ON A DIRTY TREE, AND UNTRACKED COUNTS** (`refreezeCensusBaseline()`, `:659-666`, reads `git status --porcelain` and refuses on any remaining path but the register), so P0.7's own premise ("with the two test files present") makes the refreeze impossible by construction; its message says the cure outright: *"Commit first, then refreeze at the clean tip."* ⇒ ⛔ **A SEQUENCING CONSTRAINT §5.5 AND §11.2 DO NOT NAME, now RULED into the car (§882.8): Car 1 must COMMIT its eight files FIRST, then refreeze at the clean tip** (`LIGHTING_CENSUS_REFREEZE='<seat>' LIGHTING_CENSUS_NOTE='<why>' npx vitest run tests/lint/sovereigntyLightingContract.walker.test.js`, which exits NON-ZERO by design), **then re-run the walker plainly — and THAT green is the receipt. Three steps, not one, and the middle one cannot happen before the commit.** The four derived figures are well-founded (both new test files ran green — `Test Files 2 passed (2) · Tests 20 passed (20)`, TRUE_EXIT 0 — and both are plain `describe`/`it` with function expressions, no `.skip`/`.each`/`.todo`/conditional, i.e. exactly the credited shape with no park reason) **but Car 1 MUST MEASURE all five at its clean committed tip and must not transcribe them: the register's own `_doc` forbids a hand-composed figure**''',
)

# ── ⟦G0-68⟧ §5.5 Car 0 — DISCHARGED, all nine probes ──
f.rep(
    '- **Car 0 — THE ZERO-BYTE PROBE** (Fable or Opus; a scratch dock; lands nothing): P0.1',
    '''- ⟦G0-68⟧ **Car 0 IS DISCHARGED at C′ `9a0584f0f`, 2026-09-02 08:35–09:09 ET, CLEAN, NO STOP** ''' + R + ''' — dock `$SP/laneG0RR-tree` porcelain 0, zero commits, no `src`/`tests`/`scripts` file modified, three vitest runs all through the shared mutex with `TRUE_EXIT` captured (no exit 3, no NOT-RUN), no build, `npm run check` never run, nothing killed. ⚠ **The chair's brief enumerated five probes; §5.5 lists EIGHT and §14's E42 assigns a NINTH — the lane ran all nine and said so** (the volume wins over the brief, the standing law). Dispositions: **P0.1 YES** (⟦G0-59⟧ — and the §5.5 fallback is NOT owed) · **P0.2** the eslint gap (⟦G0-62⟧) · **P0.3** the reach table with two corrections and one answered question (⟦G0-60⟧⟦G0-61⟧) · **P0.4** 61.88 s (⟦G0-63⟧) · **P0.5** the composite pinned and the soak equality proven (⟦G0-64⟧) · **P0.6** exactly one new red, the billed one (⟦G0-69⟧) · **P0.7** one figure measured, four derived, and a car constraint (⟦G0-67⟧) · **P0.8** 958‰ with two concealed defects (⟦G0-65⟧⟦G0-66⟧) · **P0.9** all three tabs render (⟦G0-70⟧). Preserved for Car 1: probes at `$SP/laneG0RR-probes/` (10 files), the **eight design skeletons at `$SP/laneG0RR-newfiles/`, ready to `cp` back verbatim**, logs/JSON at `$SP/rr-car0-*`.

- **Car 0 — THE ZERO-BYTE PROBE** (Fable or Opus; a scratch dock; lands nothing) — the act, as chartered: P0.1''',
)

# ── ⟦G0-69⟧ §5.5 — P0.6's red-set diff, and what the base red set actually is ──
f.rep(
    'STOP: none — a probe records.',
    '''STOP: none — a probe records. ⟦G0-69⟧ **P0.6 MEASURED BY TWO FULL `tests/lint` RUNS IN THE DOCK, both `GATE_MUTEX_TIER=shared` with `TRUE_EXIT` captured** ''' + R + ''' §7. **BASE (porcelain 0, the probes moved out first so nothing of the lane is charged to it): `Test Files 3 failed | 129 passed (132) · Tests 5 failed | 1852 passed (1857) · 110.24 s` — and ALL FIVE reds are FROZEN KNOWN FAILURES matched name-for-name against `scripts/.test-ratchet-baseline.json`** (`clampPrimitiveBaseline` · `warCostKindPools` ×3 · `warRulingKindPools`). ⚠ **⇒ C′ is GATE-GREEN on `tests/lint`; a bare `npx vitest run tests/lint` is NOT, because it bypasses the ratchet's frozen-known-failure allowance — a lane reading a bare run as "the base is red" would be wrong, and one reading it as "my change broke four walkers" wronger. THE BASE RED SET IS EXACTLY THOSE FIVE: that is P0.6's denominator.** **WITH THE EIGHT DESIGN FILES PRESENT** (the six `.mjs` at their designed homes plus the two test files; porcelain 4 entries; `scripts/lib/` pre-exists with 13 tracked files including the OSR tools, `scripts/review/` is genuinely new — 0 paths in HEAD): `Test Files 4 failed | 128 passed (132) · Tests 6 failed | 1851 passed (1857) · 122.73 s`. **⭐ EXACTLY ONE NEW RED, and it is the one the design already bills for**: `sovereigntyLightingContract.walker.test.js` › *THE CENSUS IS AN ASSERTION, NOT A SENTENCE*. **No other walker moved — `observedShapeReaders.walker` included** — and `grep -rln 'docs/review' tests/ scripts/` returns NOTHING, so Car 3's `docs/review/` outputs owe no doc-scanner census. ⇒ **§5.2's bill for Cars 0–2 is COMPLETE AS WRITTEN; no unnamed census exists.**''',
)

# ── ⟦G0-70⟧ §5.1 — P0.9: the three tabs render, but not yet as surfaces ──
f.rep(
    'Car 0 gains P0.9 (`renderToStaticMarkup` of the three tabs under `vite-node` with the store stubbed — if it fails, the tabs are declared UNREAD by the protocol and handed to the walk explicitly, never scored `shown` from the dump) — vetoable.',
    '''Car 0 gains P0.9 (`renderToStaticMarkup` of the three tabs — ⟦G0-59⟧ through the in-lock `ssrLoadModule` runner with `resolve.alias` mapping `**/store/index.js` to a stub — if it fails, the tabs are declared UNREAD by the protocol and handed to the walk explicitly, never scored `shown` from the dump) — vetoable. ⟦G0-70⟧ **MEASURED: ALL THREE RENDER (TRUE_EXIT 0), so the tabs are NOT handed to the walk and CAN be SURFACE documents** ''' + R + ''' §8 — Faith (`FaithTab.jsx`, default export a `function`) 347 B `<div data-testid="faith-tab" …>`; War (`WarTab.jsx`, `function`) 372 B `<div data-testid="war-tab" …>`; Power (`PowerTab.jsx`, default export an **`object`**) 88 B. ⚠ **RENDERING IS NOT YET A SURFACE: all three produced their HONEST-ABSENCE shell** ("No power structure data.") because the stub carried a settlement but no live `campaign`/`worldState` — **the MECHANISM is proven; a REAL surface document needs the threaded campaign wired into the stubbed store, which is Car 2's work and is NOT proven here.** Three mechanical notes each of which cost the lane a failed run: (1) **`PowerTab`'s default export is an OBJECT** (a `memo`/`forwardRef` wrapper; it also exports the named `PowerTab`) — a detector written as `typeof x === 'function'` MISSES it and reports NO_COMPONENT_EXPORT; test `$$typeof`. (2) **Do NOT put `react` / `react-dom/server` through `ssrLoadModule`** — they are CJS and SSR-external, and routing them through the transformer throws `ERR_AMBIGUOUS_MODULE_SYNTAX`; import them normally so the probe and the tabs share ONE React instance, which is what makes the render valid. (3) The store alias is the whole harness.''',
)

# ── ⟦G0-71⟧ §5.5 Car 1 / Car 2 — the two proofs the probes pre-pay or re-price ──
f.rep(
    "the control campaign's year-1 hash equal to the soak's (one soak year in the dock);",
    "the control campaign's year-1 hash equal to the soak's (one soak year in the dock) — ⟦G0-71⟧ **PRE-PAID BY CAR 0 AND THE COMPOSITE PINNED (⟦G0-64⟧): Car 1 hashes `{worldState, regionalGraph, settlements}` in that order and reproduces `2409ea4ec9a9…`; the proof is now a re-execution, not a discovery**;",
)
f.rep(
    '> 45 min for one campaign (shrink nothing; record and re-plan parallelism)',
    '> 45 min for one campaign (shrink nothing; record and re-plan parallelism) — ⟦G0-71⟧ **~44× AWAY FROM FIRING: one campaign measures 61.88 s of advance (⟦G0-63⟧), so the `--only` parallel-render machinery Car 2 plans may be unnecessary for the ADVANCE leg; the STOP stands unchanged as a rule**',
)

# ── ⟦G0-72⟧ §5.7 R5 + R6 — retired and re-priced ──
f.rep(
    '| R5 | `vite-node` + the JSX import fail in a script context (fonts, `Font.register`, the worker shim) | low–medium | P0.1; fallback = a vitest-run renderer file (+1 file, three censuses) |',
    "| R5 | ~~`vite-node` + the JSX import fail in a script context~~ ⟦G0-72⟧ **RETIRED BY MEASUREMENT: `renderToBuffer` runs OUTSIDE vitest on all four variants** (`canon_dossier` 347,870 B / **38 pages** against a floor of 12; `draft_brief` 345,061 / 37; `timeline_packet` 45,398 / 4; `campaign_state` 135,481 / 15; 3.46 s for all four; settlement generation 81 ms) **and font re-registration WORKS and was PROVEN NEEDED** — before it the probe read the live sources and they are the browser paths (`Lora → \"/fonts/Lora-Regular.ttf?v=2\"`), exactly the ENOENT trap the test's header documents; emptying the two families' `sources` and re-registering from `public/fonts/` renders clean. **The fallback (+1 file, three censuses) is NOT OWED.** What REPLACES this risk is the supply-chain one, cured in the same breath: the instrument is `vite.ssrLoadModule`, not `npx vite-node` (⟦G0-59⟧) | retired | ⭐ a free determinism receipt fell out: the four variants rendered BYTE-IDENTICALLY from two independent processes under two different module runners — the dossier renderer carries no per-process entropy at this tip |",
)
f.rep(
    '| R6 | cost overrun: 11 campaigns ≈ 3 h serial; a preview twin under lit flags runs slower | medium | parallel `--only`; shrink by deleting rows, NEVER by shortening years (the rubric is 30 years) |',
    '| R6 | cost overrun: 11 campaigns ≈ 3 h serial; a preview twin under lit flags runs slower | ⟦G0-72⟧ **RE-PRICED LOW: the ADVANCE leg is ≈ 11 min serial for the whole roster (11 × 1.02 min), not ≈ 3 h** (⟦G0-63⟧); what remains unmeasured is the RENDER leg and the soak-style per-year observation the runner will also pay | parallel `--only` (now optional for the advance); shrink by deleting rows, NEVER by shortening years (the rubric is 30 years) |',
)

# ── §11.4's two READERREVIEW rows ──
f.rep(
    "| READERREVIEW two tests | `test:ratchet` (`tests/scripts`) | the one-month smoke ≤ 10 s PLAUSIBLE (budget `60_000`); the 525-key round-trip ms | PLAUSIBLE |",
    "| READERREVIEW two tests | `test:ratchet` (`tests/scripts`) | ⟦G0-63⟧ **the one-month determinism smoke MEASURED 0.74 s wall and byte-identical across two fresh processes** (`4b231dfe…` both runs — so the determinism bit executes too), against the ≤ 10 s prediction; the 525-key round-trip ms; both files run green together in 20 tests, TRUE_EXIT 0 | **CONFIRMED with margin (Car 0)** |",
)
f.rep(
    "READERREVIEW's render ≈ 2.5–3.5 h serial / ≈ 45 min on four processes per corpus",
    "⟦G0-63⟧ **READERREVIEW's ADVANCE ≈ 11 min serial for the 11-campaign roster (MEASURED 61.88 s/campaign), plus the render leg (3.46 s per settlement for all four PDF variants) — the volume's ≈ 2.5–3.5 h serial / ≈ 45 min on four processes was priced against a 14–19 min campaign and is re-priced downward by more than an order of magnitude**",
)

# ── ⟦G0-73⟧ §5.6 — the OPERATIONS owner row, opened at its fold point ──
f.rep(
    '**Owner-gated, exactly:** opening the phase and accepting its charter (RR-8);',
    '''⟦G0-73⟧ ⛔ **AN OWNER ROW THIS FOLD OPENS AND DOES NOT DECIDE — RR-10, THE LIT-PREVIEW / OPERATIONS GAP.** Car 0 proved that with the FULL espionage conjunction lit and `espionageActive === true`, the layer writes ZERO records over thirty years in a four-settlement realm (⟦G0-61⟧). So the preview corpus cannot make OPERATIONS readable: Q-OPS-1/Q-OPS-2 score `dark_by_flag` on the PREVIEW posture as well as on LAUNCH, which defeats the purpose §5.1 gives the preview corpus ("so 'correct but invisible' and 'dark by flag' can never be confused"). Three options, none a lane's to pick: **(a)** accept it and let the rubric record OPERATIONS as unreadable-at-launch with this receipt as its evidence; **(b)** widen the preview realm or horizon until an accepted peace occurs (unbounded — 30 years already failed at four settlements); **(c)** the preview corpus SEEDS a covert mission directly, which is a fixture, not a lighting overlay. **At minimum `PREVIEW_OVERLAY` must gain `errandSpineEnabled` or its espionage member is dead on arrival** — that much is a chair act, not an owner one, and is folded (⟦G0-61⟧). The row touches RR-8's charter and the §12 owner rows; it is carried to §19.

**Owner-gated, exactly:** opening the phase and accepting its charter (RR-8);''',
)

f.checkpoint(73, 90)
f.save('batch5 READERREVIEW')
foldlib.fold_json(folded=[f'G0-{n}' for n in range(59, 74)])
