import { readFileSync } from 'node:fs'; import { readdirSync } from 'node:fs'; import path from 'node:path'; import { pathToFileURL } from 'node:url';
const D = '/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/laneB6';
const gen = JSON.parse(readFileSync('generated-lines.json', 'utf8'));
const want = new Set(['DS-DEF-11::WALLED-STRAINED', 'DS-DEF-8::override active (generic framing)', 'DS-GEN-11::the MARGINAL arm: neither verdict returned', 'DS-POW-1::Tolerated', 'DS-ECO-12::INCOME MIX: two or three sources between them', 'DS-DEF-3::First-Survey qualification (the reading is a first look)', 'DS-DEF-2::Internal Security: full legal chain (court AND prison)', 'DS-DEF-6::Logistics & Supply: Granary with road supply', 'DS-DEF-1::readiness ADEQUATE', 'DS-DEF-1::terrain EXPOSED', 'DS-ECO-11::TERRAIN: Plains']);
const gdir = path.join(D, 'src/data/dossierStateProse'); const pools = {};
for (const f of readdirSync(gdir).filter((f) => f.endsWith('.generated.js'))) { const mod = await import(pathToFileURL(path.join(gdir, f)).href); const table = Object.values(mod)[0]; for (const [block, b] of Object.entries(table)) for (const [pool, vs] of Object.entries(b.pools || {})) pools[`${block}::${pool}`] = vs; }
const fill = (t) => t.replace(/\{settlement\}/g, 'Breitturm');
for (const l of gen.lines) { const k = `${l.blockId}::${l.poolKey}`; if (!want.has(k)) continue; const vs = pools[k] || []; const hit = vs.find((v) => fill(v.text) === l.text) || vs.find((v) => l.text.startsWith(fill(v.text).split('{')[0].slice(0, 25)));
  console.log(`\n### ${k} [${l.angle}]  pool size ${vs.length}  sentence-counts ${vs.map((v) => (v.text.match(/[.!?](\s|$)/g) || []).length).join('/')}  openers ${vs.map((v) => v.text.split(/\s+/).slice(0, 2).join(' ')).join(' | ')}`);
  console.log(`TEMPLATE: ${hit ? hit.text : '(no exact match — slot-filled beyond {settlement})'}`); if (hit?.marks?.length) console.log(`MARKS: ${hit.marks.join(',')}`); console.log(`COMPOSED: ${l.text}`); }
