# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**EM-B1f's RE-SEAL DEADLOCKED AND THE CHAIR ROTATED THE CAPSULE:** `implementation:dispatch` refused (`implementation session already exists: EM-B1f`) because `<git-dir>/implementation-sessions/EM-B1f` is immutable evidence keyed by packet id (`implementation-session.mjs:284`, refused at `:358`, immutable by `:79`), while `check:packet`/`resume` refuse the same capsule once its sealed HEAD drifted (`:425`) — no sanctioned door exists in either script or the standard; and `assertTargetPreflight` (`:202-215`) refuses any dirty non-CREATE row, so a fresh seal is possible only on a CLEAN tree (the lane held it clean and did not apply its patch first — the right order). The lane STOPPED rather than force it or land on hand-run checks with no valid seal — accepted and praised. THE CHAIR'S ACT: `mv .git/worktrees/slot-2/implementation-sessions/EM-B1f → EM-B1f.sealed-at-c33446830` (the seal's head verified c33446830 before the move; nothing deleted); the lane re-dispatches at `c127cdfb2` on the clean tree, re-applies its patch AFTER the seal, then batch 4 (check 7's title the named pre-existing red; if the sealed runner's chain stops there, checks 8–12 run individually and say so). **TOOL-22 chartered:** a sanctioned `dispatch --reseal` that archives the prior session under its sealed head — a branch moving under a paused lane is routine, so this recurs. The lane's clean-tree proof: at `c127cdfb2` with none of its edits, `dossierProseManifest` 1/20 red on the one title; after CURE-J commit 1 ALL THREE recorder hashes mismatch (whole-file → code identity) — consistent, the owner-gated re-record the single remaining act. LANE-EM-BUILD and memory fold 112 carry the rule. "
 "**TOOL-13b LANDED ON ITS LANE** (`42331a717`, +112 lines, one file; focused 47/47 — 46 at HEAD, so the arm demonstrably ran; `tests/lint` whole 2791/2792, the lighting red alone; voiceMechanics 30; eslint bare 0; the plain scanner `1964 finding(s), exactly matching the frozen inventory`; inventory hash `dbd67ac5…` unchanged; the pre-commit hook rewrote nothing — the committed blob's sha256 equals the gated bytes). LIGHTING: `titles` +1 executed (`expected 25075 to be 25074`); ⚠ `suiteTitles` NEVER EVALUATED (the walker asserts the five in order and threw at `titles`) — PLAUSIBLE unchanged, and the next refreeze MEASURES it rather than carrying 6684. The M1–M3 fold recorded in its receipt §1.1 for TOOL-13a's compile. "
 "**FIX-D9 PAUSED WITH THE DISPOSITION WRITTEN, NOTHING DELETED:** all four modules have EXACTLY ONE importer each and every one is a TEST FILE (5,297 files scanned by resolved path — static, dynamic, `require`, `vi.mock`); none reachable from any of the seven build entries (`src/utils/pdfRender.worker.js` is NOT under `src/workers/` — a census that assumes it is misses it); **248 of 2,247 `src/` modules are reachable from NO entry**. TWO FINDINGS THAT CHANGE THE PICTURE: (a) THE DARK TRIO CHARGES FIRST PAINT — `ENGINE_SHARED_DOMAIN` is seeded by walking every file under `src/generators/`, not the reachable graph, and `computeEagerModuleGraph()` seeds from ESD, so 'is it eager?' answers yes BY CONSTRUCTION; both derivations re-run with the trio skipped: ESD 51 → 49, EAGER 268 → 266; `titularSuccession.js` alone holds `factionLifecycle.js` and `cohesionWeave.js` in the eager set (35,400 B of source; the emitted figure needs a build) → **FIX-B3 chartered** (FIX-B2's family, after B2: ESD seeded from the reachable graph; measured with a build); (b) `foldTradeCategories.js` was SUPERSEDED, not abandoned (`d855b58fc8` created it with its importer; `c1ea091f7a` replaced the call with `projectOwnedCustomTradeDirection`, the old input now `legacySatisfies`; its test asserts a dead copy; its `ENGINE_SHARED_DOMAIN_EXCISIONS` row is 1 of 18 that deletes nothing — TOOL-12's item 8 resolved: unreachable, not co-located). DISPOSITIONS: three DARK-BY-DESIGN (Register VII's un-wired half behind `REGISTER_VII_SIGNATURE = {signed:false, live:false}`; `planSeatAscension` returns `declined('dormant_law')` under the shipped dial), one RETIRE-PROPOSED; the mutation row at `:253` byte-identical (true on measurement). THE CHAIR RULED (vetoable): (1) the packet slot is 'Register VII's wiring car — chartered the day the owner signs `REGISTER_VII_SIGNATURE`; until then DELIBERATE-DARK by the owner's unsigned register' (`EDIT-MODE-TRAIN` records EM-P1 withdrawn and the wrong mint site closed; TE-DENSITY-1 has a name and no charter); (2) ONE walker MINTED — `tests/lint/deadCodeDisposition.walker.test.js` (parses the doc's own table; pins each `// dark-until:` header and each module's zero production importers; counterforce both ways; its mutation row; `tests/lint` whole in the gate); (3) RETIRE-PROPOSED stands → **§934.70 ASKED with the table (recommend: keep the trio dark until Register VII is signed; retire `foldTradeCategories.js` and its test)**. Also: **TOOL-23 chartered** (the reachability census of the 248 unreachable modules, measure-first, FIX-D9's scanner reused); the single-test-file plant weakness → TOOL-6b's family note; `scripts/` citations are gate-wired with NO baseline (`writer-dark-register.mjs` cites `titularSuccession.js:29` twice — the lane placed its header below line 29 so the address stays true). "
 "**FIX-P5 FIVE COMMITS ON ITS LANE** (`e207d0718`, `881c84863`, `5c29fef92`, `a5575107a`, `ec7d8a363`; `tests/ui` whole 1076/1076; the dossier suites 52/52; eslint 0): the badge-capitals law held at ZERO exemptions — the review named three shouted-caps sites, the census found thirteen more, all cured; the three-letter legend codes (`REQ`, `YOU`, `WORLD`, `FORCED`) sit below the four-letter bar because each is glossed on the same screen, executed as a control both ways — ACCEPTED. **THE GATE:** TOOL-13b done → FIX-C2b handed the gate (its four commits; `tests/lint` whole); shared tier = FIX-P5 (final instruments) · EM-B1f (batch 4) · FIX-C2b; queue = FIX-B2 (exclusive, alone) → FIX-D9 (after its walker) → then the older paused lanes. WORKING: FIX-D9 (the walker) · FIX-T2 · TOOL-18 · TOOL-19 (dispatched at c127cdfb2).")
line = ("- **§934.47 addendum 87 — EM-B1f's RE-SEAL DEADLOCKED (an immutable session capsule with no re-seal door) → THE CHAIR ROTATED IT ASIDE, TOOL-22 CHARTERED; TOOL-13b LANDED ON ITS LANE (`42331a717`; `suiteTitles` never evaluated — the next refreeze measures it); FIX-D9 PAUSED: ALL FOUR MODULES TEST-ONLY, THE DARK TRIO CHARGES FIRST PAINT BY CONSTRUCTION (FIX-B3 chartered), 248 `src/` MODULES UNREACHABLE (TOOL-23 chartered), ONE WALKER MINTED, **§934.70 ASKED**; FIX-P5 FIVE COMMITS; FIX-C2b HOLDS THE GATE; TOOL-19 DISPATCHED (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 86 —"; assert u.count(key) == 1 and "addendum 87 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 87" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the re-seal deadlock; TOOL-22; FIX-D9's rulings; FIX-B3, TOOL-23 chartered (ODQ §934.47 addendum 87)\n\n"
      "- **TOOL-22 (NEW; a seat when one frees):** `implementation:dispatch --reseal` — archives the prior session capsule under `<ID>.sealed-at-<head>` and seals afresh on a clean tree; until it lands the chair rotates the capsule by hand (LANE-EM-BUILD's rule).\n"
      "- **FIX-D9:** dispositions written, nothing deleted; the packet slot for the dark trio is Register VII's wiring car (chartered when the owner signs `REGISTER_VII_SIGNATURE`); `tests/lint/deadCodeDisposition.walker.test.js` minted; §934.70 asks keep-dark vs retire with the table.\n"
      "- **FIX-B3 (NEW; FIX-B2's family, after B2 lands):** `ENGINE_SHARED_DOMAIN` seeded from the REACHABLE graph, not every file under `src/generators/` (the dark trio charges first paint by construction: ESD 51 → 49, EAGER 268 → 266 without it); measured with a build; the first-paint budget's honest headroom re-measured.\n"
      "- **TOOL-23 (NEW; measure-first):** the reachability census — 248 of 2,247 `src/` modules reachable from no build entry; FIX-D9's resolved-path scanner reused; the seven entries enumerated (including `src/utils/pdfRender.worker.js`).\n"
      "- **The next lighting refreeze MEASURES `suiteTitles`** (the walker asserts its five figures in order and stops at the first miss; two lanes today could not evaluate it).\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 87:", io.open(ODQ, encoding="utf-8").read().count("addendum 87 —"), "| charter amended")
