# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**THE OWNER ASKED (12:4x): 'So what is left to build and what is left to land?' — ANSWERED FROM THE REGISTER AND THE LANE BRANCHES (recorded here so the answer is a fact, not a memory):** LANDED on the branch, not deployed — ELEVEN EM packets (`EM-B3a`, `EM-B3b`, `EM-P3`, `EM-P0`, `EM-B1d`, `EM-B1e`, `EM-B3c`, `EM-B1k`, `EM-B1k2`, `EM-P2`, `EM-B1f`; the register holds 13 EM entries: 11 LANDED, 1 SUPERSEDED, 1 READY) plus twenty-one composed fix/tool commits and seven refreezes. BUILT AND PROVED, LEFT TO LAND (composing after EM-R0a lands, then the eighth refreeze and RUN 23): EM-R0a (building under seal); CURE-K; CURE-J's re-record (3); FIX-B2 (3); FIX-T2 (in its gate); FIX-D9 (3, staged); FIX-P1c (building); TOOL-19, TOOL-15, TOOL-22, TOOL-24 (staged; gates queued); the older paused lanes with staged work (FIX-K1, TOOL-7a, TOOL-9, TOOL-8a, FIX-P2, FIX-D7, FIX-T1, FIX-D8) and the four dead-agent lanes (FIX-G, TOOL-2b, FIX-F2b, TOOL-3; `RESUME-PARALLEL.md`); then THE PUSH (the owner's word), the owner's redeploy and migrations 201–203. LEFT TO BUILD — the editor train: EM-R0a → R0d → R0b → R0f → R0c (compiled, in the kit, placed in that order as each lands) → R1–R5, R6 (compiled), R7; the T6 family B1h, B1i (compiled), B1j (compiled; waits for FIX-T1) with B1j′ / B1j″ / B1l, A2b, B1a; then the editor's later waves (EM-B2a the layer's writer, EM-C1 the registry, the tick hook, the surfaces) — roughly twenty members against the eleven landed; after the editor, the simulation architecture programme (the owner's 09-19 order). LEFT TO BUILD — fix/tool lanes with briefs: FIX-P4b, COMPILE-TOOL-13a, FIX-C2c DISPATCHED this sitting at 578272a99 (the three free seats); waiting for seats: FIX-P9, FIX-P10, FIX-B3 (after B2 composes), FIX-L3, TOOL-15b, TOOL-16, TOOL-17 (after B2), TOOL-20, TOOL-21, TOOL-23, TOOL-25; chartered without briefs: FIX-D6, FIX-W1 (signed), FIX-P6/P7/P8, TOOL-6b, TOOL-10, TOOL-11, TOOL-14, FIX-F4, FIX-F5, FIX-G3, TOOL-7b, TOOL-7c, TOOL-8b, REVIEW-P2, EM-B1j′/B1j″/B1l's compiles, and three chair docs acts (DOC-1 the phantom prose-ceiling authority, DOC-2, DOC-3). "
 "**EM-R0a's BUILD, EVERY COUNT LINE SO FAR:** batch 1 the clean-tree red at 680eacb8d (1 failed | 19 passed — the provenance title, before any byte of its own); red-first `Cannot find module '../../src/domain/edit/recordRegister.js'`; the walker 7/7; sealed check 1 (four files) 41/41; byte + citation pins 34/34; `decreeRegistryPersistence` 5/5 and `editTravel` 3/3 (the two comment-only rows); voiceMechanics 30; eslint bare 0; `typecheck:ratchet` 167/167; `domain-strict` 1113/1113; NINE §P6 MUTANTS each a nonzero exit under its OWN title (A1×2, A3×2, A4, A5, A6, A7×2), each restored to `f0d6440e…70e3`; the register exports all twelve symbols frozen with the exact declared counts (47 classes · 41 generated · 48 keyed · 15 atomic · 2 totals · 9 unproven · 3 unmergeable · 7 groups); the leaf has ZERO importers and no `src/generators` module reaches it (§5.5's placement rule and the 0 B budget hold); 139 effective lines against ≤ 210. ⛔ **THE NUL CLASS STRUCK A THIRD TIME AND WAS CURED STRUCTURALLY:** the lane's first walker spelled a composite-key separator as a RAW NUL BYTE (the Write tool turned a `\\u0000` escape into the literal byte; `file` reported the source as `data`, `grep` went silent) — and `tests/lint/controlBytes.test.js` EXISTS and would have reddened the directory-whole run, so FIX-P1b's 'no instrument catches it' was true only for the roots that test does not walk (`src/lib/anonForkSalt.js`, a commit message); the cure is not an escape spelling: the composite identity is `JSON.stringify(key.map(...))`, no separator, cannot re-acquire the byte; the lane STOPPED its first directory-whole run rather than grade stale bytes and RE-RAN the whole nine-mutant sweep on the bytes that land → **TOOL-25's brief corrected at dispatch**: read `controlBytes.test.js` whole first, measure its scope, EXTEND its roots to every tracked text file (never a second walker), the `--numstat` arm as a sibling. Its directory-whole run is in flight beside three other shared holders; the walker, the census regeneration, the goldens, `check:packet`, `implementation:resume` and the commit follow. "
 "**COMPOSE-REPROOF-1, TEN DIRECTORIES DOWN — nine green, one carrying only the expected red:** `tests/lint` 175/2818 · `tests/components` 297/2103 · `tests/copy` 13/155 · `tests/lib` 174/1797 · `tests/property` 89+1 / 674+1 (the provenance title; proved INHERITED — the diff over the arm, its three recorder files and the golden across `fb39b1ad6..578272a99` is EMPTY; all three recorder hashes now mismatch, as CURE-J's identity change predicts, and the lane checked before asserting a defect that this is the declared owner gate, not a dropped thread) · `tests/ui` 162/1076 · `tests/pdf` 46/458 (FIX-P5's F14 edited `src/pdf/lib/viewModel.js`; this directory covers it) · `tests/data` 24/311 · `tests/config` 8/137 · `tests/design` 17/228; `tests/store` (149 files) running; generators, scripts, build, map, security, `domain/autonomy` and `tests/domain` whole (986 files) remain.")
line = ("- **§934.47 addendum 100 — THE OWNER'S QUESTION 'WHAT IS LEFT TO BUILD AND TO LAND' ANSWERED FROM THE REGISTER (11 EM landed · ~20 EM members remain · the composed and staged lane work enumerated · the briefs staged); EM-R0a's BUILD GREEN THROUGH NINE MUTANTS WITH THE NUL CLASS STRUCK A THIRD TIME AND CURED STRUCTURALLY (`controlBytes.test.js` exists — TOOL-25 extends it); THE RE-PROOF TEN DIRECTORIES CLEAN; FIX-P4b, COMPILE-TOOL-13a, FIX-C2c DISPATCHED (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 99 —"; assert u.count(key) == 1 and "addendum 100 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 100" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the roster of what is left (ODQ §934.47 addendum 100)\n\n"
      "- **Landed:** EM-B3a, B3b, P3, P0, B1d, B1e, B3c, B1k, B1k2, P2, B1f (eleven). **Building:** EM-R0a. **Compiled and waiting (place in order as each lands):** EM-R0d → R0b → R0f → R0c; EM-B1h, B1i, B1j (after FIX-T1), A2b, B1a; EM-R6. **To compile:** EM-R1–R5, R7; B1j′, B1j″, B1l; the later waves (EM-B2a, EM-C1, the tick hook, the surfaces).\n"
      "- **Fix/tool lanes:** dispatched — FIX-P4b, COMPILE-TOOL-13a, FIX-C2c; staged with briefs — FIX-P9, FIX-P10, FIX-B3, FIX-L3, TOOL-15b, TOOL-16, TOOL-17, TOOL-20, TOOL-21, TOOL-23, TOOL-25 (corrected: extend `controlBytes.test.js`); chartered without briefs — FIX-D6, FIX-W1, FIX-P6/P7/P8, TOOL-6b/10/11/14, FIX-F4/F5/G3, TOOL-7b/7c/8b, REVIEW-P2, DOC-1/2/3.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 100:", io.open(ODQ, encoding="utf-8").read().count("addendum 100 —"), "| charter amended")
