# -*- coding: utf-8 -*-
"""ODQ §934.47 addendum 106 + the charter amendment: the rulings and slots of the 13:1x–13:4x sitting (recorded the same turn they were made).
argv: stamp. Run in the ledger checkout after `git show HEAD:<path> > <path>`. Control characters are spelled in words on purpose."""
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
NUL = "backslash-u-0000"
body = ("**THE SITTING'S RULINGS, EACH VETOABLE, EACH WITH ITS SLOT.** "
 "(A) **FIX-C2d CHARTERED** (brief `briefs/launch/FIX-C2d.md`): FIX-C2c's 209 remaining ARM 3 document leads over 45 documents (roster `ARM3-REMAINING-ROSTER.txt`; top GEOPOLITICAL_WAR_LAYER 18 · DESIGN_FP_ARCH_GR 16 · FABLE_VALIDATION_QUEUE 13) are a lane of their own, never a deferral — under two rulings: **R1 READ-THEN-CURE** (the sampled lead-invalidity is 5% and the symbol-attribution error 20%, so curing blind writes ~10 wrong addresses over correct ones; every cured row quotes the live line; a refused row is classified UNRESOLVABLE / MISPATHED / AMBIGUOUS) and **R2 THE RECORD-CLASS IS ANNOTATED, NEVER RE-ADDRESSED** (a survey refutation, an audit PASS row, a plan range naming a catalog are records of a past measurement; re-addressing falsifies them — an inline `(as of <sha>)` mark the walker honours, plus a `records` roster by path, the same mechanism as the LANDED-packet rule; FIX-C2c's four named rows are the first marks). Rejected: curing the 209 inside FIX-C2c's gate (a lane at the gate widens nothing) and deleting record rows (a landed record is annotated, never rewritten). "
 "(B) **FIX-B2b — a fourth commit assigned to FIX-D9's lane at its composition:** FIX-D9's walk of every commit between its base and the slot tip found FIX-B2's three composed commits moved `vite.config.js`'s `testTimeout` 912 → 1040 → 1110 → 1138 while two citers still say `:912` (`tests/lint/siteCoherenceRatchet.test.js:69`, `tests/scripts/implementationSession.test.js:187`) — stale by 226 lines and INVISIBLE: the symbol arm of `sourceCitationIntegrity` is report-only (`codeSym 3 → 5`), the EOF arm cannot see it, three composed commits and their gates were green over it. The two are re-addressed line-neutrally by D9's lane after quoting the live line; `tests/scripts` whole is owed because a file there is edited. A THIRD instance of a different vintage (`tests/data/dossierStateProseProjection.contract.test.js:1509` → `vite.config.js:877-878`, imprecise BEFORE FIX-B2) goes to **TOOL-15b** (brief amended: the symbol arm stops being report-only for CODE_TREES against a zero baseline; a citation into `vite.config.js` may name the rule's symbol or a `@consumed-by` marker instead of a line; the arm accepts either). Law written: ASSIGNED SCOPE IS NOT SCOPE CREEP — a lane widens nothing on its own (D9 was right to refuse); the chair assigns. "
 "(C) **TOOL-25's four rulings:** hold the commit for DOC-4 and cherry-pick it, so the walker lands with an EMPTY exemption register (born empty, ceiling 0; its ratchet and 'must name a ruled act' guard exercised by injection — three synthetic rows, all exact); the numstat arm ASSERTS zero (a print-only arm rots); `scripts/hazard-registry.json`'s HZ-NUL row is the lane's — instances 7 → 10 with the counting basis stated (seven through 09-19; three on 09-20 all through TOOLING: FIX-P1b's source file, EM-R0a's walker, TOOL-25's own four escapes; the commit-message strike named and not counted), the 'it caught all 7' claim withdrawn by execution, the tool-parameter vector added as a third trigger; the two scratch carriers cured (4 → 0 each). Rejected: landing with a dated exemption row its own remover deletes a commit later. "
 "(D) **FIX-P9's four rulings:** commit 2's premise REFUTED by measurement and accepted — the register row naming raw `galleryUtils.TIER_OPTIONS` (never rendered) was false when written and is deleted, its handover replaced by EXECUTED pins (the census source pin + a rendered arm in the existing `galleryFilterParity.test.jsx`; no new file, no src change); the Compendium tier id pinned to the token (`tier-${t.id}`) ACCEPTED as a repair that PRESERVES the live public URL `/compendium/tier-thorp` (byte-identical on all six rungs; three executed pins; an owner-gated URL change avoided, not made); the observed-shape register is NOT re-frozen by the lane — its gate may show exactly one named red (`observedShapeReaders.walker` naming the regenerated compendium artifact; `detectorSources: []` before and after, an absorbable input) and THE CHAIR ABSORBS IT at the composition with the plain `--write` on the composed tip (the bundle door if the plain one goes dark), gated on the walker green after; the `†` → `✓` follow-the-product cut ACCEPTED (the shipped mark is `FEATURE_MARK = '✓'`). The Compendium cure itself is through its generator (`generate-compendium-data.mjs` reads `config/tierFacts.js` `SIZE_LABEL`; the artifact diff exactly one line, `\"label\":\"Thorp\"` → `\"Thorpe\"`). "
 "(E) **TOOL-19: no veto** on its two-commit shape with commit 1's subject saying RED until the cure lands in the next commit — the composition law forbids composing a lane's commits singly, and the subject makes the trap visible; its B0 red-first `Tests 1 failed | 124 passed (125)` / B1 `125 passed (125)`; the five counterforces re-measured against the restored cure; its lighting prediction (titles 25077 against the frozen 25074 — +1 its own, +2 CURE-J's at its base, suiteTitles never reached) landed exactly where predicted. "
 "(F) **FOUR LANE LAWS appended to `LANE-PARALLEL.md`:** a PIPELINE MASKS A GATE'S EXIT CODE (`cmd | tail` reports tail's status — redirect to a file, or read `$pipestatus[1]`; TOOL-25 caught a fail-closed registry gate reading exit 0 only because the output said 'failing closed'); DETECTION IS NOT A CONTRACT, DECLARATION IS (git detected all 25 `.glb` binary while `.gitattributes` declared nothing — the census denominator was dirty; declare exhibit classes; a text file reading as binary is a defect, never an allow row); A LANDED RECORD IS ANNOTATED, NEVER REWRITTEN and a citation inside one is HISTORICAL; ASSIGNED SCOPE IS NOT SCOPE CREEP. "
 "(G) **THE CHAIR'S OWN NUL:** the harness refused the first addendum-105 commit command for 'control characters' — a " + NUL + " escape typed into a tool parameter had become the byte; three such bytes were then found in memory fold 112 (planted by earlier tool edits) and replaced with words; the rule everywhere now: control characters are SPELLED IN WORDS in any text a tool writes, and a test literal is built with `String.fromCharCode(0)` at runtime. "
 "(H) **DISPATCHED at `5dd5e8e68`:** FIX-P10 (the phone-floor leftovers) and TOOL-23 (the reachability census, read-only); FIX-D9's three (`dbf3d09fe` · `3a5618ed8` · `47197c30a`; its gate green — `tests/lint` 1 failed / 2800 passed the lighting walker only, `tests/build` 419 / 119 skipped, `tests/domain` 16642; its census delta 1172 → 1171 priced by the `--dry` door; its wiring-census second red convicted as its own deletion and cured) compose BY THEIR LANE in the slot (the census line conflicts with R0a's 1173 — the composed value is 1172, REGENERATED never hand-set; `vite.config.js` measured to apply clean). "
 "(I) **MEMORY:** the index crossed 17,000 bytes and was FOLDED (FOLD 116: the 09-19 edit-mode design row and the 09-20 base-value row, verbatim into an archive), now 16,358 bytes; fold 112 carries the tooling mechanism. "
 "THE SLOT'S ORDER (P1c's `tests/lint` whole is the last run before it frees): DOC-4 (the chair; script `doc4_em_p2_nul.py`) → TOOL-25 cherry-picks DOC-4 and gates → FIX-D9's four by its lane → TOOL-19's two → FIX-C2c's three → FIX-P9's three (+ the chair's OSR absorb) → TOOL-25's → the EIGHTH REFREEZE (whole; attributed) → RUN 23 in the consist → EM-R0d v4 PLACED (window 578272a99..tip measured CLEAN over its 14 paths at 5dd5e8e68, a positive control on `vite.config.js` proving the command sees changes; the worker ceiling at the placement tip is ZERO-SLACK — `generation.worker-*.js` measured exactly 1,401,208 B in the consist's landing build at 26f22d394, pre-B2 — so the packet's ≤ 3,314 B growth row is re-measured from RUN 23's post-B2 dist before dispatch) → its sealed build.")
line = ("- **§934.47 addendum 106 — THE 13:1x–13:4x SITTING'S RULINGS AND SLOTS: FIX-C2d CHARTERED under R1 read-then-cure and R2 the record-class annotated never re-addressed; FIX-B2b assigned to FIX-D9's lane (FIX-B2 moved `testTimeout` 912 → 1138 and two citers rode stale through three green gates — the report-only symbol arm; a third instance of an older vintage to TOOL-15b); TOOL-25's four rulings (an EMPTY exemption register; the numstat arm asserts; HZ-NUL 7 → 10 through tooling); FIX-P9's four (a false register row deleted for executed pins; the Compendium URL preserved by an id pin; the OSR absorb is the chair's; `†` → `✓`); TOOL-19 no veto; four lane laws; the chair's own NUL parameter; FIX-P10 + TOOL-23 dispatched; FOLD 116 (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 105 —"; assert u.count(key) == 1 and "addendum 106 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 106" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the sitting's rulings and slots (ODQ §934.47 addendum 106)\n\n"
      "- **New slots, each with a brief in the kit:** FIX-C2d (the 209 document leads; R1 read-then-cure, R2 the record-class annotated) · FIX-B2b (a fourth commit by FIX-D9's lane at its composition: the two `:912` citers) · TOOL-15b amended (the asserted symbol arm for CODE_TREES against a zero baseline; the third, older instance is its cure; symbol- or marker-addressing into `vite.config.js` accepted).\n"
      "- **Rulings that bind lanes now:** the exemption register of the control-bytes walker is born EMPTY; a lane never re-freezes the observed-shape register (the chair absorbs an input change at the composition); a landed record is annotated, never rewritten, and a citation inside one is historical; assigned scope is not scope creep; a pipeline masks a gate's exit code; detection is not a contract, declaration is; control characters are spelled in words in any tool-written text.\n"
      "- **The slot's order stands as addendum 106 lists it**, ending in the eighth refreeze, RUN 23, and EM-R0d v4's placement with the worker ceiling re-measured from RUN 23's post-B2 dist.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 106:", io.open(ODQ, encoding="utf-8").read().count("addendum 106 —"), "| charter amended | no NUL")
