# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**FIX-T2 COMPLETE on `fix-ratchet-comments-2026-09-20`** (`f2e2e54fa` the target cure; `6d7a73a12` the sweep; tree clean; 0 files under `src/`; goldens byte-identical): every count line in order — `significanceMigration.census` UNEDITED at base 12/12 and cured 12/12 (the 'second live instance' withdrawn by execution as well as by reading; the cure landed as hygiene, as ruled); counterforce (a) the pre-cure ratchet with a planted comment `1 failed | 1 passed` ('a NEW silent Suspense boundary appeared (39 > 38)'); (a2) the lane's OWN defect caught by the red-first cycle (`codeOnly is not defined` — the fourth guard-the-guard arm called a helper it had not imported; one line fixed it; kept on the record); (b) the cured ratchet with the SAME plant present 6/6 (`HomeHero.jsx` hashed identical before and after); `tests/lint` WHOLE 2794/2795 (the lighting red alone); eslint 6 files 0; `PricingTierCards.jsx` lints clean WITHOUT its exemption — the row does not return, the budget is 36; `tests/copy` 151/151; the five cured detectors on the committed tree 24/24. LIGHTING, a correction to the chair's expectation: the walker evaluated `expected 25078 to be 25074` with files/parked/credited PASSING before it, so the base's own distance was ZERO and the red is entirely the lane's — delta +0 · +0 · +0 · +4 titles · +1 suite, all from `loadingNarrationRatchet.test.js`; never refrozen. THE SWEEP LEDGER: 7 in the class, 5 cured (2 live: loadingNarration pins 32 → 29 / 38 → 37; rawButton 39 raw / 36 code, budget 39 → 36, one stale baseline row struck; errorCopy and forkedColor at budget 0 — free habitat removal; the significance census — hygiene), 2 left (clamp / slugify baselines: they strip, with a string-blind pair); by design: `negativeAssertionAnchor.walker` (markers), `sizeBaseline` (eslint's `skipComments`). TOOL-20's input: 51 local strippers, 27 string-blind, 11 of those trailing-blind (`^\\s*//` never removes an end-of-line comment — FIX-P3's shape). ITS ITEMS FATED: `tests/design/deepCraftKillList.test.js` (the precedent for the overturned rule; still reads raw lines against `CEILINGS`) and `tests/helpers/sourceContract.js:245` (brace-counts raw source) → TOOL-20's routing (the same cure, one import each); the `significanceMigration` shared `/g` regex passed to `tally()` where its neighbour uses a factory → TOOL-20 makes it one idiom; the reciprocal cross-reference in CURE-J's header → TOOL-20's first act (already); the three citation drifts its report-only arms printed (`roadsParticipation.test.js:415` — proved TRUE by FIX-C2b, an ARM 3 false positive; `dossierMountRegistry.walker.test.js:1287`; `scripts/wiring-census.mjs:349` — the known false-positive class) and an 18-row `[A3s]` comparand disagreement, none the lane's → FIX-C2c's inputs (sent). "
 "**FIX-B2 CLOSED CLEAN** (no gate slot held; its three commits wait for the composition; `tests/lint` untouched by the lane; the census register exactly as its base left it). **COMPOSE-REPROOF-1 ELEVEN DIRECTORIES DOWN:** + `tests/store` 149/1232 clean (a whole-directory superset of P3's 14, P1b's 6, P4's 6); `tests/generators` (113 files) running. **THE GATE:** FIX-T2 done → **FIX-D9 handed the gate** (`tests/lint`, `tests/build`, `tests/domain` whole; the three-way counterforce); shared tier = EM-R0a · the re-proof · FIX-D9 · FIX-P1c; queue = TOOL-19 → TOOL-15 → TOOL-22 → TOOL-24 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents; working = FIX-P4b · COMPILE-TOOL-13a · FIX-C2c.")
line = ("- **§934.47 addendum 101 — FIX-T2 COMPLETE (two commits; the census green unedited — its red-at-base claim withdrawn by execution; the counterforce twice over, one of them the lane's own caught defect; the lighting red entirely its own +4/+1; the sweep 7 / 5 cured / 2 left; TOOL-20's input 51 / 27 / 11); FIX-B2 CLOSED CLEAN; THE RE-PROOF ELEVEN CLEAN; FIX-D9 HANDED THE GATE (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 100 —"; assert u.count(key) == 1 and "addendum 101 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 101" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — FIX-T2 complete; TOOL-20 and FIX-C2c gain inputs (ODQ §934.47 addendum 101)\n\n"
      "- **FIX-T2** (`f2e2e54fa`, `6d7a73a12`) composes after FIX-B2 at the second composition.\n"
      "- **TOOL-20 gains:** `tests/design/deepCraftKillList.test.js` (raw lines against `CEILINGS`) and `tests/helpers/sourceContract.js:245` (raw brace counting) routed to `commentsOnly`; the `significanceMigration` `/g` regex made one idiom with its neighbour's factory.\n"
      "- **FIX-C2c gains as inputs:** the three citation drifts `tests/lint` whole's report-only arms print at the composed tip (`roadsParticipation.test.js:415` — a proved ARM 3 false positive; `dossierMountRegistry.walker.test.js:1287`; `scripts/wiring-census.mjs:349`) and the 18-row `[A3s]` comparand disagreement.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 101:", io.open(ODQ, encoding="utf-8").read().count("addendum 101 —"), "| charter amended")
