# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 108 — THE ACCOUNT-SWITCH HANDOFF (the owner, " + stamp + ": 'in about five minutes I'm going to switch accounts'): the sitting is CUT MID-COMPOSITION and every live thread is written to the kit's RESUME-NOTE top block (the ⛔⛔⛔ ACCOUNT-SWITCH HANDOFF block, sealed `refs/preserve/chair-kit-923472dc-2026-09-19`) — that block is the authority for the successor (2026-09-20 " + stamp + " EDT; the chair; vetoable).** "
 "THE STATE AT THE CUT: the slot `fixes-2026-09-18-consist` at `48450e98c` (DOC-4 `532ba71cc` + FIX-D9's four composed by its lane), tree clean; FIX-D9 mid-proof there — `tests/lint` whole printed THREE red walkers: the lighting walker (expected), `observedShapeReaders` on `src/lib/anonForkSalt.js` (FIX-P1c's; its cure on FIX-P1's branch, OSR check exit 0 there, the three whole-directory gates running at the cut), and `sourceCitationIntegrity`'s ARCHIVAL-EXCLUSION arm — UNATTRIBUTED (present since 5dd5e8e68's composed-tip run; the chair launched that walker alone in the consist at 6290f7a16, log `sci-walker-6290f7a16.log` in the chair scratchpad — the successor reads it or re-runs the file; the candidates: CURE-J's new shift record under `docs/shift-records/`, EM-R0a's new walker file, FIX-T2's baseline — measured, not guessed, before any cure; the cure is a lane's, in `tests/lint`). SIX CHAIR PICKS dry-composed CLEAN onto 48450e98c in a throwaway worktree (equal file sets, byte-equal blobs; zero NUL bytes across src/tests/scripts/docs after): TOOL-19 `a7da09382` `928f2b86d` · FIX-C2c `808837904` `1f3029ffc` `2b03bc421` · TOOL-25 `f1367909a` (TOOL-25 CLOSED GREEN: the tree-wide arm convicts nothing with the register empty; `tests/lint` whole 1 failed / 2822 passed — lighting only, +5 titles its own; the counterforce's predicted report matched byte for byte; HZ-NUL 7 → 10; `.gitattributes` gains `*.glb binary`; `tests/lint` whole now costs 557 s — a throughput cost stated). FIX-P9 at the gate (branch `fix-tier-word-2-2026-09-20` at `d071f5068`, under addendum 106 D); FIX-P10 at the gate (branch `fix-phone-floor-2-2026-09-20`, nothing committed at the cut; under addendum 107). Every lane was ordered to write its `lane-resume.md` with its exact state within two tool rounds. THE SITTING'S TAIL, in order, is in the kit block: the six picks → P1's cure → P9 (+ the chair's OSR `--write` absorb) → P10 → the EIGHTH REFREEZE (attributed by lane) → RUN 23 in the consist (no red expected once the archival-exclusion arm is attributed and cured) → EM-R0d v4 PLACED (the placement command in the block; the worker ceiling re-measured from RUN 23's dist) → its sealed build → FIX-C2d, TOOL-21, TOOL-16, FIX-L3, FIX-W1 dispatched as seats free; FIX-D10 after RUN 23. TOOL-25's two closures: 'nothing measures compliance with the tests/lint-whole law' → CLOSED with reason — compliance is verified at collection by the chair reading every receipt's count lines against the law (a commit↔run binding exists only for sealed EM builds, by design); the pipeline-masks-exit-code hazard → already a LANE-PARALLEL law (addendum 106 F). OWED TO THE OWNER, unchanged: §934.75 · the push chain after RUN 23 · migrations 201–203 · the redeploy.")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 107 —"; assert u.count(key) == 1 and "addendum 108 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 108" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendment of 2026-09-20 " + stamp + " EDT — the account-switch handoff (ODQ §934.47 addendum 108)\n\n"
      "- The sitting was cut mid-composition by an account switch; the kit's RESUME-NOTE ACCOUNT-SWITCH HANDOFF block holds the exact live state and the tail's order (six picks → P1's cure → P9 → P10 → the eighth refreeze → RUN 23 → EM-R0d v4 placed → its build). TOOL-25 landed the docs-wide control-bytes walker with an empty exemption register; the estate carries zero raw NUL bytes in tracked text.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 108:", io.open(ODQ, encoding="utf-8").read().count("addendum 108 —"), "| charter amended | no NUL")
