# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**THE LANDING'S PROCESS LAW, EXECUTED:** the chair's `npm run build` (exclusive mutex) in the consist detached at 6b57180ef — `vite v7.3.6 … ✓ built in 16.37s`, `build exit 0 at 11:43:26`; `verify:dist` → `[test-ratchet] STRICT DIST OK — 59 discovered/reported file(s), 538 test(s), zero failed/non-run/uncollected/missing/extra/duplicate rows`, `dist-measure exit 0 at 11:43:46` (log `<SP>/consist-dist-measure-6b57180ef.log`, copied to the kit); the dist's engine chunk 677,935 B, `generation.worker` 1,401,208 B — the same figures as at ec0a30da2 (EM-B1f's +184 B of `roads/state.js` landed in `engine-core`, not the lazy engine; the byte budgets' dist arms passed inside STRICT DIST). "
 "**THE SIXTH REFREEZE `fb39b1ad6`** at 7a6f85d20: the door printed `files 2656 → 2656, parked 383 → 383, credited 2273 → 2273, titles 25074 → 25080, suiteTitles 6684 → 6684` — ⭐ `suiteTitles` MEASURED this time (the walker reached it); the +6 titles attributed exactly: EM-B1f +4, CURE-J's first half +2; the plain run `34 passed (34)`, `plain exit 0 at 11:44:03`. "
 "**THE COMPOSITION SITTING, FIRST HALF:** the probe at the flip tip found FIX-P1b (`92e959285`) conflicting because its parent FIX-P1 (`e0b03b63a`) was never in the order — the chair's omission; re-probed with P1 inserted, P1 itself conflicts with FIX-P3's F12 hunk in `src/components/generate/FoundingWorlds.jsx` (both lanes edit the file: P3's refusal `at` wiring, P1's fork salt). RULED: the fourteen conflict-free commits composed by the chair — FIX-L1 (2) → FIX-P3 (5) → FIX-P4 (2) → FIX-P5 (5) — into the slot at fb39b1ad6 → tip `7dea316c7`, each commit's file set equal to its source's, and BLOB EQUALITY proved over every file of the fourteen (three blobs differ, all legitimately: the two files two lanes touched — `scripts/mutation-coverage-manifest.json` (P4's F15 row + P5's tierWord row, both present at the tip) and `tests/components/phoneChromeFloor.census.test.js` — so the pre-commit hook rewrote NOTHING); then FIX-P1's OWN LANE is granted the slot for one step: cherry-pick `e0b03b63a` resolving `FoundingWorlds.jsx` keeping BOTH hunks (the resolution diffed against both parents and quoted), then `92e959285`, then `tests/components` WHOLE (P3's pins and its own both green — the point), `tests/lib` WHOLE, its declared suites, eslint on the union — the FIX-C2 idiom (the lane that knows both sides resolves; the chair composes only what applies clean). AFTER IT: FIX-C2b (4) → TOOL-13b (1) by the chair, then **COMPOSE-REPROOF-1** (brief written: one Opus verify lane re-executes every composed lane's declared count lines ONCE at the composed tip, consolidated by directory; the expected reds named — the lighting census, which the seventh refreeze then measures whole, and the provenance title), then the chair's docs commit (the standard's two hot-file rows), then RUN 22. "
 "**TOOL-15 PAUSED WITH A DURABLE LAW FOUND:** commit 1 `1c33181d6` on its lane (EM-B1k2's LANDED row `\"uncoveredBaseline\": 186` re-spelled `\"uncoveredBaseline\"`; `grep -cF` = 1; the trap proved both ways — with the baseline burned 186 → 185 in memory, `validate` reds `EM-B1k2.requiredSymbols[20].symbol is missing` against a packet that never touched the burn); commit 2 staged (`tests/lint/packetSymbolFigureCensus.walker.test.js`, 1 describe + 6 it, +453; its mutation row). THE POPULATION: 194 packets, 2,595 symbol rows, FOUR carry a name-bound figure and the four are exactly the class (EM-B1k2 cured; DOM-3, GVF-1, GV-4 ADMITTED); six instances total — three cured (`fff247009`, `6a3e8089f`, `1c33181d6`), three admitted. ⭐ **TE-26 IS DIRECTION-DEPENDENT:** a figure narrows a symbol row's claim; narrowing is a trap where the row asserts PRESENCE (every `requiredSymbols` row; a `retiredSymbols` row before its packet lands) and LOAD-BEARING where it asserts ABSENCE (a terminal `retiredSymbols` row) — measured, not argued: `rawColorLiteral.test.js` carries `const BUDGET = 1303` today (burned 1405 → 1313 → 1303), so GVF-1's figure-free spelling would red a landed retirement at once, as would GV-4's `titles:`/`suiteTitles:`; the three terminal retirees are KEPT and the walker admits them by shape, re-derived from disk each run. THE THRESHOLD MEASURED: a name-bound value with |v| ≥ 2 convicts 4 rows, all the class; every wider spelling refused by census (|v| ≥ 1 → 10; bare integer ≥ 2 → 27; ≥ 100 → 8; the brief's 'a bare number a register also holds' limb REFUTED — 40 registers hold 2,777 distinct values, convicting `at tick 7` and `## §2 · TRAIN LANDINGS`, 24 of 25 innocent); bare `<`/`>` excluded (`<h3>3.3 …</h3>` is a live WEB-7 row). NUMERIC MANIFEST ROWS: none rewritten — all 28 live in EM-P2 [LANDED] plus `packetVersion`, and mutating four to nonsense leaves `validate ok = true`: they are NOT gate-reachable; the walker freezes the admitted key set with reasons. PROOFS: red-first at c127cdfb2 exactly one arm; `ARMS=6 FAILURES=0` on its branch; seven mutants each convicted (under a substituted node+shim harness so as not to hold the gate — the walker's predicates ran, vitest's harness did not; stated honestly); register arms 713 / `[]` / `[]` / 186 = 186. JUDGMENT ACCEPTED: a new `tests/lint` walker over an arm in `tests/scripts/implementationPackets.test.js` (not an ENFORCER_DIR; invisible to the guard-of-guards). PROPOSAL ACCEPTED → **TOOL-15b chartered** (after TOOL-15 composes; EM-B1f has landed so the validator is no longer under a seal): the same predicate beside HK-3/HK-5 in `implementation-packets.mjs`, failing the gate and the pre-commit hook (the population is zero, it lands green); and `tests/scripts/implementationPackets.test.js`'s three live-estate census arms brought under the guard-of-guards (an ENFORCER_DIR or a NAME_PATTERN token — measure which). Predicted lighting +1 file · +0 · +1 · +6 · +1. "
 "**SEATS:** gate = FIX-B2 (exclusive builds) · FIX-P1 (the slot, one step); queue = FIX-D9 → FIX-T2 → TOOL-19 → TOOL-15 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents; working = TOOL-22 · TOOL-24 (resumed) · (COMPOSE-REPROOF-1 next).")
line = ("- **§934.47 addendum 94 — THE LANDING BUILD AT 6b57180ef GREEN (`STRICT DIST OK — 59 files, 538 tests`); THE SIXTH REFREEZE `fb39b1ad6` (`2656·383·2273·25080·6684`, `suiteTitles` MEASURED); FOURTEEN LANE COMMITS COMPOSED (`7dea316c7`, blob equality proved — the hook rewrote nothing); FIX-P1's OWN LANE RESOLVES ITS `FoundingWorlds.jsx` CONFLICT WITH FIX-P3 IN THE SLOT; TOOL-15 PAUSED — TE-26 IS DIRECTION-DEPENDENT (a figure is a trap in a PRESENCE row, load-bearing in a terminal ABSENCE row), TOOL-15b CHARTERED (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 93 —"; assert u.count(key) == 1 and "addendum 94 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 94" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the composition's first half; TE-26's direction law; TOOL-15b chartered (ODQ §934.47 addendum 94)\n\n"
      "- **TE-26 amended by measurement:** a symbol row's figure is a TRAP where the row asserts PRESENCE and LOAD-BEARING where a terminal `retiredSymbols` row asserts ABSENCE; presence rows are re-spelled figure-free, terminal retirees keep their figures, and `packetSymbolFigureCensus.walker` admits them by shape.\n"
      "- **TOOL-15b (NEW; after TOOL-15 composes):** the figure-in-a-symbol predicate beside HK-3/HK-5 in `scripts/implementation-packets.mjs` (the gate and the pre-commit hook), and `tests/scripts/implementationPackets.test.js`'s census arms brought under the guard-of-guards.\n"
      "- **The composition law (the FIX-C2 idiom, generalised):** the chair composes only what cherry-picks clean, proving file-set and blob equality; a conflicting commit is composed by the lane that owns it, in the slot, for that one step, keeping both hunks and re-proving both lanes' pins.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 94:", io.open(ODQ, encoding="utf-8").read().count("addendum 94 —"), "| charter amended")
