# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**CURE-J's FIRST HALF LANDED, ITS SECOND HALF IS THE OWNER'S:** commit `9ee0be7e9` on `cure-j-2026-09-20` — `recorderShas()` now digests each recorder file's COMMENT-STRIPPED, whitespace-collapsed source through a scanner-grade `stripComments` (line and block comments removed; string, template and regex literals byte-for-byte; the whitespace collapse is a DECLARED widening so an appended comment cannot move the sha — accepted, vetoable) — the finding corrected by `--numstat`: ONE line of JSDoc in `scripts/prose-rate-corpus.mjs`, not three; red-first at base 1/15, after the cure 1/20 with the generator golden green as control; 79 · 51 · 109 · 30 passed; eslint 0; lighting +2 titles. "
 "CHERRY-PICKED BY THE CHAIR INTO THE CLEAN SLOT AS `c127cdfb2` (the diff read whole; byte-identical over its two paths; `git show --stat HEAD` names only them). ⛔ **THE RE-RECORD CANNOT BE TAKEN BY A LANE OR THE CHAIR:** `tests/fixtures/.golden-freeze-register.json` is FROZEN (2026-09-16) and pins the fixture's WHOLE-FILE sha (`921c51cf…db41`, re-measured by `goldenFreeze.walker.test.js:421-433`); the row moves only through `recordGolden` under `GOLDEN_SHIFT_SIGNED` naming a shift record with `action: 're-record'`, and `goldenRecordDoor.js:49-53` makes that verb THE OWNER'S; the existing 09-17 record's authorization is SPENT (using it would be the forged authorization its own docblock warns about) — the lane wrote no record. MEASURED WITHOUT WRITING: rows byte-identical, `rowsSha` unchanged at `e972c0d0…2559`, 0 moved / 0 added / 0 removed (1050 → 1050); only `recordedOverSha`, `note` and `recorder` would move; whole-file `921c51cf…db41` → `0f64dbd8…879a`; door `predictedRows` 2 → 2 — ZERO PROSE MOVEMENT. → **§934.71 ASKED: sign the PROVENANCE-ONLY re-record of the prose manifest golden** (the chair drafts `docs/shift-records/2026-09-20-cure-j-provenance.json` at the flip sitting with those figures; on the owner's word a lane runs the door with `GOLDEN_SHIFT_SIGNED`); until then `tests/property/dossierProseManifest.test.js` stays RED on that one title in every full check and the push recommendation stays at `141a1d775`. "
 "**EM-B1f's BATCHES 1–3 GREEN except the two named reds** (its tree clean, the six-file patch 24,692 B saved with per-file SHA-256s): red-first 4/48 (exactly its four titles; A1's red the jailed mayor who still governs); focused 52/52; walker 4/4; §P6 deletion proof (−741 B, A3 alone red convicting `state.js` by name; FLAGGED 6 → 7, STOP 7 clear); R18 13/13; densityLaw 151/151; goldens 1/29 — ONLY the provenance title, both fixtures byte-identical; `tests/lint` whole 2790/2791 (the lighting red alone; 174 files = 173 excluded + the walker, matching §P7). LIGHTING +0/+0/+0/+4/+0 as predicted (`titles 25074 → 25078` by execution; `suiteTitles` never reached — the walker asserts it after `titles`; measured from the diff instead). ONE DECISION TAKEN IN SCOPE, ACCEPTED (vetoable): §6's verbatim contract did not typecheck (`TS2345` on both sealed configs — `NPC_UNAVAILABLE_STATUSES` is `readonly NpcStatus[]`) → the HAYSTACK widened by the file's adjacent idiom (`/** @type {readonly string[]} */ (OFF_STAGE_STATUSES).includes(...)`), never the needle cast into `NpcStatus`; 293 effective (+5), 7,911 B (+184), the declaration line byte-identical; both typechecks at their ceilings; §6's TEXT is re-cut by the chair at the flip. CONFIRMED (was plausible): the walker's `:402` 'all eight flagged files' conflates roster rows with flagged files (six at base). RULED (addendum 78's precedent, vetoable): B1f RE-SEALS at c127cdfb2 and LANDS WITH CHECK 7's ONE TITLE AS A NAMED PRE-EXISTING RED whose cure is owner-gated (§934.71); every other check is the seal's verdict. "
 "**FIX-P5 FOUR COMMITS ON ITS LANE** (`e207d0718` F9+F16, `881c84863` the pill-host register, `5c29fef92` F8, `a5575107a` F14; `tests/lint` whole 2778/2779; `tests/pdf` 458 with both goldens unmoved; Group D's red-first convicts `ResourcesTab.jsx:94 \"UNEXPLOITED\"`): the review's `tierFacts.js` premise was WRONG (it declares the spellings UNIFIED to 'Thorpe', protecting the token, not a second label) — the lane made the edit with the declaration quoted; TWO F14 SURFACES REGISTERED, NOT CURED, each naming the authority it lacks → **FIX-P9 chartered**: the Compendium's `titleCase(id)` label baked into a byte-pinned generated artifact (the row is EXECUTED — it reds the day the handover lands) and the gallery's facet-wide `capitalize`; `SummaryTabV2.jsx`'s F14 read lands with Group D (the lane says so in C's message rather than overstate). "
 "**CURE-J's TWO ITEMS FATED:** 43 test files carry a LOCAL `stripComments`, most string-blind (FIX-P3's class) → FIX-T2 told to REUSE CURE-J's scanner-grade helper (never a 44th copy) and to count the copies in its sweep ledger (their hoist a slot of its own — **TOOL-20 chartered**, after FIX-T2); **47 of 50 frozen golden-register rows carry `proofForm: null`, making the door's `PROOF_FORM_MISMATCH` refusal structurally unreachable** (§555.8's map-family protection INERT on `town-map-golden`, `town-map-v2-golden` and 45 more) → **TOOL-21 chartered** (measure-first: which rows should carry a proof form, what the door would refuse, the register edit priced as the owner's door or the chair's mint — recon before any write). SEATS: gate = FIX-P5 · EM-B1f (batch 4) · TOOL-13b (finishing) → FIX-C2b → FIX-B2; working = FIX-D9 · FIX-T2 · TOOL-18 · (CURE-J done → TOOL-19 next).")
line = ("- **§934.47 addendum 86 — CURE-J HALF LANDED (`9ee0be7e9` → composed `c127cdfb2`: the recorder identity is the CODE); ITS RE-RECORD IS THE OWNER'S DOOR → **§934.71 ASKED** (a PROVENANCE-ONLY re-record: 1050 → 1050 rows, `rowsSha` unchanged; whole-file `921c51cf…` → `0f64dbd8…`); EM-B1f's BATCHES 1–3 GREEN, ITS §6 TYPECHECK CURE ACCEPTED, RE-SEALED AT c127cdfb2 TO LAND WITH CHECK 7's TITLE A NAMED PRE-EXISTING RED; FIX-P5 FOUR COMMITS (FIX-P9 chartered); TOOL-20 + TOOL-21 chartered (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 85 —"; assert u.count(key) == 1 and "addendum 86 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
assert "§934.71" not in u.split(line)[0][-20000:] or True
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 86" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — CURE-J half landed; §934.71 asked; EM-B1f re-sealed; FIX-P9, TOOL-20, TOOL-21 chartered (ODQ §934.47 addendum 86)\n\n"
      "- **CURE-J:** commit 1 composed at `c127cdfb2` (comment-insensitive recorder identity). Commit 2 — the provenance-only re-record — is the OWNER's door (§934.71): the chair drafts `docs/shift-records/2026-09-20-cure-j-provenance.json` at EM-B1f's flip sitting with the measured figures (rows 1050 → 1050, `rowsSha` `e972c0d0…2559` unchanged, whole-file `921c51cf…db41` → `0f64dbd8…879a`, `predictedRows` 2 → 2); on the owner's word a lane runs `recordGolden` under `GOLDEN_SHIFT_SIGNED`. Until then every full check reds on that one title.\n"
      "- **EM-B1f** re-seals at `c127cdfb2` and lands with check 7's one title a NAMED PRE-EXISTING RED (addendum 78's precedent); §6's text re-cut at the flip to the haystack-cast form the build proved.\n"
      "- **FIX-P9 (NEW; after FIX-P5 composes):** the two F14 surfaces FIX-P5 registered — the Compendium's `titleCase(id)` label in a byte-pinned generated artifact (regenerated through its own re-mint idiom) and the gallery's facet-wide `capitalize` (a tier-aware label), with the lane's executed register rows deleted the day each lands.\n"
      "- **TOOL-20 (NEW; after FIX-T2):** the 43 local `stripComments` copies in `tests/` hoisted onto CURE-J's scanner-grade helper, string-blind ones first.\n"
      "- **TOOL-21 (NEW; measure-first):** 47 of 50 frozen golden-register rows carry `proofForm: null`, so the door's `PROOF_FORM_MISMATCH` refusal is unreachable (§555.8 inert on the map family) — which rows should carry a proof form, what the door would then refuse, and whether the register edit is the owner's door or the chair's mint.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 86:", io.open(ODQ, encoding="utf-8").read().count("addendum 86 —"), "| charter amended")
