# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 109 — THE CLEAN PAUSE (the owner, " + stamp + ": 'Pause everything cleanly when you have everything ready for transfer'): every lane STOPPED CLEAN with its resume note written and snapshotted into the kit; zero gate processes running; the kit sealed (`a3e7ed4f3`); the tail's order unchanged (2026-09-20 " + stamp + " EDT; the chair; vetoable).** "
 "THE LANES AT THE STOP: **FIX-D9** composition COMPLETE at `48450e98c` (all three composed-tip reds attributed, none its own; its `tests/build` / `tests/scripts` / golden proofs still owed — or RUN 23 is the proof); **FIX-P1** cure COMMITTED `61c5f1722` (FIX-P1d: the address ceiling measured by running the derivation, so `lib` never reads `config.seed` — the OSR conviction was a REAL finding: `seed` is not a key of the generator's config, `forkConfigFor` deletes it; green on its branch: OSR exit 0, `observedShapeReaders` 46/46, `tests/lib` 1800, `tests/components` 2055, `tests/lint` whole 1 failed / 2775 — its base register's lighting red only), with the CURE-J archival-roster line (16 → 17) assigned as its second commit at composition; **FIX-P9** two of three commits — `d071f5068` (proofs complete; ⚠ shipped WITHOUT the Co-Authored-By trailer, the lane's omission, amend forbidden, recorded) and `de16bdf6a` (its `tests/lint` whole sweep OWED before composition; the subject says so), commit 3 prepared and not applied; its noticed `src/components/organic/samples/fixtures.js:86` hard-coding `tier: 'Thorp'` (census-invisible) → a slot in its commit 3; **FIX-P10** NO commit (all four commits' edits on disk with every red-first printed; `tests/lint` / `tests/ui` / voiceMechanics owed) — its divergence from addendum 107's commit-3 ruling is ACCEPTED, no veto: the clearance is `paddingTop: max(SP.md, calc(TOUCH_TARGET - HEADER_H))` rather than moving `top`, so the bar still butts the header, no seam can exist by construction, DESKTOP IS UNTOUCHED (the expression resolves to `SP.md` at 1024 and 1280) and the phone bar reclaims exactly the 12.83 / 9.53 / 8.57 / 6.24 px the invisible button took — the declared behaviour change shrinks to the phone band; its finding that `src/domain/worldPulse/supplyCompleteness.js` carries a raw NUL at 5dd5e8e68 (introduced by `243ddc130b`) is TOOL-25's cure `f1367909a` — compose TOOL-25 first and that red disappears. THE LANE LAW ADDED: a clean apply is DRY-RUN in a throwaway worktree, never reasoned from the hunks (FIX-P1's two conflicts were the same shape). THE SUCCESSOR'S FIRST ACTS, in order: read the kit's ACCOUNT-SWITCH HANDOFF block; verify the slot at `48450e98c` clean ON the branch; cherry-pick the six (TOOL-19 ×2 · C2c ×3 · TOOL-25) with the file-set + blob check each; compose FIX-P1's `61c5f1722` + the roster line; resume FIX-P9 (the owed sweep; commit 3) and FIX-P10 (the three owed runs; four commits) as Opus lanes from their notes; P9's OSR absorb by the chair; the eighth refreeze attributed by lane; RUN 23; EM-R0d v4 placed; its build.")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 108 —"; assert u.count(key) == 1 and "addendum 109 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 109" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendment of 2026-09-20 " + stamp + " EDT — the clean pause (ODQ §934.47 addendum 109)\n\n- Every lane stopped clean with a note; FIX-P1's cure `61c5f1722` committed; FIX-P9 two commits (one owed sweep, one missing trailer recorded); FIX-P10 no commit, its paddingTop divergence accepted. The successor's first acts are listed in addendum 109 and the kit's handoff block.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 109:", io.open(ODQ, encoding="utf-8").read().count("addendum 109 —"), "| charter amended | no NUL")
