# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**FIX-P1c COMMITTED `5fbe2d82c` on `fix-fork-salt-2026-09-20`** (over 92e959285; 4 files, +110/−0; every file text to git; no hook rewrite; goldens byte-identical). **§934.72 EXECUTED UNDER THE GRANT:** `SeedField` carries `maxLength={FORK_SEED_MAX}` — the constant DERIVED, never typed (`longest card seed + 1 + FORK_SUFFIX_MAX`, computed once in `lib/anonForkSalt.js`, imported by the field AND the address pin so they agree by construction), MEASURED at 26 with `blackcrag-016-0905f09332e2` exactly 26 (on the ceiling: a ceiling lowered by one reds); every seed the product can mint measured first (`kernel/prng.js`: `<base36 clock><3 sequence><6 entropy>` = 17 chars today, 18 once the clock needs a ninth digit — both under 26, asserted by an arm). ⚠ A DECLARED BEHAVIOUR CHANGE, recorded and signed: a reader who typed a seed longer than 26 characters could before and cannot now (seeds are opaque strings, a long phrase was legal; the field clips it) — the price of a readable limit, in the constant's docblock and the commit. The new `lib → data` import is in the permitted direction and the sample table was already in that chunk. **§934.66 PROVED BY EXECUTION, no STOP owed:** `fork 1 = fork 2 = cnocby-033a-0905f09332e2`; 1,000 repeats → ONE distinct seed; a different identity differs — two permanent arms (`ONE ACCOUNT re-forking ONE card is byte-identical, a thousand times over`; `a signed-in repeat fork survives a reload AND a cleared device salt` — the account branch never consults the device). COUNT LINES: red-first `layeredConfigurationPanel.test.jsx` 1 failed | 10 passed (`expected -1 to be greater than 0` — the arm names ABSENCE, not mismatch; worth keeping); `tests/components` WHOLE 292/2055 (the lane's tree lacks P3's composed tests; the slot reads 297/2103 — the composition runs the directory whole, as the re-proof does); `tests/ui` WHOLE 162/1076 and P3's `refusalNoticeCoverage` walker added unasked because the panel is a SHARED surface; `tests/lib` WHOLE 174/1800; `tests/data` 24/311; the lint instruments 32; voiceMechanics 30; eslint 0. The second composition's order gains P1c after FIX-T2. "
 "**PREPROOF-EM-R0d-v4 DISPATCHED at 578272a99** (the freed seat; brief written): R0d's condition (FIX-C2 composed) is satisfied, but the first composition moved THREE of its paths after its pre-proof tip 141a1d775 — `tests/components/dossierLabelCase.test.jsx` +95 (FIX-P5's badge-capitals law: R0d's TEST row must be RE-CUT over it, its cases obeying the law), `src/domain/prose/holderTable.js` 2 lines and `tests/build/domainGeneratorsBoundary.test.js` 4 lines (citation re-addresses — proved comment-only, admitted as expected movers); the lane re-measures every claim (the eleven symbols; the worker budget under the fourth amendment's no-placement-cure law — R0d modifies three generators in the worker's closure; the lazy engine against FIX-B2's new headroom; the edge-shared `inputs`; the lighting delta by `parkReasonsFor`; the preamble hash the chair PLACES under — `c9f33c8d…6675` — and the golden as it stands at its tip) and writes version 4 as copies; the chair places it at EM-R0a's flip. `src/data/bandLadders.js` is a CREATE under `src/data`, so preamble row 13's census row does not fire (the lane confirms whether the census walks `src/data`). SEATS: working = FIX-P4b · COMPILE-TOOL-13a · FIX-C2c · PREPROOF-EM-R0d-v4; gate = EM-R0a · the re-proof · FIX-D9; queue = TOOL-19 → TOOL-15 → TOOL-22 → TOOL-24 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents.")
line = ("- **§934.47 addendum 102 — FIX-P1c COMMITTED (`5fbe2d82c`): §934.72 EXECUTED (a DERIVED `FORK_SEED_MAX` of 26 on the field and the pin; a declared behaviour change — a typed seed longer than 26 now clips) AND §934.66 PROVED BY EXECUTION (1,000 repeat forks → one seed; a reload and a cleared device salt move nothing); PREPROOF-EM-R0d-v4 DISPATCHED (three of R0d's paths moved since its pre-proof; the badge-capitals law re-cuts its TEST row) (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 101 —"; assert u.count(key) == 1 and "addendum 102 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 102" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — FIX-P1c; EM-R0d's version 4 (ODQ §934.47 addendum 102)\n\n"
      "- **FIX-P1c** (`5fbe2d82c`) composes after FIX-T2 at the second composition; §934.72 and §934.66 are executed and closed.\n"
      "- **EM-R0d version 4** is pre-proofed at the composed tip (its badge-capitals TEST row re-cut; two comment-only movers admitted) and placed at EM-R0a's flip under the fourth amendment's hash; the placement window runs from the v4 pre-proof tip.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 102:", io.open(ODQ, encoding="utf-8").read().count("addendum 102 —"), "| charter amended")
