# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**EM-R0a PLACED READY at `2dc08a595`** (the placement commit `680eacb8d`; `valid: 195 packets (1 READY)`): pre-proofed at 141a1d775; the window since it over its seven paths moved ONLY `scripts/mutation-coverage-manifest.json` (+24/−1 — the shared register its REGISTER row joins, an expected mover: P4's, P5's, C2's and 13b's rows landed there); its four required symbols resolve (`generateSettlementPipeline`, `goldenCorpus`, `keyOf`, `ENFORCER_DIRS`); the CREATE targets absent; no non-terminal reserver. THE CHAIR'S CUTS: the wiring-census MODIFY row (a CREATE `.js` under `src/domain` — row 13), the anti-vacuity walker and the `tests/lint --exclude=<lighting walker>` step in `checks` before the validate step (row 14 / §P7 of the third amendment), two COMMENT-ONLY MODIFY rows (`tests/store/decreeRegistryPersistence.test.js` near `:17` — its header says `src/domain/edit/**` 'does not exist at this commit', false once `recordRegister.js` exists; `tests/lib/editTravel.test.js` near `:15` — one clause), the index rows after EM-B1f; the preamble stamped with the FOURTH amendment's hash. ONE PLACEMENT TRAP CURED IN THE SCRIPT: the compiled manifest carried `retiredSymbols: null` (the pre-proof's 'EMPTY, the post-edit simulation's RESULT') and `validate:packets` refused — `EM-R0a.retiredSymbols must be an array when present`; the first placement was rolled back (the tree restored, nothing committed), `place_ready_v2.py` now normalises an empty marker (`null`, `{}`, `\"none\"`) to `[]` and refuses anything else, the second placement committed; memory fold 112 gains the line (compiled manifests write `[]`). **ITS SEALED BUILD DISPATCHED into `slot-2` at 680eacb8d** (the frozen tuple `2664·359·2305·25501·6812`; its check 2 names `dossierProseManifest.test.js`, so its `check:packet` reds on the provenance title — the NAMED PRE-EXISTING RED under addendum 78's precedent, proved on a clean tree first; the census regeneration in its last gated batch; the chair's build + `verify:dist` at its landing). THE SLOT IS SEALED AGAIN — no chair commit on the branch until R0a lands. THE CONSIST: run 22 at 578272a99 past `typecheck:ratchet OK (167/167)` into `domain-strict` at 12:04.")
line = ("- **§934.47 addendum 97 — EM-R0a PLACED READY (`680eacb8d`) UNDER THE FOURTH AMENDMENT WITH THE CHAIR'S CUTS AND ITS SEALED BUILD DISPATCHED; A PLACEMENT TRAP CURED IN THE SCRIPT (a compiled `retiredSymbols: null` fails the validator — normalised to `[]`) (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 96 —"; assert u.count(key) == 1 and "addendum 97 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 97" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — EM-R0a placed and building (ODQ §934.47 addendum 97)\n\n"
      "- **EM-R0a is READY at `2dc08a595` (placed `680eacb8d`) and building under seal;** EM-R0d (conditional on FIX-C2, now composed) is placed at R0a's flip; EM-R0b v4 after R0a and R0d land; EM-R0f after R0b; EM-R0c after R0f and R0b.\n"
      "- **Compile law:** a compiled manifest writes `retiredSymbols: []`, never `null` or a word — the validator refuses a non-array when the key is present; the placement script normalises an empty marker and refuses anything else.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 97:", io.open(ODQ, encoding="utf-8").read().count("addendum 97 —"), "| charter amended")
