# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**FIX-L1 COMPLETE on `fix-parked-openers-2026-09-20`** (base 63e40fe57; `188f64b60` CURE-A3 — `tests/lint/composeStateProseFence.test.js`; `38f119cac` the 25 renames): the `OPENER_UNRESOLVED`-only class is CLOSED at 0 files; the roster's 26 was 25 (`ruinInstitution.test.js` already cured by CURE-C at 145acdb75); 41 shadowing bindings renamed; every batch identical before and after (`tests/domain` 277, `autonomy` 14, `generators` 2, `property` 34 — 327 both ways; the 'before' tree restored by `git show 63e40fe57:<path>`, never `git checkout --`, because the 25 were staged and a checkout would have read the cured blob), `tests/lint` whole 2776/2777 (the lighting red only), eslint 26 files exit 0, goldens unmoved; CURE-A3 red-first 9/10 → 10/10 and NOT latent (the mask destroyed 156,526 newlines across 2,207 src files, and the `(?:^|\\n)`-anchored `IMPORT_RE` lost imports after collapsed comments — `[\"./a.js\"]` before, `[\"./a.js\",\"./b.js\"]` after; every finding identical under both forms today). LIGHTING, both ends executed: base live `2651·383·2268·25034·6678`, tip `2651·358·2293·25364·6786`; lane delta files +0 · parked −25 · credited +25 · titles +330 · suites +108; composed onto the fifth refreeze that is `2656·358·2298·25404·6792` (the chair's refreeze at the terminal absorbs it). Composition clean (none of its 26 files touched by the 27 commits since its base). ITS ITEMS FATED: (1) the lighting walker's own `:2318` comment ('29 estate files bind a test word today' — 30 at its base, 5 after the cure; survivors `fidelityNoise`, `pactFormation`, `settlementAlignment`, `roadNetworkMst`, `chronicleSnapshotShape`) → TOOL-9's hand-off (that lane holds the walker; a comment, no title); (2) `tests/edgeFunctions/contracts.test.js` needs three other reason families cured → **FIX-L3 chartered** (low; after FIX-L2); (3) `densityLaw.test.js` stays FIX-L2's; (4) ⛔ **THE SHARED TIER REFUSES eslint** (`SHARED tier REFUSED — the command declares no worker cap`; the guard reads only `--maxWorkers`) and a refused line prints no count → LAW: eslint runs BARE, never through the mutex (LANE-PARALLEL this sitting); (5) `stopConditions.test.js` 14 vitest tests vs 16 walker titles → TOOL-9's hand-off (a census reconciliation note). "
 "**FIX-C2b SHARPENED THE RUN-21 FINDING BY EXECUTION:** the recorder mismatch is ONE file, pre-existing at its base — `scripts/prose-rate-corpus.mjs` live `d97c3912…` vs recorded `0f0efb35…` (the other two MATCH) — and its entire cause is one COMMENT hunk in `ee2406191` (`EconomicsTab.jsx:251-257` → `:272`) against 1,050 rows with `rowsSha` untouched: the raw-byte pin cannot tell a docblock from a decision. C2b touched none of the three (ARM 1/3/4 = 0 inside them, checked, not assumed) and added structural prevention in its own walker's header (a ⛔ refusal naming the three files, the reason, FIX-C2's precedent). `dossierProseManifest.test.js` is expected red at its base and in none of its batches — never re-recorded on its account. "
 "**THE GATE:** FIX-L1 done → TOOL-13b handed the gate (one focused run); shared tier = FIX-P5 (`tests/lint` whole caught two of its own defects — a new pill host registered with its geometry reason, an un-anchored negative anchored — both fixed and re-running) · EM-B1f (batches 1–3) · CURE-J · TOOL-13b; queue = FIX-C2b → FIX-B2 (exclusive, alone). WORKING: CURE-J · FIX-D9 · FIX-T2 · TOOL-18. THE COMPOSITION SITTING (after EM-B1f lands with CURE-J): FIX-L1 (2), FIX-P3 (5), FIX-P4 (2), FIX-P5, FIX-C2b (4), TOOL-13b (1), FIX-B2 (3) in that order, each lane re-proving at the composed tip; then RUN 22.")
line = ("- **§934.47 addendum 85 — FIX-L1 COMPLETE (the `OPENER_UNRESOLVED`-only class closed at 0; CURE-A3 not latent; parked −25 · credited +25 · titles +330 · suites +108); FIX-C2b PINNED RUN 21's CAUSE TO ONE COMMENT HUNK IN ee2406191; THE SHARED TIER REFUSES eslint (LAW: eslint runs bare); FIX-L3 CHARTERED; TOOL-13b HANDED THE GATE; THE COMPOSITION ORDER SET (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 84 —"; assert u.count(key) == 1 and "addendum 85 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 85" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — FIX-L1 complete; FIX-L3 chartered; TOOL-9's hand-off; the composition order (ODQ §934.47 addendum 85)\n\n"
      "- **FIX-L1 is complete on its lane** (`188f64b60`, `38f119cac`); composed at the composition sitting after EM-B1f lands with CURE-J, in the order FIX-L1 → FIX-P3 → FIX-P4 → FIX-P5 → FIX-C2b → TOOL-13b → FIX-B2, each lane re-proving at the composed tip; then RUN 22.\n"
      "- **FIX-L3 (NEW; low; after FIX-L2):** `tests/edgeFunctions/contracts.test.js`'s three other park-reason families cured.\n"
      "- **TOOL-9's hand-off gains two lines:** the lighting walker's `:2318` comment re-cut to the measured survivors (a comment, no title); `stopConditions.test.js` 14 vitest tests vs 16 walker titles reconciled in the census note.\n"
      "- **Lane law:** eslint runs bare — the mutex's shared tier refuses a command with no worker cap, and a refused line prints no count.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 85:", io.open(ODQ, encoding="utf-8").read().count("addendum 85 —"), "| charter amended")
