# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**COMPILE-TOOL-13a DONE — THE RUNG AS BRIEFED IS NOT MINTABLE, PROVED NOT ARGUED:** four of the seven briefed members (the root widening, P1a, M3 the header, the `minRows` default) edit `scripts/lib/legacy-reader-shape-scan.mjs`; the lane compiled all four as real files and ran `assertGovernedLegacyDetectorSource` on those exact bytes — ALL FOUR REFUSED, the untouched control ACCEPTED (a single-invocation receipt); even the +1-byte `minRows` change is refused exactly as the +1,452-byte P1a. THE MIGRATION-BUNDLE DOOR DOES NOT RELAX THE FREEZE, IT RE-ASSERTS IT: `validateMigrationReceipt` → `governedLegacyAlgorithmOf` → `governedLegacyDetectorSha256()` is the same disk read and the same predicate, and it pins `legacyAlgorithmBaseSha`; the bundle is validated at `check-observed-shape-readers.mjs:3015` BEFORE the schema admission that lets a rung move the other scanner files; the anchor is HISTORICAL — `git rev-parse 6e7acc4d:scripts/lib/reader-shape-scan.mjs` → `0310fa9f…`; the file has ONE commit in its history and twenty-two rungs landed without touching it. WHAT IS MINTABLE (compiled, with the two-commit sequence, the test list and the pin table in §7): a two-member schema-23 rung — **M1** the denominator field (figures re-measured at the tip) and **M2** the M12 docblock (+1,531 bytes of prose), both in `check-observed-shape-readers.mjs`, which a schema bump DOES move (the schema-22 precedent `51d59d00b` changed that exact file by 73 lines) — plus the `scanStats` re-freeze as the rung's write. THREE THINGS NEITHER PREDECESSOR FOUND: (1) the widening RAISES A CEILING — `institutionName on proposalPayload` 1 → 2, and `predecessorIncreased` is one of the two figures the migration report raises an issue for, never non-zero in the register's history (TOOL-13 §6.6's 'existing rows never grew' refuted for the root arm); (2) the thirteen re-triaged by EXACT SOURCE ADDRESS (not a textual probe): 0 re-attributed, 0 mixed, 13 LOST across 97 dropped raw addresses — KEPT-by-explicit-carry recommended for all thirteen; (3) `writer-reach-scan.mjs` imports the frozen `makeResolver` DIRECTLY and pins it in its own `DETECTOR_SOURCES` + baseline — any detector change owes a SECOND register re-freeze no brief named. CORRECTIONS: the header names FOUR roots (`settlement`, `worldState`, `save`, `campaign`), not six — `pulseResult` and `wizardNews` appear nowhere in it (the chair's brief carried TOOL-13's candidate list as the header's); `minRows`: EXCLUDE — refused, and behaviour-neutral (every call site passes it explicitly; the `= 8` default has zero consumers; the real cure lives outside the frozen file, §8.6 proposed not built). "
 "**THE DECISION (§934.73), TAKEN BY THE CHAIR UNDER THE OWNER'S GRANT AND RECORDED VETOABLY:** the compile puts it as the owner's — re-govern the detector at a new blob (the freeze stops meaning 'the historical detector') or CLOSE the widening, P1a and MR with reason. RULED: **CLOSE WITH REASON.** The freeze CR-OSR-FREEZE-1 exists so the observed-shape register's identity is the HISTORICAL instrument — a content-addressed, history-bound register whose meaning the estate has leaned on through twenty-two rungs; re-governing it buys +26.5 % relative resolution at the price of ERASING thirteen banked rows (every one with its read still written in source), a ceiling raise the register has never seen, and a second register re-freeze — and TOOL-13 proved the 7.6 % is overwhelmingly a DENOMINATOR ARTEFACT, which M1 cures by making the rate say what it measures. The dark root prior stays as a DOCUMENTED, MEASURED limitation: M1's field prints the two roots the frozen detector binds and the four it names, so the contradiction TOOL-13 found is stated by the instrument itself rather than hidden in a docblock the freeze forbids editing. Reversal: one owner sentence re-opens it with the compile's diffs ready. **THE MINT (the chair's act, after EM-R0a lands and the slot is free):** the schema-23 rung = M1 + M2 + the `scanStats` re-freeze through the migration-bundle door on a branch cut at the integration tip, following the compile's §7 sequence; TOOL-13a's charter row narrows to exactly that. The lane's read tip clean at start and end; four standing hashes byte-identical; nothing written.")
line = ("- **§934.47 addendum 103 — COMPILE-TOOL-13a DONE: THE RUNG AS BRIEFED IS NOT MINTABLE (four of seven members edit the FROZEN legacy detector — refused by execution; the bundle door re-asserts the freeze; the anchor is historical); A TWO-MEMBER RUNG (M1 the denominator field + M2 the M12 docblock + the `scanStats` re-freeze) IS COMPILED AND MINTABLE; THE WIDENING WOULD RAISE A CEILING AND LOSE ALL THIRTEEN ROWS; **§934.73 RULED BY THE CHAIR UNDER THE GRANT: CLOSE THE WIDENING, P1a AND MR WITH REASON** — the freeze means the historical detector; the mint follows R0a's landing (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 102 —"; assert u.count(key) == 1 and "addendum 103 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 103" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — TOOL-13a narrowed to the mintable rung (ODQ §934.47 addendum 103)\n\n"
      "- **TOOL-13a (RE-CUT):** the schema-23 rung = M1 (the `--report` denominator field, computed outside the byte-frozen blob, naming the four roots the frozen detector's header claims and the two it binds) + M2 (the M12 docblock correction) + the `scanStats` re-freeze, all in `scripts/check-observed-shape-readers.mjs`; minted by the chair through the migration-bundle door on a branch cut at the integration tip after EM-R0a lands, per the compile's §7. The root widening, P1a and `minRows` are CLOSED with reason (§934.73): the legacy detector is frozen as the historical instrument, and the door re-asserts the freeze.\n"
      "- **Recorded facts for any future OSR rung:** `writer-reach-scan.mjs` imports the frozen `makeResolver` directly and pins it in its own register — a detector change owes a second re-freeze; `predecessorIncreased` has never been non-zero in the register's history.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 103:", io.open(ODQ, encoding="utf-8").read().count("addendum 103 —"), "| charter amended")
