# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("⭐⭐ **THE OWNER, 12:2x, MID-TURN: 'I sign everything. Anything that you need for a signature now or in the future I give.'** — RECORDED AS A STANDING SIGNATURE GRANT (memory `owner-directive-2026-09-20-i-sign-everything-a-standing-signature-grant`): it covers every owner-SIGNATURE class — golden re-records through the door (each shift record carries these words verbatim as `ownerWords`), ratifications offered for signature, and the decision points the chair put with a recommendation; it does NOT cover the push, deploys, migrations, production data deletion, security posture or new paid capability — those are not signatures and stay the owner's explicit word per case; each use is recorded here, vetoable. THE USES, THIS SITTING: **§934.71 SIGNED** → the shift record `docs/shift-records/2026-09-20-cure-j-provenance.json` written with the words verbatim and COMMITTED (`3484b8c24`, on the consist's detached head over CURE-K) — CURE-J's lane runs the door (`recordGolden` under `GOLDEN_SHIFT_SIGNED`) on its own branch from the committed tree, the re-record composing after EM-R0a lands; **§934.70 SIGNED** → FIX-D9 adds the retirement commit (`foldTradeCategories.js`, its test, its excision row; the walker gains a RETIRED-means-ABSENT arm; the dark trio stays dark by the rows as written); **§934.72 SIGNED** (`SeedField` maxLength = the declared width) and **§934.66 SIGNED** (deterministic repeat forks — proved by execution, never assumed) → FIX-P1c on FIX-P1's lane; **§934.64 SIGNED** (keep 10 px — FIX-P5's executed exception stands; CLOSED); **§934.65 SIGNED** (FIX-D4 + FIX-D6 + FIX-W1's re-records — their lanes dispatch when seats free, each through the door with its own record); **§934.68 SIGNED** (the lazy-engine ceiling's two raises ratified — recorded in `vendorPdfLazy.test.js`'s header by FIX-B3's lane; FIX-B2's placements have since bought 35,079 B of headroom, so the ratification binds a number the estate is now well under); **§934.69 SIGNED** (the landing's 'Save to Library' stays decorative until launch; CLOSED). THE PUSH CHAIN remains the owner's explicit word: the chair still recommends pushing at the first green full check. "
 "**RUN 22 (578272a99) EXITED 1 at 12:19:29 ON FIVE TITLES:** the expected provenance title, and FOUR `tests/edgeFunctions` reds (`aiCharterBundle.freshness`, `aiOutputSchemaBundle.freshness`, `edgeSharedBundleReproducibility` ×2) — CAUSE, MEASURED: FIX-P5's F14 (`5236b05a6`) changed `src/domain/display/humanizeEngineTokens.js`, an INPUT of `aiCharterBundle` and `aiOutputSchemaBundle` (114 / 115 inputs), and the composition carried no regeneration — a FIX lane is not under the EM preamble's row 10. **CURE-K by the chair (`3e9a6c261`, the consist's detached head over 578272a99):** `npm run build:edge-shared` re-stamped exactly SEVEN paths (the two bundles + all five metas); the three suites green before the commit (67/67) AND after it (the pre-commit hook ran `eslint --fix` over the two bundle files and a stash cycle — re-proved 67/67 at HEAD; the foreign stash survived, the hook's backup gone); cherry-picked into the slot after EM-R0a lands. THE LAW into LANE-PARALLEL and memory: a parallel lane measures its `src/` paths against the five metas' `inputs` before staging and regenerates with its change. The chair's build + `verify:dist` at the composed tip (+CURE-K) launched in the consist (the chain's blacked-out steps). "
 "**FIX-B2 COMPLETE ON ITS LANE** (`5cc0e6c14` · `2fa685264` · `fd4be7c07`; 4 files, +422/−15; ZERO src bytes; its lighting walker run pending): chunks statically importing the engine **38 → 18 → 17 → 5**; the engine chunk 677,935 → **643,221 B (−34,714)**; effective headroom 365 → **35,079 B**; first paint 8 files unchanged; `generation.worker` 1,401,208 (the same content hash throughout); EAGER 268 throughout; nothing joined the set; no pin moved; the 679,000 ceiling untouched; the five owed build titles in the two existing homes proved live by a planted mutant (`tests/build` 538 → 543; the dist arms non-vacuous by a control run skipping 63 without `VERIFY_DIST=1`). THE FIVE RESIDUAL ANCHORS ACCOUNTED FOR: `SettlementsPanel` = the `structuralValidator` closure (refused on proportion); `composeInstantWorld`, `generationRequest`, `instantWorldBody` = the engine's own legitimate door; `generateWorldBook` = a ROLLUP GROUPING ARTIFACT (its 90-module static closure reaches no engine member — no single-member pin can cut it) → **TOOL-17's ratchet counts EDGES, not Rollup's grouping** (its brief re-cut: freeze the set of importers that reach an engine member by a static edge; the grouping artifact named as admitted). THE LANE'S OWN CATCH, on the record: it drafted figures ahead of measuring them ('38 → 8, engine 637,332') and corrected them to the measured 5 / 643,221 before commit 3. A NEW HAZARD: `negativeAssertionAnchor.walker.test.js` scans RAW lines with no comment stripping, so a comment merely NAMING the three matchers convicts a file against its frozen exact count → **TOOL-20 gains it** (that counter routed to `commentsOnly`; the marker arm stays by design). The SEAMCYCLE count was five (TOOL-12 omitted `livingContentRoster`), corrected in the comment. "
 "**COMPOSE-REPROOF-1, INTERIM (CONFIRMED so far):** the composition is BYTE-FAITHFUL — 21 file sets equal; five patches differ only by hunk-header line drift (239/540/285/623/502 added/removed lines identical); both two-lane files carry both lanes' rows; `valid: 194 packets (0 READY)`; the wiring census verified; the scanner `1964 finding(s), exactly matching`; writer-reach 0; goldens and the frozen inventory byte-identical; eslint bare over the union of 100 files, 0 errors (the count asserted via `--format json`). **`tests/lint` WHOLE at the composed tip: 175 files / 2,818 tests, ZERO failures** — every composed lane carried one red there on its own branch (the stale census); with the seventh refreeze the directory is clean, 175 = 174 + FIX-P4's walker. THE PARKED FILE NAMED: `tests/lint/embeddedMapConsoleGate.walker.test.js` (FIX-P4's) — `TEST_TABLE_UNPROVEN:test.each()` ×3 because `test.each(MUTED_CHANNELS)` passes an Identifier where `staticTableRows` requires an `ArrayExpression`; the park is the WALKER'S GRAMMAR, not a defect (the same verdict recorded for a sibling at `:4332`; the file runs 16/16) — TWO CORRECTIONS OWED: FIX-P4's receipt claim ('not a parking hazard, 4 suites / 16 tests') is REFUTED by execution (its contribution is 0/0), and the refreeze's reconciliation was right in total but wrong in route (−8 titles / −2 suites = the parked walker −16/−4 plus an undeclared +8/+2 on `postGenCoach.test.jsx`); the seventh refreeze itself EXACT by three independent derivations. ⛔ **A NEW HAZARD: `eachOnly` sits at 111 OF 111 and `literalTableStillParked` at 50 OF 50** — both monotone-down ceilings have zero headroom after FIX-P4's file took the last slot; the next created test file parking on an `each` shape reds `tests/lint` → **FIX-P4b's brief gains the cure**: rewrite `test.each(MUTED_CHANNELS)` as a literal table or a body loop so the file is CREDITED (`parked` −1, `eachOnly` 111 → 110); a zsh false green caught and recorded by the lane (`set -- $p` did not word-split). The 18-directory chain continues. "
 "**EM-R0a PAUSED AT THE GATE** (seal exit 0; sealDigest `981c3b39…e10d`; the preamble measured `c9f33c8d…6675` = the header stamp; `retiredSymbols` `[]`; nothing written to the worktree yet — batch 1 is the clean-tree red proof; its harness confirmed every sealed row: 63 collections = 48 KEYED + 15 ATOMIC, 572/572 mirror chips, `history.age === history.founding.age` 63/63; `classifySource` over the emitted walker PARK REASONS `[]`, 7 titles / 1 suite — the lighting delta MEASURED, not predicted) → the chair handed it the gate. Its two notices: §12's 'NAMES EXACTLY THESE THREE PATHS' stale against §7's six → the flip clause records it; the register draft 139 effective lines vs §7's predicted 164 (the ≤ 210 bound holds) → noted. "
 "**THE GATE:** shared tier = COMPOSE-REPROOF-1 · EM-R0a · FIX-T2 (handed the gate: its unedited `significanceMigration` run first); FIX-B2's builds done (its walker run finishing); queue = FIX-D9 (after its retirement commit) → TOOL-19 → TOOL-15 → TOOL-22 → TOOL-24 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents; CURE-J running the door (the gate granted). THE NEXT COMPOSITION (after EM-R0a lands, in this order): CURE-K (`3e9a6c261`) → the shift record (`3484b8c24`) → CURE-J's commit 2 → FIX-B2 (3) → FIX-T2 → FIX-D9 (3) → TOOL-19 → TOOL-15 (2) → TOOL-22 → TOOL-24 (3) as each lands; then the eighth refreeze and RUN 23.")
line = ("- **§934.47 addendum 98 — ⭐⭐ THE OWNER'S STANDING SIGNATURE GRANT ('I sign everything … now or in the future') RECORDED AND USED: §934.64/65/66/68/69/70/71/72 SIGNED (the shift record committed `3484b8c24`; CURE-J runs the door; FIX-D9 retires `foldTradeCategories`; FIX-P1c); THE PUSH STAYS THE OWNER'S WORD. RUN 22 RED ON FIVE (the provenance title + FOUR edge-shared staleness reds from FIX-P5's F14 input change) → CURE-K (`3e9a6c261`) AND THE LAW; FIX-B2 COMPLETE (38 → 5 importers; −34,714 B; +35,079 B headroom); COMPOSE-REPROOF-1: THE COMPOSITION BYTE-FAITHFUL, `tests/lint` 175 / 2,818 ZERO FAILURES, THE PARKED FILE NAMED (FIX-P4's walker, the grammar's), `eachOnly` AT ITS CEILING → FIX-P4b's cure; EM-R0a AND FIX-T2 HANDED THE GATE (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 97 —"; assert u.count(key) == 1 and "addendum 98 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 98" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the owner's standing signature grant; CURE-K; the second composition's order (ODQ §934.47 addendum 98)\n\n"
      "- **The owner's standing signature grant (12:2x) executes every open signature point:** §934.71 through the door (CURE-J's lane); §934.70 through FIX-D9 (retire `foldTradeCategories.js`; the trio dark); §934.72 + §934.66 through FIX-P1c; §934.68's two raises ratified (FIX-B3 records it in the header); §934.64, §934.65, §934.69 closed as recommended. The push chain is not a signature and stays the owner's explicit word.\n"
      "- **CURE-K:** the edge-shared bundles regenerated at the composed tip (FIX-P5's F14 changed an input); LANE-PARALLEL gains the input law; composed after EM-R0a lands.\n"
      "- **TOOL-17's brief re-cut:** the ratchet freezes the importers that reach an engine member by a STATIC EDGE; Rollup grouping artifacts (`generateWorldBook`) are admitted by name, never counted.\n"
      "- **TOOL-20 gains:** `negativeAssertionAnchor.walker`'s matcher counter routed to `commentsOnly` (a comment naming a matcher must not convict).\n"
      "- **FIX-P4b gains:** rewrite `embeddedMapConsoleGate.walker.test.js`'s `test.each(MUTED_CHANNELS)` as a literal table or body loop so the file is credited (`eachOnly` 111 → 110; `literalTableStillParked` 50/50 watched).\n"
      "- **The second composition's order (after EM-R0a lands):** CURE-K → the shift record → CURE-J commit 2 → FIX-B2 (3) → FIX-T2 → FIX-D9 (3) → TOOL-19 → TOOL-15 (2) → TOOL-22 → TOOL-24 (3); then the eighth refreeze and RUN 23.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 98:", io.open(ODQ, encoding="utf-8").read().count("addendum 98 —"), "| charter amended")
