# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**COMPOSE-REPROOF-1 COMPLETE — GREEN EXCEPT THE NAMED EXPECTED RED:** 18 invocations, every one with a printed count: **2,323 test files passed (+7 skipped), 29,386 tests passed, 119 skipped, exactly 1 failed** — `tests/property/dossierProseManifest.test.js`'s provenance title, proved INHERITED (the diff over the arm, its three recorder files and the golden across the range is EMPTY; cured on CURE-J's branch, composing next); `tests/lint` 175/175 · 2818/2818 (green whole for the first time since the sitting); `tests/lib` 174/1797, `tests/ui` 162/1076, `tests/pdf` 46/458, `tests/map` 34, `tests/security` 77 reproduce their lanes' declared lines digit for digit; `tests/domain` whole 986 / 16,653; `tests/build` 419 passed | 119 skipped (538 — EM-B1f's landing population; the skips are the dist arms on a tip with no build); `valid: 194 packets (0 READY)`; the census verified; the scanner exactly matching; writer-reach 0; eslint 100 files / 0 errors; goldens and the frozen inventory byte-identical. THE FIRST COMPOSITION IS VERIFIED. Its three findings recorded: the seventh refreeze's note routes the −8/−2 wrongly (two undeclared FIX-P4 movements, not one file — the figures exact); `eachOnly` 111/111 and `literalTableStillParked` 50/50 (FIX-P4b's commit 3 buys one back); FIX-P4's receipt claim refuted (the kit's copy annotated). "
 "**THE SECOND COMPOSITION'S DRY RUN at 680eacb8d:** 9 of 10 known commits apply clean (CURE-K; CURE-J's three; FIX-B2's three; FIX-T2's two); **FIX-P1c (`5fbe2d82c`) conflicts in `src/components/generate/LayeredConfigurationPanel.jsx`** with FIX-P3's composed panel change — the lane predicted a clean apply and was wrong; by the composition law (addendum 94) FIX-P1's own lane composes it in the slot, keeping both hunks with two-parent diffs as the proof; `vite.config.js` is touched by three commits (all FIX-B2's) and `vendorPdfLazy.test.js` by two (the same lane) — no cross-lane file. "
 "**FIX-P4b PAUSED, three commits authored and measured:** the phantom `pipelineReveal` flag DATED by receipt — deleted in `78699c6799` (2026-05-29, 'Phase 123 — Flag burn-down'); THREE comments corrected, not two (a third at `GenerateWizard.jsx:525` that never names the token — invisible to `git grep pipelineReveal`); comment-only proved at the code level (esbuild-stripped output byte-identical on all three). The console class: the brief's 49/18 were NARROWER than the truth — 98 unguarded calls across `public/map`, 19 in our four files, three already gated by the fork's `DEBUG.<key> &&` idiom, so 16 genuinely open: 4 channelled through the F15 guard (succeeding operations), 12 kept with a one-line reason (catch blocks whose only other trace is a swallowed `_error`); the walker widened (arms 8/9/10; a second control proving the classifier catches a bare call, a wrapped marker and a reasonless marker); scope verified (all four are `<script defer>` in document order — `load.js` already relies on it 31 times). The park CURED with the walker's own predicates: `parkReasonsFor → []`, `eachOnly` 111 → 110, `literalTableStillParked` held at 50 (the inline-literal reformat avoided). TWO CORRECTIONS to the chair's expectation, measured: the lighting delta is `0 · −1 · +1 · +13 · +5` (the +16 was a RUNTIME row count; the census counts static titles: the parking cure credits 10/4, commit 2's arms +3/+1); the node driver reproduces the frozen register exactly at its base. Its item → **FIX-P4c chartered** (two further fork-owned files with one unguarded console call each: `public/map/modules/ui/layers.js`, `notes-editor.js`). "
 "**TOOL-25 STOPPED, THE BRIEFED PREMISE REFUTED — AND A SHARPER TRUTH:** `tests/lint/controlBytes.test.js` walks `src` AND `tests` (all extensions, whole-C0) and is GREEN at the base (5,063 files, 1,513 ms) — so `src/lib/anonForkSalt.js` WAS in scope, and FIX-P1b's NUL escaped because THAT LANE NEVER RAN `tests/lint` WHOLE (a src-only edit under `src/lib` with focused `tests/lib` runs): the gap is PROCEDURAL. Tree-wide there are exactly THREE NUL carriers, one idiom (a raw NUL as a composite-key separator in a template literal): `src/domain/worldPulse/supplyCompleteness.js:158` (allowlisted, the owner's keep-vs-convert parked 'at the master merge'), `scripts/prose-wave-gate.mjs:753` (unscoped), and `docs/implementation/packets/settlement-editor/EM-P2.md:333` — the packet DOCUMENT's fenced listing (EM-P2 has LANDED; its landed tests do NOT carry the byte, the walker being green — the carrier is the record's file). `git grep -E '\\x00'` MATCHES THE TEXT, NOT THE BYTE (proved on a fixture repo; `-P` matches the byte) → LANE-PARALLEL. RULED (vetoable): DOC-4 chartered (the chair replaces the raw byte in EM-P2.md's listing with the `String.fromCharCode(0)` spelling and a note — a landed record annotated, its meaning unchanged); TOOL-25 converts `prose-wave-gate.mjs:753` and, by the chair's explicit one-line exemption from its no-src law, `supplyCompleteness.js:158` (the owner signed everything — the same string by construction; goldens byte-identical prove it; the allowlist row and its stale comment deleted, shrink-only); the four scoping forks: `git ls-files -z` (never a filesystem walk); the existing whole-C0 predicate stays on `src`/`tests` and a NUL-only arm covers the rest (vendored `jszip.min.js`'s 0x01–0x06 lawful); text-ness by `.gitattributes` first (132 SVGs join), the extension list only for undeclared paths; `*.glb binary` declared for the 25 undeclared. ⭐ **A NEW LANE LAW (the procedural gap closed): every lane that touches `src/` or `tests/` runs `tests/lint` WHOLE once before its commit — the walkers govern the whole tree, and three of today's instrument reds were files a focused batch never showed a walker** (written into LANE-PARALLEL and LANE-EM-BUILD this sitting). **FIX-D6 and FIX-W1 BRIEFS WRITTEN** (§934.65 signed; through the door with their own shift records; FIX-D6 after TOOL-8a composes; FIX-W1 at any tip) — 62 launch briefs. **FIX-P9 DISPATCHED** at 578272a99 (the free seat). SEATS: working = FIX-C2c · PREPROOF-EM-R0d-v4 · TOOL-25 (resumed) · FIX-P9; gate = EM-R0a (its sealed verbs) · FIX-D9; queue = TOOL-19 → TOOL-15 → TOOL-22 → TOOL-24 → FIX-P4b → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents.")
line = ("- **§934.47 addendum 104 — COMPOSE-REPROOF-1 GREEN EXCEPT THE NAMED RED (2,323 files · 29,386 tests · exactly 1 failed, inherited) — THE FIRST COMPOSITION VERIFIED; THE SECOND'S DRY RUN 9 OF 10 (FIX-P1c by its lane); FIX-P4b PAUSED (the phantom flag dated; 98 console calls measured, 16 open; the park cured, `eachOnly` 111 → 110); TOOL-25 STOPPED ON A REFUTED PREMISE — `controlBytes` WALKS `src` ALREADY, THE GAP WAS A LANE THAT NEVER RAN `tests/lint` WHOLE → A NEW LANE LAW; THREE NUL CARRIERS RULED (DOC-4; the owner's parked one converted under the grant); FIX-D6 + FIX-W1 BRIEFS; FIX-P9 DISPATCHED (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 103 —"; assert u.count(key) == 1 and "addendum 104 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 104" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the first composition verified; the lane law; FIX-P4c and DOC-4 chartered (ODQ §934.47 addendum 104)\n\n"
      "- **Lane law:** every lane that touches `src/` or `tests/` runs `tests/lint` WHOLE once before its commit (the walkers govern the whole tree; a focused batch never shows them the file).\n"
      "- **FIX-P4c (NEW; after FIX-P4b composes):** the two fork-owned files with one unguarded console call each (`public/map/modules/ui/layers.js`, `notes-editor.js`) under the widened F15 walker.\n"
      "- **DOC-4 (NEW; the chair's, at a docs sitting):** `docs/implementation/packets/settlement-editor/EM-P2.md:333`'s raw NUL byte in a fenced listing replaced by the `String.fromCharCode(0)` spelling with a note.\n"
      "- **TOOL-25 (re-cut):** extend `controlBytes.test.js` (NUL-only tree-wide over `git ls-files`, `.gitattributes` first; the whole-C0 predicate stays on `src`/`tests`); convert the two script/src carriers; `*.glb binary` declared.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 104:", io.open(ODQ, encoding="utf-8").read().count("addendum 104 —"), "| charter amended")
