# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**FIX-P5 COMPLETE on `fix-floors-labels-2026-09-20`** (base 63e40fe57; five commits `e207d0718` · `881c84863` · `5c29fef92` · `a5575107a` · `ec7d8a363`; tree clean): four red-first proofs convicting by exact file and line (`PricingBands.jsx:141 12px`; `viewModel.js:58 thorp = \"Thorp\"`; `ResourcesTab.jsx:94 \"UNEXPLOITED\"`; the bar's `flex` arithmetic), each plant restored byte-identically; greens `tests/ui` whole 162/1076, `tests/pdf` whole 46/458, `tests/copy` 13/155, `tests/lint` whole on the final tree 2778/2779 (the lighting red alone), voiceMechanics 30, negativeAssertionAnchor + mutationCoverageManifest green, eslint over 26 files; both goldens byte-identical. LIGHTING isolated from the base's own drift: files +1 · parked +0 · credited +1 · titles +16 · suites +3 (composed at the terminal). Three of its own defects on the record rather than quietly fixed (a guessed floor; an un-anchored negative; `e207d0718` shipped a red walker that `881c84863` closes by name). ITS TWO OWNER ITEMS: **F7 sharpens §934.64** — a 12 px face does NOT fit the painted slip (at 375 the plate is 83.92 × 22.47, the slip's content box 38.92 × 9.89; a 12 px line on `lineHeight: 1` misses by 2.11 px, and misses at 320, 391 and 430 too; §934.26's executed exception reds if a re-cut ever makes it fit) → the choice is re-cut the plate or accept 10 px on a paid 44 × 44 target — the chair's recommendation stands (keep 10 px; the plate is the owner's painting); noticed 5 is REFUTED (the exclamation sits in the copy registry at `en.js:496`, `voiceMechanics` scans it, it carries a count-pinned Tier-1 exception, and §934.26's addendum rules the owner's verbatim order stands) → CLOSED. ITS SEVEN ITEMS FATED: (1) the taste-approved sample still draws `†` (`PricingSample.jsx`) → FIX-P9 (the tier-word/label family) checks it against the shipped registry; (2) the Compendium's byte-pinned tier label and (3) the gallery's `capitalize` → FIX-P9 (chartered at addendum 86; the lane's executed census rows stand guard); (4) five prose-shaped 12–13 px lines on lane 28's surfaces (`src/App.jsx:916`, `:946`, …), (5) `phoneChromeFloor`'s `/create` and `/settlements` rows stale against 63e40fe57, (6) `WizardOutputToolbar` pinned sticky at `HEADER_H` (22.47 px at 375) under the painted header, (7) `dossierPhoneFloorAllViews.test.jsx` cannot see `/pricing` → **FIX-P10 chartered** (the phone-floor family's leftovers; after FIX-P5 composes; measure-first, register rows re-measured shrink-only). THE GATE: FIX-P5 done → **FIX-P1b handed the gate** (the hand-off text the kit owed: the `FORK_SUFFIX_MAX` pin accepted; `ACCOUNT_DIGEST_HEX` flipped to 12 first, ungated; one commit by pathspec); shared tier = EM-B1f (batch 4) · FIX-C2b · FIX-P1b; queue = FIX-B2 (exclusive, alone when the tier drains) → FIX-D9 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents. THE COMPOSITION SITTING'S ORDER gains FIX-P5's five commits after FIX-P4's two.")
line = ("- **§934.47 addendum 89 — FIX-P5 COMPLETE (five commits; four red-firsts by exact site; F7 sharpens §934.64 — 12 px cannot fit the painted slip; noticed 5 refuted); ITS SEVEN ITEMS FATED (FIX-P10 chartered); FIX-P1b HANDED THE GATE (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 88 —"; assert u.count(key) == 1 and "addendum 89 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 89" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — FIX-P5 complete; FIX-P10 chartered (ODQ §934.47 addendum 89)\n\n"
      "- **FIX-P5 is complete on its lane** (`e207d0718`, `881c84863`, `5c29fef92`, `a5575107a`, `ec7d8a363`); composed after FIX-P4 at the composition sitting.\n"
      "- **FIX-P10 (NEW; after FIX-P5 composes; measure-first):** the phone-floor family's leftovers — five prose-shaped 12–13 px lines on lane 28's surfaces (`src/App.jsx:916`, `:946`, …); `phoneChromeFloor`'s stale `/create` and `/settlements` rows re-measured shrink-only; `WizardOutputToolbar`'s sticky offset against the painted header's real height; `dossierPhoneFloorAllViews.test.jsx` extended to `/pricing`.\n"
      "- **FIX-P9 gains:** the taste-approved sample's `†` (`PricingSample.jsx`) checked against the shipped registry.\n"
      "- **§934.64 sharpened by measurement:** 12 px cannot fit the painted slip at any phone width (misses by 2.11 px at 375); the chair recommends keeping 10 px.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 89:", io.open(ODQ, encoding="utf-8").read().count("addendum 89 —"), "| charter amended")
