# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**FIX-P1b COMMITTED `92e959285` on `fix-fork-salt-2026-09-20`** (over e0b03b63a; 5 files, +227/−20; `tests/lib` WHOLE 174 files / 1,797; data 22; components 2; store 6; domain 15; lint instruments 22; voiceMechanics 30; eslint bare 0; goldens byte-identical; the register untouched). THE LANE'S JUDGMENT, ACCEPTED (vetoable): the ordered flip `ACCOUNT_DIGEST_HEX` 8 → 12 ALONE would have been COSMETIC — `fnv1a32` is a 32-bit hash, so twelve hex characters carried thirty-two bits (`00000905f093`) and the collision rate stayed at ~77,000 accounts; the obvious repair `fnv1a32(id + domain)` is length extension (measured: `acct-d36f` and `acct-bb799` collide with and without the appended domain; over 400,000 UUIDv4 ids 22 collisions at eight characters AND 22 at twelve); PREPENDING the domain decorrelates the rounds (the same pair diverges; 27 collisions at 8 hex ≈ the birthday expectation of 18.6, ZERO at 12) — so the commit is a widened HASH, not a widened field; a walker executes `fnv1a32` on the pinned pair and asserts the separation lives in characters 9–12; the hash is the estate's own (`kernel/proseHash.js#fnv1a32`, synchronous — both doors resolve inline and `crypto.subtle.digest` is a Promise). THE CHAIR'S REASON FOR ACCEPTING A DERIVATION CHANGE: nothing deployed carries the old digest — FIX-P1 (e0b03b63a) is on the same undeployed lane, so no persisted record is re-keyed and no migration is owed; §934.66 (deterministic forks) stands as asked and is untouched by this. ⛔ A HAZARD NO INSTRUMENT CATCHES: the separator first landed as a RAW NUL BYTE and git classified `src/lib/anonForkSalt.js` as BINARY (`--numstat` printed `- -`; every future review would have read 'binary file differs') — caught by the lane reading its own staged diff; rebuilt with `String.fromCharCode(0)` → **TOOL-25 chartered** (a walker: no tracked text file contains a NUL; measure-first over the tree) and memory fold 112 gains the line. LIGHTING: the walker evaluated ONE figure (`files = 2652`, the base's register 2650; +1 is FIX-P1's new test file; P1b adds none); derived and labelled: cumulative +1 · +0 · +1 · +27 · +5 against its proved-green base `2651·383·2268·25034·6678` — the sixth refreeze attributes three movements separately. ITS ITEMS FATED: the NUL class → TOOL-25; `SeedField` has no `maxLength` (the address pin is anchored on the module's declared width) → **§934.72 asked at the owner's leisure (recommend: `maxLength` = the declared width; a product-surface field limit is the owner's)**; `ANON_SALT_HEX` and `ACCOUNT_DIGEST_HEX` are both 12 but reached differently (a random UUID slice vs a two-round digest) → CLOSED with reason, recorded so nobody collapses them. "
 "**TOOL-19 PAUSED WITH ITS CURE PROVED ON FIXTURES:** the validator's non-terminal retiree arm now consults the packet's own dispatch seal from `<gitDir>/implementation-sessions/<ID>/seal.json` (the envelope's `integrityDigest` recomputed; `payload.id`, `payload.gitDir`, `payload.head` checked): absent with no seal → the old refusal byte for byte; absent under a live seal whose bound HEAD is an ancestor → valid with a printed note; a stale seal → refused with its own HEAD named; the lookup runs only on the error path (a green tree spawns no git). States (a)/(b)/(c) reproduced before (0 / 1 / 1 — the defect) and after (0 / 1 / 0 with the note); FIVE counterforces refused (a forged non-ancestor HEAD; a HEAD naming no object; a payload edited after sealing; another packet's seal; another worktree's seal), each proved twice — on the harness fixture and against a seal minted by the shipped writer `createImplementationSession`; `validate:packets` identical before and after; one sentence in the standard's lifecycle section; one new `it`. TWO THINGS ON THE RECORD: the cured arm has an EMPTY live population (zero non-terminal packets carry a `retiredSymbols` row today — 21 rows, all terminal), and `git merge-base --is-ancestor c33446830 c127cdfb2` exits 0, so EM-B1f's real seal WOULD have licensed its burn at this tip had the row survived. DESIGN NOTE ACCEPTED: the seal exemption is WORKTREE-LOCAL by construction (a packet left READY with a burned retiree still reds `validate` from the consist, another lane, or CI) — the correct scope; the charter's landing order gains the sentence (below). "
 "**FIX-T2's CORRECTION, ON THE RECORD:** its 'significanceMigration is red at base' claim is WITHDRAWN by its own re-measurement — `FAMILY_HOME` (`:55`) IS `bandFamilies.js`, the very file it accused, and the census excludes it at `:88`; class A 40/20, B 5/3, C 2/2 exactly on their pins, raw equal to comment-stripped; GREEN at base, reconciling with run 21's single red; its step 1 flipped to expect GREEN with a STOP if red; the sweep ledger now 7 in the class, 5 cured (2 live: loadingNarration, rawButton), 2 left; 51 local strippers / 27 string-blind / 11 also trailing-blind; the reciprocal cross-reference sentence in CURE-J's `dossierManifest.js` header is owed at composition (a recorder file — TOOL-20's first act; comment edits no longer move the identity). The lane's `git stash list` read (read-only, once) recorded, not repeated. "
 "**SEATS:** working = TOOL-15 · TOOL-22 · TOOL-24 (all at c127cdfb2) · (FIX-D9, FIX-T2, TOOL-19 paused); gate = EM-B1f (its resume chain's last vitest step; the commit of all thirteen §7 paths next — the chair's 'six' withdrawn, §7 is the sealed authority and STOP 9 requires the seven `_shared` artifacts); FIX-P1b done → when B1f's chain ends the shared tier is EMPTY and **FIX-B2 runs ALONE** (exclusive); then FIX-D9 → FIX-T2 → TOOL-19 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents. THE COMPOSITION DRY-RUN: the six finished lanes' 19 commits (L1 2 · P3 5 · P4 2 · P5 5 · C2b 4 · 13b 1) cherry-pick CLEANLY in the planned order onto c127cdfb2 in a throwaway worktree (removed); two files touched by two lanes (`tests/components/phoneChromeFloor.census.test.js`, `scripts/mutation-coverage-manifest.json`), no conflict; re-probed after B1f's commit. FIX-P1b's `92e959285` joins the order after FIX-P5. BRIEFS WRITTEN this hour: FIX-C2c, TOOL-22 (dispatched), TOOL-23, FIX-B3, TOOL-24 (dispatched), FIX-P9, FIX-P10 — 53 launch briefs.")
line = ("- **§934.47 addendum 92 — FIX-P1b COMMITTED (`92e959285`): THE ORDERED 8 → 12 FLIP WAS COSMETIC ON A 32-BIT HASH, SO THE LANE WIDENED THE HASH (the domain PREPENDED; 0 collisions at 12 hex over 400,000 ids) — ACCEPTED, nothing deployed carries the old digest; A RAW NUL MADE GIT CLASSIFY A SOURCE FILE AS BINARY → TOOL-25 CHARTERED; §934.72 ASKED (`SeedField` maxLength); TOOL-19 PAUSED WITH ITS CURE PROVED (five counterforces); FIX-T2's RED-AT-BASE CLAIM WITHDRAWN BY ITS OWN RE-MEASUREMENT; THE SHARED TIER DRAINS TO FIX-B2 (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 91 —"; assert u.count(key) == 1 and "addendum 92 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 92" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — FIX-P1b's judgment; TOOL-25 chartered; the seal exemption's scope (ODQ §934.47 addendum 92)\n\n"
      "- **FIX-P1b** (`92e959285`) composes after FIX-P5: the account digest is a two-round `fnv1a32` with the domain PREPENDED (a widened hash, not a widened field); accepted because nothing deployed carries the old digest (FIX-P1 is on the same undeployed lane) — a derivation change on a DEPLOYED digest would be the owner's migration.\n"
      "- **TOOL-25 (NEW; measure-first):** a walker that no tracked text file contains a NUL byte (git classifies it binary and every review reads 'binary file differs'; no instrument catches it today).\n"
      "- **The landing order gains one sentence (TOOL-19's scope):** the validator's seal exemption for a burned retiree is WORKTREE-LOCAL — a packet left READY with a burned retiree still reds `validate` elsewhere; the row turns lawful under the LANDED arm at the flip, so the flip follows the landing without an intervening placement.\n"
      "- **§934.72 (owner):** `SeedField`'s `maxLength` — recommend the module's declared width.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 92:", io.open(ODQ, encoding="utf-8").read().count("addendum 92 —"), "| charter amended")
