# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**CURE-J CLOSED GREEN — run 21's one red is cured on its branch:** `tests/property/dossierProseManifest.test.js` + `generatorGoldenMaster.test.js` `2 passed (2) · 20 passed (20)`. THREE commits over commit 1 (`9ee0be7e9`): `4416e8f9d` (the signed record cherry-picked), `efc4ecf49` (`MANIFEST_PROVENANCE` amended — a separate commit because `recordGolden` REFUSES a tree dirty beyond `[register, fixture, record]` and the script is none of the three: the provenance amendment must be COMMITTED before the door can run — a door law for every future re-record), `b077f6e79` (the re-record). THE DOOR, exact verb (`goldenRecordDoor.js:46`): `GOLDEN_SHIFT_SIGNED=docs/shift-records/2026-09-20-cure-j-provenance.json node scripts/prose-manifest-cells.mjs --record` — it verified the record's content, refused nothing, wrote fixture and register in ONE act and threw by design (EXIT 1: 'golden RE-RECORDED … action re-record, row §934.71. sha256 921c51cf…db41 → 88983938…4084; rows 2 → 2'); the lane read the record whole first and confirmed it was cut for CURE-J's cause, not reused. RE-VERIFIED ON THE WRITTEN BYTES: rows byte-identical, `rowsSha e972c0d0…2559` unchanged, 1050 → 1050, 0 moved / 0 added / 0 removed; `shift`, `ruling`, `car` held; only `recordedOverSha`, `note`, `recorder` moved; the register moved by the door alone (`ownerRow §933 → §934.71`; `rows 2 → 2`); no hand edit. ONE HONEST DISCREPANCY: the dry run predicted the whole-file sha `0f64dbd8…879a`, the door wrote `88983938…4084` — the cause is provenance bytes (`recordedOverSha` from the dry `c33446830` to the full tip; the `note` gained the record's path), not a row; the machine-checked prediction (`predictedRows` 2 → 2) held. Gates: 20 · 109 (goldenFreeze + two standing walkers) · 79 · 51 · 30; eslint 0; the control golden byte-identical; `commitTrailerRefusal` null; lighting +2 titles (commit 1's), not refrozen. THE SECOND COMPOSITION'S ORDER RE-CUT: the cure-j branch's THREE commits (`4416e8f9d` `efc4ecf49` `b077f6e79`) compose in place of the consist's record commit `3484b8c24` (the same record content; the lane's chain carries the door's writes). "
 "**FIX-D9's RETIREMENT APPLIED** (§934.70 under the grant): ten staged paths, +579/−109 — `src/domain/region/foldTradeCategories.js` (44 lines), `tests/domain/foldTradeCategories.test.js` (1 suite / 7 titles, the one asserting the dead copy) and the excision row at `vite.config.js:177` removed (the excision list 18 rows with 1 no-op → 17 with 0); the doc row RETIRED with addendum 98 named; the walker's RETIRED-means-ABSENT arm added; the dark trio untouched; goldens byte-identical; the observed-shape register EXIT 0 and byte-identical. ONE CATCH THAT WOULD HAVE RIDDEN THROUGH THE GATE: its first `vite.config.js` note was 7 lines replacing 1 and shifted `testTimeout` from `:912` to `:917` — two files cite `vite.config.js:912`; the citation detector saw it (`codeSym 3 → 5`) but that arm is REPORT-ONLY, so it would have passed green — cured by a one-line-for-one-line edit (net zero; `codeSym` back to 3; the diff 1 insertion / 1 deletion) → the law: a line-addressed citation into a config file rots on any insertion above it (TOOL-15b / FIX-C2c's family). TWO CONFIRMATIONS BY THE CHAIR: the `customContentSchema.js` header re-measured 8 → 7 importers STAYS (a comment its deletion falsified; TOOL-12's item-2 class); the relayed authority is the chair's to own — the owner's words are on the ledger verbatim and in the door-accepted record; the lane's doc row records it as the chair's vetoable use (the right shape). Its gate now: `tests/lint` whole, `tests/build` whole (the config moved), `tests/domain` whole (a file left it), the three-way counterforce; lighting net 0 files · +1 suite · +3 titles. "
 "**COMPOSE-REPROOF-1, CONTINUING CLEAN:** `tests/components` 297 / 2,103 (every +17 attributable: P4's postGenCoach +8, P5's five arms +9, P1 net zero); `tests/copy` 13 / 155 (P5's 155, not P3's 151 — both lanes right at their own bases; P5's census file exists here); `tests/lib` 174 / 1,797 (FIX-P1b's line digit for digit). **FIX-B2's LAST LINE:** the walker `2656·383·2273·25074·6684` delta `0·0·0·0·0` measured (both homes parked under `describe.runIf`, as predicted); `tests/lint` 174 / 2,791 at its base. **THE CHAIR'S BUILD AT THE COMPOSED TIP (+CURE-K):** `✓ built in 17.90s`, `STRICT DIST OK — 59 files, 538 tests`, `dist-measure exit 0 at 12:26:03` — the composition's src moves pass the dist budgets (CONFIRMED). SEATS: gate = EM-R0a · FIX-T2 · COMPOSE-REPROOF-1; queue = FIX-D9 → TOOL-19 → TOOL-15 → TOOL-22 → TOOL-24 → FIX-K1 → TOOL-7a → TOOL-9 → TOOL-8a → FIX-P2 → FIX-D7 → FIX-T1 → FIX-D8 → the dead agents; FIX-P1c working. FIX-L3's brief written (58 launch briefs; every charter now has one except TOOL-15b/TOOL-20/TOOL-21's dependents, which do).")
line = ("- **§934.47 addendum 99 — CURE-J CLOSED GREEN (the owner-signed door re-recorded the golden with every row byte-identical; three commits; a door law: commit the provenance amendment before the door runs); FIX-D9's RETIREMENT APPLIED (the excision list 18 → 17 with zero no-ops; a net-zero config edit kept two line-addressed citations true); THE RE-PROOF CLEAN THROUGH `tests/lib`; FIX-B2's LIGHTING DELTA ZERO; THE COMPOSED TIP'S BUILD GREEN (STRICT DIST OK 538) (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 98 —"; assert u.count(key) == 1 and "addendum 99 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 99" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — CURE-J closed; the second composition's order re-cut (ODQ §934.47 addendum 99)\n\n"
      "- **The second composition's order (after EM-R0a lands):** CURE-K (`3e9a6c261`) → CURE-J's three (`4416e8f9d` `efc4ecf49` `b077f6e79`, in place of the consist's record commit) → FIX-B2 (`5cc0e6c14` `2fa685264` `fd4be7c07`) → FIX-T2 → FIX-D9 (3) → FIX-P1c → TOOL-19 → TOOL-15 (2) → TOOL-22 → TOOL-24 (3) as each lands; then the eighth refreeze and RUN 23 (expected: no red).\n"
      "- **Door law (CURE-J):** `recordGolden` refuses a tree dirty beyond the register, the fixture and the record — a `MANIFEST_PROVENANCE` amendment is committed BEFORE the door runs; the door's own throw (EXIT 1, 'golden RE-RECORDED') is the success line.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 99:", io.open(ODQ, encoding="utf-8").read().count("addendum 99 —"), "| charter amended")
