# -*- coding: utf-8 -*-
"""ODQ §934.47 addendum 107 + the charter amendment: DOC-4 composed; FIX-D9's four composed by its lane; FIX-C2c and TOOL-19 closed;
TOOL-23's verdict → FIX-D10 chartered and §934.75 (the TE-STRIP tail) opened; FIX-P10's rulings; the instrument-cost law.
argv: stamp. Run in the ledger checkout after `git show HEAD:<path> > <path>`. Control characters spelled in words."""
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**DOC-4 DONE:** `6290f7a16` committed on the chair's detached consist head (EM-P2.md line 333's raw NUL → the two-character JavaScript escape + an annotation after the fence; numstat 3/1, the committed blob carries zero NUL; `valid: 195 packets (0 READY)`) and COMPOSED into the slot as `532ba71cc` (blob-equal, tree clean); TOOL-25 cherry-picked it into its branch so its walker lands with an EMPTY exemption register. "
 "**FIX-D9's FOUR COMPOSED BY ITS LANE in the slot:** `7fb4ba483` (the three dark density modules DARK-BY-DESIGN) · `3c9661c30` (`foldTradeCategories` RETIRED; the census regenerated through the `--dry`-then-write door to 1172 — the composed value, never hand-set) · `29df790ec` (the disposition walker, `tests/lint/deadCodeDisposition.walker.test.js`, 363 lines) · `48450e98c` (FIX-B2b: the two `:912` citers → `:1138`, the live line quoted first) — its composed-tip proofs running (eslint 0, census verified, `tests/lint` whole in flight). "
 "**FIX-C2c CLOSED GREEN** (`808837904` the instrument · `1f3029ffc` the PINNED-UNCOMMITTED strike · `2b03bc421` nineteen re-addressings over 15 files; `tests/lint` whole 1 failed / 2820 passed — the lighting walker at exactly its declared +3 titles; `tests/docs` 146/146; the four filesystem readers green; `valid: 194`; goldens byte-identical) — its first `tests/lint` run DIED with `FATAL ERROR: Zone Allocation failed - process out of memory` and printed no count line: the lane claimed nothing from it, found two defects in its own instrument (a document re-joined inside a match loop; 91,823 lines sentence-spanned for a set of ~169), cured them behaviour-identical (ARM 5 169 / 98 / 71 before and after), and the directory then completed in 353 s → THE INSTRUMENT-COST LAW appended to LANE-PARALLEL. "
 "**TOOL-19 CLOSED** (`a7da09382` the proof, RED alone by design and saying so in its subject · `928f2b86d` the cure + `PACKET_STANDARD.md`; B0 `1 failed | 124 passed (125)` → B1 `125 passed (125)`; five counterforces re-measured; the lighting walker's evaluated arms only — titles 25077 vs 25074, +1 its own; `valid: 194 (1 READY)` before and after). Its four handed-on findings SLOTTED: `authority.packetSha256` unread by the burn → TOOL-22's brief (the re-seal re-binds it and the burn arm compares it; counterforce: one rewritten packet byte refuses the burn); the `requiredSymbols` sibling arm's THIRD instance (EM-B1k2's `uncoveredBaseline: 186`) → TOOL-15's brief; `SEAL_ENVELOPE_SCHEMA_VERSION` duplicated against an import cycle, held by an assertion → CLOSED with reason (honest by assertion; the cycle is structural); `validate` spawning `git` once per packet on the error path → CLOSED (bounded). A CHARTER SENTENCE from its worktree-local scope: a seal licenses the retiree burn only in the worktree that dispatched it, so **NEVER PUSH WITH A PACKET READY** (a burned retiree on a pushed branch reds CI) — the landing order gains it. "
 "**BOTH DRY-COMPOSED CLEAN** onto the tip in throwaway worktrees (equal file sets, byte-equal blobs after the hook): the chair cherry-picks TOOL-19's two and C2c's three the moment D9's proofs land, then FIX-P1's cure. "
 "**FIX-P1c AT THE COMPOSED TIP — `tests/lint` whole 3 files / 4 titles red:** the lighting walker (+1 file, EM-R0a's — not P1c's), and `src/lib/anonForkSalt.js` reading `seed` on `config` — a key NO WRITER PRODUCES, a NEW observed-shape row at ceiling 0 (the chair reproduced it: `node scripts/check-observed-shape-readers.mjs` exit 1 at 5dd5e8e68 naming exactly that row) — P1c's own; its lane is curing on its branch ('measure the ceiling by running the real derivation, so `lib` never reads `config.seed`') and composes after D9. The composition-proof law worked exactly as written: a lane's own gate at its base was green; the composed tip convicted it. "
 "**TOOL-23's VERDICT (read-only; report + 249-row table in the kit):** the 248 reproduces as 249 at 5dd5e8e68 and 'unreachable from the seven Vite entries' is NOT 'dead' — **65 modules SHIP or are read by the typecheck** (five are the ENTRIES or inputs of the shipped Supabase Edge Functions bundles — `aiCharter.js`, `aiGrounding.js`, `aiOutputSchema.js`, `intentAtlas.js`, `contradictions.js`; 57 are the authoring source of 73 + 7 committed, served artifacts under `public/landing-maps/**` and the generated prose/compendium/CSS; three are pinned by JSDoc `import()` type edges Rollup erases and `tsc` resolves — `pulseShapes.js` 23 consumers, `types.js` 16, `importReconciliationTypes.js` 2), 140 are ORACLE-INSTRUMENTS measuring shipped behaviour, and the genuinely retirable population is **44 modules · 291,756 B · 3,244 effective lines · 25 test files · 2 plant rows (7.1% of the roster's mass)**, of which exactly 8 have no consumer of any kind; the price of one retirement measured from `git show --stat 3a5618ed8` (module + test + excision row + one census counter; the OSR baseline NOT moved — the largest apparent cost removed from all 247 OSR-carrying rows); the three cheapest safe retirements named (`deitySnapshot.js` a proven SUPERSEDED shim 295 B · `components/organic/index.js` a dead barrel · `hooks/usePosture.js` zero references and a false self-claimed importer); ESD/eager with all unreachable generators skipped 51 → 49, 269 → 267 (`cohesionWeave.js` is an edge-bundle input and stays); the seven register-moving or owner-gated rows named LAST (`usePricingMoment.js` PAID SURFACE — an OWNER-VERIFY hold, not proposed; `computeNetworkEcho.js`; `InteriorView.jsx`; `edgeAnnotations.js`; `tabPalette.js`; `regionWakeReplay.js`; `heraldIndex.js`). → **FIX-D10 CHARTERED** (brief written; AFTER RUN 23 at a clean tip) under four rulings: R1 THE INSTRUMENT BEFORE THE KNIFE (the walker learns the three edge classes with executed counterforces before any retirement — TOOL-23's item 1, and the disposition doc's own proposed ratchet re-cut to it, item 4); R2 RETIRE ONLY WHAT NO DESIGN DOC CLAIMS (a TEST-ONLY-FIXTURE module named by a live design doc is KEPT with `BUILT, UNMOUNTED — awaiting <doc>`; the un-mounted feature set is the owner's future until a document says otherwise); R3 THE SEVEN NAMED LAST STAY, headed with their registers; R4 THE TE-STRIP TAIL IS AN OWNER DECISION POINT. TOOL-23's twelve items each slotted in the brief (the certification tree's `@non-product` note; `worldPulse/index.js` TEST FACADE; the tuning-inventory's shrink-only/frozen question measured first; `computeNetworkEcho.js`'s standing plant landed if eligible — no phantom lane; `dossierCausalProse.generated.js`'s producer named by execution; items 11–12 recorded). "
 "**§934.75 (NEW, the chair's recommendation attached):** `src/lib/townScene/**` (5 modules, 34,596 B — the client, cache, view policy, adaptive quality and export of the legacy settlement map that TE-STRIP-1/3 took off the website on 2026-08-29) is unreachable while `townScene.worker.js` and `townSceneExport.worker.js` are STILL two of the seven build entries: a half-finished strip or a live surface with a dead front door. The chair recommends FINISHING THE STRIP (the two worker entries and the five clients retired together, the map-doors design left as the document that would bring a map back) and does not execute it: it is a product surface's return path, the grazing rule. FIX-D10 headers the five `STRIPPED CLIENT — TE-STRIP tail, §934.75` and touches nothing else there. "
 "**FIX-P10 (paused at the gate; rulings issued):** commit 1 done (five prose-shaped 12–13 px lines re-located by content and cured; `App.jsx 0→2`, `HomeHero.jsx 2→4`, `ClerkNote.jsx 0→1`, `bare 0`; the chrome roster and route baseline proved immovable by construction); commit 2 has THREE stale rows not two (`/signin files 11→13` from REVIEW-P F10's mount) — cure all three; commit 3's premise REFUTED and its operative condition confirmed: `HEADER_H` IS the painted height and the toolbar already pins there — the overlap is the 44-px PADDED TOUCH TARGET anchored at y 0 hanging 24.83 / 21.53 / 20.57 / 18.24 px below the header at 320 / 375 / 391 / 430 inside `z-index: 50`, so the Back button's top 6–13 px is an invisible Home button → CURE ACCEPTED (`TOUCH_TARGET = 44` exported from the pure leaf `arrowGeometry.js`, `ArrowHeader.jsx` imports it, the toolbar pins at `max(HEADER_H, TOUCH_TARGET)`; the DECLARED desktop change of 3.19–11.35 px accepted because the 44-px target hangs below the 40.81-px header on desktop too — the honest geometry, not a phone patch; one addition: the seam between HEADER_H and 44 on desktop is pinned opaque in the toolbar's own background at 1024 and 1280, and the chair verifies it visually in the preview after composition); commit 4's acceptance figure REFUTED by construction (source-counted fields vs a rendered walk — no equality expressible) → the arm asserts the shared verdict (`bare 0` ⇒ zero under-floor and zero sub-12 rendered) plus an exact per-surface pin, moving to an existing pricing harness if the 18-view walk's mocks cannot mount `PricingPage`. "
 "**THE GATE:** shared tier = FIX-D9's composed-tip proofs · FIX-P9 · TOOL-25 · FIX-P10 (four runs live — heavy; the eighth refreeze and RUN 23 wait for all four); working = FIX-P1 (the cure); free seats → none dispatched until the slot clears (FIX-C2d, TOOL-21, TOOL-16, FIX-L3, FIX-W1 wait; FIX-D10 after RUN 23).")
line = ("- **§934.47 addendum 107 — DOC-4 COMPOSED (`532ba71cc`); FIX-D9's FOUR COMPOSED BY ITS LANE (tip `48450e98c`, incl. FIX-B2b); FIX-C2c and TOOL-19 CLOSED GREEN and dry-composed clean (the chair picks them after D9's proofs); FIX-P1c convicted at the composed tip by the OSR walker (`anonForkSalt.js` reads `seed` on `config`, a key no writer produces — its cure in flight); TOOL-23's VERDICT (65 of 249 'unreachable' modules SHIP or typecheck; 44 retirable, 8 with no consumer) → FIX-D10 CHARTERED under four rulings and **§934.75 OPENED (the TE-STRIP tail — the chair recommends finishing the strip; awaiting the word)**; FIX-P10's rulings; NEVER PUSH WITH A PACKET READY (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 106 —"; assert u.count(key) == 1 and "addendum 107 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 107" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the slot's progress; FIX-D10; §934.75 (ODQ §934.47 addendum 107)\n\n"
      "- **Composed:** DOC-4 `532ba71cc`; FIX-D9's four by its lane, tip `48450e98c` (incl. FIX-B2b). Next: TOOL-19 (2) and FIX-C2c (3) by the chair, FIX-P1's OSR cure by its lane, then FIX-P9 (+ the chair's OSR absorb), TOOL-25, FIX-P10 as they land; the eighth refreeze; RUN 23; EM-R0d v4 placed.\n"
      "- **THE LANDING ORDER gains a sentence (from TOOL-19):** a seal licenses the retiree burn only in the worktree that dispatched it — NEVER PUSH WITH A PACKET READY.\n"
      "- **FIX-D10 chartered** (after RUN 23): the reachability walker learns the three edge classes before any retirement; the eight orphans; the vocabulary and headers for the 205 that keep; the 36 test-only fixtures classified against the design docs; the seven register-moving rows stay. **§934.75** the TE-STRIP tail is the owner's word (recommendation: finish the strip).\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 107:", io.open(ODQ, encoding="utf-8").read().count("addendum 107 —"), "| charter amended | no NUL")
