# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
W = "For the transfer state that I also go with all your recommendations, including the ones owed to me they require my sign off up to you"
line = ("- **§934.47 addendum 110 — THE OWNER'S WORD AT THE PAUSE (verbatim, ~14:05): \"" + W + "\" — EVERY RECOMMENDATION APPROVED; THE OWED SIGN-OFFS DELEGATED TO THE CHAIR; NOTHING IS OWED ANY MORE (2026-09-20 " + stamp + " EDT; the chair's reading, vetoable).** "
 "THE READING: (1) every recommendation the chair had put to the owner is approved as recommended; (2) the items listed as 'owed' because they needed the owner's sign-off are the chair's to sign — given explicitly for the transfer state, i.e. for the successor session to act on. WHAT IT COVERS, BY NAME: **§934.75** finish the TE-STRIP (the two worker entries and the five `src/lib/townScene/**` clients retired together under FIX-D10's door; the map-doors design stays as the document that would bring a map back) — RESOLVED as recommended; **the PUSH CHAIN** at the first fully green full check (push the consist + the ledger + a sealed kit; PR → master; merge on green CI behind the ignore-build gate) — reaffirming and widening the 09-19 directive; ⛔ NEVER WITH A PACKET READY (TOOL-19's law), so EM-R0d v4 is placed AFTER the push or flipped before it; **MIGRATIONS 201–203** to production by the chair's hand through the estate's migration door, after the merge and before the redeploy, the production pre-state measured and recorded; **the REDEPLOY** from the Vercel dashboard once master CI is green (a UI act under the owner's login — if the chair cannot reach it, the successor asks the owner to click and records it as a hand-act, not a decision). WHAT IT DOES NOT COVER, kept off the table by the chair's own judgment as since 09-13: production data deletion, security posture, new paid capability, parked items — none was recommended. HOW THE SUCCESSOR APPLIES IT: a permissive grant read from a file — at each gate the successor QUOTES the words in chat and proceeds unless the owner says stop (the owner gave the grant explicitly for the transfer state; the 09-13 total delegation and the 09-20 standing signature grant stand beside it). THE ORDER, after RUN 23 is fully green: the push chain → migrations 201–203 → the redeploy → §934.75 via FIX-D10. Recorded in memory (`owner-directive-2026-09-20-all-recommendations-approved-and-the-owed-sign-offs-delegated-to-the-chair`) and in the kit's handoff block (sealed `b4c9851a2`).")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 109 —"; assert u.count(key) == 1 and "addendum 110 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 110" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendment of 2026-09-20 " + stamp + " EDT — the owner's word at the pause (ODQ §934.47 addendum 110)\n\n- \"" + W + "\" — every recommendation approved; the push chain, migrations 201–203, the redeploy and §934.75 are the chair's to execute in that order after RUN 23 is fully green, never with a packet READY. Nothing is owed to the owner.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 110:", io.open(ODQ, encoding="utf-8").read().count("addendum 110 —"), "| charter amended | no NUL")
