# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
body = ("**THE FIRST COMPOSITION SITTING IS COMPOSED — 21 lane commits over the sixth refreeze, tip `d279d13eb`:** FIX-L1 (2) · FIX-P3 (5) · FIX-P4 (2) · FIX-P5 (5) by the chair (`7dea316c7`; blob equality proved); **FIX-P1 + FIX-P1b BY THEIR OWN LANE in the slot** — `326dc232f` (the conflict resolved: ONLY the import block conflicted; the `forkSample` body auto-merged with both changes intact; the resolution keeps both imports — P3's `raisedHere, REFUSAL_SURFACES` and P1's `forkIdentity` — and the TWO-PARENT DIFF is the proof: against the consist the diff adds only P1's three changes with no deletion of any P3 line, against `e0b03b63a` only P3's three with no deletion of any P1 line) and `75ea6d0e4` (P1b clean); proved at the composed tip — `tests/components` WHOLE **297 files / 2,103** (P3 landed it at 2,086; every FoundingWorlds pin of both lanes green together), `tests/lib` WHOLE 174 / 1,797, `tests/data` WHOLE 24 / 311, `tests/store` WHOLE 149 / 1,232, its domain 15, the lint instruments 22, voiceMechanics 30, eslint bare 0, goldens byte-identical; then FIX-C2b (4: `4d4535795` `cbb4fc4f2` `12f5812dc` `92626a345`) and TOOL-13b (1: `d279d13eb`) by the chair, file sets equal, blob equality proved except one legitimate difference (`docs/implementation/INDEX.md` in C2b's docs-live commit, which the chair's flip had also edited — a merge, not a hook rewrite). THE LANE'S TWO NOTICES: the composed `FoundingWorlds.jsx` now has two independent reasons to touch one call (P3 keyed the options bag, P1 the seed argument) — a third P-lane at that line conflicts with both (recorded for the next dispatch there); its P1b commit message needed a NUL stripped before git accepted it — the same escape trap as the source file — TOOL-25's walker gains the `git diff --numstat` `-` arm (no tracked source file reports as binary). FIX-P3's item (b) — the standard's hot-file rows for `src/App.jsx` and `SettlementsPanel.jsx` — is CLOSED: the rows ALREADY exist (575/600 and 577/600, joined 2026-09-20 at EM-B3c's landing); the lane read a base that predated them; no docs commit is owed. "
 "**NEXT, IN ORDER (the chair's):** THE SEVENTH REFREEZE launched at d279d13eb (the door then the plain run; the composition moved every figure — the expected deltas named in the note; commit gated on the measured tuple reconciling to the seven lanes' declared deltas within the walker's evaluated figures) → COMPOSE-REPROOF-1 dispatched at the refreeze tip (one Opus verify lane; the brief written) → RUN 22 in the consist at the refreeze tip (its ONE expected red the provenance title — §934.71; and because the `&&` chain stops at the ratchet on that red, the chair's build + `verify:dist` at the same tip run separately afterwards as the process law for the composed src moves) → EM-R0a PLACED (the fourth preamble amendment's sentence first) → the next sitting's compositions as lanes land (FIX-B2 building now; then FIX-D9 → FIX-T2 → TOOL-19 → TOOL-15 → TOOL-22 → TOOL-24 → …). TOOL-24 PAUSED with its four totals minted from measurement (`src/generators` 162,221 · domain-product 663,161 · certification 418,839 · `src/data` minus the ten leaves 244,787; byte-identical to TOOL-18's M3 rule on all 1,229 files — `per-file DIFFS: 0`; both red-firsts proved; its judgment ACCEPTED: no env-gated refresher for a report-only map — a green run must never rewrite a committed register). TOOL-22 PAUSED with the door built (`prepareImplementationDispatch` factored so both doors share one preflight; the archive name a fixed 9-char head slice matching the chair's hand rotation byte-for-byte; `resealedFrom` recorded; 31 bench arms; both collision halves executed, the empty-occupant half the sharper).")
line = ("- **§934.47 addendum 95 — THE FIRST COMPOSITION SITTING COMPOSED: 21 LANE COMMITS OVER THE SIXTH REFREEZE (tip `d279d13eb`); FIX-P1 RESOLVED ITS OWN CONFLICT WITH FIX-P3 IN THE SLOT (two-parent diffs as the proof; `tests/components` whole 2,103); FIX-P3's HOT-FILE ITEM CLOSED (the rows already exist); THE SEVENTH REFREEZE LAUNCHED; COMPOSE-REPROOF-1 AND RUN 22 NEXT; TOOL-22 AND TOOL-24 PAUSED WITH THEIR WORK PROVED (2026-09-20 " + stamp + " EDT; the chair; vetoable).** " + body)
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 94 —"; assert u.count(key) == 1 and "addendum 95 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 95" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the first composition sitting composed (ODQ §934.47 addendum 95)\n\n"
      "- **Composed at `d279d13eb`:** FIX-L1, FIX-P3, FIX-P4, FIX-P5, FIX-P1, FIX-P1b, FIX-C2b, TOOL-13b (21 commits). The seventh refreeze, COMPOSE-REPROOF-1 and RUN 22 follow at that tip; the chair's build + `verify:dist` run separately after run 22 (the `&&` chain stops at the ratchet on the owner-gated provenance red).\n"
      "- **TOOL-25 gains an arm:** `git diff --numstat` must never report `-` for a tracked source file (FIX-P1b's commit message needed a NUL stripped too).\n"
      "- **A dispatch note for `src/components/generate/FoundingWorlds.jsx`:** its `generate(seed, {...})` call now carries FIX-P3's options bag and FIX-P1's seed argument; a third lane at that line conflicts with both.\n")
io.open(CH, "w", encoding="utf-8").write(c)
print("ODQ addendum 95:", io.open(ODQ, encoding="utf-8").read().count("addendum 95 —"), "| charter amended")
