import json
src='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/hobb-24.json'
out='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-hobb-i360-374.json'
C=json.load(open(src))
V={
360:("VERIFIED_VERBATIM","The first epigraph of the story reads exactly like how a textbook of a real world country might start","Raw HTML fetched live (200, browser UA). Quote exact. 'opening' = the page's 'might start'; 'first epigraph' and 'real world country' both explicit."),
361:("VERIFIED_VERBATIM","A pretty informative, yet boring, introduction epigraph","Quote exact, immediately after the block-quoted first epigraph. 'taken by itself' is carried by the very next sentence: 'However, the first paragraph of the series that follows it is what enhances the epigraph.'"),
362:("VERIFIED_VERBATIM","But what is this tonal shift? Why is Fitz writing about himself instead of focusing fully on the facts?","Quote exact; the next sentence supplies the second limb verbatim in substance. The shift is epigraph-to-main-text: the two preceding paragraphs quote the novel's opening prose and gloss it against the epigraph."),
363:("VERIFIED_VERBATIM","I loved the excerpts at the start of each chapter describing some aspect of Six Duchies history or culture","Quote exact. 'all sixteen books' confirmed earlier on the same page: 'as of the last day of August I have completed all 16 books set in her Realm of the Elderlings world'; writer is female (pregnancy/baby girl)."),
364:("VERIFIED_VERBATIM","especially on my second read I picked up so many details that she includes on clothing, customs, politics, and architecture","Quote exact, same paragraph as 363, in the Farseer/Assassin's Apprentice section. All four categories and the second-reading limb explicit."),
365:("VERIFIED_VERBATIM","where it seems that Hobb is simply throwing in random details of description, always come back to have some relevance and I enjoyed looking out for those as I read","Quote exact, in the 'The Fitz and the Fool Trilogy' section (heading at line 256, quote at 266) as the page hint says. Both limbs — later relevance, reading watchfully — explicit."),
366:("VERIFIED_VERBATIM","There is something really appealing about the Trader way and how everything is a negotiation and a conversation","Quote exact, in the Liveship Traders section; the same paragraph names Bingtown and the Vestrit Traders, so 'Bingtown Traders' is supported."),
367:("VERIFIED_VERBATIM","Hobb doesn't come out and define it word for word for you. She shows it to you slowly, as if it's the most natural thing","Quote exact including the curly apostrophe. Both limbs — no word-for-word definition, slow showing as the most natural thing — are consecutive sentences in the magic-system paragraph."),
368:("VERIFIED_VERBATIM","if it's boring to you... Don't write it... You can have a one sentence chapter if you want","Quote exact, under the heading \"I don't want to write the next scene. It's boring.\" The compress-rather-than-write limb is the section's own solution: don't write it, type a one-line summary, get on with the story."),
369:("VERIFIED_VERBATIM","After four days of punishing travel, they reached a small holding near a water hole","Quote exact and the sentence completes as the claim says. Duration ('four days'), cost ('punishing'), arrival ('a small holding near a water hole') all present; 'cost' is a fair gloss on 'punishing'."),
370:("VERIFIED_VERBATIM","if I look for a synonym... via the word processing program... it will show me the same synonyms that every other writer is using","Quote exact, in the asterisked footnote that opens \"Do you have a copy of Roget's Thesaurus? If not, go buy one now. A fat paper thesaurus is a treasure.\" Paper-over-software advice and its stated ground both explicit."),
371:("VERIFIED_VERBATIM","The car isn't red, it's candy apple red with metal flake","Quote exact, inside the section 'Nope. I'm blocked. Really blocked.', within the editor-hat pass ('Here is what almost always works for me') that the post says gets the story flowing again."),
372:("VERIFIED_VERBATIM","Most epic fantasy doesn't spend pages... worrying about the apprentice fees for dependants, or worrying whether wise old friends are going a bit senile","Quote exact, in the Originality section of 'The Golden Fool, by Robin Hobb' (post dated February 4, 2013 on the tag page). Page says 'wise old friends' (plural, 'a bit senile') where the claim says 'an old friend is going senile' — same substance."),
373:("VERIFIED_VERBATIM","the fantasy only matters because of the reality in its shadow - that motivations are personal, and that consequences will also be personal","Quote exact, closing sentence of the same Originality section; the reality-in-its-shadow limb is the first half of that sentence."),
374:("VERIFIED_VERBATIM","every level of the narration is imperfect","Quote exact, in the final 'Finally: on this re-read' paragraph of the Golden Fool review. Layering is spelled out (past Fitz, novel-time Fitz, 'but should we really trust Fitz-the-narrator?'), and the narrating self is included ('Fitz-the-narrator's as well'). Post is tagged Tawny Man / Tawny Man Trilogy."),
}
verdicts=[{"index":i,"verdict":V[i][0],"trueWording":V[i][1],"note":V[i][2]} for i in C['indices']]
json.dump({"name":"hobb","chunk":24,"claims":C['claims'],"verdicts":verdicts},open(out,'w'),indent=1,ensure_ascii=False)
print("wrote",out)
