/**
 * src/domain/generation/generationForkRegistry.js — GENERATION'S CHOSEN FACTS, in two tiers.
 * (header JSDoc — the packet specifies its content; counted as COMMENT by max-lines)
 */
export const GENERATION_CENSUS_ROWS = 63;

export const GENERATION_TIER1 = Object.freeze([
  { step: 'resolveConfig', key: 'tier', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.tier' },
  { step: 'resolveConfig', key: 'population', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.population' },
  { step: 'resolveConfig', key: 'tradeRoute', via: 'provides', stepDraws: 63, keyMoves: 5, rows: 63, class: 'drawn', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'terrainType', via: 'provides', stepDraws: 63, keyMoves: 3, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.config.terrainType' },
  { step: 'resolveConfig', key: 'resolvedTerrain', via: 'provides', stepDraws: 63, keyMoves: 3, rows: 63, class: 'drawn', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'culture', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.config.culture' },
  { step: 'resolveConfig', key: 'culturalIdentity', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.culturalIdentity' },
  { step: 'resolveConfig', key: 'generationContentProfile', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'magicLevel', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.config.magicLevel' },
  { step: 'resolveConfig', key: 'threat', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'priorityMagicEffective', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'noMagic', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'townPlus', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'effectiveConfig', via: 'provides', stepDraws: 63, keyMoves: 7, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'resolveConfig', key: 'institutionToggles', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'categoryToggles', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'goodsToggles', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveConfig', key: 'servicesToggles', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'buildGenerationContext', key: 'generationContext', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveResources', key: 'nearbyResources', via: 'provides', stepDraws: 63, keyMoves: 62, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.config.nearbyResources' },
  { step: 'resolveResources', key: 'nearbyResourcesNative', via: 'provides', stepDraws: 63, keyMoves: 62, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.config.nearbyResources' },
  { step: 'resolveResources', key: 'nearbyResourcesDepleted', via: 'provides', stepDraws: 63, keyMoves: 48, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 23, transformed: 40 }, onRecordClass: 'varies', producedOnRecord: { absent: 0, same: 23, transformed: 40 }, producedOnRecordClass: 'varies', recordPath: 'record.config.nearbyResourcesDepleted' },
  { step: 'resolveResources', key: 'nearbyResourcesNativeDepleted', via: 'provides', stepDraws: 63, keyMoves: 48, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 23, transformed: 40 }, onRecordClass: 'varies', producedOnRecord: { absent: 0, same: 23, transformed: 40 }, producedOnRecordClass: 'varies', recordPath: 'record.config.nearbyResourcesNativeDepleted' },
  { step: 'resolveResources', key: 'nearbyResourcesCustom', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.config.nearbyResourcesCustom' },
  { step: 'resolveResources', key: 'nearbyResourceDefinitions', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.config.nearbyResourceDefinitions' },
  { step: 'resolveResources', key: 'nearbyResourceDefinitionsDepleted', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.config.nearbyResourceDefinitionsDepleted' },
  { step: 'resolveResources', key: 'effectiveConfig', via: 'mutates', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'resolveStress', key: 'stress', via: 'provides', stepDraws: 63, keyMoves: 57, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 9, transformed: 54 }, producedOnRecordClass: 'varies', recordPath: 'record.stress' },
  { step: 'resolveStress', key: 'stressTypes', via: 'provides', stepDraws: 63, keyMoves: 57, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 51, transformed: 12 }, onRecordClass: 'varies', producedOnRecord: { absent: 0, same: 51, transformed: 12 }, producedOnRecordClass: 'varies', recordPath: 'record.config.stressTypes' },
  { step: 'resolveStress', key: 'effectiveConfig', via: 'mutates', stepDraws: 63, keyMoves: 57, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'resolveNeighbour', key: 'neighbourProfile', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveNeighbour', key: 'neighbourEconBias', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveNeighbour', key: 'neighbourFacBias', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveNeighbour', key: 'rawNeighbour', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'resolveNeighbour', key: 'effectiveConfig', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'assembleInstitutions', key: 'institutions', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 7, transformed: 56 }, producedOnRecordClass: 'varies', recordPath: 'record.institutions' },
  { step: 'assembleInstitutions', key: 'catalogForTier', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'assembleInstitutions', key: 'generationRepairs', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 43, same: 20, transformed: 0 }, onRecordClass: 'varies', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.generationCoherenceReceipt.repairs' },
  { step: 'subsumptionPass', key: 'institutions', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 7, transformed: 56 }, producedOnRecordClass: 'varies', recordPath: 'record.institutions' },
  { step: 'cascadePass', key: 'institutions', via: 'mutates', stepDraws: 56, keyMoves: 56, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 41, transformed: 22 }, producedOnRecordClass: 'varies', recordPath: 'record.institutions' },
  { step: 'isolationPass', key: 'stress', via: 'provides', stepDraws: 2, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 9, transformed: 54 }, producedOnRecordClass: 'varies', recordPath: 'record.stress' },
  { step: 'isolationPass', key: 'isolationSupport', via: 'provides', stepDraws: 2, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 62, transformed: 1 }, producedOnRecordClass: 'varies', recordPath: 'record.isolationSupport' },
  { step: 'isolationPass', key: 'institutions', via: 'mutates', stepDraws: 2, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 43, transformed: 20 }, producedOnRecordClass: 'varies', recordPath: 'record.institutions' },
  { step: 'isolationPass', key: 'effectiveConfig', via: 'mutates', stepDraws: 2, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'stressConfirmPass', key: 'stress', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 9, transformed: 54 }, producedOnRecordClass: 'varies', recordPath: 'record.stress' },
  { step: 'stressConfirmPass', key: 'stressTypes', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 51, transformed: 12 }, onRecordClass: 'varies', producedOnRecord: { absent: 0, same: 51, transformed: 12 }, producedOnRecordClass: 'varies', recordPath: 'record.config.stressTypes' },
  { step: 'stressConfirmPass', key: 'effectiveConfig', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'generateEconomy', key: 'economicState', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 17, transformed: 46 }, producedOnRecordClass: 'varies', recordPath: 'record.economicState' },
  { step: 'generateEconomy', key: 'effectiveConfig', via: 'mutates', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: 'record.config' },
  { step: 'generatePower', key: 'powerIntent', via: 'provides', stepDraws: 0, keyMoves: 63, rows: 63, class: 'label', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'generatePower', key: 'powerStructure', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.powerStructure' },
  { step: 'neighbourFactions', key: 'powerStructure', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.powerStructure' },
  { step: 'factionCorrelationPass', key: 'institutions', via: 'mutates', stepDraws: 1, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 43, transformed: 20 }, producedOnRecordClass: 'varies', recordPath: 'record.institutions' },
  { step: 'coherenceRepairPass', key: 'generationRepairs', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 43, same: 20, transformed: 0 }, onRecordClass: 'varies', producedOnRecord: { absent: 43, same: 20, transformed: 0 }, producedOnRecordClass: 'varies', recordPath: 'record.generationCoherenceReceipt.repairs' },
  { step: 'coherenceRepairPass', key: 'isolationSupport', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.isolationSupport' },
  { step: 'coherenceRepairPass', key: 'effectiveConfig', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.config' },
  { step: 'coherenceRepairPass', key: 'institutions', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.institutions' },
  { step: 'economyReconcilePass', key: 'economicState', via: 'provides', stepDraws: 63, keyMoves: 20, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.economicState' },
  { step: 'economyReconcilePass', key: 'spatialLayout', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.spatialLayout' },
  { step: 'economyReconcilePass', key: 'availableServices', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.availableServices' },
  { step: 'powerEconomyReconcilePass', key: 'powerStructure', via: 'mutates', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.powerStructure' },
  { step: 'structuralValidationPass', key: 'structural', via: 'provides', stepDraws: 0, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 63, same: 0, transformed: 0 }, onRecordClass: 'absent', producedOnRecord: { absent: 63, same: 0, transformed: 0 }, producedOnRecordClass: 'absent', recordPath: null },
  { step: 'generatePopulation', key: 'npcs', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.npcs' },
  { step: 'generatePopulation', key: 'relationships', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.relationships' },
  { step: 'generatePopulation', key: 'factions', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.factions' },
  { step: 'generatePopulation', key: 'conflicts', via: 'provides', stepDraws: 63, keyMoves: 58, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.conflicts' },
  { step: 'corruptionPass', key: 'factions', via: 'mutates', stepDraws: 42, keyMoves: 39, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.factions' },
  { step: 'corruptionPass', key: 'npcs', via: 'mutates', stepDraws: 42, keyMoves: 39, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.npcs' },
  { step: 'generateNarratives', key: 'settlementReason', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.settlementReason' },
  { step: 'generateNarratives', key: 'resourceAnalysis', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.resourceAnalysis' },
  { step: 'generateNarratives', key: 'economicViability', via: 'provides', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.economicViability' },
  { step: 'generateNarratives', key: 'history', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.history' },
  { step: 'assembleSettlement', key: 'settlement', via: 'provides', stepDraws: 63, keyMoves: 63, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record' },
  { step: 'assembleSettlement', key: 'powerStructure', via: 'mutates', stepDraws: 63, keyMoves: 0, rows: 63, class: 'pure', onRecord: { absent: 0, same: 0, transformed: 63 }, onRecordClass: 'transformed', producedOnRecord: { absent: 0, same: 0, transformed: 63 }, producedOnRecordClass: 'transformed', recordPath: 'record.powerStructure' },
  { step: 'assembleSettlement', key: 'stress', via: 'mutates', stepDraws: 63, keyMoves: 54, rows: 63, class: 'drawn', onRecord: { absent: 0, same: 63, transformed: 0 }, onRecordClass: 'same', producedOnRecord: { absent: 0, same: 63, transformed: 0 }, producedOnRecordClass: 'same', recordPath: 'record.stress' },
].map(Object.freeze));

export const GENERATION_TIER2 = Object.freeze([
  { cardShape: 'institution', outputKey: 'institutions[].name', forkId: 'assembleInstitutions', step: 'assembleInstitutions', key: 'institutions', module: 'src/generators/steps/assembleInstitutions.js', symbol: 'assembleInstitutions', origin: 'drawn' },
  { cardShape: 'institution', outputKey: 'institutions[].category', forkId: 'assembleInstitutions', step: 'assembleInstitutions', key: 'institutions', module: 'src/generators/steps/assembleInstitutions.js', symbol: 'assembleInstitutions', origin: 'drawn' },
  { cardShape: 'npc', outputKey: 'npcs[].name', forkId: 'generatePopulation', step: 'generatePopulation', key: 'npcs', module: 'src/generators/steps/generatePopulation.js', symbol: 'generatePopulation', origin: 'drawn' },
  { cardShape: 'npc', outputKey: 'npcs[].role', forkId: 'generatePopulation', step: 'generatePopulation', key: 'npcs', module: 'src/generators/steps/generatePopulation.js', symbol: 'generatePopulation', origin: 'drawn' },
  { cardShape: 'npc', outputKey: 'npcs[].status', forkId: 'generatePopulation', step: 'generatePopulation', key: 'npcs', module: 'src/generators/steps/generatePopulation.js', symbol: 'generatePopulation', origin: 'drawn' },
  { cardShape: 'faction', outputKey: 'powerStructure.factions[].faction', forkId: 'generatePower', step: 'generatePower', key: 'powerStructure', module: 'src/generators/steps/generatePower.js', symbol: 'generatePower', origin: 'computed' },
  { cardShape: 'faction', outputKey: 'powerStructure.factions[].category', forkId: 'generatePower', step: 'generatePower', key: 'powerStructure', module: 'src/generators/steps/generatePower.js', symbol: 'generatePower', origin: 'computed' },
  { cardShape: 'faction', outputKey: 'powerStructure.factions[].power', forkId: 'generatePower', step: 'generatePower', key: 'powerStructure', module: 'src/generators/steps/generatePower.js', symbol: 'generatePower', origin: 'computed' },
  { cardShape: 'powerSeat', outputKey: 'powerStructure.governingName', forkId: 'generatePower', step: 'generatePower', key: 'powerStructure', module: 'src/generators/steps/generatePower.js', symbol: 'generatePower', origin: 'computed' },
  { cardShape: 'powerSeat', outputKey: 'powerStructure.factions[].isGoverning', forkId: 'generatePower', step: 'generatePower', key: 'powerStructure', module: 'src/generators/steps/generatePower.js', symbol: 'generatePower', origin: 'computed' },
].map(Object.freeze));

export const GENERATION_BLIND_HALVES = Object.freeze([
  Object.freeze({ id: 'field-rootness', statement: 'x', refutableBy: 'y' }),
  Object.freeze({ id: 'hash-channel', statement: 'x', refutableBy: 'y' }),
  Object.freeze({ id: 'corpus-ceiling', statement: 'x', refutableBy: 'y' }),
  Object.freeze({ id: 'second-seedrandom-importer', statement: 'x', refutableBy: 'y' }),
]);

export const GENERATION_CHANNELS = Object.freeze({
  mints: Object.freeze({ direct: 4, rootSeedPrefixed: true }),
  hash: Object.freeze({ instrument: 'src/kernel/proseHash.js#pickVariant', fnv1a32External: 6 }),
});

export function tier1For(step, key) {
  return GENERATION_TIER1.find((r) => r.step === step && r.key === key) || null;
}

export function tier2For(cardShape, outputKey) {
  return GENERATION_TIER2.filter((r) => r.cardShape === cardShape && r.outputKey === outputKey);
}
