import { readFileSync } from 'node:fs';
const corpus=JSON.parse(readFileSync('corpus.json','utf8'));
const R6=corpus.filter(r=>r.register==='R6');
const anyPub=R6.filter(r=>/it is public/i.test(r.text)).length;
const anyKnown=R6.filter(r=>/it is known/i.test(r.text)).length;
const either=R6.filter(r=>/it is (public|known)/i.test(r.text)).length;
console.log('rows containing "it is public" anywhere:', anyPub);
console.log('rows containing "it is known"  anywhere:', anyKnown);
console.log('rows containing either anywhere         :', either);
console.log('rows OPENING "It is public/known"        :', R6.filter(r=>/^It is (public|known)\b/.test(r.text.trim())).length);
console.log('rows OPENING There/It is|was|were|are    :', R6.filter(r=>/^(There|It) (is|was|were|are)\b/.test(r.text.trim())).length);
console.log();
console.log('--- the 34 "It is out ..." openers, first 6 ---');
R6.filter(r=>/^It is out\b/.test(r.text.trim())).slice(0,6).forEach(r=>console.log('   '+r.text.slice(0,140)));
console.log('total "It is out" openers:', R6.filter(r=>/^It is out\b/.test(r.text.trim())).length);
console.log();
console.log('--- non-public/known/out There-It openers ---');
R6.filter(r=>/^(There|It) (is|was|were|are)\b/.test(r.text.trim()) && !/^It is (public|known|out)\b/.test(r.text.trim())).forEach(r=>console.log('   '+r.text.slice(0,140)));
