import json
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/leguin-17.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-leguin-i300-314.json"
d=json.load(open(src,encoding="utf-8"))
V="VERIFIED_VERBATIM"
verdicts=[
 {"index":300,"verdict":V,"trueWording":"a haunting quality, a sense of depth, of unspoken further implication","note":"ursulakleguin.com/blog/52 fetched live (HTTP 200, raw HTML). Goblin Secrets paragraph: 'And there's something else to it that I can't put words to: a haunting quality, a sense of depth, of unspoken further implication, in the adventures and the characters, which is its real magic.' Quote exact; book, author (William Alexander) and every limb supported."},
 {"index":301,"verdict":V,"trueWording":"stories that take you quietly into a place","note":"Same page, Kij Johnson section: 'I like stories that take you quietly into a place and let you do difficult and interesting work with some of the people there.' Quote exact; the claim only shifts 'you' to third person. Said of 'The Man Who Bridged the Mist'."},
 {"index":302,"verdict":V,"trueWording":"Homer truly doesn't take sides, and so he permits the story to be tragic","note":"ursulakleguin.com/blog/31 fetched live (HTTP 200). Exact: 'But Homer truly doesn't take sides, and so he permits the story to be tragic.' Both limbs supported. Minor: the sentence sits in the sixth body paragraph, not the seventh as the page field says; that is a locator, not a claim limb."},
 {"index":303,"verdict":V,"trueWording":"His impartiality is far from dispassionate; the story is a torrent of passionate actions","note":"Same page: 'His impartiality is far from dispassionate; the story is a torrent of passionate actions, generous, despicable, magnificent, trivial. But it is unprejudiced.' All three limbs (far from dispassionate, torrent of passionate actions, unprejudiced) present verbatim."},
 {"index":304,"verdict":V,"trueWording":"I had put clues into the book, without knowing it, that led me on into Ged's life","note":"ursulakleguin.com/interview-karabatak fetched live (HTTP 200); header confirms 'Karabatak Magazine, 9th edition, summer issue, 2013'. Answer 6 (as the page field claims): 'I had no idea, when I wrote A Wizard of Earthsea... But I had put clues into the book, without knowing it, that led me on into Ged's life.' Quote exact, the Earthsea referent explicit."},
 {"index":305,"verdict":V,"trueWording":"It's a very long beat, the rhythms of a prose work","note":"lithub.com fetched live (HTTP 200); page carries 'From Ursula K. Le Guin: Conversations on Writing. Used with permission of Tin House Books. Copyright 2018.' In the Woolf/sound exchange with David Naimon: 'When you're talking about the sound in the rhythm of prose, it is so different from poetry, because it's in a way much coarser. It's a very long beat, the rhythms of a prose work.' The quote string matches contiguously despite the page's stray letter-spacing artifacts; all three limbs (very long beat, different from poetry, much coarser) supported."},
 {"index":306,"verdict":V,"trueWording":"intellectually intriguing, but, really, often a struggle to read","note":"rrhorton.blogspot.com fetched live (HTTP 200); byline Rich Horton, dated Wednesday, April 24, 2024. Final-verdict paragraph: 'The ethnographic bits -- and they are not just \"bits\" -- are intellectually intriguing, but, really, often a struggle to read.' Quote exact; 'intellectually interesting' in the claim paraphrases 'intellectually intriguing' and is the same limb."},
 {"index":307,"verdict":V,"trueWording":"It does read, to a great extent, like a writer deciding to include all her notes","note":"Same page: 'It does read, to a great extent, like a writer deciding to include all her notes.' Quote exact; the 'to a great extent' hedge that the claim carries is the page's own."},
 {"index":308,"verdict":V,"trueWording":"more impressive than it is involving","note":"Same page, final verdict: 'It is in the end a novel (or \"book\" or \"construct\" or whatever) that is more impressive than it is involving.' Quote exact and the whole claim is that sentence."},
 {"index":309,"verdict":V,"trueWording":"in the final section, some 100 pages, called 'The Back of the Book'","note":"Same page: 'she literally does -- in the final section, some 100 pages, called \"The Back of the Book\".' Quote exact; ~100 pages, the title, and the end-of-book position all supported. Flagging the wording: Horton calls it 'the final section', never 'appendix' -- the claim's word is a paraphrase of a section of notes at the book's end, not an added fact. Locator drift: it is the fourth body paragraph, not the second."},
 {"index":310,"verdict":V,"trueWording":"'Pandora', a stand in for the author or the future anthropologist who is recording all this data","note":"Same page: 'There are also snippets from the point of view of \"Pandora\", a stand in for the author or the future anthropologist who is recording all this data.' Quote exact; 'voice' in the claim renders the page's 'point of view'/'stand in', and 'recording the material' renders 'recording all this data'."},
 {"index":311,"verdict":V,"trueWording":"a novel that masquerades as anthropology, a study of a people","note":"triumphofthenow.com fetched live (HTTP 200); byline scottmanleyhadley, July 13, 2019. 'Always Coming Home is a novel that masquerades as anthropology, a study of a people living in what remains of California's Napa Valley a thousand years or so into the future.' Quote exact, both limbs supported."},
 {"index":312,"verdict":V,"trueWording":"includes third person essays about their culture: how they measure time, how they draw maps","note":"Same page: 'Le Guin supplies interviews with Kesh archivists/historians and includes third person essays about their culture: how they measure time, how they draw maps, what is their relationship with \"the City of Mind\"...' Quote exact; 'third-person essays', 'Kesh culture', and both named topics all present."},
 {"index":313,"verdict":V,"trueWording":"It is fiction without being storytelling, though it contains many stories within itself","note":"Same page, closing stretch: 'The novel is a speculative, post-anthropocene text. It is fiction without being storytelling, though it contains many stories within itself.' Quote exact; the 'It' is Always Coming Home, named throughout the review."},
 {"index":314,"verdict":V,"trueWording":"Tolkien's world has virtually no ethnographic detail, while Le Guin's has no history","note":"agreenmanreview.com fetched live (HTTP 200); byline Cat Eldridge, publisher of Green Man Review. 'This is the antithesis of Tolkien's Lord of the Rings. Tolkien's world has virtually no ethnographic detail, while Le Guin's has no history.' Quote exact (curly apostrophe matches); the contrast limb is the same sentence's second half."},
]
assert [v["index"] for v in verdicts]==d["indices"], "index mismatch"
json.dump({"name":"leguin","chunk":17,"claims":d["claims"],"verdicts":verdicts},open(out,"w",encoding="utf-8"),ensure_ascii=False,indent=1)
print("wrote",out)
