# -*- coding: utf-8 -*-
"""EM-B1d v5's two ruled exceptions; two more reds on the tip (CURE-C, CURE-D); FIX-L1; EM-B1h v2 accepted (three kinds; EM-B1i widened; EM-B1j); EM-P2's Q-8. Charter + ODQ §934.47 addendum 30."""
import io, sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — EM-B1d version 5 lands under two RULED EXCEPTIONS; two more reds on the tip slotted; EM-B1h version 2 accepted; EM-P2's one question ruled (ODQ §934.47 addendum 30)

- **EM-B1d VERSION 5 was built complete and green and STOPPED one step short of its commit on two wrong FIGURES in the packet itself** (both outside its sixteen paths). RULED, so that a third build round does not re-prove what is proved: (1) the lighting delta is `+1 / +0 / +1 / +4 / +1`, not `+5` titles — `tests/generators/densityLaw.test.js` uses vitest GLOBALS, the census parks it, and a new `it` there counts nowhere; the packet's figure is corrected at the LANDED flip. (2) `check:packet` cannot reach its last five steps because the packet's `checks` run `build:edge-shared` MID-CHAIN, which re-stamps declared paths and the gate correctly invalidates everything after it; the landing proceeds on steps 1–8 executed by the gate, steps 9–13 executed BY HAND at the same tree (all green, quoted in the commit), and the chair's own re-run of those five at its validation; the `checks` order is corrected at the flip. *Rejected:* amending the READY packet (it kills the seal and forces a full re-build for two metadata errors). *Reversal:* none needed — no code is affected. THE CLASS IS CLOSED AT PRE-PROOF: step 14 (a generator among `checks` goes LAST; a title is worth a title only in a CREDITED file) and step 15 (a file stamped by the prose-wiring census owes the plain re-take).
- **TWO MORE REDS ALREADY ON THE INTEGRATION TIP, found by that build's whole-directory lint run — both would have failed run 17:** the prose-wiring census is stale for `resolveConfig.js` (EM-P3 edited a stamped file and carried no re-take) → **CURE-D** (a stamp-only plain re-take, lawful by the standing 2026-09-08 ruling; a moved ROW is the chair's); and EM-B1e's test file landed PARKED → **CURE-C** (already slotted). The terminal's cure sitting is now CURE-A · CURE-B · CURE-C · CURE-D, one lane, four commits, before the ONE refreeze and run 17.
- **FIX-L1 (NEW; a parallel lane):** `densityLaw.test.js` carries 112 `it`s that have never counted as evidence because the file uses vitest globals; the census parks 384 files. Measured first: how many are parked for an unresolved OPENER ALONE (one import line cures each); the lane credits that population, and the census moves DELIBERATELY at its composition train's refreeze.
- **EM-B1h VERSION 2 ACCEPTED (kit `packets-waiting/EM-B1h.*`):** THREE kinds, derived from what each writer does to the record — `closure` 15 (every one sets `_worldPulseInactive` and a non-active status, including the six gently-named demotion fates), `standing` 1 (`demoted_by_disaster`: renamed in place, no status, no flag), `rise` 2; the kind map is the single authored source (structurally total, 910 B); the guard lives in the leaf (`assertWorldPulseFate`, 98 B and two kernel lines); a fifth change row — the coupling-inclusion census is total over `src/domain/worldPulse` and the leaf takes an `ARGUED_UNLAYERED` row with the ceiling 28 → 29. **EM-B1i's population is THREE, not two** (a demoted wizard's tower joins the flourishing academy and the reconstructed guild in reading as destroyed) — its row is widened. `LIFECYCLE_CLOSE_FATES` is 3 of the 15 closure fates (only the ECONOMIC closures damp; abolition, demotion, disaster and settlement death do not) — NOT derived from the kind here (it would be a lived-behaviour change, 3 counted words → 15): EM-B1i's compile measures whether that is deliberate and puts it to the chair. **EM-B1j (NEW; after EM-B1h, golden-neutral):** `institutionHistory[].fate` is a DIFFERENT, overlapping open vocabulary (17 values: 12 shared, 5 its own) and owes the same closure.
- **EM-P2 VERSION 3's PRE-PROOF re-measured everything green** (the 75 rows byte-identical at the tip; the instrument's control with its negative control) and caught that the mutation register owes TWO rows, not one (both test directories are enforcers) — version 3 would have red at the landing. Its one block, RULED: nine acceptance cases against the validator's cap of eight → `A3s` folds into `A3` as its static half, no assertion dropped, the title delta reconciled to one derivable figure. It is placed the moment EM-B1d is LANDED.

"""

ODQ = """- **§934.47 addendum 30 — EM-B1d VERSION 5 LANDS UNDER TWO RULED EXCEPTIONS; THE WHOLE-DIRECTORY LINT RUN FOUND TWO MORE REDS ALREADY ON THE BRANCH (__STAMP__; the successor chair; vetoable).** The second build of EM-B1d was complete and green — the walker red, red, green; six mutants convicted; the edge battery 67 of 67 including the pin that had convicted the poisoned slot; first paint +32 bytes of 60 allowed; the zero-slack generation worker byte-identical; the goldens unmoved — and it stopped, correctly, one step short of its commit on two wrong figures in the packet's own text: a lighting-census title it had priced in a test file the census has never counted (the file uses vitest globals), and a `checks` order that runs a generator mid-chain so the packet gate can never reach its last five steps. RULED: land it — the five unreached steps were run by hand, green, and the chair re-runs them; the two figures are corrected at the LANDED flip; amending a sealed packet would have forced a third full build to fix two lines of metadata. The class is closed where it belongs, at pre-proof (steps 14 and 15). The same build's whole-directory lint run — a rule that is six hours old — found that EM-P3's landing had left the prose-wiring census stale and EM-B1e's test file had landed uncounted: with the prose-numerics row the fix lane found, that is THREE reds earlier landings left on the branch that no focused run could see and the closing full check would have met all at once. All three are cured in one sitting before run 17 (CURE-B, CURE-C, CURE-D, beside CURE-A). ALSO: the fate vocabulary has THREE kinds, not two — a demoted-but-standing house is its own kind — so the live defect (a standing institution read as destroyed) covers three fates, not two.
"""

t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter + ODQ add. 30")
