# -*- coding: utf-8 -*-
"""Charter + ODQ §934.47 addendum 23: EM-B1d's build STOPPED correctly; the packet conflated two readings; version 5 re-cut."""
import io, sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — EM-B1d RE-CUT TO VERSION 5: two readings get two names; the pre-proof gains two steps (ODQ §934.47 addendum 23)

- **What happened.** The Opus build lane built EM-B1d version 4 complete and green and STOPPED UNCOMMITTED on three measured contradictions, each needing a path the manifest did not declare: `build:edge-shared` re-stamps ALL FIVE bundle metas in one build window (seven generated artifacts, not four — and the packet's own sealed `checks` run that generator, so the packet could not pass its own seal); a committed exact pin on `ROSTER_ABSENT_STATUSES` (`tests/generators/densityLaw.test.js`); a committed fixture spelling `status: 'imprisoned'` (`tests/domain/espionageMission.test.js`). Its "noticed, not touched" line convicted the PACKET: version 4 put `jailed` — a REVERSIBLE status — into `ROSTER_ABSENT_STATUSES`, whose one consequence is a house's DISSOLUTION, against that file's own law (R18: an irreversible consequence may only follow an irreversible cause), and re-pointed two availability readers at the roster constant, spreading the conflation. The chair promoted that contract; the error is the chair's.
- **THE RE-CUT (version 5):** `ROSTER_ABSENT_STATUSES` stays exactly `dead · exiled · removed` (its header judges `jailed` PRESENT; the committed pin stands, and gains one new pin: a house whose only figure is jailed reads `crewed`); a NEW exported AVAILABILITY vocabulary, `NPC_UNAVAILABLE_STATUSES` = `dead · exiled · jailed · removed` ("cannot act, hold a place, or succeed — NOT the house-roster reading"), is what `successors.js` and `envoyCasting.js` (+ `missing`) read; its HOME is chosen by measurement against the zero-slack generation worker (the placement before the ceiling); the walker's roster rows carry the lane's `spelling` field (`literals` | `union-read`) as contract; the three re-stamped metas and the two test files join the manifest. The lane drafts version 5 (compile-grade, ungated), the chair validates and places it, the lane re-seals and finishes.
- **EM-B1f INHERITS A MEASUREMENT (before its promotion):** `isOffStage` FILTERS a person out of the settlement every pulse kernel reads. If any IRREVERSIBLE consumer (house dissolution above all) reads that filtered view, then EM-B1f's reversible members (`jailed`, and `exiled` by a later decree) reach an irreversible consequence through the FILTER even though the roster constant refuses them — and the same would already be true today of a shelved or hostage last member. Measured first; the chair rules from it. `OFF_STAGE_STATUSES` should be DERIVED from `NPC_UNAVAILABLE_STATUSES` minus `dead` rather than spelled a third time.
- **THE PRE-PROOF GAINS STEPS 11 AND 12:** (11) RUN THE PACKET'S OWN `checks` IN A THROWAWAY COPY and diff the tree — every path a declared command writes (generated artifacts above all: the edge-shared generator re-stamps every sibling's meta) is a change-manifest row; (12) SWEEP THE TESTS, not only `src/`, for every symbol the packet changes and every literal it retires — an exact pin or a fixture that the contract reds is a declared TEST path with its cure, found at pre-proof, never at the build. The EM preamble gains row 12 (§P2) saying the same of generated siblings.

"""

ODQ = """- **§934.47 addendum 23 — EM-B1d's BUILD LANE STOPPED CORRECTLY, AND ITS LAST LINE CONVICTED THE PACKET THE CHAIR HAD PROMOTED: `jailed` IS REVERSIBLE AND MUST NEVER DISSOLVE A HOUSE — VERSION 5 RE-CUT (__STAMP__; the successor chair; vetoable).** The lane built version 4 complete and green (the walker red-first then 4/4; five mutants convicted; both goldens unmoved; the generation worker byte-identical; first paint −5 B; the lighting tuple exactly as predicted) and STOPPED UNCOMMITTED on three paths the manifest did not declare: the edge-shared generator re-stamps all five metas in one build window (seven artifacts, not four — the packet could not pass its own seal); a committed exact pin on `ROSTER_ABSENT_STATUSES`; a committed `'imprisoned'` fixture. Nothing was improvised. Then it named what the chair had missed: version 4 added `jailed` to `ROSTER_ABSENT_STATUSES`, whose single consequence is a house's permanent DISSOLUTION — against the file's own R18 law that an irreversible consequence needs an irreversible cause — so a house whose last figure is jailed would have been dissolved for good the day EM-B1a made the status writable. THE ERROR IS THE CHAIR'S (the contract conflated "cannot keep a seat" with "is off the house's roster"); it cost one build round and no landed defect. RE-CUT: the roster constant is untouched and a new pin says a jailed last figure leaves the house `crewed`; a separately named availability vocabulary (`NPC_UNAVAILABLE_STATUSES`: dead · exiled · jailed · removed) is what the successor and envoy readers use, its home chosen by measurement against the zero-slack generation worker; the five undeclared paths join the manifest. EM-B1f inherits the same question one level down — its chokepoint FILTERS a person out of the view the pulse kernels read, so a reversible member could still reach dissolution through the filter; measured before its promotion. PROCESS, so this class is caught at pre-proof: run the packet's own `checks` in a throwaway copy and declare every path they write; sweep `tests/` as well as `src/` for every changed symbol and retired literal.
"""

t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter: B1d v5 re-cut + pre-proof steps 11-12; ODQ addendum 23")
