# -*- coding: utf-8 -*-
"""Charter + ODQ: the EM-B3c re-cut with migration 203 (a live defense-in-depth gap), EM-B1f's seven rulings, TOOL-3's ceiling style, TOOL-4."""
import io, sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — EM-B3c RE-CUT (it closes a LIVE gap with migration 203); EM-B1f's rulings; TOOL-3's style; TOOL-4 (ODQ §934.55 and §934.47 addendum 22)

- **EM-B3c, version 2 — the charter's premise was REFUTED and a live gap was found.** The drift test DOES assert that every client denylist token has a covering SQL alternative (36 of 36). What nothing asserts is the scanner's SECOND mechanism: that every member of the client's `WORLD_SNAPSHOT_HARD_DENY` is refused by the net-current scanner's `hard_deny` array (or a covering alternative). Measured, and verified by the chair: `factionPairStates`, `envoyErrands` and `concludedWars` — three private ledgers the client refuses — are named by NO migration; 136 claimed "every CONDITIONAL_LEDGER_KEY but pantheon", the three joined the client list on 07-20, 08-03 and 08-31, and 202 copied 136's array. RE-CUT (one packet, one landing; the red-first proof IS the finding): the hard-deny SUBSET walker is written first and is RED at the base for exactly those three; **migration 203** re-creates the scanner with the array gaining the three and every other byte of the body unchanged from 202 (a contracted mechanical diff), with everything a new scanner migration owes (the rehearsal-train registration, the `scanner.owner` pin re-pointed 202 → 203, every constant or census that names the newest migration); then the walker is green, with a reconciliation arm (a declared-but-unextractable re-creation reds), a pinned NUMERIC migration sort, and a `CANNOT-CATCH:` header. NO exemption list is built: a denylist that mirrors what the client already refuses only grows, which is within the chair's delegation; APPLYING 201–203 stays the OWNER's hand. **It FLOATS WITH PRIORITY** — built as soon as the slot has room after train EM-T3's terminal.
- **EM-B1f — the chair's rulings on its compile (DRAFT, READY-able; every charter premise held; the defect reproduced before the fix: a `jailed` or `exiled` ruler reads `securityBand: holding`, `rulerId` set, while a dead one reads `unseated`):** (1) THE ARM'S MEMBERS: `exiled`, `jailed` (design §15) AND `removed` (every reading in the estate already counts it absent; a removed holder must not govern) — NOT `missing` and NOT `retired`: the estate's readings disagree about them ON PURPOSE (R18: an irreversible consequence may only follow an irreversible cause), the chokepoint FILTERS a person out of the settlement every pulse kernel reads, so joining them would silently override the house-roster reading; a missing or retired holder keeps the place until the DM or the pulse moves it, and what happens to the SEAT is the holder guard's question in EM-B1a's `set-npc-status`. (2) FORM B: an exported frozen vocabulary `OFF_STAGE_STATUSES` read by membership, absence-safe (94 % of generated NPCs carry no `status` key) — one named place a later packet reads and the totality walker judges; its bytes are re-measured at pre-proof and a rise is attributed, never a reason to choose the worse form. (3) The union-totality walker's NINTH roster row (`src/domain/roads/state.js`, which gains a trigger token) belongs to THIS packet, with the reasoned omission naming `active`, `dead` (paired by every caller), `missing` and `retired`. (4) It is placed only after EM-B1d is LANDED (three shared paths) and its pre-proof is re-run at that tip. (5) `envoyCasting`'s double refusal is the settled belt-and-braces idiom. (6) The lazy engine's ~700 B margin is a RAISE-TIME convention (the literal assertion is the law between re-mints).
- **TOOL-3's STYLE, ruled now because two waiting packets price against it:** the pulse worker (`advanceInterval.worker`, a 549-module closure that most domain packets touch) and `townSceneExport.worker` get MEASURED ceilings with a DECLARED HEADROOM (4 KB), ratcheted DOWN by the chair at every train terminal with per-module attribution — growth is noticed and named once per TRAIN, not re-minted once per packet; the generation worker's exact-size ceiling is unchanged (it guards the product's first forge).
- **TOOL-4 (NEW, tooling; after EM-T5):** the latest-wins walk over the migrations directory now exists in three copies (two shipped security guards and EM-B3c's walker); consolidate them into one shared helper with the parsing hazards EM-B3c measured (non-`$$` dollar tags are routine here; `DO`-block and `drop` + `create` re-creations) as its test table. Deferred deliberately: it edits guards that are `checks` members of LANDED packets.

"""

ODQ = """- **§934.55 ⛔ SECURITY FINDING (defense in depth; OPEN IN PRODUCTION TODAY) — THREE PRIVATE LEDGERS THE CLIENT REFUSES ARE NOT REFUSED BY THE DATABASE'S GALLERY SCANNER; THE CURE IS MIGRATION 203, AUTHORED INSIDE EM-B3c; APPLYING IT IS THE OWNER'S (__STAMP__; found by an Opus compile lane, verified by the chair at 58fcfe614).** `factionPairStates`, `envoyErrands` and `concludedWars` are members of the client's `WORLD_SNAPSHOT_HARD_DENY` (`src/domain/display/worldSnapshotPublic.js`) and are named by NO SQL migration: migration 136 (2026-07-16) claimed "every CONDITIONAL_LEDGER_KEY but pantheon", the three ledgers joined the client list on 2026-07-20, 08-03 and 08-31, and migration 202 copied 136's array verbatim. A test forces a new ledger onto the CLIENT list; nothing forces the SQL to follow. WHAT IT IS AND IS NOT: the client's public serializer is allowlist-based, so an honest client never publishes these keys — this is not a proven leak; it is the LAST LINE before an anonymous gallery read, and it would not stop a client regression (or a hand-made request) from publishing a world's faction-pair states, envoy errands or concluded wars. RULED (extending a denylist to mirror the client's only strengthens the posture — within the delegation; weakening one would be the owner's): EM-B3c is re-cut as ONE packet whose red-first proof is this finding — a subset walker RED for exactly these three, then MIGRATION 203 (the array gains the three; every other byte of the scanner unchanged from 202; the rehearsal train and the scanner-owner pin follow), then green; no exemption list is built; it floats with priority and is built right after train EM-T3's terminal. **THE OWNER'S HAND:** production stood at migration 200 at the 2026-09-16 deploy (the chair has no later reading); 201, 202 and now 203 are applied together with the push (`supabase db push` + the applied-head bump). Until then the gap is open in production, as it has been since 2026-07-20.
- **§934.47 addendum 22 — EM-B1f's COMPILE: EVERY PREMISE HELD, THE DEFECT REPRODUCED BEFORE ITS FIX, AND THE CHAIR'S RULINGS (__STAMP__; vetoable).** Measured by an Opus compile lane: a ruler whose status is `jailed` or `exiled` still reads as holding the seat (`securityBand: holding`) while a dead one reads `unseated` — design §15's jailed mayor, executed; no writer in `src/` can produce `exiled` today and the full 525-row golden corpus carries zero `jailed`/`exiled` NPCs, so the arm is inert on every existing world and no golden can move; the chokepoint has SEVEN consumers, none a display surface (a jailed NPC still appears in the dossier as jailed); and the arm trips EM-B1d's new totality walker, so the packet carries that walker's ninth roster row. RULED: the off-stage statuses are `exiled`, `jailed` AND `removed` — NOT `missing` or `retired`, which the estate reads two ways on purpose (R18's irreversibility rule); the chokepoint removes a person from the settlement every pulse kernel reads, so a missing or retired holder keeps the place until the DM or the pulse moves it, and the SEAT's fate is the holder guard's in EM-B1a. An exported named vocabulary (`OFF_STAGE_STATUSES`) over two inline comparisons, the extra bytes attributed rather than allowed to pick the worse form. *Rejected:* "only active people act" (it would let a reversible absence dissolve a house through the filtered roster). *Reversal:* one token in one frozen array, judged by the totality walker. ALSO RULED: the pulse worker's and the scene-export worker's new byte ceilings (TOOL-3) carry a declared 4 KB headroom ratcheted down per TRAIN with attribution, not an exact size re-minted per packet; consolidating the three copies of the migrations latest-wins walk is TOOL-4, after EM-T5.
"""

t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter: B3c re-cut + B1f rulings + TOOL-3 style + TOOL-4; ODQ 934.55 + 934.47 add. 22")
