# -*- coding: utf-8 -*-
"""FIX-F's findings and EM-P1's BLOCK, each given its fate the same turn. Charter amendment + ODQ §934.47 addendum 26 + §934.58 addendum."""
import io, sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — a red already on the branch (CURE-B); the fix lane's findings; EM-P1 BLOCKED and re-ruled (ODQ §934.47 addendum 26; §934.58 addendum)

**A RED ALREADY ON THE INTEGRATION TIP, found by the FIX-F lane:** the prose-numerics walker's exact-identity arm addresses allowed rows by FILE + LINE; EM-B3a added thirteen lines above a row in `worldSnapshotPublic.js` and nobody re-addressed it — a build lane's focused runs never reach that walker and its baseline is outside every manifest. Run 17 would have red on it. FATES: **CURE-B** (NEW) — every baselined row this train's landings shifted is re-addressed ONCE, addresses only, by the same cure lane and sitting as CURE-A, BEFORE run 17; the shared build brief now runs `tests/lint` WHOLE in every build's last batch (lawful reds named: the lighting census and the lane's own shifted rows, quoted for the terminal); the pre-proof brief gains **step 13** (line-addressed baselines priced at pre-proof).

| FIX-F finding | fate |
|---|---|
| FIX-F1 is LIVE and larger than the ledger said: ELEVEN option bags, not nine, never carried the tier noun, and eight disagreements are READER-VISIBLE today (a city's Economics tab prints "too small to change what the town is") — ODQ §934.22 addendum 2's "correct on screen" is refuted | CURED on the lane's branch (all eleven; a source-level guard with five plants; neither golden moved); gated batch queued; composed at EM-T4's terminal |
| FIX-F2: `weight` is absent from the detector's float tokens, but adding it convicts only four English comparatives ("carries more weight in council"); the detector has no allow-list and forbids raising its ceiling | RE-CUT as **FIX-F2b**, the same lane's next car: the SLOT is renamed `weight` → `weightWord` across the receipt pools (the estate's twice-ruled cure; it reaches the contract-parsed `RECEIPT_POOLS_LEGACY.md` and eight kind-pool walkers — blast radius measured first; a golden or a cell key moving is a STOP), then `weight` joins the tokens with zero hits; the stale `namesAScalar` citation is corrected there |
| FIX-F3 | **CLOSED — cured already** at `475021901`; recorded correction: the label idiom is the `tokenCase` three-rung ladder ending in sentence case, NOT small capitals (the PDF renderer has no small-caps face) — the chair had mis-stated it to two lanes and has corrected both |
| `SummaryTab.jsx`'s fifteen uppercase sites (the typography train's remainder) | SLOT: **FIX-F4**, a parallel lane, composed at EM-T4's terminal |
| `'FOOD SECURITY'` deliberately absent from `LADDER_WORDS` | SLOT: carried by **FIX-G2** (it re-words that card) |
| `EconomicsTab.jsx` at 600 of its 600-line ceiling | **CLOSED — not work now:** lawful and passing; the pre-proof's standing max-lines measurement forces the extraction into whichever packet next touches it |
| the print-parity suite's screen model; a stale row count in a comment; the unwritten DOM-level pair arm | SLOT: all three ride FIX-F1's commit (the pair arm if it fits in about forty lines, else its measured size comes back for a slot) |

**EM-P1 (stable identity) — its pre-proof came back BLOCKED, and the chair re-rules it:**
- **THE NPC ID SPELLING DOES NOT CHANGE.** `npc_<n>` is already persisted, keyed into the pulse's ledgers, carried by sidecars and crossed through the veil; re-spelling it to `npc:<n>` would have turned a key addition into a VALUE move across every golden and every NPC-keyed ledger for cosmetic uniformity. Stable identity adds an id where none exists; it never re-spells one that does.
- **THE FACTION HALF IS A MIGRATION, NOT A MINT, AND IT IS DESIGNED BEFORE IT IS BUILT.** Generated factions carry NO id; `factionRefOf` reads `id || name` at nine sites; the PERSISTED `linkedFactionIds` would silently flip from names to ids the moment an id exists; the packet's named mint site (`densityAscension.js`) is the SIMULATION-time planner whose `faction.<slug>` ids are written into replayed event chains (lived history — they stay). **RECON-ID** (NEW; next free seat): every entity-id namespace in one table, every handle and resolver, what a rename does to each, pinned mode, what old saves hold. The persisted value flip is put to the OWNER with that measurement.
- **ONE MINT FUNCTION PER ENTITY KIND**, pure and idempotent, called by the generator step before any sort, by the save migration, and at the PIN boundary; an arm proves read → reorder → write does not re-point ids.
- **WHERE EM-P1 SITS IS BEING MEASURED NOW:** the pre-proof lane is establishing which entity's names key EM-P1b's three choice sites and whether ANY packet on the way to the first door addresses an institution or a faction by id. If none does, EM-P1 (institutions and factions together: ONE packet, ONE golden shift, ONE signature) moves BEHIND train EM-T7 and RECON-ID, and the program's riskiest packet leaves the critical path; if one does, the narrowest institutions-only EM-P1 serves it. Train EM-T4's content is ruled from that answer.
- Its noticed items: a standing note beside the shift-record README that `pipelinePinnedMode.test.js` reds for ANY golden-moving packet (SLOT: the chair's golden-door sitting); the third NPC id namespace, the nine hand-rolled faction slugs and `linkedFactionIds`' un-owned follow-on (SLOT: RECON-ID, then the faction-identity packet); the 28 files whose observed-shape findings the ids silence (SLOT: a per-file cured-or-silenced table in the re-cut packet's pre-proof).

"""

ODQ = """- **§934.47 addendum 26 — A RED WAS ALREADY ON THE INTEGRATION BRANCH; THE FIX LANE'S FINDINGS; EM-P1 (STABLE IDENTITY) BLOCKED AT PRE-PROOF AND RE-RULED (__STAMP__; the successor chair; vetoable).** (1) The follow-up fix lane found that EM-B3a's landing had left the prose-numerics walker RED on the integration tip (its baseline addresses rows by file and line; thirteen lines were added above one) — invisible to every build lane's focused runs and outside every packet's manifest; run 17 would have failed on it. CURE-B re-addresses every row this train shifted, once, before run 17; every build now runs the whole lint directory; the pre-proof prices line-addressed baselines. (2) The "eight tabs on the tier-noun backstop" were ELEVEN and eight disagreements are reader-visible today (a city's Economics tab calls it a town) — cured on the lane's branch with a guard; the `weight` token becomes a slot rename (FIX-F2b); the uppercase twins were already cured. (3) EM-P1's pre-proof refuted two of the packet's premises. RULED: the NPC id spelling does NOT change (`npc_<n>` is persisted and keyed everywhere; stable identity adds ids where none exist, it never re-spells one); the FACTION half is the estate's own "governed ID-only migration" — generated factions have no id, nine readers take `id || name`, and the persisted `linkedFactionIds` would flip from names to ids — so it is DESIGNED from a recon (RECON-ID) before it is built, and that persisted value flip is the OWNER's question when the measurement is in; simulation-time houses keep their `faction.<slug>` ids (lived history). Whether EM-P1 can leave the critical path entirely (one packet, one golden shift, behind train EM-T7) is being measured now.
- **§934.58 addendum — THE GOLDEN SIGN-OFF'S SCOPE NARROWS, AND THE OWNER IS TOLD (__STAMP__).** The owner signed for FIX-G1's one row and for EM-P1's stable-identity movers as the chair had described them ("permanent NPC, institution and faction ids"). An hour later EM-P1's pre-proof showed that description was wrong in two ways: NPC ids already exist (so nothing about NPCs should move — and under the chair's ruling nothing will), and faction ids are a persisted-handle migration that needs its own design, its own measurement and ITS OWN SIGNATURE. The door's law is also one cause per record: FIX-G1 and EM-P1 are TWO signed records in one sitting, not one. So the signature the owner gave covers, as of now: FIX-G1's one row (unchanged, exact), and EM-P1's institution ids IF the measurement keeps them at train EM-T4 — and the chair returns to the owner with the exact price before opening the door for anything but FIX-G1's row.
"""

t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter: CURE-B, FIX-F fates, EM-P1 re-ruled; ODQ add. 26 + 934.58 addendum")
