# -*- coding: utf-8 -*-
"""RECON-ID's findings ruled: EM-P1 WITHDRAWN; EM-R6 moved up; the catalogId re-stamp put to the owner. Design §22.4 + charter + ODQ §934.59."""
import io, sys

d, c, f, stamp = sys.argv[1:5]

DESIGN = """

### 22.4 THE IDENTITY TABLE — stable identity needs NO new id (the chair, __STAMP__; from RECON-ID over the full 525-row corpus; ODQ §934.59; vetoable)

What an entity IS in this estate, as measured (kit `findings/RECON-ID/`), and what the editor relies on:

| kind | its identity | stable under | the editor's join |
|---|---|---|---|
| **NPC** | a stored `id` on every one (5,171 of 5,171) in THREE generated or created spellings — `npc_<n>` (the roster's draw order), `npc.<factionSlug>_<roleSlug>_<i>` (287 structural figures minted by `factionRoles.js`), `npc.<slug>_<hash>` (created later) | save → load, reorder, the public veil, rename. ⚠ NOT same-seed regeneration under a different tier or culture (the counter names a different person) — which is why an id is NEVER re-derived from position, by a migration or anything else | the merge keys `npcs` by `id`; a newcomer takes the lowest unused `npc_N`, as `regenerationPreservation.js` already does |
| **INSTITUTION** | no `id`; the town map's `anchorForInstitution` — `cat:<catalogId>` → `uid:<localUid>` → `name:<slug>` — unique in every corpus row, consumed by twenty modules through `anchorKey` | regeneration and rename for the 88 % stamped with `catalogId`; ⚠ the 12 % the cascade pass and the coherence repair ADD AFTER the stamp (2,083 of 17,361) fall to `name:`, so a rename moves their map pin, interior, fog state and glyph | the merge keys by `name`; renames and removals go through EM-R6's cascade |
| **FACTION** | no `id` on generated data (0 of 3,378); the DISPLAY NAME (`seatKey`), by design; simulation-time houses carry `faction.<slug>` (replayed history — immutable) | a rename: ALL eleven stored handle paths are on `factionRename.js`'s cascade — 0 of 15 handles stale, executed | the merge keys by `name` |

**RULED.** (1) **EM-P1 IS WITHDRAWN.** No NPC id is re-spelled; no faction id is minted — a mint is not a key addition but a BEHAVIOUR CHANGE: nine `id || name` readers would silently re-key, the persisted `linkedFactionIds` would flip from names to ids, and three id-ONLY readers that are dark on generated data by their own written decision (`rulingPower`'s succession discriminator, `warSeatBooks`' authority signature, `warPeaceDecision`) would light up; the observed-shape register's 33 findings are the census of that blast radius, not a reason to mint. (2) **THE ONE REAL GAP IS THE INSTITUTION CASCADE:** 42 stored paths hold an institution's exact name and NO rename or removal writer exists — renaming "Mages' guild" leaves 9 of 10 handles stale and nothing throws. EM-R6 is compiled NOW from the recon's executable census and lands BEFORE the institution-rename op (EM-B1c) can be promoted. (3) **THE ONE OWNER-GATED REPAIR** is re-running the existing `catalogId` stamp after the last roster mutation (**EM-P1d**, chartered conditionally): a persisted key on the 12 % and 417 of 525 golden rows re-signed — asked of the owner in plain words; EM-R6 is compiled to be correct under either answer.
"""

CHARTER = """## Amendments of __STAMP__ — EM-P1 WITHDRAWN; EM-R6 MOVES UP; EM-P1d awaits the owner (design §22.4; ODQ §934.59)

- **EM-P1 (stable identity) is WITHDRAWN** — RECON-ID measured that the smallest stable identity contains no new identity (design §22.4). Its kit drafts are superseded; nothing was ever placed in the tree. EM-P1b stands as re-cut (the institution anchor; the NPC id).
- **EM-R6 (the institution rename + removal cascade) MOVES UP: it lands BEFORE EM-B1c** (whose institution-rename op has no cascade to call) and before the first apply point. Its compile is running from the recon's census (42 paths: 33 strict, 9 polysemous each put to the chair; `factionRoles.js`'s `linkedInstitutionIds`; the member mirror; removal semantics per row; the dangling gate a DELTA by kind; an anchor section correct under both owner answers). If it exceeds the budget it splits at its natural seam — RENAME first (EM-B1c waits on it), REMOVAL second (the removal op and the merge wait on it).
- **EM-P1d (NEW, CONDITIONAL ON THE OWNER): every institution is stamped with its catalog id after the last roster mutation** — the stamp runs at step 6 and 2,083 of 17,361 institutions are added at steps 8 and 15; all 66 of their names resolve in the catalog. It writes one persisted key on those institutions and moves 417 of 525 generator-golden rows: the OWNER's signature, its own record. Placed (if YES) beside EM-R6, before EM-B1c.
- **Fates of RECON-ID's noticed items:** the wrong mint site and the ~25 `id || name` ledger keys — CLOSED with the decision not to mint; the three dark id-only readers — CLOSED: they stay dark, as their own headers say is correct; the NPC id family enumerated in one place — DONE in design §22.4; `relationships[].npc1Id/npc2Id` as a zero-dangle join the NPC rename lane does not use — SLOT: EM-B1c's pre-proof measures whether to adopt it; `conflicts[]` carry no id and no exact faction name — SLOT: a row on EM-C4a's card list at its compile; `powerStructure.factions[].name` never exists on generated data — CLOSED (the cascade row is correct as written); ⚠ `settlement.id` is a hash of the SEED alone — 516 of 525 corpus rows share one id, and it crosses the public veil — SLOT: REVIEW-P (the public-path review, dispatched the moment run 17 exits) measures who keys on it (gallery rows, realm placement, forks) and whether two published worlds grown from one seed can collide.

"""

ODQ = """- **§934.59 STABLE IDENTITY NEEDS NO NEW ID — EM-P1 IS WITHDRAWN; ONE REAL GAP (INSTITUTIONS HAVE NO RENAME OR REMOVAL CASCADE) MOVES UP; AND ONE QUESTION IS THE OWNER'S (__STAMP__; measured by an Opus recon over all 525 golden rows; design §22.4; vetoable).** MEASURED: every NPC already carries a stored id (5,171 of 5,171) that survives save, reload, reorder, rename and the public veil; every FACTION handle (eleven stored paths) is already on the rename cascade — 0 of 15 stale after a rename on real data; every INSTITUTION already has a unique, regeneration-stable map anchor. And minting a faction id would not be a key addition but a behaviour change: nine readers would silently re-key, the saved `linkedFactionIds` would flip from names to ids, and three readers that are deliberately dark today (the succession discriminator, the war-seat authority signature, a war-peace comparison) would light up. RULED: EM-P1 is WITHDRAWN — no id is minted or re-spelled, and the 525-row golden shift it would have cost is not spent. THE REAL GAP: 42 stored paths hold an institution's exact name and nothing follows a rename or a removal — renaming "Mages' guild" leaves 9 of 10 references stale (Services still lists its spells, Defense still credits it, two people's postings still read it, a supply chain names a house no longer on the roster) and nothing throws. EM-R6, the institution cascade, is compiling now and moves ahead of the rename op. **THE OWNER'S QUESTION, in the recon's plain words:** *today 12 % of the buildings in every settlement (2,083 of 17,361 across the corpus — every workshop the cascade pass adds and every house the coherence pass repairs in) have no permanent tag; the other 88 % do. The fix runs the tagging step we already have a second time, after the last building is added. It changes no number, no name and no dice roll, but it writes one new field onto those buildings, so the golden record is re-signed for 417 of its 525 rows. **Do we tag them?*** YES: nothing visible changes today, and when Edit Mode ships, renaming ANY building keeps its place on the map, its interior, its fog state and its glyph — one more signed golden shift (its own record; the signature of this afternoon covers only FIX-G1's row). NO: nothing changes today either, and when Edit Mode ships, renaming one of those buildings silently moves it on the town map, discards the DM's nudge and re-rolls its glyph while the other 88 % behave — it would look like a map bug. *The chair recommends YES.* EM-R6 is compiled to be correct under either answer.
"""

s = io.open(d, encoding="utf-8").read()
assert "### 22.4 " not in s and "### 22.3 " in s
io.open(d, "w", encoding="utf-8").write(s.rstrip("\n") + DESIGN.replace("__STAMP__", stamp))
t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("design 22.4; charter: P1 withdrawn, R6 up, P1d conditional; ODQ 934.59")
