# -*- coding: utf-8 -*-
import sys
f, stamp = sys.argv[1:3]
row = ("- **§934.19 addendum 3 — EM-P3's WORKER RISE, NAMED AND VETOABLE: +80 B, AFTER THE PLACEMENT CURE TOOK +634 B OFF THE TABLE (__STAMP__; the successor chair; offered for the owner's ratification like the mints it follows).** "
"EM-P3 (the world-fact option sets' one home) landed at f4e5b64c5 as the first packet to carry its own byte budget. Priced on paper by its pre-proof lane, it would have put +634 B into the ZERO-slack generation worker for a citation map the worker never reads; the chair ruled the cure is the PLACEMENT (the map lives in the domain-reachable leaf, out of `resolveConfig`'s import closure). Built and measured by a real `npm run build` and a 545-chunk per-module sweep: the generation worker 1,401,128 -> **1,401,208 B (+80 B**, against an estimate of +206 and the packet's bound of 412; modules 230 -> 231; exactly three modules moved anywhere in the build and all three are EM-P3's own), the lazy engine 678,131 -> **677,935 B** (196 B SMALLER; never edited), the eager first-paint set byte-identical at 268 modules, and the domain leaf present in NO emitted chunk. `WORKER_BUNDLE_CEILING_BYTES` re-minted to the exact figure in `91d5f155b`'s form, MONOTONE-DOWN from here; `verify:dist` STRICT DIST OK, 59 files, 538 tests, by the lane and again by the chair at the landing. "
"THE LANE'S JUDGMENT CALL, accepted and vetoable: the packet's section 6 spelled the forwarding export as `export { TERRAIN_WEIGHTS, CULTURES }`, which the packet's OWN manifest refuses (it pins `export const TERRAIN_WEIGHTS` and `export const CULTURES` verbatim in `resolveConfig.js`, as the LANDED SCW-0 does); the lane spelled them `export const X = CANONICAL_X` — the list still spelled once, every landed row still true — for 12 of the 80 bytes. A veto takes the `export {}` form, retires the two symbols at that path (discharging SCW-0's rows) and re-mints 12 B lower. THE PROCESS CURE: the pre-proof gains step 10 — every required symbol must still hold AFTER the packet's own edits; a symbol the packet moves is a `retiredSymbols` row — because every check before `check:packet` runs against the pre-edit tree.\n")
o = open(f, encoding="utf-8").read().rstrip("\n")
open(f, "w", encoding="utf-8").write(o + "\n" + row.replace("__STAMP__", stamp))
print("ODQ §934.19 addendum 3 written")
