# -*- coding: utf-8 -*-
"""EM-P1 leaves the critical path; train EM-T4 becomes the composition train; EM-P1b re-cut; FIX-G's findings fated. Charter + ODQ §934.47 addendum 27."""
import io, sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — EM-P1 LEAVES THE CRITICAL PATH; TRAIN EM-T4 IS RE-DEFINED; EM-P1b RE-CUT (ODQ §934.47 addendum 27)

**Measured by the EM-P1 pre-proof lane (kit `findings/EM-P1-preproof/`, §9):** NOTHING on the way to the first editor door addresses an institution or a faction by an id — EM-D0's first door is the NPC's card (NPC ids exist and are persisted), EM-B1a only shape-checks an op's target, EM-B1c's renames delegate BY NAME to the existing cascade, and the rest address steps, keys, fields, statuses or SQL. And INSTITUTIONS ALREADY HAVE A REGEN-STABLE ANCHOR: `src/domain/townMap/anchors.js`'s `anchorForInstitution` (`cat:<catalogId>` → `uid:<localUid>` → `name:<slug>`), consumed by seven modules, written for exactly the problem EM-P1 states.
- **EM-P1 MOVES BEHIND TRAIN EM-T7 AND BEHIND RECON-ID, WHOLE:** one packet (or none, if the recon shows the existing identities can be made total), ONE golden shift, ONE owner's signature — never an institutions-now / factions-later split, which would move all 525 golden rows twice under two signatures and buy nothing. The program's riskiest packet is off the path to the first door.
- **EM-P1b NO LONGER DEPENDS ON EM-P1.** Its three name-keyed choice sites are re-keyed on identities that ALREADY exist: the institution description variant (`assembleInstitutions.js`) and the glyph choice (`glyphAssign.js`, which already reads `anchorKey` first) on `anchorForInstitution`; the NPC pair site (`npcData.js`) on `npc.id`. The earlier amendment's "re-keyed on the stable id" is read as "the stable identity each entity already carries". It stays in train EM-T5; its compile carries this row.
- **TRAIN EM-T4 IS RE-DEFINED AS THE COMPOSITION TRAIN** (it had been "EM-P1 alone"): after run 17's green — compose TOOL-1 and TOOL-2, then the finished parallel fixes (FIX-F1, FIX-G2, FIX-G1 with its ONE-ROW golden re-record executed by the chair under the owner's signature of 2026-09-19, and FIX-F2b / FIX-F4 / FIX-T1 as they finish); in the slot, EM-B3c version 2 (the security gap, migration 203) and EM-P2 version 3; TOOL-3's ceilings; then its terminal full check validates the composed tree. Every slot that said "composed at EM-T4's terminal" stands under this definition.
- **A DEPENDENCY DEFECT, the A2a/A2b shape again:** EM-B1a imports an `EntityRef` typedef and names EM-A1 as its source, but EM-A1's row for `src/domain/edit/types.js` declares only `FieldKind` and `FieldDeclaration`. FATE: EM-A1's compile (queued behind EM-P2 version 3) CREATES `types.js` with `EntityRef` beside the two field types — a declaration names entity kinds, so the reference type is its to own — and EM-B1a MODIFIES that file to add `Op`. Both pre-proofs carry this row.

**FIX lane G's findings, fated:** FIX-G2 and FIX-G1 are built and staged (the bar is named "Stores and supply" through the `tokenCase` ladder; the viability summary counts the published list at one site, 370 stated counts and 0 disagreements over the 525 rows, and the zero-slack worker SHRINKS by 47 bytes) — gated batch queued. One number wearing three names across the Overview, the Defense tab and the PDF, and the PDF's Systems Health caption naming readings its chapter does not render → SLOT: **FIX-G3**, a parallel lane after FIX-G2 is composed (measure first whether the three are one number). The six title-cased Systems Health bar labels and `'FOOD SECURITY'`'s place on the ladder (both need a structural handle on the category header, pinned by element) → SLOT: **FIX-F4**, with `SummaryTab.jsx`'s fifteen sites. That the severe food-import dependency is filed under `issues` rather than the dependency list → **CLOSED — by design:** a severe dependency is shown to the DM as an issue, and after FIX-G1 the sentence and the list agree.

"""

ODQ = """- **§934.47 addendum 27 — STABLE IDENTITY LEAVES THE CRITICAL PATH: NOTHING BEFORE THE FIRST EDITOR DOOR NEEDS AN INSTITUTION OR FACTION ID, AND INSTITUTIONS ALREADY HAVE A STABLE ANCHOR (__STAMP__; the successor chair; vetoable).** Measured by the pre-proof lane: the first door is the NPC's card (NPC ids exist), the ops layer only shape-checks a target, renames delegate by name to the existing cascade, and the town map already gives every institution a regeneration-stable anchor (catalog id, else a local uid, else a name slug) that seven modules consume. RULED: EM-P1 moves behind train EM-T7 and behind a recon of what identity already exists (RECON-ID, running) — whole, never split, so the goldens move ONCE under ONE signature, or not at all if the recon shows the existing identities can simply be made total; EM-P1b's three prose-and-glyph choice sites are re-keyed on identities that already exist (the institution anchor; the NPC id) and no longer wait for EM-P1; train EM-T4, which had been "EM-P1 alone", becomes the COMPOSITION train — after run 17: the two tooling cures, the finished parallel fixes, the security packet with migration 203, EM-P2 version 3, the worker ceilings, then a full check over the composed tree. FIX-G1's one-row golden re-record — the only golden shift now in sight — is executed there by the chair under the owner's signature of this afternoon, exactly as signed. *Rejected:* an institutions-only EM-P1 now (two golden shifts, two signatures, and the narrowest packet that serves a real need before the door is empty). ALSO CAUGHT: EM-B1a imports a typedef its declared source, EM-A1, never creates — fixed in both packets' pre-proofs.
"""

t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter: EM-P1 behind T7; T4 = the composition train; P1b re-cut; ODQ add. 27")
