# -*- coding: utf-8 -*-
"""Write design §21, the charter's amendments and the two ODQ rows (run 16 green; EM-P2 STALE)."""
import sys

d, c, f, stamp = sys.argv[1:5]

DESIGN_21 = """

## 21. Generation's chosen facts are MEASURED BY EXECUTION — EM-P2 re-cut (the chair, __STAMP__; ODQ §934.47 addendum 14; under the owner's delegation, vetoable)

**What happened.** EM-P2 version 2 registered generation's choosers by a STATIC scan of three spellings (`rng.fork(`, `pickRandom(`, `createPRNG(`) with a both-directions totality arm. Its Opus build lane STOPPED before writing a line (zero edits; the STOP is in the chair kit's findings): the three spellings are a proper subset of generation's draw vocabulary — `pickRandom2`, a byte-identical alias, has 50 call sites the scan cannot see; four live keyed forks hang off receivers other than `rng`; and 22 files draw through the AMBIENT channel (`kernel/rngContext.js`), which EM-P0's own evidence measured carrying 62 of the population step's 67 derive-half draws. The totality arm would have run GREEN over a denominator it did not have. It also found the row could not carry a fork key (one symbol, four fork strings), that stream-minting choosers have no truthful `outputKey`, that the packet's example path `powerStructure.seats[].holder` exists nowhere (and `powerIntent`, a `provides` of a root-writing step, never reaches the record), and that the copied resolver mis-attributes choosers hosted in `registerStep` callbacks.

**The ruling: no static idiom scan can be total over a generator whose entropy flows ambiently, so totality moves to where it is sound.**
1. **Tier 1 — the pin-level register, total BY CONSTRUCTION and classified BY EXECUTION.** The pipeline already declares its own unit: `registerStep` with `provides` and `mutates` (22 steps and 57 provided keys at f31ca0eb8), and EM-P0's landed runner already pins by those keys. Tier 1's rows are exactly `(step, key)` for every key a step provides or mutates; the both-directions equality is against `getStepMeta()`, so a new step or key cannot escape it. Each row carries what EXECUTION measures over the golden corpus: whether the step DRAWS at all (a counting stream over the step's fork, its sub-forks and the ambient channel — every channel funnels through the stream's `random()`, which is why this sees what no spelling can), whether THIS key is `drawn` or `pure` (the step re-run on a PERTURBED stream with identical inputs: a key whose value moves is drawn — §14's "root means CHOSEN, not computed", made a measurement), and whether the key REACHES THE ASSEMBLED RECORD. The fork labels a step uses are the census's observed DATA, never a row key (so the arity problem dissolves). Stream MINTS are not rows: they are the entropy census's (`createPRNG(`), cited, not re-scanned.
2. **Tier 2 — the field-level roots EM-A1 joins on, declared and then held to measurement.** One row per editable root field `{ forkId, step, module, symbol, outputKey (the RECORD PATH), cardShape }` — exactly the fields EM-A1's draft declares, re-cut against the LIVE record (`powerStructure.seats[].holder` is struck; the power card's paths are what the record has). Each row must resolve on a generated settlement, sit under a Tier-1 `drawn` key, name a symbol that resolves against SOURCE by a resolver that understands `registerStep('<name>'` hosts (the model's resolver is NOT copied where it is wrong, and the model is not edited), and be ENTROPY-SENSITIVE under its step's perturbation. Its blind half is stated as `HABIT_FORK_REGISTRY` states its own: field-level rootness inside a drawn key is a reviewed declaration — the census can refute it, not derive it (CANNOT-CATCH: a field computed from a drawn sibling moves with it).
3. **What the measurement is FOR, beyond the register.** It is the map EM-B2a needs before it can be compiled honestly: which steps draw into keys they only MUTATE (a pinned roster re-mutated by a drawing pass would flicker on every edit), which drawn keys never reach the record (`powerIntent`: not pinnable from a record as the runner's rule stands), and therefore how the runner's partial-pin refusal — today "every `provides` key or none" — must be restated over the DRAWN keys (chartered as **EM-P0b**: a step declares its `choosers`, the census holds the declaration equal to the measurement, the runner reads it).
4. **Measure before compiling (the lesson of EM-P0 version 1, applied to the chair).** This section is a DESIGN until an Opus recon lane has executed the census as a prototype in scratch and reported what the pipeline actually shows — the drawing steps, the drawn keys, the mutating drawers, the off-record keys, any entropy side channel the step stream does not carry, and the cost per corpus row. EM-P2 version 3 is compiled against that report, and this section is amended by what it finds.

**Status.** EM-P2 is STALE at the build lane's STOP; train EM-T3 proceeds with EM-P3, EM-B3a and EM-B1d, none of which depends on it; EM-A1 (train EM-T5) still waits on it.
"""

CHARTER = """## Amendments of __STAMP__ — EM-P2 STALE and re-cut; EM-P0b chartered (design §21; ODQ §934.47 addendum 14)

- **EM-P2 (version 3, to be compiled AFTER the recon's executed prototype):** the generation register in two tiers — Tier 1 `(step, key)` for every `provides`/`mutates` key, both-directions equal to `getStepMeta()`, each row classified BY EXECUTION over the golden corpus (the step draws / the key is `drawn` or `pure` under a perturbed step stream / the key reaches the assembled record; fork labels as observed data; stream mints cited from the entropy census, never re-scanned); Tier 2 the field-level root rows EM-A1 joins on `(cardShape, outputKey)`, each resolving on a generated record, under a `drawn` key, entropy-sensitive, its symbol resolved against source by a `registerStep`-aware resolver. NO static idiom scan, NO `forkKey` in a row, NO copy of the model's resolver where it is wrong. C `src/domain/generation/generationForkRegistry.js`; T the static arms under `tests/lint/` (+ the mutation-coverage row), the census by execution under `tests/generators/` with its instrumentation in `tests/helpers/`; the mismatch arm PRINTS the fresh literal and fails — it never writes.
- **EM-P0b (NEW, after EM-P2 v3; before EM-B2a):** the runner's partial-pin refusal is restated over a step's declared `choosers` (its DRAWN keys) instead of every `provides` key; each drawing step declares `choosers` in its registration; the census holds the declaration equal to the measurement; the rule for a drawing step that only MUTATES, and for a drawn key that never reaches the record, is settled from the recon's measurement. An approved-override candidate (one line in each drawing step's registration) — priced at compile.
- **Train EM-T3 proceeds without EM-P2:** EM-P3 · EM-B3a · EM-B1d, one at a time in the slot, each made READY by an Opus pre-proof lane at the tip; EM-P2 v3 joins the first train whose base it is pre-proved at. EM-A1 still depends on it.
- **Ceilings are PRICED AT PRE-PROOF for every packet that touches the generation worker's closure** (the process law of ODQ §934.19 addendum 2): the packet's manifest carries the two bundle-ceiling tests as TEST rows with a stated byte bound, and the build lane re-mints them under the chair's standing conditional ruling — a real `npm run build`, the kit's per-module attribution showing ONLY the packet's own modules moved, growth inside the priced bound — or STOPS. EM-P3 (`resolveConfig.js`) is the first.

"""

ODQ = """- **§934.16 addendum 2 — CHECK 2 RUN 16 GREEN END TO END: TRAIN EM-T2's TERMINAL IS CLOSED (__STAMP__; the successor chair).** Bare `npm run check` on f31ca0eb8 (the consist with the T2 cure 023eda2ec, the ceilings 91d5f155b, the §19 fold 00fab686d and EM-P2's re-pin), detached, 14:37:45 → `run 16 exit 0 at 14:58:56` (`logs/consist-check-2-run16.log` in the chair kit): every validator (hazard registry OK; the pre-mortem's victory; `implementation-packets valid: 188 packets (1 READY)`), `typecheck-ratchet OK (167, ceiling 167)`, `domain-strict ✓ (1113, ceiling 1113)`, lint 0 errors, `test-ratchet OK — no test regressions (0 known failure(s) of 33555 tests, ceiling 0)`, build 18.73 s with 304 prerendered routes, `STRICT DIST OK — 59 file(s), 538 test(s)`. EM-P0's landing is now a landing with its terminal's green.
- **§934.47 addendum 14 — EM-P2 STALE: THE BUILD LANE'S STOP REFUTED THE STATIC SCAN; GENERATION'S CHOSEN FACTS WILL BE MEASURED BY EXECUTION (__STAMP__; the successor chair, under the owner's delegation; vetoable).** The re-dispatched Opus build lane sealed at f31ca0eb8 and STOPPED with zero edits: the packet's three scanned spellings are a proper subset of generation's draw vocabulary (`pickRandom2` ×50 sites; four keyed forks on other receivers, one of them the entropy census's own NC-1 control line; the ambient `rngContext` channel in 22 files — 62 of 67 derive-half draws by EM-P0's own evidence), so the both-directions totality arm would have run GREEN over a denominator it did not have; one row cannot carry four fork strings; stream mints have no truthful `outputKey`; the example path `powerStructure.seats[].holder` exists nowhere and `powerIntent` never reaches the record; the copied resolver mis-attributes `registerStep`-hosted choosers. Every census figure the packet DID pin reproduced exactly — the stop is the packet's, not the tree's. RULED (design §21): totality moves to where it is sound — Tier 1 is `(step, key)` over the pipeline's own `provides`/`mutates`, equal to `getStepMeta()` by construction and classified BY EXECUTION over the golden corpus (draws · drawn-or-pure under a perturbed stream · reaches the record); Tier 2 is EM-A1's field-level roots, declared and held to measurement; no static idiom scan, no fork key in a row. CHARTERED: EM-P0b (the runner's refusal restated over a step's declared, census-verified `choosers`), and the CEILINGS PRICED AT PRE-PROOF for every packet touching the generation worker's closure. THE CHAIR APPLIES EM-P0 VERSION 1's LESSON TO ITSELF: an Opus recon lane EXECUTES the census as a prototype before version 3 is compiled, and §21 is amended by what it measures. T3 proceeds with EM-P3, EM-B3a, EM-B1d. ALSO RECORDED for a later cure, not touched: the model walker's `codeOnly` strips import lines with a leading whitespace class that, under the multiline flag, also eats preceding newlines and can drift line-anchored declaration matching (a space-or-tab class is the safe spelling) — `chooserTotality.walker.test.js` is green today; a cure lane re-proves it after T3.
"""

s = open(d, encoding="utf-8").read()
assert "## 21." not in s
open(d, "w", encoding="utf-8").write(s.rstrip("\n") + DESIGN_21.replace("__STAMP__", stamp))

t = open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))

o = open(f, encoding="utf-8").read().rstrip("\n")
open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("design §21; charter amendments; two ODQ rows written")
