# -*- coding: utf-8 -*-
"""RECON-G's findings, each given a fate the same turn (the owner's law). Charter amendment + ODQ §934.57."""
import io, sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — RECON-G's findings, each given its fate (ODQ §934.57)

| finding (kit `findings/RECON-G/`) | fate |
|---|---|
| THE REPORTED DEFECT IS REFUTED: over all 525 golden rows the food-security WORD is exactly what its thresholds say (0 disagree), and no band was re-cut on 2026-07-22 — that commit touched `OverviewTab.jsx` only and put the word and the bar side by side for the first time | **CLOSED — not a defect** as reported; the 2026-09-18 report's "domain re-grade" reading is withdrawn |
| WHAT IS REAL: the WORD (cut from the food deficit) and the BAR beside it (`resilienceScore`: granary months, source diversity, import independence, adequacy) are two different facts shown as one — a bar of 73 sits beside three different words; "Deficit" averages a LONGER bar than "Active Famine"; 124 of 525 towns print an alarming word beside a bar at or past half | SLOT: **FIX-G2** (NEW, a PARALLEL display-only lane; zero goldens, zero saves): the bar is NAMED for what it measures and the caption is corrected, in the tome's grammar; composed at EM-T4's terminal with the other fixes |
| THE LIFECYCLE FINDING: the bar is re-graded every tick, the word NEVER — after one quiet campaign month 43 of 63 settlements print a word the thresholds contradict, while the Overview's own caption promises "Food Security is re-judged as the campaign advances" | **THE OWNER'S DECISION POINT, put to the owner today:** does "Food Security" name the land's STRUCTURAL condition (frozen at generation — then the caption is wrong and FIX-G2 corrects it) or the table's LIVED condition (re-graded at the tick — then it is a tick-wave packet, it moves no golden, and it changes lived wording on every existing save)? FIX-G2 ships the honest caption either way |
| the `Surplus` rung is unreachable: the largest surplus in 525 towns is 8 against a threshold above 40, and the Compendium documents it | **THE OWNER'S DECISION POINT** (a `src/domain` threshold is the owner's): lower the threshold, or strike the rung from the Compendium — asked with the question above |
| FIX-G1 MEASURED: exactly 1 of 525 rows; `src/generators/economy/viability.js` counts dependencies over `issues` AND `warnings` while the published list reads `warnings` alone (two `foodBalance.js` arms push a DEPENDENCY into `issues`); the LIST is right (`metrics.dependencyCount` agrees with it 525/525); a one-site cure re-records ONE generator-golden row and ZERO prose-manifest rows; saved worlds keep the old sentence (stored verbatim) | SLOT: **FIX-G1** is built as a PARALLEL lane that stops at the golden; its one-row re-record RIDES EM-P1's SIGNED GOLDEN DOOR at train EM-T4 (one signing, each cause attributed — EM-P1's pre-proof measures whether the door allows it). THE OWNER signs the before/after sentence |
| HAZARD: the kit's recon `instrument.mjs` changes directory into the READ TREE at import, so a relative write lands in a tree other lanes read | **CLOSED by cure, same turn:** a loud header on every kit copy, a line in the compile and recon launch texts, and the two running compile lanes warned |
| RECON-G's unmeasured: the orchestrator ticks by the week (shifts the calendar, not the outcome); the prose-manifest row count under the rejected derive-from-score cure; off-corpus frequency | **CLOSED — not work:** each matters only to a cure that was refused |

"""

ODQ = """- **§934.57 THE OVERVIEW'S FOOD CARD: THE REPORTED DEFECT IS REFUTED, A LARGER ONE IS REAL, AND TWO QUESTIONS ARE THE OWNER'S (__STAMP__; measured by an Opus recon lane over all 525 golden rows; kit `findings/RECON-G/`).** REFUTED: the 2026-09-18 report said the Overview's resilience score disagrees with its band label because of a 2026-07-22 domain re-grade. Over 525 rows the WORD is exactly what its thresholds say (0 disagree), and that commit touched one display file — it put the word and the bar beside each other for the first time. REAL: they are two different facts shown as one. The WORD is cut from the food deficit; the BAR is a composite of granary months, source diversity, import independence and adequacy — so a bar of 73 sits beside three different words, "Deficit" averages a longer bar than "Active Famine", and 124 of 525 towns show an alarming word beside a bar at or past half (Schwarzwalde, a metropolis: "Import-Dependent" beside a bar 73 % full). AND THE LIFECYCLE: the bar is re-graded at every tick, the word never — after ONE quiet campaign month 43 of 63 settlements print a word its own thresholds contradict, under a caption that promises "Food Security is re-judged as the campaign advances". RULED (display-only, zero goldens, zero saves; vetoable): FIX-G2 names the bar for what it measures and corrects the caption. **THE OWNER'S TWO QUESTIONS:** (1) does "Food Security" name the land's STRUCTURAL condition, frozen at generation, or the table's LIVED condition, re-graded at the tick? Lived costs no golden but changes the wording on every existing save as it next advances; structural keeps every save and makes the caption the only thing that was wrong. *The recon's measure: over twelve quiet months the frozen word is right on 63 of 63 under the structural reading and wrong on 34 of 63 under the lived one.* (2) the `Surplus` rung is unreachable — the largest surplus in 525 towns is 8 against a threshold above 40 — lower the threshold, or strike the rung from the Compendium? ALSO MEASURED — FIX-G1: the viability summary's six-beside-five is exactly 1 of 525 rows; the list is right and the sentence over-counts (it reads a second drawer the list never shows); a one-site cure re-records ONE generator-golden row and no prose row; saved worlds keep the old sentence. It is sequenced to ride EM-P1's signed golden door at train EM-T4 — **the owner signs:** "…has 6 operational dependencies…" becomes "…has 5 operational dependencies…" for one town (`town · germanic · mountain · mountain_pass`). *Rejected:* deriving the word from the bar's score (it would move 208 of 525 printed labels, all 525 generator-golden hashes, and destroys information — two score values carry three words each).
"""

t = io.open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
io.open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = io.open(f, encoding="utf-8").read().rstrip("\n")
io.open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter: RECON-G's fates; ODQ 934.57")
