# -*- coding: utf-8 -*-
"""Design §22.1 (ARCH-REDERIVE version 2), the charter's amendment, ODQ §934.47 addendum 19."""
import sys

d, c, f, stamp = sys.argv[1:5]

DESIGN = """

### 22.1 ARCH-REDERIVE, version 2 — the whole seam EXECUTED; the consequence of an edit is the DIFFERENCE between two re-derivations (the chair, __STAMP__; ODQ §934.47 addendum 19; vetoable)

A second Opus recon prototyped ALL of §22 at once through in-memory overrides (kit: `findings/RECON-ARCH-REDERIVE-2.report.md`, `tools/rederive-prototype-2/`), inert with no held bag (the committed golden hash, a 25-row stride and 63/63 plain runs all identical).

**What held.** ⭐ THE EIGHT EDITS RUN, on a village, a town and a city, 24 trials, 0 throws: terrain → desert RUNS (§14's flagship), the seat change STICKS, the power share STICKS, a culture change KEEPS THE TOWN'S NAME, a rename through the cascade leaves 0 new dangling joins, add and remove an institution stick and the services and income follow. Rulings 5 (no schema change for the power card — the share and the seat stick because the replay does not run under a held power structure), 6 (the clone: 0/63 caller mutations at 1.0–1.7 %) and ruling 1's roster claim (63/63) are CONFIRMED; ruling 4 is load-bearing (without it 9/63 throw with no edit at all); trace entries carry their `step` 95/95, so ruling 8's partition is exact; with the name held no prose speaks another name; and a re-derivation is CHEAPER than a plain generation at every tier (5.4 vs 6.6 ms for a thorp to 29.0 vs 31.7 ms for a metropolis). The §22 paragraph put to the owner is out of date in the DM's favour: the flagship runs.

**What §22 got wrong, and the corrections (all taken as measured).**
1. *"Leaves it as it is" is wrong for a writer that DRAWS on a shared stream.* Skipping the settlement-name mint (2 draws on the assembly step's shared ambient stream) moves `pressureSentence` and `arrivalScene` in 63/63. RULED: a held writer on a SHARED stream CONSUMES ITS DRAWS AND DISCARDS THE RESULT; only a writer inside its own named child stream (`enrichNpcCoherence`) is skipped.
2. *MIRROR writers are not producers.* `relinkFactionMembers` copies NPC objects into `factions[].members[]`; held-and-skipped, a member chip keeps the old role and title after an edit. RULED: a mirror always runs; the writer census classes every writer as producer · mutator · enricher · replay · mint · MIRROR.
3. *Ruling 4's second half is unreachable* — `assertStableGeneratedRoster` runs only inside the power replay, which a held power structure turns off. Struck. The freshness assert has THREE call sites (`powerEconomyReconcilePass.js:41`, `assembleSettlement.js:204`, `:223`); its fingerprint is a derived RECEIPT, recomputed at the end and excluded from the flicker gate.
4. *Ruling 8's partition key* is every step whose entries are ABOUT a held key (the four institution repair passes emit fewer entries over a held roster, 50/63), not the producers alone.
5. *`stress` is RE-DERIVED, never held* (held and re-derived agree 126/126 only because the name is held; neither terrain nor culture moves it); how a DM adds a stressor is EM-A1's and EM-B2b's measurement, not assumed here.
6. *"No new dangling reference" is a delta BY KIND* (terrain → desert adds 2–6 joins of kinds the record already carries: free-party prose, catalogue labels).

**⛔ THE CONTRADICTION THE PROTOTYPE FOUND, AND THE RULING.** The generator's readings are PATH-DEPENDENT: `generateEconomy` runs (and draws) over the roster as it stands BEFORE the repair passes, and the reconcile pass reconciles that provisional state rather than recomputing from scratch — so THE RECORD'S READINGS WERE NEVER A FUNCTION OF THE ROSTER THE RECORD HOLDS. Hence: hold the final roster at EVERY writer and a no-edit re-derivation reproduces 6/63 — opening the editor on a city and saving nothing would move food security from Secure to Pressured and rewrite 131–186 service paths; hold it only at its LAST writer and the record reproduces 60/63, but an edit never reaches the economy (it ran before the pin landed). The recon's third horn is to persist the pre-repair roster — a schema change. **RULED: none of the three. THE CONSEQUENCE OF AN EDIT IS THE DIFFERENCE BETWEEN TWO RE-DERIVATIONS.** Both are run under the every-writer seam, which is the one that lets an edit reach every reading: `R0 = rederive(record)` and `R1 = rederive(record + edit)`. The new record is a THREE-WAY MERGE with `R0` as the base: a reading (compared leaf by leaf, keyed collections by their keys) that is IDENTICAL in `R0` and `R1` keeps the record's own value — the edit did not touch it, so nothing the DM did may move it; a reading that DIFFERS takes `R1`'s value. With no edit `R1 = R0` and the record is unchanged BY CONSTRUCTION — the settling shift cancels in the difference instead of being charged to the DM. Receipts (the power fingerprint) are recomputed over the merged record last. `R0` after an edit is the previous `R1` (re-derivation depends only on held facts, config and seed), so a session pays one re-derivation per edit, tens of milliseconds. Undo is the store's snapshot, never an inverse merge. The honest residue, stated in the delta card's own words: a reading the edit DID touch is re-read whole from the town's current facts, so it may move by more than the edit alone would explain. NO SCHEMA CHANGE; the generator's path-dependence is left exactly as it is and the goldens do not move.

**MEASUREMENT OWED (a third, short recon on the same scripts):** the merge over the eight edits on three tiers — which readings move, that no unedited held fact and no untouched reading moves, the dangling delta by kind — and THE HONESTY COST: on how many touched leaves the record already differed from `R0` (settling riding along with a real edit), by edit and tier. Plus the two items the second recon could not settle: draw-SKIP versus draw-CONSUME inside `assembleInstitutions` (3,324 draws over 63 rows), and what a newly minted NPC looks like when `enrichNpcCoherence` is skipped for a held roster (ruling 3's newcomer).
"""

CHARTER = """## Amendments of __STAMP__ — ARCH-REDERIVE version 2: the re-entry family re-cut from the whole-seam prototype (design §22.1; ODQ §934.47 addendum 19)

- **The family is re-cut against the MEASURED touch list (nineteen files), compiled only after the third recon reports:** **EM-R0** the merge — `rederive` returns a re-derivation, and the editor's consequence is the three-way merge `record ⊕ (R1 − R0)` over readings, keyed collections by key, receipts recomputed last (pure, in `src/domain/edit/`; the largest member); **EM-R1** pins cloned on entry + the WRITER CENSUS as a walker with its six classes (producer · mutator · enricher · replay · mint · MIRROR) and the two exemption rules (a mirror always runs; a held writer on a SHARED stream consumes its draws and discards, only a named child stream is skipped); **EM-R2** the roster final inside `enrichNpcCoherence`, with `ensureFactionStructuralNpcs` named and `relinkFactionMembers` exempt; **EM-R3** the power structure final — the replay does not run under a held structure (`resizePoliticalRoster`, `neighbourFactions`, `powerEconomyReconcilePass` named), the freshness assert pin-aware at its THREE call sites, its fingerprint a recomputed receipt; **EM-R4** is reduced to the settlement NAME held through assembly (world facts already flow as `config′`); **EM-R5** the trace partitioned by every step whose entries are ABOUT a held key; **EM-R6** the institution rename-surface list and cascade (still entirely absent). Each is golden-sensitive (no pins ⇒ byte-identical on the full 525-row master) and prices its bytes at pre-proof.
- **`stress` is a re-derived reading, never a held fact**; the DM's way to add a stressor is measured by EM-A1 / EM-B2b.
- **THE PRE-PROOF GAINS STEP 10 (from EM-P3's build):** every `requiredSymbols` row must still hold AFTER the packet's own edits — a symbol the packet MOVES or DELETES at a path is a `retiredSymbols` row (and the successor joins `requiredSymbols` only at the LANDED flip); the pre-proof simulates the post-edit validation, because every check until `check:packet` runs against the pre-edit tree.

"""

ODQ = """- **§934.47 addendum 19 — THE WHOLE SEAM EXECUTED: THE TELEPORTED PORT RUNS; AND THE CONSEQUENCE OF AN EDIT IS THE DIFFERENCE BETWEEN TWO RE-DERIVATIONS (__STAMP__; the successor chair, under the owner's delegation; vetoable).** A second Opus recon prototyped all of design §22 through in-memory overrides, inert with no held bag. ⭐ ALL EIGHT EDITS RUN on a village, a town and a city (24 trials, 0 throws): terrain → desert runs, the governing-seat change and the power share STICK, a culture change keeps the town's name, a rename through the cascade leaves no new dangling join — and a re-derivation is CHEAPER than a plain generation at every tier. Confirmed: no schema change is needed for the power card; the clone; the roster claim; the pin-aware freshness assert (load-bearing: without it 9/63 throw with no edit). Corrected from the measurement: a held writer on a SHARED stream consumes its draws and discards (skipping the name mint moves two prose fields 63/63); MIRROR writers (`relinkFactionMembers`) always run; the stable-roster assert branch is unreachable and struck; the trace partitions by the steps whose entries are ABOUT a held key; `stress` is re-derived, never held; the dangling gate is a delta BY KIND. ⛔ THE CONTRADICTION: the generator's readings are PATH-DEPENDENT — the economy is drawn over the roster BEFORE the repair passes and then reconciled, so a record's readings were never a function of the roster it holds: holding the final roster at every writer makes a NO-EDIT re-derivation move a city's food security from Secure to Pressured (6/63 reproduce); holding it only at its last writer reproduces 60/63 but an edit never reaches the economy; the recon's third horn is persisting the pre-repair roster (a schema change). RULED — none of the three: `R0 = rederive(record)`, `R1 = rederive(record + edit)`, both under the every-writer seam, and the new record is a THREE-WAY MERGE with `R0` as base — a reading identical in `R0` and `R1` keeps the record's own value, a reading that differs takes `R1`'s; with no edit the record is unchanged BY CONSTRUCTION, the settling shift cancels instead of being charged to the DM, receipts are recomputed last, `R0` is cached as the previous `R1`, undo is the store's snapshot; the honest residue (a touched reading is re-read whole, so it may move by more than the edit alone explains) is said in the delta card. No schema change; the goldens do not move. The re-entry family is re-cut to the measured nineteen-file touch list with EM-R0 (the merge) its largest member, compiled only after a third, short recon measures the merge and its honesty cost. ALSO, from EM-P3's build: THE PRE-PROOF GAINS STEP 10 — a symbol a packet moves or deletes is a `retiredSymbols` row; every earlier check had run against the pre-edit tree, so the defect surfaced only at `check:packet`.
"""

s = open(d, encoding="utf-8").read()
assert "### 22.1 " not in s
open(d, "w", encoding="utf-8").write(s.rstrip("\n") + DESIGN.replace("__STAMP__", stamp))

t = open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))

o = open(f, encoding="utf-8").read().rstrip("\n")
open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("design §22.1; charter amendments; ODQ addendum 19")
