# -*- coding: utf-8 -*-
"""Design §22 (ARCH-REDERIVE, version 1) + §21.5.1's count corrected + §20.4 amended; the charter; ODQ §934.47 addendum 18."""
import sys

d, c, f, stamp = sys.argv[1:5]

DESIGN_22 = """

## 22. ARCH-REDERIVE, version 1 — HELD FACTS ARE FINAL (the chair, __STAMP__; ODQ §934.47 addendum 18; under the owner's delegation, vetoable; ⛔ one finding in it is put to the owner by name)

**Why this section exists.** §14's engine is "hold the record's facts fixed, change one, let the derivations follow", built by re-entering the generation pipeline with pins. An Opus recon EXECUTED that against the real pipeline over the 63-row sample (kit: `findings/RECON-ARCH-REDERIVE.report.md`; the prototype, including an in-memory override channel that puts a pin consult INSIDE a function without touching the tree, is in `tools/rederive-prototype/`). The pipeline was never built to be re-entered from a record, and the measurement says exactly where it refuses.

**What the execution showed.**
1. **No pin at a STEP BOUNDARY reproduces a record.** Record-built pins reproduce the settlement in 6 of 63 rows — and early, late, cloned, restored-after-every-step and corruption-undone placements ALL score exactly 6/63. The record's roster is made in the MIDDLE of `assembleSettlement` (`generateCoherence`: `mergeNPCLists`, `disperseNamedRoster`, `enrichNPCsWithStructure`, then `relinkFactionMembers`): ids, names and roles change at the same index, the list grows and re-orders; the enrichment is NOT idempotent for `npcs`/`factions` and NOT invertible. The ONE seam that works consults the pin INSIDE `enrichNpcCoherence`: `npcs`, `factions` and the coherence receipt then reproduce 63/63, leaving `simulationTrace` the sole residual.
2. **The divergence is confined:** of 41 record keys only `npcs`, `factions`, `simulationTrace` (and twice the coherence receipt) ever differ; `institutions`, `powerStructure`, `history`, `economicState`, `stress`, `availableServices`, `defenseProfile`, `relationships`, `conflicts` reproduce 63/63. Re-deriving the READINGS from a record works today; pushing the ROSTER back through its own enrichment is what breaks.
3. **The pin seam exists in ONE step of twenty-two.** Nine of EM-A1's ten root fields sit behind keys nothing consults a pin for.
4. **⛔ THE EDITS THE DESIGN PROMISES, EXECUTED (a town and a city):** adding an institution from the catalogue is CLEAN (the economy and twelve legal services follow; no unedited held fact moves; no dangling reference); changing an NPC's role is clean. But: **a world-fact change to terrain THROWS** (`assertPowerEconomyFreshness` at `assembleSettlement.js:204` — the power structure carries a fingerprint of tier, prosperity and the safety and food labels, so ANY edit that moves one of those readings makes a held power structure "stale" by construction) — §14's own flagship, the teleported port, does not run; **removing an institution throws the same invariant at town tier**; **seating a different governing faction THROWS** (`assertStableGeneratedRoster`: the seat holder's intent key is `'governing-seat'`); **a faction's power share is SILENTLY DISCARDED** (`reconcilePowerStructure` replays from `powerIntent`, which never reaches the record, and overwrites the held fields); **a culture change RENAMES THE SETTLEMENT** (the name is minted from culture at assembly) while a held `stress` summary still speaks the old name (its `summaryRoll` token is deleted once rendered); an NPC rename applied to the pins leaves `relationships[].npcXName` dangling (the rename CASCADE is a different repair and the right one).
5. **The reference graph:** 56 exact joins among held facts — 52 keyed on a DISPLAY NAME, 4 on an id; 30 point at an INSTITUTION by name, and **institutions have no rename surface list at all**; the record already carries 14 (town) to 30 (city) dangling name-joins before any edit, so a "no dangling reference" gate must be a DELTA.
6. **Mutators and multi-producers:** 12 of 18 declared `mutates` rows really write through, and three UNDECLARED write-throughs exist on `provides` keys (`economyReconcilePass` into `economicState`, `coherenceRepairPass` into `generationRepairs` and `institutions`); an aliased pin bag mutates the caller's record in 36/63, a deep-cloned one in 0/63, at 0.5–1.2 % cost. The record holds the LAST production of every multi-producer key (63/63) — and a held key's record value is its FINAL value while intermediate consumers originally read INTERMEDIATE values, which is why restoring final `institutions` early makes a city throw the freshness invariant with no edit at all. The partial-pin refusal is LOAD-BEARING as it stands: pinning `npcs` alone re-rolls every relationship and conflict (63/63).

**The rulings.**
1. **HELD FACTS ARE FINAL.** Re-derivation never sends a held fact back through the code that first made it. The held set is the record's rosters and their first-hand facts — institutions, NPCs, factions, relationships, conflicts, the power structure's held fields, the settlement's NAME, the world facts. Every WRITER of a held key — its producer, every mutating pass, the coherence enrichment, the power replay, the name mint — consults the pin FIRST and, when the key is held, leaves it as it is. "Pinned at a step boundary" is withdrawn as the model; "final at every writer" replaces it, and the writer census (producers, mutators, enrichers, replays, mints, asserts), by symbol, is its denominator.
2. **Re-derivation recomputes READINGS only** — the economy, the services, the defense profile, viability, the resource analysis, and whatever else the census classes as derived from held facts — on each deriving step's own forked stream (skipping a held step is stream-safe: every step forks by name). A drawn reading may move more than the edit strictly implies; that is consequence, and it is reported in the delta card as the reading's movement, never as the DM's edit.
3. **Relationships and conflicts are HELD, and additions are explicit.** Adding a person does not re-roll anyone's relationships; the newcomer has none until an op gives them some — offered as a guard's `fulfil` ("roll their ties"), drawn on a stream keyed by the newcomer's stable id. This is what makes the intra-step dependence problem disappear instead of being solved.
4. **Invariants that compare a held fact with a fresh derivation become PIN-AWARE.** Under held mode `assertPowerEconomyFreshness` REFRESHES the fingerprint (it is a derived receipt, not a held fact) and `assertStableGeneratedRoster` takes the held roster as its subject — a held power structure in a changed world is not stale, it is §14's "incoherence is consequence". In fresh generation (no pins) both stay byte-for-byte what they are: the goldens are the proof.
5. **NO SCHEMA CHANGE IS TAKEN TO MAKE THE POWER CARD WORK.** `powerIntent` is not persisted; the replay learns that a held power structure is final (ruling 1). If the prototype below shows that is impossible, persisting it is an OWNER decision (persisted shape) and is put to the owner then, not assumed now.
6. **Pins are deep-cloned on entry** (`structuredClone`), always. The partial-pin refusal stays exactly as EM-P0 landed it. EM-P0b is withdrawn as chartered (restating the refusal over drawn keys would PERMIT the one seam that re-rolls relationships).
7. **Renames never go through re-derivation** — they go through the cascade (§12.3) — and INSTITUTIONS GET A CASCADE: a declared institution rename-surface list, measured from the reference graph (30 of 56 joins), is its own packet before any institution rename op is promoted. The "no new dangling reference" gate is a delta against the record's own pre-existing dangles.
8. **`simulationTrace` is a generation receipt, partitioned by step:** a held step re-emits nothing and its recorded entries are carried; a deriving step's entries are re-derived. Whether the trace's entries carry enough to be partitioned is MEASUREMENT OWED.
9. **The acceptance criterion:** with NO edit, re-derivation reproduces every record key except a trace whose partition is proven; with an edit, no UNEDITED held fact moves, no NEW dangling reference appears, and nothing throws. Both are measured over the 63-row sample, by execution, before any packet of this family is compiled.

**⛔ PUT TO THE OWNER BY NAME.** Design §14's flagship — change a world fact and watch the consequences — does not run today: the generator's own freshness invariant refuses it, on a town and on a city. It is curable inside the rulings above (rulings 1 and 4), but it is a sub-program in the generator's most sensitive code, under the goldens' byte-identical law, and it is the editor's critical path for every card except the NPC's. The honest size is stated in the charter amendment beside this section.

**MEASUREMENT OWED BEFORE ANY PACKET (the lesson of EM-P0 version 1, again):** an Opus recon prototypes the WHOLE seam through the override channel it already built — every writer of a held key consulting the pin, the two invariants pin-aware, pins cloned — and measures ruling 9's two criteria over the 63 rows and the eight edits of X6 (terrain and the seat change must run; the share edit must stick; culture must not rename the town), plus the trace's partition and the stress summary's fate. This section is amended by what it finds.
"""

CHARTER = """## Amendments of __STAMP__ — ARCH-REDERIVE version 1; EM-D0 unblocked; the re-entry family chartered (design §22; ODQ §934.47 addendum 18)

- **EM-D0 NO LONGER WAITS ON RE-DERIVATION.** The first door is the NPC's card, and the recon measured an NPC's role change as CLEAN with no reading moving: D0's plain edits are RECORD WRITES through the op boundary — `set-field` on the NPC's held fields, the rename through the existing cascade, the annotation — with no pipeline re-entry at all. Its dependencies are EM-A1, EM-A2a, EM-B1a (after EM-B1d, EM-B1e, EM-B1f) and EM-C4a; EM-B2a leaves the list. Train EM-T7 stands.
- **EM-B2a is RE-CUT, not merely blocked:** `rederive` is "held facts are final" (design §22), and it is preceded by **the re-entry family EM-R**, compiled ONLY after the owed prototype reports: **EM-R1** pins cloned on entry + the writer census as a walker (every writer of a held key, by symbol, consults the pin — producers, mutating passes, the coherence enrichment, the power replay, the name mint); **EM-R2** the roster is final inside `enrichNpcCoherence` (the one seam measured to reproduce 63/63) and `corruptionPass` leaves a held roster alone; **EM-R3** the power structure is final in `reconcilePowerStructure`'s replay, and the two invariants are pin-aware (refresh, never throw, under held mode; byte-identical with no pins); **EM-R4** the settlement's name and the world facts are held through assembly; **EM-R5** the trace's partition by step; **EM-R6** the institution rename-surface list and its cascade (before any institution rename op). Each is golden-sensitive (no pins ⇒ byte-identical, proven on the full 525-row master) and prices its byte budget at pre-proof. **EM-P0b is WITHDRAWN** (it would permit the one seam that re-rolls every relationship). HONEST SIZE: six to nine packets in `src/generators/**`, the editor's critical path for the institution, faction, power and world-fact cards.
- **Relationships and conflicts are HELD; ties for a newcomer are an explicit op** (`roll-ties`, offered by a guard's `fulfil`, drawn on a stream keyed by the newcomer's stable id — after EM-P1) — a wave-1 follow-on, chartered with EM-B1b's family.

"""

ODQ = """- **§934.47 addendum 18 — THE RE-DERIVATION RECON: THE TELEPORTED PORT THROWS; ARCH-REDERIVE VERSION 1 — HELD FACTS ARE FINAL (__STAMP__; the successor chair, under the owner's delegation; vetoable; ⛔ ONE FINDING IS PUT TO THE OWNER BY NAME).** An Opus recon executed design §14's engine against the real pipeline over the 63-row sample with scratch wrappers only. MEASURED: record-built pins reproduce a settlement 6/63, and EVERY step-boundary placement scores the same 6/63 — the record's roster is made in the MIDDLE of `assembleSettlement` by an enrichment that is neither idempotent nor invertible; the one seam that works consults the pin INSIDE `enrichNpcCoherence` (63/63, the trace the sole residual); the divergence is confined to `npcs`/`factions`/the trace — every READING reproduces 63/63; the pin seam exists in ONE step of twenty-two. ⛔ THE PROMISED EDITS, EXECUTED: adding an institution and changing an NPC's role are clean; **a terrain change THROWS the generator's freshness invariant — §14's flagship does not run**; removing an institution throws it at town tier; seating a new governing faction throws the stable-roster assertion; a faction's power share is silently discarded (the replay reads `powerIntent`, which never reaches the record); a culture change renames the settlement; 52 of 56 joins among held facts are on display names and institutions have no rename cascade; an aliased pin bag mutates the caller's record 36/63 (a clone: 0/63 at ~1 % cost); the partial-pin refusal is load-bearing (pinning `npcs` alone re-rolls every relationship). RULED (design §22): HELD FACTS ARE FINAL — every writer of a held key consults the pin and leaves it; re-derivation recomputes READINGS only; relationships and conflicts are held and a newcomer's ties are an explicit op; the two invariants become pin-aware (refresh under held mode, byte-identical without pins); NO schema change for the power card (the replay learns finality; persisting `powerIntent` would be the owner's decision and is not assumed); pins cloned; EM-P0b withdrawn; renames go through the cascade and institutions get one; the acceptance criterion is measured (no edit reproduces the record; an edit moves no unedited held fact, adds no dangling join, throws nothing). CHARTERED: the re-entry family EM-R1..R6 (six to nine golden-sensitive packets in the generator — the editor's critical path for every card but the NPC's), compiled ONLY after a second Opus recon prototypes the WHOLE seam and measures the criterion. EM-D0 IS UNBLOCKED: the NPC card's edits are record writes and the cascade, no re-entry.
"""

s = open(d, encoding="utf-8").read()
assert "## 22. " not in s
old_count = "13 of 22 steps draw; 29 rows are drawn, 46 pure."
assert s.count(old_count) == 1
s = s.replace(old_count, "13 of 22 steps draw; under ruling 2 below the rows are 28 drawn, 1 label, 46 pure (the recon's pre-ruling count was 29 / 46; EM-P2 version 3's re-run over the 63-row sample agrees with the recon's 525-row literal on all 75 rows).")
m20 = "**EM-D0 — the first door, pulled forward (§7 and the charter amended).**"
assert s.count(m20) == 1
s = s.replace(m20, m20 + " ⚠ AMENDED BY §22: the NPC card's plain edits are RECORD WRITES and the rename cascade — no pipeline re-entry — so EM-B2a (`rederive`) leaves D0's dependencies.")
open(d, "w", encoding="utf-8").write(s.rstrip("\n") + DESIGN_22.replace("__STAMP__", stamp))

t = open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))

o = open(f, encoding="utf-8").read().rstrip("\n")
open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("design §22 (+ §21.5.1 count, §20.4 marker); charter amendments; ODQ addendum 18")
