# -*- coding: utf-8 -*-
"""The owner's order: the deferred work goes into the sequence. Charter amendment + ODQ §934.53."""
import sys

c, f, stamp = sys.argv[1:4]

CHARTER = """## Amendments of __STAMP__ — THE DEFERRED WORK, SEQUENCED (the owner: "Put the deferred work into the sequence were appropriate"; ODQ §934.53)

Every item the chair had recorded as deferred-and-unsequenced (the kit's `DEFERRALS-UNSEQUENCED.md`, 22 items) now has a slot, a condition, or an owner's decision point. THE TRAIN PLAN AS IT NOW STANDS (one build at a time in the slot; each member made READY by an Opus pre-proof at the tip; each train ends in a bare full check; parallel lanes that need no sealed dispatch run in their own worktrees and are composed at a train boundary):

| when | what | why there |
|---|---|---|
| **EM-T3 (closing)** | EM-B1d (building) → **CURE-A: the model walker's `codeOnly` regex** (`chooserTotality.walker.test.js`: a space-or-tab class instead of `\\s*` under the multiline flag; an Opus cure lane on the branch; proof = the walker's scanned set is IDENTICAL before and after, or the difference is the finding) → ONE lighting refreeze (the chair) → run 17 | the cure is validated by the terminal that follows it instead of waiting for one |
| **TOOLING WINDOW (after run 17 green, before EM-P2 v3 is promoted)** | **TOOL-1** the validator compares a non-terminal packet's §7 change table with its JSON `changeManifest` (EM-B1d's Markdown named eight files against a five-file manifest and every gate passed) — measured first: how many of the estate's packets carry a parseable §7 table, so the arm is scoped and reds nothing historical · **TOOL-2** a dist-gated build test that is run WITHOUT a dist says so in a way a lane cannot read as green (today `describe.runIf(DIST_EXISTS)` skips silently unless `VERIFY_DIST=1`) · **TOOL-3** a census of every emitted WORKER against the byte ceilings, and a measured, monotone-down ceiling minted for each one that has none (`townSceneExport.worker`, `advanceInterval.worker` — the tick packets of wave 3 will land bytes in the second) | every later promotion and landing runs under the cured instruments; TOOL-3 must precede EM-E1 |
| **PARALLEL, from run 17's green base (own worktrees, composed at EM-T4's terminal; they never hold the slot)** | **FIX-F1** the eight tabs still on the tier-noun backstop (ODQ §934.22 addendum 2) · **FIX-F2** the prose-numerics detector's missing `weight` token · **FIX-F3** the two uppercase sites kept because their screen twins still shout (`Services`, `SupplyChainFlow`) · **REVIEW-P** the public-path review (ODQ §934.24), a read-only walk on the consist preview · **RECON-G** the Overview `resilienceScore` against its band label: measure what the 2026-07-22 re-grade would move and put the proposal to the OWNER (a src/domain re-grade is the owner's) | fixes-chain follow-ups are not editor packets and need no seal; the five-agent ceiling and the gate mutex still bind |
| **EM-T3.5** | EM-P2 version 3 (its pre-proof re-runs the 75 rows at the then-tip) | EM-A1 waits on it |
| **EM-T4** | EM-P1 (stable identity; alone; the golden door once, under a signed record) | unchanged |
| **EM-T5** | EM-A1 (its pre-proof ALSO measures how a DM adds a STRESSOR — `stress` is re-derived, never held, and neither terrain nor culture moves it) · EM-A2b · EM-B1e · EM-P1b (with the three name-keyed choice sites) · **EM-B3c** (the scanner's SQL-side subset arm) | EM-B3c must land before the FIRST WRITER of either editor key exists, and that writer is now EM-C4a |
| **EM-T6** | **EM-B1f** (status-based absence at `isOffStage`; FIRST — it blocks EM-B1a) → EM-A2a → EM-B1a | EM-B2a left this train (re-cut behind EM-R) |
| then | EM-B1c (after EM-P1b: a rename must not re-roll prose) · EM-B1b · **EM-B1g `roll-ties`** (a newcomer's relationships as an explicit op, drawn on a stream keyed by the stable id; design §22 ruling 3) · EM-A3 | by dependency |
| **EM-T7** | **EM-B3d** (the `importScrub` strip of the two editor keys — defense in depth, deferred by EM-B3a's K4) → EM-C4a → EM-D0 (the first door) → **BROWSER PASS 4** (an Opus browser lane on the consist preview: the door, the halo, the phone sheet — and the long-owed check of the preview persona's "row appears in the library" claim) | ⛔ EM-C4a IS THE FIRST WRITER of `dmLayer`: its packet carries the arm EM-B3a could not — a REAL written layer run through EM-B3a's travel tests (fork · import · gallery · export · the anonymous envelope) — and a red there is ITS stop |
| **the EM-R family** | EM-R0…R6 after the third recon; EM-R2/R3 also retire the wasted `powerLinkage()` run under a held roster; then EM-B2a (its re-cut repeats the real-layer travel arm for `rederive`'s writes) · EM-B2b · EM-B4 | unchanged in order; two notes attached |
| waves 2–5 | as chartered; **the owner's two unconfirmed defaults have decision points:** the per-tick registry cap (default: none) is asked before EM-C1 is compiled; pending decrees in the PDF (default: no) before EM-D3 | so a default is never built by silence |

**Conditional, not slotted:** the two byte buy-backs (ODQ §934.19 addendum 2) run only on the owner's veto of the re-mints; if no veto has come by the editor program's last terminal, they close as not wanted.
**The owner's hand, with its natural moment named (never the chair's act):** the paused push chain (ODQ §934.42) — run 17's green tip is the first coherent point to resume it, and every train terminal after it is another; migrations 201/202, the admin grant, PRs #51/#52 and the Vercel redeploy ride that push; the ratifications offered today (ODQ §934.19 addenda 2–3; design §20–§22.1) are best given before it.

"""

ODQ = """- **§934.53 OWNER: "Put the deferred work into the sequence were appropriate" (__STAMP__) — DONE: every deferred item has a slot, a condition, or a named decision point (the charter's newest amendments section; the kit's `DEFERRALS-UNSEQUENCED.md` rewritten as a pointer file).** The chair had listed 22 deferred-and-unsequenced items for the owner (12 from the editor program, 6 from the 2026-09-18 fixes chain, 4 the owner's hand). SEQUENCED: the model walker's regex cure rides T3's closing, ahead of the refreeze and run 17, so its own terminal validates it; a TOOLING WINDOW after run 17 cures the validator's blind spot (a packet's §7 table against its JSON manifest), the dist-gated tests' silent skip, and mints the missing WORKER byte ceilings before wave 3 lands bytes in one of them; the fixes-chain follow-ups (the eight tier-noun tabs, the `weight` token, the two uppercase sites), the public-path review and the resilience re-grade's measurement run as PARALLEL lanes in their own worktrees from run 17's green base, composed at T4's terminal — they never hold the slot; EM-B3c joins T5 and EM-B3d heads T7, both BEFORE the first writer of an editor key, which — since EM-D0 was pulled forward — is EM-C4a, whose packet now carries the real-layer travel arm EM-B3a could only run on planted fixtures; EM-B1f heads T6 (it blocks EM-B1a); `roll-ties` becomes EM-B1g after EM-B1b; how a DM adds a stressor is EM-A1's pre-proof measurement; the wasted `powerLinkage()` run is retired inside EM-R2/R3; browser pass 4 (with the long-owed persona check) follows EM-D0. CONDITIONAL: the two byte buy-backs run only on a veto. THE OWNER'S: the push chain's natural moment is any green terminal from run 17 on; the two unconfirmed defaults (no per-tick cap; pending decrees not in the PDF) are asked before EM-C1 and EM-D3 are compiled; the resilience re-grade is decided from RECON-G's measurement. Vetoable line by line.
"""

t = open(c, encoding="utf-8").read()
anchor = "## Pre-proof tasks (Opus, read-only, before each packet is READY)"
assert t.count(anchor) == 1
open(c, "w", encoding="utf-8").write(t.replace(anchor, CHARTER.replace("__STAMP__", stamp) + anchor))
o = open(f, encoding="utf-8").read().rstrip("\n")
open(f, "w", encoding="utf-8").write(o + "\n" + ODQ.replace("__STAMP__", stamp))
print("charter: the deferred work sequenced; ODQ §934.53")
