# -*- coding: utf-8 -*-
HSG19="https://cyborgsandmages.wordpress.com/wp-content/uploads/2019/11/dnd_house_style_guide_updated_january_2019.pdf"
HSG13="https://adventurersleague.files.wordpress.com/2018/10/1765690-dnd_house_style_guide.pdf"
EB="https://www.expositionbreak.com/a-walk-through-the-planes-an-interview-with-monte-cook-ray-vallese-and-colin-mccomb/"
PK="https://web.archive.org/web/20201112024903if_/http://www.wizards.com/dnd/files/DM_Experience_2011.pdf"
DC="https://textual.ru/rpg/dungeoncraft.pdf"
SV="https://save.vs.totalpartykill.ca/blog/kim-mohan/"
ST="https://50yearsinthedungeon.substack.com/p/honoring-kim-mohan"
MP="https://www.mopop.org/sffhof/kim-mohan"

sources=[
 {"title":"Kim Mohan on the D&D Podcast (Ramanan Sivaranjan, Save vs. Total Party Kill)","url":SV,"kind":"reception","substantive":True,"date":"2013-06-16","route":"curl with browser user agent"},
 {"title":"Honoring Kim Mohan (Stan!, 50 Years in the Dungeon)","url":ST,"kind":"reception","substantive":True,"date":"2025-05-24","route":"curl with browser user agent"},
 {"title":"Kim Mohan, SFFHOF Inductee (Museum of Pop Culture)","url":MP,"kind":"analysis","substantive":True,"date":"2025","route":"curl with browser user agent"},
 {"title":"Dragon Editor-in-Chief Kim Mohan Passes (EN World thread)","url":"https://www.enworld.org/threads/dragon-editor-in-chief-kim-mohan-passes.693806/","kind":"reception","substantive":False,"date":"2022-12-12","route":"curl; news item plus tributes, no statement on style"},
 {"title":"D&D Style Guide: Writing and Editing, Version 1.08a","url":HSG19,"kind":"own-words","substantive":True,"date":"2018 copyright line; file posted January 2019","route":"curl PDF, pypdf text extraction"},
 {"title":"D&D Style Guide: Writing and Editing, Version 1.04a","url":HSG13,"kind":"own-words","substantive":True,"date":"2013 copyright line; file posted October 2018","route":"curl PDF, pypdf text extraction"},
 {"title":"A Walk Through the Planes: An Interview with Monte Cook, Ray Vallese, and Colin McComb (Exposition Break)","url":EB,"kind":"own-words","substantive":True,"date":"2022-03-07","route":"curl with browser user agent"},
 {"title":"The Dungeon Master Experience 2011 (Christopher Perkins, collected Dungeon columns)","url":PK,"kind":"own-words","substantive":True,"date":"2011","route":"Wayback id_ capture of wizards.com PDF, pypdf extraction"},
 {"title":"Dungeoncraft (Ray Winninger, Dragon 255-283, collected by John H. Kim)","url":DC,"kind":"own-words","substantive":True,"date":"1997-1999 columns; PDF collection undated","route":"curl PDF, pypdf extraction"},
 {"title":"Insane Angel Studios - RPG - Editing (Scott Fitzgerald Gray)","url":"https://www.insaneangel.com/insaneangel/RPG/RPGEditing.html","kind":"own-words","substantive":False,"date":"n.d.","route":"curl; credits list only, no statement on style"},
 {"title":"DwDD - Editing Adventures with Scott Fitzgerald Gray (Mastering Dungeons)","url":"https://masteringdungeons.podbean.com/e/dwdd-%E2%80%93-editing-adventures-with-scott-fitzgerald-gray/","kind":"own-words","substantive":False,"date":"2020-03-05","route":"curl; show notes only, audio not transcribed"},
]

claims=[
 {"feature":"withheld information and inference","claim":"Kim Mohan, D&D's longest-serving editor, praises Ed Greenwood's prose for leaving the reader feeling that fifty words are held back behind every word given.","source":"Kim Mohan, quoted by Ramanan Sivaranjan reporting the D&D podcast interview, 2013","url":SV,"quote":"you feel like he’s holding fifty in reserve","page":"body, second paragraph","kind":"own-words","polarity":"asserts","date":"2013-06-16","routeHint":"curl with browser user agent","registerHint":"dossier-archivist","confidence":"medium","confidenceReason":"the words reach us through a blogger's transcription of a podcast, not the recording"},
 {"feature":"plainness and economy","claim":"Mohan says that of every ten words Ed Greenwood supplies, three or four could probably have been kept back.","source":"Kim Mohan, quoted by Ramanan Sivaranjan reporting the D&D podcast interview, 2013","url":SV,"quote":"for every ten that he gives you he probably could","page":"body, second paragraph","kind":"own-words","polarity":"asserts","date":"2013-06-16","routeHint":"curl with browser user agent","registerHint":"dossier-archivist","confidence":"medium","confidenceReason":"blogger's transcription of a podcast"},
 {"feature":"edition and house style","claim":"Stan!, who worked with Mohan for about ten years, says Mohan's job under whatever title was to set the editorial tone and mentor the staff.","source":"Stan! (Steven Brown), 50 Years in the Dungeon, 2025","url":ST,"quote":"always to set the editorial tone and mentor the staff","page":"third paragraph","kind":"reception","polarity":"asserts","date":"2025-05-24","routeHint":"curl with browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"edition and house style","claim":"Stan! states that Mohan edited every edition of D&D from the original hardcovers to fifth-edition supplements.","source":"Stan! (Steven Brown), 50 Years in the Dungeon, 2025","url":ST,"quote":"worked on EVERY edition of D&D from the original hardcovers","page":"third paragraph","kind":"reception","polarity":"asserts","date":"2025-05-24","routeHint":"curl with browser user agent","registerHint":"none","confidence":"medium","confidenceReason":"a colleague's recollection, not a credits audit"},
 {"feature":"other: editor biography","claim":"The Museum of Pop Culture records that Mohan came to TSR in 1979 from newspaper work, having been a reporter and then a sports and state editor.","source":"Museum of Pop Culture, Science Fiction and Fantasy Hall of Fame inductee page, 2025","url":MP,"quote":"as a reporter for the Lake Geneva Regional News","page":"inductee biography","kind":"analysis","polarity":"asserts","date":"2025","routeHint":"curl with browser user agent","registerHint":"none","confidence":"high"},

 {"feature":"edition and house style","claim":"The D&D house style guide circulated to Guild creators is numbered version 1.08a and carries a 2018 Wizards of the Coast copyright line.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a","url":HSG19,"quote":"Version 1.08a ©2018 Wizards of the Coast","page":"running footer, every page","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"edition and house style","claim":"Version 1.08a takes the Chicago Manual of Style, 17th edition as one of its two foundations.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a","url":HSG19,"quote":"The Chicago Manual of Style, 17th edition","page":"opening section","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"edition and house style","claim":"The earlier version 1.04a of the same guide took the Chicago Manual of Style, 16th edition as its foundation, so the house authority moved one Chicago edition between the two releases.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.04a","url":HSG13,"quote":"The Chicago Manual of Style, 16th edition","page":"opening section","kind":"own-words","polarity":"asserts","date":"2013","routeHint":"curl PDF, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"edition and house style","claim":"The superseded version of the guide is numbered 1.04a and carries a 2013 copyright line.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.04a","url":HSG13,"quote":"Version 1.04a ©2013 Wizards of the Coast","page":"running footer, every page","kind":"own-words","polarity":"asserts","date":"2013","routeHint":"curl PDF, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"edition and house style","claim":"Neither released version of the D&D style guide names an author, editor or compiler anywhere in its pages; the only attribution is the corporate copyright line.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a (11 pages) and v1.04a (9 pages)","url":HSG19,"quote":"","page":"whole document","kind":"measurement","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction, search for credits, byline, author","registerHint":"none","confidence":"medium","confidenceReason":"a negative finding over the extracted text of the two released versions; a byline in an image or in an unreleased internal version would not appear"},
 {"feature":"dm-facing sentence","claim":"The house style guide states that in rules text the D&D editors prefer to achieve gender neutrality by writing in the second person wherever possible.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Achieving Gender Neutrality","url":HSG19,"quote":"neutrality by writing in the second person","page":"Achieving Gender Neutrality","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction; the PDF's text has hard line breaks mid-sentence","registerHint":"dm-page","confidence":"high"},
 {"feature":"terminology consistency","claim":"The house style guide instructs writers to avoid page references as much as possible.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Page References","url":HSG19,"quote":"We avoid page references as much as possible.","page":"Cross-References, Page References","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"terminology consistency","claim":"The guide's stated reason for avoiding page references is that they are labor-intensive, having to be added by hand during galley review.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Page References","url":HSG19,"quote":"They are labor-intensive (they must be added by","page":"Cross-References, Page References","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"terminology consistency","claim":"The guide tells writers to use cross-references judiciously because they are easily overused.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Cross-References","url":HSG19,"quote":"Use cross-references judiciously.","page":"Cross-References","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"terminology consistency","claim":"The guide sets a monster's name in bold only on its first appearance in an encounter area or subsection, not on every mention.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Terms to Set in Bold","url":HSG19,"quote":"Set a monster’s name in bold only the first time","page":"Terms to Set in Bold","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"dm-page","confidence":"high"},
 {"feature":"terminology consistency","claim":"The guide forbids any word coming between the number of monsters appearing and the name of the stat block.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Terms to Set in Bold","url":HSG19,"quote":"Make sure no text gets between the number of","page":"Terms to Set in Bold","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"dm-page","confidence":"high"},
 {"feature":"terminology consistency","claim":"The guide treats italicized spell and magic item names as titles rather than as descriptions of the thing they create.","source":"Wizards of the Coast, D&D Style Guide: Writing and Editing v1.08a, Terms to Italicize","url":HSG19,"quote":"The italicized terms are treated as titles","page":"Terms to Italicize","kind":"own-words","polarity":"asserts","date":"2018","routeHint":"curl PDF, pypdf extraction","registerHint":"none","confidence":"high"},

 {"feature":"register modulation","claim":"Ray Vallese, the Planescape line's editor, says the products were often written in a wry, overly clever voice that smirked at the setting's ignorant outsiders.","source":"Ray Vallese, TSR Planescape editor, interviewed at Exposition Break, 2022","url":EB,"quote":"written in a wry, overly clever voice that smirked","page":"answer on Planescape's reputation","kind":"own-words","polarity":"asserts","date":"2022-03-07","routeHint":"curl with browser user agent","registerHint":"herald-pools","confidence":"high"},
 {"feature":"other: editorial process","claim":"Vallese describes the RPG editor's job as extending past words and game stats to structure, plot, playability and how the text would fit the layout.","source":"Ray Vallese, TSR Planescape editor, interviewed at Exposition Break, 2022","url":EB,"quote":"issues like structure, plot, playability, how things would fit","page":"answer on what an RPG editor does","kind":"own-words","polarity":"asserts","date":"2022-03-07","routeHint":"curl with browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"other: editorial process","claim":"Vallese names Michele Carter as the other primary Planescape editor of that era.","source":"Ray Vallese, TSR Planescape editor, interviewed at Exposition Break, 2022","url":EB,"quote":"The other primary Planescape editor of that era was Michele","page":"answer on roles","kind":"own-words","polarity":"asserts","date":"2022-03-07","routeHint":"curl with browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"diction (native vs latinate)","claim":"Monte Cook recalls that WotC president Peter Adkison did not want a line whose characters used slang he could not understand to discuss philosophy.","source":"Monte Cook, Planescape designer, interviewed at Exposition Break, 2022","url":EB,"quote":"not people using slang he didn’t understand to discuss philosophy","page":"answer on Planescape after the WotC purchase","kind":"own-words","polarity":"mentions","date":"2022-03-07","routeHint":"curl with browser user agent","registerHint":"herald-pools","confidence":"medium","confidenceReason":"Cook is reporting another man's preference two decades later"},

 {"feature":"plainness and economy","claim":"Christopher Perkins states as a working practice that he keeps his descriptions spare.","source":"Christopher Perkins, The Dungeon Master Experience: T'wit, Dungeon 197, 2011","url":PK,"quote":"I keep my descriptions spare.","page":"column: T'wit","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture of the wizards.com PDF, pypdf extraction","registerHint":"dm-page","confidence":"high"},
 {"feature":"adjective and adverb discipline","claim":"Perkins says he keeps his NPC descriptions brief as well.","source":"Christopher Perkins, The Dungeon Master Experience: T'wit, Dungeon 197, 2011","url":PK,"quote":"I keep my NPC descriptions brief as well.","page":"column: T'wit","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"concrete sensory noun","claim":"Perkins gives an NPC one distinguishing characteristic and then moves on.","source":"Christopher Perkins, The Dungeon Master Experience: T'wit, Dungeon 197, 2011","url":PK,"quote":"I generally like to give an NPC one","page":"column: T'wit","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"omission as information","claim":"Perkins says he does not frontload information but lets it trickle out.","source":"Christopher Perkins, The Dungeon Master Experience: T'wit, Dungeon 197, 2011","url":PK,"quote":"I don’t frontload information.","page":"column: T'wit","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Perkins says that whenever the characters arrive in a new village, town or city he gives them local rumours, some true and some false.","source":"Christopher Perkins, The Dungeon Master Experience: Lies My DM Told Me, Dungeon 197, 2011","url":PK,"quote":"new village, town, or city, I pepper them with local","page":"column: Lies My DM Told Me","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Perkins advises that when in doubt the DM should tell the players things that are true, noting that old D&D adventures carried more true rumours than false ones.","source":"Christopher Perkins, The Dungeon Master Experience: Lies My DM Told Me, Dungeon 197, 2011","url":PK,"quote":"When in doubt, tell the players things that are true.","page":"column: Lies My DM Told Me, Lessons Learned","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"naming and forms of address","claim":"Perkins says the trick with human names is finding names that sound human yet seem grounded in a world of fantasy rather than reality.","source":"Christopher Perkins, The Dungeon Master Experience: What's in a Name?, Dungeon 197, 2011","url":PK,"quote":"names that sound human but seem grounded in a","page":"column: What's in a Name?","kind":"own-words","polarity":"asserts","date":"2011-12","routeHint":"Wayback id_ capture, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},

 {"feature":"plainness and economy","claim":"Ray Winninger's First Rule of Dungeoncraft is never to force yourself to create more than you must.","source":"Ray Winninger, Dungeoncraft, Dragon 256 (later WotC's D&D executive producer)","url":DC,"quote":"Never force yourself to create more than","page":"Dragon 256, World Building Part I","kind":"own-words","polarity":"asserts","date":"1999","routeHint":"curl of John H. Kim's collected PDF at textual.ru, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Winninger's Second Rule of Dungeoncraft is that every major piece of the campaign world filled in must be given at least one secret related to it.","source":"Ray Winninger, Dungeoncraft, Dragon 257","url":DC,"quote":"Whenever you fill in a major piece of the","page":"Dragon 257, recap of the first two rules","kind":"own-words","polarity":"asserts","date":"1999","routeHint":"collected PDF at textual.ru, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Winninger populates a fantasy city's government with functional bureaucrats such as a Master of the Docks who authorises all cargo in and out of the city.","source":"Ray Winninger, Dungeoncraft, Dragon 257, Home Base","url":DC,"quote":"Master of the Docks who authorizes all cargo that","page":"Dragon 257, Home Base, City","kind":"own-words","polarity":"applies","date":"1999","routeHint":"collected PDF at textual.ru, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Winninger tells the DM to give the home settlement a rumour mill, a place where adventurers gather to swap boasts, rumours and legends.","source":"Ray Winninger, Dungeoncraft, Dragon 261, The Rumor Mill","url":DC,"quote":"a place where adventurers gather to","page":"Dragon 261, The Rumor Mill","kind":"own-words","polarity":"asserts","date":"1999","routeHint":"collected PDF at textual.ru, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"place and institution description","claim":"Winninger sets the minimum population of a home base at two interesting NPCs, arguing it is better to develop two really good ideas than four or five mediocre ones.","source":"Ray Winninger, Dungeoncraft, Dragon 261, Interesting NPCs","url":DC,"quote":"better to develop two really good ideas than four","page":"Dragon 261, Interesting NPCs","kind":"own-words","polarity":"asserts","date":"1999","routeHint":"collected PDF at textual.ru, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
]

PDG="https://paizo.com/writersguidelines/dungeon_writer_guidelines.pdf"
PDR="https://paizo.com/writersguidelines/dragon.html"
sources += [
 {"title":"DUNGEON Submission Guidelines, By the DUNGEON Staff","url":PDG,"kind":"own-words","substantive":True,"date":"Paizo era, D&D 3.5 (c. 2005-2007)","route":"curl PDF, pypdf extraction"},
 {"title":"Dragon Writers Guidelines (Paizo/Dragon editorial staff)","url":PDR,"kind":"own-words","substantive":True,"date":"Paizo era, D&D 3.5 (c. 2005-2007)","route":"curl with browser user agent"},
]
claims += [
 {"feature":"boxed text form","claim":"The DUNGEON staff's writers' guidelines state that read-aloud text makes no reference to the viewer.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Read-Aloud Text section","url":PDG,"quote":"does not make any reference to the viewer","page":"Read-Aloud Text (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"boxed text form","claim":"The DUNGEON guidelines tell writers to avoid phrases such as \"you see\" and \"as you enter the room\" in read-aloud text because they assume player action.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Read-Aloud Text section","url":PDG,"quote":"Avoid phrases such as “you see,” “as you enter the","page":"Read-Aloud Text (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"boxed text form","claim":"The DUNGEON guidelines cap read-aloud text: it should only rarely run more than a few sentences.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Read-Aloud Text section","url":PDG,"quote":"should only rarely run more than a few sentences","page":"Read-Aloud Text (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"boxed text form","claim":"The DUNGEON guidelines say long sections of read-aloud text are better served as player handouts.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Read-Aloud Text section","url":PDG,"quote":"are better served as player handouts","page":"Read-Aloud Text (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"boxed text form","claim":"The DUNGEON guidelines tell writers to keep descriptions of creatures out of read-aloud text, because a creature's position and activity depend on circumstances.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Read-Aloud Text section","url":PDG,"quote":"descriptions of any creatures in the room","page":"Read-Aloud Text (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"omission as information","claim":"The DUNGEON editors say they greatly dislike printing the words \"This room is empty\" in the magazine.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, The Adventure's Encounters","url":PDG,"quote":"printing the words “This room is empty”","page":"The Adventure's Encounters (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dm-page","confidence":"high"},
 {"feature":"dm-facing sentence","claim":"The DUNGEON guidelines rule that if a writer has nothing to say under any of the encounter's headings, the area is not an encounter and takes no number.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, The Adventure's Encounters","url":PDG,"quote":"the area is not an encounter and should not be","page":"The Adventure's Encounters (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"edition and house style","claim":"The DUNGEON staff list failure to present information in the proper D&D style among the standard reasons an article is rejected.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Rejection","url":PDG,"quote":"failure to present information in the proper D&D style","page":"Rejection","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"place and institution description","claim":"The DUNGEON staff say the key to designing a compelling fantasy city is presenting a strong sense of place.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Appendix 1: Cities of Adventure","url":PDG,"quote":"compelling fantasy city is presenting a strong “sense of place.”","page":"Appendix 1: Cities of Adventure, Thirty Questions About Your City","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"The DUNGEON staff set a writer thirty questions about a city before writing it, opening with who rules the city and how the ruler maintains power.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Appendix 1: Cities of Adventure","url":PDG,"quote":"THIRTY QUESTIONS ABOUT YOUR CITY","page":"Appendix 1: Cities of Adventure","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"concrete sensory noun","claim":"Among the thirty questions the DUNGEON staff require a city writer to answer is what the city smells like.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Appendix 1, question 24","url":PDG,"quote":"What does the city smell like?","page":"Appendix 1: Cities of Adventure, question 24","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"The last of the DUNGEON staff's thirty city questions, and the only one set in capitals, asks why adventurers come to the city.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Appendix 1, question 30","url":PDG,"quote":"WHY DO ADVENTURERS COME TO YOUR CITY?","page":"Appendix 1: Cities of Adventure, question 30","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"A DUNGEON \"Cities of Adventure\" article runs from 8,000 to 10,000 words.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Features","url":PDG,"quote":"Cities of Adventure articles range in length from","page":"Features, Cities of Adventure","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"A DUNGEON city article must carry a brief appendix with up to five complete stat blocks for personages important to the city.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Features","url":PDG,"quote":"stat blocks for personages important to the city","page":"Features, Cities of Adventure","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"A DUNGEON Backdrop, the magazine's locale feature, may range in scope from a demiplane down to a single city location such as a tavern or temple.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Features","url":PDG,"quote":"from a demiplane to a single city location","page":"Features, Backdrop","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"The DUNGEON staff hold that a background that cannot be presented in 500 words is probably too complex and should be simplified.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Adventure Background","url":PDG,"quote":"present an adventure background in 500 words, it’s probably","page":"Appendix II, Adventure Background (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: measured length","claim":"The DUNGEON staff give 500 words as the rough average word count of a single published encounter.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Appendix II: Adventure Design Guide","url":PDG,"quote":"a rough average for a single encounter’s word count","page":"Appendix II: Adventure Design Guide","kind":"measurement","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: measured length","claim":"The DUNGEON staff cap a sidebar at 300 words and ask writers to keep the number of sidebars to a minimum.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Appendix II: Adventure Design Guide","url":PDG,"quote":"sidebars in your adventure to a minimum, and to no","page":"Appendix II: Adventure Design Guide","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dm-page","confidence":"high"},
 {"feature":"withheld information and inference","claim":"The DUNGEON guidelines require surprises and plot twists to be outlined in the synopsis for the DM rather than sprung during the adventure text.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, Adventure Synopsis","url":PDG,"quote":"Outline surprises and plot","page":"Appendix II, Adventure Synopsis (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"dm-page","confidence":"high"},
 {"feature":"place and institution description","claim":"The DUNGEON guidelines list rumours, researchable background and town statistics among the sections a writer may place before an adventure's encounters.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, The Adventure's Encounters","url":PDG,"quote":"background information the players can uncover in research","page":"Appendix II, The Adventure's Encounters (Mandatory)","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"herald-pools","confidence":"high"},
 {"feature":"other: measured length","claim":"The DUNGEON guidelines require an author bio of 25 words at the end of an adventure or backdrop manuscript.","source":"The DUNGEON Staff, DUNGEON Submission Guidelines, The Manuscript","url":PDG,"quote":"write a 25-word personal bio","page":"The Manuscript, rule 4","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl PDF from paizo.com, pypdf extraction","registerHint":"none","confidence":"high"},

 {"feature":"point of view and distance","claim":"The Dragon editorial staff state that they will not publish an article written in the first person.","source":"Dragon Writers Guidelines (Dragon editorial staff), Format and Style","url":PDR,"quote":"we will not publish an article written in the first person","page":"Format and Style","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl with browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"opening sentence","claim":"The Dragon guidelines cap an article's opening narrative vignette or example dialogue at 200 words.","source":"Dragon Writers Guidelines (Dragon editorial staff), Format and Style","url":PDR,"quote":"no more than 200 words long","page":"Format and Style","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl with browser user agent","registerHint":"herald-pools","confidence":"high"},
 {"feature":"other: measured length","claim":"The Dragon guidelines state that a full page of text in the magazine contains about 750 words.","source":"Dragon Writers Guidelines (Dragon editorial staff), Format and Style","url":PDR,"quote":"A full page of text in Dragon contains about 750 words.","page":"Format and Style","kind":"measurement","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl with browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"terminology consistency","claim":"The Dragon guidelines require article manuscripts to use the current style of D&D game products, italicising magic item and spell names and capitalising feat names.","source":"Dragon Writers Guidelines (Dragon editorial staff), Format and Style","url":PDR,"quote":"should use the current style of D&D game","page":"Format and Style","kind":"own-words","polarity":"asserts","date":"c. 2005-2007","routeHint":"curl with browser user agent","registerHint":"none","confidence":"high"},
]
