import json
base='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/'
chunk=json.load(open(base+'chunks/wolfe-23.json'))
V='VERIFIED_VERBATIM'
verdicts=[
 {"index":345,"verdict":V,"trueWording":"Wolfe: characterize by showing thinking, speaking, acting characteristically.","note":"Stewart's blog (POSSIBLY IRRITATING ESSAYS, Feb 2022) relays five bits of advice Wolfe gave Neil Gaiman; the quote sits verbatim in the fourth: 'You do not characterize by telling the reader about the character. You do it by showing the character thinking, speaking and acting in a characteristic way. You simply show it and shut up.' Every limb holds, including 'rather than described'."},
 {"index":346,"verdict":V,"trueWording":"Ambiguity: organising principle of form and fundamental theme.","note":"Opening paragraph, verbatim: 'ambiguity is the watchword to the text. More significantly, it is also an organising principle of form, a means of confounding interpretation, and a fundamental theme...'. Article by Peter Wright, Ultan's Library, 15 January 2002; the 'not only a theme' limb is supported because the page asserts both roles."},
 {"index":347,"verdict":V,"trueWording":"Puzzle's existence more significant than its solution.","note":"Verbatim (including the page's own typo 'more significant that its solution'), and located exactly where the claim says - the paragraph closing the Wendland discussion: '...the existence of the puzzle is more significant that its solution, since the puzzle is where the political arguments of the novel can be found.'"},
 {"index":348,"verdict":V,"trueWording":"Early-1980s readers accused Wolfe of fabricating words; untrue.","note":"Wowra's introduction to his 2009 interview with Andre-Driussi: 'In the early 1980s, frustrated readers accused Mr. Wolfe of deliberately fabricating unusual words to confuse them. Nothing could be further from the truth.' Both limbs (the early-1980s dating and the denial) are on the page."},
 {"index":349,"verdict":V,"trueWording":"Real strange words show how odd language sounds.","note":"Verbatim: 'All of the strange words that appear in THE BOOK OF THE NEW SUN are real. And they remind us just how odd language can sound without science fiction authors inventing new words that lack inherent meaning.' The 'without any invented vocabulary' limb is the page's own clause."},
 {"index":350,"verdict":V,"trueWording":"Bizarre, seemingly counterfeit words: omophagist and cherkaji.","note":"Verbatim in the same introduction: 'full of bizarre and seemingly counterfeit words like omophagist (an eater of raw flesh) and cherkaji (Persian light cavalry)', with 'All of the strange words... are real' two sentences later, supporting the 'seemingly counterfeit but real' limb."},
 {"index":351,"verdict":V,"trueWording":"Range actually one thousand to thirty-thousand years, revising 'about a chiliad'.","note":"Section 2.1 Overview, verbatim: 'In “Posthistory 101” and Lexicon Urthus I stated that the time from Ymar to Severian was about a chiliad. Recent reading suggests that the range is actually between one thousand and thirty-thousand years...'. By Michael Andre-Driussi, Ultan's Library, 6 July 2020; the revision limb is explicit."},
 {"index":352,"verdict":"PARTIAL","unsupportedLimb":"that the earlier thousand-year figure rested on a single character's remark - the page names a second basis, Wolfe's own remark in a 1983 Robert Frazier interview ('an autarch a chiliad dead'), and concludes 'Based, then, on Vodalus’ and Wolfe’s comments, I took the 1K model as being solid'","trueWording":"Vodalus's line plus Wolfe's 1983 interview remark grounded 1K.","note":"Quote is verbatim in section 2.2 ('This statement strongly implied to me that the autarchs had reigned for about a thousand years'), and the 'rather than any stated chronology' limb is supported ('it turns out I had not adequately cited the source text for that detail'). The 'single character's offhand remark' limb overstates: the source text is Vodalus's recruitment-pitch line (II, chap. 10) AND Wolfe's interview statement, which Andre-Driussi says he was 'perhaps unduly influenced by'."},
 {"index":353,"verdict":V,"trueWording":"Brute-force search for chiliads, thousand years, ages, aeons, eons.","note":"Section 2.3 Narrowing the range, verbatim: 'In an attempt to narrow that down a bit, I set upon a brute force method of searching for the terms “chiliads,” “thousand years,” “ages,” “aeons,” and “eons,” in order to sift for further clues.' The five time words match the claim exactly, and the narrowing purpose is stated."},
 {"index":354,"verdict":"PARTIAL","unsupportedLimb":"that this advice came in a letter - the memoir introduces it only as 'He once advised', naming no setting; the letter it does describe is the earlier critique of her novel chapters (the 'uncooked dumplings' letter)","trueWording":"'He once advised' - setting unnamed, not attributed to a letter.","note":"Quotation verbatim: 'He once advised, “Always tell a story as cleanly and as clearly as possible.”' Cooney's memoir (Ultan's Library, 10 June 2016) mixes dinner conversation and correspondence, and this line is not placed in either. Secondary: the page calls her a poet and short-story writer with an unsold novel; 'novelist' is not the page's word."},
 {"index":355,"verdict":V,"trueWording":"Letter on her chapters: infodumps, 'lumps of prose like uncooked dumplings'.","note":"Verbatim and every limb holds: 'he wrote me a long letter about what he did read... I had a tendency to interrupt my dialogue with long infodumps. He used the phrase “lumps of prose like uncooked dumplings”'. The draft was the first chapters of her novel, which she had sent him."},
 {"index":356,"verdict":V,"trueWording":"She'd cut sing-songy rhythm and rhyme; he urged otherwise.","note":"Verbatim, and directly after the clean-and-clear advice as the claim locates it: 'after I wrote “Three Fancies from the Infernal Garden”... and showed it to Gene, telling him I’d probably need to cut much of the sing-songy rhythm and internal rhyme, he urged me not to take my knife to it.'"},
 {"index":357,"verdict":V,"trueWording":"5HoC's opening line riffs on Proust's 'For a long time I went to bed early.'","note":"Verbatim: 'The opening line of The Fifth Head of Cerberus... is a riff on Proust’s “For a long time I went to bed early.”' By Matthew Keeley, Tor.com/Reactor, published 9 November 2017 (datePublished 2017-11-09). The page names Swann's Way as the work in the next sentence ('Readers unfamiliar with Swann’s Way... people who recognize the source quote'); it does not itself use the word 'opening' for the Proust line, though that line is Swann's Way's first sentence."},
 {"index":358,"verdict":V,"trueWording":"'There’s also, perhaps, a slight clue... in the sentence’s grammar'.","note":"Verbatim in the same paragraph. The page hedges with 'perhaps', which the claim drops; the claim's own wording ('a slight clue') keeps the page's low strength, so the limb stands."},
 {"index":359,"verdict":V,"trueWording":"'We eventually do learn why that comma is missing.'","note":"Verbatim, and the missing comma is explicitly the one in 'my brother David': 'If the narrator had only one brother, we would read “my brother, David” rather than the comma-less “my brother David.” We eventually do learn why that comma is missing.'"},
]
out={"name":"wolfe","chunk":23,"claims":chunk["claims"],"verdicts":verdicts}
assert len(verdicts)==15 and [v["index"] for v in verdicts]==chunk["indices"]
p=base+'verdicts-wolfe-i345-359.json'
json.dump(out,open(p,'w'),indent=1,ensure_ascii=False)
print("wrote",p,len(open(p).read()))
