/**
 * tests/helpers/shrinkOnlyBaseline.js — THE GUARD ON THE DOCUMENTED REFREEZE
 * (VOICE-1b, ODQ §854; the standing STRIP-never-raise ruling at ODQ line 266).
 *
 * THE DEFECT THIS CLOSES. Three committed baselines are regenerated by ONE
 * documented command — `UPDATE_VOICE_BASELINE=1 npx vitest run
 * tests/copy/voiceMechanics.test.js` (and the same variable in
 * tests/copy/proseLeak.test.js) — and every one of those writes was a bare
 * `writeFileSync` of whatever the scan had just measured. The docstrings around
 * them say the regeneration is "shrink-only: totals may never grow"; nothing
 * enforced it. Running the documented command on a drifted tree therefore
 * BANKED THE DRIFT, silently, in the direction the ratchet exists to forbid.
 *
 * WHAT A REFREEZE WOULD ACTUALLY HAVE DONE, measured (the skeptic pass on
 * TE-VOICE-1's report): it would NOT have gone green. The two budget arms
 * compare against HARDCODED constants (EM_BUDGET 670 / BANG_BUDGET 15 in Tier 2,
 * 6 / 0 in Tier 3), so a rewrite of the per-file JSONs turns four red arms into
 * TWO — the two per-file arms go green ON THE BANKED GROWTH, and the run then
 * prints a RATCHET-DOWN notice inviting the permanent deletion of the two census
 * rows that had been holding the debt visible. That is the whole failure: not a
 * loud wrong answer, a quiet correct-looking one that erases its own evidence.
 *
 * THE RULE. A regeneration may LOWER any total and may leave any total equal.
 * It may never RAISE one. A growth means the tree acquired new debt, and the
 * cure for new debt is to rewrite the string (VOICE_AND_TONE §6), never to move
 * the line the string is measured against. On a raise this throws, so the write
 * never happens and the run fails where a human is watching.
 *
 * Pure except for the one guarded write; no network, no ambient state.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

/**
 * Sum every numeric metric across every file row of a baseline map.
 * @param {Record<string, Record<string, number>>} map
 * @returns {Record<string, number>} metric name → total
 */
export function totalsOf(map) {
  /** @type {Record<string, number>} */
  const totals = {};
  for (const row of Object.values(map || {})) {
    for (const [metric, n] of Object.entries(row || {})) {
      if (typeof n === 'number') totals[metric] = (totals[metric] || 0) + n;
    }
  }
  return totals;
}

/**
 * Compare two totals maps and name every metric that GREW.
 * A metric present only in `next` counts from zero, so a newly-introduced tell
 * cannot enter a baseline by arriving under a name the old file never used.
 * @param {Record<string, number>} before
 * @param {Record<string, number>} after
 * @returns {string[]} human-readable growth rows, empty when nothing grew
 */
export function growthRows(before, after) {
  /** @type {string[]} */
  const rows = [];
  for (const metric of [...new Set([...Object.keys(before), ...Object.keys(after)])].sort()) {
    const b = before[metric] || 0;
    const a = after[metric] || 0;
    if (a > b) rows.push(`${metric}: ${b} → ${a} (+${a - b})`);
  }
  return rows;
}

/**
 * Write a per-file baseline, but ONLY in the shrink direction.
 *
 * @param {string} path absolute path of the committed baseline JSON
 * @param {Record<string, Record<string, number>>} next the freshly measured map
 * @param {string} label what this baseline governs, for the refusal message
 * @returns {{written: boolean, before: Record<string, number>, after: Record<string, number>}}
 * @throws {Error} when any metric total would grow — the write is NOT performed
 */
export function writeShrinkOnlyBaseline(path, next, label) {
  const before = existsSync(path)
    ? totalsOf(JSON.parse(readFileSync(path, 'utf8')))
    : {};
  const after = totalsOf(next);
  const grew = growthRows(before, after);
  if (grew.length > 0) {
    throw new Error(
      `REFUSED: regenerating ${label} would RAISE its committed totals.\n`
      + `${grew.map((r) => `  ${r}`).join('\n')}\n`
      + 'The documented refreeze is shrink-only (the standing STRIP-never-raise ruling).'
      + ' A total that grew means new debt landed: rewrite the string per'
      + ' docs/VOICE_AND_TONE.md §6, or burn the debt down, and run the refreeze again.'
      + ' Re-freezing around the growth would turn the per-file arms green ON the growth'
      + ' while the hardcoded budget arms stayed red, and the resulting RATCHET-DOWN'
      + ' notice would invite deleting the very census rows holding this debt visible.',
    );
  }
  writeFileSync(path, JSON.stringify(next, null, 1) + '\n');
  return { written: true, before, after };
}
