import json
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/martin-03.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-martin-i850-874.json"
d=json.load(open(src,encoding='utf-8'))
V=[
{"index":850,"verdict":"VERIFIED_VERBATIM","trueWording":"prose seems uninspired, cliched, repetitive, in stark contrast to plotting","note":"Live page fetched raw (HTTP 200). Walda, posted 31 July 2015, page 2: \"If, at the moment, there are many places where, to me, GRRM's prose seems uninspired, clichéd, repetitive, in stark contrast to his plotting and his characters, what do I know?\" Quote verbatim; every limb (in places, the three adjectives, the contrast with plotting and characters) present. Context worth carrying: the judgement is explicitly provisional and the same post calls the series addictive and 'what masterful prose is supposed to do'."},
{"index":851,"verdict":"VERIFIED_VERBATIM","trueWording":"Romanian translation made awkward dialogues less painful, if painful at all","note":"Live page fetched raw. Drekinn, posted 31 July 2015 (edited same day), page 2: \"I really like the Romanian translation. Some awkward dialogues weren't as painful if at all in the translation. Like saying ''Nuncle'', fat pink mast or the infamous ''Sunset found her squatting in the grass...''\" Quote verbatim as a substring; the Romanian-translation limb and the awkward-English limb both present."},
{"index":852,"verdict":"VERIFIED_VERBATIM","trueWording":"A good piece, covering ground ranging from prose to themes to world-building","note":"Live www.westeros.org returned HTTP 403 to curl with a browser UA; recovered via Wayback raw capture https://web.archive.org/web/20250424162321id_/https://www.westeros.org/News/Entry/13834 (raw page, not a summary). Entry dated January 18, 2011, signed \"Posted at 23:40 CET by Linda\" — the 2011 dating, the Collins subject and the quoted phrase are all verbatim. Caveat on attribution only: the page gives the poster as \"Linda\" with no surname and no role title; \"news editor\" and \"Antonsson\" come from outside this page."},
{"index":854,"verdict":"VERIFIED_VERBATIM","trueWording":"never read heroic fiction so relentlessly driving home war's degradation","note":"Live page fetched raw (HTTP 200), AttentionDeficitDisorderly. Point 10: \"There's basically nothing glorious or badass whatsoever about violence as portrayed in these books... I don't think I've ever read a heroic fiction that so relentlessly drives home how war and violence immiserate and degrade everyone who participates in them.\" Quote verbatim; the anti-glorification limb is carried by the point's first sentence."},
{"index":857,"verdict":"VERIFIED_VERBATIM","trueWording":"writing did a superb job of immediately putting the reader in the moment","note":"www.tor.com returned HTTP 403; recovered via Wayback raw capture https://web.archive.org/web/20240114133050id_/https://www.tor.com/2011/03/18/a-read-of-ice-and-fire-a-game-of-thrones-part-1/. Byline Leigh Butler, Fri Mar 18 2011; the post states she is reading the series \"for the very first time\". The sentence sits in the Prologue Commentary. Quote verbatim."},
{"index":858,"verdict":"VERIFIED_VERBATIM","trueWording":"just enough worldbuilding tidbits to pique the interest without drowning you in exposition","note":"Same Wayback raw capture. End of the Prologue Commentary: \"Overall, nicely done, with just enough worldbuilding tidbits to pique the interest without drowning you in exposition.\" Quote verbatim. Use the page's own tail wording — the restraint claimed is 'without drowning you in exposition', not the absence of exposition; do not tighten it to 'without exposition' in any quoted rendering."},
{"index":859,"verdict":"PARTIAL","unsupportedLimb":"that the repeated chapter titles are character names — Butler says only 'Or non-repetitive titles, either'","trueWording":"Martin is not into chapter numbers, or non-repetitive titles either","note":"Same Wayback raw capture. Introductory note: \"Today's inaugural entry is Part 1 of A Game of Thrones, in which we cover the Prologue and 'Bran,' because it turns out Mr. Martin is not into chapter numbers. Or non-repetitive titles, either.\" The quote is verbatim and the no-numbers limb is fully supported; the repetition limb is supported only as 'non-repetitive titles'. Butler nowhere says the titles are character names — the reader infers it from the chapter header 'Bran' shown on the page. Grade the character-name half as inference, not as Butler's observation."},
{"index":861,"verdict":"VERIFIED_VERBATIM","trueWording":"after the combine harvester that was ASOS, a refreshing break","note":"Live reactormag page fetched raw (HTTP 200); reactormag.com is the renamed Tor.com, byline \"By Leigh Butler\", published December 5, 2013 — same reader as 857–859. Commentary: \"After the combine harvester that was ASOS, a relatively simple story about a dude trying to win a joust is a refreshing break.\" Quote verbatim; the after-ASOS limb and the contrast-with-the-novels limb both present (she adds that Martin still layers politics and history around Dunk)."},
{"index":862,"verdict":"VERIFIED_VERBATIM","trueWording":"his prose style is unstable; it veers between the two registers","note":"Live page fetched raw (HTTP 200), Books & Boots, \"by Simon on March 31, 2014\". Opening paragraph: \"George RR Martin's prose style ... is unstable. By this I mean it veers from purely functional modern thriller prose to prose larded with fake medievalisms, from a lexicon of short, Anglo-Saxon words to one suddenly stuffed with neoclassical and latinate vocabulary.\" Quote verbatim; unstable, both poles, and the fake-medievalism naming all present."},
{"index":867,"verdict":"VERIFIED_VERBATIM","trueWording":"by repetition over scores of chapters the distorted English becomes your home setting","note":"Same page, section \"5 Distorting English\": \"By repetition over the multiple scenes, and scores of chapters, Martin's slightly distorted English, and slightly amended concepts, become your home setting.\" Quote verbatim; the repetition-across-chapters limb and the default-setting limb both explicit. Examples given on the page: Ser, flowered, sourleaf, dreamwine."},
{"index":868,"verdict":"VERIFIED_VERBATIM","trueWording":"most persistent of the annoying would-be medievalisms is dropping -ly","note":"Same page, section \"9. Cod medievalism\": Martin \"abandons his natural crisp, clear style to slip into pastiche medievalism\" and there is \"a number of would-be medievalisms which become annoying mannerisms: The most persistent one is removing the -ly suffix from adverbs.\" Quote verbatim; most-persistent and cod-medieval limbs explicit. On the blemish limb: the disparagement is carried here by \"annoying mannerisms\", while the word \"blemishes\" itself appears in the Conclusion attached to 'oft' and 'elsewise' — same family, adjacent sentence, so the limb holds, but do not quote 'blemish' as applied to the -ly item."},
{"index":869,"verdict":"VERIFIED_VERBATIM","trueWording":"not the occasional pseudo-medievalisms but consistent Anglo-Saxon choice gives the woodiness","note":"Same page, Conclusion: \"...it is not because of the occasional pseudo-medievalisms ('oft' and 'elsewise') which are in fact blemishes on his otherwise swift clear style; it is because he consistently chooses words of Anglo-Saxon origin and generally avoids Latinate and neoclassical vocabulary, thus giving his prose a cumulative feeling of woodiness, antiquity, pithiness.\" Quote verbatim; the not-X-but-Y structure of the claim matches the source exactly."},
{"index":870,"verdict":"VERIFIED_VERBATIM","trueWording":"systematic exclusion of almost all Latin, Greek, French and loan words","note":"Live page fetched raw (HTTP 200), Books & Boots, \"by Simon on March 8, 2013\" — same author as 862–869. Under the heading \"Abstract\": the series is distinguished \"by a systematic exclusion from his vocabulary of almost all words derived from Latin, Greek, French or other languages, or foreign loan words, or the 'neo-classical' coinages which entered the English language from the 17th century onwards.\" Quote verbatim; heading placement as cited."},
{"index":871,"verdict":"VERIFIED_VERBATIM","trueWording":"Instead, high frequency of Anglo-Saxon words, conspicuous in compounds","note":"Same page, Abstract, the sentence immediately following the exclusion sentence: \"Instead, his style shows a high frequency of words of Anglo-Saxon origin, a tendency which is particularly conspicuous in his use of compound and combination words.\" Quote verbatim; the 'counterpart of that exclusion' limb is carried by the page's own \"Instead\"."},
{"index":874,"verdict":"VERIFIED_VERBATIM","trueWording":"in 770 pages of Feast of Crows only one really Latinate word","note":"Same page, under the heading \"CONCLUSION\": \"In the 770 pages of Feast of Crows I noticed only one really Latinate word, 'intermediate'.\" Quote verbatim, page count and the 'only one' count both as claimed. Two source-internal wrinkles to carry if the figure is reused: the page writes the title as 'Feast of Crows' (the novel is A Feast for Crows), and elsewhere the same post names 'intermittent', 'intercession', 'fornication', 'penetrate' and 'complement' as Latinate standouts in that novel, so the 'only one' is the author's impression, not a count that survives his own post."}
]
assert [v["index"] for v in V]==d["indices"], "index mismatch"
json.dump({"name":"martin","chunk":3,"claims":d["claims"],"verdicts":V},open(out,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print("wrote",out)
