# -*- coding: utf-8 -*-
import sys, importlib.util, os
spec=importlib.util.spec_from_file_location('build', os.path.join(os.path.dirname(os.path.abspath(__file__)),'build.py'))
B=importlib.util.module_from_spec(spec); spec.loader.exec_module(B)

MIT='https://www.theguardian.com/books/2015/oct/23/david-mitchell-wizard-of-earthsea-tolkien-george-rr-martin'
MITS='David Mitchell, "David Mitchell on Earthsea: a rival to Tolkien and George RR Martin", The Guardian, 23 October 2015'
ATW='https://www.nybooks.com/articles/2002/09/26/the-queen-of-quinkdom/'
ATWS='Margaret Atwood, "The Queen of Quinkdom", The New York Review of Books, 26 September 2002 issue'
KIR='https://www.kirkusreviews.com/book-reviews/ursula-k-le-guin/tehanu/'
KIRS='Kirkus Reviews, unsigned review of Tehanu, 1 February 1990'
LOA='https://www.loa.org/news-and-views/1375-fellow-writers-remember-ursula-k-le-guin-1929-2018/'
CRA='https://www.theguardian.com/books/2003/sep/24/buildingachildrenslibrary.booksforchildrenandteenagers'
CRAS='Amanda Craig, "Classic of the month: A Wizard of Earthsea", The Guardian, 24 September 2003'
WG='https://reactormag.com/a-woman-on-gont-ursula-k-le-guins-tehanu/'
WGS='Jo Walton, "A Woman on Gont: Ursula K. Le Guin’s Tehanu", Tor.com/Reactor, 25 October 2011'
WE='https://reactormag.com/let-her-be-eaten-ursula-k-le-guins-the-tombs-of-atuan/'
WES='Jo Walton, "Let her be eaten: Ursula K. Le Guin’s The Tombs of Atuan", Tor.com/Reactor, 2011'
PH='https://www.newyorker.com/magazine/2016/10/17/the-fantastic-ursula-k-le-guin'
PHS='Julie Phillips, "The Fantastic Ursula K. Le Guin", The New Yorker, 17 October 2016'
EA='https://web.archive.org/web/20151107114510id_/http://sfra.org/Coyote/alwayshome.htm'
EE='https://web.archive.org/web/20151107114510id_/http://sfra.org/Coyote/earthsea.htm'
ES='Richard D. Erlich, Coyote’s Song: The Teaching Stories of Ursula K. Le Guin (SFRA digital book, 2009 revision), chapter '

C=[]
def add(**k): C.append(k)

# ---- Mitchell, Guardian 2015 ----
add(feature='metaphor discipline', claim='David Mitchell states that metaphors and similes are rare in A Wizard of Earthsea, and that this scarcity is what makes them vivid when they do appear.', source=MITS, url=MIT, quote='Metaphors and similes are scarce enough to burn vividly', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent (curl -A Chrome UA); the Guardian day index /books/2015/oct/23/all supplied the slug', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='dialogue register', claim='David Mitchell states that dialogue in A Wizard of Earthsea is sparing.', source=MITS, url=MIT, quote='dialogue is sparing', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='none', confidence='high', _file='mitchell-guardian.txt')
add(feature='per-speaker register', claim='David Mitchell states that Earthsea’s accents and dialects are mentioned in the narration but never written out phonetically on the page.', source=MITS, url=MIT, quote='accents and dialects are referred to but not reproduced on', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='register modulation', claim='David Mitchell states that Le Guin avoids wide variations of tone or register in A Wizard of Earthsea.', source=MITS, url=MIT, quote='Le Guin eschews wide variations of tone or register', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='humour', claim='David Mitchell states that the dialogue of A Wizard of Earthsea carries warmth and humour but contains no knowing wisecracks.', source=MITS, url=MIT, quote='Dialogue contains warmth and humour, but no knowing wisecracks', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='none', confidence='high', _file='mitchell-guardian.txt')
add(feature='cadence and rhythm', claim='David Mitchell characterises the narrating voice of Ged’s story as having the calm authority of an age-old Icelandic saga.', source=MITS, url=MIT, quote='the calm authority of an age-old Icelandic saga', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='chronicle-line', confidence='high', _file='mitchell-guardian.txt')
add(feature='annalist voice and deep time', claim='David Mitchell states that the cumulative effect of Le Guin’s stylistic restraint is that A Wizard of Earthsea reads like a tale handed down through generations of storytellers.', source=MITS, url=MIT, quote='reads like the retelling of a tale first told centuries', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='chronicle-line', confidence='high', _file='mitchell-guardian.txt')
add(feature='place and institution description', claim='David Mitchell states that a quoted passage describing an East Reach woman’s customary greeting gesture persuades precisely because its detail seems too particular to have been invented.', source=MITS, url=MIT, quote='Such specificity is persuasive because it sounds too detailed', page='paragraph following the quoted East Reach greeting', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='plainness and economy', claim='David Mitchell names a studied neutrality of style as one of the two failure modes fantasy prose falls into, the other being a cod-historic narratorial voice.', source=MITS, url=MIT, quote='a studied neutrality of style tastes like clingfilm', page='section on style and voice', kind='analysis', polarity='rejects', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='archaism', claim='David Mitchell states that a cod-historic narratorial voice in a fantasy novel feels like being locked inside a medieval theme park.', source=MITS, url=MIT, quote='A cod-historic narratorial voice in a fantasy novel', page='section on style and voice', kind='analysis', polarity='rejects', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='place and institution description', claim='David Mitchell states that descriptions of people and places in A Wizard of Earthsea are frugal enough to leave the reader’s imagination room to collaborate.', source=MITS, url=MIT, quote='rich enough to nourish the reader’s imagination, but frugal enough', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='point of view and distance', claim='David Mitchell states that Le Guin gives minor characters who appear only briefly the psychological depth of oil paintings.', source=MITS, url=MIT, quote='thumbnail sketches contain the psychological depth of oil paintings', page='paragraph on minor characters (Pechvarry)', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='place and institution description', claim='David Mitchell lists trade-routes, local politics, class hierarchies, infant mortality, abuse, addiction and slavery as the mundane institutional furniture that makes Earthsea’s fantastical elements feel quotidian.', source=MITS, url=MIT, quote='trade-routes, local politics, class hierarchies, infant mortality, abuse, addiction and slavery', page='paragraph beginning "Earthsea is a fantasy world"', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='mitchell-guardian.txt')
add(feature='withheld information and inference', claim='David Mitchell states that A Wizard of Earthsea contains moments of foreshadowing and authorial omniscience but no tricks.', source=MITS, url=MIT, quote='moments of foreshadowing and authorial omniscience but no tricks', page='section on style and voice', kind='analysis', polarity='asserts', date='2015-10-23', routeHint='live URL with browser user agent', registerHint='chronicle-line', confidence='high', _file='mitchell-guardian.txt')

# ---- Atwood NYRB 2002 ----
add(feature='plainness and economy', claim='Margaret Atwood names graceful prose first among the qualities that earned Le Guin her awards.', source=ATWS, url=ATW, quote='her graceful prose, carefully thought-through premises, psychological insight', page='paragraph beginning "Which brings us to Ursula K. Le Guin"', kind='reception', polarity='asserts', date='2002-09-26', routeHint='live nybooks.com URL with browser user agent returned the full article text', registerHint='none', confidence='high', _file='nybooks-quinkdom.txt')
add(feature='civic record register', claim='Margaret Atwood describes the task of Le Guin’s Ekumen envoys as non-invasive, non-directive understanding and recording of the societies they visit.', source=ATWS, url=ATW, quote='non-directive understanding and recording are the functions required', page='paragraph describing the Ekumen premise', kind='analysis', polarity='asserts', date='2002-09-26', routeHint='live nybooks.com URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='nybooks-quinkdom.txt')
add(feature='register modulation', claim='Margaret Atwood states that Le Guin, though at times a movingly lyrical writer, has never avoided writing gore when the story required it.', source=ATWS, url=ATW, quote='at times a movingly lyrical writer', page='paragraph on "Old Music and the Slave Women"', kind='analysis', polarity='asserts', date='2002-09-26', routeHint='live nybooks.com URL with browser user agent', registerHint='none', confidence='high', _file='nybooks-quinkdom.txt')
add(feature='closing sentence', claim='Margaret Atwood characterises the closing scene of The Birthday of the World as a minimalist dance and quotes it as the book’s last words.', source=ATWS, url=ATW, quote='ends with a minimalist dance, as an old woman', page='final paragraph', kind='analysis', polarity='asserts', date='2002-09-26', routeHint='live nybooks.com URL with browser user agent', registerHint='chronicle-line', confidence='high', _file='nybooks-quinkdom.txt')
add(feature='other: process over theory in forewords', claim='Margaret Atwood states that in the foreword to The Birthday of the World Le Guin describes process rather than theory, giving the genesis of each story.', source=ATWS, url=ATW, quote='Le Guin describes process rather than theory', page='paragraph comparing the two introductions', kind='analysis', polarity='asserts', date='2002-09-26', routeHint='live nybooks.com URL with browser user agent', registerHint='none', confidence='high', _file='nybooks-quinkdom.txt')

# ---- Kirkus 1990 ----
add(feature='plainness and economy', claim='The unsigned Kirkus review of Tehanu calls the novel’s prose flawless and poetic and says even young readers will be beguiled by it.', source=KIRS, url=KIR, quote='beguiled by the flawless, poetic prose', page='review body', kind='reception', polarity='asserts', date='1990-02-01', routeHint='live kirkusreviews.com URL (path /book-reviews/ursula-k-le-guin/tehanu/) with browser user agent', registerHint='none', confidence='high', _file='kirkus-tehanu.txt')
add(feature='other: pacing', claim='The unsigned Kirkus review of Tehanu records that the action moves slowly while Le Guin explores her themes.', source=KIRS, url=KIR, quote='the action moves slowly as Le Guin explores her themes', page='review body', kind='reception', polarity='asserts', date='1990-02-01', routeHint='live kirkusreviews.com URL with browser user agent', registerHint='none', confidence='high', _file='kirkus-tehanu.txt')
add(feature='annalist voice and deep time', claim='The unsigned Kirkus review of Tehanu says Le Guin weaves contemporary concerns into a tale carrying the universality and dignity of legend.', source=KIRS, url=KIR, quote='a tale with the universality and dignity of legend', page='review body', kind='reception', polarity='asserts', date='1990-02-01', routeHint='live kirkusreviews.com URL with browser user agent', registerHint='chronicle-line', confidence='high', _file='kirkus-tehanu.txt')
add(feature='metaphor discipline', claim='The unsigned Kirkus review of Tehanu says the novel’s philosophy is expressed in thoughtful, potent metaphor.', source=KIRS, url=KIR, quote='the philosophy expressed in thoughtful, potent metaphor', page='review body', kind='reception', polarity='asserts', date='1990-02-01', routeHint='live kirkusreviews.com URL with browser user agent', registerHint='none', confidence='high', _file='kirkus-tehanu.txt')

# ---- LOA tribute page 2018 ----
add(feature='sentence length variation', claim='Zadie Smith, in the Library of America tribute page, calls Le Guin’s sentences as elegant and beautiful as any written in the twentieth century.', source='Zadie Smith, in "Fellow writers remember Ursula K. Le Guin, 1929–2018", Library of America, January 2018', url=LOA, quote='her sentences, as elegant and beautiful as any written', page='Zadie Smith entry', kind='reception', polarity='asserts', date='2018-01', routeHint='live loa.org URL (news-and-views/1375-...) with browser user agent', registerHint='none', confidence='high', _file='loa-fellow.txt')
add(feature='plainness and economy', claim='Harold Bloom, in the Library of America tribute page, calls Le Guin an exquisite stylist.', source='Harold Bloom, in "Fellow writers remember Ursula K. Le Guin, 1929–2018", Library of America, January 2018', url=LOA, quote='Ursula was an exquisite stylist', page='Harold Bloom entry', kind='reception', polarity='asserts', date='2018-01', routeHint='live loa.org URL with browser user agent', registerHint='none', confidence='high', _file='loa-fellow.txt')
add(feature='cadence and rhythm', claim='Harold Bloom, in the Library of America tribute page, states that in Le Guin every word was exactly in place and every sentence or line had resonance.', source='Harold Bloom, in "Fellow writers remember Ursula K. Le Guin, 1929–2018", Library of America, January 2018', url=LOA, quote='Every word was exactly in place', page='Harold Bloom entry', kind='reception', polarity='asserts', date='2018-01', routeHint='live loa.org URL with browser user agent', registerHint='none', confidence='high', _file='loa-fellow.txt')

# ---- Amanda Craig, Guardian 2003 ----
add(feature='annalist voice and deep time', claim='Amanda Craig states that Earthsea gains the mysterious depths of Tolkien’s world without Tolkien’s back-stories and verse.', source=CRAS, url=CRA, quote='the mysterious depths of Tolkien’s, but without his tiresome back-stories', page='Classic of the month column', kind='analysis', polarity='asserts', date='2003-09-24', routeHint='live theguardian.com URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='craig-guardian.txt')
add(feature='withheld information and inference', claim='Amanda Craig states that A Wizard of Earthsea contains allusions to fragmented legends about the tragedies of heroes and heroines.', source=CRAS, url=CRA, quote='allusions to fragmented legends about the tragedies of heroes', page='Classic of the month column', kind='analysis', polarity='asserts', date='2003-09-24', routeHint='live theguardian.com URL with browser user agent', registerHint='chronicle-line', confidence='high', _file='craig-guardian.txt')

# ---- Walton ----
add(feature='cadence and rhythm', claim='Jo Walton states that Tehanu reads aloud beautifully, as she found while reading it aloud to a baby.', source=WGS, url=WG, quote='It reads aloud beautifully', page='essay body', kind='analysis', polarity='asserts', date='2011-10-25', routeHint='reactormag.com slug with "ursula-k-le-guins" (the "ursula-le-guins" form 404s); browser user agent', registerHint='herald-pools', confidence='high', _file='walton-gont.txt')
add(feature='other: pacing', claim='Jo Walton calls Tehanu a restless book with very strange pacing.', source=WGS, url=WG, quote='This is a restless book with very strange pacing', page='essay body', kind='analysis', polarity='asserts', date='2011-10-25', routeHint='reactormag.com live URL, browser user agent', registerHint='none', confidence='high', _file='walton-gont.txt')
add(feature='other: domestic detail', claim='Jo Walton states that she did not believe in Tenar’s life as a farmwife on Gont and that something about it rings false.', source=WGS, url=WG, quote='there’s something false about it', page='essay body', kind='analysis', polarity='disputes', date='2011-10-25', routeHint='reactormag.com live URL, browser user agent', registerHint='dossier-archivist', confidence='high', _file='walton-gont.txt')
add(feature='register modulation', claim='Jo Walton states that The Tombs of Atuan is beautifully written but, unlike A Wizard of Earthsea, is not told like a legend.', source=WES, url=WE, quote='beautifully written, but it isn’t told like a legend', page='essay body', kind='analysis', polarity='asserts', date='2011', routeHint='reactormag.com slug with "ursula-k-le-guins"; browser user agent', registerHint='chronicle-line', confidence='high', _file='walton-eaten.txt')
add(feature='point of view and distance', claim='Jo Walton states that The Tombs of Atuan keeps the reader straightforwardly behind Tenar’s shoulder for the whole book.', source=WES, url=WE, quote='straightforwardly right behind Tenar’s shoulder the entire time', page='essay body', kind='analysis', polarity='asserts', date='2011', routeHint='reactormag.com live URL, browser user agent', registerHint='none', confidence='high', _file='walton-eaten.txt')
add(feature='closing sentence', claim='Jo Walton observes that A Wizard of Earthsea calls Ged a "young wizard" at its close while The Tombs of Atuan describes Tenar at its close as "like a child coming home".', source=WES, url=WE, quote='like a child coming home', page='essay body', kind='analysis', polarity='asserts', date='2011', routeHint='reactormag.com live URL, browser user agent', registerHint='chronicle-line', confidence='high', _file='walton-eaten.txt')
add(feature='omission as information', claim='Jo Walton states that a lesser writer would have ended The Tombs of Atuan with the earthquake and the triumphant escape, and that Le Guin instead carries on into the escape through the mountains.', source=WES, url=WE, quote='a lesser writer would have finished the book with the earthquake', page='essay body', kind='analysis', polarity='asserts', date='2011', routeHint='reactormag.com live URL, browser user agent', registerHint='chronicle-line', confidence='medium', confidenceReason='the quotation is contiguous on the page but the claim compresses two adjacent sentences', _file='walton-eaten.txt')

# ---- Phillips New Yorker 2016 ----
add(feature='place and institution description', claim='Julie Phillips reports that Le Guin learned from Thomas Hardy to handle strong feeling by pouring it into landscape so the setting carries part of the emotional charge.', source=PHS, url=PH, quote='letting the settings carry part of the emotional charge', page='section on her reading as a girl', kind='analysis', polarity='asserts', date='2016-10-17', routeHint='live newyorker.com URL with browser user agent returned the full article text', registerHint='dossier-archivist', confidence='high', _file='phillips-newyorker.txt')
add(feature='place and institution description', claim='Le Guin, quoted by Julie Phillips, rejects the term "pathetic fallacy" for letting a landscape carry feeling and calls the technique art.', source='Ursula K. Le Guin, in interview with Julie Phillips, The New Yorker, 17 October 2016', url=PH, quote='It’s not a fallacy; it’s art', page='section on her reading as a girl', kind='own-words', polarity='asserts', date='2016-10-17', routeHint='live newyorker.com URL with browser user agent', registerHint='dossier-archivist', confidence='high', _file='phillips-newyorker.txt')
add(feature='other: reception of obliquity', claim='Julie Phillips reports that after 1974 some readers found The Left Hand of Darkness too oblique and metaphorical and its play evasive rather than illuminating.', source=PHS, url=PH, quote='seemed to some readers too oblique and metaphorical', page='section on the years after The Dispossessed', kind='reception', polarity='disputes', date='2016-10-17', routeHint='live newyorker.com URL with browser user agent', registerHint='none', confidence='high', _file='phillips-newyorker.txt')

# ---- Erlich ----
add(feature='per-speaker register', claim='Richard D. Erlich states that Le Guin’s method in Always Coming Home is a fairly exhaustive ethnography that works by having many voices speak the world of the Kesh.', source=ES+'"Always Coming Home: Future Ethnography"', url=EA, quote='exhaustive ethnography: having all those voices speaking the world', page='chapter Always Coming Home, endnote 36', kind='analysis', polarity='asserts', date='2009', routeHint='Wayback raw capture https://web.archive.org/web/20151107114510id_/http://sfra.org/Coyote/alwayshome.htm (redirects to the 20150924204511 capture of www.sfra.org)', registerHint='dossier-archivist', confidence='high', _file='erlich-alwayshome.txt')
add(feature='omission as information', claim='Richard D. Erlich identifies a point in Tehanu where how Therru knows Tenar has lied is hinted at but never explained, and calls it a gap left for readers to fill.', source=ES+'"Earthsea Revisited: Tehanu"', url=EE, quote='a significant gap to be left or filled in by readers', page='chapter Earthsea Revisited: Tehanu', kind='analysis', polarity='asserts', date='2009', routeHint='Wayback raw capture .../Coyote/earthsea.htm at timestamp 20151107114510', registerHint='dossier-archivist', confidence='high', _file='erlich-earthsea.txt')
add(feature='parataxis vs hypotaxis', claim='Richard D. Erlich notes that Le Guin sets a conclusion-drawing sentence in Tehanu off in a paragraph of its own with no transition and no explanation of the phrase it turns on.', source=ES+'"Earthsea Revisited: Tehanu"', url=EE, quote='marked by no transition but set off in a paragraph', page='chapter Earthsea Revisited: Tehanu', kind='analysis', polarity='asserts', date='2009', routeHint='Wayback raw capture of /Coyote/earthsea.htm', registerHint='chronicle-line', confidence='high', _file='erlich-earthsea.txt')
add(feature='register modulation', claim='Richard D. Erlich states that Tehanu gains a different style from the Earthsea trilogy, which he calls a welcome variation from the high-fantastic.', source=ES+'"Earthsea Revisited: Tehanu"', url=EE, quote='a welcomed variation from the high-fantastic', page='chapter Earthsea Revisited: Tehanu, closing section', kind='analysis', polarity='asserts', date='2009', routeHint='Wayback raw capture of /Coyote/earthsea.htm', registerHint='none', confidence='high', _file='erlich-earthsea.txt')
add(feature='opening sentence', claim='Richard D. Erlich, with a linguist colleague, describes the opening sentence of Always Coming Home as past conditional, semi-conditional and emphatic past perfect, implying futurity.', source=ES+'"Always Coming Home: Future Ethnography", endnote 29', url=EA, quote='emphatic past perfect, implying futurity', page='chapter Always Coming Home, endnote 29', kind='analysis', polarity='asserts', date='2009', routeHint='Wayback raw capture of /Coyote/alwayshome.htm', registerHint='dossier-archivist', confidence='high', _file='erlich-alwayshome.txt')

S=[
 dict(title='David Mitchell on Earthsea: a rival to Tolkien and George RR Martin', url=MIT, kind='analysis', substantive=True, date='2015-10-23', route='live URL, browser UA'),
 dict(title='The Queen of Quinkdom (review of The Birthday of the World)', url=ATW, kind='reception', substantive=True, date='2002-09-26', route='live URL, browser UA'),
 dict(title='TEHANU — Kirkus Reviews', url=KIR, kind='reception', substantive=True, date='1990-02-01', route='live URL, browser UA'),
 dict(title='Fellow writers remember Ursula K. Le Guin, 1929–2018', url=LOA, kind='reception', substantive=True, date='2018-01', route='live URL, browser UA'),
 dict(title='Classic of the month: A Wizard of Earthsea', url=CRA, kind='analysis', substantive=True, date='2003-09-24', route='live URL, browser UA'),
 dict(title='A Woman on Gont: Ursula K. Le Guin’s Tehanu', url=WG, kind='analysis', substantive=True, date='2011-10-25', route='live URL, browser UA'),
 dict(title='Let her be eaten: Ursula K. Le Guin’s The Tombs of Atuan', url=WE, kind='analysis', substantive=True, date='2011', route='live URL, browser UA'),
 dict(title='The Fantastic Ursula K. Le Guin', url=PH, kind='analysis', substantive=True, date='2016-10-17', route='live URL, browser UA'),
 dict(title='Coyote’s Song, ch. "Always Coming Home: Future Ethnography"', url=EA, kind='analysis', substantive=True, date='2009', route='Wayback id_ raw capture'),
 dict(title='Coyote’s Song, ch. "Earthsea Revisited: Tehanu"', url=EE, kind='analysis', substantive=True, date='2009', route='Wayback id_ raw capture'),
 dict(title='Ursula K. Le Guin, tribute (The Guardian)', url='https://www.theguardian.com/books/2018/jan/24/ursula-k-le-guin-margaret-atwood-tribute', kind='reception', substantive=False, date='2018-01-24', route='live URL, browser UA — read in full; a personal farewell with no line-level style observation'),
 dict(title='Coyote’s Song home page / table of contents', url='https://web.archive.org/web/20151107114510id_/http://sfra.org/Coyote/CoyoteHome.htm', kind='analysis', substantive=False, date='2009', route='Wayback id_ raw capture — navigation only'),
]
if __name__=='__main__':
    B.build(C,S,'IN PROGRESS - first checkpoint',False)
