# -*- coding: utf-8 -*-
import importlib.util, os, sys
d=os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0,d)
import claims1 as P
B=P.B
C=P.C; S=P.S
def add(**k): C.append(k)

DIR='https://www.washingtonpost.com/archive/entertainment/books/1990/02/25/the-twilight-of-an-age-of-magic/34d58490-4114-430b-890e-dc3dc3a3680a/'
DIRS='Michael Dirda, "The Twilight of an Age of Magic" (review of Tehanu), The Washington Post, 25 February 1990'
DR='dirda-wapo.txt'
NYT='https://www.nytimes.com/2018/01/23/obituaries/ursula-k-le-guin-acclaimed-for-her-fantasy-fiction-is-dead-at-88.html'
NYTS='Gerald Jonas, obituary of Ursula K. Le Guin, The New York Times, 23 January 2018'
GW='https://reactormag.com/a-wizard-of-earthsea-the-unsung-song-of-the-shadow/'
GWS='Sean Guynes, "A Wizard of Earthsea: The Unsung Song of the Shadow", The Ursula K. Le Guin Reread, Tor.com, 8 April 2020'
KE='https://paradoxa.com/wp-content/uploads/2020/07/1-Boldly-to-Re-Venture-New-Writing-on-the-Works-of-Ursula-K.-Le-Guin-Kelso-pp-7-22.pdf'
KES='Sylvia A. Kelso, "Boldly to Re-Venture: New Writing on the Works of Ursula K. Le Guin", Paradoxa 21 (2009), pp. 7-22'
KR='Wayback/live PDF: paradoxa.com hosts this one article of Paradoxa 21 as a free PDF; binary fetched with curl and text extracted with pypdf'

# ---- Dirda, Washington Post 1990 ----
add(feature='civic record register', claim='Michael Dirda states that the narrating voice of the first three Earthsea books is that of a chronicler or mythmaker.', source=DIRS, url=DIR, quote='the voice that of the chronicler or mythmaker', page='review body, paragraph on the earlier novels', kind='analysis', polarity='asserts', date='1990-02-25', routeHint='Wayback raw capture https://web.archive.org/web/20170827235846id_/<washingtonpost archive url>; the live washingtonpost.com URL aborted the TLS stream', registerHint='chronicle-line', confidence='high', _file=DR)
add(feature='diction (native vs latinate)', claim='Michael Dirda characterises the prose of the Earthsea trilogy as grave and elevated, a style of moral seriousness.', source=DIRS, url=DIR, quote='The prose is grave and elevated, a style of moral seriousness', page='review body, paragraph on the earlier novels', kind='analysis', polarity='asserts', date='1990-02-25', routeHint='Wayback raw capture of the Washington Post archive page', registerHint='chronicle-line', confidence='high', _file=DR)
add(feature='register modulation', claim='Michael Dirda states that Tehanu is consequently meditative, somber, even talky, in contrast to the journeying of the earlier books.', source=DIRS, url=DIR, quote='It is consequently meditative, somber, even talky', page='review body', kind='analysis', polarity='asserts', date='1990-02-25', routeHint='Wayback raw capture of the Washington Post archive page', registerHint='none', confidence='high', _file=DR)
add(feature='other: hostile reception', claim='Michael Dirda reports that some critics feel Le Guin’s recent writing has grown windy and soft, too feminist, too mythic, too preachy.', source=DIRS, url=DIR, quote='Le Guin’s writing has grown windy and soft, too feminist', page='review body, penultimate section', kind='reception', polarity='mentions', date='1990-02-25', routeHint='Wayback raw capture of the Washington Post archive page', registerHint='none', confidence='high', _file=DR)
add(feature='sentence length variation', claim='Michael Dirda states that Le Guin can still stand your hair on end with her sentences, and introduces a quoted Tehanu passage as the demonstration.', source=DIRS, url=DIR, quote='stand your hair on end with her sentences', page='review body, penultimate section', kind='analysis', polarity='asserts', date='1990-02-25', routeHint='Wayback raw capture of the Washington Post archive page', registerHint='none', confidence='high', _file=DR)
add(feature='opening sentence', claim='Michael Dirda opens his review by quoting the first sentence of A Wizard of Earthsea, which names the island of Gont, its mile-high peak, its towns in high valleys and its ports on dark narrow bays before naming any person.', source=DIRS, url=DIR, quote='a single mountain that lifts its peak a mile above', page='review opening, quoting A Wizard of Earthsea', kind='analysis', polarity='asserts', date='1990-02-25', routeHint='Wayback raw capture of the Washington Post archive page', registerHint='dossier-archivist', confidence='high', _file=DR)

# ---- NYT obituary 2018 ----
add(feature='plainness and economy', claim='Gerald Jonas, in the New York Times obituary, describes Le Guin’s fiction as combining compelling stories and rigorous narrative logic with a lean but lyrical style.', source=NYTS, url=NYT, quote='a lean but lyrical style', page='obituary body', kind='reception', polarity='asserts', date='2018-01-23', routeHint='Wayback raw capture https://web.archive.org/web/20260111213522id_/<nytimes url>; the live nytimes.com URL returns 403 to curl', registerHint='dossier-archivist', confidence='high', _file='nyt-obit.txt')
add(feature='register modulation', claim='Gerald Jonas states that the first three Earthsea books, written for young adults at the publisher’s request, show no trace of writing down to their audience in scale or style.', source=NYTS, url=NYT, quote='elevated style betray no trace of writing down to an audience', page='obituary body', kind='reception', polarity='asserts', date='2018-01-23', routeHint='Wayback raw capture of the NYT obituary', registerHint='none', confidence='high', _file='nyt-obit.txt')
add(feature='naming and forms of address', claim='Le Guin, quoted in her New York Times obituary, said she must find the right name for a character before she can get on with the story.', source='Ursula K. Le Guin, quoted by Gerald Jonas, The New York Times obituary, 23 January 2018', url=NYT, quote='I must find the right name or I cannot get on', page='obituary body, paragraph on true names', kind='own-words', polarity='asserts', date='2018-01-23', routeHint='Wayback raw capture of the NYT obituary', registerHint='dossier-archivist', confidence='high', _file='nyt-obit.txt')
add(feature='other: hostile reception', claim='Harold Bloom, quoted in the New York Times obituary, called Le Guin a superbly imaginative creator and major stylist who raised fantasy into high literature.', source='Harold Bloom, quoted by Gerald Jonas, The New York Times obituary, 23 January 2018', url=NYT, quote='a superbly imaginative creator and major stylist', page='obituary body', kind='relay', polarity='asserts', date='2018-01-23', routeHint='Wayback raw capture of the NYT obituary', registerHint='none', confidence='medium', confidenceReason='the obituary is a relay of Bloom’s earlier written judgement; the primary Bloom text was not located', _file='nyt-obit.txt')

# ---- Guynes reread 2020 ----
add(feature='register modulation', claim='Sean Guynes states that the tone of Le Guin’s writing in A Wizard of Earthsea is simpler and sparser than in The Left Hand of Darkness or The Dispossessed.', source=GWS, url=GW, quote='simpler and sparser than in The Left Hand of Darkness', page='opening section of the reread instalment', kind='analysis', polarity='asserts', date='2020-04-08', routeHint='raw page already banked in the sweep at leguin-craft-raw2/guynes-wizard.txt (Tor.com capture); reread live at reactormag.com', registerHint='none', confidence='high', _file='../leguin-craft-raw2/guynes-wizard.txt')
add(feature='plainness and economy', claim='A reader commenting under Sean Guynes’s reread of A Wizard of Earthsea describes the novel’s language as managing to be both semi-sparse and beautiful.', source='AeronaGreenjoy, reader comment under Sean Guynes’s Le Guin Reread instalment on A Wizard of Earthsea, Tor.com, 2020', url=GW, quote='both semi-sparse and beautiful', page='comment thread', kind='reader', polarity='asserts', date='2020', routeHint='comment thread present in the banked raw capture leguin-craft-raw2/reactor-guynes-live.txt', registerHint='none', confidence='medium', confidenceReason='a reader comment, not a critic; quoted for the reception record only', _file='../leguin-craft-raw2/reactor-guynes-live.txt')

# ---- Kelso, Paradoxa 21 ----
add(feature='cadence and rhythm', claim='Sylvia Kelso states that rhythm, as opposed to scansion, eludes most contemporary critical frames and is not susceptible to ideological analysis.', source=KES, url=KE, quote='Rhythm, as opposed to scansion, eludes most contemporary critical frames', page='p. 14', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='none', confidence='high', _file='kelso.txt')
add(feature='cadence and rhythm', claim='Sylvia Kelso analyses the opening sentence of The Lathe of Heaven as four opposing blocks — two compound adjectives and two clauses — that echo the rhythm of ocean on beach.', source=KES, url=KE, quote='four opposing blocks, two compound adjectives, two clauses', page='p. 14', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='chronicle-line', confidence='high', _file='kelso.txt')
add(feature='cadence and rhythm', claim='Sylvia Kelso judges the quoted opening paragraph of Always Coming Home to contain no rhythmic superfluities.', source=KES, url=KE, quote='Here there are no rhythmic superfluities', page='p. 15', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='dossier-archivist', confidence='high', _file='kelso.txt')
add(feature='sentence length variation', claim='Sylvia Kelso analyses the Always Coming Home opening as a long opening clause that checks into shortening phrases and brakes to a heavy pause at a colon.', source=KES, url=KE, quote='The long opening clause checks into the shortening phrases', page='p. 15', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='dossier-archivist', confidence='high', _file='kelso.txt')
add(feature='plainness and economy', claim='Sylvia Kelso states that Le Guin, like Yeats, seems to move toward simplicity or at least austerity in the rhythm and content of her later work.', source=KES, url=KE, quote='Le Guin does seem to move toward simplicity', page='p. 16', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='dossier-archivist', confidence='high', _file='kelso.txt')
add(feature='plainness and economy', claim='Sylvia Kelso states that Tehanu shows the skill of experience making less do more rather than more do more.', source=KES, url=KE, quote='making less do more, rather than more do more', page='p. 16', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='dossier-archivist', confidence='high', _file='kelso.txt')
add(feature='dialogue register', claim='Sylvia Kelso states that where a playwright can score dialogue with silences a prose writer must rely on business, and that in the Tenar and Moss scene the splitting of rushes performs that function.', source=KES, url=KE, quote='Where playwrights can score dialogue with significant silences', page='p. 16-17', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='none', confidence='high', _file='kelso.txt')
add(feature='repetition and refrain', claim='Sylvia Kelso states that the repeated splitting of rushes in the Tenar and Moss scene operates as a suite of variations marking pause and emphasis.', source=KES, url=KE, quote='a suite of variations to indicate pause and emphasis', page='p. 17', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='chronicle-line', confidence='high', _file='kelso.txt')
add(feature='metaphor discipline', claim='Sylvia Kelso judges that the closing clauses of the bread-and-stone passage in The Lathe of Heaven, though rhythmically necessary, slightly weaken its antithesis and its homely simile.', source=KES, url=KE, quote='actually detract slightly from the antithesis of bread and stone', page='p. 15', kind='analysis', polarity='disputes', date='2009', routeHint=KR, registerHint='none', confidence='high', _file='kelso.txt')
add(feature='cadence and rhythm', claim='Le Guin, quoted by Sylvia Kelso from "Collectors, Rhymesters and Drummers", said that if she could hold to the rhythms of the dragon’s flight the story told itself.', source='Ursula K. Le Guin, "Collectors, Rhymesters and Drummers" (in The Wave in the Mind, 2004), pp. 183-84, quoted by Sylvia Kelso in Paradoxa 21', url=KE, quote='If I could hold to the rhythms of the dragon’s flight', page='p. 17, quoting The Wave in the Mind pp. 183-84', kind='own-words', polarity='asserts', date='2004', routeHint=KR, registerHint='none', confidence='high', _file='kelso.txt')
add(feature='sentence length variation', claim='Sylvia Kelso describes the rhythm of the Kalessin arrival passage in Tehanu as almost somnambulistically smooth, with an extraordinarily long second sentence whose commas weight the critical words.', source=KES, url=KE, quote='almost somnambulistically smooth, the second sentence extraordinarily long', page='p. 17', kind='analysis', polarity='asserts', date='2009', routeHint=KR, registerHint='none', confidence='high', _file='kelso.txt')

S.extend([
 dict(title='The Twilight of an Age of Magic (review of Tehanu)', url=DIR, kind='analysis', substantive=True, date='1990-02-25', route='Wayback id_ raw capture'),
 dict(title='Ursula K. Le Guin, Acclaimed for Her Fantasy Fiction, Is Dead at 88', url=NYT, kind='reception', substantive=True, date='2018-01-23', route='Wayback id_ raw capture'),
 dict(title='A Wizard of Earthsea: The Unsung Song of the Shadow (Le Guin Reread)', url=GW, kind='analysis', substantive=True, date='2020-04-08', route='raw capture already banked in the sweep'),
 dict(title='Boldly to Re-Venture: New Writing on the Works of Ursula K. Le Guin (Paradoxa 21)', url=KE, kind='analysis', substantive=True, date='2009', route='free PDF from paradoxa.com, text extracted with pypdf'),
 dict(title='Volume 21 – Ursula K. Le Guin (Paradoxa contents page)', url='https://paradoxa.com/volume-21-ursula-k-le-guin/', kind='relay', substantive=False, date='2009', route='live URL — contents listing; only the Kelso introduction is free, the other sixteen articles are paywalled per-article PDFs'),
])
if __name__=='__main__':
    B.build(C,S,'IN PROGRESS - second checkpoint',False)
