import fs from 'node:fs';
const p = process.argv[2];
const rows = JSON.parse(fs.readFileSync(p,'utf8'));
console.log('total rows', rows.length);
const byReg = {};
for (const r of rows) byReg[r.register] = (byReg[r.register]||0)+1;
console.log(JSON.stringify(byReg));
const keys = new Set();
for (const r of rows.slice(0,500)) Object.keys(r).forEach(k=>keys.add(k));
console.log('fields(first500):', [...keys].join(','));
const allkeys = new Set();
for (const r of rows) Object.keys(r).forEach(k=>allkeys.add(k));
console.log('fields(all):', [...allkeys].join(','));
