// R15-TAIL classifier. Ordered rules; FIRST match wins. Each rule carries the
// consumer site actually READ in the tree (file:line) and a note.
// cls: reader | dm-only | dev | ai-prompt | ambiguous
export const FILE_RULES = [
  // ── verified by reading the render site ───────────────────────────────────
  { f:'src/data/tradeGoodsData.js', e:'INSTITUTION_SERVICES', cls:'reader',
    cp:'src/components/ServicesTogglePanel.jsx:58', n:'{def.desc} rendered under each service toggle' },
  { f:'src/store/selectors.js', e:'selectCurrentCatalog()', cls:'reader',
    cp:'src/components/InstitutionalGrid.jsx:143', n:'truncateAtWord(instDef.desc,80) on the institution card; full text at :271' },
  { f:'src/domain/compendium/searchIndex.js', e:'COMPENDIUM_INDEX', leaf:'.term', cls:'reader',
    cp:'src/components/compendium/CompendiumGlobalSearch.jsx:179', n:'{r.term} is the search-result row label' },
  { f:'src/domain/compendium/searchIndex.js', e:'COMPENDIUM_INDEX', leaf:'.keywords', cls:'dev',
    cp:'src/domain/compendium/searchIndex.js:264', n:'match-only token bag folded into the search haystack; never rendered and NOT in the SEO description (seoCompendium.js:51-53 uses term+category only)' },
  { f:'src/data/stressInstitutionEffects.js', e:'STRESS_INSTITUTION_EFFECTS', cls:'dm-only',
    cp:'src/generators/npcGenerator.js:779 -> src/components/new/npcComponents.jsx:458', n:'becomes npc.secret{what,stakes}; PRIVATE_KEY_RE (publicSafe.js:101) strips `secret` from every public projection unless the owner opts into shareDm (ShareToGallery.jsx:452)' },
  { f:'src/domain/autonomy/index.js', e:'signalRegistryEntries()', cls:'ai-prompt',
    cp:'src/domain/aiCharter.js:278', n:'lines.push(`      ${entry.description}`) inside the AI CHARTER teaching block destined for the static prompt prefixes; AutonomyPanel.jsx renders no `description`' },
  { f:'src/domain/worldPulse/stressorDynamics.js', e:'VARIANT_HOOKS', cls:'dm-only',
    cp:'src/domain/worldPulse/stressorDynamics.js:738', n:'stamped as originContext.hooks on a newborn stressor; `hook` is a PRIVATE_KEY_RE key (publicSafe.js:101), so it is DM-side only' },
  { f:'src/domain/worldPulse/stressorDynamics.js', e:'STRESSOR_SYNERGIES', cls:'dev',
    cp:'src/domain/worldPulse/stressorDynamics.js:548', n:'synergyAssessment() reads the table for decayMult/resolutionDelta/blocksResolution/companions and never returns `.note`' },
  { f:'src/domain/display/warAndRoadNames.js', cls:'reader',
    cp:'src/domain/display/warAndRoadNames.js:275 -> src/components/new/tabs/WarTab.jsx', n:'render-time war/road names; consumed inside the file by deriveWarName()/route naming (no non-test importer of the pools themselves)' },
  { f:'src/lib/instantWorld/factionDedup.js', e:'candidateNames()', cls:'reader',
    cp:'src/lib/instantWorld/factionDedup.js:134', n:'world-scoped faction display names minted for the composer' },
  { f:'src/components/organic/samples/fixtures.js', cls:'reader',
    cp:'src/components/organic/samples/DossierSample.jsx', n:'the taste-veto sample screens typeset these strings verbatim' },
  { f:'src/components/home/landingFixture.js', cls:'reader',
    cp:'src/components/home/LandingArtifacts.jsx:231', n:'frozen engine output rendered on the landing artifacts' },
  { f:'src/domain/worldPulse/habitForkRegistry.js', cls:'dev',
    cp:'tests/lint/chooserTotality.walker.test.js:53', n:'the chooser-totality classification registry; no product importer at all' },
  { f:'src/domain/tuning/proposedSoakBands.js', cls:'dev',
    cp:'scripts/check-tuning-bands.mjs', n:'tuning-band manifest read only by a script' },
  { f:'src/lib/flags.js', e:'FLAGS', leaf:'.description', cls:'dev',
    cp:'src/components/dev/DevFlagPanel.jsx', n:'feature-flag registry descriptions; the only render surface is the dev flag panel' },
  { f:'src/domain/fieldManifest.js', cls:'dev',
    cp:'src/domain/fieldManifest.js', n:'structural-prevention manifest (frozen-vs-live display rules), a dev contract' },
  { f:'src/domain/worldPulse/pulseStageManifest.js', cls:'dev',
    cp:'src/domain/worldPulse/pulseStageManifest.js', n:'declarative pulse topology; purpose strings are dev documentation' },
  { f:'src/design/organic/index.js', cls:'dev', cp:'src/design/organic/motion.js', n:'design tokens + motion grammar glosses' },
  { f:'src/design/boundBook.js', cls:'dev', cp:'scripts/audit/bound-book-report.mjs', n:'design policy substrate, declarations only' },
  { f:'src/domain/aiGrounding.js', cls:'ai-prompt', cp:'src/store/settlementSlice.js', n:'AI prompt grounding envelope; assemblePromptSections()/forbiddenChanges() are prompt text' },
  { f:'src/domain/ai/suggestedQuestions.js', cls:'reader', cp:'src/components/AiAnalystPanel.jsx', n:'the zero-cost empty-state question chips the DM clicks' },
  { f:'src/domain/townMap/arch/cathedralSection.js', cls:'dev', cp:'scripts/generate-k0b.mjs', n:'3D spike element names, script-only' },
  { f:'src/domain/npc/characterReadModel.js', e:'EXPERIENCE_CLAUSES', cls:'ambiguous',
    cp:'src/domain/npc/characterReadModel.js:420', n:'authored reader clauses, but the module is reachable from NO product surface at fd36f0298 (dark prose)' },
  { f:'src/domain/display/engagementNarrative.js', cls:'ambiguous',
    cp:'src/domain/display/engagementNarrative.js:341', n:'authored battle-phase prose; the module is reachable from no product surface at fd36f0298 (dark prose)' },
  { f:'src/data/securityQuestions.js', cls:'reader', cp:'src/components/auth/SecurityQuestionsFields.jsx', n:'account-recovery question text shown at sign-up' },
  { f:'src/data/roadmapLedger.js', cls:'reader', cp:'src/components/howto/RoadmapPage.jsx', n:'the public roadmap page renders exactly this list' },
  { f:'src/lib/seo.js', cls:'reader', cp:'src/lib/seo.js:242', n:'per-route <meta name=description>; reader-facing outside the app chrome' },
  { f:'src/lib/galleryHubs.js', cls:'reader', cp:'src/components/gallery/GalleryHubPage.jsx', n:'facet-hub landing blurbs' },
  { f:'src/components/settlement/eventComposer/EventComposerConstants.js', e:'_TYPE_ICONS', cls:'dev',
    cp:'src/components/settlement/eventComposer/EventComposerConstants.js', n:'SVG path `d` attributes, not prose (corpus false positive)' },
  { f:'src/domain/display/visibilityAudit.js', cls:'dev', cp:'src/components/admin/AdminSimTuningPanel.jsx', n:'admin-only audit check labels' },
];

// leaf-key / export-name patterns, applied when no FILE_RULE matched
export const PATTERN_RULES = [
  { test:(r)=>/(_DARK_POOLS|_UNREACHABLE_POOLS|_BLOCKED_POOLS)$/.test(r.exp), cls:'dev',
    cp:'src/domain/display/stateProse/dossierMounts.js', n:'witness pool KEYS for the dark/unreachable ledger, never prose shown to anyone' },
  { test:(r)=>/PoolKey\(\)$/.test(r.exp)||r.leaf==='.poolKey', cls:'dev',
    cp:'src/domain/display/stateProse/*', n:'a pool KEY string (the corpus block address), not the pooled sentence' },
  { test:(r)=>/(_PROVENANCE|_TUNING_COVERAGE|_COVERAGE|_MANIFEST|_LAW|_GATE_DISPOSITION|_DISPOSITION|_SEAMS|_COUPLINGS|_EXEMPT|PARITY_EXEMPT|_REGISTRY_?PROVENANCE)$/.test(r.exp)
      || /^PARKED_/.test(r.exp) || /^EXEMPT_/.test(r.exp) || /_FACET_REGISTRY$/.test(r.exp), cls:'dev',
    cp:'(declaration site)', n:'owner-provenance / coverage / law / parked-item ledger: dev-side declarations, never rendered' },
  { test:(r)=>['.status','.rationale','.ruling','.rejected','.measured','.closeOwed','.unblockingAct','.consumers','.sourceNote','.displayRule','.rule','.means','.purpose','.evidence','.guard','.read','.reads','.grazes','.cost','.fact','.claimedFamily','.subject','.d'].includes(r.leaf), cls:'dev',
    cp:'(declaration site)', n:'dev-note leaf key (provenance status / ruling / owed act / design rule)' },
  { test:(r)=>r.leaf==='.why', cls:'dev', cp:'(declaration site)', n:'`why` rows are the surface-manifest rationale columns the walkers read' },
  { test:(r)=>/^(validate|evaluate)[A-Z]/.test(r.exp) && /errors|reasons/.test(r.path), cls:'dev',
    cp:'(validator)', n:'validator error strings' },
  { test:(r)=>r.leaf==='.secret'||r.leaf==='.stakes', cls:'dm-only',
    cp:'src/domain/display/publicSafe.js:101', n:'NPC secret pair; stripped from every public projection' },
];
