# -*- coding: utf-8 -*-
import json,os
OUT='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/found-dnd-scholarship-history.json'
Z46='https://zenopusarchives.blogspot.com/2015/02/part-46-zenopus-built-tower.html'
ALEX='https://thealexandrian.net/wordpress/4051/roleplaying-games/dungeon-delve-wtf'
DT='https://deathtrap-games.blogspot.com/2021/08/designing-layout-and-information-in.html'
GH='https://greyhawkery.blogspot.com/2011/06/new-article-d-adventure-format.html'
DE='https://deltasdnd.blogspot.com/2021/10/early-evolution-of-encounter-text.html'
DTAM='https://deltasdnd.blogspot.com/2017/10/tip-offs-in-tamoachan.html'
DD24='https://www.rpg.net/columns/designers-and-dragons/designers-and-dragons24.phtml'
M624='https://www.dndbeyond.com/posts/624-lets-design-an-adventure-adventure-hooks-and'
M626='https://www.dndbeyond.com/posts/626-lets-design-an-adventure-encounter-basics'

sources=[
 {"title":"Part 46: \"Zenopus Built a Tower\" (Holmes manuscript vs published Basic Set)","url":Z46,"kind":"analysis","substantive":True,"date":"2015-02-06","route":"direct fetch"},
 {"title":"Dungeon Delve - WTF? (quoting Bill Slavicsek's introduction to Dungeon Delve, 2009)","url":ALEX,"kind":"analysis","substantive":True,"date":"2009-04-16","route":"direct fetch"},
 {"title":"Designing Layout and Information in Adventures","url":DT,"kind":"analysis","substantive":True,"date":"2021-08-29","route":"direct fetch"},
 {"title":"New Article: D&D Adventure Format (quoting Bruce Cordell's Design & Development column)","url":GH,"kind":"analysis","substantive":True,"date":"2011-06-30","route":"direct fetch"},
 {"title":"Early Evolution of Encounter Text","url":DE,"kind":"measurement","substantive":True,"date":"2021-10-25","route":"direct fetch"},
 {"title":"Tip-Offs in Tamoachan","url":DTAM,"kind":"analysis","substantive":True,"date":"2017-10-02","route":"direct fetch"},
 {"title":"Designers & Dragons: The Column #24: My History of Dungeons & Dragons, Part One","url":DD24,"kind":"analysis","substantive":True,"date":"2013-01-23","route":"Wayback raw capture 20240224035027 (live rpg.net returns 403)"},
 {"title":"Let's Design an Adventure: Adventure Hooks and Opening Scenes","url":M624,"kind":"own-words","substantive":True,"date":"2019-10-23","route":"direct fetch of https://www.dndbeyond.com/posts/624"},
 {"title":"Let's Design an Adventure: Encounter Basics","url":M626,"kind":"own-words","substantive":True,"date":"2019-12-04","route":"direct fetch of https://www.dndbeyond.com/posts/626"},
]

claims=[
 # --- Zenopus Archives / Holmes Basic ---
 {"feature":"place and institution description","claim":"Zach Howard judges the introduction to the Holmes Basic Sample Dungeon highly evocative, reading almost like weird fiction.","source":"Zach Howard (Zenopus Archives), 'Part 46: \"Zenopus Built a Tower\"', 2015","url":Z46,"quote":"The introduction is highly evocative, reading almost like the weird fiction","page":"section 'SAMPLE DUNGEON'","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"boxed text form","claim":"J. Eric Holmes instructs the Dungeon Master to read the sample dungeon's background material aloud to the assembled players.","source":"J. Eric Holmes, D&D Basic Set (1977), quoted by Zach Howard (Zenopus Archives) 2015","url":Z46,"quote":"should read the background material above to the assembled players","page":"section 'SAMPLE DUNGEON', quoted rulebook text","kind":"own-words","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"boxed text form","claim":"Howard reads Holmes's Portown background as material meant to be read to the players, predating boxed text.","source":"Zach Howard (Zenopus Archives), 'Part 46', 2015","url":Z46,"quote":"this background material is meant to be read to the players","page":"commentary on the Portown paragraph","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Howard calls Holmes's one-paragraph account of Portown's trade, ships and inhabitants a thumbnail sketch of a campaign setting.","source":"Zach Howard (Zenopus Archives), 'Part 46', 2015","url":Z46,"quote":"Here we get a thumbnail sketch of a campaign setting","page":"commentary on the Portown paragraph","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: adventure as coherent mini-setting","claim":"Howard contrasts OD&D's Sample Level, a collection of examples, with Holmes presenting his dungeon as part of a coherent adventure.","source":"Zach Howard (Zenopus Archives), 'Part 46', 2015","url":Z46,"quote":"presents his dungeon ideas as part of a coherent adventure","page":"section 'SAMPLE DUNGEON'","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"terminology consistency","claim":"TSR's published Basic Set changed Holmes's manuscript phrase 'one or more assistants' to 'one or more men-at-arms'.","source":"Zach Howard (Zenopus Archives), 'Part 46', 2015","url":Z46,"quote":"changes \"one or more assistants\" to \"one or more men-at-arms\"","page":"closing commentary on the introduction","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"dm-facing sentence","claim":"TSR moved a sentence of Holmes's introduction to the end of its paragraph so it sat immediately before the room descriptions.","source":"Zach Howard (Zenopus Archives), 'Part 46', 2015","url":Z46,"quote":"it places it right before the room descriptions","page":"closing commentary on the introduction","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"edition and house style","claim":"Howard reports that TSR made only minor changes to Holmes's sample dungeon between manuscript and published rulebook.","source":"Zach Howard (Zenopus Archives), 'Part 46', 2015","url":Z46,"quote":"only minor changes by TSR in the published version","page":"section 'SAMPLE DUNGEON'","kind":"analysis","polarity":"asserts","date":"2015-02-06","routeHint":"direct fetch","registerHint":"none","confidence":"high"},

 # --- Delta, Early Evolution of Encounter Text ---
 {"feature":"boxed text form","claim":"Delta dates the first boxed text in a Gygax adventure to the 1982 published Lost Caverns of Tsojcanth.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', Delta's D&D Hotspot, 2021","url":DE,"quote":"And hey, there's boxed text for the first time!","page":"section '1982 - Lost Caverns of Tsojcanth Publication'","kind":"analysis","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"boxed text form","claim":"In the 1982 Lost Caverns of Tsojcanth the dungeon areas carry boxed text while the wilderness areas do not.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"while the dungeon areas use boxed text, the wilderness does not","page":"section '1982 - Lost Caverns of Tsojcanth Publication'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"Gygax's 1974 Castle Greyhawk notes gave a single curt bullet-line per encounter area.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"only a single curt bullet-line per encounter area","page":"section '1974 - Castle Greyhawk Notes'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"sentence length variation","claim":"Gygax's 1976 Lost Caverns of Tsojconth tournament document moved from bullet points to full English sentences describing each area.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"here we at least get full English sentences describing each area","page":"section '1976 - Lost Caverns of Tsojconth Tournament'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"concrete sensory noun","claim":"In the 1978 Steading of the Hill Giant Chief the area paragraphs tend to lead with sense-descriptions.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"the paragraphs tend to lead with those sense-descriptions","page":"section '1978 - Steading of the Hill Giant Chief'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Expedition to the Barrier Peaks devotes almost 500 words to the Ship Commander's Quarters, an area with no monsters.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"almost 500 words total for the one area","page":"section '1980 - Expedition to the Barrier Peaks'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"boxed text form","claim":"Isle of the Ape opens with a boxed speech by Tenser of some 1,600 words to be read verbatim.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"2 full pages of text to be read verbatim","page":"section '1984 (c.) - Dungeonland & Temple of Elemental Evil'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"herald-pools","confidence":"high"},
 {"feature":"boxed text form","claim":"The Temple of Elemental Evil's introductory boxed text runs about 1,300 words, more than a full page.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"introductory boxed text section that runs more than a full page","page":"section '1984 (c.) - Dungeonland & Temple of Elemental Evil'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"place and institution description","claim":"Delta counts 1,200 words of content text for room 404 of the Temple of Elemental Evil, a 20 by 30 foot room.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"room 404 is ironically a 20'×30' room with 1,200 words","page":"section '1984 (c.) - Dungeonland & Temple of Elemental Evil'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"dm-facing sentence","claim":"The Temple of Elemental Evil tends to open an encounter with non-boxed information for the DM before the boxed description.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"start with some non-boxed info to the DM, and then","page":"section '1984 (c.) - Dungeonland & Temple of Elemental Evil'","kind":"measurement","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"other: stat block versus prose","claim":"Delta locates in the 1982 Tsojcanth the moment monster stat blocks grew too big to sit inside the paragraph text.","source":"Delta (Daniel R. Collins), 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"monster stat blocks grew too big to comfortably fit within the paragraph","page":"section '1982 - Lost Caverns of Tsojcanth Publication'","kind":"analysis","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"boxed text form","claim":"Delta says boxing his own sensory lead-in would imply reading it verbatim, which he calls a bad idea for a volatile situation.","source":"Delta (Daniel R. Collins), comment reply on 'Early Evolution of Encounter Text', 2021","url":DE,"quote":"that seems to imply the need to read it verbatim","page":"comments, reply to Warren D., 2021-10-28","kind":"own-words","polarity":"rejects","date":"2021-10-28","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"boxed text form","claim":"A reader argues boxed text is linear and assumes the characters approach a room from one specific direction.","source":"Warren D., reader comment on Delta's D&D Hotspot, 2021","url":DE,"quote":"because it is linear, it often assumes PCs are approaching the room","page":"comments, 2021-10-25","kind":"reader","polarity":"rejects","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"other: point-form room description","claim":"A reader praises Old-School Essentials room descriptions that bold the important object and put details in parentheses.","source":"Warren D., reader comment on Delta's D&D Hotspot, 2021","url":DE,"quote":"Room descriptions have important object in bold with parenthesis containing details","page":"comments, 2021-10-25","kind":"reader","polarity":"asserts","date":"2021-10-25","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},

 # --- Delta, Tamoachan ---
 {"feature":"boxed text form","claim":"In the 1979 Lost Tamoachan the initial area descriptions are set as quoted and indented passages rather than boxed text.","source":"Delta (Daniel R. Collins), 'Tip-Offs in Tamoachan', Delta's D&D Hotspot, 2017","url":DTAM,"quote":"not exactly in boxed text, but in specially quoted and indented","page":"section 'Other Curiosities', 'Proto-Boxed Text'","kind":"measurement","polarity":"asserts","date":"2017-10-02","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},

 # --- Cordell via Greyhawkery ---
 {"feature":"edition and house style","claim":"Bruce Cordell wrote that the 4e tactical format makes a compelling adventure narrative difficult to generate.","source":"Bruce Cordell, Design & Development column (2011), quoted by Mike Bridges, Greyhawkery","url":GH,"quote":"The tactical format makes it difficult to generate a compelling adventure narrative","page":"quoted block, paragraph 1","kind":"own-words","polarity":"rejects","date":"2011-06-30","routeHint":"direct fetch of the blog quoting the column","registerHint":"none","confidence":"high"},
 {"feature":"omission as information","claim":"Cordell wrote that the tactical format leaves too little space for notes on exploration, lore or character story.","source":"Bruce Cordell, Design & Development column (2011), quoted by Mike Bridges, Greyhawkery","url":GH,"quote":"adventures tend to be fairly Spartan affairs, because too little space","page":"quoted block, final paragraph","kind":"own-words","polarity":"rejects","date":"2011-06-30","routeHint":"direct fetch of the blog quoting the column","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"edition and house style","claim":"Cordell reports reviewing 1st Edition adventures including Tomb of Horrors for models of adventure format.","source":"Bruce Cordell, Design & Development column (2011), quoted by Mike Bridges, Greyhawkery","url":GH,"quote":"1st Edition adventures I looked at included Tomb of Horrors","page":"second quoted block","kind":"own-words","polarity":"asserts","date":"2011-06-30","routeHint":"direct fetch of the blog quoting the column","registerHint":"none","confidence":"high"},

 # --- Slavicsek via The Alexandrian ---
 {"feature":"other: delve format definition","claim":"Bill Slavicsek defines a Dungeon Delve as a compact series of encounters appropriate for a specific level of play.","source":"Bill Slavicsek, introduction to Dungeon Delve (2009), quoted by Justin Alexander, The Alexandrian","url":ALEX,"quote":"a compact series of encounters appropriate for a specific level of play","page":"quoted introduction","kind":"own-words","polarity":"asserts","date":"2009-04-16","routeHint":"direct fetch of the blog quoting the book","registerHint":"none","confidence":"high"},

 # --- Welcome to the Deathtrap ---
 {"feature":"place and institution description","claim":"In 4th Edition adventures, locations with no encounter are compressed into single paragraphs with minimal description.","source":"Welcome to the Deathtrap (OSR blog), 'Designing Layout and Information in Adventures', 2021","url":DT,"quote":"compressed into single paragraphs with minimal effort spent on description","page":"section 'The Evolution of Dungeons & Dragons' Information Design'","kind":"analysis","polarity":"asserts","date":"2021-08-29","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"boxed text form","claim":"The blogger describes 5th Edition's Candlekeep Mysteries as a wall of text with a boxed description.","source":"Welcome to the Deathtrap (OSR blog), 2021","url":DT,"quote":"it is a wall of text with a boxed description","page":"section 'The Evolution of Dungeons & Dragons' Information Design'","kind":"analysis","polarity":"asserts","date":"2021-08-29","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"other: typographic signposting","claim":"5th Edition still signposts traps and treasure with bold italics at the start of the appropriate paragraph.","source":"Welcome to the Deathtrap (OSR blog), 2021","url":DT,"quote":"They still signpost traps and treasure with bold italics","page":"section 'The Evolution of Dungeons & Dragons' Information Design'","kind":"analysis","polarity":"asserts","date":"2021-08-29","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"other: typographic signposting","claim":"3rd Edition signposted monsters, treasure, traps and tactics using indentation and icons in a specific order.","source":"Welcome to the Deathtrap (OSR blog), 2021","url":DT,"quote":"clearly signposted monsters, treasure, traps, and tactics using indentation and icons","page":"section 'The Evolution of Dungeons & Dragons' Information Design'","kind":"analysis","polarity":"asserts","date":"2021-08-29","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"boxed text form","claim":"The Dark of Hot Springs Island replaces long box text with a handful of adjectives for the GM to improvise from.","source":"Welcome to the Deathtrap (OSR blog), 2021","url":DT,"quote":"rather than give a long box text, Hot Springs Island provides","page":"section 'Point Form Description'","kind":"analysis","polarity":"asserts","date":"2021-08-29","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},

 # --- Appelcline ---
 {"feature":"place and institution description","claim":"Appelcline calls the Village of Hommlet Greyhawk's first described locale that was not just a dungeon or adventuring point.","source":"Shannon Appelcline, 'Designers & Dragons: The Column #24', RPGnet, 2013","url":DD24,"quote":"first described locale that wasn't just some dungeon or adventuring point","page":"section 'The Temple Adventures (1979, 1985)'","kind":"analysis","polarity":"asserts","date":"2013-01-23","routeHint":"Wayback raw capture 20240224035027id_","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"edition and house style","claim":"Appelcline says the TSR UK Saltmarsh adventures differ markedly from the staid dungeon crawls US authors were then writing.","source":"Shannon Appelcline, 'Designers & Dragons: The Column #24', RPGnet, 2013","url":DD24,"quote":"how much they differ from the staid dungeon crawls then being","page":"section 'The (U)k Adventures (1981-1983)'","kind":"analysis","polarity":"asserts","date":"2013-01-23","routeHint":"Wayback raw capture 20240224035027id_","registerHint":"none","confidence":"high"},

 # --- Merwin ---
 {"feature":"opening sentence","claim":"Merwin reports being taught that a short story must hook the reader in the first half-page or go unfinished.","source":"Shawn Merwin, 'Let's Design an Adventure: Adventure Hooks and Opening Scenes', D&D Beyond, 2019","url":M624,"quote":"unless you hook the reader in the first half-page","page":"section 'You May Ask Yourself, How Did I Get Here?'","kind":"own-words","polarity":"asserts","date":"2019-10-23","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"opening sentence","claim":"Merwin says fiction's razor-edge audience-grabbing may not be necessary in adventure writing.","source":"Shawn Merwin, 'Let's Design an Adventure: Adventure Hooks and Opening Scenes', D&D Beyond, 2019","url":M624,"quote":"might not be necessary in adventure writing","page":"section 'You May Ask Yourself, How Did I Get Here?'","kind":"own-words","polarity":"disputes","date":"2019-10-23","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"opening sentence","claim":"Merwin defines the opening scene as the answer to 'where am I' and the hook as the answer to 'why am I here'.","source":"Shawn Merwin, 'Let's Design an Adventure: Adventure Hooks and Opening Scenes', D&D Beyond, 2019","url":M624,"quote":"The “where” is the opening scene, and the “why” is the adventure hook","page":"section 'You May Ask Yourself, How Did I Get Here?'","kind":"own-words","polarity":"asserts","date":"2019-10-23","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"edition and house style","claim":"Merwin judges the way The Village of Hommlet hands over its hook and opening not very exciting or particularly nutritious.","source":"Shawn Merwin, 'Let's Design an Adventure: Adventure Hooks and Opening Scenes', D&D Beyond, 2019","url":M624,"quote":"It’s not very exciting or particularly nutritious","page":"section 'You May Ask Yourself, How Did I Get Here?'","kind":"own-words","polarity":"rejects","date":"2019-10-23","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"boxed text form","claim":"Merwin says an encounter's opening information is probably delivered in the form of boxed text.","source":"Shawn Merwin, 'Let's Design an Adventure: Encounter Basics', D&D Beyond, 2019","url":M626,"quote":"probably in the form of boxed text or some other vehicle","page":"section 'Learned Information'","kind":"own-words","polarity":"asserts","date":"2019-12-04","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Merwin locates drama in the dissonance between what characters know entering an encounter and what they learn inside it.","source":"Shawn Merwin, 'Let's Design an Adventure: Encounter Basics', D&D Beyond, 2019","url":M626,"quote":"There is drama and tension in the dissonance between the information","page":"section 'Known Information'","kind":"own-words","polarity":"asserts","date":"2019-12-04","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
]


POLY='https://www.polygon.com/2021/10/12/22722602/dungeons-dragons-game-wizards-book-excerpt-jon-peterson-arneson-lawsuit'
PWARN='https://playingattheworld.blogspot.com/2020/04/dave-arnesons-origins-1977-tournament.html'
LYAHF='https://writeups.letsyouandhimfight.com/rulebook-heavily/dungeonsanddragons-gazetteer/'
RPGGAZ='https://therpggazette.wordpress.com/2025/11/11/the-shadowed-old-gods-of-game-design-remembering-holmes-moldvay-and-mentzer/'
MF='https://eprints.whiterose.ac.uk/id/eprint/147044/1/Deterding_Zagal_Many_Faces_RPG_Studies.pdf'

sources += [
 {"title":"From the Unknown to the Borderlands (excerpt from Jon Peterson, Game Wizards, MIT Press 2021)","url":POLY,"kind":"own-words","substantive":True,"date":"2021-10-12","route":"direct fetch"},
 {"title":"Dave Arneson's Origins 1977 Tournament","url":PWARN,"kind":"analysis","substantive":True,"date":"2020-04","route":"direct fetch"},
 {"title":"Dungeons & Dragons Gazetteer (long-form writeup of GAZ1 The Grand Duchy of Karameikos)","url":LYAHF,"kind":"reader","substantive":True,"date":"undated writeup; GAZ1 published 1987","route":"direct fetch"},
 {"title":"The Shadowed Old Gods of Game Design: Remembering Holmes, Moldvay and Mentzer","url":RPGGAZ,"kind":"analysis","substantive":True,"date":"2025-11-11","route":"direct fetch"},
 {"title":"The Many Faces of Role-Playing Game Studies (Deterding & Zagal, chapter 1 of Role-Playing Game Studies, Routledge 2018)","url":MF,"kind":"analysis","substantive":True,"date":"2018-04-04","route":"White Rose eprints accepted-manuscript PDF, text extracted with pypdf"},
 {"title":"Fifty Years of Dungeons & Dragons chapter pages (Peterson ch.3; Rowe & Howard ch.5; Cote & Saidel ch.15; Trammell & Garcia ch.17)","url":"https://direct.mit.edu/books/book/5778/chapter/4746687/Doctor-Holmes-I-Presume-How-a-California-Neurology","kind":"analysis","substantive":False,"date":"2023","route":"BLOCKED: direct.mit.edu returns 403 to curl and WebFetch; no Wayback capture; OpenAlex and Semantic Scholar hold no abstract"},
 {"title":"Shared Fantasy (Fine 1983) and The Fantasy Role-Playing Game (Mackay 2001) full-text search","url":"https://archive.org/metadata/sharedfantasyrol0000fine","kind":"analysis","substantive":False,"date":"1983/2001","route":"BLOCKED: archive.org search-inside endpoints unreachable from this host (HTTP 000)"},
]

claims += [
 {"feature":"dm-facing sentence","claim":"Peterson says In Search of the Unknown carried starting guidance on running an adventure absent from the then-current D&D books.","source":"Jon Peterson, Game Wizards (MIT Press 2021), excerpt published by Polygon","url":POLY,"quote":"useful starting guidance on running an adventure that you wouldn\u2019t find","page":"paragraph 1 of the excerpt","kind":"own-words","polarity":"asserts","date":"2021-10-12","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"edition and house style","claim":"Peterson says much of Carr's text on the art of dungeon mastering was effectively paraphrased in Gygax's Keep on the Borderlands.","source":"Jon Peterson, Game Wizards (MIT Press 2021), excerpt published by Polygon","url":POLY,"quote":"enlightening text about the art of dungeon mastering was effectively paraphrased","page":"paragraph beginning 'It was then that Gygax apparently grasped'","kind":"own-words","polarity":"asserts","date":"2021-10-12","routeHint":"direct fetch","registerHint":"dm-page","confidence":"high"},
 {"feature":"edition and house style","claim":"Peterson dates the start of modules as a business for TSR to the summer of 1978.","source":"Jon Peterson, Game Wizards (MIT Press 2021), excerpt published by Polygon","url":POLY,"quote":"Modules only started to become a business for TSR in the summer","page":"paragraph 1 of the excerpt","kind":"own-words","polarity":"asserts","date":"2021-10-12","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"other: circulation of the register","claim":"Peterson reports Keep on the Borderlands selling 750,000 copies a year at the height of the 1981 boom.","source":"Jon Peterson, Game Wizards (MIT Press 2021), excerpt published by Polygon","url":POLY,"quote":"selling 750,000 copies a year","page":"final paragraph","kind":"own-words","polarity":"asserts","date":"2021-10-12","routeHint":"direct fetch","registerHint":"none","confidence":"high"},
 {"feature":"terminology consistency","claim":"Peterson notes Arneson still wrote armour class values in Roman numerals in his 1977 tournament documents.","source":"Jon Peterson, 'Dave Arneson's Origins 1977 Tournament', Playing at the World, 2020","url":PWARN,"quote":"Arneson still wrote armor class values with Roman numerals","page":"final paragraph","kind":"analysis","polarity":"asserts","date":"2020-04","routeHint":"direct fetch","registerHint":"none","confidence":"high"},

 {"feature":"diction (native vs latinate)","claim":"A long-form reader writeup describes the D&D Gazetteer line's language as casual and informal.","source":"Rulebook Heavily, 'Dungeons & Dragons Gazetteer' writeup, RPG Writeups","url":LYAHF,"quote":"The language is casual and informal","page":"Introduction, 'The Base Rules'","kind":"reader","polarity":"asserts","date":"undated; describes GAZ1 (1987)","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: a forum-style writeup, not peer-reviewed criticism"},
 {"feature":"plainness and economy","claim":"The same writeup says the Gazetteers make their points quickly and efficiently.","source":"Rulebook Heavily, 'Dungeons & Dragons Gazetteer' writeup, RPG Writeups","url":LYAHF,"quote":"points are made quickly and efficiently","page":"Introduction, 'The Base Rules'","kind":"reader","polarity":"asserts","date":"undated; describes GAZ1 (1987)","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: a forum-style writeup"},
 {"feature":"plainness and economy","claim":"GAZ1 The Grand Duchy of Karameikos runs to 64 pages plus maps.","source":"Rulebook Heavily, 'Dungeons & Dragons Gazetteer' writeup, RPG Writeups","url":LYAHF,"quote":"The first one clocks in at a mere 64 pages plus maps","page":"Introduction, 'The Base Rules'","kind":"measurement","polarity":"asserts","date":"undated; describes GAZ1 (1987)","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"register modulation","claim":"The writeup says GAZ1's chapter of place descriptions is meant mostly for players rather than the DM.","source":"Rulebook Heavily, 'Dungeons & Dragons Gazetteer' writeup, RPG Writeups","url":LYAHF,"quote":"The descriptions in this chapter are mostly meant for players","page":"Gaz 1 Part 4: The Lay of the Land","kind":"reader","polarity":"asserts","date":"undated; describes GAZ1 (1987)","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: a forum-style writeup"},
 {"feature":"civic record register","claim":"GAZ1 gives Specularum an official census of 50.000 taken fifteen years before the setting's present.","source":"Rulebook Heavily, 'Dungeons & Dragons Gazetteer' writeup, RPG Writeups","url":LYAHF,"quote":"the official census of 50.000 was taken 15 years ago","page":"Gaz 1 Part 4, the cities of Karameikos","kind":"reader","polarity":"asserts","date":"undated; describes GAZ1 (1987)","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: reported at second hand from the supplement"},
 {"feature":"place and institution description","claim":"In GAZ1 some notable places of Karameikos merit only a paragraph of description.","source":"Rulebook Heavily, 'Dungeons & Dragons Gazetteer' writeup, RPG Writeups","url":LYAHF,"quote":"Some merit only a paragraph","page":"Gaz 1 Part 4, the cities of Karameikos","kind":"reader","polarity":"asserts","date":"undated; describes GAZ1 (1987)","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: a forum-style writeup"},

 {"feature":"plainness and economy","claim":"An essayist characterises J. Eric Holmes's Basic Set prose as dispassionate, methodical and encouraging.","source":"Serban Ionita, 'The Shadowed Old Gods of Game Design', The RPG Gazette, 2025","url":RPGGAZ,"quote":"His prose is dispassionate, methodical, and encouraging","page":"section 'The Translotar: J. Eric Holmes'","kind":"analysis","polarity":"asserts","date":"2025-11-11","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: an evaluative hobbyist essay with no textual measurement"},
 {"feature":"edition and house style","claim":"The same essay calls the original 1974 boxed set's text dense and peculiar.","source":"Serban Ionita, 'The Shadowed Old Gods of Game Design', The RPG Gazette, 2025","url":RPGGAZ,"quote":"The text in the set was dense and peculiar","page":"section 'The Translotar: J. Eric Holmes'","kind":"analysis","polarity":"asserts","date":"2025-11-11","routeHint":"direct fetch","registerHint":"none","confidence":"medium: an evaluative hobbyist essay"},
 {"feature":"plainness and economy","claim":"The same essay calls Tom Moldvay's 1981 Basic text both efficient and lyrical.","source":"Serban Ionita, 'The Shadowed Old Gods of Game Design', The RPG Gazette, 2025","url":RPGGAZ,"quote":"Moldvay\u2019s text seems both efficient and lyrical","page":"section 'The poet: Tom Moldvay'","kind":"analysis","polarity":"asserts","date":"2025-11-11","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: an evaluative hobbyist essay"},
 {"feature":"diction (native vs latinate)","claim":"The same essay characterises Gygax's prose as resembling a baroque sermon.","source":"Serban Ionita, 'The Shadowed Old Gods of Game Design', The RPG Gazette, 2025","url":RPGGAZ,"quote":"whose prose resembled a baroque sermon","page":"section 'The Teacher: Frank Mentzer'","kind":"analysis","polarity":"asserts","date":"2025-11-11","routeHint":"direct fetch","registerHint":"none","confidence":"medium: an evaluative hobbyist essay"},
 {"feature":"omission as information","claim":"The essay says Moldvay's adventures implied a cosmology, a history and a mood through their placement of statues, monsters and ruins.","source":"Serban Ionita, 'The Shadowed Old Gods of Game Design', The RPG Gazette, 2025","url":RPGGAZ,"quote":"Each adventure implied a cosmology, a history, and a mood","page":"section 'The poet: Tom Moldvay'","kind":"analysis","polarity":"asserts","date":"2025-11-11","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: an evaluative hobbyist essay"},
 {"feature":"place and institution description","claim":"The essay says Moldvay's adventures communicated worldviews rather than merely offering maps.","source":"Serban Ionita, 'The Shadowed Old Gods of Game Design', The RPG Gazette, 2025","url":RPGGAZ,"quote":"These adventures communicated worldviews, rather than merely offering maps","page":"section 'The poet: Tom Moldvay'","kind":"analysis","polarity":"asserts","date":"2025-11-11","routeHint":"direct fetch","registerHint":"dossier-archivist","confidence":"medium: an evaluative hobbyist essay"},

 {"feature":"stylometry","claim":"Deterding and Zagal place the study of textuality, authorship and narrative in RPGs with literary and media scholars in the 2000s.","source":"Sebastian Deterding and Jose P. Zagal, 'The Many Faces of Role-Playing Game Studies', in Role-Playing Game Studies (Routledge 2018)","url":MF,"quote":"textuality, authorship, and narrative in RPGs","page":"section on the history of RPG studies","kind":"analysis","polarity":"asserts","date":"2018-04-04","routeHint":"White Rose accepted-manuscript PDF, pypdf text extraction","registerHint":"none","confidence":"high"},
 {"feature":"other: scholarly field map","claim":"Deterding and Zagal credit Peterson and Appelcline, independent authors, with the substantial historiographies of tabletop role-playing games.","source":"Sebastian Deterding and Jose P. Zagal, 'The Many Faces of Role-Playing Game Studies', in Role-Playing Game Studies (Routledge 2018)","url":MF,"quote":"have produced substantial historiographies of the emergence and evolution","page":"section on the history of RPG studies","kind":"analysis","polarity":"asserts","date":"2018-04-04","routeHint":"White Rose accepted-manuscript PDF, pypdf text extraction","registerHint":"none","confidence":"high"},
]

def write(complete=False,coverage="in progress"):
    json.dump({"complete":complete,"coverage":coverage,"sourcesRead":sources,"claims":claims},open(OUT,'w'),indent=1,ensure_ascii=False)
    print('wrote',OUT,len(claims),'claims',len(sources),'sources')
if __name__=='__main__':
    write()
