import json
base='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/'
src=json.load(open(base+'prose-research/sweep/chunks/dnd-04.json'))
claims=src['claims']
V=[
 (214,"VERIFIED_VERBATIM","Beginners want all stats/contingencies; long-time players want bullet lists.","Raw EN World AMA thread (Jun 3 2015) fetched live with browser UA. Baur's answer: 'Beginners tend to want as much support as possible, all the stats, contingencies for everything, answers in the text for corner cases, map support, tokens, guidelines. Long-time players tend to want bullet lists, bare bones text that allows them to improvise in response to the players at the table, a bit more wiggle room, less wall of text.' Quote verbatim; every limb supported ('veterans' = his 'long-time players').",None),
 (215,"VERIFIED_VERBATIM","Write write write. Turn out a lot of prose.","Raw EN World AMA. Answer to 'If you had three tips for unpublished fantasy and/or RPG authors': 'Three tips for unpublished authors and game designers? ... 1) Write write write (and don't quit your day job too early). Turn out a lot of prose. Speed keeps you fed; quality keeps you respected. Find a balance. Do the work.' Quote verbatim; advice is explicitly addressed to authors AND game designers. Context worth carrying: the volume advice is immediately balanced by 'Find a balance.'",None),
 (216,"VERIFIED_VERBATIM","Much time lavished on history and background is wasted energy.","Wayback raw capture 20130531110015id_ of the dead wizards.com column. Page: 'much of the time lavished on history and background is wasted energy ... Make sure your backstory is recent and relevant; avoid anything that starts \"Thousands of years ago...\"' Quote verbatim, both advice limbs verbatim. On the 'ex-Dungeon editor' descriptor the page says only 'When I worked on Dungeon magazine I saw them constantly' - the editorial role is entailed (he saw beginners' submission errors constantly) but the title itself is never printed here or in the AMA (index 214/215 source), which says only 'your time with Dungeon/Dragon magazine'.",None),
 (217,"VERIFIED_VERBATIM","Four common errors, seen constantly at Dungeon magazine.","Wayback raw capture. Page: 'There are four fairly common errors in beginning adventure design. When I worked on Dungeon magazine I saw them constantly, and the errors haven't changed. 1) too much useless backstory 2) slow starts 3) random encounters 4) too many encounters'. Quote verbatim; the enumerated four match the claim exactly and in order.",None),
 (218,"VERIFIED_VERBATIM","Skip involved history the PCs cannot learn; save it for sourcebooks.","Wayback raw capture. Page: 'Unless it connects directly to action in the current timeframe (and the PCs have a way of learning it), skip the involved history. Save that for sourcebooks.' Quote verbatim; the PC-cannot-learn condition and the sourcebook destination are both explicit, and 'not adventures' is the column's subject.",None),
 (219,"VERIFIED_VERBATIM","Hooks should be specific and very hard to turn down.","Wayback raw capture 20130531075546id_. Section 'Make It Concrete and Tough to Refuse': 'You want your hooks to be specific, and you want them to be very hard to turn down. Vague, overused, or clichéd hooks don't interest players because they have heard them before.' The overused list includes 'Meeting a stranger in a tavern' and 'Requests from the mayor or head villager'. Quote verbatim; every limb, including both cited examples, is on the page.",None),
 (220,"VERIFIED_VERBATIM","Arrow with Elvish note beats the guy in a bar.","Wayback raw capture. Page opens by comparing '\"You meet a guy in a bar and he tells you about a dungeon outside town.\"' (called 'old news') with '\"During the midnight watch, someone shoots an arrow into your camp. There's a note attached, written in Elvish.\"', then: 'The adventure hook is what kicks off the action ... In fiction, it would be called the \"inciting incident.\"' Quote verbatim; both limbs supported.",None),
 (221,"VERIFIED_VERBATIM","Intentionally modern-sounding labels so roles stay out of game text.","Wayback raw capture 20140106064951id_. Page: 'And I intentionally used modern-sounding labels on some of the roles because I didn't want the roles to creep into game text. Only the designers and I would ever know what the monster's role is.' The role list on the page includes Mook, Decathlete and Artillery, as the claim's parenthetical names. Quote verbatim (page uses a curly apostrophe in 'didn't').",None),
 (222,"VERIFIED_VERBATIM","Accepting that restriction limits how much you write and art size.","Wayback raw capture. Page: 'Laying out a monster manual is trickier than most other books, once you accept the restriction that monsters don't break out of page spreads. If you want a monster manual where you don't have to flip pages during your time at the table, then you have to accept some significant limitations on how much you can write and how big your illustrations can be.' Quote verbatim; both consequences (text length, illustration size) explicit. Framing nuance: the page presents it as a restriction one accepts to get a no-flip book, not as a house rule imposed from outside.",None),
 (223,"VERIFIED_VERBATIM","VERY fond of boxed text back in the day.","Live blogspot page fetched raw. Reviewing his 1992 TSR Dark Sun super-adventure Dragon's Crown among his 28 published adventures: 'I also seem to have been VERY fond of boxed text back in the day, although that was kind of a 2e style thing.' Quote verbatim; the self-review framing and the TSR-era adventure are both on the page.",None),
 (224,"PARTIAL","MU was the scheduling unit used at TSR, not WotC.","Live blogspot page. Page: 'A \"MU\" was the scheduling unit used at TSR for RPG work. It stood for \"module unit\" and represented 32 pages of writing/design, or 20,000 to 22,000 words. When I first started at TSR, the standard was that a designer like me would be scheduled for 1 month per MU.' Quote verbatim and the 32 pages / 20,000-22,000 words / one designer-month limbs are all exact - but the page attributes the unit to TSR (Baker joined TSR in Oct 1991; this is the 1992 Dark Sun project), five years before WotC acquired TSR. The claim's 'WotC' is the page's 'TSR'.","'WotC scheduled' - the page says the MU was TSR's scheduling unit"),
 (225,"VERIFIED_VERBATIM","Chicago Manual of Style is your main bible for WotC work.","Live Critical Hits page fetched raw. 'Lessons Learned 2: Yes the Chicago Manual of Style is a HUGE and expensive document. If you want to write for WotC, that's going to be your main bible.' Templates limb: 'While you are given templates to follow and a series of well-written guidelines...', 'Lessons Learned 3: If you're serious about being a freelancer, get MS-Word', and Lesson 4 on 'the WotC templates'. Editing limb verbatim: 'deliver top grade, engaging manuscripts that will require no or minimal editing in terms of grammar, syntax and spelling.' Date limb: post is 19 Dec 2012 describing assignments from early 2011 to early 2012.",None),
 (226,"PARTIAL","D&D House Style Guide - WotC docs given to freelancers.","Live slyflourish.com page fetched raw. The bullet 'Focus on the here and now. Omit verbose backstories.' appears verbatim, but under the heading 'D&D House Style Guide', described as 'This free set of documents from Wizards of the Coast includes the house styles the D&D team gives to freelancers. It includes a short paper on adventure writing.' The WotC origin, the freelancer audience and the adventure-writing paper are all supported; the document name 'Adventure Guide' never appears anywhere on the page.","the source document's name - the page calls it the D&D House Style Guide, never 'Adventure Guide'"),
 (227,"VERIFIED_VERBATIM","Small beats large. Keep it brief. Be specific. Read aloud.","Live slyflourish.com page. Under 'Kobold's Guide to Game Design: Adventures' the bullets include 'Small beats large. Keep it brief.', 'Read your work aloud.' and 'Be specific.' Quote verbatim; all three precepts named in the claim are on the page and correctly attributed to the Kobold guide.",None),
 (228,"VERIFIED_VERBATIM","Daunting task of fitting in, not contradicting existing lore.","Live koboldpress.com page fetched raw (Jeremy L.C. Jones interview, 26 May 2009). Greenwood's answer: 'Yet the shared world writer faces many constraints. Character descriptions, backstories, aims, and mannerisms are usually well-established, and the writer faces the daunting task of \"fitting in\" (perhaps even to a particular prose style) and not contradicting what may be a sizable body of existing lore.' Quote verbatim, speaker attribution explicit ('Greenwood:'), every limb supported.",None),
]
verdicts=[]
for idx,v,tw,note,limb in V:
    d={"index":idx,"verdict":v,"trueWording":tw,"note":note}
    if limb: d["unsupportedLimb"]=limb
    verdicts.append(d)
assert [d["index"] for d in verdicts]==[c["index"] for c in claims], "index mismatch"
out={"name":"dnd","chunk":4,"claims":claims,"verdicts":verdicts}
p=base+'prose-research/sweep/verdicts-dnd-i214-228.json'
json.dump(out,open(p,'w',encoding='utf-8'),indent=1,ensure_ascii=False)
print("wrote",p)
chk=json.load(open(p,encoding='utf-8'))
print("claims",len(chk["claims"]),"verdicts",len(chk["verdicts"]))
from collections import Counter
print(Counter(d["verdict"] for d in chk["verdicts"]))
