import { readFileSync } from 'node:fs';
import { measure } from './metrics.mjs';
const R = JSON.parse(readFileSync('report.json', 'utf8'));
const C = JSON.parse(readFileSync('corpus.json', 'utf8'));
const ds = C.filter((r) => r.register === 'R1' || r.register === 'R2');
const m = measure(ds);
console.log('=== CROSS-CHECK vs the refuter / dossier §3 (n=2,734 dossier variants) ===');
console.log('my n:', m.variants, ' (X1 raw 2734, admission dropped', 2734 - m.variants, ')');
console.log('1-seg:', Math.round(m.oneSegment * m.variants), '(refuter 2030)  2-seg:', Math.round(m.twoSegments * m.variants), '(691)  3+:', Math.round(m.threePlusSegments * m.variants), '(11)');
console.log('rather than:', m.pet['rather than'], '(dossier 288, 10.5%) rate', m.shapesRate.ratherThan);
console.log('abstract closers:', Math.round(m.shapesRate.abstractCloser * m.segments), '(dossier 128, 4.4%) rate', m.shapesRate.abstractCloser);
console.log('its own:', m.pet['its own'], '(70)  whatever:', m.pet.whatever, '(49)  enough to:', m.pet['enough to / enough that'], '(97)  kind/sort of:', m.pet['kind of / sort of'], '(29)  quiet:', m.pet['quiet / quietly'], '(37)');
console.log('nobody/no one/nothing:', m.pet['nobody / no one / nothing'], '(333)  still:', m.pet.still, '(149)  yet:', m.pet.yet, '(61)  already:', m.pet.already, '(26)');
console.log('gloss tail ", which":', Math.round(m.shapesRate.glossTail * m.variants), '(dossier 123-149)');
console.log('2nd-sentence That/This/It:', Math.round(m.shapesRate.secondSentSummary * m.variants), '(dossier 80)');
console.log('pools uniform in seg count:', m.pools.sameSegmentCountShare, 'of', m.pools.poolsWith2Plus, 'pools (dossier 407/708 = 0.575)');
console.log('pools repeated 2-word opener:', m.pools.repeatedTwoWordOpenerShare, '(dossier 79/708 = 0.112)');
const r1 = R.metrics.R1, r2 = R.metrics.R2;
console.log('\nR1 wps:', JSON.stringify(r1.wps), '(dossier state: mean 16.7 sd 7.2 p10 7 p90 26 under8 0.13)');
console.log('R1 semicolon count:', Math.round(r1.shapesRate.semicolon * r1.variants), '(386)   R2 semicolon:', Math.round(r2.shapesRate.semicolon * r2.variants), '(169)');
console.log('R2 share segments >30w:', r2.wps.over30, '(dossier causal: 0.49)');
console.log('R1 tells:', JSON.stringify(r1.tells), ' R2 tells:', JSON.stringify(r2.tells));
console.log('R1 digits:', r1.bibleHardRules.digitsInProse, 'R2 digits:', r2.bibleHardRules.digitsInProse, 'R1 question rate:', r1.shapesRate.question, 'R1 emDash:', r1.bibleHardRules.emDash);
