# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 115 — THE DEPLOY PRE-FLIGHT'S VERDICT: GO WITH CONDITIONS, AND THE CHAIN'S ORDER CHANGES (migrations and the applied-head bump come BEFORE the deploying commit); FIX-C2d and FIX-P10 paused at the gate; FIX-W1 and QUEUE-RECON dispatched (2026-09-20 " + stamp + " EDT; the chair, session `4a1823e2`; every call vetoable; NOTHING GATED HAS BEEN CROSSED).** "
 "**DEPLOY-PREFLIGHT DONE (read-only Opus recon; kit `findings/DEPLOY-PREFLIGHT/`; merge-base `b9c494afe` exactly; 521 commits, 1,090 files; `package.json`, the lockfile, `vercel.json` and `.nvmrc` UNCHANGED).** THE FOUR FACTS THAT RE-ORDER THE CHAIN, each CONFIRMED by command: (1) **PRODUCTION HAS NOT DEPLOYED SINCE 2026-09-16's MERGE** — master's CI run on `b9c494afe` had every gate green except `Coverage floors`, CANCELLED at its 45-minute cap, which SKIPPED both deploy jobs; this branch's one CI change raises that cap to 60 — the merge is itself the cure for the stuck deploy; (2) **THE VERCEL GATE IS FAIL-CLOSED ON MIGRATION DRIFT** — `scripts/vercel-ignore-build.mjs` skips the build while `repoHead (203) > appliedHead (200)`, so merge-then-migrate yields a green PR and NO deploy; all three migrations are `create or replace function` only (201 staff hold the Surveyor entitlement — the one genuine loosening, owner-ordered §934.28; 202 and 203 only widen the gallery scanner's refusals), re-runnable, non-destructive, and SAFE TO APPLY BEFORE the new client (202 says so itself: the server may refuse a key before a client token for it exists, never after); (3) **`origin`'s ledger branch is 215 commits stale** and two deploy-gating CI jobs fetch it by name — push the ledger FIRST; its own CI run will go red on fossil `src/` and means nothing; ⛔ PR #48 (ledger → master) must NEVER be merged — close it before the ledger push; #51/#52 are contained and close after the merge; (4) **THE REPOSITORY IS NOW PRIVATE** (it was public on deploy day): branch protection and rulesets return 403 on the free tier, so master's protection is very probably NOT ENFORCED, Actions minutes are billed, and the Vercel ignore-build gate is the only armed gate. "
 "**THE FIVE CI JOBS THE LOCAL CHECK DOES NOT COVER:** `npm audit --audit-level=high --omit=dev` (blocking, queries the live advisory DB; deps are byte-unchanged so a red would be a new upstream advisory) · `e2e` (HIGH: 8 → 14 specs, ~36 → ~73 chromium tests inside an untouched 15-minute cap; master's last run took 5.2 min) · `performance` (runner-calibrated; not reproducible locally) · `coverage-floors` (the `src/lib/saves.js` floor has ~5 pt of buffer and two covering test files lost a net 9 cases with the world-locks removal — PLAUSIBLE risk, unmeasured) · `deno-tests` and `determinism-hostile-locale` (LOW; none of their inputs changed; zero banned locale APIs added in the domain trees). Local node is v24.12.0 while CI pins 22. "
 "**JUDGMENT 6 — THE e2e JOB'S CAP IS RAISED 15 → 25 MINUTES BEFORE THE PUSH.** Decided: one line in `.github/workflows/ci.yml`, assigned to CURE-L as its third commit, proven by `tests/build/ciCheckParity.test.js` + `ciGateHardening.test.js` (no test pins that cap; the only pinned cap is `check-tests` at 45). Why: the same failure mode — a cap cutting a passing run — is what has blocked production for four days, one job over. Rejected: waiting for CI to cut it (an hour per iteration, billed). Reversal: one revert. Blast radius: CI wall-clock ceiling only. "
 "**JUDGMENT 7 — THE PRE-PUSH HOOK IS NOT BYPASSED.** The recon recommended `git push --no-verify` after a green full run; REJECTED — a hook bypass is the owner's explicit word in session, never a lane's or the chair's inference; the hook's own `npm run check` runs honestly when `GATE_MUTEX_MAX_POLLS=100000 GATE_MUTEX_POLL_SECONDS=20` are exported for the push, at about twenty-five minutes. The owner may overrule in chat. "
 "**THE CHAIN AS THE CHAIR NOW RECOMMENDS IT (each outward step waits for the owner's word in session):** RUN 24 green → the cheap CI-only pre-runs at the gate (npm audit; the hostile-locale eight; `deno task check:edge` + `test:edge`; a targeted `saves.js` coverage lower bound) → close PR #48 → push the ledger → push the consist (hook honest) → PR with a REFRESHED body (seven stale statements listed in the report; the materially wrong one says 'migration 201 after merge') → watch the branch's CI → ⛔ THE OWNER'S HAND: `supabase login` / `link` / `db push` (201–203) / `migration list` (the CLI is not installed on this box; production credentials are never typed by the chair) → the owner hands over the live head NUMBER → the chair runs `SUPABASE_MIGRATION_HEAD=203 npm run validate:migration-head` and commits `supabase/applied-head.json` = 203 with its verification text on the branch → merge on green → the Vercel build proceeds (or the owner clicks Redeploy on the merge commit if neither deploy secret is set) → ⛔ THE OWNER'S HAND: redeploy the EIGHT edge functions whose shared bundles moved (`generate-narrative`, `custom-content`, `interpret-session`, `surveyor-autonomy`, `construct-realm`, `construct-settlement`, `surveyor-byok`, `ai-analyst`) FROM A CLEAN CHECKOUT OF THE MERGE COMMIT (never the stale main checkout) and `npm run ops:post-deploy` with production credentials. "
 "**WHAT THE OWNER MUST HEAR BEFORE THE MERGE (put in the chair's report):** the purchases lock (`src/lib/launchGate.js`, `VITE_PURCHASES_OPEN`) does NOT exist on master — this merge is what first obeys the 09-16 order; the data-loss cure stops new loss, heals NO save already damaged, and a client ROLLBACK after it re-opens the defect (one committed tick re-erases whoever the cure protected) — rollback is destructive, not neutral; nine signed shift records mean a seed generated on production today will not reproduce byte-identically after the deploy (each shift owner-worded; the aggregate stated here for the first time); world locks are REMOVED (a coup in a save that had locked its incumbent now falls without an approval queue) — existing saves behave differently; anonymous visitors are narrowed (no thorp; no pre-generation options); a new persisted browser key `anonDraft` keeps an anonymous visitor's dossier across a refresh; migration 201 widens the AI entitlement to staff incl. the provider-key write door; Edit Mode is dark because the editor does not exist yet (all sixteen architected modules absent) — two forward hazards slotted for EM-D0 / EM-C4a: `TIER_GATE.premium.editMode` must be CREATED, and the architected state key `editMode` COLLIDES by name with the shipped dossier boolean. "
 "**LANES:** FIX-C2d PAUSED AT THE GATE with FOUR commits on `fix-c2d-doc-citations-2026-09-20` — ⚠ it committed its instrument change before `tests/lint` whole (the 13:08 law); accepted as it stands because its branch is its own and a red in its window is cured by a further commit, never an amend; its agent is at ~484k tokens, so its gate window goes to a FRESH agent from its note. FIX-P10 PAUSED with commit 5 prepared in scratch (the scroll-padding term is zero at 1024 and 1280 by construction; its scope correction `src/components/GenerateWizard.jsx` ACCEPTED); its finding that `CHROME.toolbarHeight` 64 is the DESKTOP figure while the phone bar is 68 (a 4 px under-reserve older than this lane, now PINNED exactly by its new arm) → **FIX-P11 CHARTERED** (a phone toolbar-height token in `src/components/theme.js`; the pin banks the win). FIX-P9's hand-off gains commits 5–6 (its own noticed items 4 and 3: the two reader-facing 'Thorp' sentences in `src/copy/en.js`; `tests/lib/seoCompendium.test.js` reads the real index entry); its item 5 CLOSED (no label table exists for those vocabularies; a header sentence in the generator names the rule) and item 6 CLOSED (`verify:dist` runs the dist-reading arms at every full check). FIX-W1 DISPATCHED at `e45c4738b` (the doubled article 'the The Chandlers' in the Wizard News composers; measure on rendered text; its commit 3 uses the owner's golden door and WAITS for the owner's in-session re-confirmation of the standing signature grant). QUEUE-RECON DISPATCHED (read-only: a composition forecast for the sixteen paused lanes — base drift, the tests that name their files, stale literals — before gate windows are spent on them).")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 114 —"; assert u.count(key) == 1 and "addendum 115 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 115" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the deploy pre-flight; FIX-P11 chartered; FIX-W1 and QUEUE-RECON dispatched (ODQ §934.47 addendum 115)\n\n"
 "- **THE DEPLOY CHAIN'S ORDER IS RE-CUT** by the pre-flight's measurements: the Vercel gate skips while `repoHead (203) > appliedHead (200)`, so migrations 201–203 (the owner's hand; all three safe before the new client) and the `applied-head.json` bump precede the merge that is meant to deploy; the ledger pushes first; PR #48 is closed unmerged; eight edge functions are redeployed by the owner from a clean checkout of the merge commit. The e2e job's CI cap goes 15 → 25 as CURE-L's third commit. The pre-push hook is not bypassed.\n"
 "- **FIX-P11 CHARTERED:** `CHROME.toolbarHeight` (64) is the desktop figure; the phone wizard toolbar is 68 — a phone toolbar-height token in `src/components/theme.js`, FIX-P10's exact pin `[4,4,4,4,0,0]` banking the win.\n"
 "- **EM-D0 / EM-C4a gain two compile lines:** `TIER_GATE.premium.editMode` does not exist and must be CREATED; the architected store key `editMode` collides by name with the shipped dossier boolean (`settlementSlice.js`) — the packet renames or the live Cartographer button becomes the editor's door.\n"
 "- FIX-C2d and FIX-P10 PAUSED AT THE GATE; FIX-P9's window gains commits 5–6; FIX-W1 dispatched (its door commit waits for the owner's in-session signature); QUEUE-RECON dispatched (read-only).\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 115:", io.open(ODQ, encoding="utf-8").read().count("addendum 115 —"), "| charter amended | no NUL")
