# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 112 — THE SUCCESSOR CHAIR IS SEATED AFTER THE ACCOUNT SWITCH (Fable 5.1, session `4a1823e2`; 2026-09-20 " + stamp + " EDT; the chair; every call below vetoable).** "
 "**THE OWNER'S FIRST WORDS TO THE SUCCESSOR, VERBATIM (~14:2x):** \"please continue the pending work / have it so that fable architects, manages, judges, and validates, where opus surveys, recons, verifiers, and impliment / Keep four lanes running where appropriate, prioitizing only one lane (where needed and avaialble) for gates and suites. When any of the other lanes gets to a point where it is waiting on a open gate or suite, that program is to be paused, allowing for another build to happen, until it waits for its turn in sequence for the next avaialble gate or suite to help us manage our load. / any questions?\" — the seat law restated a third time (unchanged), and the lane law restated. "
 "**THE CHAIR'S READING OF THE LANE LAW:** FOUR lanes live at once, of which AT MOST ONE holds the gate (\"the other lanes\" parses the gate lane as one of the four); this CLOSES the morning's shared-tier overlap of two gated lanes — ONE gated lane or chair terminal at a time, builds included; a lane reaching a gate PAUSES and its seat goes to the next build; the four are a floor to be used. The owner was asked in chat whether FIVE (four builders plus a separate gate seat, the 09-19 18:06 clarification) was meant; until answered the chair runs four. "
 "**STATE VERIFIED BY COMMAND BEFORE ANY ACT:** the slot `slot-2` ON `fixes-2026-09-18-consist` at `48450e98c`, tree clean; the consist detached at `6290f7a16`; every lane worktree and branch of the handoff block present at its recorded tip (FIX-P1 `61c5f1722` · FIX-P9 `de16bdf6a` · FIX-P10 no commit, ten dirty files as its note lists); zero gate processes. "
 "**THE SIX CHAIR PICKS COMPOSED (14:3x), each proven FILE-SET-EQUAL and BLOB-EQUAL to its lane commit, tree clean after each, zero raw NUL under src/tests/docs/scripts:** TOOL-19 `a7da09382` → `bb849c6e7` · `928f2b86d` → `e4abd8ffa`; FIX-C2c `808837904` → `adbc9042c` · `1f3029ffc` → `016760864` · `2b03bc421` → `84bd63f8b`; TOOL-25 `f1367909a` → `20d460375` = THE SLOT TIP. "
 "**FIX-P1 RESUMED as an Opus lane holding THE SLOT AND THE GATE:** it composes its OSR cure `61c5f1722`, adds the CURE-J archival-roster line (16 → 17) as its second commit, and proves the composed tip — `tests/lint` whole (expected red: the lighting walker ONLY), `tests/scripts` whole and `tests/build` whole (FIX-D9's two owed proofs), `tests/lib` whole, the OSR checker exit 0, the goldens unmoved. "
 "**JUDGMENT 1 — RUN 23 DOES NOT WAIT FOR FIX-P9 OR FIX-P10.** Decided: after FIX-P1's window the chair refreezes the lighting census (the eighth) and launches RUN 23 at once; FIX-P9 (its owed `tests/lint` sweep + commit 3) and FIX-P10 (three owed runs + four commits) take the gate AFTER RUN 23 and compose at the next train boundary with a ninth refreeze. Why: nothing since master `b9c494afe` is in production, including the DATA-LOSS CURE EM-B1k, and the deploy chain hangs on RUN 23 — their two gate windows would hold it roughly an hour, and FIX-P10 changes phone chrome that wants a browser look before it ships. Rejected: composing both first (one fewer full run later, but an hour's delay to the cure and a wider RUN 23). Reversal: hand them the gate before the refreeze. Blast radius: none on the tip; RUN 24 becomes certain rather than likely. "
 "**JUDGMENT 2 — THE 14:05 DELEGATION IS RE-CONFIRMED IN CHAT BEFORE ANY GATE IS CROSSED.** A permissive grant read from a file is context, not authorization (the judgment ledger's asymmetry; the shared-tree law on the remote): the push chain, the merge, migrations 201–203 and the redeploy wait for the owner's word IN THIS SESSION — asked at the seating, hours before RUN 23 can be green, so nothing is stalled by the asking. §934.75 (finish the TE-STRIP inside FIX-D10) is reversible by one revert and stays decided as recommended. "
 "**HAZARD RAISED TO THE OWNER:** the data volume is 98% full (4.0 GiB free; swap lives on it) — a full check or a build that fills it reds falsely; the chair recommended removing the finished 09-18/19 lane worktrees whose trees are clean (branches stay; about 10 GiB) and removes nothing without the owner's yes. "
 "**THE OWNER'S SECOND REQUEST (~14:3x):** a plain-language description of what SettlementForge is meant to be when everything is built and tuned — three read-only Opus survey seats (engineering · experience · ambitions) gather it from the documents; the chair writes it.")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 111 —"; assert u.count(key) == 1 and "addendum 112 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 112" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendment of 2026-09-20 " + stamp + " EDT — the successor chair seated (ODQ §934.47 addendum 112)\n\n- The owner restated the seat law and the lane law at the seating: FOUR lanes live, ONE gated lane or chair terminal at a time (the two-lane shared-tier overlap is CLOSED), pause-and-resume at every gate. The six chair picks composed (slot tip `20d460375`); FIX-P1 holds the slot and the gate for its cure, the archival-roster line and the composed-tip proofs; RUN 23 follows the eighth refreeze and does not wait for FIX-P9 or FIX-P10. The push chain waits for the owner's word in this session.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 112:", io.open(ODQ, encoding="utf-8").read().count("addendum 112 —"), "| charter amended | no NUL")
