# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 114 — RUN 23 RED ON THREE TESTS, TWO CAUSES (exit 1 at 15:13:42, in `test:ratchet`; validators, both typecheck ratchets and lint green; the `&&` chain blinded `build` and `verify:dist`, which the chair then ran bare at the same tip: GREEN); CURE-L ruled and dispatched into the slot; FIX-P9's STOP ruled; EM-B3d's compile accepted with one budget override (2026-09-20 " + stamp + " EDT; the chair, session `4a1823e2`; every call vetoable).** "
 "**CAUSE A (two titles, `tests/data/sampleSettlements.test.js` — REVIEW-P F1's fork-door walker):** FIX-P1d (`ee204c827`) measures the address ceiling by RUNNING `forkSeedFor` inside `src/lib/anonForkSalt.js`, so the walker reads that module as a door passing a bare id and importing no `forkIdentity`. The lane proved `tests/lib`, `tests/components` and `tests/lint` whole and never ran `tests/data`; the chair's composed-tip re-proof named four directories and not that one. RULED: the walker's claim stays true and unweakened for every real door (a planted bare-id call still reds both arms); preferred shape, measured before built — the measuring call passes a DECLARED synthetic identity resolved by `forkIdentity` if and only if that path is pure at module evaluation, and arm 2 learns that the module DEFINING `forkIdentity` owes no import of it; `FORK_SEED_MAX` stays 26 and the OSR checker stays exit 0; never an exemption by filename; if the preferred shape is impure the lane STOPS with the alternative priced. "
 "**CAUSE B (one title, `tests/domain/ruinInstitution.test.js` — EM-B1e's acceptance arm A4):** the arm carries its own literal `921c51cf…` of the prose-manifest golden's sha; CURE-J's SIGNED provenance-only re-record (§934.71) lawfully moved the file to `88983938…` and the freeze register with it, and the literal reddened — latent since the second composition, first seen by a full run now. RULED: a test never carries its own literal copy of a frozen golden's sha — the freeze register is the ONE pin and an arm that must assert those bytes READS the register's row by surface id; census first, with its denominator, over every literal of any current or former hash of the two goldens and the preset witness under `tests/`, `src/` and `scripts/`; the re-pointed arm is proven still to bite against a scratch register. "
 "**CURE-L DISPATCHED 15:1x** = the FIX-P1 agent RESUMED (its context holds cause A), holding THE SLOT AND THE GATE at `e45c4738b`; two commits, `tests/data` · `tests/lib` · `tests/domain` whole, then `tests/lint` whole last (brief `briefs/launch/CURE-L.md`). Then the chair's ninth refreeze if a title moved, and RUN 24. "
 "**THE BLINDED STEPS, MEASURED BY THE CHAIR at `e45c4738b` (log `<SP>/consist-dist-measure-e45c4738b.log`):** `npm run build` exit 0 (`built in 16.80s`); `verify:dist` exit 0 — `STRICT DIST OK — 59 discovered/reported file(s), 543 test(s)`; ⚠ the generation worker is 1,401,208 B against `WORKER_BUNDLE_CEILING_BYTES` 1,401,208 — ZERO SLACK: EM-R0d v4's placement prices its own headroom. "
 "**TWO LANE LAWS ADDED TO LANE-PARALLEL:** find the tests that NAME your file (`git grep -l -F <basename> -- tests`) and run each hit's directory whole — `tests/lint` whole is mandatory and no longer sufficient; a golden's re-record owes a census of every literal copy of the OLD hash. "
 "**FIX-P9's STOP, RULED (JUDGMENT 4):** commits 3 and 4 move a byte-pinned SSR render (`docs/samples/organic-craft/pricing-desk.html` holds 13 daggers; `library-desk.html` one rendered `Thorp`), whose only refresh is `UPDATE_ORGANIC_SAMPLES=1` — an `UPDATE_*` door the lane law forbids without qualification. Decided: THE DOOR IS LAWFUL HERE under six conditions (red-first without the door naming exactly the expected sample; the door run for that one file through the mutex; the artefact's diff proven to be EXACTLY the counted substitutions with every sibling sample byte-identical; the plain re-run and `tests/design` whole green; the refreshed artefact committed in the SAME commit as its source; the two frozen goldens re-hashed unmoved, the commit body naming the door and the register row). Why: the freeze register itself lists `UPDATE_ORGANIC_SAMPLES` under `excludedEnvSpellings` — 'a build-artifact byte golden … It pins a RENDERED PAGE, not a generated world; it moves when the sample builder moves' — the same class as `gen:compendium-data` and `build:edge-shared`, both of which lanes already run. Rejected: the categorical reading (both cures die in the lane and the taste-veto pages keep a glyph the shipped card dropped and a spelling the estate retired); landing commit 3's comment half alone (its paragraph says the divergence is closed, false until the sample follows). Reversal: revert the two commits; the pages regenerate from source. Blast radius: two committed HTML samples change by 13 marks and one word, shown to the owner in the sitting's report; no world fingerprint moves. Any OTHER excluded spelling is asked of the chair by name. FIX-P9 also corrected its predecessor's grep prediction (rendered sites 1 → 0 while matching LINES 4 → 6) — count the thing the claim is about. "
 "**COMPILE-EM-B3d ACCEPTED — DRAFT, READY-able (kit `packets-waiting/EM-B3d.*`, `findings/COMPILE-EM-B3d/`):** the finding that raises its standing — `tests/lib/editTravel.test.js` names an IMPORT arm (design §12 item 4) that its body never executes, so EM-B3d builds the strip K4 deferred AND the runtime arm the ruling names. Measured: three call sites by symbol, NO fourth import path (denominator 8 lines); the destructure-omit spelling reads ZERO keys for the observed-shape instrument (a guard spelling would mint two identities); it reaches NO byte budget and no edge-shared input; lighting delta titles +5 / suites +1 (credited-ness owed to the pre-proof's `parkReasonsFor` print). **Q1 RULED (JUDGMENT 5): THE OVERRIDE IS APPROVED — modified logic files 3 → 4, direct consumers 2 → 3** — one cause, the module's own law that all three import paths route through one scrub; the three call-site edits are one-token wraps. Rejected: minting a CALL-SITE budget class now — a standard amendment re-stamps the preamble hash under twenty compiled packets for one packet's convenience; it is slotted for the next preamble amendment's agenda instead. Q2 (three citations as addresses-only rows), Q3 (no other seam — `normalizeSettlement` runs on every load and would erase the DM's own edits) and Q4 (`NOT_YET_WRITTEN_KEYS` stays a required symbol; EM-C4a's compile owes its discharge) ACCEPTED as recommended. ITS SEVEN NOTICED ITEMS FATED: (1) a docblock naming arms its body never runs — the instance is cured here; the CLASS is CLOSED with reason (no mechanical predicate exists that is not a prose reader, which FIX-T2 retired from the detectors; review lanes read docblocks); (2) the citation walker's ARM 1 sees past-EOF only → the chair rules ARM 3's gating at FIX-C2d's measurement (its commit 4 gives the residue); (3) CLOSED (re-measured by law); (4) the observed-shape baseline's three file manifests are frozen at `31ab5d18b` and are not a live gate → a line in the TOOL-13a mint's checklist (the bundle door re-derives them) and in LANE-EM-COMPILE's foot at the next kit edit; (5) CLOSED with reason; (6) `personaSlicer.js` is the one reader of `settlement.decrees` → A NAMED LINE FOR EM-C1's COMPILE: pending, applied, or neither may feed an AI persona slice; (7) CLOSED. "
 "**SEATS:** CURE-L (the slot, the gate) · FIX-C2d · DEPLOY-PREFLIGHT · FIX-P10's scratch preparation of commit 5; FIX-P9 PAUSED AT THE GATE, first after RUN 24. The owner's four questions of 15:0x (the push chain's in-session word · the seat count · §934.76 · the clean finished lane worktrees) are unanswered at this stamp; nothing gated has been crossed.")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 113 —"; assert u.count(key) == 1 and "addendum 114 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 114" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — RUN 23 red; CURE-L; EM-B3d accepted; FIX-P9's door (ODQ §934.47 addendum 114)\n\n"
 "- **RUN 23 RED on three tests, two causes** (the fork-door walker in `tests/data` convicts FIX-P1d's measuring call; EM-B1e's A4 arm pins the prose-manifest golden's pre-CURE-J sha as a literal). **CURE-L** holds the slot and the gate (brief `briefs/launch/CURE-L.md`); the ninth refreeze if a title moves; RUN 24. The blinded `build` + `verify:dist` measured green at `e45c4738b`; the generation worker has ZERO slack (1,401,208 / 1,401,208).\n"
 "- **EM-B3d COMPILED AND ACCEPTED (DRAFT, READY-able; train EM-T7's first member):** the import strip of `dmLayer` and `decrees` AND the runtime import arm design §12 item 4 names and `editTravel.test.js` never ran. THE BUDGET OVERRIDE IS APPROVED (modified logic files 3 → 4, direct consumers 2 → 3); a CALL-SITE row class goes on the next preamble amendment's agenda. Its pre-proof prints `parkReasonsFor` for both test files. **EM-C1's compile gains a named line:** `personaSlicer.js` is the one reader of `settlement.decrees` — rule which of pending / applied / neither may feed an AI persona slice. **EM-C4a's compile owes** the `NOT_YET_WRITTEN_KEYS` discharge.\n"
 "- **FIX-P9** may use `UPDATE_ORGANIC_SAMPLES=1` under six conditions (the freeze register excludes that spelling by name; LANE-PARALLEL's foot carries the ruling); any other excluded spelling is asked by name.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 114:", io.open(ODQ, encoding="utf-8").read().count("addendum 114 —"), "| charter amended | no NUL")
