# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 113 — FIX-P1 COMPOSED AND THE COMPOSED TIP PROVEN; THE EIGHTH REFREEZE `e45c4738b`; RUN 23 LAUNCHED; TOOL-21's VERDICT AND §934.76 OPENED; four seats working (2026-09-20 " + stamp + " EDT; the chair, session `4a1823e2`; every call vetoable).** "
 "**FIX-P1's WINDOW (it held the slot and the one gate):** its OSR cure composed CLEAN as `ee204c827` (blob-equal to `61c5f1722`), and the CURE-J archival-roster line as `da5310f30` (`archivalExclusionAtFreeze.byRule.tree` 16 → 17, measured with the shipped detector by a plain-node import: the sole newcomer is `docs/shift-records/2026-09-20-cure-j-provenance.json`, born archival — a growth, not a move; `pastEofCitationsExcluded` unchanged at 377). THE PROOFS AT `da5310f30`, each count line read by the chair from the lane's logs before its report: `tests/lint` WHOLE `1 failed | 176 passed (177)` · `1 failed | 2846 passed (2847)`, the ONE red the lighting walker stopped at `files` (2665 vs 2664) — the three reds of the handoff are gone; `tests/scripts` whole 9 files / 125; `tests/build` whole 59 files / 478 passed, 65 skipped; `tests/lib` whole 174 / 1800; the OSR checker exit 0 (`1964 finding(s), exactly matching the frozen inventory`); eslint bare exit 0; the goldens unmoved (`7177cd6e…` / `88983938…`). FIX-D9's two owed directory proofs are DISCHARGED by the same window. "
 "**THE EIGHTH LIGHTING REFREEZE `e45c4738b` (the branch tip):** the door (red by design) printed files 2664 → 2665 · parked 359 → 359 · credited 2305 → 2306 · titles 25501 → 25529 · suiteTitles 6812 → 6815; the plain run 34/34. Attribution by a per-commit count over `578272a99..da5310f30`: EM-R0a +7/+1 and its walker file; FIX-T2 +4/+1; FIX-P1c +5; FIX-D9 net +3/+1 (the retired test −7/−1, the disposition walker +10/+2, files net 0); TOOL-19 +1; FIX-C2c +3; TOOL-25 +5 = 28 titles and 3 suites, equal to the door. FIX-B2's +3/+1 in two `tests/build` files are not counted, which is what the tuple implies for files the census parks (PLAUSIBLE; TOOL-9's print mode names the roster when it composes). "
 "**RUN 23 LAUNCHED 14:53:51** in the consist detached at `e45c4738b` after `rm -rf dist` (log `<SP>/consist-check-2-run23.log`; expected NO red; runs 20 and 22 took about twenty minutes). Nothing else gates while it runs. "
 "**FIX-P1's THREE NOTICED ITEMS, FATED:** (1) the citation baseline's freeze stamp contradicts `_rosterMove2026-09-20` beside it (29 vs 30 archival) → FIX-C2d's gate hand-off: an as-of annotation beside the stale sentence under its own ruling R2, never a rewrite; (2) the lighting walker asserts in order and hides four figures per red → CLOSED into TOOL-9, whose print mode (paused at its gate) is exactly this cure; (3) `docs.live` drifted 482 → 484 with no arm reading it → FIX-C2d's commit 4 prints the live count and annotates the stamp as-of; no gate is minted for a figure nothing reads. "
 "**TOOL-21 DONE (read-only; kit `findings/TOOL-21/` at the next refresh; report `<SP>/lane-tool-21-scratch/TOOL-21.report.md`):** CONFIRMED by driving the real `recordGolden` in a hermetic sandbox — 47 of 50 frozen register rows carry `proofForm: null`, which makes `PROOF_FORM_MISMATCH` unreachable for them (a map-family re-record proving with `derived-artefact` is ACCEPTED and written); but THREE PREMISES OF THE CHARTER ARE FALSE BY MEASUREMENT: §555.8 is a car-specific instruction whose own premise §561.2 refuted, never a register law; NO ruling assigns a proof form to any surface (so 44 of 47 back-fill values would be invented); and no door verb writes `proofForm` at all while no walker arm reads it. Zero pin drift, zero absent files. The replay of all ten shift records: 0 refused today, 0 refused under a signed-precedent back-fill. Option (b) as chartered ('refuse when the record carries a form and the row is null') is REFUTED BY EXECUTION — it seals all 47 surfaces shut, `generator-golden-master` included. "
 "**§934.76 OPENED (the owner's word, in session — it changes what the golden door writes): THE DOOR LEARNS A NULL ROW'S PROOF FORM AT FIRST USE.** When the row is null and an owner-signed record carries a lawful form, the door writes `row.proofForm` beside the three fields it already writes; a set row is governed by the existing check unchanged; shipped with a walker arm and a plant, since the field has no instrument today. The chair RECOMMENDS YES: no value is ever invented, protection only grows, the replay shows zero historical false positives. Rejected: the back-fill (invented values nothing would catch); option (b) (seals the estate); leaving it (acceptable only with the record corrected to what is true: the genesis freeze did not fill a field its own FIELD MEANINGS says is filled at the freeze act). **FIX-G4 CHARTERED for the build on the owner's word** — the door's write set, the walker arm and plant, `README.md:62` ('Must equal' is enforced on 3 of 50 surfaces) and `:118` ('the register pins each one by hash' — 1 of 11 records is pinned) corrected, the six fixtureless dormancy suites' owed ruling, and the rider fence's silent enrollment recorded. "
 "**SEATS (four live, one gate):** COMPILE-EM-B3d dispatched at `ee204c827` (train EM-T7's first member — the `importScrub` strip of `dmLayer` and `decrees`, EM-B3a's K4 deferral; brief `briefs/launch/COMPILE-EM-B3d.md`); FIX-C2d dispatched at `da5310f30` (209 document leads read row by row; pauses at its gate); FIX-P9 RESUMED for its ungated preparation and is FIRST at the gate after RUN 23 (brief `briefs/launch/RESUME-FIX-P9-P10.md`: FIX-P9 gains commit 4 = the rendered sample's hard-coded 'Thorp' in `fixtures.js`; FIX-P10 gains commit 5 = `GenerateWizard`'s scroll-padding derived from `HEADER_H` and `TOUCH_TARGET`); DEPLOY-PREFLIGHT dispatched (read-only: CI job by job against the local check's coverage, migrations 201–203 classified statement by statement with their order against the redeploy, the runbook's credentialed steps named as the owner's hand, the PR body's stale rows). "
 "**JUDGMENT 3 — HOUSEKEEPING UNDER A 98%-FULL DISK:** Decided: twelve CLEAN, finished, chair-created read tips removed with `git worktree remove` (never `--force`), 3.7 → 7.0 GiB free, before RUN 23's build and swap needed the room; each restore command is recorded in `tools/chair-scripts-4a1823e2/read-tips-removed.txt`. Why: a full check that fills the data volume reds falsely, and a read tip is a cache of committed objects. Rejected: waiting for the owner's answer with 3.7 GiB free and a build about to run. Reversal: one `git worktree add --detach <path> <sha>` each. Blast radius: no branch, commit, lane worktree or scratch directory touched; two read tips in use were kept. "
 "**THE OWNER'S DESCRIPTION REQUEST IS DELIVERED** (the finished product in plain language, experience and engineering; three Opus surveys gathered it, the chair read the vision document and wrote it; sent as a file).")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 112 —"; assert u.count(key) == 1 and "addendum 113 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 113" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — FIX-P1 composed; the eighth refreeze; RUN 23; §934.76 and FIX-G4; the seats (ODQ §934.47 addendum 113)\n\n"
 "- FIX-P1d `ee204c827` and the CURE-J archival-roster line `da5310f30` composed and proven at the tip (`tests/lint` whole red on the lighting walker only; `tests/scripts`, `tests/build`, `tests/lib` whole green; FIX-D9's two owed proofs discharged). The eighth lighting refreeze `e45c4738b` = `2665·359·2306·25529·6815`. RUN 23 launched 14:53:51 at that tip.\n"
 "- **FIX-G4 CHARTERED (dispatched on the owner's word at §934.76):** the golden door learns a null register row's `proofForm` at first use from an owner-signed record; a walker arm and a plant; the shift-records README's two false sentences corrected; the six fixtureless dormancy suites' ruling; the rider fence's enrollment recorded. TOOL-21 closed with its report.\n"
 "- **FIX-P9 gains commit 4** (the rendered sample's hard-coded 'Thorp'); **FIX-P10 gains commit 5** (`GenerateWizard`'s scroll-padding derived from `HEADER_H` and `TOUCH_TARGET`). FIX-C2d's gate hand-off carries FIX-P1's noticed items 1 and 3; item 2 is closed into TOOL-9.\n"
 "- COMPILE-EM-B3d dispatched (train EM-T7's first member); DEPLOY-PREFLIGHT dispatched (read-only) ahead of the push chain, which waits for the owner's word in session.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 113:", io.open(ODQ, encoding="utf-8").read().count("addendum 113 —"), "| charter amended | no NUL")
