# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 117 — CURE-L CLOSED GREEN (three commits); THE NINTH REFREEZE `7a4ea48e9`; RUN 24 LAUNCHED 15:46:14; THE OWNER'S BATCH GATES ADOPTED AND THE BATCH LEDGER OPENED; TOOL-26 CHARTERED (2026-09-20 " + stamp + " EDT; the chair, session `4a1823e2`; every call vetoable).** "
 "**CURE-L (the FIX-P1 agent resumed; it held the slot and the one gate; kit `findings/CURE-L/`):** `65cbf86e1` cause A — the measuring call passes `forkIdentity(<a declared synthetic non-empty id>)` (pure at module evaluation, proven by a plain-node import; `FORK_SEED_MAX` still 26) and the walker's import arm learns `definesForkIdentity` with a counterforce arm; two plants red the arms they should and were restored by copy, byte-identical; `85cd9f4a8` cause B — EM-B1e's A4 arm reads the three artefacts' pins from the freeze register by surface id (fail-closed on a missing surface, a null sha, a non-array), CENSUS FIRST: the register parsed at all 25 commits that ever touched it, 13 distinct shas, `git grep -P` over tests/src/scripts found 6 sites — 3 register rows untouched and the 3 A4 literals re-pointed; class (b) empty; `835f81812` the e2e job's CI cap 15 → 25 (anchored on the `e2e:` header; `performance` 15, `check-tests` 45, `coverage-floors` 60 unmoved; 8 → 14 spec files, 39 → 81 `test(`, explicitly budgeted time 1155 s → 1335 s, `retries: 1`). ALL THREE DIFFS READ WHOLE AND VALIDATED BY THE CHAIR. PROOFS, count lines read by the chair from the lane's logs: `tests/data` 24 files / 312 · `tests/lib` 174 / 1800 · `tests/domain` WHOLE 985 files / 16,646 tests (362 s) · the CI parity pair 2 / 38 · `tests/build` 59 files / 478 passed 65 skipped · `tests/lint` WHOLE `1 failed | 176 passed (177)`, the one red the lighting walker at `titles` (25530 vs 25529 — the lane's declared +1); the OSR checker exit 0; goldens unmoved. "
 "**THE NINTH LIGHTING REFREEZE `7a4ea48e9` (the branch tip):** the door (red by design) printed titles 25529 → 25530 and every other figure unmoved (`2665·359·2306·25530·6815`); the plain run 34/34; the lane's declared delta and the door's measurement agree. **RUN 24 LAUNCHED 15:46:14** in the consist detached at `7a4ea48e9` after `rm -rf dist` (log `<SP>/consist-check-2-run24.log`). "
 "**THE OWNER'S TWO SENTENCES, IN THE LIVE SESSION, verbatim:** \"By the way, can you not combine some different areas into one gate if they are queued in line to preserve time?\" — and — \"And you will assign them into appropriate batches as they come correct or into new ones if they don't fit into an appropriate one\". **JUDGMENT 8 — BATCH GATES.** Decided: queued lanes whose change sets are disjoint are COMPOSED onto one throwaway batch branch cut at the green tip by an Opus composer lane (cherry-pick committed work; export-and-`git apply --3way` uncommitted work, one commit per lane under its prepared message; each still-owed FOCUSED red-first run in sequence while the lane is applied); the chair refreezes the lighting census once and absorbs the observed-shape baseline once; ONE full check proves the batch; green ⇒ the integration branch fast-forwards; red ⇒ attribute by the failing tests' subjects, drop or cure the member on the throwaway branch, re-run. A lane is ASSIGNED the moment it is gate-ready — into the newest open batch if it passes THE FIT TEST (files disjoint or disjoint hunks read; a clean dry-run apply at the batch tip; no unstated register ordering; at most ONE golden-door or same-family fixture-regeneration member; build-measuring lanes share ONE build batch; a batch closes at six members or about sixty files; sealed Edit-Mode builds are never batched), otherwise into a NEW batch. Why: about twenty paused lanes each owed a 15–30 minute window re-running `tests/lint` and their directories AT A STALE BASE — six to eight hours of serial gate (the chair's estimate) — and RUN 23 proved those own-base runs miss exactly the failures that matter (both of its reds existed only at the composed tip). Rejected: per-lane windows (the status quo — slower AND weaker). Reversal: gate a lane alone under verb 4 as before. Blast radius: no product code; attribution moves from the lane's own receipt to the batch's one run, recorded per member in `BATCH-LEDGER.md` (kit) and in each batch's ledger addendum. THE LEDGER IS OPEN: **B1** = FIX-C2d · FIX-P9 · FIX-P10 on RUN 24's green tip; **B2** = FIX-W1 (its one golden-door member; the chair signs its drafted record first) + the older paused lanes the forecast clears; **B3** = the 09-19 dead three that are not build-bound · FIX-P4b · TOOL-15 · TOOL-22 · TOOL-24 · FIX-G4; **BUILD** = FIX-P2 · TOOL-3 (+ TOOL-16 · TOOL-17 · FIX-B3); FIX-D6 (a golden-door user) waits for a batch with no other door member — all PROVISIONAL until QUEUE-RECON's forecast (now extended with a batch-partition section) confirms file-disjointness and the apply method per lane. RUN 24 stays cures-only so the push candidate is the smallest honest delta. "
 "**CURE-L's NOTICED ITEMS, FATED:** (1) ⭐ 104 test files OUTSIDE `tests/lint` walk the `src/` tree across 19 directories (103 inside it) — a `src/` lane obeying 'tests/lint whole' misses 103 of them, which is exactly how FIX-P1d shipped → **TOOL-26 CHARTERED**: a shrink-only roster of every test file that reads `src/` by path, with the governed directories per `src/` area derived from it, so a lane is HANDED its counted set instead of rediscovering it by conviction (the batch gate's full check already covers every one of them at the composed tip; TOOL-26 serves lanes that gate alone and every future program); (2) the freeze register's `_doc` still says the register is UNFROZEN while all three freeze fields are set → FIX-G4 measures whether `_doc` can be corrected lawfully and reports (no hand edit of the register); (3) the citation baseline's stale `burnedDownBy` sentence → already FIX-C2d's (addendum 113); (4) the lighting walker's ordered assertion hid `suiteTitles` again → already CLOSED into TOOL-9. "
 "**SEATS:** FIX-G4 DISPATCHED at `7a4ea48e9` as a batch member-to-be (it ends `GATE-READY FOR A BATCH`, its note composer-ready); FIX-W1 working; QUEUE-RECON and LEFT-CENSUS (the enumerated denominator behind the owner's question 'What is all left to run and build?') read-only. The chair's answer to that question was given in chat from a fresh snapshot: twenty lanes with built work waiting on the gate; about a dozen chartered lanes never started; the Edit-Mode train at 12 landed, about twenty compiled and waiting, waves 2–5 and the first door uncompiled; then the simulation architecture program, the paid volumes, the Scribe, the content platform, the map module and the launch endgame.")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 116 —"; assert u.count(key) == 1 and "addendum 117 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 117" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — CURE-L closed; the ninth refreeze; RUN 24; BATCH GATES; TOOL-26 (ODQ §934.47 addendum 117)\n\n"
 "- CURE-L's three commits (`65cbf86e1` · `85cd9f4a8` · `835f81812`) cure RUN 23's two causes and raise the e2e CI cap; the ninth lighting refreeze `7a4ea48e9` = `2665·359·2306·25530·6815`; RUN 24 launched 15:46:14 at that tip.\n"
 "- **STAFFING AMENDED BY THE OWNER — BATCH GATES:** queued lanes with disjoint change sets compose onto one throwaway batch branch and share ONE full check; a gate-ready lane is assigned to the newest open batch it fits, else a new one; the fit test and the live batches are in the kit's `BATCH-LEDGER.md`; sealed Edit-Mode builds and a second golden-door lane are never batched together. Verb 4's pause-and-resume still governs a lane that gates alone.\n"
 "- **TOOL-26 CHARTERED:** a shrink-only roster of every test file that reads `src/` by path (104 outside `tests/lint` across 19 directories, 103 inside), and from it the governed directories per `src/` area — a lane is handed its counted set. After B1.\n"
 "- FIX-G4 dispatched as a batch member-to-be; it also measures whether the freeze register's stale `_doc` sentence can be corrected lawfully.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 117:", io.open(ODQ, encoding="utf-8").read().count("addendum 117 —"), "| charter amended | no NUL")
