# -*- coding: utf-8 -*-
import io, sys
stamp = sys.argv[1]
ODQ = "docs/OWNER_DECISION_QUEUE.md"; CH = "docs/implementation/charters/EDIT-MODE-TRAIN.md"
line = ("- **§934.47 addendum 116 — THE OWNER'S WORD IN THE LIVE SESSION, verbatim (~15:3x, in answer to the chair's listed gates): \"I leave all decisions to you and give you all deferment regarding signatures and golden door signings\" — every listed question DECIDED as recommended; §934.76 DECIDED YES; the signature grant RE-CONFIRMED in session (2026-09-20 " + stamp + " EDT; the chair, session `4a1823e2`; every call vetoable).** "
 "**WHAT WAS ASKED (15:00 and 15:25, in chat):** the push chain in its re-cut order · four seats or four plus a gate seat · §934.76 · removing the clean finished 09-18/19 lane worktrees · closing PR #48 · the 12:2x standing signature grant's re-confirmation for FIX-W1's golden-door commit. **THE CHAIR'S READING, said back to the owner in chat:** the sentence answers the list. "
 "**DECIDED:** (1) THE PUSH CHAIN RUNS after a fully green full check (RUN 24 or its successor) and the cheap CI-only pre-runs, in addendum 115's order, the owner's words quoted at each outward step (close PR #48 unmerged → push the ledger → push the consist with the pre-push hook honest → the PR with a refreshed body); THE MERGE TO MASTER IS ANNOUNCED IN CHAT BEFORE IT HAPPENS, because it is the act that changes production, and it cannot deploy until the OWNER'S OWN HAND has applied migrations 201–203 (production credentials are never the chair's keystrokes) and handed over the live head number — that hand-act is the owner's participation in the deploy; the edge-function redeploys and `ops:post-deploy` stay the owner's hand for the same reason. (2) FOUR lanes live, ONE gate holder at a time (the chair's reading stands; the gate, not the seat count, is the program's bottleneck — more builders only deepen the gate queue). (3) **§934.76 YES — FIX-G4 BRIEFED** (`briefs/launch/FIX-G4.md`: the instrument first, the door's write set gains `proofForm` under exactly the ruled condition, the README's two false sentences, the historical replay as a standing arm; dispatched at the cured tip after CURE-L lands so the two cannot collide in `tests/helpers`). (4) THE SIGNATURE GRANT STANDS IN SESSION: the chair signs REPAIR shift records whose moved rows are measured and attributed, trailer `Owner-Signed: §<row> (by the owner's in-session deferment of 2026-09-20 15:3x)`; FIX-W1 was told — it drafts its record, the chair reads and signs it at the gate hand-off, only then does the lane run the door. NOT assumed under a sentence about repairs: the endgame TUNING signature (THE PROMISE), production data deletion, security posture, new paid capability. (5) PR #48 is closed unmerged at the push. "
 "**HOUSEKEEPING EXECUTED under (4)'s sibling approval:** eight finished 09-18/19 lane worktrees with CLEAN trees removed by `git worktree remove` (never `--force`), branches untouched, 6.6 → 11 GiB free; restore commands in the kit's `tools/chair-scripts-4a1823e2/lane-worktrees-removed.txt`. SIX were KEPT because each holds one untracked `.lane-resume.md` (`lane-public-copy`, `lane-typography`, `lane-prose-weave`, `lane-gates-store`, `lane-console-hygiene`, `lane-gallery-errors`) — a note is work, and nothing is forced. "
 "**CURE-L, FIRST COMMIT `65cbf86e1` — READ WHOLE AND VALIDATED BY THE CHAIR:** the measuring call now passes `forkIdentity(<a declared synthetic non-empty id>)` — pure at module evaluation (the signed-in branch is two `fnv1a32` rounds; proven by importing the module in plain node), `FORK_SEED_MAX` still 26; the walker's import arm learns `definesForkIdentity` (judged over comment-stripped code) with a counterforce arm proving a mere mentioner still convicts; two plants (a bare-id call inside the definer; a throwaway door that neither defines nor imports) red the arms they should and were restored byte-identically by copy. It adds ONE title, so the ninth lighting refreeze follows its window. Causes B and the CI cap are in flight. "
 "**THE MEMORY RECORDS the sentence as HISTORY, not as a grant to a later session** (`owner-directive-2026-09-20-in-session-all-decisions-and-all-signatures-deferred-to-the-chair`): a successor re-confirms in its own chat before any push, merge, migration, deploy or golden-door signing.")
u = io.open(ODQ, encoding="utf-8").read()
key = "- **§934.47 addendum 115 —"; assert u.count(key) == 1 and "addendum 116 —" not in u
i = u.index(key); j = u.index("\n", i); u = u[:j + 1] + line + "\n" + u[j + 1:]
io.open(ODQ, "w", encoding="utf-8").write(u)
c = io.open(CH, encoding="utf-8").read(); assert "addendum 116" not in c
if not c.endswith("\n"): c += "\n"
c += ("\n## Amendments of 2026-09-20 " + stamp + " EDT — the owner's in-session word; §934.76 decided; FIX-G4 briefed (ODQ §934.47 addendum 116)\n\n"
 "- **THE OWNER, IN THE LIVE SESSION (~15:3x), verbatim:** \"I leave all decisions to you and give you all deferment regarding signatures and golden door signings\". Every listed gate is decided as recommended: the push chain after a fully green check in addendum 115's order (the merge announced first; migrations, edge redeploys and `ops:post-deploy` the owner's hand because they need credentials); four lanes / one gate holder; PR #48 closed unmerged; the chair signs repair shift records.\n"
 "- **§934.76 DECIDED YES — FIX-G4 BRIEFED** (`briefs/launch/FIX-G4.md`), dispatched at the cured tip after CURE-L lands. FIX-W1's golden-door commit proceeds on the chair's signature of its drafted record.\n")
io.open(CH, "w", encoding="utf-8").write(c)
assert bytes([0]) not in io.open(ODQ, "rb").read() and bytes([0]) not in io.open(CH, "rb").read(), "NUL in the ledger — STOP"
print("ODQ addendum 116:", io.open(ODQ, encoding="utf-8").read().count("addendum 116 —"), "| charter amended | no NUL")
