import json
base='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/'
src=json.load(open(base+'chunks/kay-01.json'))
V=[
(383,"VERIFIED_VERBATIM","If I do it right, this use of the fantastic ... causes reader and author to share with each other that we are, indeed, rhyming with the past, not trying to pin the present down with it precisely.","Raw page fetched (HTTP 200). Quote is a literal substring. Preceding sentence supplies the 'quarter-turn to the fantastic' referent ('What one reviewer called history with a quarter-turn to the fantastic. If I do it right, this use of the fantastic...'). Only nuance: Kay hedges the effect with 'If I do it right', which the claim drops."),
(384,"VERIFIED_VERBATIM","I want people reading ... and also thinking about ... right now. Not for lessons! I'm offering a story not giving a lecture.","Raw page. Quote verbatim (curly apostrophe). Both limbs -- readers thinking about their own time, and not-for-lessons/story-not-lecture -- are consecutive sentences in the penultimate section."),
(385,"VERIFIED_VERBATIM","I'm focused on complicating things, multiple ideas, on nuance, on letting readers decide what they find in or take away from a book.","Raw page, fifth paragraph of Kay's essay. Quote verbatim. Claim omits 'multiple ideas' but adds nothing unsupported."),
(386,"VERIFIED_VERBATIM","we are at risk ... if we are ignorant of the themes of history. That doesn't necessarily mean the minutiae of dates and places, it has to do -- for me -- with patterns, lessons, warnings that can emerge.","Raw page, answer 2, as the claim's page hint says. Quote verbatim; all three limbs present. Kay frames it negatively ('ignorant of the themes of history'); the claim's 'being alert to' is the same proposition inverted."),
(390,"VERIFIED_VERBATIM","Children of Earth and Sky was deliberately set up in my mind to be about people who are not important in the scheme of things ... how those grand events can reach down and affect people far away.","Raw page, answer 5, matching the page hint. Quote verbatim; both limbs are sentences in the same answer."),
(394,"VERIFIED_VERBATIM","I started thinking about how some parts of the world still carry the hard imprint of what has gone before.","Raw page ('Letter to the Reader of Ysabel'), penultimate paragraph as hinted. Quote verbatim; Kay's own first-person statement."),
(395,"VERIFIED_VERBATIM","I believe that grounding has to be so secure that the vast majority of the research does not enter the book except subliminally, or does so very quietly ... or else you get what I hate as a reader, which is the 'info dump'.","Raw page, in the answer about research for River of Stars. Quote verbatim; every limb (secure grounding, vast majority, subliminal/quiet, info dump he hates as a reader) is in the one sentence."),
(396,"VERIFIED_VERBATIM","I often find that through the peripheral figures I can achieve my strongest effects, whether of character, emotion, or shaping depth to a setting for the reader.","Raw page. Quote verbatim. Note the site's own formatting runs the grey-characters question into the previous answer with no break, but the sentence is Kay's and sits in that answer."),
(402,"VERIFIED_VERBATIM","Now, I don't believe in saying exactly what happens to characters after a novel closes - the ending of every book I've written makes this point.","Raw page, in the Sharra passage as hinted. Quote verbatim; both limbs in one sentence. Date detail only: the header says the afterword first appeared in the 2004 20th-anniversary edition, and Kay signs it December 2003, so the source label's '(2003)' is the signing date, not the publication date."),
(406,"VERIFIED_VERBATIM","I don't write novels inspired by history to offer easy parallels to our own time. That can feel lazy, or glib, or both.","Raw page (essay headed 'Exile'; the WordPress post title is 'Under Heaven Author's Letter'). Quote verbatim, in the paragraph following the River of Stars discussion, as hinted. The claim's 'because' makes explicit a link the page leaves to adjacency."),
(408,"VERIFIED_VERBATIM","Dunnett also flatly refuses to talk down to her readers; she makes demands and rewards them - hugely.","Raw page; the Lymond Chronicles entry, as hinted. Quote verbatim. Page confirms the piece first appeared at cbc.ca in 2016."),
(409,"VERIFIED_VERBATIM","I steep myself in a period and then I twist it just that little bit to give myself the ethical and creative space that seems to work for me.","Raw page (BrightWeavings reproduction, headnote: 'originally appeared at theguardian.com ... written by Alison Flood'). Quote verbatim, in the El Cid paragraph as hinted. Claim's 'just a little' paraphrases 'just that little bit'."),
(410,"VERIFIED_VERBATIM","One critic described his work as 'history with a quarter-turn to the fantastic' - a phrase Kay loves.","Raw page. Quote verbatim, in Flood's narration (not in Kay's quoted speech), which is exactly what the claim asserts: the phrase is the critic's, reported by Flood."),
(411,"VERIFIED_VERBATIM","I've been calling it an epidemic of co-opting real lives ... Though he is careful never to criticise any writer who does.","Raw page. Quote verbatim in Kay's speech. The second limb is Flood's narration plus Kay's own words ('I have vastly enjoyed a great many books that do not share my view on this'); the article separately notes he will not 'discuss or critique contemporaries'."),
(412,"VERIFIED_VERBATIM","I have several scenes in this novel where a conversation takes place, as described by more than one of the people in the conversation. When I switch to another character's point of view, the conversation isn't the same.","Raw LARB page fetched directly (HTTP 200, no paywall). Quote verbatim, in the answer to the question about multiple points of view, as hinted. 'This novel' is Children of Earth and Sky, the interview's subject."),
]
out={"name":src["name"],"chunk":src["chunk"],"claims":src["claims"],
 "verdicts":[{"index":i,"verdict":v,"trueWording":t,"note":n} for i,v,t,n in V]}
idx=[c["index"] for c in src["claims"]]
assert idx==[i for i,_,_,_ in V], (idx,[i for i,_,_,_ in V])
p=base+'verdicts-kay-i383-412.json'
json.dump(out,open(p,'w',encoding='utf-8'),indent=1,ensure_ascii=False)
print("wrote",p,len(json.dumps(out)))
