import { readFileSync } from 'node:fs';
const SC='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad';
const A=JSON.parse(readFileSync(`${SC}/capacity/artifacts/research-lit-4s.cases/research-lit-4s-300y-4s-seed1.json`,'utf8'));
const B=JSON.parse(readFileSync(`${SC}/capacity-horizon/artifacts/horizon-600y-4s-lit.json`,'utf8'));
const ya=A.behavioral.yearly, yb=B.behavioral.yearly;
console.log('yearly lengths', ya.length, yb.length);
const rdA=ya[299].realmDemography, rdB=yb[299].realmDemography;
console.log('A y300 realmDemography:', JSON.stringify(rdA));
console.log('B y300 realmDemography:', JSON.stringify(rdB));
console.log('B y600 realmDemography:', JSON.stringify(yb[599].realmDemography));
console.log('\nmarks in B:');
for(const y of [300,350,400,450,500,550,600]) console.log(' y'+y, yb[y-1].realmDemography.loadRatio01);
console.log('\ndivergence evidence A:', JSON.stringify(A.storyMixDivergence||A.divergence||null).slice(0,600));
console.log('\ndivergence evidence B:', JSON.stringify(B.storyMixDivergence||B.divergence||null).slice(0,600));
