# -*- coding: utf-8 -*-
COMPLETE = False
COVERAGE = "in progress"

SOURCES = [
 {"title":"Fantasy as Memory: The Historical Imagination of Guy Gavriel Kay (Chris McBean, The Rowanwood Chronicles)","url":"https://therowanwoodchronicles.blog/2025/12/24/fantasy-as-memory-the-historical-imagination-of-guy-gavriel-kay/","kind":"analysis","substantive":True,"date":"2025-12-24","route":"curl browser UA (WebFetch returned a summary, not the page)"},
 {"title":"The Fantastic Worlds of Guy Gavriel Kay — Christine Fischer Guy interviews Kay (Los Angeles Review of Books)","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","kind":"own-words","substantive":True,"date":"2016-08-14","route":"curl browser UA"},
 {"title":"The Masters Of Prose (The Quill to Live)","url":"https://thequilltolive.com/2016/01/07/the-masters-of-prose/","kind":"reader","substantive":True,"date":"2016-01-07","route":"curl browser UA"},
 {"title":"You Should Read Tigana (Eric Falden, Falden's Forge, Substack)","url":"https://ericfalden.substack.com/p/you-should-read-tigana","kind":"analysis","substantive":True,"date":"2024-02-23","route":"curl browser UA"},
 {"title":"Ambiguities and Divided Loyalties: Focalization in Guy Gavriel Kay's Tigana — BA thesis, Roosa Toyryla, University of Helsinki (hosted at BrightWeavings)","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","kind":"analysis","substantive":True,"date":"2017-08-05 (thesis 2017)","route":"curl browser UA"},
 {"title":"Provencal Fantasy: Guy Gavriel Kay's A Song for Arbonne (Jo Walton, Tor.com / Reactor)","url":"https://reactormag.com/provencal-fantasy-guy-gavriel-kays-a-song-for-arbonne/","kind":"reception","substantive":True,"date":"2010-08-06","route":"curl browser UA"},
 {"title":"Review: Sailing to Sarantium (Kate Nepveu, steelypips.org; originally posted to rec.arts.sf.written)","url":"https://www.steelypips.org/reviews/sarantium.html","kind":"reception","substantive":True,"date":"1999-05-12","route":"curl browser UA"},
 {"title":"Review of Sailing to Sarantium by Guy Gavriel Kay (Jesse, Speculiction)","url":"http://speculiction.blogspot.com/2014/05/review-of-sailing-to-sarantium-by-guy.html","kind":"reception","substantive":True,"date":"2014-05-06","route":"curl browser UA"},
 {"title":"Altering the Familiar: Tigana by Guy Gavriel Kay (Joshua Palmatier, Tor.com, 'That Was Awesome! Writers on Writing')","url":"https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","kind":"analysis","substantive":True,"date":"2016-07-06","route":"Wayback raw capture 20221205133732id_ (live tor.com and reactormag both Cloudflare-blocked)"},
 {"title":"Written on the Dark: Feels like Kay's most elegiac work (Bill Capossere, FantasyLiterature.com)","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","kind":"analysis","substantive":True,"date":"2025-05 (novel published May 2025)","route":"Wayback raw capture 20250624011037id_ (live fetch returned an empty body)"},
 {"title":"Sailing to Sarantium by Guy Gavriel Kay book review (Floresiensis and Calvin Park, Fantasy Book Review)","url":"https://www.fantasybookreview.co.uk/Guy-Gavriel-Kay/Sailing-to-Sarantium.html","kind":"reader","substantive":True,"date":"undated (site 2006-2026)","route":"curl browser UA"},
 {"title":"Sailing to Sarantium by Guy Gavriel Kay (Peat Long's Blog)","url":"https://peatlong.wordpress.com/2026/07/02/sailing-to-sarantium-by-guy-gavriel-kay/","kind":"reader","substantive":False,"date":"2026-07-02","route":"curl browser UA"},
]

CLAIMS = [
 # --- Rowanwood (Chris McBean) ---
 {"_file":"rowanwood","feature":"cadence and rhythm","claim":"McBean writes that Kay favours cadence, balance and carefully chosen imagery over density or excess.","source":"Chris McBean, 'Fantasy as Memory: The Historical Imagination of Guy Gavriel Kay', The Rowanwood Chronicles blog, 24 December 2025","url":"https://therowanwoodchronicles.blog/2025/12/24/fantasy-as-memory-the-historical-imagination-of-guy-gavriel-kay/","quote":"He favours cadence, balance, and carefully chosen imagery over density","page":"section 'Lyrical clarity rather than baroque fantasy'","kind":"analysis","polarity":"asserts","date":"2025-12-24","routeHint":"curl with a browser user agent returns the full post; WebFetch summarises it","registerHint":"none","confidence":"high"},
 {"_file":"rowanwood","feature":"place and institution description","claim":"McBean writes that Kay does not bury the reader in invented terminology or ornate description.","source":"Chris McBean, The Rowanwood Chronicles blog, 24 December 2025","url":"https://therowanwoodchronicles.blog/2025/12/24/fantasy-as-memory-the-historical-imagination-of-guy-gavriel-kay/","quote":"he does not bury the reader in invented terminology","page":"section 'Lyrical clarity rather than baroque fantasy'","kind":"analysis","polarity":"asserts","date":"2025-12-24","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"rowanwood","feature":"dialogue register","claim":"McBean writes that in Kay's dialogue emotion is often conveyed by what is not said.","source":"Chris McBean, The Rowanwood Chronicles blog, 24 December 2025","url":"https://therowanwoodchronicles.blog/2025/12/24/fantasy-as-memory-the-historical-imagination-of-guy-gavriel-kay/","quote":"Emotion is often conveyed by what is not said.","page":"section 'Dialogue as character and culture'","kind":"analysis","polarity":"asserts","date":"2025-12-24","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
 {"_file":"rowanwood","feature":"plainness and economy","claim":"McBean characterises Kay's prose as elegant without being ornamental.","source":"Chris McBean, The Rowanwood Chronicles blog, 24 December 2025","url":"https://therowanwoodchronicles.blog/2025/12/24/fantasy-as-memory-the-historical-imagination-of-guy-gavriel-kay/","quote":"elegant without being ornamental","page":"third paragraph","kind":"analysis","polarity":"asserts","date":"2025-12-24","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},

 # --- LARB interview (Kay's own words) ---
 {"_file":"larb","feature":"point of view and distance","claim":"Kay says that in Children of Earth and Sky he wrote several scenes in which one conversation is described by more than one of the people in it.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"a conversation takes place, as described by more than one","page":"answer to the question about multiple points of view","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent returns the full interview","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"larb","feature":"point of view and distance","claim":"Kay says that when he switches to another character's point of view the same conversation is not the same, though it bears a resemblance.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"It bears a resemblance, but it’s not the same.","page":"answer to the question about multiple points of view","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"larb","feature":"place and institution description","claim":"Kay says one starting point of Children of Earth and Sky was that it takes place on the borderlands in the lives of not-powerful people.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"on the borderlands in the lives of not-powerful people","page":"answer about legacy and fathers","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"larb","feature":"consequence on a household","claim":"Kay says his reading brought home to him that the ambitions of emperors, empresses, sultans and dukes did not much matter to the day-to-day desires of ordinary people on the borderlands.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"the ambitions and doings of emperors and empresses and sultans","page":"answer about legacy and fathers","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"larb","feature":"other: worldview rendered as the inhabitants hold it","claim":"Kay says the fantastic lets him make the world be as his characters believe it to be.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"make the world be as my characters believe it to be","page":"answer to 'How else does the fantastic serve your purposes?'","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"larb","feature":"other: worldview rendered as the inhabitants hold it","claim":"Kay says a modern reader tends to a smug, patronising attitude toward the past, and that presenting the world as the characters believe it removes that smugness.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"it removes that smugness from the reader","page":"answer to 'How else does the fantastic serve your purposes?'","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"larb","feature":"other: signalling the invented world","claim":"Kay says he has used two moons in several books as a signal to the reader that the setting is not our world.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"The two moons say, We’re not here","page":"answer about setting the rules of engagement","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
 {"_file":"larb","feature":"other: history-shaped invention","claim":"Kay says that if a reader can pick out what is made up and what is real, the storytelling has been botched.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"if a reader can pick out what’s made up and what’s real","page":"answer about the Hilary Mantel review","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
 {"_file":"larb","feature":"other: distance from the past","claim":"Kay says the past is, for him, staggeringly alien, and that writers about the past should acknowledge and work with that.","source":"Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"it’s also, for me, staggeringly alien","page":"answer about the Huxley quotation","kind":"own-words","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
 {"_file":"larb","feature":"diction (native vs latinate)","claim":"The interviewer Christine Fischer Guy writes that a reverence for language runs through everything Kay writes.","source":"Christine Fischer Guy (interviewer's framing), Los Angeles Review of Books, 14 August 2016","url":"https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/","quote":"A reverence for language runs through everything he writes.","page":"interviewer's introduction","kind":"analysis","polarity":"asserts","date":"2016-08-14","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},

 # --- Falden's Forge ---
 {"_file":"falden","feature":"point of view and distance","claim":"Eric Falden writes that Kay employs a limited omniscience that vacillates between being inside a character's head and being more objective for certain scenes.","source":"Eric Falden, 'You Should Read Tigana', Falden's Forge (Substack), 23 February 2024","url":"https://ericfalden.substack.com/p/you-should-read-tigana","quote":"Kay employs a limited omniscience that vacillates between being in","page":"section 'Writing Style'","kind":"analysis","polarity":"asserts","date":"2024-02-23","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"falden","feature":"point of view and distance","claim":"Falden writes that Kay changes narrative distance by zooming in and out of the narrative, the farther narration no less haunting for giving summary.","source":"Eric Falden, Falden's Forge (Substack), 23 February 2024","url":"https://ericfalden.substack.com/p/you-should-read-tigana","quote":"Kay changes narrative distance incredibly well, zooming in and out","page":"section 'Writing Style'","kind":"analysis","polarity":"asserts","date":"2024-02-23","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"falden","feature":"place and institution description","claim":"Falden writes that Kay lets the reader learn about the Peninsula of the Palm by living in it rather than by being spoon-fed.","source":"Eric Falden, Falden's Forge (Substack), 23 February 2024","url":"https://ericfalden.substack.com/p/you-should-read-tigana","quote":"lets the reader learn about the Palm by living in it","page":"section 'World-Building & Exposition'","kind":"analysis","polarity":"asserts","date":"2024-02-23","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"falden","feature":"place and institution description","claim":"Falden writes that it is rarely noticeable when Kay is explaining something purely for the reader's benefit, because the exposition happens together with revelations about characters.","source":"Eric Falden, Falden's Forge (Substack), 23 February 2024","url":"https://ericfalden.substack.com/p/you-should-read-tigana","quote":"purely for the reader’s benefit","page":"section 'World-Building & Exposition'","kind":"analysis","polarity":"asserts","date":"2024-02-23","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},

 # --- BrightWeavings focalization thesis ---
 {"_file":"bw-focal","feature":"civic record register","claim":"Toyryla argues the narrator of Tigana often reports what the world seems like to an average person living in that world rather than simply giving information about the world as it is.","source":"Roosa Toyryla, 'Ambiguities and Divided Loyalties: Focalization in Guy Gavriel Kay's Tigana', BA thesis, University of Helsinki, 2017 (hosted at BrightWeavings)","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"reporting what the world seems like to an average person","page":"section 'Communal Viewpoints: As Everyone Knows'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent; the thesis text sits below a long site navigation block","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"bw-focal","feature":"civic record register","claim":"Toyryla observes that general facts about the storyworld of Tigana are often presented as something that everyone knows or as circulating rumours.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"as circulating rumours","page":"section 'Communal Viewpoints: As Everyone Knows'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"bw-focal","feature":"annalist voice and deep time","claim":"Toyryla writes that narratorial focalization in Tigana often takes the form of matter-of-fact description with only minimal commentary.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"matter-of-fact description with only minimal commentary","page":"section 'Narratorial Focalization: All-seeing but Indifferent'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"bw-focal","feature":"annalist voice and deep time","claim":"Toyryla writes that the narrator of Tigana does not make strong moral judgments, denying readers a guiding voice that would tell them what is right or wrong.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"The narrator does not make strong moral judgments","page":"section 'Narratorial Focalization: All-seeing but Indifferent'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"bw-focal","feature":"consequence on a household","claim":"Toyryla shows that the shift away from the innkeeper Ettocio's perspective to the narrator's enables a matter-of-fact description of his execution.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"enables the matter-of-fact description of his execution","page":"section 'Minor Characters as Focal Characters'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"bw-focal","feature":"consequence on a household","claim":"Toyryla argues that the Ettocio passage forces readers to see what the main characters' actions cost, though the main characters probably never learn his name.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"The main characters probably never even learn Ettocio’s name","page":"section 'Minor Characters as Focal Characters'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"bw-focal","feature":"withheld information and inference","claim":"Toyryla writes that the phrase 'according to most reports later' suggests the narrator is restricting his omniscience and narrating only what people hear about the incident afterwards.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"restricting their omniscience and narrating only what people hear","page":"section 'Narratorial Focalization: All-seeing but Indifferent'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"bw-focal","feature":"other: approximate figures in a report","claim":"Toyryla notes that the narrator gives an approximate number of the dead in the Senzio massacre rather than an exact one.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"The approximate number of the dead could also point","page":"section 'Narratorial Focalization: All-seeing but Indifferent'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"bw-focal","feature":"opening sentence","claim":"Toyryla observes that the first chapter of Tigana does not claim that Duke Sandre is dead but reports that word went forth that he had died.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"the narrator does not claim that Sandre is dead","page":"section 'Communal Viewpoints: As Everyone Knows'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"bw-focal","feature":"point of view and distance","claim":"Toyryla reports that about sixty per cent of the text of Tigana has either Devin or Dianora as the focal character.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"About sixty per cent of the text has either Devin","page":"section 'Variable Internal Focalization'","kind":"measurement","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
 {"_file":"bw-focal","feature":"point of view and distance","claim":"Toyryla counts at least nineteen focal characters in Tigana besides Devin and Dianora, ranging from Alessan to an innkeeper named Ettocio.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"at least nineteen other focal characters that can be clearly","page":"section 'Variable Internal Focalization'","kind":"measurement","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
 {"_file":"bw-focal","feature":"other: minor lives as world texture","claim":"Toyryla argues that focalizing a passage through the Governor of Stevanien strengthens the illusion of a world full of other stories around the one the novel is about.","source":"Roosa Toyryla, BA thesis, University of Helsinki, 2017, hosted at BrightWeavings","url":"https://brightweavings.com/ambiguities-and-divided-loyalties-focalization-in-guy-gavriel-kays-tigana/","quote":"the illusion of there being a world full of other stories","page":"section 'Minor Characters as Focal Characters'","kind":"analysis","polarity":"asserts","date":"2017-08-05","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},

 # --- Jo Walton, A Song for Arbonne ---
 {"_file":"walton-arbonne","feature":"place and institution description","claim":"Jo Walton writes that the world of A Song for Arbonne is portrayed beautifully, in effective, evocative and memorable detail.","source":"Jo Walton, 'Provencal Fantasy: Guy Gavriel Kay's A Song for Arbonne', Tor.com, 6 August 2010","url":"https://reactormag.com/provencal-fantasy-guy-gavriel-kays-a-song-for-arbonne/","quote":"The world is portrayed beautifully, in effective, evocative and memorable detail","page":"fourth paragraph","kind":"reception","polarity":"asserts","date":"2010-08-06","routeHint":"curl with a browser user agent on reactormag.com (the tor.com URL is Cloudflare-blocked)","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"walton-arbonne","feature":"place and institution description","claim":"Walton names it a problem of A Song for Arbonne that the world is more memorable and denser than the characters, who are gossamer by comparison.","source":"Jo Walton, Tor.com, 6 August 2010","url":"https://reactormag.com/provencal-fantasy-guy-gavriel-kays-a-song-for-arbonne/","quote":"the world is more memorable and somehow denser than the characters","page":"fourth paragraph","kind":"reception","polarity":"disputes","date":"2010-08-06","routeHint":"curl with a browser user agent on reactormag.com","registerHint":"none","confidence":"high"},
 {"_file":"walton-arbonne","feature":"point of view and distance","claim":"Walton criticises A Song for Arbonne as too slight, too conventional and too distanced to carry its own weight.","source":"Jo Walton, Tor.com, 6 August 2010","url":"https://reactormag.com/provencal-fantasy-guy-gavriel-kays-a-song-for-arbonne/","quote":"too slight, too conventional, and too distanced","page":"fourth paragraph","kind":"reception","polarity":"disputes","date":"2010-08-06","routeHint":"curl with a browser user agent on reactormag.com","registerHint":"none","confidence":"high"},
 {"_file":"walton-arbonne","feature":"other: magic quantity across the oeuvre","claim":"Walton describes a trajectory away from magic across Kay's books, with Fionavar full of magic, Tigana less, Arbonne less again, and The Lions of Al-Rassan containing nothing but an accurate prophecy.","source":"Jo Walton, Tor.com, 6 August 2010","url":"https://reactormag.com/provencal-fantasy-guy-gavriel-kays-a-song-for-arbonne/","quote":"nothing but an accurate prophecy","page":"third paragraph","kind":"reception","polarity":"asserts","date":"2010-08-06","routeHint":"curl with a browser user agent on reactormag.com","registerHint":"none","confidence":"high"},

 # --- Kate Nepveu ---
 {"_file":"steelypips","feature":"point of view and distance","claim":"Kate Nepveu writes that Sailing to Sarantium shows its major plot events through multiple points of view, some dominant and accented by many minor ones.","source":"Kate Nepveu, 'Review: Sailing to Sarantium', steelypips.org, 12 May 1999 (originally posted to rec.arts.sf.written)","url":"https://www.steelypips.org/reviews/sarantium.html","quote":"shown through multiple points of view, where some dominate but","page":"paragraph beginning 'However, Crispin is not the sole focus'","kind":"reception","polarity":"asserts","date":"1999-05-12","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"steelypips","feature":"withheld information and inference","claim":"Nepveu writes that Kay's mosaic technique rewards careful reading because small details relayed in one area refer to and reflect larger ones elsewhere.","source":"Kate Nepveu, steelypips.org, 12 May 1999","url":"https://www.steelypips.org/reviews/sarantium.html","quote":"small details relayed in one area refer to and reflect","page":"paragraph beginning 'However, Crispin is not the sole focus'","kind":"reception","polarity":"asserts","date":"1999-05-12","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"steelypips","feature":"other: signalling the invented world","claim":"Nepveu identifies a throw-away line in the prologue of Sailing to Sarantium, a sandalmaker's having seen a ghost, as the first signal that the book is not a straight historical.","source":"Kate Nepveu, steelypips.org, 12 May 1999","url":"https://www.steelypips.org/reviews/sarantium.html","quote":"a throw-away line in the prologue is the first signal","page":"third paragraph","kind":"reception","polarity":"asserts","date":"1999-05-12","routeHint":"curl with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},

 # --- Speculiction ---
 {"_file":"speculiction-sts","feature":"other: proleptic aside","claim":"The Speculiction reviewer identifies as a habit of Kay's middle period numerous throwaway lines that flash forward to a later consequence.","source":"Jesse, 'Review of Sailing to Sarantium by Guy Gavriel Kay', Speculiction, 6 May 2014","url":"http://speculiction.blogspot.com/2014/05/review-of-sailing-to-sarantium-by-guy.html","quote":"there are numerous throwaway lines to the effect","page":"paragraph beginning 'Forever utilizing the patient voice'","kind":"reception","polarity":"asserts","date":"2014-05-06","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"speculiction-sts","feature":"other: proleptic aside","claim":"The Speculiction reviewer says these flash-forward throwaway lines are fewer in Sailing to Sarantium than in A Song for Arbonne and all but dry up once Crispin reaches Sarantium.","source":"Jesse, Speculiction, 6 May 2014","url":"http://speculiction.blogspot.com/2014/05/review-of-sailing-to-sarantium-by-guy.html","quote":"by the time Crispin arrives in Sarantium they all but dry up","page":"paragraph beginning 'Forever utilizing the patient voice'","kind":"reception","polarity":"disputes","date":"2014-05-06","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"medium — the reviewer treats the device's frequency as a flaw, so this is a criticism of the device rather than an endorsement"},
 {"_file":"speculiction-sts","feature":"cadence and rhythm","claim":"The Speculiction reviewer calls Kay's the patient voice of the storyteller, skipping ahead, back and around to provide a variety of entry points into each scene.","source":"Jesse, Speculiction, 6 May 2014","url":"http://speculiction.blogspot.com/2014/05/review-of-sailing-to-sarantium-by-guy.html","quote":"the patient voice of the storyteller","page":"paragraph beginning 'Forever utilizing the patient voice'","kind":"reception","polarity":"asserts","date":"2014-05-06","routeHint":"curl with a browser user agent","registerHint":"chronicle-line","confidence":"high"},

 # --- Joshua Palmatier ---
 {"_file":"walton-alter","feature":"place and institution description","claim":"Joshua Palmatier writes that Tigana taught him fantasy works because the majority of the world it is set in is contrasted against a backdrop essentially ninety per cent familiar.","source":"Joshua Palmatier, 'Altering the Familiar: Tigana by Guy Gavriel Kay', Tor.com, 6 July 2016","url":"https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","quote":"a backdrop that was essentially 90 percent familiar","page":"fourth paragraph","kind":"analysis","polarity":"asserts","date":"2016-07-06","routeHint":"Wayback raw capture https://web.archive.org/web/20221205133732id_/https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"walton-alter","feature":"place and institution description","claim":"Palmatier writes that Kay alters the familiar through all aspects of life, down to arbitrary everyday rituals, including myths, legends and superstitions.","source":"Joshua Palmatier, Tor.com, 6 July 2016","url":"https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","quote":"down to arbitrary everyday rituals","page":"paragraph beginning 'How he does is it arcane'","kind":"analysis","polarity":"asserts","date":"2016-07-06","routeHint":"Wayback raw capture 20221205133732id_","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"walton-alter","feature":"place and institution description","claim":"Palmatier says the flavour of Italy in Tigana is carried in the word structure, the place names, the characters, the gestures and the traditions rather than in the map.","source":"Joshua Palmatier, Tor.com, 6 July 2016","url":"https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","quote":"in the word structure, the place names, the characters","page":"paragraph beginning 'In Tigana'","kind":"analysis","polarity":"asserts","date":"2016-07-06","routeHint":"Wayback raw capture 20221205133732id_","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"walton-alter","feature":"other: two moons and cosmetic markers","claim":"Palmatier calls devices such as two moons or a changed landscape mere cosmetic changes, and locates Kay's craft in subtler alterations.","source":"Joshua Palmatier, Tor.com, 6 July 2016","url":"https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","quote":"these are mere cosmetic changes","page":"paragraph beginning 'How he does is it arcane'","kind":"analysis","polarity":"asserts","date":"2016-07-06","routeHint":"Wayback raw capture 20221205133732id_","registerHint":"none","confidence":"high"},
 {"_file":"walton-alter","feature":"other: where the effect lives","claim":"Palmatier says that for him the true art of Kay's work is not in the use of language but in the subtle skewing of a familiar setting.","source":"Joshua Palmatier, Tor.com, 6 July 2016","url":"https://www.tor.com/2016/07/06/altering-the-familiar-tigana-by-guy-gavriel-kay/","quote":"is not in the use of language","page":"final paragraph","kind":"analysis","polarity":"disputes","date":"2016-07-06","routeHint":"Wayback raw capture 20221205133732id_","registerHint":"none","confidence":"high"},

 # --- Bill Capossere, FantasyLiterature ---
 {"_file":"fantlit","feature":"point of view and distance","claim":"Bill Capossere describes a move between micro and macro in Written on the Dark: a tight third-person point of view for most of the story, zooming outward at times via an omniscient narrator far less bound by space or time.","source":"Bill Capossere, review of Written on the Dark, FantasyLiterature.com, May 2025","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","quote":"zoom outward via an omniscient narrator far less bound by","page":"section on Kay's style","kind":"analysis","polarity":"asserts","date":"2025-05","routeHint":"Wayback raw capture https://web.archive.org/web/20250624011037id_/https://fantasyliterature.com/reviews/written-on-the-dark/ (the live page returned an empty body)","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"fantlit","feature":"annalist voice and deep time","claim":"Capossere identifies a mode in which the zoom-out pulls way back to show a more general impact on the world, such as the Asharites' first intent to conquer Sarantium.","source":"Bill Capossere, FantasyLiterature.com, May 2025","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","quote":"to pull way, way back and show a more general impact","page":"section on Kay's style","kind":"analysis","polarity":"asserts","date":"2025-05","routeHint":"Wayback raw capture 20250624011037id_","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"fantlit","feature":"other: flash-forward over a whole life","claim":"Capossere describes a quick in-and-out flash forward tied to a character the narration has just been close to, telling in one sentence what that character would remember all his life.","source":"Bill Capossere, FantasyLiterature.com, May 2025","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","quote":"a simple, quick in and out flash forward","page":"section on Kay's style","kind":"analysis","polarity":"asserts","date":"2025-05","routeHint":"Wayback raw capture 20250624011037id_","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"fantlit","feature":"consequence on a household","claim":"Capossere says a favourite element of Kay's writing is the refusal to denote characters as lesser or minor, viewing them instead as characters in their own story.","source":"Bill Capossere, FantasyLiterature.com, May 2025","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","quote":"view them as characters in their own story","page":"paragraph on secondary characters","kind":"analysis","polarity":"asserts","date":"2025-05","routeHint":"Wayback raw capture 20250624011037id_","registerHint":"dossier-archivist","confidence":"high"},
 {"_file":"fantlit","feature":"other: structure as vignettes","claim":"Capossere writes that Written on the Dark is not a seamless narrative but more a series of situations, pausing on a time and then jumping ahead over intervening months or years.","source":"Bill Capossere, FantasyLiterature.com, May 2025","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","quote":"not a seamless narrative but more a series of situations","page":"paragraph on the novel's structure","kind":"analysis","polarity":"asserts","date":"2025-05","routeHint":"Wayback raw capture 20250624011037id_","registerHint":"chronicle-line","confidence":"high"},
 {"_file":"fantlit","feature":"other: pivot points","claim":"Capossere names as a major theme the way small decisions by people overlooked by the history books - tavern poets, bartenders, guardsmen - can have major impact.","source":"Bill Capossere, FantasyLiterature.com, May 2025","url":"https://fantasyliterature.com/reviews/written-on-the-dark/","quote":"the tavern poets, the bartenders, the guardsmen","page":"paragraph on themes","kind":"analysis","polarity":"asserts","date":"2025-05","routeHint":"Wayback raw capture 20250624011037id_","registerHint":"dossier-archivist","confidence":"high"},

 # --- Fantasy Book Review, Quill to Live ---
 {"_file":"fbr-sts","feature":"plainness and economy","claim":"The Fantasy Book Review reviewer Floresiensis writes that there is a precision, care and subtlety to each and every sentence of Sailing to Sarantium.","source":"Floresiensis, review of Sailing to Sarantium, Fantasy Book Review (undated)","url":"https://www.fantasybookreview.co.uk/Guy-Gavriel-Kay/Sailing-to-Sarantium.html","quote":"there is a precision, care and subtlety to each and every sentence","page":"first reviewer's section","kind":"reader","polarity":"asserts","date":"undated","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"medium — the page carries no date, so the observation cannot be placed in time"},
 {"_file":"quill","feature":"plainness and economy","claim":"The Quill to Live blogger writes that Kay's writing style is poetic but not too dense, so passages move without requiring hours of thought to decipher.","source":"The Quill to Live, 'The Masters Of Prose', 7 January 2016","url":"https://thequilltolive.com/2016/01/07/the-masters-of-prose/","quote":"incredibly poetic but also not too dense","page":"Guy Gavriel Kay entry","kind":"reader","polarity":"asserts","date":"2016-01-07","routeHint":"curl with a browser user agent","registerHint":"none","confidence":"high"},
]
