# -*- coding: utf-8 -*-
OLIVER_URL="https://dc.swosu.edu/mythlore/vol41/iss1/4/"
OLIVER_SRC="Matthew Oliver (Campbellsville University), 'History in the Margins: Epigraphs and Negative Space in Robin Hobb's Assassin's Apprentice', Mythlore 41.1 (Fall/Winter 2022) 45-66"
O_ROUTE="SWOSU Digital Commons PDF (dc.swosu.edu/cgi/viewcontent.cgi article=1447 context=mythlore); landing page 403s to a plain fetch, the PDF does not"
def O(feature,claim,quote,page,reg='dossier-archivist',pol='asserts',conf='high'):
    return dict(feature=feature,claim=claim,source=OLIVER_SRC,url=OLIVER_URL,quote=quote,page=page,kind='analysis',
                polarity=pol,date='2022-10',routeHint=O_ROUTE,registerHint=reg,confidence=conf,_file='oliver-mythlore.txt')

CLAIMS=[
 O('civic record register',
   "Every chapter of Assassin's Apprentice opens with a long epigraph excerpted from an in-world history of the Six Duchies.",
   "Each chapter of the novel begins with a lengthy epigraph","p. 45",'chronicle-line'),
 O('civic record register',
   "Oliver characterises the register of those in-world history epigraphs as a formal history in a distant, scholarly voice, set against the personal first-person narrative that follows.",
   "largely a formal history written in a distant, scholarly voice","p. 45",'dossier-archivist'),
 O('civic record register',
   "Oliver calls the chapter-opening history dry and impersonal, and says the personal main text feels more authoritative and satisfying than it does.",
   "the dry, impersonal, but objective history beginning the chapter","p. 57",'dossier-archivist'),
 O('place and institution description',
   "The chapter-13 epigraph describing Fitz's stepmother Patience carries no sign of the writer's own relationship to her.",
   "contains no hint of the author's relationship to her","p. 56",'dossier-archivist'),
 O('civic record register',
   "In place of personal knowledge the Patience epigraph cites testimony from her nursemaids and publicly available information.",
   "evidentiary quotes from her nursemaids and publicly available information","p. 56",'dossier-archivist'),
 O('omission as information',
   "Oliver names the novel's most striking stylistic element its continual insistence on describing what is not happening.",
   "continual insistence on describing what is not happening","p. 57",'none'),
 O('omission as information',
   "The device Oliver labels 'negative narration' works through sentences that open by saying what a character is not doing or feeling.",
   "sentences that start by telling what a character is not doing","p. 57",'none'),
 O('omission as information',
   "Negative constructions are so frequent in the novel's early chapters that scarcely a page passes without obvious examples.",
   "scarcely a page goes by without obvious examples","p. 57",'none'),
 O('omission as information',
   "Although the frequency of negative constructions falls off later, Oliver says the mode remains one of the book's predominant ones throughout.",
   "remains one of the predominant modes throughout","p. 57",'none'),
 O('register modulation',
   "When Fitz invents a prophetic vision to persuade a duchess, his sentences shift into extensive parataxis, elevated figurative language and parallelism.",
   "extensive parataxis, elevated figurative language, and parallelism","p. 59",'herald-pools'),
 O('register modulation',
   "Oliver reads that stylistic shift as marking Fitz's move from a discourse of history into a discourse of fantasy.",
   "Fitz marks his shift from a discourse of history","p. 60",'none'),
 O('register modulation',
   "Late in the novel the epigraphs take on the style of imaginative fiction in place of the style of scholarly discourse.",
   "increasingly infected by the style of imaginative fiction","p. 62",'dossier-archivist'),
 O('register modulation',
   "At the chapter-15 epigraph a poetic lyricism enters the register of the supposedly scholarly history.",
   "a poetic lyricism creeps into his style in the epigraph","p. 62",'dossier-archivist'),
 O('cadence and rhythm',
   "Oliver measures the epigraph's drift by counting its inverted-syntax sentences: two of them, alongside parataxis across sentence boundaries and listed parallel phrases.",
   "Two sentences use inverted syntax","p. 63",'dossier-archivist'),
 O('withheld information and inference',
   "A roughly seventy-page stretch of the novel is defined by the absence of a key fact that is never stated outright.",
   "marked by the absence of a key detail","p. 61",'none'),
 O('withheld information and inference',
   "At the moment Fitz's magic returns, the narration reports only what the two men are not doing and leaves what they are doing implied.",
   "we are told what they are not doing","p. 61",'none'),
 O('withheld information and inference',
   "Oliver argues that the withheld section trains the reader to see what is not there and to supply the connections.",
   "training the reader to see what is not there","p. 62",'none'),
 dict(feature='civic record register',
   claim="Farah Mendlesohn, quoted by Oliver, disputes the authority of Hobb's chapter epigraphs, calling them recollection and gossip masquerading as accurate description of the past.",
   source="Farah Mendlesohn, Rhetorics of Fantasy (Wesleyan UP, 2008) 16, quoted verbatim in Matthew Oliver, Mythlore 41.1 (2022) 63-64",
   url=OLIVER_URL,
   quote="recollection and gossip masquerading as an accurate description of the past",
   page="p. 63-64 (block quotation of Mendlesohn 16)", kind='relay', polarity='disputes', date='2022-10',
   routeHint=O_ROUTE+"; Mendlesohn primary is lending-restricted on archive.org (rhetoricsoffanta0000mend, 401 on _djvu.txt)",
   registerHint='chronicle-line', confidence='high', _file='oliver-mythlore.txt'),
]
