# -*- coding: utf-8 -*-
ET_URL="https://www.diva-portal.org/smash/get/diva2:1659740/FULLTEXT01.pdf"
ET_SRC="Stefan Ekman and Audrey Isabel Taylor, 'Between World and Narrative: Fictional Epigraphs and Critical World-Building', Journal of the Fantastic in the Arts 32.2 (2021) 244-265 (author copy in DiVA)"
ET_ROUTE="diva-portal.org refuses connections from here; Wayback raw capture https://web.archive.org/web/20231231145740id_/<url>, then pypdf text extraction"
LAG_URL="https://helda.helsinki.fi/server/api/core/bitstreams/ae370f8d-eafe-41e3-8eb9-79b245702b82/content"
LAG_SRC="Timo Lagus, 'Toward Figural Fantasy: The Representation of Consciousness in Modern American Fantasy Literature', MA thesis, University of Helsinki, 2006"
MOON_URL="https://kar.kent.ac.uk/108514/1/97moon2024maresfinal.pdf"
MOON_SRC="Emily Moon, \"'I set no limits on my love': Magic, Queerness and the Disruption of Binaries in Robin Hobb's Realm of the Elderlings\", MA by Research, University of Kent, 2024"
WIKI_URL="https://en.wikipedia.org/wiki/Farseer_trilogy"
ES_URL="https://elliottrwi.com/2021/05/19/sites-of-memory-in-robin-hobbs-realm-of-the-elderlings/"
ES_SRC="Geoffrey B. Elliott, 'Sites of Memory in Robin Hobb's Realm of the Elderlings', paper given at the 2021 International Congress on Medieval Studies (Tales after Tolkien Society session), self-published 19 May 2021"
PLOS_URL="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0126470"
PLOS_SRC="Michael C. Waumans, Thibaut Nicodeme and Hugues Bersini, 'Topology Analysis of Social Networks Extracted from Literature', PLoS ONE 10.6 (3 June 2015)"
SLAV_URL="https://www.ijcrsee.com/index.php/ijcrsee/article/view/238"
SLAV_SRC="Velina Slavova, 'Towards Emotion Recognition in Texts - A Sound-Symbolic Experiment', International Journal of Cognitive Research in Science, Engineering and Education 7.2 (2019) 41-51"
FED_URL="https://elliottrwi.com/research/hobb-bibliography/"

CLAIMS=[
 # --- Ekman & Taylor 2021: the register of world-intrinsic epigraphs (the form Hobb uses) ---
 dict(feature='civic record register',
   claim="Ekman and Taylor say the source line attached to a world-intrinsic epigraph tells the reader what text genres exist in the secondary world, along with naming customs, titles and social positions.",
   source=ET_SRC,url=ET_URL,quote="Naming customs, titles, and social positions, and what text genres exist",
   page="Function Two: Adding Details, p. 253",kind='analysis',polarity='asserts',date='2021',
   routeHint=ET_ROUTE,registerHint='chronicle-line',confidence='high',_file='ekman-taylor.txt'),
 dict(feature='civic record register',
   claim="Ekman and Taylor argue that a reader can determine a secondary world's generic makeup from the epigraph source lines alone, without reading the epigraph texts.",
   source=ET_SRC,url=ET_URL,quote="Even without reading the texts of the epigraphs, it is possible",
   page="Function Two: Adding Details, p. 253",kind='analysis',polarity='asserts',date='2021',
   routeHint=ET_ROUTE,registerHint='chronicle-line',confidence='high',_file='ekman-taylor.txt'),
 dict(feature='diction (native vs latinate)',
   claim="Ekman and Taylor read a Bakker epigraph's lexical markers - 'further argument', 'supposition', 'discourse' - as making the writing read like a philosophical treatise and implying a society that writes such treatises.",
   source=ET_SRC,url=ET_URL,quote="the writing suggests a philosophical treatise",
   page="Function Two: Adding Details, p. 252-253",kind='analysis',polarity='asserts',date='2021',
   routeHint=ET_ROUTE,registerHint='dossier-archivist',confidence='high',_file='ekman-taylor.txt'),
 dict(feature='civic record register',
   claim="Ekman and Taylor describe McKillip's chapter epigraph as written in the style of a scholarly treatise originating inside the fictional world, which sets itself up as an authoritative source.",
   source=ET_SRC,url=ET_URL,quote="The style is that of a scholarly treatise that emerges",
   page="Function Three: Adding Perspectives, p. 256",kind='analysis',polarity='asserts',date='2021',
   routeHint=ET_ROUTE,registerHint='dossier-archivist',confidence='high',_file='ekman-taylor.txt'),
 dict(feature='per-speaker register',
   claim="Ekman and Taylor say an epigraph can settle which of epigraph and main text is the more reliable account, the scholarly or scientific epigraph making the main text read as the more biased one.",
   source=ET_SRC,url=ET_URL,quote="in which the epigraph is a more objective account",
   page="Function Three: Adding Perspectives, p. 256",kind='analysis',polarity='asserts',date='2021',
   routeHint=ET_ROUTE,registerHint='chronicle-line',confidence='high',_file='ekman-taylor.txt'),
 # --- Lagus 2006 ---
 dict(feature='point of view and distance',
   claim="Lagus classifies Hobb's Ship of Magic as a pure figural narrative, formally like Martin's.",
   source=LAG_SRC,url=LAG_URL,quote="a pure figural narrative formally similar",
   page="ch. 5, p. 125",kind='analysis',polarity='asserts',date='2006',
   routeHint="helda.helsinki.fi DSpace bitstream (towardfi.pdf), extracted to text",registerHint='none',confidence='high',_file='lagus.txt'),
 dict(feature='point of view and distance',
   claim="Lagus says Hobb, like Martin, uses consonant psychonarration and empathic free indirect discourse to great effect.",
   source=LAG_SRC,url=LAG_URL,quote="uses consonant psychonarration and empathic FID to great effect",
   page="ch. 5, p. 125",kind='analysis',polarity='asserts',date='2006',
   routeHint="helda.helsinki.fi DSpace bitstream (towardfi.pdf), extracted to text",registerHint='none',confidence='high',_file='lagus.txt'),
 dict(feature='point of view and distance',
   claim="Lagus finds Ship of Magic's internal focalization immersive and often pronounced.",
   source=LAG_SRC,url=LAG_URL,quote="Its internal focalization is immersive and often pronounced",
   page="ch. 5, p. 125",kind='analysis',polarity='asserts',date='2006',
   routeHint="helda.helsinki.fi DSpace bitstream (towardfi.pdf), extracted to text",registerHint='none',confidence='high',_file='lagus.txt'),
 dict(feature='consequence on a household',
   claim="To exemplify Hobb's figural perspectivism Lagus reprints a domestic bedside passage in which the trader matriarch Ronica Vestrit, nursing her dying husband, weighs what to do about an indentured servant.",
   source=LAG_SRC,url=LAG_URL,quote="Sitting by her dying husband's bedside, Ronica Vestrit, the matriarch",
   page="ch. 5, pp. 126-127 (block quotation from Ship of Magic)",kind='analysis',polarity='applies',date='2006',
   routeHint="helda.helsinki.fi DSpace bitstream (towardfi.pdf), extracted to text",registerHint='none',
   confidence='medium: Lagus chose the passage to illustrate focalization, not household economy; the household content is mine to observe',_file='lagus.txt'),
 # --- Moon 2024 ---
 dict(feature='annalist voice and deep time',
   claim="Moon describes the older narrating Fitz as a historian who keeps getting distracted by his own role in the history.",
   source=MOON_SRC,url=MOON_URL,quote="that of a historian getting distracted by their own role",
   page="ch. 2, p. 55",kind='analysis',polarity='asserts',date='2024',
   routeHint="kar.kent.ac.uk PDF, extracted to text",registerHint='chronicle-line',confidence='high',_file='moon-kent.txt'),
 dict(feature='per-speaker register',
   claim="Moon reads the sudden appearance and disappearance of quotation marks around a pronoun as the seam between the child Fitz's usage and the older narrator's.",
   source=MOON_SRC,url=MOON_URL,quote="the abrupt addition and disappearance of quotation marks",
   page="ch. 3, p. 88",kind='analysis',polarity='asserts',date='2024',
   routeHint="kar.kent.ac.uk PDF, extracted to text",registerHint='none',confidence='high',_file='moon-kent.txt'),
 # --- Wikipedia relaying Mandala 2010 ---
 dict(feature='place and institution description',
   claim="Susan Mandala, as relayed by Wikipedia, holds that Hobb writes the fantastic as an unquestioned, familiar part of the setting, producing an illusion of familiarity for the reader.",
   source="Wikipedia, 'Farseer trilogy', Style section, relaying Susan Mandala, Language in Science Fiction and Fantasy: The Question of Style (Continuum, 2010) 100-102",
   url=WIKI_URL,quote="casts the fantastic as an unquestioned, familiar aspect of the setting",
   page="Style section",kind='relay',polarity='asserts',date='2026-09 (article revision as fetched)',
   routeHint="live en.wikipedia.org fetch; Mandala primary unavailable (not on archive.org, no open copy found)",
   registerHint='dossier-archivist',confidence='medium: relay, primary not reached',_file='wiki-farseer-live.txt'),
 dict(feature='register modulation',
   claim="Mandala, relayed by Wikipedia, observes that Hobb's narration of Fitz's first shared dream with a dog stays lexically coherent across the human and the animal parts.",
   source="Wikipedia, 'Farseer trilogy', Style section, relaying Susan Mandala, Language in Science Fiction and Fantasy (2010) 101-102",
   url=WIKI_URL,quote="the narration matches how he experiences the dream",
   page="Style section",kind='relay',polarity='asserts',date='2026-09 (article revision as fetched)',
   routeHint="live en.wikipedia.org fetch",registerHint='none',confidence='medium: relay, primary not reached',_file='wiki-farseer-live.txt'),
 dict(feature='terminology consistency',
   claim="When the Skill is first named, the narrative does not explain the term, treating its meaning as known inside the world.",
   source="Wikipedia, 'Farseer trilogy', Style section, relaying Susan Mandala, Language in Science Fiction and Fantasy (2010) 102",
   url=WIKI_URL,quote="the narrative does not address the term directly",
   page="Style section",kind='relay',polarity='asserts',date='2026-09 (article revision as fetched)',
   routeHint="live en.wikipedia.org fetch",registerHint='dossier-archivist',confidence='medium: relay, primary not reached',_file='wiki-farseer-live.txt'),
 dict(feature='naming and forms of address',
   claim="Mandala, relayed by Wikipedia, notes that Fitz describes his own family in the same terms he uses for strangers, his grandfather becoming 'the tall man' and his mother 'a voice'.",
   source="Wikipedia, 'Farseer trilogy', Style section, relaying Susan Mandala, Language in Science Fiction and Fantasy (2010) 128-130",
   url=WIKI_URL,quote="Fitz describes his immediate family in the same terms as the",
   page="Style section",kind='relay',polarity='asserts',date='2026-09 (article revision as fetched)',
   routeHint="live en.wikipedia.org fetch",registerHint='dossier-archivist',confidence='medium: relay, primary not reached',_file='wiki-farseer-live.txt'),
 dict(feature='civic record register',
   claim="Wikipedia's Farseer article describes the chapter-prefacing excerpts as short memoirs narrating a fictional history of the setting, and calls them unreliable narratives.",
   source="Wikipedia, 'Farseer trilogy', Style section",
   url=WIKI_URL,quote="short memoirs prefacing each chapter that narrate a fictional history",
   page="Style section",kind='relay',polarity='asserts',date='2026-09 (article revision as fetched)',
   routeHint="live en.wikipedia.org fetch",registerHint='chronicle-line',confidence='high',_file='wiki-farseer-live.txt'),
 # --- Elliott 2021 ---
 dict(feature='consequence on a household',
   claim="Elliott calls attention to the all-too-human factors of avarice and pettiness a hallmark of Hobb's writing, citing the looting of her memorial city by merchants.",
   source=ES_SRC,url=ES_URL,quote="the all-too-human factors of avarice and pettiness",
   page="section 'The Typical Sites of Memory'",kind='analysis',polarity='asserts',date='2021-05-19',
   routeHint="live elliottrwi.com fetch",registerHint='dossier-archivist',confidence='high',_file='elliott-sites.txt'),
 dict(feature='consequence on a household',
   claim="Elliott reports that in Hobb's Bingtown a family buying a liveship commonly takes a multi-generational loan secured by potential marriages.",
   source=ES_SRC,url=ES_URL,quote="a multi-generational loan, secured by potential marriages, to purchase one",
   page="section 'The Strange Sites of Memory: The Liveships'",kind='analysis',polarity='asserts',date='2021-05-19',
   routeHint="live elliottrwi.com fetch",registerHint='dossier-archivist',confidence='high',_file='elliott-sites.txt'),
 dict(feature='place and institution description',
   claim="Elliott notes that Hobb introduces the ruined city Kelsingra through what Fitz fails to perceive there.",
   source=ES_SRC,url=ES_URL,quote="he finds it empty, perceiving no signs of life around him",
   page="section 'The Typical Sites of Memory'",kind='analysis',polarity='asserts',date='2021-05-19',
   routeHint="live elliottrwi.com fetch",registerHint='dossier-archivist',confidence='high',_file='elliott-sites.txt'),
 # --- Waumans 2015 (measurement) ---
 dict(feature='stylometry',
   claim="Waumans, Nicodeme and Bersini's corpus of forty-seven best-selling novels includes seven of Hobb's - the three Liveship Traders and four Rain Wild Chronicles books.",
   source=PLOS_SRC,url=PLOS_URL,quote="the forty-seven best-selling books",
   page="Introduction",kind='measurement',polarity='applies',date='2015-06-03',
   routeHint="live journals.plos.org fetch",registerHint='none',confidence='high',_file='plos-topology.txt'),
 dict(feature='stylometry',
   claim="The study proposes dialogue spacing and alias-network topology as features that may identify an author's style.",
   source=PLOS_SRC,url=PLOS_URL,quote="relevant in the identification of the author's style like the dialog",
   page="Conclusion and future work",kind='measurement',polarity='asserts',date='2015-06-03',
   routeHint="live journals.plos.org fetch",registerHint='none',confidence='high',_file='plos-topology.txt'),
 dict(feature='stylometry',
   claim="In the study's hierarchical clustering the Rain Wild Chronicles books cluster together, which the authors treat as an absence of the style fluctuation they see in a scattered series.",
   source=PLOS_SRC,url=PLOS_URL,quote="The dendrogram shows a good clustering of certain series",
   page="Results, Fig 21",kind='measurement',polarity='asserts',date='2015-06-03',
   routeHint="live journals.plos.org fetch",registerHint='none',confidence='high',_file='plos-topology.txt'),
 # --- Slavova 2019 (measurement) ---
 dict(feature='stylometry',
   claim="Slavova's sound-symbolic experiment selected twenty roughly one-page passages, drawn from works by seven authors including Robin Hobb.",
   source=SLAV_SRC,url=SLAV_URL,quote="Twenty approximately one-page-long passages of text",
   page="Materials and Methods",kind='measurement',polarity='applies',date='2019',
   routeHint="ijcrsee.com download link returns HTML; the PDF came from dialnet.unirioja.es/descarga/articulo/7136787.pdf",
   registerHint='none',confidence='high',_file='slavova.txt'),
 # --- Fedwren Project relays ---
 dict(feature='place and institution description',
   claim="Elliott's annotation reports that Shropshire's geography thesis codes Hobb's landscape passages as performing five functions, among them establishing verisimilitude, criticising social systems and denoting privilege and relative power.",
   source="Geoffrey B. Elliott, annotating Catherine Ann Shropshire, 'The Importance of Geographic Realism in Genre Fiction' (MS thesis, Oklahoma State University, 2019), in The Fedwren Project: A Robin Hobb Annotated Bibliography (last updated 18 May 2026)",
   url=FED_URL,quote="establishing verisimilitude, criticizing social systems, denoting privilege and relative power",
   page="entry: Shropshire, Catherine Ann",kind='relay',polarity='asserts',date='2026-05-18',
   routeHint="live elliottrwi.com fetch; the Shropshire thesis itself is not in SHAREOK's search index",
   registerHint='dossier-archivist',confidence='medium: relay, primary not reached',_file='fedwren.txt'),
 dict(feature='place and institution description',
   claim="Elliott's annotation reports that Crane and Fletcher read the Liveship Traders novels as inverting the usual depiction of land as busy and sea as empty.",
   source="Geoffrey B. Elliott, annotating Ralph Crane and Lisa Fletcher, 'An Imaginary Water World: Robin Hobb's The Liveship Traders Trilogy' (2017), in The Fedwren Project",
   url=FED_URL,quote="inverting the usual depiction of land as busy and sea",
   page="entry: Crane, Ralph, and Lisa Fletcher",kind='relay',polarity='asserts',date='2026-05-18',
   routeHint="live elliottrwi.com fetch",registerHint='dossier-archivist',confidence='medium: relay, primary not reached',_file='fedwren.txt'),
 dict(feature='point of view and distance',
   claim="Elliott's annotation records that Mendlesohn's taxonomy places Hobb's Elderlings corpus as an example of portal-quest fantasy.",
   source="Geoffrey B. Elliott, annotating Farah Mendlesohn, Rhetorics of Fantasy (2008), in The Fedwren Project",
   url=FED_URL,quote="offering an example of the portal-quest fantasy in the Elderlings corpus",
   page="entry: Mendlesohn, Farah",kind='relay',polarity='asserts',date='2026-05-18',
   routeHint="live elliottrwi.com fetch",registerHint='none',confidence='medium: relay, primary not reached',_file='fedwren.txt'),
]
