# -*- coding: utf-8 -*-
SOURCES=[
 dict(title="The Fedwren Project: A Robin Hobb Annotated Bibliography (Geoffrey B. Elliott)",url="https://elliottrwi.com/research/hobb-bibliography/",kind="analysis",substantive=True,date="2026-05-18",route="live fetch"),
 dict(title="Matthew Oliver, 'History in the Margins: Epigraphs and Negative Space in Robin Hobb's Assassin's Apprentice', Mythlore 41.1 (2022) 45-66",url="https://dc.swosu.edu/mythlore/vol41/iss1/4/",kind="analysis",substantive=True,date="2022-10",route="SWOSU Digital Commons PDF (landing page 403s; PDF fetches)"),
 dict(title="Stefan Ekman and Audrey Isabel Taylor, 'Between World and Narrative: Fictional Epigraphs and Critical World-Building', JFA 32.2 (2021) 244-265",url="https://www.diva-portal.org/smash/get/diva2:1659740/FULLTEXT01.pdf",kind="analysis",substantive=True,date="2021",route="Wayback raw capture 20231231145740id_ (diva-portal refuses connections here)"),
 dict(title="Timo Lagus, 'Toward Figural Fantasy', MA thesis, University of Helsinki, 2006",url="https://helda.helsinki.fi/server/api/core/bitstreams/ae370f8d-eafe-41e3-8eb9-79b245702b82/content",kind="analysis",substantive=True,date="2006",route="helda DSpace bitstream PDF"),
 dict(title="Emily Moon, 'I set no limits on my love': Magic, Queerness and the Disruption of Binaries in Robin Hobb's Realm of the Elderlings, MA by Research, University of Kent, 2024",url="https://kar.kent.ac.uk/108514/1/97moon2024maresfinal.pdf",kind="analysis",substantive=True,date="2024",route="kar.kent.ac.uk PDF"),
 dict(title="Wikipedia, 'Farseer trilogy' (Style section, relaying Susan Mandala 2010, Clute, Langford, Mendlesohn)",url="https://en.wikipedia.org/wiki/Farseer_trilogy",kind="relay",substantive=True,date="2026-09 revision",route="live fetch"),
 dict(title="Geoffrey B. Elliott, 'Sites of Memory in Robin Hobb's Realm of the Elderlings' (ICMS 2021 paper)",url="https://elliottrwi.com/2021/05/19/sites-of-memory-in-robin-hobbs-realm-of-the-elderlings/",kind="analysis",substantive=True,date="2021-05-19",route="live fetch"),
 dict(title="Waumans, Nicodeme and Bersini, 'Topology Analysis of Social Networks Extracted from Literature', PLoS ONE 10.6 (2015)",url="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0126470",kind="measurement",substantive=True,date="2015-06-03",route="live fetch"),
 dict(title="Velina Slavova, 'Towards Emotion Recognition in Texts - A Sound-Symbolic Experiment', IJCRSEE 7.2 (2019) 41-51",url="https://www.ijcrsee.com/index.php/ijcrsee/article/view/238",kind="measurement",substantive=True,date="2019",route="PDF via dialnet.unirioja.es/descarga/articulo/7136787.pdf (journal download link serves HTML)"),
]

SOURCES += [
 dict(title="Polina Tkach and Maryna Volkova, \"Robin Hobb's 'The World of the Elderlings' Onomasticon: The Structural and Functional Significance of Charactonyms\", Perspectives and Innovations of Science 5(47) (2026) 372-381",url="https://perspectives.pp.ua/index.php/vno/article/download/46053/46079",kind="analysis",substantive=True,date="2026",route="open-access PDF, found via OpenAlex search"),
 dict(title="Petra Srsic, 'Motherhood, Disability, and Rebellion: Constructing the Mother in Hobb's Liveship Traders Trilogy', Studia Anglica Resoviensia 22 (2025)",url="https://journals.ur.edu.pl/SAR/article/download/11148/11875",kind="analysis",substantive=True,date="2025",route="open-access PDF, found via OpenAlex search"),
 dict(title="Geoffrey B. Elliott, 'Searching the Hoard in Words like Coins' (sample conference paper)",url="http://gelliottteaching.blogspot.com/2013/07/sample-conference-length-paper.html",kind="analysis",substantive=True,date="2013-07-29",route="live blogspot fetch"),
 dict(title="Wikipedia, 'Liveship Traders' (Style section, relaying Borowska-Szerszun 2019)",url="https://en.wikipedia.org/wiki/Liveship_Traders",kind="relay",substantive=True,date="2026-09 revision",route="live fetch"),
 dict(title="OpenAlex record for Borowska-Szerszun, Extrapolation 60.1 (2019) - abstract only",url="https://api.openalex.org/works/doi:10.3828/extr.2019.2",kind="analysis",substantive=True,date="2019",route="OpenAlex API (full text closed at Liverpool UP)"),
 dict(title="OpenAlex record for Peter Melville, 'Queerness and Homophobia in Robin Hobb's Farseer Trilogies', Extrapolation 59.3 (2018) - abstract only, no prose-style content",url="https://api.openalex.org/works/doi:10.3828/extr.2018.17",kind="analysis",substantive=False,date="2018",route="OpenAlex API"),
 dict(title="OpenAlex record for Helen Young, 'Critiques of Colonialism in Robin Hobb's Soldier Son Trilogy', Extrapolation 55.1 (2014) - abstract only, no prose-style content",url="https://api.openalex.org/works/doi:10.3828/extr.2014.4",kind="analysis",substantive=False,date="2014",route="OpenAlex API"),
 dict(title="Geoffrey B. Elliott, \"Another Update to 'Moving beyond Tolkien's Medievalism'\" (2026 ICMS paper)",url="https://elliottrwi.com/2026/05/18/another-update-to-moving-beyond-tolkiens-medievalism/",kind="analysis",substantive=True,date="2026-05-18",route="live fetch"),
 dict(title="Velina Slavova, 'Emotional Valence Coded in the Phonemic Content', Cybernetics and Information Technologies 20.2 (2020)",url="https://www.sciendo.com/pdf/10.2478/cait-2020-0012",kind="measurement",substantive=True,date="2020",route="sciendo PDF"),
 dict(title="Lepukhova and Mishchur, 'Linguostylistics of the literary translation of fantasy', Perspectives and Innovations of Science 5(47) (2026) 1238-1251 - cites Hobb only in its bibliography",url="https://perspectives.pp.ua/index.php/vno/article/download/46118/46144",kind="analysis",substantive=False,date="2026",route="open-access PDF"),
 dict(title="Chandarana and Choudhary, 'Employment of the Tolkienian Tools in the Nuanced Study of Robin Hobb's The Farseer Trilogy', Towards Excellence 14.2 (2022) - abstract page only, applies Tolkien's Recovery/Escape/Eucatastrophe, no prose-style content",url="https://doi.org/10.37867/te140290",kind="analysis",substantive=False,date="2022",route="live fetch of the journal page"),
]
