import json
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/kay-03.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-kay-i441-485.json"
chunk=json.load(open(src))
V=[
 (441,"VERIFIED_VERBATIM","That kind of gap is very fertile ground for a novelist","Live fetch, Clarkesworld issue 117 (June 2016), Chris Urie. Page: 'fascinated by the vast gulf between how the Uskoks were seen by (say) Venice and Ragusa/Dubrovnik, and how they viewed and understood themselves... That kind of gap is very fertile ground for a novelist.' Every limb present."),
 (442,"VERIFIED_VERBATIM","I like finding corners of history that have been under-explored","Live fetch, same Clarkesworld answer on the Uskoks, verbatim sentence."),
 (447,"VERIFIED_VERBATIM","I am drawn as a reader to intelligent characters","Live fetch, brightweavings.com/patrick (Interview with Patrick St-Denis), answer on extraordinary individuals: 'I am drawn as a reader to intelligent characters, I get irritated if I feel too much smarter than the characters (unless that's being done with purpose, and it can be).' All three limbs present."),
 (450,"VERIFIED_VERBATIM","Emotion is often conveyed by what is not said.","Live fetch, Chris McBean, posted December 24 2025, section 'Dialogue as character and culture'. Sentence appears verbatim."),
 (456,"VERIFIED_VERBATIM","make the world be as my characters believe it to be","Live fetch, LARB 14 Aug 2016, Christine Fischer Guy. Answer to 'How else does the fantastic serve your purposes?': 'What the fantastic lets me do... is make the world be as my characters believe it to be.'"),
 (457,"VERIFIED_VERBATIM","it removes that smugness from the reader","Live fetch, same LARB answer: 'there's a slightly smug patronizing attitude that kicks in' about the past, and 'The strength of this, for me, is enormous, because it removes that smugness from the reader who's willing to go there.' Both limbs present."),
 (458,"VERIFIED_VERBATIM","The two moons say, We're not here","Live fetch, LARB. Interviewer: 'you're setting the rules of engagement? So your reader knows you're not talking about Justinian himself?' Kay: 'That's right. That's also one of the reasons I've used two moons in several of the books. The two moons say, We're not here.' The 'signal to the reader' limb rests on that exchange."),
 (459,"VERIFIED_VERBATIM","if a reader can pick out what's made up and what's real, you've botched your storytelling","Live fetch, LARB, answer to the question quoting Kay's Bring Up the Bodies (Hilary Mantel) review. Verbatim."),
 (460,"VERIFIED_VERBATIM","it's also, for me, staggeringly alien","Live fetch, LARB, answer to the Aldous Huxley quotation: 'The past is sometimes refreshingly different, but it's also, for me, staggeringly alien. I think it's important for people writing about the past to acknowledge and work with that.' Both limbs present."),
 (461,"VERIFIED_VERBATIM","A reverence for language runs through everything he writes.","Live fetch, LARB, interviewer's introduction ('Kay and I met in Toronto in early June...'), byline Christine Fischer Guy, August 14 2016. Verbatim."),
 (473,"VERIFIED_VERBATIM","The approximate number of the dead could also point in the same direction","Live fetch, brightweavings hosting of Roosa Toyryla's 2017 University of Helsinki bachelor's thesis (page states: 'This is a bachelor's thesis by Roosa Toyryla, written at the University of Helsinki, Finland. 2017.'). Section 'Narratorial Focalization: All-seeing but Indifferent'. Quoted novel passage gives 'some thirty or forty Senzians'; thesis adds 'the exact number of casualties does not seem to be of great importance'. Note: the thesis calls the Senzio incident a 'bloody, to-the-death melee' / slaughter, not a 'massacre' - the claim's own label, not a separate factual limb."),
 (477,"VERIFIED_VERBATIM","it strengthens the illusion of there being a world full of other stories","Live fetch, same thesis, section 'Minor Characters as Focal Characters: Less Important People?': 'The Governor's experience is not essential to the story, but it strengthens the illusion of there being a world full of other stories around the one the novel is about.' Governor of Stevanien named as the focal character earlier in the same section."),
 (481,"VERIFIED_VERBATIM","Fionavar is full of magic, Tigana has somewhat less, Arbonne has less again","Live fetch, reactormag (Tor.com) reprint, By Jo Walton, Published on August 6, 2010: 'This is also a trajectory away from magic - Fionavar is full of magic, Tigana has somewhat less, Arbonne has less again, and The Lions of Al-Rassan has nothing but an accurate prophecy.' Every limb present; the sentence sits in the second body paragraph rather than the third (locator only)."),
 (484,"VERIFIED_VERBATIM","a throw-away line in the prologue is the first signal","Live fetch, steelypips.org, 'Copyright May 12, 1999 by Kate Nepveu': '...a throw-away line in the prologue is the first signal that this is not a \"straight\" historical:' followed by the block quote of Fotius the sandalmaker having seen a ghost. All limbs present."),
 (485,"VERIFIED_VERBATIM","there are numerous throwaway lines to the effect","Live fetch, Speculiction, Tuesday May 6 2014, posted by Jesse, paragraph beginning 'Forever utilizing the patient voice of the storyteller': 'As is also Kay's habit in the middle stage of his oeuvre, there are numerous throwaway lines to the effect \"Later, he, too, would have cause to be privately grateful - amid chaos - that a wager had not taken place that day.\"' The flash-forward limb is carried by that example."),
]
verdicts=[{"index":i,"verdict":v,"trueWording":t,"note":n} for i,v,t,n in V]
idx=[c["index"] for c in chunk["claims"]]
assert idx==[x[0] for x in V], (idx,[x[0] for x in V])
json.dump({"name":"kay","chunk":3,"claims":chunk["claims"],"verdicts":verdicts},open(out,"w"),indent=1,ensure_ascii=False)
print("wrote",out)
