import json
chunk=json.load(open('/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/dnd-36.json'))
V="VERIFIED_VERBATIM"
verdicts=[
{"index":694,"verdict":V,"trueWording":"It doesn't just matter what gets told, it also matters how it gets told.","note":"Raw page fetched (HTTP 200, browser UA). Quote exact in section 'The Keep on the Borderlands without The Keep on the Borderlands'. Byline 'Melan'; sidebar links a 'melan-gabor-lux-bibliography' page, confirming Melan = Gabor Lux. Context is adventures/game texts, so 'how an adventure is told' is supported."},
{"index":695,"verdict":V,"trueWording":"In old-school gaming, Ultra-Minimalism is stripping games of their flavour, depth and inner complexity.","note":"Quote exact. Page says 'stripping games of' rather than 'out of game texts'; the essay's subject throughout is modules and rulesets, so the limb holds. Locator drift only: the sentence sits in the 'Know your enemy' section, not the opening."},
{"index":696,"verdict":V,"trueWording":"These things, even if technically 'superfluous' for specific, individual encounters, give game materials a voice.","note":"Quote exact. 'These things' resolves in the preceding sentence to Gygaxian prose, Bob Bledsaw's quirky humour and M.A.R. Barker's dry wit, i.e. stylistic elements; 'technically superfluous for specific, individual encounters' and 'sticks in our imagination' both on the page. Locator section correct."},
{"index":697,"verdict":V,"trueWording":"Hommlet draws the portrait of an idyllic rural community by spending much of its time talking about random details.","note":"Quote exact and every limb present verbatim: 'The Village of Hommlet draws the portrait of an idyllic rural community by spending much of its time talking about random details that don't really matter in an adventure.' Locator 'Know your enemy' is correct."},
{"index":698,"verdict":V,"trueWording":"Layout wizardry and graphical design ... vastly improve accessibility, but it doesn't replace style.","note":"Quote exact (curly apostrophe matches). Full sentence: 'Layout wizardry and graphical design can make GMing flow better, and vastly improve accessibility, but it doesn't replace style.' Both limbs supported; locator section correct."},
{"index":699,"verdict":V,"trueWording":"the larger PF and 5e publishers ... a bloated, lumbering mess full of encounters which read well but play terribly","note":"Raw page fetched (HTTP 200). Quote exact. Page writes 'larger PF and 5e publishers'; PF is Pathfinder. The read/play contrast is explicit ('may pass as interesting bog reading, but put them on the table')."},
{"index":700,"verdict":V,"trueWording":"a slogan pioneered by T. Foster - 'Creativity aid, not creativity replacement'","note":"Quote exact. Page: 'I want to return to a slogan pioneered by T. Foster', which supports 'revives'. Applied to RPG books/supplements ('These mottoes articulate something about the flexibility of good game materials'), supporting the 'published game text' limb. Page also credits Bob Bledsaw with the original point."},
{"index":701,"verdict":V,"trueWording":"What such a synthesis requires is a skillful application of the principle of economy.","note":"Raw page fetched (HTTP 200). Quote exact, in the section headed 'A Via Media' (= middle way), which explicitly synthesises the maximalist and minimalist schools set out earlier. Byline on page: Tad Davis, December 5, 2013, ars phantasia."},
{"index":702,"verdict":V,"trueWording":"these descriptions tend to take up too much time and bore players to tears","note":"Quote exact. Reported, not asserted: 'Others have observed that the minimalist approach also has three advantages over its more ponderous rival ... Third, in particular the absence of boxed descriptions meant to be read aloud to players...'. Locator drift only: the sentence closes the section just before 'Assessing the Two Approaches'."},
{"index":703,"verdict":V,"trueWording":"I am also not convinced that we should completely eliminate the boxed text ... format.","note":"Quote exact in 'Assessing the Two Approaches'. The valuing limb is explicit in the next sentence: 'they still strike me as a useful way of partitioning off information specifically to be given to the players.'"},
{"index":704,"verdict":V,"trueWording":"As visually well laid out as exhibit A is, navigating the walls of text takes time.","note":"Quote exact. The 'even when well laid out' limb is the same sentence's concessive clause. Same section as the locator states."},
{"index":705,"verdict":V,"trueWording":"Short description (one to two sentences), highlighting the 5 senses.","note":"Raw page fetched (HTTP 200). Quote exact, and it is the first line of the key template under the heading 'The Key'. Byline: 'Published by cygnus on November 30, 2023', The Lady and Tiger. Note the running prose hedges slightly - 'tries to touch on a few of the senses' - while the template says 5."},
{"index":706,"verdict":V,"trueWording":"focusing on what the characters can immediately perceive helps to ... avoid rambling boxed text","note":"Quote exact. The page hedges where the claim does not: 'helps to both A) avoid rambling boxed text and, B) quickly identify key room elements', versus the claim's 'is what keeps'. Substance of the single asserted limb is supported."},
{"index":707,"verdict":V,"trueWording":"a mish-mash of Courtney's keying style in Hack & Slash: On Set Design and the Old-School Essentials house style for adventure writing","note":"Quote exact, and the 'one of two models' limb is supported by the sentence naming exactly two sources for the rewritten key format."},
{"index":708,"verdict":V,"trueWording":"there's one thing I really love about the delve format: Putting everything you need to run an encounter area in the description of the encounter area","note":"Raw page fetched (HTTP 200). Quote exact, in the section headed 'ISOLATED ENCOUNTERS'. Page byline The Alexandrian, January 10th 2011, Justin Alexander. Page hedges with 'Conceptually' and goes on to name two problems with the format in practice; the claim's limb is only about what he loves, so it holds."},
]
out={"name":"dnd","chunk":36,"claims":chunk["claims"],"verdicts":verdicts}
p='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-dnd-i694-708.json'
json.dump(out,open(p,'w',encoding='utf-8'),indent=1,ensure_ascii=False)
d=json.load(open(p,encoding='utf-8'))
print('claims',len(d['claims']),'verdicts',len(d['verdicts']))
print('indices match:', [c['index'] for c in d['claims']]==[v['index'] for v in d['verdicts']])
