# -*- coding: utf-8 -*-
import json, os
D = os.path.dirname(os.path.abspath(__file__))

CK = "https://arxiv.org/html/2409.14509v3"
MO = "https://www.oneusefulthing.org/p/choosing-to-stay-human"
GS = "https://www.abcbranddesign.com/blog/ai-can-t-give-you-good-taste"
GW = "https://www.itsnicethat.com/articles/elizabeth-goodspeed-designers-who-write-creative-industry-020426"

sourcesRead = [
 {"title":"Tuhin Chakrabarty, Philippe Laban et al. (Salesforce AI Research / Columbia), \"Can AI writing be salvaged? Mitigating Idiosyncrasies and Improving Human-AI Alignment in the Writing Process through Edits\", arXiv:2409.14509v3","url":CK,"kind":"measurement","substantive":True,"date":"2024-09-26","route":"bibliography chase from the Baumler post-editing paper; arXiv HTML fetched with curl and a browser UA"},
 {"title":"Ethan Mollick, \"Choosing to Stay Human\", One Useful Thing","url":MO,"kind":"analysis","substantive":True,"date":"2026-05-26","route":"post URL recovered from https://www.oneusefulthing.org/sitemap/2026 (the /archive page is JS-only); direct curl with browser UA"},
 {"title":"Elizabeth Goodspeed, \"AI Can't Give You Good Taste\" (It's Nice That column, reproduced on ABC Brand/Design)","url":GS,"kind":"relay","substantive":True,"date":"undated on the relay page; the relay states it originally appeared on It's Nice That","route":"the original It's Nice That URL could not be recovered (session web-search budget exhausted; the relay does not carry the source link), so the column was read on the reproducing page and is treated as a relay"},
 {"title":"Elizabeth Goodspeed, \"on why design writing needs designers writing\", It's Nice That","url":GW,"kind":"analysis","substantive":False,"date":"2026-04-02","route":"live page is JS-rendered; read via Wayback raw capture 20260715020203id_. Read in full: the piece argues for designers writing about design and makes no claim about generated prose, so no claim is drawn from it"},
]

claims = [
 # ---- CHAKRABARTY: what a human editor sees first ----
 {"feature":"other: what a human editor sees first","claim":"Chakrabarty and colleagues hired professional writers to edit LLM-generated paragraphs and found the writers agree on undesirable idiosyncrasies in LLM-generated text, which the authors formalised into a seven-category taxonomy.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"these writers agree on undesirable idiosyncrasies in LLM-generated text","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3, direct curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet and Llama-3.1-70b; data collected for the September 2024 preprint; register: literary fiction and creative non-fiction paragraphs"},
 {"feature":"other: what a human editor sees first","claim":"The seven edit categories the study's professional writers converged on are Cliche, Unnecessary/Redundant Exposition, Purple Prose, Poor Sentence Structure, Lack of Specificity and Detail, Awkward Word Choice and Phrasing, and Tense Inconsistency.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"","page":"Table 3 and Section 4.4, Final Taxonomy for Fine-Grained Edits","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3; the seven names appear as section headings 4.4.1 to 4.4.7 and as the Final Category column of Table 3","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"other: what a human editor sees first","claim":"The LAMP corpus consists of 1,057 LLM-generated paragraphs edited by professional writers according to that taxonomy.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"1,057 LLM-generated paragraphs edited by professional writers","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"other: what a human editor sees first","claim":"Eighteen professional writers produced 8035 fine-grained edits on those responses.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"resulting in 8035 fine-grained edits","page":"Section 1, Introduction","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"steerability","claim":"The models in that study were explicitly prompted to be original and were instructed not to use ornamental language and to focus on nuance, simplicity, and subtext, yet their output still drew the seven categories of expert edits.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"Do not use ornamental language and focus on nuance, simplicity, and subtext","page":"Section 4.1, Collecting Instruction and Response Pairs (prompt quoted in text; full prompt in Appendix A Table 13)","kind":"measurement","polarity":"asserts (a limit of prompt-level steerability)","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"discourse-level tells","claim":"Of the 50 most common part-of-speech templates in the study's LLM-generated responses, 15 templates do not occur as frequently in the original human-written seed paragraphs.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"15 templates do not occur as frequently in original human-written seed paragraphs","page":"Section 5.3, Are there any specific stylistic idiosyncrasies in LLM generated responses?","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"lexical tells","claim":"In the study's Table 8 the syntactic pattern DT NN IN NN CC, represented by sequences such as a mix of pride and or a sense of wonder and, was edited by the writers 54% of the times it occurred.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"","page":"Table 8, first row (Syntactic Pattern DT NN IN NN CC, % of Times Edited 54%)","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3; Table 8 renders as a flat sequence of cells in the HTML, pattern then percentage then representative sequences","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"lexical tells","claim":"The study reports that the word unspoken occurs in about 15% of the LLM-generated responses in the LAMP corpus.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"a word like unspoken occurs in about 15% of LLM-generated responses","page":"Section 5.3, discussion of Figure 6","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"lexical tells","claim":"The study reports that the phrases weight of, sense of and mix of occur very rarely or not at all in the human-written seed paragraphs while occurring frequently in the LLM-generated responses.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"","page":"Section 5.3, discussion of Figure 6","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3; the sentence renders with the phrases in italic markup, so a contiguous verbatim span is unreliable and the quote is left blank","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"homogenisation","claim":"The study calls it the most surprising finding that all three LLMs generate the same idiosyncratic words and phrases, and suggests overlap in instruction tuning data across model families or training on another model's synthetic output.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"all 3 LLMs generate these idiosyncratic words/phrases","page":"Section 5.3","kind":"measurement","polarity":"asserts a mechanism","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet and Llama-3.1-70b compared directly, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"model era drift","claim":"The study found that none of the three LLMs it used outperformed each other in terms of writing quality, which it reads as common limitations across model families.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"none of the LLMs used in our study","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o vs Claude-3.5-Sonnet vs Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"abstraction over the concrete","claim":"In the study's taxonomy, edits in the Lack of Specificity and Detail category typically make the text longer, because writers add detail rather than cut.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"typically make the text longer as writers add more details","page":"Section 4.4.5, Lack of Specificity and Detail","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"lexical tells","claim":"One professional writer in the study, identified as W1, reported that a very common phrasing in the LLM excerpts was seem to plus a verb, which the writer judged inelegant and preferred replaced by the plain verb.","source":"Writer W1, quoted from an email in Chakrabarty, Laban et al., arXiv:2409.14509, September 2024","url":CK,"quote":"a very common phrasing in these excerpts is","page":"Section 4.4.6, Awkward Word Choice and Phrasing","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3; the text is a quotation from a study participant inside the paper, not the authors' own analysis","registerHint":"dossier-archivist","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"reader and expert judgment","claim":"The study's large-scale preference annotation found that experts largely prefer text edited by other experts over automatically edited text.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"although experts largely prefer text edited by other experts","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3","registerHint":"none","confidence":"high","modelEra":"GPT-4o, Claude-3.5-Sonnet, Llama-3.1-70b, September 2024; register: literary fiction and creative non-fiction"},
 {"feature":"detection and its failures","claim":"In the study's span-detection evaluation, expert agreement with each other on which spans are problematic reached only 0.57 general precision and 0.23 categorical precision.","source":"Tuhin Chakrabarty, Philippe Laban et al., Salesforce AI Research, arXiv:2409.14509, September 2024","url":CK,"quote":"","page":"Section 6.1, results table row 'Expert Agreement'","kind":"measurement","polarity":"asserts (a limit on expert consensus)","date":"2024-09-26","routeHint":"arXiv HTML at /html/2409.14509v3; the two figures render as separate table cells under the Expert Agreement row, so no contiguous verbatim span carries both","registerHint":"none","confidence":"high","modelEra":"expert annotators on GPT-4o/Claude-3.5-Sonnet/Llama-3.1-70b output, September 2024; register: literary fiction and creative non-fiction"},
 # ---- MOLLICK ----
 {"feature":"homogenisation","claim":"Mollick writes that the sameness of AI writing eventually gets tedious enough that he skips writing on interesting topics when his internal AI detector goes off.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"the sameness of the AI writing","page":"opening section","kind":"analysis","polarity":"asserts","date":"2026-05-26","routeHint":"post URL recovered from oneusefulthing.org/sitemap/2026; direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs, May 2026; register: social media posts, academic papers, opinion articles"},
 {"feature":"gloss and over-explaining","claim":"Mollick argues that badly prompted AI writing produces very little meaning per word and takes the reader in intellectual circles.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"produces very little meaning per word, taking you in intellectual circles","page":"opening section","kind":"analysis","polarity":"asserts","date":"2026-05-26","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs, May 2026; register: online posts and comments"},
 {"feature":"other: surface polish with nothing underneath","claim":"Mollick calls such posts meaning-shaped attention vampires that take mental effort to decode and give no equivalent understanding in return.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"meaning-shaped attention vampires","page":"opening section","kind":"analysis","polarity":"asserts","date":"2026-05-26","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs, May 2026; register: online posts and comments"},
 {"feature":"abstraction over the concrete","claim":"Mollick writes in a footnote that AI is notoriously weak while seeming strong at fiction writing, and that ChatGPT in particular is fond of meaningless similes and metaphors.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"fond of meaningless similes and metaphors","page":"footnote 1","kind":"analysis","polarity":"asserts","date":"2026-05-26","routeHint":"direct curl with browser UA; the text is in footnote 1, printed after the post body","registerHint":"none","confidence":"high","modelEra":"ChatGPT named specifically, May 2026; register: fiction writing"},
 {"feature":"reader and expert judgment","claim":"Mollick argues that such similes can feel profound at first sight only because readers assume difficult writing is purposeful and work hard to assign it meaning.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"","page":"footnote 1","kind":"analysis","polarity":"asserts a mechanism of reader deception","date":"2026-05-26","routeHint":"direct curl with browser UA; footnote 1. Quote left blank because the sentence runs long and no twelve-word contiguous span carries the whole limb","registerHint":"none","confidence":"high","modelEra":"ChatGPT, May 2026; register: fiction writing"},
 {"feature":"steerability","claim":"Mollick states that a little bit of effort can make AI writing less cliche, more personal, and more worth using in moderation.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"a little bit of effort can make AI writing less cliche","page":"paragraph beginning \"This is not a condemnation\"","kind":"analysis","polarity":"asserts (counter to a flat steerability ceiling)","date":"2026-05-26","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"medium - asserted in passing with no measurement on the page","modelEra":"contemporary LLMs, May 2026; register: writing generally"},
 {"feature":"detection and its failures","claim":"Mollick states parenthetically that frequent AI users have historically done quite well at identifying AI writing.","source":"Ethan Mollick, Wharton professor, One Useful Thing, 26 May 2026","url":MO,"quote":"frequent AI users have historically done quite well identifying AI writing","page":"opening section","kind":"analysis","polarity":"asserts","date":"2026-05-26","routeHint":"direct curl with browser UA; the claim is hyperlinked on the page to an external source that was not followed","registerHint":"none","confidence":"medium - Mollick links out rather than giving the figure, and the linked source was not read","modelEra":"contemporary LLMs, May 2026; register: online prose"},
 # ---- GOODSPEED (relay, and about imagery not prose) ----
 {"feature":"counter-evidence","claim":"Goodspeed locates the failure of AI imagery not in the technology but in the cliche and superficial creative ambitions of the people using it.","source":"Elizabeth Goodspeed, It's Nice That columnist, in her column reproduced on ABC Brand/Design","url":GS,"quote":"AI image generation is essentially a truncated exercise in taste","page":"opening section","kind":"relay","polarity":"asserts, about imagery rather than prose","date":"undated on the relay page","routeHint":"the original It's Nice That URL could not be recovered in this session; the column text was read on the reproducing page and should be treated as a relay of the primary","registerHint":"none","confidence":"medium - read on a reproducing site rather than at the primary, and the claim concerns generated images, not generated prose","modelEra":"OpenAI's Sora named as the video model; the piece is undated on the relay, and the register discussed is generated imagery, not text"},
]

json.dump({"sourcesRead":sourcesRead,"claims":claims}, open(os.path.join(D,"extra_c.json"),"w"), indent=1, ensure_ascii=False)
print(len(claims), "claims", len(sourcesRead), "sources")
