# -*- coding: utf-8 -*-
import json, os
D = os.path.dirname(os.path.abspath(__file__))

SC23 = "https://whatever.scalzi.com/2023/02/23/omg-is-the-ai-coming-for-my-job/"
SC26 = "https://whatever.scalzi.com/2026/02/14/10-thoughts-on-ai-february-2026-edition/"
WE = "https://terribleminds.com/ramble/2025/05/21/repeat-after-me-ai-doesnt-know-anything/"
SL = "https://www.robinsloan.com/newsletters/authors-note/"
DO = "https://pluralistic.net/2026/03/02/nonconsensual-slopping/"
TN = "https://thenewpublishingstandard.com/2026/08/16/anthropic-ai-slop-detection-guide/"
ST = "https://writerbeware.blog/2026/08/28/production-companies-literary-agents-foreign-languages-ai-driven-scams-continue-to-morph/"

sourcesRead = [
 {"title":"John Scalzi, \"OMG is the AI Coming For My Job?!\", Whatever","url":SC23,"kind":"own-words","substantive":True,"date":"2023-02-23","route":"direct curl with browser UA"},
 {"title":"John Scalzi, \"10 Thoughts On 'AI,' February 2026 Edition\", Whatever (post plus reader comments)","url":SC26,"kind":"own-words","substantive":True,"date":"2026-02-14","route":"direct curl with browser UA; Scalzi's own text ends at the '- JS' sign-off, everything after is reader comments"},
 {"title":"Chuck Wendig, \"Repeat After Me: AI Doesn't Know Anything\", Terribleminds","url":WE,"kind":"own-words","substantive":True,"date":"2025-05-21","route":"live curl returned the site's generic shell; read via Wayback raw capture 20260618213915id_/"},
 {"title":"Robin Sloan, \"Author's note\", robinsloan.com newsletter","url":SL,"kind":"own-words","substantive":True,"date":"2022-11","route":"direct curl with browser UA; NB the page inserts soft hyphens (U+00AD) inside many words, so verbatim matching must avoid hyphenated words"},
 {"title":"Cory Doctorow, \"No one wants to read your AI slop\", Pluralistic","url":DO,"kind":"analysis","substantive":True,"date":"2026-03-02","route":"found via pluralistic.net/tag/slop/; direct curl with browser UA"},
 {"title":"Mark Williams, \"Anthropic Doesn't Need Watermarks... 20 Tell-Tale Signs You're Reading AI Slop, Even When A Human Wrote It\", The New Publishing Standard","url":TN,"kind":"analysis","substantive":True,"date":"2026-08-16","route":"found via thenewpublishingstandard.com archive index; direct curl with browser UA"},
 {"title":"Victoria Strauss, \"Production Companies, Literary Agents, Foreign Languages: AI-Driven Scams Continue to Morph\", Writer Beware","url":ST,"kind":"analysis","substantive":True,"date":"2026-08-28","route":"direct curl with browser UA"},
 {"title":"Robin Sloan, \"Are language models in hell?\", robinsloan.com lab blog","url":"https://www.robinsloan.com/lab/language-models-hell/","kind":"analysis","substantive":False,"date":"2023-12-17","route":"direct curl with browser UA; read in full, the provocation is about model welfare/framing, not about prose failure, so no claim drawn"},
]

claims = [
 # ---- SCALZI 2023 ----
 {"feature":"reader and expert judgment","claim":"Scalzi wrote in February 2023 that the AI-generated stories then flooding science fiction magazines are kinda trash.","source":"John Scalzi, novelist, Whatever, 23 February 2023","url":SC23,"quote":"all these generated stories are kinda trash","page":"opening paragraph","kind":"own-words","polarity":"asserts","date":"2023-02-23","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"pre-GPT-4 ChatGPT (he quotes a ChatGPT reply in the post), February 2023; register: short science fiction submissions"},
 {"feature":"homogenisation","claim":"Scalzi argues that a single prompter sees one output and may find it original, but an editor sees the current AI tropes dozens of times with each new iteration of the generators.","source":"John Scalzi, novelist, Whatever, 23 February 2023","url":SC23,"quote":"see the current AI tropes dozens of times","page":"para. beginning \"If this is indeed mostly scamsters\"","kind":"own-words","polarity":"asserts","date":"2023-02-23","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"ChatGPT-era text generators, February 2023; register: short science fiction submissions"},
 {"feature":"homogenisation","claim":"Scalzi argues that leaving prose quality aside, the sheer repetition of elements across generated submissions is by itself enough to remove the material from serious editorial consideration.","source":"John Scalzi, novelist, Whatever, 23 February 2023","url":SC23,"quote":"the sheer repetition of elements will remove the material from serious consideration","page":"para. beginning \"If this is indeed mostly scamsters\"","kind":"own-words","polarity":"asserts","date":"2023-02-23","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"ChatGPT-era text generators, February 2023; register: short science fiction submissions"},
 {"feature":"other: surface polish with nothing underneath","claim":"Scalzi describes AI as a fast, infinite generator of competently-assembled bullshit with no ability to tell truth from nonsense.","source":"John Scalzi, novelist, Whatever, 23 February 2023","url":SC23,"quote":"a fast, infinite generator of competently-assembled bullshit","page":"para. beginning \"But, as it happens, I agree with the text here\"","kind":"own-words","polarity":"asserts","date":"2023-02-23","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"ChatGPT, February 2023; register: informational articles (he cites CNet and Men's Health) and prose generally"},
 {"feature":"other: surface polish with nothing underneath","claim":"Scalzi frames the gap as one between text that is serviceable on the sentence level and text that is actually good, and says closing it takes so much human work that skipping the generation step would be less work.","source":"John Scalzi, novelist, Whatever, 23 February 2023","url":SC23,"quote":"serviceable on the sentence level","page":"para. beginning \"This estimation, mind you\"","kind":"own-words","polarity":"asserts","date":"2023-02-23","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"ChatGPT-era generators, February 2023; register: stories, articles and books"},
 # ---- SCALZI 2026 ----
 {"feature":"reader and expert judgment","claim":"Scalzi states in February 2026 that he does not use AI in his published text partly because he writes better than AI can or ever will.","source":"John Scalzi, novelist, Whatever, 14 February 2026","url":SC26,"quote":"I write better than","page":"numbered point 1","kind":"own-words","polarity":"asserts","date":"2026-02-14","routeHint":"direct curl with browser UA; Scalzi's own text ends at the '- JS' sign-off","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs unnamed in this point (he names ChatGPT/Claude/Gemini/Copilot at point 9), February 2026; register: novels"},
 {"feature":"reader and expert judgment","claim":"Scalzi asserts in February 2026 that there is no statistical model that can create what is uniquely you.","source":"John Scalzi, novelist, Whatever, 14 February 2026","url":SC26,"quote":"There is no statistical model that can create what is uniquely you","page":"numbered point 10, final line before the '- JS' sign-off","kind":"own-words","polarity":"asserts","date":"2026-02-14","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs, February 2026; register: creative work generally"},
 {"feature":"model era drift","claim":"A commenter using the name Fatman argues on Scalzi's blog that although LLMs have improved considerably at pattern-recognition tasks, more powerful software has so far not led to better machine-generated fiction.","source":"'Fatman', a reader commenting on John Scalzi's Whatever, 15 February 2026","url":SC26,"quote":"more powerful software has so far not led to better machine-generated fiction","page":"comment thread, comment by Fatman timestamped February 15, 2026, 9:50 am","kind":"reader","polarity":"asserts","date":"2026-02-15","routeHint":"direct curl with browser UA; this text is in the comment thread BELOW the '- JS' sign-off and is not Scalzi's own","registerHint":"none","confidence":"high","modelEra":"LLMs over the couple of years to February 2026; register: fiction"},
 {"feature":"counter-evidence","claim":"A commenter using the name Quill argues on Scalzi's blog that AI will be better at writing than Scalzi within roughly two to seven years.","source":"'Quill', a reader commenting on John Scalzi's Whatever, quoted by another commenter, February 2026","url":SC26,"quote":"AI will be better at writing than you are","page":"comment thread, quoted by Fatman on February 15, 2026","kind":"reader","polarity":"disputes the critics' position","date":"2026-02-15","routeHint":"direct curl with browser UA; the line reaches the page as a quotation inside Fatman's comment","registerHint":"none","confidence":"medium - read as quoted inside another commenter's reply rather than at Quill's own comment","modelEra":"a prediction made February 2026 about models two to seven years out; register: writing generally"},
 # ---- WENDIG ----
 {"feature":"other: surface polish with nothing underneath","claim":"Wendig argues that a generative model does not conjure an answer but an answer-shaped thing, filling the space with the shape of what was asked for.","source":"Chuck Wendig, novelist, Terribleminds, 21 May 2025","url":WE,"quote":"It will conjure not an answer, but an answer-shaped thing","page":"section beginning \"AI doesn't know anything\"","kind":"own-words","polarity":"asserts","date":"2025-05-21","routeHint":"live terribleminds.com returns a generic shell to curl; use the Wayback raw capture https://web.archive.org/web/20260618213915id_/https://terribleminds.com/ramble/2025/05/21/repeat-after-me-ai-doesnt-know-anything/","registerHint":"none","confidence":"high","modelEra":"unnamed generative AI used to produce a newspaper summer-reading insert, May 2025; register: informational listicle prose, not fiction"},
 {"feature":"other: surface polish with nothing underneath","claim":"Wendig calls generative AI almost literally a super-fancy lorum ipsum generator.","source":"Chuck Wendig, novelist, Terribleminds, 21 May 2025","url":WE,"quote":"a super-fancy lorum ipsum generator","page":"section beginning \"AI doesn't know anything\"","kind":"own-words","polarity":"asserts","date":"2025-05-21","routeHint":"Wayback raw capture 20260618213915id_","registerHint":"none","confidence":"high","modelEra":"unnamed generative AI, May 2025; register: informational prose","":""},
 {"feature":"reader and expert judgment","claim":"A commenter using the name bluespiderwort writes on Wendig's post that AI paragraphs have words, sometimes big words, and lots of sentences, but frequently say nothing.","source":"'bluespiderwort', a reader commenting on Chuck Wendig's Terribleminds, 21 May 2025","url":WE,"quote":"The paragraphs have words, sometimes big words","page":"comment thread below the post","kind":"reader","polarity":"asserts","date":"2025-05-21","routeHint":"Wayback raw capture 20260618213915id_; this is a reader comment, not Wendig's own text","registerHint":"none","confidence":"high","modelEra":"unnamed contemporary generative AI, May 2025; register: online prose"},
 # ---- SLOAN ----
 {"feature":"other: no model of what the draft is doing","claim":"Sloan reports that when he tried to make Google's Wordcraft AI play detective in a locked-room mystery it had no idea what was happening a few paragraphs in.","source":"Robin Sloan, novelist, newsletter, November 2022","url":SL,"quote":"it had no idea what was happening","page":"section \"Notes on writing with Google's AI\"","kind":"own-words","polarity":"asserts","date":"2022-11","routeHint":"direct curl with browser UA; beware soft hyphens (U+00AD) inserted inside many words on this page","registerHint":"none","confidence":"high","modelEra":"Google's Wordcraft editor over an unnamed LaMDA-class model, November 2022; register: a locked-room mystery short story"},
 {"feature":"abstraction over the concrete","claim":"Sloan reports that the model knew he was writing a mystery and reached for the appropriate terms and tropes, but that this was nowhere close to sufficient.","source":"Robin Sloan, novelist, newsletter, November 2022","url":SL,"quote":"It knew I was writing a mystery","page":"section \"Notes on writing with Google's AI\"","kind":"own-words","polarity":"asserts","date":"2022-11","routeHint":"direct curl with browser UA; soft hyphens present in 'appro-priate'","registerHint":"none","confidence":"high","modelEra":"Google's Wordcraft, November 2022; register: mystery short fiction"},
 {"feature":"steerability","claim":"Sloan reports that the project only worked once he established a fenced-in space for the AI, assigning it a litany of grisly deaths and fantasy character names to riff on rather than any structural role.","source":"Robin Sloan, novelist, newsletter, November 2022","url":SL,"quote":"a fenced-in space for the AI","page":"section \"Notes on writing with Google's AI\"","kind":"own-words","polarity":"asserts a working constraint","date":"2022-11","routeHint":"direct curl with browser UA","registerHint":"herald-pools","confidence":"high","modelEra":"Google's Wordcraft, November 2022; register: a fantasy-saga litany inside a short story"},
 {"feature":"steerability","claim":"Sloan reports that the AI did not make a useful or pleasant writing partner because even a state-of-the-art language model cannot presently understand what a fiction writer is trying to accomplish in an evolving draft.","source":"Robin Sloan, novelist, newsletter, November 2022","url":SL,"quote":"did not make a useful or pleasant writing partner","page":"section \"Notes on writing with Google's AI\", third closing thought","kind":"own-words","polarity":"asserts","date":"2022-11","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"Google's Wordcraft, November 2022; register: short fiction drafting"},
 # ---- DOCTOROW ----
 {"feature":"gloss and over-explaining","claim":"Doctorow refers in passing to the verbosity of chatbot responses as a reason forwarding transcripts imposes on the reader.","source":"Cory Doctorow, novelist and journalist, Pluralistic, 2 March 2026","url":DO,"quote":"the verbosity of chatbot responses","page":"para. beginning \"The same is true of your conversations with chatbots\"","kind":"analysis","polarity":"asserts","date":"2026-03-02","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary chatbots, Grok named, March 2026; register: chat transcripts, not fiction"},
 {"feature":"other: surface polish with nothing underneath","claim":"Doctorow argues that prompting a model for a rebuttal yields a blob of plausible sentences that is just stochastic word-salad until a human who understands the issue verifies it line by line.","source":"Cory Doctorow, novelist and journalist, Pluralistic, 2 March 2026","url":DO,"quote":"you have generated a blob of plausible sentences","page":"para. beginning \"You haven't generated a rebuttal\"","kind":"analysis","polarity":"asserts","date":"2026-03-02","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary chatbots, March 2026; register: argumentative commentary, not fiction"},
 {"feature":"gloss and over-explaining","claim":"Doctorow describes what a chatbot costlessly produces as infinite volumes of verbose, plausible-seeming topical sentences.","source":"Cory Doctorow, novelist and journalist, Pluralistic, 2 March 2026","url":DO,"quote":"infinite volumes of verbose, plausible-seeming topical sentences","page":"para. beginning \"Remember: even the AI companies will tell you\"","kind":"analysis","polarity":"asserts","date":"2026-03-02","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary chatbots, March 2026; register: topical commentary"},
 # ---- MARK WILLIAMS / TNPS (counter-case) ----
 {"feature":"counter-evidence","claim":"Mark Williams rejects the premise of AI-spotting, arguing that machine writing does not carry a stable, visible fingerprint.","source":"Mark Williams, editor-in-chief, The New Publishing Standard, 16 August 2026","url":TN,"quote":"machine writing carries a stable, visible fingerprint","page":"section \"Full disclosure\"","kind":"analysis","polarity":"rejects (the page states this premise in order to deny it: 'It doesn't')","date":"2026-08-16","routeHint":"direct curl with browser UA; note the sentence quoted is the premise Williams immediately denies","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs unnamed (several models used for the demonstration), August 2026; register: LinkedIn and professional online posts"},
 {"feature":"counter-evidence","claim":"Williams argues that what the supposed AI tells actually mark is the fingerprint of editing - clarity, structure, transitions, a point that goes somewhere - which is a feature of good writing whoever produced the first draft.","source":"Mark Williams, editor-in-chief, The New Publishing Standard, 16 August 2026","url":TN,"quote":"What it carries is the fingerprint of editing","page":"section \"Full disclosure\"","kind":"analysis","polarity":"disputes the tells","date":"2026-08-16","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"contemporary LLMs, August 2026; register: professional online prose"},
 {"feature":"detection and its failures","claim":"Williams argues that classifiers cannot reliably separate AI prose from human prose because the models were trained on human prose, so the categories overlap by construction.","source":"Mark Williams, editor-in-chief, The New Publishing Standard, 16 August 2026","url":TN,"quote":"the categories overlap by construction","page":"section beginning \"So here's the actual argument\"","kind":"analysis","polarity":"asserts","date":"2026-08-16","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"AI detection classifiers as of August 2026; register: prose generally"},
 {"feature":"detection and its failures","claim":"Williams argues that detectors falsely flag non-native English writing because ESL prose tends toward simpler sentence-length variance, safer phrasing and fewer idioms, the very features detectors treat as tells.","source":"Mark Williams, editor-in-chief, The New Publishing Standard, 16 August 2026","url":TN,"quote":"simpler sentence-length variance, safer phrasing, fewer idioms","page":"section beginning \"So here's the actual argument\"","kind":"analysis","polarity":"asserts","date":"2026-08-16","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"medium - Williams cites 'Studies on GPT-detection tools' without naming them on the page","modelEra":"GPT-detection tools, August 2026; register: ESL and Global South professional prose"},
 {"feature":"counter-evidence","claim":"Williams discloses that the twenty satirical tell-tale signs in his own piece were not written by him but gathered from several AI models, whose sharpest lines he picked and presented as one voice.","source":"Mark Williams, editor-in-chief, The New Publishing Standard, 16 August 2026","url":TN,"quote":"I put a version of this challenge to several AI models","page":"section \"Full disclosure\"","kind":"analysis","polarity":"asserts (a demonstration against the tells)","date":"2026-08-16","routeHint":"direct curl with browser UA; the twenty numbered items are AI-written parody text curated by Williams, not his own prose","registerHint":"none","confidence":"high","modelEra":"several unnamed AI models, August 2026; register: satirical listicle"},
 # ---- STRAUSS ----
 {"feature":"homogenisation","claim":"Strauss reports that the AI-driven author scams she tracks are marked by hyper-personalization coupled with lavish praise, which she attributes to generative AI.","source":"Victoria Strauss, Writer Beware, 28 August 2026","url":ST,"quote":"hyper-personalization coupled with lavish praise","page":"para. beginning \"The one thing the scammers haven't changed\"","kind":"analysis","polarity":"asserts","date":"2026-08-28","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"unnamed generative AI used by scam operations, reported August 2026; register: solicitation email, not fiction"},
 {"feature":"homogenisation","claim":"Strauss reports that receiving multiple flattering yet suspiciously similar solicitations every day is itself what makes the AI-written approaches start to seem inauthentic.","source":"Victoria Strauss, Writer Beware, 28 August 2026","url":ST,"quote":"suspiciously similar solicitations every day","page":"para. beginning \"The one thing the scammers haven't changed\"","kind":"analysis","polarity":"asserts","date":"2026-08-28","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"unnamed generative AI, August 2026; register: solicitation email"},
 {"feature":"discourse-level tells","claim":"Strauss identifies friendly, open-ended inquiry as a common ingredient of AI marketing solicitations, used to incentivize a reply and draw the writer into a long exchange.","source":"Victoria Strauss, Writer Beware, 28 August 2026","url":ST,"quote":"friendly, open-ended inquiry is a common ingredient","page":"section on the German-language solicitation","kind":"analysis","polarity":"asserts","date":"2026-08-28","routeHint":"direct curl with browser UA","registerHint":"none","confidence":"high","modelEra":"unnamed generative AI, August 2026; register: solicitation email"},
]

for c in claims:
    c.pop("", None)
json.dump({"sourcesRead":sourcesRead,"claims":claims}, open(os.path.join(D,"extra_a.json"),"w"), indent=1, ensure_ascii=False)
print(len(claims), "claims", len(sourcesRead), "sources")
