/**
 * Faction-gated NPC candidates that are not derivable from institutions alone.
 *
 * These are immutable module data rather than per-generation allocations.
 * Eligibility remains the orchestrator's responsibility: tier, faction, guild,
 * route, and WorldLaw gates are applied before a candidate enters a draw pool.
 */

export const NOBLE_ROLES = Object.freeze([
  {
    role: 'Lord/Lady of the Manor',
    title: 'noble',
    priority: 8,
    minTier: 'village',
    category: 'noble',
    goalCategories: ['power', 'wealth'],
  },
  {
    role: 'Baron/Baroness',
    title: 'noble',
    priority: 9,
    minTier: 'town',
    category: 'noble',
    goalCategories: ['power', 'wealth'],
  },
  {
    role: 'Court Advisor',
    title: 'advisor',
    priority: 7,
    minTier: 'town',
    category: 'noble',
    goalCategories: ['power', 'knowledge'],
  },
  {
    role: 'House Steward',
    title: 'steward',
    priority: 6,
    minTier: 'village',
    category: 'noble',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Noble Heir',
    title: 'noble',
    priority: 5,
    minTier: 'hamlet',
    category: 'noble',
    goalCategories: ['personal', 'power'],
  },
  {
    role: 'Land Agent',
    title: 'agent',
    priority: 5,
    minTier: 'village',
    category: 'noble',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Knight/Dame',
    title: 'knight',
    priority: 7,
    minTier: 'village',
    category: 'noble',
    goalCategories: ['protection', 'personal'],
  },
  {
    role: 'Duke/Duchess',
    title: 'noble',
    priority: 10,
    minTier: 'metropolis',
    category: 'noble',
    goalCategories: ['power', 'wealth'],
  },
  {
    role: 'Royal Chamberlain',
    title: 'noble',
    priority: 8,
    minTier: 'city',
    category: 'noble',
    goalCategories: ['power', 'personal'],
  },
]);

export const CRAFTS_ROLES = Object.freeze([
  {
    role: 'Master Blacksmith',
    title: 'master',
    priority: 7,
    minTier: 'hamlet',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Master Carpenter',
    title: 'master',
    priority: 6,
    minTier: 'hamlet',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Master Weaver',
    title: 'master',
    priority: 6,
    minTier: 'village',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Master Tanner',
    title: 'master',
    priority: 5,
    minTier: 'village',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Head Brewer',
    title: 'guild',
    priority: 5,
    minTier: 'hamlet',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Guild Warden',
    title: 'guild',
    priority: 7,
    minTier: 'town',
    category: 'crafts',
    goalCategories: ['power', 'wealth'],
    requiresGuild: true,
  },
  {
    role: 'Journeyman Overseer',
    title: 'overseer',
    priority: 5,
    minTier: 'town',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Craft Guild Representative',
    title: 'guild',
    priority: 6,
    minTier: 'city',
    category: 'crafts',
    goalCategories: ['power', 'wealth'],
    requiresGuild: true,
  },
  {
    role: 'Master Potter',
    title: 'master',
    priority: 4,
    minTier: 'village',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
  {
    role: 'Master Glassblower',
    title: 'master',
    priority: 5,
    minTier: 'town',
    category: 'crafts',
    goalCategories: ['wealth', 'personal'],
  },
]);
