import json, os
D=os.path.dirname(os.path.abspath(__file__))
RAS="https://www.rascal.news/ai-generated-profiles-of-ttrpg-designers-ignite-fury-across-social-media/"
ALEX="https://thealexandrian.net/wordpress/53232/roleplaying-games/thought-of-the-day-genai-and-rpgs"
TFP="https://tenfootpole.org/ironspike/?p=10009"
WB="https://old.reddit.com/r/worldbuilding/wiki/rules"
LK="https://www.legendkeeper.com/worldbuilding-with-ai/"

sourcesRead=[
 {"title":"r/worldbuilding subreddit rules wiki (rule 4, 'AI Content')","url":WB,"kind":"vendor","substantive":True,"date":"captured 2026-08-19","route":"Wayback raw id_ capture of old.reddit (live reddit and reddit .json both blocked)"},
 {"title":"r/DnDBehindTheScreen sidebar posting rules (rule 8, 'No AI-centric content')","url":"https://old.reddit.com/r/DnDBehindTheScreen/wiki/index","kind":"vendor","substantive":False,"date":"captured 2025-03-28","route":"Wayback raw id_ capture; rule title only, no rule body captured"},
 {"title":"Braden Herndon, 'Worlds ex Machina: Worldbuilding with AI', LegendKeeper blog","url":LK,"kind":"vendor","substantive":True,"date":"published 2022-07-29; author's notes 2024-02-27 and 2025-08-12","route":"live curl with browser UA"},
 {"title":"Lin Codega, 'AI-generated profiles of TTRPG designers ignite fury across social media', Rascal News","url":RAS,"kind":"analysis","substantive":True,"date":"2026-05-12","route":"live curl with browser UA (full text, not paywalled)"},
 {"title":"Justin Alexander, 'Thought of the Day: GenAI and RPGs', The Alexandrian (post plus author comments)","url":ALEX,"kind":"analysis","substantive":True,"date":"2025-12-28; comments to 2025-12-31","route":"live curl with browser UA"},
 {"title":"Bryce Lynch, review of 'Stygina: The Land of Ice and Plunder' plus comment thread, tenfootpole.org","url":TFP,"kind":"reception","substantive":True,"date":"2025-10-18; comments to 2025-10-27","route":"live curl with browser UA"},
 {"title":"Morrus, \"DriveThruRPG's New AI-Content Filter\", EN World","url":"https://www.enworld.org/threads/drivethrurpgs-new-ai-content-filter.707636/","kind":"reception","substantive":True,"date":"2024-10-29","route":"live curl with browser UA"},
 {"title":"Timothy Linward, 'Major DnD marketplaces put AI content in the dungeon', Wargamer","url":"https://www.wargamer.com/dnd/marketplace-dungeon-masters-guild-ai-ban","kind":"analysis","substantive":True,"date":"updated 2023-07-26","route":"live curl with browser UA"},
 {"title":"Whizbang Dustyboots, 'DMs Guild and DriveThruRPG ban AI written works…', EN World","url":"https://www.enworld.org/threads/dms-guild-and-drivethrurpg-ban-ai-written-works-requires-labels-for-ai-generated-art.698936/","kind":"reception","substantive":True,"date":"2023-07","route":"live curl with browser UA"},
 {"title":"Chase Carter, \"Dungeons & Dragons' new art direction isn't AI generated but almost worse—boring\", Rascal News","url":"https://www.rascal.news/dungeons-dragons-new-art-direction-isnt-ai-generated-but-almost-worse-boring/","kind":"analysis","substantive":False,"date":"2024-06-25","route":"live curl; body paywalled after the lede, and the subject is illustration not prose"},
]

claims=[
{"feature":"other: no citation apparatus","claim":"The r/worldbuilding moderators ban AI-written worldbuilding posts on the ground that AI generators do not cite the material they were trained on, making such text incompatible with the subreddit's citation rule.","source":"r/worldbuilding moderators, subreddit rules wiki, rule 4","url":WB,"quote":"incompatible with our policies on citation","page":"Rule 4, 'AI Content'","kind":"vendor","polarity":"asserts","date":"capture 2026-08-19","routeHint":"Wayback raw id_ capture of old.reddit; live reddit blocked","registerHint":"none","confidence":"high","modelEra":"no model named; rule text live as of the 2026-08-19 capture; register governed is amateur worldbuilding prose and art"},
{"feature":"steerability","claim":"The same r/worldbuilding rule extends the ban to using AI merely to organise, edit, present or rewrite the poster's own worldbuilding material.","source":"r/worldbuilding moderators, subreddit rules wiki, rule 4","url":WB,"quote":"Using AI to organize, edit, present, or rewrite material","page":"Rule 4, 'AI Content'","kind":"vendor","polarity":"asserts","date":"capture 2026-08-19","routeHint":"Wayback raw id_ capture of old.reddit","registerHint":"none","confidence":"high","modelEra":"no model named; capture 2026-08-19; register governed is amateur worldbuilding prose"},
{"feature":"other: volume without readership","claim":"LegendKeeper's founder, writing about AI-heavy worldbuilding competitors, says he wonders why anyone would generate walls of text nobody will read.","source":"Braden Herndon, LegendKeeper blog, author's note of 2025-08-12","url":LK,"quote":"generate walls of text that no one will read","page":"Author's Note (Aug 12th, 2025)","kind":"vendor","polarity":"asserts","date":"2025-08-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"no model named; observation dated August 2025; register is worldbuilding wiki/article text sold by AI worldbuilding tools"},
{"feature":"discourse-level tells","claim":"TTRPG historian Shannon Appelcline, having read five paragraphs of an LLM-written designer history, says the false implications created between sentences were worse than the outright factual errors.","source":"Shannon Appelcline, email to Rascal News, quoted by Lin Codega","url":RAS,"quote":"But worse were the misimplications.","page":"Appelcline's emailed statement, roughly one-third in","kind":"analysis","polarity":"asserts","date":"2026-05-12 (reading done January 2026)","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model not named beyond 'LLM'; reading January 2026, published May 2026; register measured is biographical/archival history prose"},
{"feature":"other: mechanism — no model of what was written","claim":"Appelcline attributes those cross-sentence false implications to the model not knowing what it is writing.","source":"Shannon Appelcline, email to Rascal News, quoted by Lin Codega","url":RAS,"quote":"They don't know what they're writing.","page":"Appelcline's emailed statement","kind":"analysis","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model not named beyond 'LLM'; January 2026 reading; register measured is archival/biographical history prose"},
{"feature":"homogenisation","claim":"Reporter Lin Codega describes the AI-generated designer profiles as flattening careers into sycophantic textual formulas.","source":"Lin Codega, Rascal News","url":RAS,"quote":"a sloppish wasteland of sycophantic textual formulas","page":"paragraph 3","kind":"analysis","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model unnamed; observation May 2026; register measured is encyclopedic designer-profile prose"},
{"feature":"other: missing apparatus (links, citations, works list)","claim":"Codega reports that the generated profiles carry no internal or external links, no list of published work and no source references.","source":"Lin Codega, Rascal News","url":RAS,"quote":"there are no links, internal or external","page":"section asking 'what the fuck is the point of all this?'","kind":"analysis","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model unnamed; May 2026; register measured is encyclopedic designer-profile prose presented as a historical archive"},
{"feature":"other: omission of the salient fact","claim":"Codega reports that Greg Costikyan's profile omitted his game Violence, which she attributes to the model not connecting his pseudonym Designer X to him.","source":"Lin Codega, Rascal News","url":RAS,"quote":"wasn’t even mentioned in the overwrought bolus of his profile","page":"paragraph on Costikyan","kind":"analysis","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model unnamed; May 2026; register measured is encyclopedic designer-profile prose"},
{"feature":"repetition and refrain","claim":"Codega reports that each AI-written reply she received ran three or four paragraphs of evasion built on repeated stock phrases.","source":"Lin Codega, Rascal News","url":RAS,"quote":"three or four paragraphs of sycophantic evasion","page":"section on her Facebook interview with 4 Pillar","kind":"analysis","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"none","confidence":"medium","modelEra":"model unnamed; May 2026; register measured is AI-written correspondence, not the setting or profile text"},
{"feature":"discourse-level tells","claim":"Codega reports that every AI-written reply followed the same four-move formula: apology, rewrite, nebulous statement of future intent, then a shift of the goalposts.","source":"Lin Codega, Rascal News","url":RAS,"quote":"each explanatory message followed a similar formula","page":"section on her Facebook interview with 4 Pillar","kind":"analysis","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"none","confidence":"medium","modelEra":"model unnamed; May 2026; register measured is AI-written correspondence"},
{"feature":"measurement","claim":"Codega reports the AI-generated profiles run mostly between 1500 and 2000 words each, which the site said took around two hours apiece.","source":"Lin Codega, Rascal News","url":RAS,"quote":"Most end up between 1500 and 2000 words","page":"section on word counts","kind":"measurement","polarity":"asserts","date":"2026-05-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model unnamed; May 2026; register measured is encyclopedic designer-profile prose"},
{"feature":"other: mechanism — corruption of the record","claim":"Appelcline told Ken Whitman on LinkedIn that publishing the LLM-written histories was poisoning the well of history.","source":"Shannon Appelcline, LinkedIn message of January 2026, quoted by Lin Codega","url":RAS,"quote":"poisoning the well of history","page":"paragraph on the January 2026 LinkedIn exchange","kind":"analysis","polarity":"asserts","date":"message January 2026, published 2026-05-12","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"high","modelEra":"model unnamed; January 2026; register measured is archival history prose"},
{"feature":"other: setting-material contamination","claim":"Justin Alexander, testing Gemini on the one-page RPG Lasers & Feelings, found the generated mission summary had imported Star Trek setting material that is not in the game.","source":"Justin Alexander, comment on his own post, The Alexandrian","url":ALEX,"quote":"It got confused and included Star Trek setting information.","page":"comment of December 31st, 2025 - 3:28 pm","kind":"analysis","polarity":"asserts","date":"2025-12-31","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"high","modelEra":"Google Gemini (shared gemini.google.com transcript), December 2025; register measured is RPG setting and play-transcript prose"},
{"feature":"discourse-level tells","claim":"In the same test Alexander found the model renamed its own just-established ship detail one line later, which he calls forgetting what it had just said.","source":"Justin Alexander, comment on his own post, The Alexandrian","url":ALEX,"quote":"It immediately forgot what it just said.","page":"comment of December 31st, 2025 - 3:28 pm","kind":"analysis","polarity":"asserts","date":"2025-12-31","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"high","modelEra":"Google Gemini, December 2025; register measured is RPG setting and play-transcript prose"},
{"feature":"other: mechanism — no mental model","claim":"Alexander argues an LLM cannot form a mental model of a text and so can only produce a simulacrum of criticism of it.","source":"Justin Alexander, The Alexandrian","url":ALEX,"quote":"produce a simulacrum of criticism","page":"section 'Designing with ChatGPT'","kind":"analysis","polarity":"asserts","date":"2025-12-28","routeHint":"live curl with browser UA","registerHint":"none","confidence":"high","modelEra":"ChatGPT and LLMs generally, December 2025; register discussed is RPG rules text and critique of it"},
{"feature":"reader and expert judgment","claim":"Bryce Lynch, who reviews commercial adventures and setting books full time, says he cannot recognise AI-written products that his readers spot easily.","source":"Bryce Lynch, comment on his own review, tenfootpole.org","url":TFP,"quote":"I just don’t understand how people can recognize it so easily.","page":"comment of October 22, 2025 at 8:49 am","kind":"reception","polarity":"asserts","date":"2025-10-22","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"high","modelEra":"no model named; October 2025; register measured is published OSR adventure and gazetteer prose"},
{"feature":"detection and its failures","claim":"A commenter on that review argues a first glance will not reveal machine-generated text because imitating conventional writing well enough to pass is what LLMs are for.","source":"commenter 'DP', tenfootpole.org comment thread","url":TFP,"quote":"to imitate conventional writing enough to pass for man-made","page":"comment of October 23, 2025 at 1:33 pm","kind":"reader","polarity":"asserts","date":"2025-10-23","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"medium","modelEra":"no model named; October 2025; register discussed is a 198-page OSR setting book preview"},
{"feature":"lexical tells","claim":"A commenter on that review says machines tend to have a particular style of palaver, while conceding the signs are subtle and can be missed once a human has edited the text.","source":"commenter 'Peltast', tenfootpole.org comment thread","url":TFP,"quote":"machines do tend to have a particular style of palaver","page":"comment of October 25, 2025 at 4:20 am","kind":"reader","polarity":"asserts","date":"2025-10-25","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"medium","modelEra":"no model named; October 2025; register discussed is published setting-book prose"},
{"feature":"other: human tells rather than machine tells","claim":"The same commenter says the reliable first-glance signs are human ones — misspellings and long widely spaced constructions — because LLMs have good spelling and bad memory.","source":"commenter 'Peltast', tenfootpole.org comment thread","url":TFP,"quote":"LLMs have good spelling and bad memory","page":"comment of October 25, 2025 at 4:20 am","kind":"reader","polarity":"asserts","date":"2025-10-25","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"medium","modelEra":"no model named; October 2025; register discussed is published setting-book prose"},
{"feature":"model era drift","claim":"A commenter argues that the recognisable 'ChatGPT Voice' is deliberately built into that product and is not common to all LLMs, so readers who know only ChatGPT overestimate their ability to detect generated text.","source":"commenter 'LettuceBeReal', tenfootpole.org comment thread","url":TFP,"quote":"the “ChatGPT Voice” that OpenAI purposefully bakes into it","page":"comment of October 26, 2025 at 10:43 am","kind":"reader","polarity":"disputes","date":"2025-10-26","routeHint":"live curl with browser UA","registerHint":"none","confidence":"medium","modelEra":"ChatGPT versus 'all LLMs', October 2025; register discussed is long-form setting prose"},
{"feature":"uniform rhythm (low burstiness)","claim":"A commenter maintains that LLMs do not write like intelligent humans once the text reaches any serious length, and that the hard case is telling good LLM text from a dull human's.","source":"commenter 'Peltast', tenfootpole.org comment thread","url":TFP,"quote":"LLMs do not write like intelligent humans","page":"comment of October 27, 2025 at 5:48 am","kind":"reader","polarity":"asserts","date":"2025-10-27","routeHint":"live curl with browser UA","registerHint":"dm-page","confidence":"medium","modelEra":"no model named; October 2025; register discussed is long-form setting prose"},
{"feature":"discourse-level tells","claim":"The same commenter holds that the tell is length-dependent, because a model that cannot juggle interconnected concepts or reason about consequences eventually reveals itself.","source":"commenter 'Peltast', tenfootpole.org comment thread","url":TFP,"quote":"If it goes on long enough, it always shows itself.","page":"comment of October 27, 2025 at 12:25 pm","kind":"reader","polarity":"asserts","date":"2025-10-27","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"medium","modelEra":"no model named; October 2025; register discussed is long-form setting prose"},
{"feature":"counter-evidence","claim":"A commenter demonstrating that the reviewed setting book was human-written pasted one of its ungrammatical setting sentences into ChatGPT, and the returned rewrite fixed the grammar and regularised the construction.","source":"commenter 'Blakely', tenfootpole.org comment thread, quoting ChatGPT output","url":TFP,"quote":"This version tightens the flow","page":"comment of October 22, 2025 at 10:53 am","kind":"reader","polarity":"applies","date":"2025-10-22","routeHint":"live curl with browser UA","registerHint":"dossier-archivist","confidence":"medium","modelEra":"ChatGPT, October 2025; register measured is a gazetteer sentence about a people's crafts"},
{"feature":"other: marketplace policy","claim":"DriveThruRPG's July 2023 policy bans commercial content primarily written by AI language generators while permitting partly AI-written titles, and the platform conceded enforcement difficulty.","source":"Timothy Linward, Wargamer, quoting the OneBookShelf policy","url":"https://www.wargamer.com/dnd/marketplace-dungeon-masters-guild-ai-ban","quote":"commercial content primarily written by AI language generators","page":"paragraph 3","kind":"analysis","polarity":"asserts","date":"2023-07-26","routeHint":"live curl with browser UA (help.drivethrurpg.com itself is Cloudflare-blocked)","registerHint":"none","confidence":"high","modelEra":"no model named; policy effective 2023-07-31; register governed is commercial RPG rulebook, adventure and supplement text"},
]

out={"complete":False,"coverage":"in progress","sourcesRead":sourcesRead,"claims":claims}
json.dump(out, open(os.path.join(D,'found-ai-arch-worldbuilding-communities.json'),'w'), indent=1)
print(len(claims),"claims",len(sourcesRead),"sources")
