import json
OUT="found-martin-measurement.json"
d=json.load(open(OUT))

KL  = "https://link.springer.com/chapter/10.1007/978-3-658-36145-7_6"
PN  = "https://www.pnas.org/doi/10.1073/pnas.2006465117"
VA  = "https://arxiv.org/abs/1409.5830"
KY  = "https://cyberleninka.ru/article/n/historical-grand-narratives-of-the-seven-kingdoms-of-westeros-from-invention-to-deconstruction-of-a-traditional-medieval-historiography/pdf"
DN  = "https://www.dothraki.com/2011/08/new-dothraki-words/"

d["sourcesRead"] += [
 {"title":"Monika Kirner-Ludwig, ‘Rare but there’: On subtleties and saliencies of (pseudo-)archaisms in Game of Thrones scripted dialogues, in Sprache und Literatur (Springer VS, 2022), pp. 91-123","url":KL,"kind":"measurement","substantive":True,"date":"published online 22 June 2022","route":"Springer live page and PDF both refused by a Client Challenge wall; Wayback raw capture 20250801025545id_ carries the full open-access chapter text"},
 {"title":"Gessey-Jones, Connaughton, Dunbar, Kenna, MacCarron, O’Conchobhair, Yose, 'Narrative structure of A Song of Ice and Fire creates a fictional world with realistic measures of social complexity', PNAS 117(46)","url":PN,"kind":"measurement","substantive":True,"date":"approved 15 September 2020; published 2020","route":"OpenAlex OA locations -> Warwick WRAP author PDF -> pypdf text extraction"},
 {"title":"Richard Vale, 'Bayesian Prediction for The Winds of Winter', arXiv:1409.5830","url":VA,"kind":"measurement","substantive":True,"date":"2014-09-19","route":"arXiv API -> arxiv.org/pdf -> pypdf text extraction"},
 {"title":"Maksim W. Kyrchanoff, 'Historical grand narratives of the Seven Kingdoms of Westeros: from invention to deconstruction of a traditional medieval historiography', Journal of Frontier Studies 2018 no. 1, 17-43","url":KY,"kind":"analysis","substantive":True,"date":"2018","route":"OpenAlex OA locations -> CyberLeninka PDF -> pypdf text extraction"},
 {"title":"David J. Peterson, 'New Dothraki Words', Dothraki.com","url":DN,"kind":"own-words","substantive":False,"date":"August 2011 (moved from dothraki.conlang.org)","route":"Wayback CDX listing of dothraki.com -> direct fetch"},
 {"title":"OpenAlex title_and_abstract search, 'Game of Thrones archaism' (3 records) and 'A Song of Ice and Fire' (740 records)","url":"https://api.openalex.org/works?filter=title_and_abstract.search:Game%20of%20Thrones%20archaism","kind":"measurement","substantive":False,"date":"queried 2026-09-06","route":"OpenAlex API; used for bibliography and cited-by expansion after the WebSearch budget was exhausted"},
]

d["claims"] += [
 # Kirner-Ludwig
 {"feature":"archaism","claim":"Kirner-Ludwig concludes that the archaisms in the Game of Thrones scripted dialogues are not frequent in token terms yet are highly salient.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"may not be particularly frequent token-wise, but are highly salient","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw: https://web.archive.org/web/20250801025545id_/<url> (the live Springer page is behind a Client Challenge)","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Kirner-Ludwig states that Game of Thrones does not overdo pseudo-archaisms or archaic pronouns.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"GoT does not overdo the use of pseudo-archaisms","page":"section 6, Conclusion","kind":"measurement","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw capture","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"stylometry","claim":"Kirner-Ludwig's corpus is the full Game of Thrones transcripts covering 8 seasons and 73 episodes, analysed in Sketch Engine.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"covering 8 seasons and 73 episodes","page":"section 1, Introduction","kind":"measurement","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"stylometry","claim":"Kirner-Ludwig measures function words at about 43% of the Game of Thrones transcript corpus.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"Function words make up for ca. 43% of the corpus","page":"section 5","kind":"measurement","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"stylometry","claim":"Kirner-Ludwig finds that only 7.6% of the transcripts' lexical word stock belongs to the medieval and fantasy-medieval semantic fields she investigated.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"only 7.6% responded to the lexico-semantic fields","page":"section 5, discussion of Table 3","kind":"measurement","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw capture","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"naming and forms of address","claim":"Kirner-Ludwig measures 42,426 tokens, 8.38% of her corpus, as names of persons, places and languages.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"42,426 tokens (8.38%) cover names of persons, places and languages","page":"endnote 6","kind":"measurement","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw capture","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Kirner-Ludwig asserts that Martin himself lacks expert knowledge of the historical stages of English.","source":"Monika Kirner-Ludwig, Springer VS chapter, 2022","url":KL,"quote":"That is even true for George R. R. Martin himself.","page":"section 4, on archaisms versus pseudo-archaisms","kind":"analysis","polarity":"asserts","date":"2022-06-22","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},

 # PNAS
 {"feature":"point of view and distance","claim":"The PNAS study states that A Song of Ice and Fire is presented from the personal perspectives of 24 point of view characters.","source":"Gessey-Jones et al., PNAS 117(46), 2020","url":PN,"quote":"presented from the personal perspectives of 24 point of view (POV) characters","page":"Results, first paragraph","kind":"measurement","polarity":"asserts","date":"2020","routeHint":"Warwick WRAP author PDF, pypdf text (note: the PDF uses fi and fl ligatures, so avoid quotations containing those letter pairs)","registerHint":"none","confidence":"high"},
 {"feature":"point of view and distance","claim":"The PNAS study counts 14 of the point of view characters as major, defined as having eight or more chapters.","source":"Gessey-Jones et al., PNAS 117(46), 2020","url":PN,"quote":"we consider 14 to be major: eight or more chapters","page":"Results, first paragraph","kind":"measurement","polarity":"asserts","date":"2020","routeHint":"Warwick WRAP author PDF","registerHint":"none","confidence":"high"},
 {"feature":"other: book and chapter length","claim":"The PNAS study counts 343 chapters across the five published novels and identifies 2,007 characters in them.","source":"Gessey-Jones et al., PNAS 117(46), 2020","url":PN,"quote":"343 chapters, 2,007 characters were identified","page":"Results, 'Evolution of the Social Network Structure'","kind":"measurement","polarity":"asserts","date":"2020","routeHint":"Warwick WRAP author PDF","registerHint":"none","confidence":"high"},
 {"feature":"other: cast size","claim":"The PNAS study finds 1,806 of the identified characters interact with another character at least once.","source":"Gessey-Jones et al., PNAS 117(46), 2020","url":PN,"quote":"of which 1,806 interact with another at least once","page":"Results, 'Evolution of the Social Network Structure'","kind":"measurement","polarity":"asserts","date":"2020","routeHint":"Warwick WRAP author PDF","registerHint":"none","confidence":"high"},
 {"feature":"withheld information and inference","claim":"The PNAS study finds the intervals between significant deaths measured in chapters are geometrically rather than power-law distributed, which it reads as measurable support for the deaths being unpredictable chapter by chapter.","source":"Gessey-Jones et al., PNAS 117(46), 2020","url":PN,"quote":"it is geometric rather than power law","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2020","routeHint":"Warwick WRAP author PDF","registerHint":"chronicle-line","confidence":"high"},
 {"feature":"other: discourse order versus story order","claim":"The PNAS study reports that the order and pacing of deaths differ greatly between discourse time and story time in the novels.","source":"Gessey-Jones et al., PNAS 117(46), 2020","url":PN,"quote":"differ greatly between discourse time and story time","page":"Discussion","kind":"measurement","polarity":"asserts","date":"2020","routeHint":"Warwick WRAP author PDF","registerHint":"chronicle-line","confidence":"high"},

 # Vale
 {"feature":"point of view and distance","claim":"Vale counts 24 point of view characters in the first five novels once prologue and epilogue chapters are set aside.","source":"Richard Vale, 'Bayesian Prediction for The Winds of Winter', arXiv:1409.5830, 2014","url":VA,"quote":"24 characters have had chapters told from their point of view","page":"section 1.1","kind":"measurement","polarity":"asserts","date":"2014-09-19","routeHint":"arXiv PDF, pypdf text extraction","registerHint":"none","confidence":"high"},

 # Kyrchanoff
 {"feature":"civic record register","claim":"Kyrchanoff argues that the authors of The World of Ice and Fire imitated the style of the medieval chronicle and synthesised it with simplified modern historical representations.","source":"Maksim W. Kyrchanoff, Journal of Frontier Studies 2018 no. 1","url":KY,"quote":"actually imitated the style of the medieval chronicle","page":"body of the article","kind":"analysis","polarity":"asserts","date":"2018","routeHint":"CyberLeninka PDF, pypdf text extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"annalist voice and deep time","claim":"Kyrchanoff notes the imagined chronicler of The World of Ice and Fire gives the age of the world as a range from 40 to 500 thousand years rather than a fixed figure.","source":"Maksim W. Kyrchanoff, Journal of Frontier Studies 2018 no. 1","url":KY,"quote":"his estimates ranged from 40 to 500 thousand years","page":"body of the article","kind":"analysis","polarity":"asserts","date":"2018","routeHint":"CyberLeninka PDF, pypdf text extraction","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"The passage Kyrchanoff quotes from The World of Ice and Fire page 79 shows the chronicler correcting his own titulature in a parenthesis, noting Dorne had not submitted.","source":"Martin, Antonsson and Garcia, The World of Ice and Fire (2014), p. 79, as quoted by Kyrchanoff (2018)","url":KY,"quote":"was the style used, though Dorne had not submitted","page":"body of the article, quoting Martin, Antonsson, & Garcia, 2014, p. 79","kind":"analysis","polarity":"applies","date":"2014 book quoted in a 2018 article","routeHint":"CyberLeninka PDF, pypdf text extraction","registerHint":"dossier-archivist","confidence":"high"},
]
json.dump(d, open(OUT,'w'), indent=1, ensure_ascii=False)
print("claims",len(d["claims"]),"sources",len(d["sourcesRead"]))
