import json,os
OUT="found-wolfe-craft.json"
COV=("Angle named no URL roster, only critics: Wright FETCHED (Confounding the Skin and the Mask, Ultan 2002; his BotNS review was already in the pooled state), "
 "Andre-Driussi FETCHED (two Ultan interviews plus Posthistory 201), Gaiman NOT NEW (the WolfeWiki page is a pointer only; the primary sfsite text is already in the pooled state), "
 "Clute NOT FETCHED at primary (only quoted inside Sini), Le Guin NOT FOUND as a craft essay (only a relayed blurb in Barach), Borski NOT FOUND online at primary. "
 "Substantive per route: lateral search 13 (Gladstone, Holland, Alex/jafrank, Sini, Keeley x2, Polansky, Swanwick x2, Barach, Elliot, Noel, schicksalgemeinschaft), "
 "bibliography chasing from the Ultan and WolfeWiki indexes 8 (Novice guide, Wright, Wowra x2, Andre-Driussi x2, Palmer, Cooney), game-designer route 1 substantive (Leo Hunt on Vaults of Vaarn) "
 "plus 2 logged non-substantive (noisms, The Alexandrian). BLOCKED/NOT FOUND: lofkinreview 403, conceptualfiction 404, cwhowell and donbeck1 404 at guessed slugs, scatterings1976 empty body, DuckDuckGo HTML refused. "
 "WebSearch budget was exhausted mid-sweep (200/200), so the last expansion ran by index-crawling ultan.org.uk rather than by search; reactormag is fetchable by curl with a browser UA despite the earlier round recording 403.")
S=[]
C=[]
def src(title,url,kind,sub,date=None,route="curl browser-UA raw HTML"):
    S.append({"title":title,"url":url,"kind":kind,"substantive":sub,"date":date,"route":route})
def cl(feature,claim,source,url,quote,page=None,kind="analysis",polarity="asserts",date=None,routeHint="curl browser-UA raw HTML",registerHint="none",confidence="high"):
    C.append({"feature":feature,"claim":claim,"source":source,"url":url,"quote":quote,"page":page,"kind":kind,"polarity":polarity,"date":date,"routeHint":routeHint,"registerHint":registerHint,"confidence":confidence})

G="https://maxgladstone.substack.com/p/the-wolfeman"
src("The Wolfeman",G,"analysis",True,"2022-10-14")
cl("withheld information and inference","Novelist Max Gladstone says Wolfe's readers build interpretations by connecting sentences hundreds of pages apart rather than from anything stated outright.","Max Gladstone, 'The Wolfeman', The Third Place (Substack), 2022",G,"building theories by rubbing together two sentences two hundred pages apart","body, para 4",date="2022-10-14",registerHint="dossier-archivist")
cl("point of view and distance","Gladstone says Wolfe's narrators claim eidetic memory and perfect recall and honesty, and then lie or forget.","Max Gladstone, 'The Wolfeman', The Third Place (Substack), 2022",G,"They assert their eidetic memories and perfect recall and utter honesty","body, para 8",date="2022-10-14")
cl("omission as information","Gladstone says an elision in a Wolfe text can carry large implications a casual reader will not see.","Max Gladstone, 'The Wolfeman', The Third Place (Substack), 2022",G,"vast churning implications invisible to the casual reader","body, para 2",date="2022-10-14",registerHint="dossier-archivist")
cl("withheld information and inference","Gladstone describes reading Wolfe as assembling clues by touch in the dark rather than being told.","Max Gladstone, 'The Wolfeman', The Third Place (Substack), 2022",G,"We fumble through darkness, trying to assemble clues by touch.","body, para 8",date="2022-10-14")
cl("other: authorial signature detail","Gladstone says some details Wolfe plants are the author's signature to the audience rather than evidence about the story world.","Max Gladstone, 'The Wolfeman', The Third Place (Substack), 2022",G,"Wolfe loves to include winking asides between author and audience.","body, para 9",date="2022-10-14",confidence="medium")

H="https://floydholland.substack.com/p/the-enchanting-prose-of-gene-wolfe"
src("The Enchanting Prose of Gene Wolfe",H,"analysis",True,"2025-01-03")
cl("parataxis vs hypotaxis","Floyd Holland characterises Wolfe's prose as dense and built with parentheticals and complicating clauses.","Floyd Holland, 'The Enchanting Prose of Gene Wolfe' (Substack), 2025",H,"the dense prose, interjecting itself with parentheticals and complicating clauses","after the 5HC excerpt",date="2025-01-03")
cl("plainness and economy","Holland says Wolfe never lets a sentence run away from him, reading an aura of control across the prose.","Floyd Holland, 'The Enchanting Prose of Gene Wolfe' (Substack), 2025",H,"One never feels he let a sentence get away from him","penultimate section",date="2025-01-03")
cl("diction (native vs latinate)","Holland attributes the beauty of Wolfe's otherwise unwieldy sentences to word choice and confidence of construction.","Floyd Holland, 'The Enchanting Prose of Gene Wolfe' (Substack), 2025",H,"made beautiful by careful word choice and a certain confidence of construction","penultimate section",date="2025-01-03")
cl("point of view and distance","Wolfe, quoted by Holland, said real people are unreliable narrators all the time.","Gene Wolfe, quoted by Floyd Holland (Substack), 2025",H,"Real people really are unreliable narrators all the time","after the 5HC excerpt",kind="relay",date="2025-01-03",confidence="medium")
cl("withheld information and inference","Holland says the opening scene of The Fifth Head of Cerberus carries clues to a larger mystery while reading as ordinary recollection.","Floyd Holland, 'The Enchanting Prose of Gene Wolfe' (Substack), 2025",H,"the scene is peppered with clues to the larger story","after the 5HC excerpt",date="2025-01-03",registerHint="dossier-archivist")

J="https://jafrank09.substack.com/p/whose-afraid-of-the-big-bad-wolfe"
src("Whose Afraid of the Big Bad Wolfe?",J,"analysis",True,"2025-07-22")
cl("opening sentence","In a sentence-level reading of the opening paragraph of The Fifth Head of Cerberus, Alex notes it shows no genre markers at all.","Alex, 'Whose Afraid of the Big Bad Wolfe?' (Substack), 2025",J,"There are no obvious genre trappings in this opening paragraph, at all.","section 'What can an opening teach you?'",date="2025-07-22",registerHint="dossier-archivist")
cl("omission as information","Alex says what is absent from Wolfe's opening paragraph, not what is present, is what is notable about it.","Alex, 'Whose Afraid of the Big Bad Wolfe?' (Substack), 2025",J,"What’s noticeable here is not what’s present but what’s missing.","section 'What can an opening teach you?'",date="2025-07-22")
cl("place and institution description","Alex says the opening grounds the reader in concrete spatial description of the narrator's house, naming the orientation of its wings and courtyard.","Alex, 'Whose Afraid of the Big Bad Wolfe?' (Substack), 2025",J,"grounded in a narrator’s spatial description that is concrete","section 'What can an opening teach you?'",date="2025-07-22",registerHint="dossier-archivist")
cl("concrete sensory noun","Alex says Wolfe makes odd details register as stranger by setting them among mundane ones.","Alex, 'Whose Afraid of the Big Bad Wolfe?' (Substack), 2025",J,"weird details feel all the weirder when they are grounded","final section",date="2025-07-22",registerHint="dossier-archivist")
cl("omission as information","Alex says the detail Wolfe leaves unexplained reads as more real than an explanation of it would.","Alex, 'Whose Afraid of the Big Bad Wolfe?' (Substack), 2025",J,"These little opacities feel ‘realer’ than any explanation of them would.","final section",date="2025-07-22",registerHint="dossier-archivist")
cl("withheld information and inference","Alex says the brothers' unexplained soundless gestures imply a private life the reader is never given access to.","Alex, 'Whose Afraid of the Big Bad Wolfe?' (Substack), 2025",J,"hint at a private life that the reader never gets access to","final section",date="2025-07-22")

SI="https://newmythologies.substack.com/p/great-uncle-gene"
src("Great Uncle Gene",SI,"analysis",True,"2023-07-17")
cl("cadence and rhythm","Writer Matthew Sini says Wolfe's sentences work at the level of rhythm and structure.","Matthew Sini, 'Great Uncle Gene', New Mythologies (Substack), 2023",SI,"they hit at the level of rhythm and structure","para 4",date="2023-07-17")
cl("withheld information and inference","Sini says the presence Wolfe's sentences summon has contours that are not clearly defined and yet are not vague.","Matthew Sini, 'Great Uncle Gene', New Mythologies (Substack), 2023",SI,"its contours aren’t always clearly defined, but it’s also not vague","para 4",date="2023-07-17",confidence="medium")
cl("point of view and distance","Sini says much of Wolfe's world is withheld from the reader by the narrowness of the narrator's perception.","Matthew Sini, 'Great Uncle Gene', New Mythologies (Substack), 2023",SI,"kept from us due to the narrowness of the narrator’s perception","closing section",date="2023-07-17",registerHint="dossier-archivist")

W="https://www.wolfewiki.com/pmwiki/pmwiki.php?n=Articles.Novice"
src("Where to Begin? A Novice's Guide to the Lupine Maze",W,"analysis",True,"2017-11-17")
cl("withheld information and inference","The WolfeWiki novice guide reports Wolfe said he does not give important information twice.","WolfeWiki, 'Where to Begin? A Novice's Guide to the Lupine Maze', last modified 2017",W,"he doesn't give the important information twice","section 'Hints for Beginners'",kind="relay",date="2017-11-17")
cl("withheld information and inference","The guide advises reading an apparent contradiction as a hint that the narrator is concealing something.","WolfeWiki, 'Where to Begin? A Novice's Guide to the Lupine Maze', last modified 2017",W,"Apparent contradictions are often useful hints that the narrator is concealing something.","section 'Hints for Beginners'",polarity="applies",date="2017-11-17",registerHint="dossier-archivist")
cl("omission as information","The guide asserts the information a reader needs is always present in a Wolfe text, though not where the reader expects it.","WolfeWiki, 'Where to Begin? A Novice's Guide to the Lupine Maze', last modified 2017",W,"The information you need is always there","section 'Hints for Beginners'",date="2017-11-17",registerHint="dossier-archivist")
cl("per-speaker register","The guide says Wolfe works out what a narrator would say rather than what the author wants to say.","WolfeWiki, 'Where to Begin? A Novice's Guide to the Lupine Maze', last modified 2017",W,"what they would say, rather than what he wants to say","section 'Hints for Beginners'",date="2017-11-17",registerHint="chronicle-line")
cl("point of view and distance","The guide tells a new reader to begin by asking who is telling the story, when, why, and to whom.","WolfeWiki, 'Where to Begin? A Novice's Guide to the Lupine Maze', last modified 2017",W,"Who is telling this story, and when? Why are they telling it","section 'Hints for Beginners'",polarity="applies",date="2017-11-17")

K1="https://reactormag.com/how-gene-wolfe-starts-a-story-and-where-to-start-reading-his-work/"
src("How Gene Wolfe Starts a Story (and Where to Start Reading His Work)",K1,"analysis",True,"2017-11-09")
cl("opening sentence","Matthew Keeley says the grammar of the opening sentence of The Fifth Head of Cerberus carries a clue to the story.","Matthew Keeley, Tor.com/Reactor, 2017",K1,"a slight clue to the story in the sentence’s grammar","body, para 4",date="2017-11-09",registerHint="dossier-archivist")
cl("withheld information and inference","Keeley reads the absent comma in the phrase naming the narrator's brother as a detail the book later explains.","Matthew Keeley, Tor.com/Reactor, 2017",K1,"We eventually do learn why that comma is missing.","body, para 4",date="2017-11-09",registerHint="dossier-archivist")
cl("point of view and distance","Keeley says one first-person sentence near the end of an otherwise third-person Wolfe book makes the reader reconsider all of it.","Matthew Keeley, Tor.com/Reactor, 2017",K1,"asks readers to reconsider everything that they’ve already read","body, para 5",date="2017-11-09")

K2="https://reactormag.com/the-best-way-to-approach-the-book-of-the-new-sun/"
src("The Best Way to Approach The Book of the New Sun",K2,"analysis",True,"2017-12-04")
cl("archaism","Keeley says every word in The Book of the New Sun can be found in a dictionary, so the strangeness is not neologism.","Matthew Keeley, Tor.com/Reactor, 2017",K2,"every word in the book appears in a dictionary","advice 1",date="2017-12-04",registerHint="dossier-archivist")
cl("diction (native vs latinate)","Keeley says the rare words in The Book of the New Sun were chosen to be evocative rather than specific.","Matthew Keeley, Tor.com/Reactor, 2017",K2,"chosen to be evocative, rather than specific","advice 1",date="2017-12-04",registerHint="dossier-archivist")
cl("archaism","Wolfe's appendix to The Shadow of the Torturer, quoted by Keeley, says substituted words like peltast and exultant are meant to be suggestive rather than definitive.","Gene Wolfe, appendix to The Shadow of the Torturer, quoted by Matthew Keeley (Tor.com, 2017)",K2,"are intended to be suggestive rather than definitive","advice 1, block quotation",kind="relay",date="2017-12-04",registerHint="dossier-archivist")
cl("omission as information","Keeley advises the reader to attend to Severian's sins of omission.","Matthew Keeley, Tor.com/Reactor, 2017",K2,"Pay attention to his sins of omission","advice 3",polarity="applies",date="2017-12-04",registerHint="dossier-archivist")
cl("point of view and distance","Keeley says Severian self-justifies and misinterprets but rarely lies outright.","Matthew Keeley, Tor.com/Reactor, 2017",K2,"He self-justifies and misinterprets, but rarely lies outright.","advice 3",date="2017-12-04")
cl("withheld information and inference","Keeley says a small detail in one volume of The Book of the New Sun frequently presages a large revelation in a later one.","Matthew Keeley, Tor.com/Reactor, 2017",K2,"a small detail in one book frequently presages a large revelation","advice 5",date="2017-12-04",registerHint="dossier-archivist")

# non-substantive / logged
src("On Gene Wolfe and the Feeling of Being Inspired","https://monstersandmanuals.blogspot.com/2023/03/on-gene-wolfe-and-feeling-of-being.html","analysis",False,"2023-03-14")
src("Gene Wolfe's Writing Rules","https://brianbiswas.com/blog/2015/wolfewritingrules","relay",False,"2015-03-27")


SW="http://floggingbabel.blogspot.com/2016/05/how-to-read-gene-wolfe.html"
src("How to Read Gene Wolfe (reposting 'The Wolf in the Labyrinth', F&SF 2007)",SW,"analysis",True,"2016-05-09")
cl("plainness and economy","Novelist Michael Swanwick rates Wolfe's prose as good as prose gets, in a beginners' guide first printed in F&SF in 2007.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"his prose is as good as prose gets","essay, para 3",kind="reception",date="2016-05-09")
cl("withheld information and inference","Swanwick says Wolfe is notorious for never explaining his stories, so no reader can tell where interpretation stops.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"Gene Wolfe is notorious for never explaining his stories","essay, on 'A Solar Labyrinth'",date="2016-05-09",registerHint="dossier-archivist")
cl("withheld information and inference","Swanwick's first rule for reading Wolfe is to look for hidden implications.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"Look for hidden implications.","essay, the three rules",polarity="applies",date="2016-05-09")
cl("concrete sensory noun","Swanwick's second rule for reading Wolfe is to pay serious attention to the obvious, citing Poe's purloined letter.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"Remember Poe\u2019s purloined letter, and pay serious attention to the obvious.","essay, the three rules",polarity="applies",date="2016-05-09",registerHint="dossier-archivist")
cl("omission as information","Swanwick tells the reader of the story 'Memorare' to look up the prayer of that name to see what Wolfe left out of it.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"look up the prayer to see what Wolfe left out","essay, on 'Memorare'",polarity="applies",date="2016-05-09",registerHint="dossier-archivist")
cl("plainness and economy","Swanwick warns that a Wolfe story's surface meaning cannot be ignored merely because the story also has deeper levels.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"simply because a story has deeper levels, its surface meaning can be","essay, after the Solar Labyrinth section",polarity="disputes",date="2016-05-09")
cl("withheld information and inference","Swanwick says Wolfe always leaves room in his work for more than one interpretation.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"Wolfe always leaves room for multiple interpretations in his work.","essay, on 'Memorare'",date="2016-05-09")
cl("concrete sensory noun","Swanwick points to the engineering detail of the suits and cenotaphs in 'Memorare' as craftsmanship on the story's surface.","Michael Swanwick, 'The Wolf in the Labyrinth', F&SF 2007, reposted on Flogging Babel 2016",SW,"Note the careful engineering of the suits and cenotaphs.","essay, on 'Memorare'",date="2016-05-09",registerHint="dm-page")
cl("other: authorial statement of method","Wolfe, quoted by Swanwick from his short essay 'What I Know About Writing (in no particular order)', wrote that an interesting work of art comes close to saying the opposite of what it says.","Gene Wolfe, 'What I Know About Writing (in no particular order)', quoted by Michael Swanwick",SW,"Almost any interesting work of art comes close to saying the opposite","essay, mid-piece",kind="relay",date="2016-05-09",confidence="medium")

SX="http://floggingbabel.blogspot.com/2009/10/explicated-gene-wolfe_07.html"
src("The Explicated Gene Wolfe",SX,"analysis",True,"2009-10-07")
cl("withheld information and inference","Swanwick says annotation pays off on Wolfe because he puts more into his works than almost any other writer.","Michael Swanwick, 'The Explicated Gene Wolfe', Flogging Babel, 2009",SX,"so much more into his works than almost any other writer","body, para 3",date="2009-10-07")
cl("omission as information","Swanwick likens Wolfe's buried details to programmers' Easter eggs, not needed for enjoying the story.","Michael Swanwick, 'The Explicated Gene Wolfe', Flogging Babel, 2009",SX,"not necessary for your enjoyment of the experience","body, after the fuligin example",date="2009-10-07",registerHint="dossier-archivist")

BA="https://barach.us/2007/03/03/how-to-read-gene-wolfe/"
src("How to Read Gene Wolfe (Kata Iwannhn)",BA,"relay",True,"2007-03-03")
cl("withheld information and inference","John Barach reports Wolfe's own statement that he gives a clue only once.","John Barach, 'How to Read Gene Wolfe', Kata Iwannhn blog, 2007",BA,"he gives a clue only once","body, para 6",kind="relay",date="2007-03-03",registerHint="dossier-archivist")

EL="https://liviajelliot.com/blog/2024/17-podcast-worldbuilding/"
src("The Puzzle Left Behind: On Worldbuilding Through Omission",EL,"analysis",True,"2024-10-03")
cl("omission as information","Ada Palmer's foreword to the Tor Essentials Shadow & Claw, quoted by Livia J. Elliot, says reading for world-building requires retaining information without context.","Ada Palmer, foreword to Shadow & Claw (Tor Essentials), quoted by Livia J. Elliot, 2024",EL,"Reading for world-building requires retaining information without context","transcript, quoting the foreword",kind="relay",date="2024-10-03",registerHint="dossier-archivist")
cl("omission as information","Author Livia J. Elliot says Wolfe often gives information about the world without context.","Livia J. Elliot, 'The Puzzle Left Behind', Books Undone ep. 010 transcript, 2024",EL,"give information about the world without context","transcript, after the Palmer quotation",date="2024-10-03",registerHint="dossier-archivist")
cl("place and institution description","Elliot says one reason a world term goes unexplained is that the characters already know the concept even though it is foreign to the reader.","Livia J. Elliot, 'The Puzzle Left Behind', Books Undone ep. 010 transcript, 2024",EL,"the characters may already know about those concepts","transcript, the three reasons",date="2024-10-03",registerHint="dossier-archivist")
cl("annalist voice and deep time","Elliot says a third reason a term goes unexplained is that the society has forgotten or misinterpreted its own history.","Livia J. Elliot, 'The Puzzle Left Behind', Books Undone ep. 010 transcript, 2024",EL,"perhaps the society has forgotten or misinterpreted its own history","transcript, the three reasons",date="2024-10-03",registerHint="chronicle-line")
cl("omission as information","Elliot says the combination of the three kinds of omission is what adds realism to the world-building.","Livia J. Elliot, 'The Puzzle Left Behind', Books Undone ep. 010 transcript, 2024",EL,"these three types of omission adds a level of realism","transcript, after the three reasons",date="2024-10-03",registerHint="dossier-archivist")
cl("annalist voice and deep time","Elliot says the incomprehensible fragments of a world's history are what make its world-building stand out.","Livia J. Elliot, 'The Puzzle Left Behind', Books Undone ep. 010 transcript, 2024",EL,"those bits of incomprehensible history are what makes the world-building pop","transcript, later section",date="2024-10-03",registerHint="chronicle-line")
cl("withheld information and inference","Elliot says Wolfe is an author who does not aid the reader by explaining concepts.","Livia J. Elliot, 'The Puzzle Left Behind', Books Undone ep. 010 transcript, 2024",EL,"do not aid the reader by explaining concepts","transcript, on entry barriers",date="2024-10-03")

LH="https://bucoliablog.wordpress.com/2022/08/27/interview-leo-hunt/"
src("Interview: Leo Hunt (Vaults of Vaarn)",LH,"own-words",True,"2022-08-27")
cl("archaism","Game designer Leo Hunt names the obscure and archaic language of The Book of the New Sun as a setting element he took into Vaults of Vaarn.","Leo Hunt, interviewed at Bucolia, 2022",LH,"the obscure and archaic language that\u2019s employed","interview, second question",kind="own-words",date="2022-08-27",registerHint="dm-page")
cl("annalist voice and deep time","Hunt names the melancholic weight of hundreds of extinguished civilisations on the present day as a Wolfe element carried into his game setting.","Leo Hunt, interviewed at Bucolia, 2022",LH,"the melancholic weight of hundreds of extinguished civilisations","interview, second question",kind="own-words",date="2022-08-27",registerHint="dm-page")

RP="https://reactormag.com/the-mysteries-of-gene-wolfes-peace-and-why-they-keep-me-up-at-night/"
src("The Mysteries of Gene Wolfe's Peace (and Why They Keep Me Up at Night)",RP,"analysis",True,"2015-10-20")
cl("withheld information and inference","Novelist Daniel Polansky says the narrator's sins in Peace are hidden but identifiable by the scars they leave in his memory.","Daniel Polansky, Tor.com/Reactor, 2015",RP,"they can be identified by the scars they leave in his memory","body, para 7",date="2015-10-20",registerHint="dossier-archivist")
cl("omission as information","Polansky says the narrative of Peace is riddled with ambiguities and contradictions and with holes the reader is encouraged to investigate.","Daniel Polansky, Tor.com/Reactor, 2015",RP,"riddled with ambiguities and contradictions, with holes we are encouraged to investigate","body, para 7",date="2015-10-20",registerHint="dossier-archivist")
cl("withheld information and inference","Polansky says a reader can miss the clues in Peace entirely and still be moved by the book.","Daniel Polansky, Tor.com/Reactor, 2015",RP,"possible to miss the subtle clues with which the book is filled","body, para 8",date="2015-10-20")

src("Numenera: Welcome to the Ninth World","https://thealexandrian.net/wordpress/40081/roleplaying-games/numenera-welcome-to-the-ninth-world","analysis",False,"2016-08-16")
src("How to Read Gene Wolfe (pointer page)","https://www.wolfewiki.com/pmwiki/pmwiki.php?n=OnlineArticles.HowToReadGeneWolfe","relay",False,"2023-08-08")

SP="https://ultan.org.uk/palmer-me-gene/"
src("Me & Gene - by Stephen Palmer",SP,"analysis",True,"2015-08-04")
cl("withheld information and inference","SF novelist Stephen Palmer says his favourite books are the ones where only a proportion of the meaning is on the surface, and names Wolfe as the model.","Stephen Palmer, 'Me & Gene', Ultan's Library, 2015",SP,"only a proportion of the meaning is on the surface","body, para 10",kind="own-words",date="2015-08-04")
cl("withheld information and inference","Palmer says his own Wolfe-influenced novel was written so that much of its meaning is concealed and must be teased out by the reader.","Stephen Palmer, 'Me & Gene', Ultan's Library, 2015",SP,"the meaning is concealed and has to be teased out by the reader","body, on Urbis Morpheos",kind="own-words",date="2015-08-04",confidence="medium")

AU="https://ultan.org.uk/the-reader-as-augur/"
src("The Reader as Augur: Beginnings and Endings in The Book of the Long Sun",AU,"analysis",True,"2000-09-05")
cl("opening sentence","Critic Nick Gevers says every opening passage of The Book of the Long Sun stages a dialogue between a naive figure and one who holds privileged information.","Nick Gevers, 'The Reader as Augur', Ultan's Library, 2000",AU,"a figure possessing privileged information, which he will only yield up","article, section on Nightside",date="2000-09-05",registerHint="chronicle-line")
cl("opening sentence","Gevers reads the opening passage of Nightside the Long Sun as a warning that interpreting the evidence given demands great care.","Nick Gevers, 'The Reader as Augur', Ultan's Library, 2000",AU,"great care must be exercised in interpreting divine or authorial evidence","article, section on Nightside",date="2000-09-05")
cl("repetition and refrain","Gevers describes a formal conceit of The Book of the New Sun by which any fragment of the text contains the essence of the whole.","Nick Gevers, 'The Reader as Augur', Ultan's Library, 2000",AU,"any fragment contains the essence of the whole","article, para 4",date="2000-09-05",registerHint="dossier-archivist")

DR="https://ultan.org.uk/tell-me-about-the-lexicon-urthus-an-interview-with-michael-andre-driussi/"
src("Tell Me About the Lexicon Urthus: an interview with Michael Andre-Driussi",DR,"own-words",True,"2008-09-25")
cl("archaism","Michael Andre-Driussi says Wolfe himself stated in the essay 'Words Weird and Wonderful' that the Urth Cycle's strange words are real words, not coinages.","Michael Andre-Driussi, interviewed at Ultan's Library, 2008",DR,"that\u2019s what Wolfe himself said in \u201cWords Weird and Wonderful.\u201d","interview, on real words",kind="relay",date="2008-09-25",registerHint="dossier-archivist")
cl("naming and forms of address","Andre-Driussi says Wolfe uses naming schemes by group in the Urth Cycle, among them naming people of the Commonwealth after Catholic saints.","Michael Andre-Driussi, interviewed at Ultan's Library, 2008",DR,"naming people in the Commonwealth after Catholic saints","interview, on naming schemes",date="2008-09-25",registerHint="dossier-archivist")

PN="https://ultan.org.uk/place-names-in-gene-wolfes-soldier-of-the-mist/"
src("Place Names in Gene Wolfe's Soldier of the Mist",PN,"analysis",True,"2016-09-07")
cl("naming and forms of address","Wolfe's foreword to Soldier of the Mist, quoted by Scott Wowra, says the narrator sometimes wrote place names as he heard them and more often translated them.","Gene Wolfe, foreword to Soldier of the Mist (1986), quoted by Scott Wowra, Ultan's Library, 2016",PN,"sometimes wrote them as he heard them but more often translated them","essay, introduction",kind="relay",date="2016-09-07",registerHint="dossier-archivist")
cl("naming and forms of address","Wowra says folk etymology is the primary method by which the narrator of Soldier of the Mist records place names.","Scott Wowra, 'Place Names in Gene Wolfe's Soldier of the Mist', Ultan's Library, 2016",PN,"it is the primary method Latro uses to record his place names","essay, introduction",date="2016-09-07",registerHint="dossier-archivist")
cl("naming and forms of address","Classifying the place names by a toponymic taxonomy, Wowra finds folk etymology the predominant category.","Scott Wowra, 'Place Names in Gene Wolfe's Soldier of the Mist', Ultan's Library, 2016",PN,"The predominant category is folk etymology","essay, section 'Toponymy'",kind="measurement",date="2016-09-07",registerHint="dossier-archivist")
cl("naming and forms of address","Wowra says the narrator's place names are generated by four processes: folk etymology, association, description and commemoration.","Scott Wowra, 'Place Names in Gene Wolfe's Soldier of the Mist', Ultan's Library, 2016",PN,"folk etymology, association, description, and commemoration","essay, introduction",date="2016-09-07",registerHint="dossier-archivist")
cl("place and institution description","Wowra glosses the narrator's name for Laconia, Silent Country, by the Spartans' renowned brevity of speech.","Scott Wowra, 'Place Names in Gene Wolfe's Soldier of the Mist', Ultan's Library, 2016",PN,"Spartans were renowned for brevity in speech","essay, folk etymology table",date="2016-09-07",registerHint="dossier-archivist")
cl("naming and forms of address","Wolfe, in a 1988 Weird Tales interview quoted by Wowra, said the narrator calls Athens Thought because that is what he thinks the name means.","Gene Wolfe, Weird Tales interview with Darrell Schweitzer, Spring 1988, quoted by Scott Wowra",PN,"Latro calls Athens Thought because that\u2019s what he thinks it means","essay, block quotation",kind="relay",date="2016-09-07",registerHint="dossier-archivist")

SC="https://schicksalgemeinschaft.wordpress.com/2021/05/16/the-book-of-the-new-sun-gene-wolfe-1980-83/"
src("THE BOOK OF THE NEW SUN - Gene Wolfe (1980-83)",SC,"analysis",True,"2021-05-16")
cl("withheld information and inference","In a reread essay the blogger says Severian does not tell the reader certain things straight away.","'Weighing a pig doesn't fatten it' blog, reread essay on The Book of the New Sun, 2021",SC,"he doesn\u2019t tell certain things to the reader straight away","essay, section 1",date="2021-05-16",registerHint="dossier-archivist")
cl("point of view and distance","The same essay disputes the common claim that Severian lies to the reader, holding that he does not.","'Weighing a pig doesn't fatten it' blog, reread essay on The Book of the New Sun, 2021",SC,"he doesn\u2019t lie to the reader","essay, section 1",polarity="disputes",date="2021-05-16")
cl("archaism","The essay says the found-text conceit is what motivates the obscure words for animals and things that do not yet exist.","'Weighing a pig doesn't fatten it' blog, reread essay on The Book of the New Sun, 2021",SC,"had to resort to obscure words to use for animals and things","essay, the three reasons",date="2021-05-16",registerHint="dossier-archivist")

NO="https://noelvee.wordpress.com/2015/06/03/on-fiction-writing-restraint-subtlety-unreliable-narrators-and-gene-wolfe/"
src("[On Fiction-Writing] Restraint, subtlety, unreliable narrators, and Gene Wolfe",NO,"analysis",True,"2015-06-03")
cl("place and institution description","Fiction writer Noel says Wolfe describes his world as an actual inhabitant of that world would describe it.","Noel, 'Stuff about a thing' blog, 2015",NO,"describes his world in a way that an actual character","body, on The Book of the New Sun",date="2015-06-03",registerHint="dossier-archivist")
cl("adjective and adverb discipline","Noel says the strange creatures of the world get only the barest descriptions of their nature.","Noel, 'Stuff about a thing' blog, 2015",NO,"we only get the barest of descriptions as to their nature","body, on The Book of the New Sun",date="2015-06-03",registerHint="dossier-archivist")
cl("omission as information","Noel says the most interesting stories arise from the untold details.","Noel, 'Stuff about a thing' blog, 2015",NO,"the most interesting stories arise from the untold details","body, closing",date="2015-06-03")
cl("civic record register","Noel rejects world history delivered as if written in books, asking instead for history that surfaces from a character's interaction with surroundings.","Noel, 'Stuff about a thing' blog, 2015",NO,"don\u2019t tell me histories as if they were written in books","body, closing",polarity="rejects",date="2015-06-03",registerHint="chronicle-line")

GS="https://faithandsciencefiction.blogspot.com/2022/02/writing-advice-short-stories-advice-and.html"
src("WRITING ADVICE: Short Stories - Advice and Observation #14: Gene Wolfe '& Me'",GS,"relay",True,"2022-02-12")
cl("other: characterisation method","Guy Stewart reports Wolfe's rule that a character is characterised by being shown thinking, speaking and acting in a characteristic way rather than described.","Gene Wolfe's writing advice, relayed by Guy Stewart, 2022",GS,"showing the character thinking, speaking and acting in a characteristic way","post, the five rules",kind="relay",polarity="applies",date="2022-02-12")

CF="https://ultan.org.uk/confounding-the-skin-and-the-mask/"
src("Confounding the Skin and the Mask: The Fifth Head of Cerberus and the Politics of Ambiguity",CF,"analysis",True,"2002-01-15")
cl("withheld information and inference","Critic Peter Wright says ambiguity in The Fifth Head of Cerberus is an organising principle of the book's form, not only a theme.","Peter Wright, 'Confounding the Skin and the Mask', Ultan's Library, 2002",CF,"it is also an organising principle of form","article, opening paragraph",date="2002-01-15",registerHint="dossier-archivist")
cl("withheld information and inference","Wright says the existence of the puzzle in The Fifth Head of Cerberus matters more than its solution.","Peter Wright, 'Confounding the Skin and the Mask', Ultan's Library, 2002",CF,"the existence of the puzzle is more significant that its solution","article, after the Wendland discussion",date="2002-01-15")

LU="https://ultan.org.uk/the-lupine-scholar-by-scott-wowra/"
src("'The Lupine Scholar' - an interview with Michael Andre-Driussi",LU,"analysis",True,"2009-05-21")
cl("archaism","Scott Wowra reports that readers in the early 1980s accused Wolfe of fabricating unusual words, and says this is untrue.","Scott Wowra, 'The Lupine Scholar', Ultan's Library, 2009",LU,"readers accused Mr. Wolfe of deliberately fabricating unusual words","introduction",polarity="disputes",date="2009-05-21",registerHint="dossier-archivist")
cl("archaism","Wowra says Wolfe's real rare words show how odd genuine language can sound without any invented vocabulary.","Scott Wowra, 'The Lupine Scholar', Ultan's Library, 2009",LU,"they remind us just how odd language can sound","introduction",date="2009-05-21",registerHint="dossier-archivist")
cl("diction (native vs latinate)","Wowra gives omophagist and cherkaji as examples of the seemingly counterfeit but real words in The Book of the New Sun.","Scott Wowra, 'The Lupine Scholar', Ultan's Library, 2009",LU,"omophagist (an eater of raw flesh) and cherkaji","introduction",date="2009-05-21",registerHint="dossier-archivist")

PH="https://ultan.org.uk/posthistory-201/"
src("Posthistory 201",PH,"measurement",True,"2020-07-06")
cl("annalist voice and deep time","Michael Andre-Driussi revises his estimate of the span from Ymar to Severian, giving a range between one thousand and thirty-thousand years.","Michael Andre-Driussi, 'Posthistory 201', Ultan's Library, 2020",PH,"the range is actually between one thousand and thirty-thousand years","section 2.1 Overview",kind="measurement",date="2020-07-06",registerHint="chronicle-line")
cl("annalist voice and deep time","Andre-Driussi derived his earlier thousand-year figure for the Autarchy from a single character's offhand remark rather than any stated chronology.","Michael Andre-Driussi, 'Posthistory 201', Ultan's Library, 2020",PH,"This statement strongly implied to me that the autarchs had reigned","section 2.2 Revising my estimate",date="2020-07-06",registerHint="chronicle-line")
cl("annalist voice and deep time","To narrow the chronology Andre-Driussi searched the text for the time words chiliads, thousand years, ages, aeons and eons.","Michael Andre-Driussi, 'Posthistory 201', Ultan's Library, 2020",PH,"a brute force method of searching for the terms","section 2.3 Narrowing the range",kind="measurement",date="2020-07-06",registerHint="chronicle-line")

src("What would it be like... (teaser for C. S. E. Cooney piece)","https://ultan.org.uk/what-would-it-be-like/","analysis",False,"2016-06-08")

CO="https://ultan.org.uk/an-homage-to-my-honorary-grandfather/"
src("An Homage to my Honorary Grandfather",CO,"own-words",True,"2016-06-10")
cl("plainness and economy","Wolfe, quoted from a letter by novelist C. S. E. Cooney, advised always telling a story as cleanly and as clearly as possible.","Gene Wolfe, in letters and conversation, quoted by C. S. E. Cooney, Ultan's Library, 2016",CO,"Always tell a story as cleanly and as clearly as possible.","memoir, later section",kind="relay",date="2016-06-10",registerHint="dossier-archivist")
cl("other: exposition and infodump","Wolfe's critique of Cooney's draft named her habit of interrupting dialogue with long infodumps, which he called lumps of prose like uncooked dumplings.","Gene Wolfe, letter to C. S. E. Cooney, quoted in Ultan's Library, 2016",CO,"lumps of prose like uncooked dumplings","memoir, on the first letter",kind="relay",polarity="rejects",date="2016-06-10",registerHint="dossier-archivist")
cl("cadence and rhythm","Cooney reports that when she proposed cutting the sing-song rhythm and internal rhyme from one story, Wolfe urged her not to.","C. S. E. Cooney, 'An Homage to my Honorary Grandfather', Ultan's Library, 2016",CO,"he urged me not to take my knife to it","memoir, after the clean-and-clear advice",date="2016-06-10",confidence="high")

json.dump({"complete":True,"coverage":COV,"sourcesRead":S,"claims":C},open(OUT,"w"),indent=1,ensure_ascii=False)
print(len(S),"sources",len(C),"claims")
