import json, re, os, sys
BASE=os.path.dirname(os.path.abspath(__file__)); WA=os.path.join(BASE,'wa')
def norm(s): return re.sub(r'\s+',' ',s)
FILES={}
def reg(url, path): FILES[url]=norm(open(os.path.join(WA,path),encoding='utf-8',errors='replace').read())
R_PDF="gwern.net raw PDF fetched with a browser user agent; text extracted locally from the macOS Quartz PDF text layer"
R_WEB="live URL fetched with a browser user agent (curl --compressed), HTML stripped to text locally"
R_WB="Wayback raw capture (web.archive.org/web/<ts>id_/<url>)"
G="https://gwern.net/doc/fiction/gene-wolfe/1999-gerlach.pdf"
F="https://gwern.net/doc/fiction/gene-wolfe/2007-farrell.pdf"
J="https://gwern.net/doc/fiction/gene-wolfe/1989-jones.pdf"
H="https://gwern.net/doc/fiction/gene-wolfe/2007-hall.pdf"
A="https://gwern.net/doc/fiction/gene-wolfe/2019-aramini.pdf"
UW="https://ultan.org.uk/confounding-the-skin-and-the-mask/"
UP="https://ultan.org.uk/place-names-in-gene-wolfes-soldier-of-the-mist/"
UG="https://ultan.org.uk/the-reader-as-augur/"
UB="https://ultan.org.uk/desanctifying-victor-trenchard/"
for u,p in [(G,'1999-gerlach.txt'),(F,'2007-farrell.txt'),(J,'1989-jones.txt'),(H,'2007-hall.txt'),(A,'2019-aramini.txt'),
            (UW,'u-confounding-the-skin-and-the-mask.txt'),(UP,'u-place-names-in-gene-wolfes-soldier-of-the-mist.txt'),
            (UG,'u-the-reader-as-augur.txt'),(UB,'u-desanctifying-victor-trenchard.txt')]:
    try: reg(u,p)
    except FileNotFoundError: print('missing',p)
GS="John Gerlach, 'The Rhetoric of an Impossible Object: Gods, Chems, and Science Fantasy in Gene Wolfe's Book of the Long Sun', Extrapolation vol. 40 no. 2 (1999), Kent State University Press"
FS="John Farrell, 'The Distant Suns of Gene Wolfe', First Things, April 2007"
JS="Gwyneth Jones, review of Gene Wolfe's There Are Doors, Foundation, Fall 1989 (Science Fiction Foundation)"
HS="Gene Wolfe, interviewed by Melissa Mia Hall, Amazing Science Fiction Stories, September 1981; reprinted as chapter 3 of Peter Wright (ed.), Shadows of the New Sun: Wolfe on Writing/Writers on Wolfe, Liverpool University Press, 2007"
WS="Peter Wright, 'Confounding the Skin and the Mask: Gene Wolfe's The Fifth Head of Cerberus and the Politics of Ambiguity', paper given at the Gene Wolfe conference, University of Birmingham, 26 August 2000; published in Ultan's Library, 15 January 2002"
POS="Scott Wowra, 'Place Names in Gene Wolfe's Soldier of the Mist', Ultan's Library, 7 September 2016"
GEV="Nick Gevers, 'The Reader as Augur: Beginnings and Endings in Gene Wolfe's The Book of the Long Sun', written 1998, published in Ultan's Library, 5 September 2000"
BOR="Robert Borski, 'Desanctifying Victor Trenchard: some notes on Peter Wright's Confounding the Skin and the Mask', Ultan's Library, 24 May 2002 (dated December 2001)"
ARA="Marc Anthony Aramini, 'Does It Mean? Gene Wolfe: Perverse Puzzle Maker', PhD dissertation, University of Nevada Las Vegas, May 2019"
SOURCES=[
 {"title":"John Gerlach, 'The Rhetoric of an Impossible Object' (Extrapolation 40.2, 1999)","url":G,"kind":"analysis","substantive":True,"date":"1999","route":R_PDF},
 {"title":"John Farrell, 'The Distant Suns of Gene Wolfe' (First Things, April 2007)","url":F,"kind":"analysis","substantive":True,"date":"2007-04","route":R_PDF},
 {"title":"Gwyneth Jones, review of There Are Doors (Foundation, Fall 1989)","url":J,"kind":"reception","substantive":True,"date":"1989","route":R_PDF},
 {"title":"Melissa Mia Hall interview with Gene Wolfe (Amazing, Sept 1981; repr. Shadows of the New Sun, Liverpool UP 2007)","url":H,"kind":"own-words","substantive":True,"date":"1981-09 / repr. 2007-08","route":R_PDF},
 {"title":"Marc Aramini, 'Does It Mean? Gene Wolfe: Perverse Puzzle Maker' (PhD dissertation, UNLV, 2019)","url":A,"kind":"analysis","substantive":True,"date":"2019-05","route":R_PDF+"; the UNLV Digital Scholarship copy returned 403, the gwern mirror of the same 315-page dissertation was used"},
 {"title":"Peter Wright, 'Confounding the Skin and the Mask' (Ultan's Library, 2002; Birmingham conference paper, 2000)","url":UW,"kind":"analysis","substantive":True,"date":"2002-01-15","route":R_WEB},
 {"title":"Scott Wowra, 'Place Names in Gene Wolfe's Soldier of the Mist' (Ultan's Library, 2016)","url":UP,"kind":"analysis","substantive":True,"date":"2016-09-07","route":R_WEB},
 {"title":"Nick Gevers, 'The Reader as Augur' (Ultan's Library, 2000)","url":UG,"kind":"analysis","substantive":True,"date":"2000-09-05","route":R_WEB},
 {"title":"Robert Borski, 'Desanctifying Victor Trenchard' (Ultan's Library, 2002)","url":UB,"kind":"analysis","substantive":True,"date":"2002-05-24","route":R_WEB},
 {"title":"Joan Gordon, Gene Wolfe (Starmont Reader's Guide 29, 1986)","url":"https://gwern.net/doc/fiction/gene-wolfe/1986-gordon-genewolfe.pdf","kind":"analysis","substantive":False,"date":"1986","route":"fetched (41MB scan); the Quartz text layer returns interleaved two-column OCR and no sentence is recoverable verbatim, so no claims were written from it"},
 {"title":"Thomas D. Clareson, 'The Launching Pad', SFRA Newsletter (1985)","url":"https://gwern.net/doc/fiction/gene-wolfe/1985-clareson.pdf","kind":"analysis","substantive":False,"date":"1985","route":R_PDF+"; read in full, a column on the state of sf criticism with Wolfe mentioned only in passing"},
 {"title":"'2005-green' (gwern.net Gene Wolfe document directory)","url":"https://gwern.net/doc/fiction/gene-wolfe/2005-green.pdf","kind":"analysis","substantive":False,"date":"2005","route":"fetched 200 OK but image-only scan, text extraction empty, blocked for quotation"},
]
CLAIMS=[
 {"feature":"place and institution description","claim":"Gerlach argues that the reader of The Book of the Long Sun comes to occupy its city as its inhabitants do, rather than being given an explanatory overview of it.","source":GS,"url":G,"quote":"we begin to inhabit much as the characters do","page":"p. 155","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Gerlach observes that the clues to the nature of Wolfe's world are so sparse that the reader's attention moves off the world question and onto the plot.","source":GS,"url":G,"quote":"clues are so sparse the reader will focus elsewhere","page":"p. 155","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"concrete sensory noun","claim":"Gerlach describes the fictional world of the Long Sun as built out of dense particulars, including street names that recur.","source":GS,"url":G,"quote":"dense and intricate, rich in detail","page":"p. 155","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: repurposed familiar vocabulary","claim":"Gerlach notes that Wolfe estranges his setting by giving ordinary English words unfamiliar in-world applications rather than by coining new ones.","source":GS,"url":G,"quote":"familiar with are applied in unusual, usually comical ways","page":"pp. 154-155","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"Gerlach shows that the in-text dramatis personae preface bound into each volume of The Book of the Long Sun revises its own entry for the god called the Outsider from volume to volume, so that the record corrects itself with no narrator announcing the correction.","source":GS,"url":G,"quote":"subsequent volumes offer a truer picture","page":"p. 159","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Gerlach says Wolfe's text pushes the reader to form hypotheses about the identity of the Outsider on minimal evidence.","source":GS,"url":G,"quote":"develop hypotheses about who the Outsider is from minimal clues","page":"p. 158","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 {"feature":"point of view and distance","claim":"Gerlach observes that Wolfe's viewpoint character accepts as ordinary the event the reader is questioning, so the gap between belief and inference is carried by the character's incuriosity rather than by narratorial comment.","source":GS,"url":G,"quote":"does not question whether the Chenille he knows could be possessed","page":"p. 157","kind":"analysis","polarity":"asserts","date":"1999","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: documentary frame","claim":"Farrell reports that each of Wolfe's three Soldier novels opens with a found-manuscript apparatus in which Wolfe presents himself as the translator of a discovered scroll.","source":FS,"url":F,"quote":"an introduction by Wolfe posing as translator","page":"p. 29","kind":"analysis","polarity":"asserts","date":"2007-04","routeHint":R_PDF,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"place and institution description","claim":"Farrell characterises Soldier of Sidon as reading like a fictional travelogue through ancient Egypt.","source":FS,"url":F,"quote":"reads like a fictional travelogue through ancient Egypt","page":"p. 29","kind":"analysis","polarity":"asserts","date":"2007-04","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: historical density","claim":"Farrell argues that the density of historical detail in the Soldier novels prevents them from being read as straightforward allegory.","source":FS,"url":F,"quote":"The novels are too dense with the details of history","page":"p. 29","kind":"analysis","polarity":"asserts","date":"2007-04","registerHint":"none","routeHint":R_PDF,"confidence":"high"},
 {"feature":"point of view and distance","claim":"Farrell judges Wolfe's Castleview weakened by the absence of a first-person narrator to unify it.","source":FS,"url":F,"quote":"lacks the unifying force of a first-person narrator","page":"p. 30","kind":"analysis","polarity":"asserts","date":"2007-04","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 {"feature":"place and institution description","claim":"Gwyneth Jones faults the alternate world of There Are Doors for having no coherent geography, population or time scale.","source":JS,"url":J,"quote":"without coherent geography, population or time scale","page":"p. 78","kind":"reception","polarity":"rejects","date":"1989","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Jones reports that Wolfe's withholding in There Are Doors left her groping without guidance rather than inferring.","source":JS,"url":J,"quote":"The reader is left groping without guidance","page":"p. 78","kind":"reception","polarity":"disputes","date":"1989","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wolfe states that the premise of Peace is that its narrator has already died and is haunting his own memories.","source":HS,"url":H,"quote":"a man has died and he is haunting his own mind","page":"p. 41","kind":"own-words","polarity":"asserts","date":"1981-09","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 {"feature":"omission as information","claim":"Wolfe says that very few readers grasp the central fact of Peace, which the novel signals only through its opening sentence about a fallen elm.","source":HS,"url":H,"quote":"This is something very few people seem to understand about Peace","page":"p. 41","kind":"own-words","polarity":"asserts","date":"1981-09","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 {"feature":"other: drafting method","claim":"Wolfe says he had all four volumes of The Book of the New Sun in second draft before he offered the first for sale.","source":HS,"url":H,"quote":"I had all four volumes in second draft","page":"p. 43","kind":"own-words","polarity":"asserts","date":"1981-09","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 {"feature":"other: visual versus verbal texture","claim":"Wolfe says that when he began the Torturer books he was worried that his writing had become too verbal and too cerebral.","source":HS,"url":H,"quote":"I've been tending to be too verbal, too cerebral","page":"p. 40","kind":"own-words","polarity":"asserts","date":"1981-09","routeHint":R_PDF,"registerHint":"none","confidence":"high"},
 # --- Peter Wright, Ultan's Library
 {"feature":"withheld information and inference","claim":"Peter Wright argues that ambiguity in The Fifth Head of Cerberus is not decoration but an organising principle of the book's form.","source":WS,"url":UW,"quote":"an organising principle of form, a means of confounding interpretation","page":"opening paragraph","kind":"analysis","polarity":"asserts","date":"2002-01-15","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"omission as information","claim":"Wright argues that the unsolved puzzle in The Fifth Head of Cerberus carries the book's political argument, so the withholding is where the meaning lives rather than an obstacle in front of it.","source":WS,"url":UW,"quote":"the puzzle is where the political arguments of the novel can be found","page":"section on prior criticism","kind":"analysis","polarity":"asserts","date":"2002-01-15","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: documentary frame","claim":"Wright argues that the authorship of the embedded document inside The Fifth Head of Cerberus can be settled by clues planted elsewhere in the collection rather than by any statement of attribution.","source":WS,"url":UW,"quote":"whose authenticity can be validated from the clues Wolfe weaves","page":"section on authenticity","kind":"analysis","polarity":"asserts","date":"2002-01-15","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wright says Wolfe's clues, though subtle, lead the careful reader to a determinate conclusion, so the ambiguity is resolvable rather than open.","source":WS,"url":UW,"quote":"clues lead the cautious and reflective reader","page":"section on authenticity","kind":"analysis","polarity":"asserts","date":"2002-01-15","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"place and institution description","claim":"Wright reads the house at 666 Saltimbanque in The Fifth Head of Cerberus as a standing figure for cultural isolationism, so that the building carries the book's political argument.","source":WS,"url":UW,"quote":"is a rambling metaphor for cultural isolationism","page":"section on mimicry","kind":"analysis","polarity":"asserts","date":"2002-01-15","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"Wright argues that Wolfe's two colonised worlds are shown inside a colonial system that has no colonial discourse, so no official account of who is human is available to the reader.","source":WS,"url":UW,"quote":"exist in a colonial system lacking a colonial discourse","page":"section on colonial discourse","kind":"analysis","polarity":"asserts","date":"2002-01-15","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wright quotes the critic Bruce Gillespie complaining that Wolfe's stories offer only jigsaw pieces with no certainty that a pattern exists.","source":"Bruce Gillespie, 'Gene Wolfe's Sleight of Hand', Australian Science Fiction Review, March 1986, p. 15, quoted by Peter Wright in Ultan's Library (2002)","url":UW,"quote":"little pieces of the jigsaw and one is never quite sure","page":"opening paragraph","kind":"reception","polarity":"disputes","date":"1986 (quoted 2002)","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 # --- Wowra, place names
 {"feature":"other: place naming","claim":"Wolfe writes in his foreword to Soldier of the Mist that the narrator recorded place names as he believed he understood their meanings, so the record's names are the narrator's guesses.","source":"Gene Wolfe, foreword to Soldier of the Mist (Tor, 1986), p. xii, quoted by Scott Wowra in Ultan's Library, 7 September 2016","url":UP,"quote":"he understood (or believed he understood) their meanings","page":"Introduction","kind":"own-words","polarity":"asserts","date":"1986 (quoted 2016)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: place naming","claim":"Wowra finds that folk etymology, a plausible but wrong translation, is the main way Wolfe's amnesiac narrator generates the place names in his record.","source":POS,"url":UP,"quote":"it is the primary method Latro uses to record his place names","page":"Introduction","kind":"analysis","polarity":"asserts","date":"2016-09-07","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: place naming","claim":"Wolfe says in a 1988 interview that his narrator arrives at the right meaning of a city's name by an incorrect derivation.","source":"Gene Wolfe, interviewed by Darrell Schweitzer, Weird Tales, Spring 1988, quoted by Scott Wowra in Ultan's Library, 7 September 2016","url":UP,"quote":"although his derivation of it is incorrect","page":"Introduction","kind":"own-words","polarity":"asserts","date":"1988 (quoted 2016)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"naming and forms of address","claim":"Wowra describes Wolfe's toponyms in Soldier of the Mist as plain compounded names such as Hundred Eyed and Redface Island that provoke wonder and puzzlement.","source":POS,"url":UP,"quote":"awash with charming place names that evoke wonder and puzzlement","page":"opening paragraph","kind":"analysis","polarity":"asserts","date":"2016-09-07","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: place naming","claim":"Wolfe explains in his introduction that his narrator named a region Silent Country after mishearing a remark about a person's laconic manners.","source":"Gene Wolfe, introduction to Soldier of the Mist (Tor, 1986), p. xii, quoted by Scott Wowra in Ultan's Library, 7 September 2016","url":UP,"quote":"seems to have heard some taciturn person referred to as","page":"Folk Etymology section","kind":"own-words","polarity":"asserts","date":"1986 (quoted 2016)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: place naming","claim":"Wowra concludes that the record's place names are dominated by folk etymology, with descriptive, associative and commemorative naming used less often.","source":POS,"url":UP,"quote":"Latro relies predominantly on folk etymology","page":"Conclusion","kind":"analysis","polarity":"asserts","date":"2016-09-07","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 # --- Gevers
 {"feature":"withheld information and inference","claim":"Gevers argues that Wolfe writes so that any seemingly incidental paragraph reflects the whole design, which is what obliges the reader to read incidental detail as evidence.","source":GEV,"url":UG,"quote":"every paragraph, however incidental seeming, reflects the whole","page":"section on augury","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Gevers argues that the divination scenes inside The Book of the Long Sun function as instruction to the reader in how closely the text must be read.","source":GEV,"url":UG,"quote":"instruction in, the demands of incisive reading","page":"section on augury","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"opening sentence","claim":"Gevers finds that every volume of The Book of the Long Sun opens with a dialogue in which the informed party releases what he knows only in oracular or obscure form.","source":GEV,"url":UG,"quote":"which he will only yield up in oracular or otherwise obscure form","page":"section on beginnings and endings","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"plainness and economy","claim":"Gevers describes Wolfe's narration in the final volume of the Long Sun as spare and unexplanatory, made of hints and implications.","source":GEV,"url":UG,"quote":"narration becomes spare, unexplanatory, a minefield of hints and implications","page":"section on Exodus","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"closing sentence","claim":"Gevers uses Kim Stanley Robinson and John Clute's term slingshot ending for a close whose implications carry past the end of the text.","source":GEV,"url":UG,"quote":"an ending whose momentum of implication carries well beyond the confines","page":"section on beginnings and endings","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"point of view and distance","claim":"Gevers notes that the narrator of The Book of the Long Sun identifies himself only in the last pages, which forces the reader to re-appraise everything already read.","source":GEV,"url":UG,"quote":"thus forcing the reader to re-appraise the whole of the preceding text","page":"section on Exodus","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Gevers states that Wolfe's third volume instructs the reader to assemble the meaning of the text out of clues that appear disconnected.","source":GEV,"url":UG,"quote":"assembling the meaning of the text from numerous seemingly disconnected clues","page":"section on Calde","kind":"analysis","polarity":"asserts","date":"2000-09-05","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 # --- Borski
 {"feature":"omission as information","claim":"Borski endorses Wright's finding that the absence of any discourse between coloniser and colonised in The Fifth Head of Cerberus destabilises the reality the book reports.","source":BOR,"url":UB,"quote":"the destabilizing effects such omissions have on reality","page":"second paragraph","kind":"analysis","polarity":"applies","date":"2002-05-24","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Borski links two of Wolfe's characters into a single pattern using small domestic repetitions, among them the barley soup each is served in prison.","source":BOR,"url":UB,"quote":"Both men are served barley soup while imprisoned","page":"numbered list, item 14","kind":"analysis","polarity":"applies","date":"2002-05-24","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 # --- Aramini
 {"feature":"omission as information","claim":"Aramini reports as general critical consensus that Wolfe leaves certain resolutions out of the text for the reader to infer.","source":ARA,"url":A,"quote":"Wolfe leaves out certain resolutions which are left to the reader","page":"Introduction","kind":"analysis","polarity":"asserts","date":"2019-05","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Aramini reports Peter Wright's contrary position that many details in Wolfe's primary narrative are distractions rather than clues.","source":"Peter Wright, Attending Daedalus (Liverpool University Press, 2003), summarised by Marc Aramini in his UNLV dissertation, 2019","url":A,"quote":"many of the details included in the primary narrative","page":"Introduction","kind":"analysis","polarity":"disputes","date":"2003 (reported 2019)","routeHint":R_PDF,"registerHint":"none","confidence":"medium: Aramini is summarising Wright's book, which was not read directly"},
 {"feature":"other: documentary frame","claim":"Aramini reports Wright's finding that Wolfe's translator persona makes deliberate mistranslations and substitutions inside the Latro books.","source":"Peter Wright, Attending Daedalus (Liverpool University Press, 2003), p. 188, quoted by Marc Aramini in his UNLV dissertation, 2019","url":A,"quote":"explicit mistranslations and substitutions by the translator Wolfe","page":"chapter on the Latro novels","kind":"analysis","polarity":"asserts","date":"2003 (quoted 2019)","routeHint":R_PDF,"registerHint":"chronicle-line","confidence":"medium: reached through Aramini quoting Wright rather than through Attending Daedalus itself"},
 {"feature":"omission as information","claim":"A passage of Wolfe's own fiction reproduced in Aramini's dissertation states that what is not said can be important but what is said matters more.","source":"Gene Wolfe, The Sword of the Lictor, p. 182, quoted within Peter Wright's argument as reproduced in Marc Aramini's UNLV dissertation, 2019","url":A,"quote":"What is not said can be important","page":"chapter on critical reception","kind":"relay","polarity":"asserts","date":"1982 (quoted 2019)","routeHint":R_PDF,"registerHint":"dossier-archivist","confidence":"medium: this is a line of Wolfe's fiction, not a statement of his craft doctrine"},
 {"feature":"annalist voice and deep time","claim":"Aramini argues that Wolfe builds his Latro narrative on the Herodotean model of an account that blends history, myth and rumour.","source":ARA,"url":A,"quote":"blends history, myth, and rumor","page":"chapter on the Latro novels","kind":"analysis","polarity":"asserts","date":"2019-05","routeHint":R_PDF,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"civic record register","claim":"A passage of Wolfe's The Wizard Knight reproduced in Aramini's dissertation describes a past that survives only as memories and as records nobody reads or can read.","source":"Gene Wolfe, The Wizard Knight, p. 39, quoted in Marc Aramini's UNLV dissertation, 2019","url":A,"quote":"records nobody reads, and records nobody can read","page":"chapter on archetypes","kind":"relay","polarity":"asserts","date":"2004 (quoted 2019)","routeHint":R_PDF,"registerHint":"chronicle-line","confidence":"medium: a line of Wolfe's fiction quoted by the critic, not the critic's own analysis"},
]

# ================= BATCH 3 =================
C1="https://gwern.net/doc/fiction/gene-wolfe/2001-01-29-johnclute-excessivecandorv7no5issue197-itisbecomingtograpplewiththisbook.html"
C2="https://gwern.net/doc/fiction/gene-wolfe/2009-04-06-johnclute-thebestofgenewolfe-review.html"
UM="https://ultan.org.uk/review-botns/"
NX="http://losarciniegas.blogspot.com/2021/04/suns-new-long-and-short-interview-with.html"
WK="https://en.wikipedia.org/wiki/Gene_Wolfe"
for u,p2 in [(C1,'clute-2001.txt'),(C2,'clute-2009.txt'),(UM,'u-review-botns.txt'),(NX,'nova3.txt'),(WK,'wiki-wolfe.txt')]:
    try: reg(u,p2)
    except FileNotFoundError: print('missing',p2)
C1S="John Clute, 'It Is Becoming to Grapple with This Book', Excessive Candour column, Science Fiction Weekly issue 197, 29 January 2001"
C2S="John Clute, review of The Best of Gene Wolfe, SCI FI Wire, 6 April 2009"
UMS="Peter Wright, 'Mapping a Masterwork: A Critical Review of Gene Wolfe's The Book of the New Sun', Ultan's Library, 28 August 2002"
NXS="Gene Wolfe, interviewed by Lawrence Person, 'Suns New, Long, and Short', Nova Express vol. 5 no. 1, Fall/Winter 1998; collected in Peter Wright (ed.), Shadows of the New Sun, Liverpool University Press, 2007"
R_MIR="blog reproduction of the Nova Express interview text, fetched with a browser user agent after the wolfewiki page proved to be a stub and lawrenceperson.com returned 404"
SOURCES.extend([
 {"title":"John Clute, Excessive Candour on The Book of the Short Sun (Science Fiction Weekly 197, 2001)","url":C1,"kind":"analysis","substantive":True,"date":"2001-01-29","route":"gwern.net mirror of the scifi.com page (itself a Wayback capture), fetched with a browser user agent"},
 {"title":"John Clute, review of The Best of Gene Wolfe (SCI FI Wire, 2009)","url":C2,"kind":"analysis","substantive":True,"date":"2009-04-06","route":"gwern.net mirror of the scifiwire.com page (itself a Wayback capture), fetched with a browser user agent"},
 {"title":"Peter Wright, 'Mapping a Masterwork' (Ultan's Library, 2002)","url":UM,"kind":"analysis","substantive":True,"date":"2002-08-28","route":R_WEB},
 {"title":"Lawrence Person interview with Gene Wolfe, Nova Express (Fall/Winter 1998)","url":NX,"kind":"own-words","substantive":True,"date":"1998","route":R_MIR},
 {"title":"Wikipedia, 'Gene Wolfe' (Style and Reception sections, as of September 2026)","url":WK,"kind":"relay","substantive":True,"date":"read 2026-09-06","route":R_WEB},
 {"title":"Wikipedia, 'The Book of the New Sun'","url":"https://en.wikipedia.org/wiki/The_Book_of_the_New_Sun","kind":"relay","substantive":False,"date":"read 2026-09-06","route":R_WEB+"; fetched and read, its style material duplicates the Gene Wolfe article and adds no separately citable critic"},
 {"title":"Wikipedia, 'The Fifth Head of Cerberus'","url":"https://en.wikipedia.org/wiki/The_Fifth_Head_of_Cerberus","kind":"relay","substantive":False,"date":"read 2026-09-06","route":R_WEB+"; fetched and read, plot and publication history, nothing on prose register beyond what Wright's paper covers directly"},
 {"title":"Peter Wright (ed.), Shadows of the New Sun, introduction (Cambridge Core listing)","url":"https://www.cambridge.org/core/books/abs/shadows-of-the-new-sun/introduction/C861D0D3B8C29D7A4CD8C40CAA72A62E","kind":"analysis","substantive":False,"date":"2007","route":"BLOCKED: connection returned no bytes to curl with a browser user agent; the volume was reached instead through the Hall interview chapter mirrored on gwern"},
 {"title":"UNLV Digital Scholarship copy of the Aramini dissertation","url":"https://digitalscholarship.unlv.edu/cgi/viewcontent.cgi?article=4585&context=thesesdissertations","kind":"analysis","substantive":False,"date":"2019","route":"BLOCKED: HTTP 403 to curl with a browser user agent; the same dissertation was read through the gwern mirror"},
])
CLAIMS.extend([
 {"feature":"per-speaker register","claim":"Clute reports that the large cast of The Book of the Short Sun speaks in dozens of distinct dialects and accents, each rendered with care.","source":C1S,"url":C1,"quote":"dozens of different dialects and accents spoken by the huge cast","page":"section 'A Complex Yet Rewarding Finish'","kind":"analysis","polarity":"asserts","date":"2001-01-29","routeHint":"gwern.net mirror","registerHint":"herald-pools","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Clute identifies Wolfe's refusal to restate a difficult story in easy terms as one of the things the reader must struggle with.","source":C1S,"url":C1,"quote":"refusal to unpack in easy terms","page":"section 'A Complex Yet Rewarding Finish'","kind":"analysis","polarity":"asserts","date":"2001-01-29","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"concrete sensory noun","claim":"Clute locates the moral quality of Wolfe's central character in the details rather than in any statement about him.","source":C1S,"url":C1,"quote":"that goodness is in the details","page":"section 'A Complex Yet Rewarding Finish'","kind":"analysis","polarity":"asserts","date":"2001-01-29","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"Clute argues that every word in Wolfe's stories is deliberate, so that no sentence can be slurred over by the reader.","source":C2S,"url":C2,"quote":"every word he wrote was meant","page":"paragraph on the 1970s stories","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"metaphor discipline","claim":"Clute states that Wolfe did not write metaphors into his text, or wrote only metaphors to which a literal meaning could be attached.","source":C2S,"url":C2,"quote":"Wolfe did not create metaphors in his text","page":"paragraph on the 1970s stories","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"metaphor discipline","claim":"Clute says the nearest Wolfe normally comes to metaphor is letting one of his characters tell a lie.","source":C2S,"url":C2,"quote":"the closest Wolfe normally gets to metaphor is when he","page":"paragraph on The Fifth Head of Cerberus","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: literal over thematic","claim":"Clute argues Wolfe wrote neither thematics nor allegory but the thing itself.","source":C2S,"url":C2,"quote":"he did not write allegory, he wrote the thing itself","page":"paragraph on the 1970s stories","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: literal over thematic","claim":"Clute says Wolfe's stories cannot be paraphrased for meaning because they only make sense once the manner of their telling is understood.","source":C2S,"url":C2,"quote":"stories that only make sense when it is understood how","page":"paragraph on academic reception","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"none","confidence":"high"},
 {"feature":"plainness and economy","claim":"Clute describes the surface of The Fifth Head of Cerberus as a fluent and seemingly translucent style.","source":C2S,"url":C2,"quote":"written in a fluent, seemingly translucent style","page":"paragraph on The Fifth Head of Cerberus","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Clute argues that the easy surface of Wolfe's prose can itself distract the reader from noticing that every word must be taken literally.","source":C2S,"url":C2,"quote":"may distract the reader from realizing that it can only","page":"paragraph on The Fifth Head of Cerberus","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Clute observes that the dwelling of a Wolfe narrator characteristically combines the functions of prison, pleasure garden and tomb.","source":C2S,"url":C2,"quote":"the home of the narrator of a typical Wolfe tale","page":"paragraph on The Fifth Head of Cerberus","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Clute adds that a Wolfe narrator's house is also likely to be a laboratory whose experimental subject is that narrator.","source":C2S,"url":C2,"quote":"the home of a Wolfe narrator will also serve as a laboratory","page":"paragraph on The Fifth Head of Cerberus","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"opening sentence","claim":"Clute reads the first sentence of The Fifth Head of Cerberus as telling the reader at once that the text is a memoir that has been physically written down.","source":C2S,"url":C2,"quote":"we are meant to understand has actually been written down","page":"paragraph on The Fifth Head of Cerberus","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"chronicle-line","confidence":"high"},
 {"feature":"other: academic reception","claim":"Clute states that academics have tended to avoid Wolfe for decades because his stories cannot be mined for detachable themes.","source":C2S,"url":C2,"quote":"academics have notoriously tended to shun him for decades","page":"paragraph on academic reception","kind":"analysis","polarity":"asserts","date":"2009-04-06","routeHint":"gwern.net mirror","registerHint":"none","confidence":"high"},
 {"feature":"point of view and distance","claim":"Wright argues that Severian is unreliable precisely because of the trait that makes him look reliable, his eidetic memory.","source":UMS,"url":UM,"quote":"unreliable because of the very characteristic that makes him appear wholly reliable","page":"section on the first-person narrator","kind":"analysis","polarity":"asserts","date":"2002-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wright explains the concealment in The Book of the New Sun as an effect of a narrator who remembers a wealth of detail and thereby scatters the meaning.","source":UMS,"url":UM,"quote":"remember a wealth of detail (plot) which scatters meaning","page":"section on the first-person narrator","kind":"analysis","polarity":"asserts","date":"2002-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wright names the gap between plot and story, the apparent and the real, as the signal that alerts the reader to Wolfe's game.","source":UMS,"url":UM,"quote":"gulf between plot and story, between the apparent and the real","page":"section on plot and story","kind":"analysis","polarity":"asserts","date":"2002-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"Wright says the reader's first task is to see the text not as the religious document it claims to be but as the product of a manipulated narrator.","source":UMS,"url":UM,"quote":"the text not as the religious document it purports to be","page":"section on plot and story","kind":"analysis","polarity":"asserts","date":"2002-08-28","routeHint":R_WEB,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"plainness and economy","claim":"Wright reports that on a first reading there is little in the prose surface of The Book of the New Sun to distinguish it from other genre novels.","source":UMS,"url":UM,"quote":"On a first, superficial reading, there is little to distinguish","page":"section on the masterwork claim","kind":"analysis","polarity":"asserts","date":"2002-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"Wright quotes Michael Bishop calling The Shadow of the Torturer immediately accessible to any reader of moderate intelligence.","source":"Michael Bishop, quoted by Peter Wright in 'Mapping a Masterwork', Ultan's Library, 28 August 2002","url":UM,"quote":"an immediately accessible book for anyone with moderate intelligence","page":"section on early reception","kind":"reception","polarity":"asserts","date":"quoted 2002-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wright quotes Algis Budrys, a working novelist, saying he could tell the cards were up Wolfe's sleeve without being able to follow the moves.","source":"Algis Budrys, quoted by Peter Wright in 'Mapping a Masterwork', Ultan's Library, 28 August 2002","url":UM,"quote":"I know the cards are up the sleeves somewhere","page":"section on early reception","kind":"reception","polarity":"asserts","date":"quoted 2002-08-28","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"other: academic reception","claim":"Wright reports that Baird Searles's prediction of an academic field day over The Book of the New Sun had gone largely unfulfilled twenty years on.","source":UMS,"url":UM,"quote":"his prophecy has gone largely unfulfilled","page":"section on the masterwork claim","kind":"analysis","polarity":"asserts","date":"2002-08-28","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"other: academic reception","claim":"Wright quotes Baird Searles calling the tetralogy a possible turning point of science fiction from matter to manner.","source":"Baird Searles, quoted by Peter Wright in 'Mapping a Masterwork', Ultan's Library, 28 August 2002","url":UM,"quote":"from content to style, from matter to manner","page":"section on early reception","kind":"reception","polarity":"asserts","date":"quoted 2002-08-28","routeHint":R_WEB,"registerHint":"none","confidence":"high"},
 {"feature":"per-speaker register","claim":"Wolfe says he differentiates unlabelled speakers by giving each one something only that character would say, so the reader identifies the speaker from the content of the speech.","source":NXS,"url":NX,"quote":"she is saying something that only Maytera Marble would say","page":"answer on speech patterns","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"herald-pools","confidence":"high"},
 {"feature":"per-speaker register","claim":"Wolfe says an intelligent reader can tell who spoke from what was said, without a speech tag.","source":NXS,"url":NX,"quote":"knows who said that from what was said","page":"answer on speech patterns","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"herald-pools","confidence":"high"},
 {"feature":"point of view and distance","claim":"Wolfe states that once a person inside the story tells the story, that narrator is necessarily unreliable.","source":NXS,"url":NX,"quote":"then the narrator is damn well going to be unreliable","page":"answer on The Fifth Head of Cerberus","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wolfe grounds narrator unreliability in courtroom testimony, where several witnesses all trying to tell the truth have nonetheless seen different things.","source":NXS,"url":NX,"quote":"all trying to tell the truth, but they have all seen","page":"answer on The Fifth Head of Cerberus","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"Wolfe says a complex story has to be told in a clear structure, because otherwise it is not complex but merely confused.","source":NXS,"url":NX,"quote":"or it isn't complex, it's simply confused","page":"answer on narrative style","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"The interviewer characterises The Book of the Long Sun as told in a straightforward and transparent narrative style despite its complexity, and Wolfe does not dispute the description.","source":"Lawrence Person, question put to Gene Wolfe in Nova Express vol. 5 no. 1, Fall/Winter 1998","url":NX,"quote":"told in a very straightforward and transparent narrative style","page":"question on narrative style","kind":"analysis","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Wolfe says he began the Sun books with the deliberate decision not to coin invented proper names.","source":NXS,"url":NX,"quote":"the idea of not coining Tars Tarkas type names","page":"answer on research and vocabulary","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Wolfe says the right choice for those books was archaic real names and archaic terms rather than coinages.","source":NXS,"url":NX,"quote":"using archaic names and archaic terms for things","page":"answer on research and vocabulary","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Wolfe attaches a condition to his use of archaic terms: they must appear in contexts that make their meaning clear to the reader.","source":NXS,"url":NX,"quote":"it will be clear to the reader what is meant","page":"answer on research and vocabulary","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"diction (native vs latinate)","claim":"Wolfe describes his method of sourcing vocabulary as looking up the Latin or Greek word for what he needs and then finding an English word someone had already anglicised from it.","source":NXS,"url":NX,"quote":"someone will have anglicized this term as a new word","page":"answer on research and vocabulary","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"naming and forms of address","claim":"Wolfe praises Avram Davidson for building imaginary countries out of obsolete real place names.","source":NXS,"url":NX,"quote":"in using obsolete place names","page":"answer on research and vocabulary","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"naming and forms of address","claim":"Wolfe describes Davidson's place-naming procedure as taking a third-century name and asking what if this place had survived under that name.","source":NXS,"url":NX,"quote":"Suppose this place survived as an entity with that name","page":"answer on research and vocabulary","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Wolfe argues that a very large city would show great diversity across its neighbourhoods and social levels, and calls the monocultured world of much science fiction laziness.","source":NXS,"url":NX,"quote":"diversity among the neighborhoods and social levels","page":"answer on multiple cultures","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"per-speaker register","claim":"Wolfe observes that in a real city people on different social levels already talk in ways that are almost different languages.","source":NXS,"url":NX,"quote":"people are talking in ways that are almost different languages","page":"answer on multiple cultures","kind":"own-words","polarity":"asserts","date":"1998","routeHint":R_MIR,"registerHint":"herald-pools","confidence":"high"},
 {"feature":"point of view and distance","claim":"Wolfe says real people are unreliable narrators all the time even when they are trying to be reliable.","source":"Gene Wolfe, quoted in Wikipedia's Gene Wolfe article, citing Lawrence Person's Nova Express interview (Fall/Winter 1998)","url":WK,"quote":"Real people really are unreliable narrators all the time","page":"Style section","kind":"relay","polarity":"asserts","date":"1998 (relayed 2026)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"In the appendix to The Shadow of the Torturer Wolfe states that he could have used invented terms but in no case did so.","source":"Wikipedia relaying Gene Wolfe's appendix to The Shadow of the Torturer (cited as Shadow and Claw, Tor 1994, p. 211)","url":WK,"quote":"in no case have I done so","page":"Style section","kind":"relay","polarity":"asserts","date":"1980 (relayed 2026)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"medium: the primary appendix is not online, so this is read through the Wikipedia quotation"},
 {"feature":"archaism","claim":"Wolfe's appendix says his substituted real words are meant to be suggestive rather than definitive.","source":"Wikipedia relaying Gene Wolfe's appendix to The Shadow of the Torturer (cited as Shadow and Claw, Tor 1994, p. 211)","url":WK,"quote":"intended to be suggestive rather than definitive","page":"Style section","kind":"relay","polarity":"asserts","date":"1980 (relayed 2026)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"medium: read through the Wikipedia quotation of a printed appendix"},
 {"feature":"archaism","claim":"Wolfe's appendix names peltast, androgyn and exultant as real words standing in for undiscovered concepts.","source":"Wikipedia relaying Gene Wolfe's appendix to The Shadow of the Torturer (cited as Shadow and Claw, Tor 1994, p. 211)","url":WK,"quote":"Such words as peltast, androgyn, and exultant are substitutions","page":"Style section","kind":"relay","polarity":"asserts","date":"1980 (relayed 2026)","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"medium: read through the Wikipedia quotation of a printed appendix"},
 {"feature":"other: rereading","claim":"Wolfe defined a great story in a 1982 letter as one a cultivated reader can read with pleasure and reread with increasing pleasure.","source":"Wikipedia relaying Gene Wolfe, chain letter to George R. R. Martin and Greg Benford, 10 July 1982, as published in Castle of Days (1992)","url":WK,"quote":"One that can be read with pleasure by a cultivated reader","page":"Style section","kind":"relay","polarity":"asserts","date":"1982 (relayed 2026)","routeHint":R_WEB,"registerHint":"none","confidence":"medium: the letter is quoted by Wikipedia from a printed collection not read directly"},
 {"feature":"omission as information","claim":"Wikipedia's synthesis states that Wolfe planted subtle hints and lacunae that the text may never refer to explicitly, giving a backyard of morning glories in Free Live Free as an example legible only to a reader with horticultural knowledge.","source":"Wikipedia, 'Gene Wolfe', Style section (unattributed editorial synthesis)","url":WK,"quote":"subtle hints and lacunae that may never be explicitly referred to","page":"Style section","kind":"relay","polarity":"asserts","date":"read 2026-09-06","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"low: this sentence carries no citation in the article and is the encyclopedia's own summary"},
])


# ================= BATCH 4 =================
UPH="https://ultan.org.uk/posthistory-201/"
ULS="https://ultan.org.uk/the-lupine-scholar-by-scott-wowra/"
U5H="https://ultan.org.uk/review-fifth-head-of-cerberus/"
for u,p3 in [(UPH,'u-posthistory-201.txt'),(ULS,'u-the-lupine-scholar-by-scott-wowra.txt'),(U5H,'u-review-fifth-head-of-cerberus.txt')]:
    try: reg(u,p3)
    except FileNotFoundError: print('missing',p3)
MADS="Michael Andre-Driussi, 'Posthistory 201', Ultan's Library, 6 July 2020, revising his 'Posthistory 101' (Extrapolation vol. 37 no. 2, 1996)"
LSS="Scott Wowra, introduction to 'The Lupine Scholar: an interview with Michael Andre-Driussi', Ultan's Library, 21 May 2009"
B5S="Robert Borski, review of The Fifth Head of Cerberus (Millennium, 1999), Ultan's Library, 28 August 2001"
SOURCES.extend([
 {"title":"Michael Andre-Driussi, 'Posthistory 201' (Ultan's Library, 2020)","url":UPH,"kind":"analysis","substantive":True,"date":"2020-07-06","route":R_WEB},
 {"title":"Scott Wowra, 'The Lupine Scholar' interview introduction (Ultan's Library, 2009)","url":ULS,"kind":"analysis","substantive":True,"date":"2009-05-21","route":R_WEB},
 {"title":"Robert Borski, review of The Fifth Head of Cerberus (Ultan's Library, 2001)","url":U5H,"kind":"analysis","substantive":True,"date":"2001-08-28","route":R_WEB},
 {"title":"Nick Gevers, 'Five Steps towards Briah' (Ultan's Library)","url":"https://ultan.org.uk/five-steps-towards-briah/","kind":"analysis","substantive":False,"date":"read 2026-09-06","route":R_WEB+"; fetched and skimmed, structural/theological argument superseded for this angle by the same author's 'The Reader as Augur', from which the claims were taken"},
 {"title":"'Torture and confession in Wolfe's Book of the New Sun' (Ultan's Library)","url":"https://ultan.org.uk/torture-and-confession-in-wolfes-book-of-the-new-sun/","kind":"analysis","substantive":False,"date":"read 2026-09-06","route":R_WEB+"; fetched, thematic rather than stylistic, no register or place claims taken"},
 {"title":"Science Fiction Studies review of Attending Daedalus (SFS 32.1, 2005) and the 1987 SFS review of Joan Gordon's Gene Wolfe","url":"https://doi.org/10.1525/sfs.32.1.0212","kind":"analysis","substantive":False,"date":"2005","route":"BLOCKED: depauw.edu returns 404 for every /sfs/ review path tried, no Wayback capture of the review pages exists, and the DOI record is not open access; located through OpenAlex but not read"},
 {"title":"Cecilia Michel Lopez, 'Art and Allegory: A Method to Read The Book of the New Sun' (Logos, 2015)","url":"https://doi.org/10.1353/log.2015.0030","kind":"analysis","substantive":False,"date":"2015","route":"BLOCKED: not open access; only the OpenAlex first-paragraph record was available, which is not a read"},
 {"title":"'Time After Time: On the speculative fiction of Gene Wolfe' (Critical Quarterly, 2020)","url":"https://doi.org/10.1111/criq.12563","kind":"analysis","substantive":False,"date":"2020","route":"BLOCKED: not open access, no abstract in the OpenAlex record"},
])
CLAIMS.extend([
 {"feature":"annalist voice and deep time","claim":"Andre-Driussi argues that Wolfe's narrator writes from a post-historic vantage point at which all dating is vague.","source":MADS,"url":UPH,"quote":"post-historic vantage point means that all time is vague","page":"section 2.2","kind":"analysis","polarity":"asserts","date":"2020-07-06","routeHint":R_WEB,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"annalist voice and deep time","claim":"Andre-Driussi contrasts Wolfe with Jack Vance, who dates his dying-Earth events by numbered Aeons, and says Wolfe writes against that grain.","source":MADS,"url":UPH,"quote":"goes against the Vancean grain of numbered Aeons","page":"section 2.2","kind":"analysis","polarity":"asserts","date":"2020-07-06","routeHint":R_WEB,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"annalist voice and deep time","claim":"Andre-Driussi revises his own published estimate of the duration of the Autarchy and reports that the text supports only a range between one thousand and thirty thousand years.","source":MADS,"url":UPH,"quote":"the range is actually between one thousand and thirty-thousand years","page":"section 2.1","kind":"measurement","polarity":"asserts","date":"2020-07-06","routeHint":R_WEB,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"place and institution description","claim":"Andre-Driussi infers from a single offhand remark by a minor character that the city's name records a failure of its water treatment, and that technological decline is what poisoned the river.","source":MADS,"url":UPH,"quote":"the poisoning of the water is a direct result of technological decline","page":"section 1","kind":"analysis","polarity":"asserts","date":"2020-07-06","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"consequence on a household","claim":"Andre-Driussi reconstructs from that same remark that the city had to move upstream to escape its own filth, a civic history the narrative never states outright.","source":MADS,"url":UPH,"quote":"the city had to move upstream to avoid its own filth","page":"section 1","kind":"analysis","polarity":"asserts","date":"2020-07-06","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Wowra states that all the strange words in The Book of the New Sun are real English words, and that this shows how odd language can sound without invented vocabulary.","source":LSS,"url":ULS,"quote":"how odd language can sound without science fiction authors inventing new words","page":"introduction","kind":"analysis","polarity":"asserts","date":"2009-05-21","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Wowra reports that Wolfe answered the charge of fabricating words by publishing the essay 'Words Weird and Wonderful' in The Castle of the Otter in 1982 to show the words were genuine.","source":LSS,"url":ULS,"quote":"all the words he used in THE SHADOW OF THE TORTURER","page":"introduction","kind":"analysis","polarity":"asserts","date":"2009-05-21","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"archaism","claim":"Wowra gives omophagist and cherkaji as examples of Wolfe's seemingly counterfeit but genuine vocabulary, glossing them as an eater of raw flesh and Persian light cavalry.","source":LSS,"url":ULS,"quote":"omophagist (an eater of raw flesh) and cherkaji","page":"introduction","kind":"analysis","polarity":"asserts","date":"2009-05-21","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"Borski describes the frame of the third novella of The Fifth Head of Cerberus as a junior military officer adjudicating a case from a file of documents.","source":B5S,"url":U5H,"quote":"an unnamed junior military officer is seeking to adjudicate the case","page":"section on V.R.T.","kind":"analysis","polarity":"asserts","date":"2001-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: documentary frame","claim":"Borski reports that most of what that officer reads comes to the reader as extracts, among them taped interrogation transcripts, a field journal and a prison diary.","source":B5S,"url":U5H,"quote":"Much of what the officer examines takes the form of extracts","page":"section on V.R.T.","kind":"analysis","polarity":"asserts","date":"2001-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: documentary frame","claim":"Borski notes that the dossier is not ordered chronologically and that ordinary details of the officer's own present keep interrupting the documents he is reading.","source":B5S,"url":U5H,"quote":"Little is told chronologically, and often mundanities from the present-time narrative intrude","page":"section on V.R.T.","kind":"analysis","polarity":"asserts","date":"2001-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Borski says the third novella is told out of order with the reader left to piece the case together from a fragmentary narrative.","source":B5S,"url":U5H,"quote":"told anachronically, with the reader left to piece everything together","page":"opening section","kind":"analysis","polarity":"asserts","date":"2001-08-28","routeHint":R_WEB,"registerHint":"dossier-archivist","confidence":"high"},
])


# ================= BATCH 5: Science Fiction Studies =================
SFS="https://web.archive.org/web/20260117042947id_/https://www.depauw.edu/sfs/interviews/wolfe46interview.htm"
try: reg(SFS,'sfs-mccaffery.txt')
except FileNotFoundError: print('missing sfs')
SFSS="Gene Wolfe, interviewed by Larry McCaffery, 'On Encompassing the Entire Universe', Science Fiction Studies #46, vol. 15 part 3, November 1988"
SFSH="Larry McCaffery, editorial headnote to 'On Encompassing the Entire Universe: An Interview with Gene Wolfe', Science Fiction Studies #46, November 1988"
R_SFS="Wayback raw capture (web.archive.org/web/20260117042947id_/...) after every live depauw.edu/sfs path returned HTTP 404"
SOURCES.append({"title":"Larry McCaffery interview with Gene Wolfe, Science Fiction Studies #46 (November 1988)","url":SFS,"kind":"own-words","substantive":True,"date":"1988-11","route":R_SFS})
CLAIMS.extend([
 {"feature":"other: drafting method","claim":"Wolfe told Science Fiction Studies that he writes a minimum of three passes over everything, an original plus at least two rewrites.","source":SFSS,"url":SFS,"quote":"an original and then at least two rewrites","page":"answer on revision","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"none","confidence":"high"},
 {"feature":"other: drafting method","claim":"Wolfe said some of his work goes through fifteen or more drafts.","source":SFSS,"url":SFS,"quote":"some of it goes 15 or even more drafts","page":"answer on revision","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"none","confidence":"high"},
 {"feature":"opening sentence","claim":"Wolfe said he rewrote the opening pages of The Fifth Head of Cerberus at least eight or ten times.","source":SFSS,"url":SFS,"quote":"I completely rewrote those opening pages at least eight or ten times","page":"answer on revision","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"opening sentence","claim":"Wolfe said the reason he rewrote that opening so many times was to establish the feeling of stagnation that governs what follows.","source":SFSS,"url":SFS,"quote":"the feeling of stagnation which affects a lot of","page":"answer on revision","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"register modulation","claim":"Wolfe said getting the language right matters most when he is trying to capture a specific atmosphere or cultural attitude in a story.","source":SFSS,"url":SFS,"quote":"trying to capture a specific atmosphere or cultural attitude in a story","page":"answer on revision","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wolfe rejected the reading that his refracted narrative methods are meant to mystify readers.","source":SFSS,"url":SFS,"quote":"is not to mystify my readers","page":"answer on refracted methods","kind":"own-words","polarity":"rejects","date":"1988-11","routeHint":R_SFS,"registerHint":"none","confidence":"high"},
 {"feature":"place and institution description","claim":"Wolfe said he drew a floor plan of the house in Free Live Free because he otherwise got tangled in physical questions about the building.","source":SFSS,"url":SFS,"quote":"I had to draw a floor plan of","page":"answer on outlining","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Wolfe listed the kind of physical question the floor plan settled, such as whether the street was visible from a given window.","source":SFSS,"url":SFS,"quote":"Could you see the street from this window","page":"answer on outlining","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"terminology consistency","claim":"Wolfe said he checks that a recurring character is the same person on page 300 as on page 10, and rewrites the earlier page when he prefers the later version.","source":SFSS,"url":SFS,"quote":"the same person on page 300 as he was on page 10","page":"answer on revision","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"none","confidence":"high"},
 {"feature":"withheld information and inference","claim":"Wolfe told Science Fiction Studies that memory is all we have, the present being a knifes edge and the future not existing.","source":SFSS,"url":SFS,"quote":"Memory is all we have","page":"answer on memory","kind":"own-words","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"chronicle-line","confidence":"high"},
 {"feature":"per-speaker register","claim":"McCaffery credits The Fifth Head of Cerberus with sure control of a variety of imaginative narrative voices.","source":SFSH,"url":SFS,"quote":"sure control of a variety of imaginative narrative voices","page":"editorial headnote","kind":"analysis","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"herald-pools","confidence":"high"},
 {"feature":"withheld information and inference","claim":"McCaffery characterises the exposition of The Fifth Head of Cerberus as prismatic.","source":SFSH,"url":SFS,"quote":"Its prismatic manner of exposition","page":"editorial headnote","kind":"analysis","polarity":"asserts","date":"1988-11","routeHint":R_SFS,"registerHint":"dossier-archivist","confidence":"high"},
])

def emit(complete, coverage, out="found-wolfe-academic.json"):
    bad=[]
    for i,c in enumerate(CLAIMS):
        q=c.get('quote','')
        if q:
            t=FILES.get(c['url'])
            if t is None: bad.append((i,'NOFILE',c['url']))
            elif norm(q) not in t: bad.append((i,'NOQUOTE',q))
    if bad:
        for b in bad: print('QUOTE FAIL',b)
        sys.exit(1)
    json.dump({"complete":complete,"coverage":coverage,"sourcesRead":SOURCES,"claims":CLAIMS},
              open(os.path.join(BASE,out),'w',encoding='utf-8'), indent=1, ensure_ascii=False)
    print('wrote',out,'| claims',len(CLAIMS),'| sources',len(SOURCES))
if __name__=='__main__':
    emit(False, "checkpoint 2: 12 sources fetched raw (gwern.net scholarly PDF directory + Ultan's Library, the online journal of Gene Wolfe studies); 9 substantive.")
