# -*- coding: utf-8 -*-
GUARDIAN = "https://www.theguardian.com/books/2014/oct/29/guy-gavriel-kay-jrr-tolkien-interview-fionovar-tapesty-the-summer-tree"
OLLEY_INTRO = "https://writersinspire.org/content/guy-gavriel-kay-short-introduction"
OLLEY_VERSE = "https://writersinspire.org/content/verse-prose-fantasy-literature"
BTDH = "https://brightweavings.com/books/books/beyond-this-dark-house/"
LARB = "https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/"
LOCUS = "https://locusmag.com/feature/guy-gavriel-kay-margins-of-history/"
FOXED = "https://foxedquarterly.com/niall-allsopp-dorothy-dunnett-literary-review/"
PEMBROKE = "https://www.pmb.ox.ac.uk/news/just-enough-light-guy-gavriel-kay-delivers-jrr-tolkien-lecture"

CLAIMS = [
# ---- ANGLE 1: the Silmarillion year ----
dict(_src='guardian', feature='other: apprenticeship and revision',
 claim="Kay says the year on The Silmarillion taught him that great works reach their final form through rewriting and mistakes rather than arriving fully formed.",
 source="Guy Gavriel Kay, interviewed by Alison Flood, The Guardian, 29 October 2014", url=GUARDIAN,
 quote="They get there with writing and rewriting and drudgery", page="body, 'Putting The Silmarillion together' paragraph",
 kind='own-words', polarity='asserts', date='2014-10-29', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='guardian', feature='other: biography of the Silmarillion year',
 claim="Kay spent a year between 1974 and 1975 in Oxford helping Christopher Tolkien put together The Silmarillion.",
 source="Alison Flood, The Guardian, 29 October 2014", url=GUARDIAN,
 quote="He had spent a year, between 1974 and 1975, in Oxford", page="body, fourth paragraph",
 kind='analysis', polarity='asserts', date='2014-10-29', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='guardian', feature='other: silence about the editing method',
 claim="Flood reports that Kay declines to discuss the details of the Silmarillion editing process, calling it a personal decision.",
 source="Alison Flood, The Guardian, 29 October 2014", url=GUARDIAN,
 quote="Kay won't talk about the details of the editing process", page="body, fifth paragraph",
 kind='analysis', polarity='asserts', date='2014-10-29', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='guardian', feature='other: sustained concentration',
 claim="Kay says the Silmarillion year demanded a degree of concentration and focus he had not previously exercised as a student.",
 source="Guy Gavriel Kay, interviewed by Alison Flood, The Guardian, 29 October 2014", url=GUARDIAN,
 quote="It demanded a great deal of concentration and focus", page="body, 'Instead, he describes the Silmarillion experience' paragraph",
 kind='own-words', polarity='asserts', date='2014-10-29', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='guardian', feature='other: authority conferred by the Tolkien estate work',
 claim="Kay says his work for the Tolkien estate gave him the standing to argue publicly that 1980s fantasy was going back only as far as Tolkien.",
 source="Guy Gavriel Kay, interviewed by Alison Flood, The Guardian, 29 October 2014", url=GUARDIAN,
 quote="I felt validation, some authenticity to my making statements like that", page="body, 'Fantasy, he felt very strongly' paragraph",
 kind='own-words', polarity='asserts', date='2014-10-29', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='guardian', feature='other: quarter-turn method',
 claim="Kay describes his working method as steeping himself in a historical period and then twisting it slightly.",
 source="Guy Gavriel Kay, interviewed by Alison Flood, The Guardian, 29 October 2014", url=GUARDIAN,
 quote="I steep myself in a period and then I twist it", page="body, 'He just won't do it himself' paragraph",
 kind='own-words', polarity='asserts', date='2014-10-29', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='pembroke', feature='withheld information and inference',
 claim="Pembroke College's report of Kay's 2021 Tolkien Lecture says the talk argued for the vital importance of the unsaid and the unexplained in fiction.",
 source="Pembroke College, Oxford, news report on the 2021 J.R.R. Tolkien Lecture, 20 May 2021", url=PEMBROKE,
 quote="the vital importance of the unsaid and the unexplained in fiction", page="news item, second paragraph",
 kind='reception', polarity='asserts', date='2021-05-20', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='pembroke', feature='withheld information and inference',
 claim="Kay asked in the 2021 Tolkien Lecture how comfortable our responses to art are with mystery, as quoted by Pembroke College.",
 source="Guy Gavriel Kay, quoted in Pembroke College, Oxford news report, 20 May 2021", url=PEMBROKE,
 quote="how comfortable in our responses to art are we with mystery", page="news item, second paragraph",
 kind='own-words', polarity='asserts', date='2021-05-20', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='medium',
 ),

dict(_src='pembroke', feature='other: biography of the Silmarillion year',
 claim="Pembroke College reports that Kay's 2021 Tolkien Lecture opened with reflections from his time in Oxfordshire editing The Silmarillion.",
 source="Pembroke College, Oxford, news report on the 2021 J.R.R. Tolkien Lecture, 20 May 2021", url=PEMBROKE,
 quote="where he helped to edit Tolkien's Silmarillion prior to its publication", page="news item, second paragraph",
 kind='reception', polarity='asserts', date='2021-05-20', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='olleyintro', feature='other: biography of the Silmarillion year',
 claim="Olley, an Oxford medievalist, introduces Kay to a Tolkien audience primarily as one of the editors of The Silmarillion.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford / Great Writers Inspire, 16 December 2020 (auto-generated subtitle file)", url=OLLEY_INTRO,
 quote="known to many fans of Tolkien as one of the editors", page="subtitle transcript, opening",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='writersinspire page, then the linked .srt at media.podcasts.ox.ac.uk/engfac/fantasy_lit/introduction-guy-gavriel-kaydefault.srt',
 registerHint='none', confidence='medium'),

# ---- ANGLE 1 continued: the historian-narrator / chronicle line ----
dict(_src='olleyintro', feature='annalist voice and deep time',
 claim="Olley identifies the retrospective construction of history as one of Kay's chief thematic concerns across all his works.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="The nature of history is retrospective construction", page="subtitle transcript, Under Heaven section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='olleyintro', feature='consequence on a household',
 claim="Olley says Kay chooses to focus on the smaller, more personal moments behind the scenes that shape larger historical events.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="the smaller, more personal moments behind the scenes", page="subtitle transcript, historical inspiration section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='olleyintro', feature='omission as information',
 claim="Olley observes that Kay condenses the whole of the An Lushan rebellion in Under Heaven into an epilogue.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="all of that is condensed into an epilogue", page="subtitle transcript, Under Heaven section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='olleyintro', feature='withheld information and inference',
 claim="Olley says that once events become inevitable Kay largely leaves them to be supplied by the reader's imagination.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="Once events become inevitable, he largely leaves them", page="subtitle transcript, Under Heaven section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='olleyintro', feature='point of view and distance',
 claim="Olley says Kay encourages reflection with the clarity of hindsight rather than building suspense.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="to look back with the tragic clarity of hindsight", page="subtitle transcript, Under Heaven section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='olleyintro', feature='place and institution description',
 claim="Olley says Kay's research is close enough that he seems to write around history rather than rewrite it.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="not to rewrite history but to write around it", page="subtitle transcript, historical inspiration section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='olleyintro', feature='plainness and economy',
 claim="Olley attributes Kay's distinctive style to his ability to find power in quiet moments rather than brash heroic ones.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="ability to find power in these quiet moments", page="subtitle transcript, mosaicist section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='dossier-archivist', confidence='high'),

# ---- ANGLE 2: the poetry ----
dict(_src='olleyintro', feature='cadence and rhythm',
 claim="Olley states that Kay is himself a poet as well as a novelist.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="is himself a poet as well as a novelist", page="subtitle transcript, art section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='none', confidence='high'),

dict(_src='olleyintro', feature='repetition and refrain',
 claim="Olley states that Kay's fantasy novels often include poetic quotations that he writes himself.",
 source="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction', University of Oxford, 16 December 2020", url=OLLEY_INTRO,
 quote="fantasy works often include poetic quotations", page="subtitle transcript, art section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='herald-pools', confidence='high'),

dict(_src='olleyverse', feature='register modulation',
 claim="Olley says embedded poetry in fantasy narrative works by allowing a change in register.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="By allowing for a change in register", page="subtitle transcript, structure section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='writersinspire page, then .srt at media.podcasts.ox.ac.uk/engfac/fantasy_lit/verse-and-prose-fantasy-literaturedefault.srt',
 registerHint='herald-pools', confidence='high'),

dict(_src='olleyverse', feature='repetition and refrain',
 claim="Olley says poetic quotations in fantasy cluster around moments of particular narrative significance.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="poetic quotations, often cluster around moments of particular narrative significance", page="subtitle transcript, structure section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='herald-pools', confidence='high'),

dict(_src='olleyverse', feature='closing sentence',
 claim="Olley says the closing verse lament in The Lions of Al-Rassan heightens the pathos of the moment.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="Breaking into poetry here heightens the pathos of the moment", page="subtitle transcript, Lions of Al-Rassan section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='herald-pools', confidence='high'),

dict(_src='olleyverse', feature='closing sentence',
 claim="Olley says the closing verse allows Kay to impart a sense of closure to the novel itself.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="it allows Kay to impart a sense of closure", page="subtitle transcript, Lions of Al-Rassan section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='herald-pools', confidence='high'),

dict(_src='olleyverse', feature='cadence and rhythm',
 claim="Olley argues that in Kay the conclusion of the novel's themes is conveyed by form as much as by content.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="It's not just what Kaye writes, but how he writes it", page="subtitle transcript, Lions of Al-Rassan section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='none', confidence='high'),

dict(_src='olleyverse', feature='place and institution description',
 claim="Olley states that although worldbuilding is central to fantasy, readers do not want to feel they are reading an encyclopaedia.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="But we do not want to feel like we're reading an encyclopaedia", page="subtitle transcript, worldbuilding section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='olleyverse', feature='civic record register',
 claim="Olley says a deft author can use a verse quotation to educate the reader about a world's history and culture.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="to educate us about a world history and culture", page="subtitle transcript, worldbuilding section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='olleyverse', feature='civic record register',
 claim="Olley says imitating the ancient and medieval prosimetric form lends fantasy literature an air of authority and authenticity.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="an air of authority and authenticity", page="subtitle transcript, prosimetrum section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='olleyverse', feature='civic record register',
 claim="Olley says the prosimetric form arose partly out of a desire for an authoritative narrative voice.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="a desire for an authoritative narrative voice", page="subtitle transcript, prosimetrum section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='olleyverse', feature='opening sentence',
 claim="Olley says the snatch of verse heard on arrival in Fionavar signposts a major shift in setting and tone without moving the characters.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="A major shift in setting and tone", page="subtitle transcript, Fionavar section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='herald-pools', confidence='high'),

dict(_src='olleyverse', feature='annalist voice and deep time',
 claim="Olley says verse whose subject is a distant legendary past establishes a sense of historical depth.",
 source="Katherine Olley, 'Verse and Prose in Fantasy Literature', University of Oxford, 16 December 2020", url=OLLEY_VERSE,
 quote="establishes a sense of historical depth", page="subtitle transcript, Sam / Gil-galad section",
 kind='analysis', polarity='asserts', date='2020-12-16', routeHint='.srt at media.podcasts.ox.ac.uk',
 registerHint='chronicle-line', confidence='high'),

dict(_src='btdh', feature='other: poetry practice',
 claim="Kay says that around the time he began publishing fiction he stopped sending out poetry for publication while continuing to write it.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="I stopped sending out poetry for publication", page="Questions and Answers on Beyond this Dark House, Q1",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='btdh', feature='other: narrative architecture of the verse',
 claim="Kay says Beyond this Dark House took its structure very much from a narrative point of view.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="very much from a narrative point of view", page="Questions and Answers on Beyond this Dark House, Q2",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='btdh', feature='other: narrative architecture of the verse',
 claim="Kay attributes the narrative shaping of his poetry collection to twenty years of writing fiction.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="a result of twenty years of writing fiction", page="Questions and Answers on Beyond this Dark House, Q2",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='btdh', feature='other: narrative architecture of the verse',
 claim="Kay calls the narrative shape of a book its architecture.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="what I call the 'architecture' of a book", page="Questions and Answers on Beyond this Dark House, Q2",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='btdh', feature='other: poetry practice',
 claim="Kay says the task and labour element he feels in writing fiction was absent from writing the poems.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="the task and labour element of fiction just wasn't there", page="Questions and Answers on Beyond this Dark House, Q3",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='btdh', feature='other: accessibility without prior knowledge',
 claim="Kay says he wants his historical fantasies to be engaging and accessible to readers who know nothing at all of the actual historical periods.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="engaging and accessible to readers who know nothing at all", page="Questions and Answers on Beyond this Dark House, Q3",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='btdh', feature='other: variations on a theme',
 claim="Kay says he likes playing variations on other writers, as he plays variations on historical periods in his fiction.",
 source="Guy Gavriel Kay, Penguin Canada Q&A on Beyond this Dark House, reproduced at brightweavings.com", url=BTDH,
 quote="I like playing variations on some other writers", page="Questions and Answers on Beyond this Dark House, Q4",
 kind='own-words', polarity='asserts', date='2003', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='larb', feature='cadence and rhythm',
 claim="Christine Fischer Guy writes that Kay was a poet first and still publishes poetry from time to time.",
 source="Christine Fischer Guy, 'The Fantastic Worlds of Guy Gavriel Kay', Los Angeles Review of Books, 14 August 2016", url=LARB,
 quote="he was a poet first", page="introduction, third paragraph",
 kind='analysis', polarity='asserts', date='2016-08-14', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

# ---- ANGLE 3 and the withheld-meaning device ----
dict(_src='locus', feature='withheld information and inference',
 claim="Kay says Dorothy Dunnett conveyed a character's intelligence in the Lymond books by having characters say things the reader does not understand.",
 source="Guy Gavriel Kay, interviewed in Locus, 'Margins of History', 2025", url=LOCUS,
 quote="say things the reader doesn't understand", page="interview excerpt, banter paragraph",
 kind='own-words', polarity='asserts', date='2025', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='locus', feature='withheld information and inference',
 claim="Kay says the effect of Dunnett's withheld references in the moment is the impression that these are really smart people.",
 source="Guy Gavriel Kay, interviewed in Locus, 'Margins of History', 2025", url=LOCUS,
 quote="These are really smart people", page="interview excerpt, banter paragraph",
 kind='own-words', polarity='asserts', date='2025', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='locus', feature='dialogue register',
 claim="Kay calls it tricky writing to convey the idea that a character is genuinely smart.",
 source="Guy Gavriel Kay, interviewed in Locus, 'Margins of History', 2025", url=LOCUS,
 quote="to convey the idea that a character is genuinely smart", page="interview excerpt, banter paragraph",
 kind='own-words', polarity='asserts', date='2025', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='locus', feature='consequence on a household',
 claim="Kay says he has long looked for the unwritten histories and the people at the margins of history.",
 source="Guy Gavriel Kay, interviewed in Locus, 'Margins of History', 2025", url=LOCUS,
 quote="looking for the unwritten histories, the people at the margins of history", page="interview excerpt, historical work paragraph",
 kind='own-words', polarity='asserts', date='2025', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='locus', feature='other: biography of the Silmarillion year',
 claim="Locus's biographical note states that Kay and Christopher Tolkien worked on The Silmarillion at Oxford from 1974 to 1975.",
 source="Locus, biographical note accompanying 'Guy Gavriel Kay: Margins of History', 2025", url=LOCUS,
 quote="They worked on the book at Oxford from 1974-75", page="biographical note, first paragraph",
 kind='analysis', polarity='asserts', date='2025', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='foxed', feature='point of view and distance',
 claim="Allsopp says Dunnett almost never shows events from Lymond's point of view.",
 source="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81, 2024", url=FOXED,
 quote="We almost never see events from Lymond's point of view", page="article body, Lymond description",
 kind='analysis', polarity='asserts', date='2024', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='foxed', feature='withheld information and inference',
 claim="Allsopp says the reader can never guess what Lymond is thinking.",
 source="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81, 2024", url=FOXED,
 quote="we can never guess what he is thinking", page="article body, Lymond description",
 kind='analysis', polarity='asserts', date='2024', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='foxed', feature='other: untranslated allusion',
 claim="Allsopp says Dunnett's books are studded with poetry quoted in many languages, a fact her Desert Island Discs persona concealed.",
 source="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81, 2024", url=FOXED,
 quote="studded with poetry quoted in Scots, French, Spanish, Italian, Latin", page="article body, Desert Island Discs paragraph",
 kind='analysis', polarity='asserts', date='2024', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='foxed', feature='place and institution description',
 claim="Allsopp faults Dunnett for always including a clunky exposition scene in which a character recites the political situation.",
 source="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81, 2024", url=FOXED,
 quote="There is also always a clunky exposition scene", page="article body, plot summary paragraph",
 kind='analysis', polarity='disputes', date='2024', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='foxed', feature='plainness and economy',
 claim="Allsopp says Dunnett's best writing has something of Muriel Spark's spikiness but none of Spark's compression.",
 source="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81, 2024", url=FOXED,
 quote="though none of Spark's compression", page="article body, Spark comparison",
 kind='analysis', polarity='disputes', date='2024', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='larb', feature='other: competing memories of one event',
 claim="Kay says that when he switches point of view in Children of Earth and Sky the same conversation is not the same, only resembling its other telling.",
 source="Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016", url=LARB,
 quote="the conversation isn't the same. It bears a resemblance", page="interview, multiple points of view question",
 kind='own-words', polarity='asserts', date='2016-08-14', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='larb', feature='consequence on a household',
 claim="Kay says Children of Earth and Sky starts from the borderlands and the lives of not-powerful people.",
 source="Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016", url=LARB,
 quote="it takes place on the borderlands in the lives of not-powerful people", page="interview, legacy question",
 kind='own-words', polarity='asserts', date='2016-08-14', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='larb', feature='other: seam between invention and record',
 claim="Kay says that if a reader can pick out what is made up and what is real, the storytelling has been botched.",
 source="Guy Gavriel Kay, interviewed by Christine Fischer Guy, Los Angeles Review of Books, 14 August 2016", url=LARB,
 quote="if a reader can pick out what's made up and what's real", page="interview, Bring Up the Bodies question",
 kind='own-words', polarity='asserts', date='2016-08-14', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),
]

RETTINO_THESIS = "https://brightweavings.com/fantasies-of-history-guy-gavriel-kays-synthesis-of-the-historical-fantasy-novel/"
SACNOTH_KAY = "http://sacnoths.blogspot.com/2020/02/kay-and-christopher.html"
SACNOTH_NOAD = "https://sacnoths.blogspot.com/2020/01/charles-noad-comments-was-christophers.html"
ONERING = "https://www.theonering.com/douglas-kane-talks-about-arda-reconstructed/"
ORDWAY_REV = "https://www.mythsoc.org/reviews/arda-reconstructed-ordway.htm"
BW_WORLD = "https://brightweavings.com/worldbuilding/"
RETTINO_BTDH = "https://matthewrettino.com/2014/02/07/beyond-this-dark-house-by-guy-gavriel-kay/"
DDS_WRITERS = "https://dunnettcentral.org/centenary/the-writers-writer/"

CLAIMS += [
# ---- ANGLE 1: what critics have made of the Silmarillion year ----
dict(_src='sacnothkay', feature='other: what Kay actually did on the Silmarillion',
 claim="Rateliff says he knows of no evidence that Kay wrote any of the published Silmarillion.",
 source="John D. Rateliff, 'Kay and Christopher', Sacnoth's Scriptorium, 6 February 2020", url=SACNOTH_KAY,
 quote="I don't know of any evidence that Kay wrote any of it", page="post body, third paragraph",
 kind='analysis', polarity='disputes', date='2020-02-06', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='sacnothkay', feature='other: what Kay actually did on the Silmarillion',
 claim="Rateliff judges it far more likely that Kay helped in the sorting and sequencing of the manuscripts.",
 source="John D. Rateliff, 'Kay and Christopher', Sacnoth's Scriptorium, 6 February 2020", url=SACNOTH_KAY,
 quote="Kay helped in the sorting and sequencing of the manuscripts", page="post body, fourth paragraph",
 kind='analysis', polarity='asserts', date='2020-02-06', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='sacnothkay', feature='other: what Kay actually did on the Silmarillion',
 claim="Rateliff says Kay also served as a sounding board whose advice Christopher Tolkien sometimes took.",
 source="John D. Rateliff, 'Kay and Christopher', Sacnoth's Scriptorium, 6 February 2020", url=SACNOTH_KAY,
 quote="I think Kay also served as a sounding board", page="post body, fourth paragraph",
 kind='analysis', polarity='asserts', date='2020-02-06', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='sacnothkay', feature='other: what Kay actually did on the Silmarillion',
 claim="Rateliff ranks Kay's input to the published Silmarillion above that of Clyde Kilby and Taum Santoski.",
 source="John D. Rateliff, 'Kay and Christopher', Sacnoth's Scriptorium, 6 February 2020", url=SACNOTH_KAY,
 quote="I think Kilby had the least input and Kay probably the most", page="post body, sixth paragraph",
 kind='analysis', polarity='asserts', date='2020-02-06', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='sacnothnoad', feature='other: what Kay actually did on the Silmarillion',
 claim="Noad thinks it reasonable to suppose that Kay's nascent creativity in narrative played a part in the published Silmarillion.",
 source="Charles Noad, comments published by John D. Rateliff, Sacnoth's Scriptorium, 27 January 2020", url=SACNOTH_NOAD,
 quote="Kay's nascent creativity in the matter of narrative played a part", page="Charles Noad's letter, third paragraph",
 kind='analysis', polarity='asserts', date='2020-01-27', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='sacnothnoad', feature='other: silence about the editing method',
 claim="Noad says the details of Kay's contribution will probably never be known unless Kay breaks his silence on the matter.",
 source="Charles Noad, comments published by John D. Rateliff, Sacnoth's Scriptorium, 27 January 2020", url=SACNOTH_NOAD,
 quote="Kay one day breaks his silence on the matter", page="Charles Noad's letter, third paragraph",
 kind='analysis', polarity='asserts', date='2020-01-27', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='sacnothnoad', feature='other: what Kay actually did on the Silmarillion',
 claim="Noad says the passage narrating Thingol's death in the published Silmarillion is unquestionably an invention of the editors.",
 source="Charles Noad, comments published by John D. Rateliff, Sacnoth's Scriptorium, 27 January 2020", url=SACNOTH_NOAD,
 quote="the passage about Thingol's death is an invention of the editors", page="Charles Noad's letter, third paragraph",
 kind='analysis', polarity='asserts', date='2020-01-27', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='sacnothnoad', feature='other: narrative craft versus textual editing',
 claim="Noad argues that producing a finished narrative from edited texts requires a degree of creativity distinct from textual editing, and identifies that as where Kay enters.",
 source="Charles Noad, quoted from an archived Tolkien Plaza review by an anonymous commenter on Sacnoth's Scriptorium, 29 January 2020", url=SACNOTH_NOAD,
 quote="Here I think is where Guy Gavriel Kay enters the picture", page="comment thread, quoted Noad review",
 kind='analysis', polarity='asserts', date='2020-01-29 (quoting an earlier review)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='medium'),

dict(_src='sacnothnoad', feature='other: narrative craft versus textual editing',
 claim="Noad states that it was Kay's idea to produce a finished narrative rather than a scholarly version of the Silmarillion material.",
 source="Charles Noad, quoted from an archived Tolkien Plaza review by an anonymous commenter on Sacnoth's Scriptorium, 29 January 2020", url=SACNOTH_NOAD,
 quote="Kay's idea to produce a finished narrative", page="comment thread, quoted Noad review",
 kind='analysis', polarity='asserts', date='2020-01-29 (quoting an earlier review)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='medium'),

dict(_src='sacnothnoad', feature='other: what Kay actually did on the Silmarillion',
 claim="A commenter reports that Shippey, Flieger and Rosebury each mistook the editors' scene of Thingol's death for J.R.R. Tolkien's own work.",
 source="Anonymous commenter on John D. Rateliff's Sacnoth's Scriptorium, 26 January 2020", url=SACNOTH_NOAD,
 quote="mistakenly referred to the scene of Thingol's death as J.R.R. Tolkien's work", page="comment thread, first comment",
 kind='reader', polarity='asserts', date='2020-01-26', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='medium'),

dict(_src='onering', feature='other: what Kay actually did on the Silmarillion',
 claim="Kane says Christopher Tolkien gave remarkably little insight into the final step in which he created the published work with Kay's help.",
 source="Douglas C. Kane, interviewed at TheOneRing.net about Arda Reconstructed, 2009", url=ONERING,
 quote="he created the final publish work with Guy Kay's help", page="interview, 'how did this book come about' answer",
 kind='analysis', polarity='asserts', date='2009', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='ordwayrev', feature='other: what Kay actually did on the Silmarillion',
 claim="Ordway reports that Kane's answer to whether the editorial cuts changed Tolkien's prose style for the worse seems to be yes.",
 source="Holly Ordway, review of Arda Reconstructed, Mythprint / The Mythopoeic Society", url=ORDWAY_REV,
 quote="Kane's answer seems to be yes", page="review body",
 kind='reception', polarity='asserts', date='2009 (review of the 2009 book)', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='medium'),

# ---- ANGLE 1: the historian-narrator and the chronicle line ----
dict(_src='rettinothesis', feature='opening sentence',
 claim="Rettino says the opening passage of Tigana reads like an entry in a chronicle and lends the novel a historical flavour.",
 source="Matthew Rettino, 'Fantasies of History: Guy Gavriel Kay's Synthesis of the Historical Fantasy Novel', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="The opening passage reads like an entry in a chronicle", page="section on Tigana",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='point of view and distance',
 claim="Rettino says Kay's narrator has a voice that at times resembles a historian's in its distanced relation of events.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="whose voice at times resembles that of a historian", page="section on Tigana, club-story discussion",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='point of view and distance',
 claim="Rettino says the revelation that Duke Sandre faked his death throws doubt on the reliability of the narrator's historian persona in Tigana.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="the reliability of the historian persona of the narrator", page="section on Tigana",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='civic record register',
 claim="Rettino says that when Kay's narratorial voice reveals itself it adopts the authority of the club-story teller and becomes unquestionable.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="it adopts the authority of the club-story teller", page="section on Tigana, club-story discussion",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='point of view and distance',
 claim="Rettino says the omniscient historian's voice in The Lions of Al-Rassan prevents the novel from being a perfectly immersive fantasy.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="due to the narrator's omniscient historian's voice", page="section on The Lions of Al-Rassan",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='annalist voice and deep time',
 claim="Rettino says the narrator of Under Heaven presents himself as one Kitan historian among many.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="The narrator presents himself as one Kitan historian among many", page="section on Under Heaven",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='civic record register',
 claim="Rettino says the narrator of Under Heaven places value on the scholarly consensus of the chronicles he cites.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="the narrator places value on the consensus, like a scholar", page="section on Under Heaven",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='omission as information',
 claim="Rettino says that because not all documents survive in Under Heaven one cannot have a complete and therefore authoritative narrative of history.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="one cannot possibly have a complete and therefore authoritative narrative of history", page="section on Under Heaven",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='omission as information',
 claim="Rettino says Kay's omniscient narrator subverts authoritative historical narration by revealing that many events in history are not known.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="many events in history are not known", page="section on Under Heaven",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='civic record register',
 claim="Rettino says Kay implies that history is always crafted and that narratives are always imposed on recorded facts.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="history is always crafted", page="conclusion",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='rettinothesis', feature='consequence on a household',
 claim="Rettino says historical fantasy in Kay can recover parts of history that have been lost through the omissions of historians.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="recover parts of history that have been lost", page="conclusion",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='rettinothesis', feature='other: biography of the Silmarillion year',
 claim="Rettino's thesis dates Kay's becoming an editor of The Silmarillion to 1974, citing Ordway.",
 source="Matthew Rettino, 'Fantasies of History', 2012 McGill honours thesis, hosted at brightweavings.com", url=RETTINO_THESIS,
 quote="he became an editor of The Silmarillion in 1974", page="introduction",
 kind='analysis', polarity='asserts', date='2012 (posted 2015-07-19)', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwworld', feature='other: Tolkien as influence after the Silmarillion year',
 claim="Ordway says the strongest single literary influence on Kay's Fionavar Tapestry is Tolkien, a natural result of his co-editing The Silmarillion.",
 source="Holly Ordway, 'The World-Building of Guy Gavriel Kay' (1998 independent study, UMass Amherst), hosted at brightweavings.com", url=BW_WORLD,
 quote="The strongest single literary influence on Kay's creation of The Fionavar", page="section on The Fionavar Tapestry",
 kind='analysis', polarity='asserts', date='1998', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

# ---- ANGLE 2: the verse ----
dict(_src='rettinobtdh', feature='cadence and rhythm',
 claim="Rettino says Kay's poetry is only a small departure from his novels, given the lyricism of his prose.",
 source="Matthew Rettino, review of Beyond this Dark House, matthewrettino.com, 7 February 2014", url=RETTINO_BTDH,
 quote="a departure from the grand quasi-historical narratives that define his novels", page="review body, third paragraph",
 kind='reception', polarity='asserts', date='2014-02-07', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='rettinobtdh', feature='other: poetry practice',
 claim="Rettino reports that in his introduction to Beyond this Dark House the poet Don Coles writes that Kay has an ease with crafting words in prose or poetry.",
 source="Matthew Rettino, review of Beyond this Dark House, matthewrettino.com, 7 February 2014", url=RETTINO_BTDH,
 quote="Coles writes that Kay has an ease with crafting words", page="review body, third paragraph",
 kind='reception', polarity='asserts', date='2014-02-07', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='medium'),

dict(_src='rettinobtdh', feature='other: poetry practice',
 claim="Rettino notes that one poem in Beyond this Dark House is dedicated to J.R.R. Tolkien.",
 source="Matthew Rettino, review of Beyond this Dark House, matthewrettino.com, 7 February 2014", url=RETTINO_BTDH,
 quote="nods towards his relationship with J. R. R. Tolkien", page="review body, sixth paragraph",
 kind='reception', polarity='asserts', date='2014-02-07', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='rettinobtdh', feature='metaphor discipline',
 claim="Rettino argues that the two moons in the title poem of Beyond this Dark House are not an allusion to Kay's novels but a slight suggestion about the beloved.",
 source="Matthew Rettino, review of Beyond this Dark House, matthewrettino.com, 7 February 2014", url=RETTINO_BTDH,
 quote="two moons are no cheap allusion to his novels", page="review body, closing analysis",
 kind='reception', polarity='asserts', date='2014-02-07', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='medium'),

# ---- ANGLE 3: the Dunnett side ----
dict(_src='ddswriters', feature='point of view and distance',
 claim="Macpherson says Dunnett breaks the rules of point of view by rarely letting Lymond's sneering mask drop to reveal the man behind it.",
 source="Marie Macpherson, 'A Riddle wrapped in a Mystery inside an Enigma', The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="rarely letting her anti-hero's sneering mask drop", page="Marie Macpherson section",
 kind='analysis', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='live URL returned 403; Wayback raw capture https://web.archive.org/web/20240616085027id_/https://dunnettcentral.org/centenary/the-writers-writer/',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='withheld information and inference',
 claim="Macpherson says Lymond is seen through the eyes of others who constantly change their minds about him, as does the reader.",
 source="Marie Macpherson, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="seen through the eyes of others who constantly change their minds", page="Marie Macpherson section",
 kind='analysis', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='place and institution description',
 claim="Macpherson says that despite the wealth of historical knowledge in her work Dunnett never descends into information dumping.",
 source="Marie Macpherson, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="Dunnett never descends into information dumping", page="Marie Macpherson section",
 kind='analysis', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='concrete sensory noun',
 claim="Macpherson says Dunnett's every researched detail is seamlessly woven in, offering a sensory experience of sounds, tastes, colours and textures.",
 source="Marie Macpherson, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="every detail is seamlessly woven into her astonishing tapestries", page="Marie Macpherson section",
 kind='analysis', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='place and institution description',
 claim="Macpherson attributes to Dunnett a painter's eye for detail that makes her descriptions of scenes linger long after reading.",
 source="Marie Macpherson, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="Her painter's eye for gorgeous detail enlivens descriptions so striking", page="Marie Macpherson section",
 kind='analysis', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='withheld information and inference',
 claim="The screenwriter Gwyneth Hughes reports that even reading the Lymond Chronicles in order there were stretches where she had no idea what was going on.",
 source="Gwyneth Hughes, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="stretches where I had no idea what was going on", page="Gwyneth Hughes section",
 kind='reader', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='withheld information and inference',
 claim="Ellen Kushner says she became obsessed with Dunnett's technique, knowing she was pulling all sorts of tricks without being able to see how.",
 source="Ellen Kushner, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="I knew she was pulling all sorts of tricks", page="Ellen Kushner section",
 kind='analysis', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='plainness and economy',
 claim="Ellen Kushner says she wrote Swordspoint, in conversation with the Lymond Chronicles, keeping the narrative as spare and devious as possible.",
 source="Ellen Kushner, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="keeping the narrative as spare and devious as possible", page="Ellen Kushner section",
 kind='own-words', polarity='applies', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswriters', feature='other: Kay and the Dunnett Society',
 claim="Kay was the keynote speaker at the Dorothy Dunnett Centenary Gathering in 2023.",
 source="The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="author and keynote speaker @ DD Centenary Gathering 2023", page="Guy Gavriel Kay section heading",
 kind='vendor', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='none', confidence='high'),

dict(_src='ddswriters', feature='other: Kay and Dunnett in person',
 claim="Kay says Dunnett was wonderful in person and not only in print, across many encounters.",
 source="Guy Gavriel Kay, The Writers' Writer, Dorothy Dunnett Centenary (Dorothy Dunnett Society)", url=DDS_WRITERS,
 quote="she was wonderful in person, not just in print", page="Guy Gavriel Kay section",
 kind='own-words', polarity='asserts', date='2023 centenary collection (Wayback capture 2024-06-16)',
 routeHint='Wayback raw capture 20240616085027id_',
 registerHint='none', confidence='high'),
]

BW_DUNNETT = "https://brightweavings.com/dunnett/"
BW_FIONAFTER = "https://brightweavings.com/fionavarafterword/"
DDS_BIO = "https://dunnettcentral.org/dorothy"
DDS_WG = "https://dunnettcentral.org/whisperinggallery"
DM_DUNNETT = "https://www.digitalmedievalist.com/reading-lists/dorothy-dunnett/"
BILL3 = "https://www.dorothydunnett.co.uk/blog/lymond-reading-notes/the-play-for-jonathan-crouch-iii-more-blindfold-play.php"
BILL4 = "https://www.dorothydunnett.co.uk/blog/lymond-reading-notes/the-play-for-jonathan-crouch-iv-several-moves-by-a-knight.php"
BILL5 = "https://www.dorothydunnett.co.uk/blog/lymond-reading-notes/the-play-for-jonathan-crouch-v-castling.php"

CLAIMS += [
# ---- Kay's Dunnett memorial: the two angles meet ----
dict(_src='bwdunnett', feature='other: biography of the Silmarillion year',
 claim="Kay says he met Dorothy Dunnett in spring 1975 while living in a village outside Oxford working on the papers that became The Silmarillion.",
 source="Guy Gavriel Kay, 'In Memoriam - Dorothy Dunnett', Locus Magazine, December 2001, reproduced at brightweavings.com", url=BW_DUNNETT,
 quote="working on the papers that became The Silmarillion", page="first paragraph",
 kind='own-words', polarity='asserts', date='2001-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwdunnett', feature='other: what Kay actually did on the Silmarillion',
 claim="Kay says going through the Tolkien correspondence was a part of the editing process he worked on.",
 source="Guy Gavriel Kay, 'In Memoriam - Dorothy Dunnett', Locus Magazine, December 2001, reproduced at brightweavings.com", url=BW_DUNNETT,
 quote="which was a part of the editing process", page="first paragraph",
 kind='own-words', polarity='asserts', date='2001-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwdunnett', feature='other: silence about the editing method',
 claim="Kay says he did not discuss the details of editing The Silmarillion with Dunnett in 1975 and still does not.",
 source="Guy Gavriel Kay, 'In Memoriam - Dorothy Dunnett', Locus Magazine, December 2001, reproduced at brightweavings.com", url=BW_DUNNETT,
 quote="I didn't discuss the details of editing The Silmarillion", page="fourth paragraph",
 kind='own-words', polarity='asserts', date='2001-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwdunnett', feature='repetition and refrain',
 claim="Kay says poetry in many languages and music are inextricably bound up with Dunnett's writing.",
 source="Guy Gavriel Kay, 'In Memoriam - Dorothy Dunnett', Locus Magazine, December 2001, reproduced at brightweavings.com", url=BW_DUNNETT,
 quote="Poetry (in many languages) and music are inextricably bound up", page="closing paragraphs",
 kind='own-words', polarity='asserts', date='2001-12', routeHint='live URL with browser user agent (curl)',
 registerHint='herald-pools', confidence='high'),

dict(_src='bwdunnett', feature='repetition and refrain',
 claim="Kay says Dunnett's books are filled to overflowing with music and verse.",
 source="Guy Gavriel Kay, 'In Memoriam - Dorothy Dunnett', Locus Magazine, December 2001, reproduced at brightweavings.com", url=BW_DUNNETT,
 quote="The books are filled - gloriously so, spilling over", page="closing paragraphs",
 kind='own-words', polarity='asserts', date='2001-12', routeHint='live URL with browser user agent (curl)',
 registerHint='herald-pools', confidence='high'),

# ---- Kay on his own register modulation ----
dict(_src='bwfionafter', feature='register modulation',
 claim="Kay says the principal reason the language of the Fionavar Tapestry differs from his later books is that it was his mythic endeavour.",
 source="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword', HarperPerennial Canada 20th anniversary edition, December 2003, reproduced at brightweavings.com", url=BW_FIONAFTER,
 quote="the language of the trilogy differs from my later books", page="afterword, fifth paragraph",
 kind='own-words', polarity='asserts', date='2003-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwfionafter', feature='register modulation',
 claim="Kay says his later books track a movement, not a consistent one, towards history.",
 source="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword', December 2003, reproduced at brightweavings.com", url=BW_FIONAFTER,
 quote="The others track a movement (not a consistent one) towards history", page="afterword, fifth paragraph",
 kind='own-words', polarity='asserts', date='2003-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwfionafter', feature='register modulation',
 claim="Kay says the language of the Fionavar Tapestry was guided by the matter of the story, a god imprisoned under a mountain and a battle beneath a sacrificial tree.",
 source="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword', December 2003, reproduced at brightweavings.com", url=BW_FIONAFTER,
 quote="Language was guided by that context", page="afterword, fifth paragraph",
 kind='own-words', polarity='asserts', date='2003-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bwfionafter', feature='closing sentence',
 claim="Kay says he does not believe in saying exactly what happens to characters after a novel closes, and that the ending of every book he has written makes this point.",
 source="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword', December 2003, reproduced at brightweavings.com", url=BW_FIONAFTER,
 quote="saying exactly what happens to characters after a novel closes", page="afterword, Sharra paragraph",
 kind='own-words', polarity='asserts', date='2003-12', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='bwfionafter', feature='omission as information',
 claim="Kay says we do not always know what happens next, in life or fiction, and the end of a novel does not demand tying down every life that passed through it.",
 source="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword', December 2003, reproduced at brightweavings.com", url=BW_FIONAFTER,
 quote="we don't always know what happens next, in life or fiction", page="afterword, Sharra paragraph",
 kind='own-words', polarity='asserts', date='2003-12', routeHint='live URL with browser user agent (curl)',
 registerHint='chronicle-line', confidence='high'),

dict(_src='bwfionafter', feature='omission as information',
 claim="Kay says he cut a planned closing conversation for Sharra because the scene felt static and flat, existing only to tie up a thread.",
 source="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword', December 2003, reproduced at brightweavings.com", url=BW_FIONAFTER,
 quote="The scene felt static, flat", page="afterword, Sharra paragraph",
 kind='own-words', polarity='asserts', date='2003-12', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

# ---- Dunnett side: the Society and its close readers ----
dict(_src='ddsbio', feature='annalist voice and deep time',
 claim="The Dorothy Dunnett Society reports that the memorial stone in Edinburgh's Makars' Court carries a quotation from Dunnett asking where the links in the chain joining us to the past are.",
 source="Dorothy Dunnett Society, 'Dorothy Dunnett' biography page", url=DDS_BIO,
 quote="the links in the chain … joining us to the past", page="biography, final paragraph",
 kind='vendor', polarity='asserts', date='accessed via Wayback capture 2025-08-19',
 routeHint='live URL 403; Wayback raw capture https://web.archive.org/web/20250819090027id_/https://dunnettcentral.org/dorothy',
 registerHint='chronicle-line', confidence='high'),

dict(_src='ddsbio', feature='repetition and refrain',
 claim="The Dorothy Dunnett Society describes the House of Niccolo novels as containing poetry and music wrapped up in an evocation of history.",
 source="Dorothy Dunnett Society, 'Dorothy Dunnett' biography page", url=DDS_BIO,
 quote="poetry and music, all wrapped up in an evocation of history", page="biography, House of Niccolo paragraph",
 kind='vendor', polarity='asserts', date='accessed via Wayback capture 2025-08-19',
 routeHint='Wayback raw capture 20250819090027id_',
 registerHint='herald-pools', confidence='high'),

dict(_src='ddswg', feature='withheld information and inference',
 claim="The Dorothy Dunnett Society's magazine publishes essays studying hints in Dunnett's text to establish what a character's purpose was.",
 source="Dorothy Dunnett Society, Whispering Gallery page describing Issue 166 (June 2025)", url=DDS_WG,
 quote="we study the hints in the text that suggest", page="Issue 166 description",
 kind='vendor', polarity='asserts', date='2025-06 issue description',
 routeHint='live URL 403; Wayback raw capture https://web.archive.org/web/20250814193009id_/https://dunnettcentral.org/whisperinggallery',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='ddswg', feature='withheld information and inference',
 claim="The Dorothy Dunnett Society calls the question of which child died during the chess game at Topkapi a perennial argument among readers.",
 source="Dorothy Dunnett Society, Whispering Gallery page describing Issue 166 (June 2025)", url=DDS_WG,
 quote="We revisit a perennial argument in this issue", page="Issue 166 description",
 kind='vendor', polarity='asserts', date='2025-06 issue description',
 routeHint='Wayback raw capture 20250814193009id_',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='dmdunnett', feature='other: untranslated allusion',
 claim="Spangenberg says the quantity of literary allusions and quotations in the Lymond Chronicles drew her into a paper chase after Dunnett's sources.",
 source="Lisa L. Spangenberg, 'The Books of Dorothy Dunnett', Digital Medievalist / Celtic Studies Resources", url=DM_DUNNETT,
 quote="enticed me into a paper chase as I tried to locate", page="introductory paragraph",
 kind='reader', polarity='asserts', date="accessed 2026-09-06 (page undated; written after Dunnett's 2001 death)",
 routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='medium'),

dict(_src='dmdunnett', feature='other: untranslated allusion',
 claim="Spangenberg says the two Dunnett Companion books supply the sources and even the translations for many of the allusions in the novels.",
 source="Lisa L. Spangenberg, 'The Books of Dorothy Dunnett', Digital Medievalist / Celtic Studies Resources", url=DM_DUNNETT,
 quote="offer the sources and even the translations, for many of the allusions", page="books section",
 kind='reader', polarity='asserts', date='accessed 2026-09-06',
 routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='medium'),

dict(_src='bill3', feature='withheld information and inference',
 claim="The Dunnett close-reader 'bill' identifies Dunnett's habit of having one character's assessment explain to the reader what has already taken place, calling it an interesting writing technique.",
 source="bill, 'The Play for Jonathan Crouch - III. More Blindfold Play', Bill's Dunnett Blog (dorothydunnett.co.uk), 9 July 2026", url=BILL3,
 quote="an interesting writing technique", page="reading notes, Sybilla paragraph",
 kind='reader', polarity='asserts', date='2026-07-09', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='bill3', feature='withheld information and inference',
 claim="The Dunnett close-reader 'bill' says Sybilla's assessment is what explains to the reader what has taken place.",
 source="bill, 'The Play for Jonathan Crouch - III. More Blindfold Play', Bill's Dunnett Blog, 9 July 2026", url=BILL3,
 quote="her assessment also explains what has taken place to the reader", page="reading notes, Sybilla paragraph",
 kind='reader', polarity='asserts', date='2026-07-09', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='bill4', feature='withheld information and inference',
 claim="The Dunnett close-reader 'bill' says there are always so many layers to what Dunnett is telling the reader, after listing unanswered questions raised by one exchange.",
 source="bill, 'The Play for Jonathan Crouch - IV: Several Moves by a Knight', Bill's Dunnett Blog, 5 August 2026", url=BILL4,
 quote="Always so many layers to what Dorothy is telling us", page="reading notes, breakfast scene",
 kind='reader', polarity='asserts', date='2026-08-05', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='bill4', feature='other: untranslated allusion',
 claim="The Dunnett close-reader 'bill' wonders what percentage of readers had to look up the word epithalamium to follow the passage.",
 source="bill, 'The Play for Jonathan Crouch - IV: Several Moves by a Knight', Bill's Dunnett Blog, 5 August 2026", url=BILL4,
 quote="had to look up the former", page="reading notes, epithalamium paragraph",
 kind='reader', polarity='asserts', date='2026-08-05', routeHint='live URL with browser user agent (curl)',
 registerHint='none', confidence='high'),

dict(_src='bill5', feature='withheld information and inference',
 claim="The Dunnett close-reader 'bill' says the Game of Kings is written so that the reader realises nothing is ever quite what it seems.",
 source="bill, 'The Play for Jonathan Crouch - V: Castling', Bill's Dunnett Blog, 21 August 2026", url=BILL5,
 quote="nothing is ever quite what it seems", page="reading notes, closing summary",
 kind='reader', polarity='asserts', date='2026-08-21', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),

dict(_src='bill5', feature='withheld information and inference',
 claim="The Dunnett close-reader 'bill' says new readers are told that at about a hundred pages in they will change their mind on everything that has confused them.",
 source="bill, 'The Play for Jonathan Crouch - V: Castling', Bill's Dunnett Blog, 21 August 2026", url=BILL5,
 quote="everything that has confused them up till now", page="reading notes, opening paragraph",
 kind='reader', polarity='asserts', date='2026-08-21', routeHint='live URL with browser user agent (curl)',
 registerHint='dossier-archivist', confidence='high'),
]
