# -*- coding: utf-8 -*-
import json
SEG="https://www.sfsfss.com/stories2/Le%20Guin,%20Ursula%20K.%20-%20The%20Matter%20of%20Seggri.html"
LOA="https://www.loa.org/news-and-views/1491-always-coming-home-the-ursula-k-le-guin-book-that-breaks-the-novel-form-8220wide-open8221/"
HOR="http://rrhorton.blogspot.com/2024/04/review-always-coming-home-by-ursula-k.html"
REA="https://reactormag.com/book-reviews-the-new-edition-of-ursula-k-le-guins-always-coming-home/"
CSU="https://rivercity.wusd.k12.ca.us/subsites/Brandon-Duff/documents/Expository-Reading-and-Writing-Course/Modules/The-Left-Hand-of-Darkness/Student%20Version.pdf"
SEGSRC="Ursula K. Le Guin, 'The Matter of Seggri' (1994), full text transcription, sfsfss.com"
sources=[
 {"title":"Rich Horton, 'Review: Always Coming Home, by Ursula K. Le Guin', Strange at Ecbatan","url":HOR,"kind":"reception","substantive":True,"date":"2024-04-24","route":"direct curl, browser UA"},
 {"title":"Library of America, 'Always Coming Home: The Ursula K. Le Guin book that breaks the novel form “wide open”' — interview with editor Brian Attebery","url":LOA,"kind":"analysis","substantive":True,"date":"2019-05-01","route":"direct curl, browser UA"},
 {"title":"Ursula K. Le Guin, 'The Matter of Seggri' — full text (first pub. Crank! 1994; repr. The Birthday of the World, 2002)","url":SEG,"kind":"own-words","substantive":True,"date":"1994","route":"direct curl; text cross-checked against Dozois YBSF 12th Annual and Flying Cups & Saucers via OpenLibrary search-inside"},
 {"title":"CSU Expository Reading and Writing Course, 'The Left Hand of Darkness' module, Student Version (PDF), Washington USD","url":CSU,"kind":"analysis","substantive":True,"date":"n.d. (CSU ERWC Semester Two)","route":"direct curl of PDF binary; text extracted with pypdf"},
 {"title":"Matthew Keeley, 'A Future in the Author's Backyard: The New Edition of Ursula K. Le Guin's Always Coming Home', Reactor (Tor.com)","url":REA,"kind":"reception","substantive":True,"date":"2019-03-15","route":"direct curl, browser UA"},
]
claims=[
 # --- The Matter of Seggri, primary text
 {"feature":"civic record register","claim":"The frame narrator of 'The Matter of Seggri' opens the story in the past tense with a dated archival event rather than a scene.","source":SEGSRC,"url":SEG,"quote":"The first recorded contact with Seggri was in year 242","page":"opening paragraph","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; page hard-wraps lines, normalise whitespace","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"omission as information","claim":"The Seggri frame records the killing of an observer by naming exactly what the record does not contain.","source":SEGSRC,"url":SEG,"quote":"disclosed the fact, but not the circumstances","page":"frame passage after Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"withheld information and inference","claim":"The Seggri frame marks a gap in the archive with a present-tense statement that no record exists.","source":SEGSRC,"url":SEG,"quote":"There is no record of further contact with Seggri until","page":"frame passage after Captain Aolao-olao's report","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"point of view and distance","claim":"The Seggri compiler uses a first-person-plural editorial voice that states the limit of its holding before excerpting a document.","source":SEGSRC,"url":SEG,"quote":"We have only her report, from which three excerpts follow.","page":"frame passage introducing Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"A policy decision in the Seggri frame is reported as an agentless passive with the number written out in words.","source":SEGSRC,"url":SEG,"quote":"A limit of two hundred visitors from off world was set.","page":"frame passage after Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: self-dating record","claim":"The Seggri frame dates its own assertion against the report that contains it rather than against a calendar year.","source":SEGSRC,"url":SEG,"quote":"As of the date of this report the Seggri have not","page":"frame passage after Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Each document in 'The Matter of Seggri' is introduced by a provenance line naming the kind of document, its recipient and its date.","source":SEGSRC,"url":SEG,"quote":"The following is a memoir given to Ambassador Eritho te Ves","page":"frame line before the Ush memoir","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"terminology consistency","claim":"The Seggri frame names an institutional procedure as a capitalised proper term and leaves it unglossed.","source":SEGSRC,"url":SEG,"quote":"They made Resehavanar's Choice as \"all the truth slowly.\"","page":"frame passage after Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"plainness and economy","claim":"An observer's institutional advice is compressed in the Seggri frame into a nominalisation and two bare verbs.","source":SEGSRC,"url":SEG,"quote":"Her recommendation was to observe and avoid.","page":"frame passage after Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"The Seggri frame reports a demographic figure in the present tense as a hedged ratio, giving the balance as about 12:1.","source":SEGSRC,"url":SEG,"quote":"the gender balance now stands at about 12:1","page":"frame passage after Merriment's notes","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"A generalisation about Seggri's literary institutions is written as an agentless past passive inside the report.","source":SEGSRC,"url":SEG,"quote":"Small value was placed on preserving a \"true\" text","page":"report section on Seggri literature","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"per-speaker register","claim":"The captain's log inside 'The Matter of Seggri' is written in an archaic diction the frame narrator never uses.","source":SEGSRC,"url":SEG,"quote":"They are ordinary drudges, living in towns which belong","page":"Captain Aolao-olao's Report","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl","registerHint":"chronicle-line","confidence":"high"},
 {"feature":"other: bureaucratic idiom","claim":"The closing personal memoir of 'The Matter of Seggri' ends on a filing formula borrowed from an application form.","source":SEGSRC,"url":SEG,"quote":"my record is herewith enclosed","page":"final section, autobiographical sketch","kind":"own-words","polarity":"applies","date":"1994","routeHint":"direct curl; quote spans the page's hard line wrap","registerHint":"dossier-archivist","confidence":"high"},
 # --- Always Coming Home reception / editorial
 {"feature":"other: proportion of record to narrative","claim":"Rich Horton reports that the closing ethnographic section of Always Coming Home runs to some 100 pages.","source":"Rich Horton, Strange at Ecbatan (blog), 2024","url":HOR,"quote":"the final section, some 100 pages, called","page":"paragraph 3","kind":"reception","polarity":"asserts","date":"2024-04-24","routeHint":"direct curl, browser UA","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: readability of the record register","claim":"Rich Horton judges the ethnographic passages of Always Coming Home intellectually interesting but hard to read.","source":"Rich Horton, Strange at Ecbatan (blog), 2024","url":HOR,"quote":"intellectually intriguing, but, really, often a struggle to read","page":"final verdict paragraph","kind":"reception","polarity":"disputes","date":"2024-04-24","routeHint":"direct curl, browser UA","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: readability of the record register","claim":"Rich Horton reads the ethnographic material of Always Coming Home as an author's notes deliberately left in.","source":"Rich Horton, Strange at Ecbatan (blog), 2024","url":HOR,"quote":"like a writer deciding to include all her notes","page":"paragraph 3","kind":"reception","polarity":"disputes","date":"2024-04-24","routeHint":"direct curl, browser UA","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"omission as information","claim":"Le Guin's editorial note on the Kesh novella records its damage in transit and its lost pages in the flat voice of a catalogue entry.","source":"Ursula K. Le Guin, editorial note in Always Coming Home, quoted by Brian Attebery in a Library of America interview","url":LOA,"quote":"was damaged in transit, and the rest of the third chapter","page":"final question of the interview","kind":"own-words","polarity":"applies","date":"2019-05-01","routeHint":"direct curl of the LOA interview page, which reproduces the note verbatim","registerHint":"dossier-archivist","confidence":"medium: read inside the LOA interview rather than in the book itself"},
 {"feature":"withheld information and inference","claim":"The same editorial note states the extent of the loss as a hedged range of pages rather than an exact figure.","source":"Ursula K. Le Guin, editorial note in Always Coming Home, quoted by Brian Attebery in a Library of America interview","url":LOA,"quote":"the last ten or twenty pages of the novel, are lost","page":"final question of the interview","kind":"own-words","polarity":"applies","date":"2019-05-01","routeHint":"direct curl of the LOA interview page","registerHint":"dossier-archivist","confidence":"medium: read inside the LOA interview rather than in the book itself"},
 {"feature":"other: encyclopedic form","claim":"Brian Attebery, the editor of the Library of America edition, calls the form Le Guin chose for Always Coming Home encyclopedic.","source":"Brian Attebery, interviewed by Library of America","url":LOA,"quote":"The encyclopedic form of Always Coming Home was exactly what","page":"third answer","kind":"analysis","polarity":"asserts","date":"2019-05-01","routeHint":"direct curl","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Attebery presents the Back of the Book as a section a reader may begin with for its world-building rather than as an appendix.","source":"Brian Attebery, interviewed by Library of America","url":LOA,"quote":"you can start with “The Back of the Book” and relish","page":"fourth answer","kind":"analysis","polarity":"asserts","date":"2019-05-01","routeHint":"direct curl","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Matthew Keeley argues that the scholarly and cultural notes that would be appendices elsewhere are the main text of Always Coming Home.","source":"Matthew Keeley, Reactor (Tor.com) review, 2019","url":REA,"quote":"are here the core of the text","page":"paragraph beginning 'The table of contents'","kind":"reception","polarity":"asserts","date":"2019-03-15","routeHint":"direct curl, browser UA","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: encyclopedic form","claim":"Matthew Keeley characterises Le Guin's method in Always Coming Home as ethnography rather than epic narrative.","source":"Matthew Keeley, Reactor (Tor.com) review, 2019","url":REA,"quote":"Le Guin’s mode is ethnography, not epic.","page":"paragraph beginning 'The interrupted story'","kind":"reception","polarity":"asserts","date":"2019-03-15","routeHint":"direct curl, browser UA","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"place and institution description","claim":"Matthew Keeley describes Always Coming Home as a book whose ambition is to become a place.","source":"Matthew Keeley, Reactor (Tor.com) review, 2019","url":REA,"quote":"This is a book that aspires to placehood.","page":"paragraph beginning 'This novel represents a culmination'","kind":"reception","polarity":"asserts","date":"2019-03-15","routeHint":"direct curl, browser UA","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"other: reader routing through a record","claim":"Le Guin's own first-page note tells readers that the explanatory pieces are set apart so a narrative reader can skip them.","source":"Ursula K. Le Guin, first-page note to Always Coming Home, quoted in Matthew Keeley's Reactor review","url":REA,"quote":"where those who want narrative can ignore them","page":"paragraph beginning 'The table of contents'","kind":"own-words","polarity":"applies","date":"1985 (quoted 2019-03-15)","routeHint":"direct curl of the Reactor review, which reproduces the note","registerHint":"dossier-archivist","confidence":"medium: read inside a review rather than in the book"},
 # --- LHD teaching module
 {"feature":"point of view and distance","claim":"A CSU Expository Reading and Writing Course module teaches The Left Hand of Darkness as a report addressed by Genly Ai to an official of the Ekumen.","source":"CSU Expository Reading and Writing Course, The Left Hand of Darkness module, Student Version","url":CSU,"quote":"this novel is presented as a report from Genly Ai","page":"Activity 12, p. 73","kind":"analysis","polarity":"asserts","routeHint":"curl of the PDF binary, text extracted with pypdf","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"civic record register","claim":"The same module names the in-world genre of the novel's frame as an ansible document.","source":"CSU Expository Reading and Writing Course, The Left Hand of Darkness module, Student Version","url":CSU,"quote":"It is called an ansible document.","page":"Activity 12, p. 73","kind":"analysis","polarity":"asserts","routeHint":"curl of the PDF binary, text extracted with pypdf","registerHint":"dossier-archivist","confidence":"high"},
]
def write(complete=False, coverage=""):
    out={"complete":complete,"coverage":coverage,"sourcesRead":sources,"claims":claims}
    p="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/found-leguin-record-register.json"
    open(p,"w").write(json.dumps(out,indent=1,ensure_ascii=False))
    print(f"wrote {len(claims)} claims / {len(sources)} sources")
if __name__=="__main__": write(False,"in progress: 5 sources read")
