import re,sys,os
R2="kay-raw2"; R1="kay-raw"
SPEC = {
 "kay-raw2/fantasycafe.txt": ["whimsy","shaping mood","kills nuance","not-them","past works on the present"],
 "kay-raw2/clarkesworld.txt": ["exactly right","fertile ground","non-powerful","know the theme","favorite","Balancing"],
 "kay-raw2/scotspec.txt": ["ebb and flow","protracted","Dianora","deft without","tragedy that pervades","subtle touch"],
 "kay-raw2/jeroen.txt": ["wordiness","keep repeating","clash","savoured","Dunsany","waffles","melancholic"],
 "kay-raw2/shoul.txt": ["mannered","fever-pitch","directly inform","poetic novel","pretentious","compliments"],
 "kay-raw2/strangehorizons.txt": ["rose","reworks","diffuse","historical realism","less idealized","ordinary"],
 "kay-raw2/tarvolon.txt": ["aftermath","sketching","another book that uses","omniscient","distant"],
 "kay-raw2/hatch.txt": ["tessera","gossip","cyclical","sever","play against"],
 "kay-raw2/camelot1989.txt": ["sonnet","latent","what the hell","carefully thought out"],
 "kay-raw2/infinityplus-int.txt": ["Michener","pure pleasure","guesswork","block out"],
 "kay-raw2/locus-margins.txt": ["reduce the gap","teaching a reader","lyric language","margins of history","doesn't understand"],
 "kay-raw2/transmissions.txt": ["cabin in the woods","template","isn't even past","behind","favorite part"],
 "kay-raw2/bigidea2025.txt": ["quarter-turn","rhymes","Big Idea","lecture","yesterday"],
 "kay-raw2/home-away-globe.txt": ["guessing","brings you home","eroding","apply more","without pretense","nine hundred"],
 "kay-raw2/sffworld-2007.txt": ["part of craft","journey","trends"],
 "kay-raw2/soden.txt": ["functional","create space","universalize","lyrical","compress","We're not here"],
 "kay-raw2/ttrpbc.txt": ["numinous","1/3","Terror consumed","trembled","climax"],
 "kay-raw2/rowanwood.txt": ["cadence","invented terminology","foreknowledge","judge","not said","provisional","saga","curt"],
 "kay-raw2/larb.txt": ["speaks in paragraphs","reverence for language","poet first"],
 "kay-raw2/walton-sarantine.txt": ["telescope","throw them away","ironic linking","real enough to bite","pulling back"],
 "kay-raw/fantlit-arch.txt": ["micro and macro","sentence fragment","more spare","impressionistic","would remember that afternoon","series of situations","zoom outward"],
 "kay-raw2/allbery-uh.txt": ["stays within itself","High Drama","hot bath","deft touch","background be background","turn up"],
 "kay-raw2/hp-ceas.txt": ["staccato","says once","omniscient","middle of"],
 "kay-raw2/c2c.txt": ["elegiac tone","lens","meditative","compact, spare"],
 "kay-raw2/ordway.txt": ["Very dark it was","Jaddites, worshippers"],
 "kay-raw2/webbtigana.txt": ["Naming is crucial","plaited","whole tapestry","acts out"],
 "kay-raw2/kleander.txt": ["focalizants","absence of knowledge","very end","written as mosaic","echoing of elements"],
 "kay-raw2/rettino-thesis.txt": ["Jehane's thoughts","entry in a chronicle","expose the structural","elegiac tone to the end"],
 "kay-raw2/rettino-blog.txt": ["arrogant assertions","resemble, but do not"],
 "kay-raw2/revlions.txt": ["dealt with","contemporary feel","withholding information","conspicuously","verbal duels","waste a word","baggage","Shakespearean","short, sharp","screaming point","always on individuals"],
 "kay-raw2/toyryla.txt": ["twice or even thrice","twin snakes","enhances the emotionality","matter-of-fact style","inhabitant of that world","not directly told","sixty per cent","most reports later","khav rooms agreed","executed him on a wheel"],
 "kay-raw2/cobb.txt": ["left behind and yet stayed"],
 "kay-raw2/psychopomp.txt": ["through action","Period and place","imaginative empathy","don't outline"],
 "kay-raw2/hsparallel.txt": ["saga","tenets","variations on historical themes","in private"],
 "kay-raw2/gregcook.txt": ["stiletto","all three","erode"],
 "kay-raw2/fbr-int.txt": ["organically","leave it to readers"],
 "kay-raw2/hotlist2019.txt": ["shape of a novel","told to you by someone","architect"],
 "kay-raw2/cbc2019.txt": ["one to one","allegor"],
 "kay-raw2/lovereading.txt": ["very quiet","strangeness of the past"],
 "kay-raw2/bw-tigana.txt": ["novel about memory"],
 "kay-raw2/gr-balancing.txt": ["balance characters and theme"],
 "kay-raw2/lasmith.txt": ["reflections on the themes","interludes sprinkled"],
 "kay-raw2/speculiction.txt": ["formal use of language","tone is subtle","tributaries"],
 "kay-raw2/wisseman-lions.txt": ["cut away","actually another"],
 "kay-raw2/elitist-uh.txt": ["subtle and elegant","without ever giving","aloof summary"],
 "kay-raw2/anywayward.txt": ["laconic","obliquely","rolls out slowly","reflects the nature"],
 "kay-raw2/onelastsketch.txt": ["lean prose","change his life forever","overwrought","last possible moment","told how to feel","rougher use of language","sentence fragments"],
 "kay-raw2/fbr-abla.txt": ["several different viewpoints","elegant in its simplicity","outskirts"],
 "kay-raw2/globe-abla.txt": ["deciding what to tell","sparse description"],
 "kay-raw2/blair-ros.txt": ["rhetorical repetition","pulling back","spaces between things","never going to see again"],
 "kay-raw2/stefan-ros.txt": ["sotto voce","fatalistic","small ways early"],
 "kay-raw2/littlered-uh.txt": ["hidden meanings","linger through meals"],
 "kay-raw2/fbr-uh.txt": ["exposition always necessary","brushed the edges"],
 "kay-raw2/ff-barnard.txt": ["lyrical without being flowery"],
 "kay-raw2/bormgans.txt": ["visibly withhold","repeated too often"],
 "kay-raw2/sffworld-forum.txt": ["pure dialogue","somehow important","internal monologues","tone and manner"],
 "kay-raw2/kara-fionavar.txt": ["same person talking","switches gears"],
 "kay-raw2/ivana.txt": ["not much dwelled","sad and serene"],
 "kay-raw2/brok3n.txt": ["less of it"],
 "kay-raw2/gr-bend.txt": ["asides to the reader","who tells them"],
 "kay-raw2/rpgnet.txt": ["portentous","people living through history","images on a wall"],
 "kay-raw2/profpope.txt": ["light touch of magic","Burning Wheel"],
 "kay-raw2/locus-2007.txt": ["interesting things happening","universalized"],
 "kay-raw2/locus-2000.txt": ["mosaic","Byzantium","Procopius","research"],
 "kay-raw2/locus-wolfe2016.txt": ["harmonic","mobile phones","walk-on","too ingenious","chronology opens"],
 "kay-raw/reactor-tigana-arch.txt": ["90 percent","everyday rituals","impressionistic","simple word choices"],
 "kay-raw2/reactor-ama.txt": ["detached historian","spelling everything out","rhythm and shape","some others","whichever way","sentimental manipulation"],
 "kay-raw2/wertzone.txt": ["prose","style"],
}
for f,keys in SPEC.items():
    if not os.path.exists(f): print("## MISSING FILE",f); continue
    t=open(f,encoding="utf-8",errors="replace").read()
    t=re.sub(r"\s+"," ",t)
    print("##",f,len(t))
    for k in keys:
        idx=[m.start() for m in re.finditer(re.escape(k),t,flags=re.I)]
        if not idx: print("   ??",k); continue
        for i in idx[:2]:
            print("   >",k,"::",t[max(0,i-110):i+len(k)+140].replace("\n"," "))
