# -*- coding: utf-8 -*-
MU="https://arxiv.org/pdf/2411.04427"; SH="https://arxiv.org/pdf/2504.12522"
CH="https://arxiv.org/pdf/2503.17126"; SU="https://arxiv.org/pdf/2405.16455"
RT="curl with browser user agent to the arXiv PDF, text extracted with pypdf"
R_MU="Murthy, Ullman and Hu (Harvard / Kempner Institute), arXiv 2411.04427"
R_SH="Shypula, Li, Zhang, Padmakumar, Yin and Bastani (Penn / NYU / Berkeley), COLM 2025"
R_CH="Chung, Padmakumar, Roemmele, Sun and Kreminski (Midjourney / NYU), arXiv 2503.17126"
R_SU="Xiao, Li, Xie, Getzen, Fang, Long and Su, Journal of the American Statistical Association (arXiv 2405.16455 v2)"

CLAIMS2=[
{"feature":"homogenisation","claim":"Murthy, Ullman and Hu found aligned models generally display less conceptual diversity than their instruction fine-tuned counterparts.","source":R_MU,"url":MU,"quote":"display less diversity than their instruction fine-","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-11-07","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"Llama-2 7B base, chat and RLAIF variants and comparable open models, observed 2024; register measured: colour association and concept-property behavioural tasks, not prose"},
{"feature":"homogenisation","claim":"Murthy, Ullman and Hu report that no model in their study reached human-like conceptual diversity.","source":R_MU,"url":MU,"quote":"While no model reaches","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-11-07","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"open LLMs including the Llama-2 family, 2024; register measured: two behavioural domains with human data, not prose"},

{"feature":"counter-evidence","claim":"Shypula et al. find that preference-tuned models exhibit greater effective semantic diversity than SFT or base models once quality thresholds are applied.","source":R_SH,"url":SH,"quote":"models exhibit greater effective semantic diversity","page":"Section 1, Introduction","kind":"measurement","polarity":"disputes","date":"2025-04-16","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"LLaMA 2 7B and 70B and LLaMA 3.1 8B and 70B in base, SFT, DPO and RL forms including Tulu-3 PPO and GRPO, observed 2025; registers measured: code generation and WritingPrompts stories"},
{"feature":"other: mechanism of mode collapse","claim":"Shypula et al. found that restricted to high-quality generations only, preference-tuned models produce less semantically diverse content within that subset.","source":R_SH,"url":SH,"quote":"duce less semantically diverse content within that subset","page":"Section 1, Introduction","kind":"measurement","polarity":"asserts","date":"2025-04-16","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"LLaMA 2 and 3.1 families, 2025; register measured: code generation"},
{"feature":"counter-evidence","claim":"Shypula et al. report that for open-ended creative writing preference tuning is linked to greater diversity in lexical patterns.","source":R_SH,"url":SH,"quote":"preference tuning is linked to greater diversity in lexical patterns","page":"Section 1, Introduction","kind":"measurement","polarity":"disputes","date":"2025-04-16","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"LLaMA 2 and 3.1 families, 2025; register measured: WritingPrompts open-ended stories"},

{"feature":"steerability","claim":"Chung et al. report that their trained models had higher diversity than GPT-4o-iter, a baseline that used diversity-inducing prompts.","source":R_CH,"url":CH,"quote":"even higher than •GPT-4o-iter, which used diversity-inducing prompts","page":"Section 5.2, Results","kind":"measurement","polarity":"rejects","date":"2025-03-21","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"GPT-4o (2024-11-20) prompted iteratively against Llama-3.1-8B and Mistral-7B-v0.3 tuned by the authors, observed March 2025; register measured: Reddit r/WritingPrompts short stories"},
{"feature":"reader and expert judgment","claim":"Chung et al. report that human-crafted gold stories scored lower on their reward model than the instruction-tuned models but were far more diverse.","source":R_CH,"url":CH,"quote":"these models but the diversity was far higher","page":"Section 5.2, Results","kind":"measurement","polarity":"asserts","date":"2025-03-21","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"GPT-4o, o1, Claude-3.5-sonnet, DeepSeek-R1 and Llama/Mistral Instruct against human Reddit stories, March 2025; register measured: r/WritingPrompts short fiction"},
{"feature":"steerability","claim":"Chung et al. report an 8B-parameter model trained with their deviation-weighted objective achieving diversity on par with a human-created dataset.","source":R_CH,"url":CH,"quote":"achieve on-par diversity as a human-created","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2025-03-21","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"Llama-3.1-8B tuned with DDPO/DORPO, March 2025; register measured: r/WritingPrompts short fiction"},

{"feature":"other: mechanism of mode collapse","claim":"Xiao et al. argue the Kullback-Leibler-based regularization in RLHF carries an algorithmic bias that in extreme cases produces preference collapse.","source":R_SU,"url":SU,"quote":"this bias could lead to a phenomenon we term preference collapse","page":"Abstract","kind":"analysis","polarity":"asserts","date":"2025-08-25","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"theoretical result validated on OPT and Llama-family models, published in the Journal of the American Statistical Association, 2024-2025; register measured: general natural-language generation"},
{"feature":"steerability","claim":"Xiao et al. report their preference-matching RLHF variant improved alignment with human preferences by 29% to 41% over standard RLHF on one metric.","source":R_SU,"url":SU,"quote":"","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2025-08-25","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"OPT and Llama-family models, 2024-2025; register measured: general natural-language generation"},
]
