# -*- coding: utf-8 -*-
OM="https://openreview.net/pdf?id=3pDMYjpOxk"
RO="live openreview.net PDF route returns an HTML shell; read through the Wayback raw capture web.archive.org/web/20260302103430id_/<url>"
R_OM="O'Mahony, Grinsztajn, Schoelkopf and Biderman (EleutherAI / Limerick / INRIA), ICLR 2024 ME-FoMo workshop"
CLAIMS4=[
{"feature":"other: mechanism of mode collapse","claim":"O'Mahony et al. find that supervised fine-tuning is largely responsible for the drop in next-token prediction diversity.","source":R_OM,"url":OM,"quote":"We find that SFT is largely responsible for the drop","page":"Section 1, Introduction","kind":"measurement","polarity":"asserts","date":"2024-05-11","routeHint":RO,"registerHint":"none","confidence":"high","modelEra":"Pythia 70M to 2.8B fine-tuned by the authors, plus open-weight models, observed 2024; registers measured: factual prompts and creative prompts"},
{"feature":"other: mechanism of mode collapse","claim":"O'Mahony et al. find the reward-based fine-tuning step causes a dramatic decrease in output diversity not present in its SFT precursor.","source":R_OM,"url":OM,"quote":"dramatic decrease in output diversity which is not present","page":"Section 1, Introduction","kind":"measurement","polarity":"asserts","date":"2024-05-11","routeHint":RO,"registerHint":"none","confidence":"high","modelEra":"Pythia 70M to 2.8B with DPO, 2024; registers measured: factual and creative prompts"},
{"feature":"register measured","claim":"O'Mahony et al. observed notably lower diversity for creative-type prompts than factual ones on both of their generation metrics.","source":R_OM,"url":OM,"quote":"lower diversity for creative type prompts for both metrics","page":"Section 3.2 and Figure 1","kind":"measurement","polarity":"asserts","date":"2024-05-11","routeHint":RO,"registerHint":"none","confidence":"high","modelEra":"Pythia-2.8B PLM, SFT and DPO versions at various temperatures, 2024; registers measured: factual prompts and creative prompts"},
{"feature":"lexical tells","claim":"O'Mahony et al. give Llama-2-chat repeating the invented word Frumplenook each time as an example of mode collapse.","source":R_OM,"url":OM,"quote":"Llama-2-chat repeats the term “Frumplenook” each time","page":"Section 1, Introduction, citing Appendix A.4","kind":"measurement","polarity":"asserts","date":"2024-05-11","routeHint":RO,"registerHint":"herald-pools","confidence":"high","modelEra":"Llama-2-chat, 2024; register measured: a word-invention prompt"},
{"feature":"homogenisation","claim":"O'Mahony et al. found industrially fine-tuned models to have very poor output diversity results.","source":R_OM,"url":OM,"quote":"find industrially fine-tuned models to have very poor output diversity results","page":"Section 1, Introduction","kind":"measurement","polarity":"asserts","date":"2024-05-11","routeHint":RO,"registerHint":"none","confidence":"high","modelEra":"open-weight instruction-tuned models compared against the authors' controlled Pythia pipeline, 2024; registers measured: factual and creative prompts"},
]
