# -*- coding: utf-8 -*-
J="https://www.lesswrong.com/posts/t9svvNPNmFf5Qa3TA/mysteries-of-mode-collapse"
B="https://arxiv.org/pdf/2410.12954"
WK="https://aclanthology.org/2024.wikinlp-1.12.pdf"
SB="https://arxiv.org/pdf/2403.00553"
TP="https://arxiv.org/pdf/2405.00492"
RT="curl with browser user agent to the arXiv PDF, text extracted with pypdf"
RJ="live lesswrong.com is behind a Vercel security checkpoint; read through the Wayback raw capture web.archive.org/web/20260725093614id_/<url>"
RW="curl with browser user agent to the ACL Anthology PDF, text extracted with pypdf"
R_J="janus, 'Mysteries of mode collapse', LessWrong / AI Alignment Forum, 8 November 2022, with the author's later correction note"
R_B="Ali Borji, 'A Note on Shumailov et al. (2024)', arXiv 2410.12954 v2"
R_WK="Brooks, Eggert and Peskoff (Princeton), First Workshop on Advancing NLP for Wikipedia (WikiNLP), ACL 2024"
R_SB="Shaib, Govindarajan, Barrow, Sun, Siu, Wallace and Nenkova, arXiv 2403.00553"
R_TP="Peeperkorn, Kouwenhoven, Brown and Jordanous, 'Is Temperature the Creativity Parameter of Large Language Models?', ICCC 2024 (arXiv 2405.00492)"

CLAIMS3=[
{"feature":"other: mechanism of mode collapse","claim":"janus, who coined the mode-collapse usage, later corrected the post to say text-davinci-002 was not trained with RLHF.","source":R_J,"url":J,"quote":"text-davinci-002 was not trained with RLHF","page":"Important correction, head of post","kind":"own-words","polarity":"disputes","date":"2022-11-08","routeHint":RJ,"registerHint":"none","confidence":"high","modelEra":"text-davinci-002, observed November 2022; the correction was added later; register measured: open-ended completions, poems and random numbers"},
{"feature":"steerability","claim":"janus argues that raising the sampling temperature flattens the rest of the output distribution into undifferentiated goo before it helps escape a high-confidence attractor.","source":R_J,"url":J,"quote":"will flatten the rest of the output distribution into undifferentiated goo","page":"Section on temperature","kind":"analysis","polarity":"rejects","date":"2022-11-08","routeHint":RJ,"registerHint":"none","confidence":"medium — an argument illustrated by the author's own sampling plots, not a controlled measurement","modelEra":"text-davinci-002 against GPT-3 base, November 2022; register measured: open-ended prose completions"},
{"feature":"steerability","claim":"janus argues the mode collapse he observed is irreducible to an effective decrease in temperature.","source":R_J,"url":J,"quote":"is irreducible to an effective decrease in temperature","page":"Section on temperature / Attractors","kind":"analysis","polarity":"rejects","date":"2022-11-08","routeHint":RJ,"registerHint":"none","confidence":"medium — the author's inference from behaviour across prompts, not a controlled measurement","modelEra":"text-davinci-002, November 2022; register measured: open-ended prose completions"},
{"feature":"steerability","claim":"janus reports it is sometimes possible to avoid mode collapse using prompt engineering.","source":R_J,"url":J,"quote":"possible to avoid mode collapse using prompt engineering","page":"Section on when mode collapse occurs","kind":"own-words","polarity":"asserts","date":"2022-11-08","routeHint":RJ,"registerHint":"none","confidence":"high","modelEra":"text-davinci-002, November 2022; the examples given are a Python-interpreter framing and few-shot examples establishing that each item differs"},

{"feature":"counter-evidence","claim":"Borji concludes from kernel-density-estimate resampling experiments that the outcomes Shumailov et al. report are a statistical phenomenon and may be unavoidable.","source":R_B,"url":B,"quote":"the outcomes reported are a statistical phenomenon and may be unavoidable","page":"Abstract","kind":"analysis","polarity":"disputes","date":"2024-10-24","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"synthetic Gaussian and uniform distributions rather than a language model, June to October 2024; no natural-language register measured"},

{"feature":"register measured","claim":"Brooks, Eggert and Peskoff detect as many as 5% of 2,909 English Wikipedia articles created in August 2024 as containing significant AI-generated content.","source":R_WK,"url":WK,"quote":"we detect that as many as 5% of 2,909 English","page":"Figure 1 caption","kind":"measurement","polarity":"asserts","date":"2024-11-16","routeHint":RW,"registerHint":"dossier-archivist","confidence":"high","modelEra":"GPTZero and Binoculars detectors run in 2024 on post-GPT-3.5 Wikipedia; register measured: encyclopedic articles, the closest published measurement to an archival register"},
{"feature":"detection and its failures","claim":"Brooks, Eggert and Peskoff report that the Wikipedia articles their detectors flagged are typically of lower quality.","source":R_WK,"url":WK,"quote":"Flagged Wikipedia articles are typically","page":"Abstract","kind":"measurement","polarity":"asserts","date":"2024-11-16","routeHint":RW,"registerHint":"dossier-archivist","confidence":"high","modelEra":"2024 Wikipedia pages judged by GPTZero and Binoculars; register measured: encyclopedic articles in English, German, French and Italian"},

{"feature":"detection and its failures","claim":"Shaib et al. state there is no standard method to measure lexical diversity in language-model output.","source":R_SB,"url":SB,"quote":"there is no standard method to measure","page":"Abstract","kind":"analysis","polarity":"asserts","date":"2024-03-01","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"survey of diversity scores over English texts, 2024; no single register measured"},

{"feature":"steerability","claim":"Peeperkorn et al. found temperature only weakly correlated with novelty in a narrative generation task.","source":R_TP,"url":TP,"quote":"temperature is weakly correlated with novelty","page":"Abstract","kind":"measurement","polarity":"rejects","date":"2024-05-01","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"LLaMA 2-Chat 70B at 6-bit quantisation with top-k 50, observed 2024; register measured: short narrative generation from a fixed prompt"},
{"feature":"steerability","claim":"Peeperkorn et al. conclude that raising temperature does not enable access to a larger slice of the probability distribution.","source":R_TP,"url":TP,"quote":"does not enable access to a larger slice of the probability","page":"Conclusion","kind":"measurement","polarity":"rejects","date":"2024-05-01","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"LLaMA 2-Chat 70B, 2024; register measured: short narratives"},
{"feature":"steerability","claim":"Peeperkorn et al. describe the influence of temperature on creativity as far more nuanced and weak than the creativity-parameter claim suggests.","source":R_TP,"url":TP,"quote":"far more nuanced and weak","page":"Conclusion","kind":"analysis","polarity":"rejects","date":"2024-05-01","routeHint":RT,"registerHint":"none","confidence":"high","modelEra":"authors' reading of their LLaMA 2-Chat 70B narrative study, 2024"},
]
