import re,html,sys,os
def extract(p):
    s=open(p,encoding='utf-8',errors='replace').read()
    s=re.sub(r'<script.*?</script>','',s,flags=re.S|re.I)
    s=re.sub(r'<style.*?</style>','',s,flags=re.S|re.I)
    s=re.sub(r'<noscript.*?</noscript>','',s,flags=re.S|re.I)
    s=re.sub(r'<!--.*?-->','',s,flags=re.S)
    s=re.sub(r'</(p|div|h1|h2|h3|h4|li|blockquote|br|tr)>','\n',s,flags=re.I)
    s=re.sub(r'<br[^>]*>','\n',s,flags=re.I)
    s=re.sub(r'<[^>]+>','',s)
    s=html.unescape(s)
    s=re.sub(r'[ \t]+',' ',s)
    s=re.sub(r'\n\s*\n+','\n',s)
    return s.strip()
for f in sys.argv[1:]:
    out='txt/'+os.path.basename(f).replace('.html','.txt')
    t=extract(f)
    os.makedirs('txt',exist_ok=True)
    open(out,'w',encoding='utf-8').write(t)
    print(out, len(t))
