exec(open('lg-add.py').read())
VC="https://vector-bsfa.com/2020/12/24/review-the-left-hand-of-darkness-by-ursula-k-le-guin/"
WA="https://en.wikipedia.org/wiki/Always_Coming_Home"
WT="https://en.wikipedia.org/wiki/Tales_from_Earthsea"
OL="https://openlibrary.org/search/inside?q=%22A+Description+of+Earthsea%22"
MB="https://sites.middlebury.edu/sciencefiction2017/2019/10/09/le-guin/"
BR="https://www.bookreporter.com/reviews/tales-from-earthsea-the-earthsea-cycle-book-5"

addsrc(title="Nick Hubble, review of The Left Hand of Darkness (Gollancz 50th-anniversary edition, intro. China Miéville), The BSFA Review, reprinted at Vector", url=VC, kind="reception", substantive=True, date="2020-12-24", route="direct curl, browser UA")
addsrc(title="Wikipedia, 'Always Coming Home' (relaying Le Guin, Always Coming Home, 1985)", url=WA, kind="relay", substantive=True, date="retrieved 2026-09-06", route="direct curl, browser UA")
addsrc(title="Wikipedia, 'Tales from Earthsea' (relaying Le Guin, Tales from Earthsea, 2001)", url=WT, kind="relay", substantive=True, date="retrieved 2026-09-06", route="direct curl, browser UA")
addsrc(title="Open Library search-inside results for \"A Description of Earthsea\", returning snippets from Michael Cadden (ed.), Ursula K. Le Guin Beyond Genre (Routledge, 2005)", url=OL, kind="analysis", substantive=True, date="retrieved 2026-09-06", route="Open Library search-inside (snippet-only); the Internet Archive per-item search-inside endpoints returned empty or 'Item not available' for this book")
addsrc(title="Michael Newbury's Science Fiction course blog (Middlebury College), student responses on Le Guin's 'The Question of Sex'", url=MB, kind="reader", substantive=True, date="2019-10-09", route="direct curl, browser UA")
addsrc(title="Kathy Weissman, review of Tales from Earthsea, Bookreporter.com", url=BR, kind="reception", substantive=True, date="2001-05-04", route="direct curl, browser UA")
addsrc(title="libcom.org, 'Four ways to forgiveness - Ursula Le Guin' (hosting a scanned PDF of the 1996 collection)", url="https://libcom.org/article/four-ways-forgiveness-ursula-le-guin", kind="relay", substantive=False, date="2013-05-20", route="direct curl; page is a posting of an unauthorised full-text PDF, not used")
addsrc(title="NEA Big Read reader resource for The Left Hand of Darkness", url="https://www.arts.gov/initiatives/nea-big-read/left-hand-darkness", kind="analysis", substantive=False, date="n/a", route="NOT FOUND — arts.gov returns 'Gone'; no NEA Big Read guide for this title located by search")

# --- Vector / Hubble: the field-notes register quoted at length ---
addclaim(feature="civic record register", claim="The Ekumen field notes in The Left Hand of Darkness state a biological rule in the present tense with a generic plural subject.", source="Le Guin, The Left Hand of Darkness ch. 7, quoted in Nick Hubble's BSFA Review notice", url=VC, quote="Normal individuals have no predisposition to either sexual role in kemmer", page="quoted block, cited to p. 91", kind="own-words", polarity="applies", date="2020-12-24 (quoting the 1969 novel)", routeHint="direct curl, browser UA; the block quote sits above Hubble's first paragraph of commentary", registerHint="dossier-archivist", confidence="high")
addclaim(feature="withheld information and inference", claim="The same field notes mark the limit of the observer's own experience in a first-person parenthesis.", source="Le Guin, The Left Hand of Darkness ch. 7, quoted in Nick Hubble's BSFA Review notice", url=VC, quote="I haven’t seen this done in rural Karhide", page="quoted block, cited to p. 91", kind="own-words", polarity="applies", date="2020-12-24 (quoting the 1969 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="The field notes cite a second named observer inside a parenthesis before qualifying his report.", source="Le Guin, The Left Hand of Darkness ch. 7, quoted in Nick Hubble's BSFA Review notice", url=VC, quote="Otie Nim wrote that in the Orgoreyn region the use", page="quoted block, cited to p. 91", kind="own-words", polarity="applies", date="2020-12-24 (quoting the 1969 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: figures in a record", claim="The field notes give one interval as an exact decimal and the next as a two-number range in the same sentence.", source="Le Guin, The Left Hand of Darkness ch. 7, quoted in Nick Hubble's BSFA Review notice", url=VC, quote="the 8.4 month gestation period and the 6 to 8 month", page="quoted block, cited to p. 91", kind="own-words", polarity="applies", date="2020-12-24 (quoting the 1969 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="plainness and economy", claim="The field notes close the ambisexuality section with a twelve-word sentence built entirely of common kinship nouns.", source="Le Guin, The Left Hand of Darkness ch. 7, quoted in Nick Hubble's BSFA Review notice", url=VC, quote="the mother of several children may be the father of several more", page="quoted block, cited to p. 91", kind="own-words", polarity="applies", date="2020-12-24 (quoting the 1969 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="Hubble notes that the field notes are held by the envoy, giving the document a stated chain of custody.", source="Nick Hubble, The BSFA Review, 2020", url=VC, quote="These notes are in the possession of Genly Ai", page="paragraph after the block quote", kind="reception", polarity="asserts", date="2020-12-24", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")

# --- Wikipedia relays ---
addclaim(feature="place and institution description", claim="The Back of the Book runs to about a fifth of the pages of Always Coming Home and presents cultural lore.", source="Wikipedia relaying Le Guin, Always Coming Home (1985)", url=WA, quote="about a fifth of the number of pages, presents cultural lore", page="section 'Summary'", kind="relay", polarity="asserts", date="retrieved 2026-09-06", routeHint="direct curl, browser UA; the primary is the novel itself, not reachable in full text", registerHint="dossier-archivist", confidence="medium: relay, not the primary")
addclaim(feature="civic record register", claim="The Back of the Book is described as carrying the attributions or annotations an ethnographic fieldworker would make.", source="Wikipedia relaying Le Guin, Always Coming Home (1985)", url=WA, quote="attributions or annotations that an ethnographic fieldworker might make", page="section 'Summary'", kind="relay", polarity="asserts", date="retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: relay, not the primary")
addclaim(feature="place and institution description", claim="Each attributed Kesh text carries a provenance line naming the teller, her town and the recipient.", source="Le Guin, Always Coming Home (1985), item headings relayed by Wikipedia", url=WA, quote="As told by Little Bear Woman of Sinshan to the Editor", page="section 'Summary', list of texts attributed to Little Bear Woman", kind="relay", polarity="applies", date="retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: relay of the book's headings, not the primary")
addclaim(feature="place and institution description", claim="A map inside Always Coming Home is captioned with the person who gave it to the Editor.", source="Le Guin, Always Coming Home (1985), item heading relayed by Wikipedia", url=WA, quote="given to the Editor by Little Bear Woman of Sinshan", page="section 'Summary'", kind="relay", polarity="applies", date="retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: relay of the book's caption, not the primary")
addclaim(feature="plainness and economy", claim="Pandora states the Kesh population as a seven-word sentence containing no number.", source="Le Guin, Always Coming Home (1985), quoted by Wikipedia with a citation", url=WA, quote="There are not too many of them", page="section 'Setting'", kind="relay", polarity="applies", date="retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: relay quoting the primary")
addclaim(feature="other: encyclopedic form", claim="'A Description of Earthsea' is characterised as a reference narrative covering peoples, languages, history and magic.", source="Wikipedia relaying Le Guin, Tales from Earthsea (2001)", url=WT, quote="a reference narrative covering Earthsea's peoples, languages, history, and magic", page="section on contents", kind="relay", polarity="asserts", date="retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: relay, not the primary")

# --- Cadden via Open Library search-inside ---
addclaim(feature="other: encyclopedic form", claim="Michael Cadden's volume records that 'A Description of Earthsea' runs to almost thirty pages of Earthsea lore.", source="Michael Cadden (ed.), Ursula K. Le Guin Beyond Genre (2005), via Open Library search-inside", url=OL, quote="almost thirty pages of Earthsea lore", page="search-inside snippet", kind="analysis", polarity="asserts", date="2005", routeHint="Open Library search-inside, query \"A Description of Earthsea\"; snippet-only, page number not shown", registerHint="dossier-archivist", confidence="medium: snippet-only, no surrounding page")
addclaim(feature="other: encyclopedic form", claim="Cadden's volume classes 'A Description of Earthsea' as neither story nor afterword.", source="Michael Cadden (ed.), Ursula K. Le Guin Beyond Genre (2005), via Open Library search-inside", url=OL, quote="a text that is neither story nor afterword", page="search-inside snippet", kind="analysis", polarity="asserts", date="2005", routeHint="Open Library search-inside, query \"A Description of Earthsea\"; snippet-only", registerHint="dossier-archivist", confidence="medium: snippet-only, the sentence is cut off after 'afterword'")

# --- Middlebury student readers on the field-notes chapter ---
addclaim(feature="civic record register", claim="A student reader observes that the field-notes chapter could have been written as straightforward declarative sentences but is not.", source="Tori Koontz, comment on Michael Newbury's Science Fiction course blog, Middlebury College, 2019", url=MB, quote="which could just as easily be written in straight-forward, declarative sentences", page="comment of 9 October 2019", kind="reader", polarity="disputes", date="2019-10-09", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: a student's reading, not published criticism")
addclaim(feature="place and institution description", claim="A student reader describes the field-notes chapter as proceeding outward from the individual to the interpersonal to the social.", source="Cole Easton, comment on Michael Newbury's Science Fiction course blog, Middlebury College, 2019", url=MB, quote="from the individual level, to the pairing level/interpersonal level, to the social", page="comment of 9 October 2019", kind="reader", polarity="asserts", date="2019-10-09", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: a student's reading, not published criticism")

# --- Bookreporter on the Earthsea appendix ---
addclaim(feature="place and institution description", claim="Kathy Weissman lists the topics of the Earthsea appendix as history, language, royal dynasties and dragons.", source="Kathy Weissman, review of Tales from Earthsea, Bookreporter.com, 2001", url=BR, quote="covers topics such as history, language, royal dynasties, and dragons", page="penultimate paragraph", kind="reception", polarity="asserts", date="2001-05-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: encyclopedic form", claim="Weissman credits Le Guin with constructing Earthsea with a scholar's seriousness and eye for detail.", source="Kathy Weissman, review of Tales from Earthsea, Bookreporter.com, 2001", url=BR, quote="with a scholar's seriousness and eye for detail", page="penultimate paragraph", kind="reception", polarity="asserts", date="2001-05-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")

json.dump(d, open(P,'w'), indent=1, ensure_ascii=False)
print('sources',len(d['sourcesRead']),'claims',len(d['claims']))
