exec(open('lg-add.py').read())

SH="https://strangehorizons.com/wordpress/non-fiction/articles/i-never-did-like-smart-ass-utopians-on-always-coming-home-by-ursula-k-le-guin/"
TT="http://talktoyouniverse.blogspot.com/2008/10/genly-ai-ridiculously-close-look.html"
BG="https://booksongif.substack.com/p/left-hand-of-darkness-ursula-le-guin"
GK="https://ray.yorksj.ac.uk/id/eprint/6566/8/14744740221126984.pdf"
DY="https://dannyreviews.com/h/Always_Coming_Home.html"
TP="https://troypress.com/a-history-of-earthsea/"

addsrc(title="Mazin Saleem, '\"I never did like smart-ass utopians\"—on Always Coming Home by Ursula K. Le Guin', Strange Horizons", url=SH, kind="analysis", substantive=True, date="2018-11-26", route="direct curl, browser UA")
addsrc(title="Juliette Wade, 'Genly Ai: A Ridiculously Close Look', TalkToYoUniverse", url=TT, kind="analysis", substantive=True, date="2008-10-04", route="direct curl, browser UA")
addsrc(title="Books on GIF (Mike), review #280 of 'The Left Hand of Darkness' (Orbit 1992 reprint), with the novel's opening excerpt reproduced", url=BG, kind="own-words", substantive=True, date="2026-04-26", route="direct curl, browser UA")
addsrc(title="Ben Garlick and Liesl King, 'A geography beyond the Anthropocene: Ursula Le Guin's Always Coming Home as topophilia for survival', cultural geographies (accepted manuscript, York St John RaY repository)", url=GK, kind="analysis", substantive=True, date="2022", route="PDF binary fetched, text extracted with pypdf")
addsrc(title="Danny Yee, review of Always Coming Home (Bantam Books 1987), Danny Yee's Book Reviews", url=DY, kind="reception", substantive=True, date="1995", route="direct curl, browser UA")
addsrc(title="Troy Press, 'A History of Earthsea'", url=TP, kind="reception", substantive=True, date="n.d.", route="direct curl, browser UA")
addsrc(title="Aaron Fuegi, 'The World of Earthsea', Boston University personal page", url="https://scv.bu.edu/~aarondf/earthsea/earthsea.html", kind="reader", substantive=False, date="n.d.", route="direct curl; fan summary, no sentence-level evidence")
addsrc(title="Course Hero, 'A Description of Earthsea.pdf'", url="https://www.coursehero.com/file/60886041/A-Description-of-Earthseapdf/", kind="relay", substantive=False, date="n.d.", route="BLOCKED — Cloudflare interstitial on direct curl and browser UA")

# --- Juliette Wade close reading of the LHD archival header ---
addclaim(feature="civic record register", claim="Juliette Wade observes that the archival header opening The Left Hand of Darkness contains no verbs at all.", source="Juliette Wade, 'Genly Ai: A Ridiculously Close Look', TalkToYoUniverse blog, 2008", url=TT, quote="Notice that there are no verbs in this excerpt", page="paragraph on the second voice", kind="analysis", polarity="asserts", date="2008-10-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="point of view and distance", claim="Wade argues that the verbless archival header removes every actor and leaves what she calls a sourceless truth.", source="Juliette Wade, 'Genly Ai: A Ridiculously Close Look', TalkToYoUniverse blog, 2008", url=TT, quote="leaving us with a sourceless truth", page="paragraph on the second voice", kind="analysis", polarity="asserts", date="2008-10-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="opening sentence", claim="Wade identifies the register of the novel's archival header as that of the notes heading a scientific report.", source="Juliette Wade, 'Genly Ai: A Ridiculously Close Look', TalkToYoUniverse blog, 2008", url=TT, quote="the notes that would head a scientific report", page="paragraph on the second voice", kind="analysis", polarity="asserts", date="2008-10-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="annalist voice and deep time", claim="Wade reads the header's dating line as showing that the institution keeps its own measurement of time.", source="Juliette Wade, 'Genly Ai: A Ridiculously Close Look', TalkToYoUniverse blog, 2008", url=TT, quote="it also dictates its own measurement of time", page="paragraph on the number of alien names", kind="analysis", polarity="asserts", date="2008-10-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="register modulation", claim="Wade counts three distinct voices in the opening page of The Left Hand of Darkness, of which the archival header is the second.", source="Juliette Wade, 'Genly Ai: A Ridiculously Close Look', TalkToYoUniverse blog, 2008", url=TT, quote="This is a voice of ultimate authority", page="opening paragraphs", kind="analysis", polarity="asserts", date="2008-10-04", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: 'three different voices' and the quoted phrase are in adjacent sentences, not one")

# --- LHD opening excerpt, own words ---
addclaim(feature="opening sentence", claim="The Left Hand of Darkness opens with a filing header that names an archive and a document number before any sentence with a verb.", source="Ursula K. Le Guin, The Left Hand of Darkness, ch. 1 opening, reproduced in Books on GIF review #280", url=BG, quote="From the Archives of Hain. Transcript of Ansible Document", page="'An opening excerpt'", kind="own-words", polarity="applies", date="1969 (text as reprinted by Orbit, 1992)", routeHint="direct curl, browser UA; the excerpt is block-quoted near the end of the review", registerHint="dossier-archivist", confidence="high")
addclaim(feature="civic record register", claim="Genly Ai's first sentence names the document he is writing as a report before it narrates anything.", source="Ursula K. Le Guin, The Left Hand of Darkness, ch. 1 opening, reproduced in Books on GIF review #280", url=BG, quote="I’ll make my report as if I told a story", page="'An opening excerpt'", kind="own-words", polarity="applies", date="1969 (text as reprinted by Orbit, 1992)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="withheld information and inference", claim="The report's opening concedes that its account is neither wholly the reporter's nor told by him alone.", source="Ursula K. Le Guin, The Left Hand of Darkness, ch. 1 opening, reproduced in Books on GIF review #280", url=BG, quote="The story is not all mine, nor told by me alone", page="'An opening excerpt'", kind="own-words", polarity="applies", date="1969 (text as reprinted by Orbit, 1992)", registerHint="dossier-archivist", routeHint="direct curl, browser UA", confidence="high")
addclaim(feature="annalist voice and deep time", claim="The report fixes its starting point by an ordinal day of a numbered year before naming any person or place.", source="Ursula K. Le Guin, The Left Hand of Darkness, ch. 1 opening, reproduced in Books on GIF review #280", url=BG, quote="It starts on the 44th diurnal of the Year 1491", page="'An opening excerpt'", kind="own-words", polarity="applies", date="1969 (text as reprinted by Orbit, 1992)", routeHint="direct curl, browser UA", registerHint="chronicle-line", confidence="high")
addclaim(feature="civic record register", claim="A local timekeeping custom is stated as a bare present-tense sentence of seven ordinary words.", source="Ursula K. Le Guin, The Left Hand of Darkness, ch. 1 opening, reproduced in Books on GIF review #280", url=BG, quote="It is always the Year One here", page="'An opening excerpt'", kind="own-words", polarity="applies", date="1969 (text as reprinted by Orbit, 1992)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")

json.dump(d, open(P,'w'), indent=1, ensure_ascii=False)
print('sources',len(d['sourcesRead']),'claims',len(d['claims']))
