exec(open('lg-add.py').read())
AS="https://astrofella.wordpress.com/2019/12/05/rocannons-world-ursula-le-guin/"
UT="https://www.ursulakleguin.com/tales-from-earthsea"
AD="http://anthrodendum.org/2018/01/26/ursula-ak-le-guin-interplanetary-anthropologist-2/"
addsrc(title="Books & Boots (astrofella), 'Rocannon's World by Ursula Le Guin (1966)', quoting the novel's opening handbook entry in full", url=AS, kind="reception", substantive=True, date="2019-12-05", route="direct curl, browser UA")
addsrc(title="Ursula K. Le Guin Foundation, 'Tales from Earthsea' book page (Harcourt, May 2001; now Clarion Books)", url=UT, kind="vendor", substantive=True, date="retrieved 2026-09-06", route="direct curl, browser UA")
addsrc(title="Anand Pandian, 'Ursula K. Le Guin, Interplanetary Anthropologist', anthro{dendum}", url=AD, kind="analysis", substantive=True, date="2018-01-26", route="direct curl, browser UA")
addsrc(title="Michael Cadden (ed.), Ursula K. Le Guin Beyond Genre, Internet Archive item ursulakleguinbey0000cadd", url="https://archive.org/details/ursulakleguinbey0000cadd", kind="analysis", substantive=False, date="2005", route="BLOCKED — api.archivelab.org search-inside and the per-item fulltext endpoint both returned empty or 'Item not available'; reached only as Open Library snippets")

# --- Rocannon's World handbook entry: the purest gazetteer sentences ---
addclaim(feature="place and institution description", claim="Rocannon's World opens with a gazetteer heading that gives a galactic area number, an entry number and the planet name.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted in full by Books & Boots", url=AS, quote="Galactic Area 8, No. 62: FOMALHAUT II", page="prologue quotation, blog paragraph 3", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA; the blogger says he quotes the passage in full, and the block follows immediately", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="A people is described in the handbook by a verbless string of adjectives closing on a height range in centimetres.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted by Books & Boots", url=AS, quote="Highly intelligent, fully hominoid nocturnal troglodytes, 120-135 cm. in height", page="prologue quotation, Species I-A", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="civic record register", claim="An intervention by the institution is recorded as a verbless clause with a grade and a date range and no actor.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted by Books & Boots", url=AS, quote="Technology enhanced to Industrial, Point C, during League Mission of 252-254", page="prologue quotation, Species I-A", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="terminology consistency", claim="Each species entry in the handbook ends on a two-word status code.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted by Books & Boots", url=AS, quote="Status C-Prime", page="prologue quotation, end of Species I-A entry", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA; the parallel entry ends 'Status E-Query'", registerHint="dossier-archivist", confidence="high")
addclaim(feature="withheld information and inference", claim="The handbook grades the strength of its own evidence by saying that brief contacts only indicated what it reports.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted by Books & Boots", url=AS, quote="indicated village and nomadic communal societies", page="prologue quotation, Species I-B", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA; the word before it is broken by OCR as 'con~ tacts'", registerHint="dossier-archivist", confidence="high")
addclaim(feature="plainness and economy", claim="The handbook delivers a fiscal verdict on a whole people in a two-word sentence.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted by Books & Boots", url=AS, quote="Currently untaxable", page="prologue quotation, Species I-B", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="dm-facing sentence", claim="The handbook addresses its reader with a bare imperative telling him to note a social division.", source="Le Guin, Rocannon's World (1966), opening handbook entry, quoted by Books & Boots", url=AS, quote="Note horizontal social cleavage into 2 pseudo-races", page="prologue quotation, Species II", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dm-page", confidence="high")
addclaim(feature="place and institution description", claim="The planetary entry states landmass coverage as a percentage of the planet's surface.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="Four major landmasses, Northwest, Southwest, East and Antarctic Continents, occupy 38%", page="second quotation, physical description", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: cross-reference apparatus", claim="The survey entry sends the reader to numbered maps in a parenthesis inside the sentence.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="see maps 3114-a, b, c, 3115-a, b", page="second quotation, First Geographical Survey", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: cross-reference apparatus", claim="The same entry cross-refers forward within the document rather than repeating the material.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="see description of intelligent species below", page="second quotation, First Geographical Survey", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="annalist voice and deep time", claim="The handbook's history is a labelled section whose first sentence is a dated passive naming the expedition.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="History: The planet was charted by the Elieson Expedition in 202", page="second quotation, History", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="chronicle-line", confidence="high")
addclaim(feature="civic record register", claim="A survey is recorded as a verbless line of label, year and named director.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="First Ethnographic Survey, 321, Director: G. Rocannon", page="second quotation, last line", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="civic record register", claim="A prohibition is recorded as a dated passive naming the authority that imposed it and the reason it stands.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="the planet was placed under Interdict by the Allworld HILF Authority", page="second quotation, Control and Taxation Missions", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: figures in a record", claim="The planetary entry gives the length of a year down to the second.", source="Le Guin, Rocannon's World (1966), second handbook entry, quoted by Books & Boots", url=AS, quote="Revolution: 800 Earthdays 8 hrs. 11 min. 42 sec", page="second quotation, physical description", kind="own-words", polarity="applies", date="2019-12-05 (quoting the 1966 novel)", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="register modulation", claim="The blogger contrasts the folk-tale style of the novel's opening story with the more factual style of the rest.", source="Books & Boots (astrofella), review of Rocannon's World, 2019", url=AS, quote="juxtaposed with the rest of the narrative which are cast in much more factual", page="section 'The plot'", kind="reception", polarity="asserts", date="2019-12-05", routeHint="direct curl, browser UA", registerHint="none", confidence="high")

# --- Le Guin Foundation on the Earthsea appendix ---
addclaim(feature="other: encyclopedic form", claim="Le Guin's Foundation describes Tales from Earthsea as concluding with an account of the world's history, people, languages, literature and magic.", source="Ursula K. Le Guin Foundation, Tales from Earthsea book page", url=UT, quote="an account of Earthsea's history, people, languages, literature, and magic", page="book description", kind="vendor", polarity="asserts", date="retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")

# --- Pandian on Rocannon's opening survey ---
addclaim(feature="opening sentence", claim="Anand Pandian describes Rocannon's World as opening with the ethnographer's survey of hominoid species on one world.", source="Anand Pandian, anthro{dendum}, 2018", url=AD, quote="opening with his survey of “hominoid” species on the world", page="paragraph beginning 'Le Guin's books teem with anthropologists'", kind="analysis", polarity="asserts", date="2018-01-26", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")

json.dump(d, open(P,'w'), indent=1, ensure_ascii=False)
print('sources',len(d['sourcesRead']),'claims',len(d['claims']))
