exec(open('lg-add.py').read())
BW="https://www.ursulakleguin.com/the-birthday-of-the-world-1"
FW="https://www.ursulakleguin.com/foreword-the-birthday-of-the-world"
addsrc(title="Ursula K. Le Guin Foundation, 'Excerpts from The Birthday of the World' (openings of Coming of Age in Karhide, The Matter of Seggri, Unchosen Love, Mountain Ways, Solitude, Old Music and the Slave Women, The Birthday of the World, Paradises Lost)", url=BW, kind="own-words", substantive=True, date="collection 2002; page retrieved 2026-09-06", route="direct curl, browser UA")
addsrc(title="Ursula K. Le Guin, 'Foreword: The Birthday of the World' (dated 2001), on the author's official site", url=FW, kind="own-words", substantive=True, date="2001; page retrieved 2026-09-06", route="direct curl, browser UA")

# --- Foreword: Le Guin's own account of the record register ---
addclaim(feature="civic record register", claim="Le Guin describes 'The Matter of Seggri' as a compendium of reports on the society of one world.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="is a compendium of reports on the society of a world", page="paragraph on 'The Matter of Seggri'", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA; the foreword is reproduced whole on the author's official site", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="Le Guin places the Seggri documents in the archives of the Historians of Hain.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="These documents are from the archives of the Historians of Hain", page="paragraph on 'The Matter of Seggri'", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="humour", claim="Le Guin characterises the Hainish historians' relation to reports with a squirrels-and-nuts simile.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="who are to reports as squirrels are to nuts", page="paragraph on 'The Matter of Seggri'", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="point of view and distance", claim="Le Guin identifies the first voice of The Left Hand of Darkness as a Mobile of the Ekumen making a report.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="the first voice is that of a Mobile of the Ekumen", page="paragraph on The Left Hand of Darkness", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="naming and forms of address", claim="Le Guin defines the Ekumen in six words as a non-directive, information-gathering consortium of worlds.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="a non-directive, information-gathering consortium of worlds", page="paragraph on the League of Worlds", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="annalist voice and deep time", claim="Le Guin's Hainish historians are described as knowing that events keep happening and will happen again.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="know that it keeps happening and will happen again", page="second paragraph", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA", registerHint="chronicle-line", confidence="high")
addclaim(feature="other: how the record is made", claim="Le Guin says she worked out the kinship rules of the planet O by drawing charts with symbols and arrows.", source="Ursula K. Le Guin, Foreword to The Birthday of the World (2001)", url=FW, quote="I drew charts, with male and female symbols, and lines", page="paragraph on A Fisherman of the Inland Sea", kind="own-words", polarity="asserts", date="2001", routeHint="direct curl, browser UA", registerHint="none", confidence="high")

# --- The excerpts page: the record sentences themselves ---
addclaim(feature="place and institution description", claim="The introduction to 'Unchosen Love' is signed with an address chain running from farmhold through village and watershed to the planet.", source="Ursula K. Le Guin, 'Unchosen Love' introduction, excerpted on the author's official site", url=BW, quote="of Inanan Farmhold of Tag Village on the Southwest Watershed", page="'Unchosen Love', Introduction byline", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="dm-facing sentence", claim="'Mountain Ways' opens with an explicit note addressed to readers unfamiliar with the planet before the story starts.", source="Ursula K. Le Guin, 'Mountain Ways', excerpted on the author's official site", url=BW, quote="Note for readers unfamiliar with the planet O", page="'Mountain Ways', headnote", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dm-page", confidence="high")
addclaim(feature="civic record register", claim="The headnote defines a social institution in a present-tense passive sentence of ordinary words.", source="Ursula K. Le Guin, 'Mountain Ways' headnote, excerpted on the author's official site", url=BW, quote="Ki'O society is divided into two halves or moieties, called", page="'Mountain Ways', headnote", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="terminology consistency", claim="The headnote sets out the four permitted relationships as a labelled list, each pairing given its own named term.", source="Ursula K. Le Guin, 'Mountain Ways' headnote, excerpted on the author's official site", url=BW, quote="The Morning woman and the Evening man (the \"Morning marriage\")", page="'Mountain Ways', headnote list", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="omission as information", claim="The headnote records that the forbidden relationships have no name at all except sacrilege.", source="Ursula K. Le Guin, 'Mountain Ways' headnote, excerpted on the author's official site", url=BW, quote="they aren't called anything, except sacrilege", page="'Mountain Ways', headnote", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="'Mountain Ways' opens on a present-tense sentence that places settlements in a named upland and states their density.", source="Ursula K. Le Guin, 'Mountain Ways', excerpted on the author's official site", url=BW, quote="In the stony uplands of the Deka Mountains the farmholds are few", page="'Mountain Ways', first line of the story", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="A settlement is identified by a present-tense copula sentence that nests farm inside village inside watershed inside river inside continent inside planet.", source="Ursula K. Le Guin, 'Mountain Ways', excerpted on the author's official site", url=BW, quote="Danro is the farthest farm of Oro Village in the High Watershed", page="'Mountain Ways', second section", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="plainness and economy", claim="An economic relation between a people and their herds is stated as a plain two-clause sentence that reverses itself.", source="Ursula K. Le Guin, 'Mountain Ways', excerpted on the author's official site", url=BW, quote="The farmers are dependent on the ariu; the ariu are not", page="'Mountain Ways', second section", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="opening sentence", claim="'Solitude' opens with a header declaring the text an addition to a named, numbered prior report on a planet.", source="Ursula K. Le Guin, 'Solitude', excerpted on the author's official site", url=BW, quote="An addition to \"POVERTY: The Second Report on Eleven-Soro\"", page="'Solitude', headnote", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="point of view and distance", claim="The narrator of 'Solitude' names her mother's profession in a bare apposition before saying anything about her.", source="Ursula K. Le Guin, 'Solitude', excerpted on the author's official site", url=BW, quote="My mother, a field ethnologist, took the difficulty of learning anything", page="'Solitude', first paragraph", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="per-speaker register", claim="A Gethenian narrator explains the offworld convention for numbering years before stating her own.", source="Ursula K. Le Guin, 'Coming of Age in Karhide', excerpted on the author's official site", url=BW, quote="They call the year of some portentous event Year One", page="'Coming of Age in Karhide', opening", kind="own-words", polarity="applies", date="2002 collection; page retrieved 2026-09-06", routeHint="direct curl, browser UA", registerHint="chronicle-line", confidence="high")

json.dump(d, open(P,'w'), indent=1, ensure_ascii=False)
print('sources',len(d['sourcesRead']),'claims',len(d['claims']))
