exec(open('lg-add.py').read())
SH="https://strangehorizons.com/wordpress/non-fiction/articles/i-never-did-like-smart-ass-utopians-on-always-coming-home-by-ursula-k-le-guin/"
GK="https://ray.yorksj.ac.uk/id/eprint/6566/8/14744740221126984.pdf"
DY="https://dannyreviews.com/h/Always_Coming_Home.html"
TP="https://troypress.com/a-history-of-earthsea/"

# --- Saleem on the Kesh record register ---
addclaim(feature="civic record register", claim="Mazin Saleem notes that Le Guin repeatedly uses the modal 'may' when the book describes a Kesh custom.", source="Mazin Saleem, Strange Horizons, 2018", url=SH, quote="Again and again, Le Guin used the word", page="section 'Thou mayest'", kind="analysis", polarity="asserts", date="2018-11-26", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="Saleem quotes a Kesh description of a ritual song whose permitted repetitions are given as an open list ending in the option of not at all.", source="Mazin Saleem quoting Always Coming Home, Strange Horizons, 2018", url=SH, quote="it may be sung four times, or five times, or nine times", page="section 'Thou mayest'", kind="own-words", polarity="applies", date="2018-11-26", routeHint="direct curl, browser UA; Le Guin's sentence quoted inside Saleem's", registerHint="dossier-archivist", confidence="high")
addclaim(feature="omission as information", claim="Saleem reports that the book's own note offers two competing readings of a disputed Kesh text rather than a verdict.", source="Mazin Saleem quoting Always Coming Home, Strange Horizons, 2018", url=SH, quote="a vengeful biography pretending to be autobiography", page="section 'Thou mayest'", kind="own-words", polarity="applies", date="2018-11-26", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="humour", claim="Saleem characterises the tone of an editorial note on a neighbouring people in Always Coming Home as dry.", source="Mazin Saleem, Strange Horizons, 2018", url=SH, quote="a note dryly explains how", page="section 'There and back again'", kind="analysis", polarity="asserts", date="2018-11-26", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="point of view and distance", claim="Saleem describes a gloss attached to a Kesh story as spoken by a commentator on that story in the present tense.", source="Mazin Saleem, Strange Horizons, 2018", url=SH, quote="writes a commentator on the story", page="section 'There and back again'", kind="analysis", polarity="asserts", date="2018-11-26", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="edition and house style", claim="Saleem gives the length of Always Coming Home as 525 pages and lists field notes first among its contents.", source="Mazin Saleem, Strange Horizons, 2018", url=SH, quote="At 525 pages, including field notes, stories, maps, charts", page="opening section", kind="analysis", polarity="asserts", date="2018-11-26", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="translation and register", claim="Saleem reports Le Guin's explanation that she withheld the accents on Kesh names until the Back of the Book.", source="Mazin Saleem paraphrasing Le Guin, Strange Horizons, 2018", url=SH, quote="purposefully left the accents off Kesh names until the Back", page="closing section on language", kind="analysis", polarity="asserts", date="2018-11-26", routeHint="direct curl, browser UA; Saleem's paraphrase, not Le Guin's transcribed words", registerHint="dossier-archivist", confidence="medium: reported as Le Guin's explanation, no citation given")

# --- Garlick & King ---
addclaim(feature="place and institution description", claim="Garlick and King describe the Back of the Book as encyclopaedia-like appendices holding the novel's practical information.", source="Ben Garlick and Liesl King, cultural geographies, 2022", url=GK, quote="appendices referred to as ‘The Back of the Book’", page="p. 3-4, section on the text", kind="analysis", polarity="asserts", date="2022", routeHint="PDF binary, pypdf extraction; the word 'encyclopaedia-like' ends the previous line", registerHint="dossier-archivist", confidence="high")
addclaim(feature="point of view and distance", claim="Garlick and King characterise Pandora as an implicit translator or reporter rather than a character with a stake in the events.", source="Ben Garlick and Liesl King, cultural geographies, 2022", url=GK, quote="narrator or else implicit translator/reporter", page="p. 4", kind="analysis", polarity="asserts", date="2022", routeHint="PDF binary, pypdf extraction", registerHint="dossier-archivist", confidence="high")
addclaim(feature="civic record register", claim="A Kesh social fact is stated in Always Coming Home as a rule of the language's grammar.", source="Le Guin, Always Coming Home, quoted in Garlick and King, cultural geographies, 2022", url=GK, quote="Kesh grammar makes no provision for a relation of ownership", page="p. 11 (note 107)", kind="own-words", polarity="applies", date="2022 (quoting the 1985 novel)", routeHint="PDF binary, pypdf extraction; quoted inside the article", registerHint="dossier-archivist", confidence="high")
addclaim(feature="civic record register", claim="Kesh social disapproval is reported in Always Coming Home as an agentless past passive listing three disapproved things.", source="Le Guin, Always Coming Home, quoted in Garlick and King, cultural geographies, 2022", url=GK, quote="a competitive attitude were all socially disapproved", page="p. 11 (note 109)", kind="own-words", polarity="applies", date="2022 (quoting the 1985 novel)", routeHint="PDF binary, pypdf extraction", registerHint="dossier-archivist", confidence="high")
addclaim(feature="place and institution description", claim="Garlick and King report the Kesh life expectancy from the novel as a range of thirty to forty years.", source="Ben Garlick and Liesl King, cultural geographies, 2022", url=GK, quote="short life expectancies (30–40 years)", page="p. 11", kind="analysis", polarity="asserts", date="2022", routeHint="PDF binary, pypdf extraction", registerHint="dossier-archivist", confidence="high")

# --- Danny Yee ---
addclaim(feature="place and institution description", claim="Danny Yee describes the Back of the Book as presenting the Kesh in a more traditional ethnographic form than the rest of the volume.", source="Danny Yee, review of Always Coming Home, 1995", url=DY, quote="contains additional information about the Kesh in more traditional ethnographic form", page="paragraph 2", kind="reception", polarity="asserts", date="1995", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: ethnography without history", claim="Danny Yee contrasts Le Guin's world as having no history with Tolkien's as having almost no ethnographic detail.", source="Danny Yee, review of Always Coming Home, 1995", url=DY, quote="Tolkien's world has almost no ethnographic detail", page="paragraph 1", kind="reception", polarity="asserts", date="1995", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")
addclaim(feature="other: encyclopedic form", claim="Danny Yee classes Always Coming Home as a fictional ethnography rather than a novel.", source="Danny Yee, review of Always Coming Home, 1995", url=DY, quote="it is a fictional ethnography rather than a novel", page="paragraph 1", kind="reception", polarity="asserts", date="1995", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="high")

# --- Troy Press ---
addclaim(feature="other: encyclopedic form", claim="Troy Press describes 'A Description of Earthsea' as a descriptive essay written alongside the five stories of Tales from Earthsea.", source="Troy Press, 'A History of Earthsea'", url=TP, quote="she ended up writing five short stories plus a descriptive essay", page="paragraph on world-building", kind="reception", polarity="asserts", date="n.d.", routeHint="direct curl, browser UA", registerHint="dossier-archivist", confidence="medium: the blogger's label for the appendix, not Le Guin's")
addclaim(feature="other: how the record is made", claim="Le Guin states that research into a nonexistent history is done by telling the story and finding out what happened.", source="Ursula K. Le Guin, Foreword to Tales from Earthsea, quoted by Troy Press", url=TP, quote="research into nonexistent history is to tell the story", page="paragraph on world-building", kind="own-words", polarity="asserts", date="2001 (foreword), quoted n.d.", routeHint="direct curl, browser UA; the same sentence is quoted at greater length by Mazin Saleem in Strange Horizons", registerHint="none", confidence="high")

json.dump(d, open(P,'w'), indent=1, ensure_ascii=False)
print('sources',len(d['sourcesRead']),'claims',len(d['claims']))
