import json, io
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/kay-00.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-kay-i360-382.json"
d=json.load(open(src,encoding='utf-8'))
V=[
 (360,"VERIFIED_VERBATIM","so I’m very lightly edited","Raw HTML of brightweavings.com/sfsite/ (HTTP 200, browser UA). GGK: “I’m very slow and somewhat obsessive, so have never delivered a book until I’m quite sure it is just about where I want it to be… and so I’m very lightly edited. In theory, one might have expected problems, given three editors in three countries.” The three-publisher limb: the page says “three editors in three countries” and the interviewer names them earlier — “you are one of the few who separate the Canadian, US and UK markets” — with Kay confirming he is published by a house based in each country, so the English-language limb holds from the page itself, though the phrase “English-language” is not on this page (it is Kay’s wording in the Deep Magic interview)."),
 (361,"VERIFIED_VERBATIM","I also like to work with cross-sections of a culture or society","Raw HTML of brightweavings.com/sfchannel/ (HTTP 200). “I also like to work with cross-sections of a culture or society, so I’ll tend to have figures from many different classes.” Quote verbatim; both limbs on the page."),
 (363,"VERIFIED_VERBATIM","grow in importance because I like their voice","Same page, earlier paragraph on creating characters: “Other characters, who I think of as minor to start with, grow in importance because I like their voice.” Quote verbatim; page hint (early, on making characters) is accurate."),
 (364,"VERIFIED_VERBATIM","By telescoping events into effectively two generations","Raw HTML of brightweavings.com/sfx/ (HTTP 200), final answer of the interview: the Reconquista “took place over a period of 300 years… By telescoping events into effectively two generations it allows me to intensify the emotional and intellectual response to what really happened by bringing it home to the same set of characters.” The reader limb is carried by the page’s next sentences: “whatever is a strength for the author is, by automatic extension, a strength for the reader.”"),
 (365,"VERIFIED_VERBATIM","great gobbets of raw fact are tucked into the book","Raw HTML of brightweavings.com/challengingdestiny/ (HTTP 200), answer on the fact/fiction balancing act: “that great gobbets of raw fact are tucked into the book like an undigested meal. You have to get over them in order to get back to the story. That’s failed fiction writing for me.” Quote and every limb verbatim."),
 (371,"VERIFIED_VERBATIM","examine how those great events can impact on ordinary lives","Raw HTML of brightweavings.com/eventhorizon/ (HTTP 200). Freund introduces Kay as author “most recently, Sailing to Sarantium” and asks the premise; Kay: “This time I wanted to make the protagonist less central to the great events and at the same time examine how those great events can impact on ordinary lives.”"),
 (372,"VERIFIED_VERBATIM","as part of his worldbuilding “game,” but here you have it straight","Same transcript, answer to Ran on the differing LIONS and SARANTIUM maps: “Tolkien would have tried to construct some brilliant elaborate ‘explanation’ for the difference, as part of his worldbuilding ‘game,’ but here you have it straight.” The declining limb is the closing clause."),
 (373,"VERIFIED_VERBATIM","you have to KNOW the theme before you try variations","Raw HTML of brightweavings.com/deepmagic/ (HTTP 200), answer on settings and history: “if you are doing a fantasy based on a period, a variation on a theme, as it were, you have to KNOW the theme before you try variations!” Capitalisation of KNOW matches."),
 (374,"VERIFIED_VERBATIM","be skeptical when writers present intuitive processes as thought-out planning","Raw HTML of brightweavings.com/on-the-strengths-of-fiction-done-as-near-history/ (HTTP 200), caveat paragraph: “But here’s a caveat: be skeptical when writers present intuitive processes as thought-out planning. This was an evolution for me, not a strategic concept. I discovered what I was doing… I didn’t lay it out in advance.”"),
 (375,"VERIFIED_VERBATIM","Readers will never learn the year of the Treaty of Utrecht","Same essay, downsides paragraph: “There are also downsides, or risks, to how I work… Readers will never learn the year of the Treaty of Utrecht in my novels. They will not assuage any desire to ‘learn the real facts’ about a specific period.” Both limbs on the page."),
 (378,"VERIFIED_VERBATIM","I wanted to explore interactions not ideologies","Same essay, Lions of Al-Rassan section (immediately after “I changed the three religions of our history”): “I wanted to explore interactions not ideologies.” Quote verbatim, book attribution correct."),
 (379,"VERIFIED_VERBATIM","each reader makes the book they read","Same essay, A Song for Arbonne section: “If they preferred to just treat the book as a tale … well, each reader makes the book they read.” Quote verbatim; section attribution correct."),
 (380,"VERIFIED_VERBATIM","There are no rules. That’s my main contribution to this discussion","Raw HTML of brightweavings.com/some-writing-advice-dont-take-others-advice/ (HTTP 200), middle of the body. “This discussion” is the essay’s subject, writing advice, opened by “I am, more or less, allergic to writing advice.”"),
 (381,"VERIFIED_VERBATIM","People everywhere tell you not to use italics","Same essay, second paragraph: “I am, more or less, allergic to writing advice… Writing advice is an industry on steroids. People everywhere tell you not to use italics.” Allergy, industry and italics limbs all in the opening paragraphs."),
 (382,"VERIFIED_VERBATIM","history may not repeat, but it rhymes","Raw HTML of whatever.scalzi.com/2025/05/28/the-big-idea-guy-gavriel-kay-4/ (HTTP 200), the Big Idea essay for Written on the Dark: “A wise man who was not Mark Twain wrote that history may not repeat, but it rhymes. (His name was Theodore Reik and he was a psychoanalyst … but it always seems to be credited to Twain.) I share that thought. I write with that idea in mind.”"),
]
byidx={i:(v,t,n) for i,v,t,n in V}
verdicts=[]
for c in d["claims"]:
    v,t,n=byidx[c["index"]]
    verdicts.append({"index":c["index"],"verdict":v,"trueWording":t,"note":n})
assert len(verdicts)==15
json.dump({"name":"kay","chunk":0,"claims":d["claims"],"verdicts":verdicts},open(out,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print("wrote",out)
