# -*- coding: utf-8 -*-
import json

U_REACTOR="https://reactormag.com/how-gene-wolfe-starts-a-story-and-where-to-start-reading-his-work/"
U_KELLY="https://www.markrkelly.com/Blog/2014/07/03/rereading-gene-wolfes-the-fifth-head-of-cerberus/"
U_KM="https://katemacdonald.net/2017/01/09/gene-wolfes-the-shadow-of-the-torturer/"
U_MEFI="https://www.metafilter.com/149475/Gene-Wolfe-The-Reliably-Unreliable-Author"
U_5HC="https://www.sffchronicles.com/threads/11050/"
U_PEACE="https://www.sffchronicles.com/threads/528814/"
U_URTH="http://lists.urth.net/pipermail/urth-urth.net/2006-September/%s.html"

R_LIVE="live URL fetched raw with a browser user agent (curl), HTML parsed to text"
R_WB="lists.urth.net dead from here (curl 000); Wayback raw capture https://web.archive.org/web/2021id_/<url> (byte-identical to the live capture)"

sources=[
 dict(title="How Gene Wolfe Starts a Story (and Where to Start Reading His Work) — Matthew Keeley, Reactor (Tor.com)",url=U_REACTOR,kind="analysis",substantive=True,date="2017-11-09",route=R_LIVE),
 dict(title="Rereading Gene Wolfe's “The Fifth Head of Cerberus” — Mark R. Kelly, Views from Crestmont Drive",url=U_KELLY,kind="analysis",substantive=True,date="2014-07-03",route=R_LIVE),
 dict(title="Gene Wolfe's The Shadow of the Torturer — Kate Macdonald (podcast script, Really Like This Book)",url=U_KM,kind="analysis",substantive=True,date="2017-01-09",route=R_LIVE),
 dict(title="Gene Wolfe: The Reliably Unreliable Author — MetaFilter thread 149475 (78 comments)",url=U_MEFI,kind="reader",substantive=True,date="2015-05-08",route=R_LIVE),
 dict(title="The Fifth Head of Cerberus (caution: spoilers!) — SFF Chronicles thread 11050 (Ian Sales essay 2006; felicibusbrevis analysis 2013)",url=U_5HC,kind="reader",substantive=True,date="2006-06-13",route=R_LIVE),
 dict(title="Peace (*SPOILERS*) — SFF Chronicles thread 528814",url=U_PEACE,kind="reader",substantive=True,date="2010-09-14",route=R_LIVE),
 dict(title="(urth) Close Reading: Torturer Chapter I — JWillard, Urth mailing list (project proposal + chapter-1 observations)",url=U_URTH%"058531",kind="reader",substantive=True,date="2006-09-04",route=R_WB),
 dict(title="(urth) Close Reading: Torturer Chapter I — 'b sharp', Urth mailing list",url=U_URTH%"002915",kind="reader",substantive=True,date="2006-09-05",route=R_WB),
 dict(title="(urth) Close Reading: Torturer Chapter I — Dan'l Danehy-Oakes, Urth mailing list",url=U_URTH%"002922",kind="reader",substantive=True,date="2006-09-05",route=R_WB),
 dict(title="(urth) Close Reading: Torturer Chapter I — Roy C. Lackey, Urth mailing list",url=U_URTH%"002935",kind="reader",substantive=True,date="2006-09-05",route=R_WB),
]

def C(feature,claim,source,url,quote,page,kind,polarity,date,route,reg="none",conf="high"):
    return dict(feature=feature,claim=claim,source=source,url=url,quote=quote,page=page,kind=kind,
                polarity=polarity,date=date,routeHint=route,registerHint=reg,confidence=conf)

K="Matthew Keeley, Reactor (Tor.com), 9 November 2017"
MK="Kate Macdonald, katemacdonald.net, 9 January 2017"
MRK="Mark R. Kelly, Views from Crestmont Drive, 3 July 2014"

claims=[
 C("opening sentence","Keeley reads the opening line of The Fifth Head of Cerberus as a riff on the opening of Proust's Swann's Way.",K,U_REACTOR,"is a riff on Proust’s","body, paragraph on Wolfe's reading","analysis","asserts","2017-11-09",R_LIVE),
 C("withheld information and inference","Keeley says the grammar of that opening sentence carries a slight clue to the story.",K,U_REACTOR,"a slight clue to the story in the sentence’s grammar","body, paragraph on Wolfe's reading","analysis","asserts","2017-11-09",R_LIVE,"dossier-archivist"),
 C("omission as information","Keeley says the reader eventually learns why the comma is missing from the phrase “my brother David”.",K,U_REACTOR,"We eventually do learn why that comma is missing.","body, paragraph on Wolfe's reading","analysis","asserts","2017-11-09",R_LIVE,"dossier-archivist"),
 C("point of view and distance","Keeley says a single first-person sentence near the end of an otherwise third-person Wolfe book asks readers to reconsider everything already read.",K,U_REACTOR,"asks readers to reconsider everything that they’ve already read","body, paragraph after the 5HC discussion","analysis","asserts","2017-11-09",R_LIVE),

 C("withheld information and inference","Kelly says the narrator of The Fifth Head of Cerberus describes his surroundings at face value and leaves understanding to the reader.",MRK,U_KELLY,"describes his surroundings at face value, leaving it up to the reader","body, after the plot summary","analysis","asserts","2014-07-03",R_LIVE,"dossier-archivist"),
 C("withheld information and inference","Kelly says a Wolfe story carries an underlying real story that the point-of-view character does not necessarily understand and that Wolfe expects the reader to deduce.",MRK,U_KELLY,"which Wolfe counts on the reader to being able to deduce","body, after the plot summary","analysis","asserts","2014-07-03",R_LIVE,"dossier-archivist"),
 C("place and institution description","Kelly says the fact that the narrator's large house is a brothel emerges in the course of the narration rather than being stated.",MRK,U_KELLY,"It develops that this large house is a brothel.","body, plot summary","analysis","asserts","2014-07-03",R_LIVE,"dossier-archivist"),
 C("withheld information and inference","Kelly, summarising Joan Gordon's 1986 Starmont study, says the novella's theme is underscored by small details in the text such as the house's address.",MRK+", relaying Joan Gordon's 1986 Starmont House study of Wolfe",U_KELLY,"underscored by small details in the text","body, paragraph on Joan Gordon","analysis","applies","2014-07-03",R_LIVE,"dossier-archivist","medium — Kelly's paraphrase of Gordon, not Gordon's own words"),
 C("other: precision as a constant of the prose","Kelly says it is difficult to find a paragraph anywhere in Wolfe that is not both precise and poetic.",MRK,U_KELLY,"not both precise and poetic","body, before the sample paragraph","analysis","asserts","2014-07-03",R_LIVE),

 C("withheld information and inference","Macdonald says the things Severian knows that the reader does not are left unexplained because they are the mysteries of his trade.",MK,U_KM,"are not explained because they are the mysteries of his trade","body, plot summary","analysis","asserts","2017-01-09",R_LIVE,"dossier-archivist"),
 C("compounds and coinages","Macdonald says Wolfe's new vocabulary is mainly nouns that sound as if made from a familiar root by changing a vowel or suffix.",MK,U_KM,"His new vocabulary (mainly nouns) sounds as if it was altered","body, vocabulary paragraph","analysis","asserts","2017-01-09",R_LIVE),
 C("compounds and coinages","Macdonald says the meaning of Wolfe's strange words is fairly obvious from context.",MK,U_KM,"Their meaning is fairly obvious in the context","body, vocabulary paragraph","analysis","asserts","2017-01-09",R_LIVE),
 C("archaism","Macdonald says Wolfe also changes the meaning of real words, giving destrier as her example.",MK,U_KM,"He also changes the meaning of real words, like destrier","body, vocabulary paragraph","analysis","asserts","2017-01-09",R_LIVE),
 C("civic record register","Macdonald says Wolfe's frame invites the reader to think about these stories as histories, reports, assessments and commentaries rather than only as story.",MK,U_KM,"we also think about these stories as histories, reports, assessments, commentaries","body, paragraph on the appended note about invented words","analysis","asserts","2017-01-09",R_LIVE,"dossier-archivist"),
 C("point of view and distance","Macdonald says the torture is reported from a very clinical viewpoint.",MK,U_KM,"we’re told about the event from a very clinical viewpoint","body, paragraph on the torture scenes","analysis","asserts","2017-01-09",R_LIVE,"dossier-archivist"),
 C("omission as information","Macdonald says the narration withholds screams, bleeding flesh and details of pain from the torture scenes, so the reader feels no immediate horrified empathy.",MK,U_KM,"we aren’t told anything about screams, bleeding flesh, details of pain","body, paragraph on the torture scenes","analysis","asserts","2017-01-09",R_LIVE,"dossier-archivist"),
 C("other: aside as misdirection","Macdonald says Wolfe casts casual asides into the reader's path just when attention is expected elsewhere.",MK,U_KM,"casting casual asides down in our path","body, paragraph on gaps in knowledge","analysis","asserts","2017-01-09",R_LIVE),

 C("omission as information","A MetaFilter reader reports that in Shadow of the Torturer the narrator meets a blind man and never mentions that he is blind.","MetaFilter user “straight”, thread 149475, 8 May 2015, 9:00 AM",U_MEFI,"encounters a blind man but never mentions he is blind","comment by straight, 9:00 AM","reader","asserts","2015-05-08",R_LIVE,"dossier-archivist"),
 C("withheld information and inference","A MetaFilter reader disputes the ambiguity reading, arguing Wolfe's unreliability is a puzzle readers assemble from careful cluing rather than genuine epistemic uncertainty.","MetaFilter user “RogerB”, thread 149475, 8 May 2015, 8:50 AM",U_MEFI,"assemble based on careful cluing the truth that the narrator doesn't know","comment by RogerB, 8:50 AM","reader","disputes","2015-05-08",R_LIVE),
 C("withheld information and inference","A MetaFilter reader says the text reveals how horrible Severian is through what still manages to slip through his own narration.","MetaFilter user “Pseudoephedrine”, thread 149475, 8 May 2015, 12:29 PM",U_MEFI,"revealing how horrible he is through what still manages to slip","comment by Pseudoephedrine, 12:29 PM","reader","asserts","2015-05-08",R_LIVE,"dossier-archivist"),
 C("point of view and distance","A MetaFilter reader says some Wolfe narrators are sincere recorders of what they experienced who have fundamentally misunderstood the events they record.","MetaFilter user “byanyothername”, thread 149475, 8 May 2015, 9:00 AM",U_MEFI,"sincere recorders of the truth they've experienced, but they've fundamentally misunderstood","comment by byanyothername, 9:00 AM","reader","asserts","2015-05-08",R_LIVE,"chronicle-line"),
 C("withheld information and inference","A MetaFilter reader names deliberate frustration of expectations as the Wolfe device more central than unreliable narration.","MetaFilter user “straight”, thread 149475, 8 May 2015, 9:11 AM",U_MEFI,"the deliberate frustration of expectations","comment by straight, 9:11 AM","reader","asserts","2015-05-08",R_LIVE),
 C("diction (native vs latinate)","A MetaFilter reader states that in The Book of the New Sun everything archaic to Severian is rendered as Latin.","MetaFilter user “Ipsifendus”, thread 149475, 8 May 2015, 8:57 AM",U_MEFI,"Everything archaic to Severian is rendered as Latin.","comment by Ipsifendus, 8:57 AM","reader","asserts","2015-05-08",R_LIVE,"none","medium — a reader's account of Wolfe's stated constraint, not Wolfe's own words"),
 C("withheld information and inference","A MetaFilter reader attributes to Wolfe the remark that everything means something but not everything means very much.","MetaFilter user “straight” relaying Gene Wolfe, thread 149475, 8 May 2015",U_MEFI,"Everything means something, but not everything means very much.","comment by straight, 9:00 AM","relay","asserts","2015-05-08",R_LIVE,"none","medium — a forum attribution; the primary occasion is not named on the page"),
 C("other: counter-evidence, anomaly as authorial error","A MetaFilter reader reports that Wolfe, asked by letter about a contradiction in the first pages of Shadow of the Torturer, answered that it was a typo.","MetaFilter user “Ipsifendus” reporting a letter from Gene Wolfe, thread 149475, 8 May 2015, 9:25 AM",U_MEFI,"Typo.","comment by Ipsifendus, 9:25 AM","reader","disputes","2015-05-08",R_LIVE,"none","medium — a reader's account of a private letter"),

 C("opening sentence","Ian Sales says the title novella of The Fifth Head of Cerberus opens traditionally, as a childhood memory.","Ian Sales (“iansales”), SFF Chronicles thread 11050, 13 June 2006",U_5HC,"The novella opens traditionally enough—a childhood memory","post #1, essay body","analysis","asserts","2006-06-13",R_LIVE),
 C("withheld information and inference","Ian Sales says that three paragraphs after that conventional opening the reader learns the narrator's father traded in children.","Ian Sales (“iansales”), SFF Chronicles thread 11050, 13 June 2006",U_5HC,"three paragraphs later we learn that the narrator’s father traded in children","post #1, essay body","analysis","asserts","2006-06-13",R_LIVE,"dossier-archivist"),
 C("civic record register","Ian Sales says the novella 'V.R.T.' consists of excerpts from taped interviews and a field journal, framed by a military officer reading those documents to decide on an incarceration.","Ian Sales (“iansales”), SFF Chronicles thread 11050, 13 June 2006",U_5HC,"It consists of excerpts from taped interviews, the field journal","post #1, essay body","analysis","asserts","2006-06-13",R_LIVE,"dossier-archivist"),
 C("withheld information and inference","Ian Sales says the authorities read a table of bullet-drop figures found in a field guide as meaning Marsch is an assassin.","Ian Sales (“iansales”), SFF Chronicles thread 11050, 13 June 2006",U_5HC,"the authorities take this to mean Marsch is an assassin","post #1, essay body","analysis","asserts","2006-06-13",R_LIVE,"dossier-archivist"),
 C("withheld information and inference","Ian Sales says clues in the text, including a library shelf description, suggest the unnamed narrator's surname is Wolfe.","Ian Sales (“iansales”), SFF Chronicles thread 11050, 13 June 2006",U_5HC,"Clues in the text suggest his surname is Wolfe","post #1, essay body","analysis","asserts","2006-06-13",R_LIVE,"dossier-archivist"),
 C("other: incidental detail as evidence","A forum analyst says objective outside detail is, in his opinion, at the heart of getting to the bottom of things in Wolfe.","SFF Chronicles user “felicibusbrevis”, thread 11050, 24 March 2013 (an analysis written for the Urth mailing list)",U_5HC,"at the heart of getting to the bottom of things in Wolfe","post #16, opening statement of method","analysis","asserts","2013-03-24",R_LIVE,"dossier-archivist"),
 C("register modulation","The same forum analyst says the embedded aboriginal myth “A Story” is written in a mythic dream prose very different from the first part of the novel.","SFF Chronicles user “felicibusbrevis”, thread 11050, 24 March 2013",U_5HC,"mythic but confusing dream prose that channels the savage mind","post #16, section on “A Story”","analysis","asserts","2013-03-24",R_LIVE,"chronicle-line"),

 C("withheld information and inference","A reader of Peace reports taking things in at face value and failing to catch the significance of what Wolfe was alluding to.","SFF Chronicles user “Fried Egg”, thread 528814, 14 September 2010",U_PEACE,"taking things in at face value and failed to catch the significance","post #1","reader","attests","2010-09-14",R_LIVE,"dossier-archivist"),

 C("other: incidental detail as evidence","The reader who proposed the Urth list's chapter-by-chapter close reading says he does not believe in trivial trivia in Wolfe.","JWillard, Urth mailing list, 4 September 2006",U_URTH%"058531","I don't believe in trivial trivia, provided one can ask","message body, paragraph 3","reader","asserts","2006-09-04",R_WB,"dossier-archivist"),
 C("withheld information and inference","The same reader describes his reading posture as walking through Wolfe like a minefield.","JWillard, Urth mailing list, 4 September 2006",U_URTH%"058531","why I walk through Wolfe like a minefield","message body, chapter-1 observations","reader","asserts","2006-09-04",R_WB),
 C("withheld information and inference","The same reader treats the hedge word “perhaps” in Severian's narration as a signal that something is being covered.","JWillard, Urth mailing list, 4 September 2006",U_URTH%"058531","uses a perhaps, or one of its relatives, I get nervous","message body, “Suspicious sentence” item","reader","asserts","2006-09-04",R_WB,"dossier-archivist"),
 C("opening sentence","Dan'l Danehy-Oakes calls the first line of Shadow of the Torturer a haunting first line.","Dan'l Danehy-Oakes, Urth mailing list, 5 September 2006",U_URTH%"002922","A rather haunting first line, for me.","message body, note on p9","reader","asserts","2006-09-05",R_WB),
 C("withheld information and inference","Dan'l Danehy-Oakes says the first page of Shadow of the Torturer is full of forward references.","Dan'l Danehy-Oakes, Urth mailing list, 5 September 2006",U_URTH%"002922","This first page is full of forward","message body, note on p9","reader","asserts","2006-09-05",R_WB,"chronicle-line"),
 C("other: action rendered as confusion","Dan'l Danehy-Oakes says the fight in chapter I is more like a real fight than most in fiction.","Dan'l Danehy-Oakes, Urth mailing list, 5 September 2006",U_URTH%"002922","more like a real fight than most in fiction.","message body, note on the fight","reader","asserts","2006-09-05",R_WB),
 C("withheld information and inference","Dan'l Danehy-Oakes argues the explanation Severian himself offers for the coin's binding power does not hold up against a detail the narration supplies.","Dan'l Danehy-Oakes, Urth mailing list, 5 September 2006",U_URTH%"002922","Not Vodalus', to be sure; so the magickal explanation he","message body, note on pp16-17","reader","asserts","2006-09-05",R_WB,"dossier-archivist"),
 C("other: counter-evidence, anomaly as authorial error","Roy C. Lackey argues that a contradiction about who was handed the pistol, repeated in the appendix to Citadel of the Autarch, is probably Wolfe's own mistake rather than the narrator's.","Roy C. Lackey, Urth mailing list, 5 September 2006",U_URTH%"002935","so the mistake is probably Wolfe's.","message body, first paragraph","reader","disputes","2006-09-05",R_WB),
]

out=dict(complete=False,coverage="in progress — 10 sources read raw",sourcesRead=sources,claims=claims)
json.dump(out,open("found-wolfe-close.json","w"),indent=1,ensure_ascii=False)
print(len(sources),"sources",len(claims),"claims")
