import json, os, sys
OUT = "found-martin-measurement.json"

SP  = "https://medium.com/@dimitrisspathis/exploring-linguistic-patterns-in-best-selling-book-series-100290c94242"
WR  = "https://wordsrated.com/game-of-thrones-stats/"
DH  = "https://www.dothraki.com/2011/09/the-header-script/"
DC  = "https://dothraki.com/2012/03/developing-canon/"
DA  = "https://dothraki.com/about-david-j-peterson/"
HBO = "http://dothraki.conlang.org/official-hbo-press-release/"
BEC = "https://serena.sharepress.it/anglistica-aion/article/download/8606/9299/31827"
RIV = "https://authorarrivera.com/2023/09/10/a-brief-linguistic-exam-of-a-song-of-ice-and-fire/"
WON = "https://wonderlandpress.com/a-song-of-ice-and-fire-structureword-count-case-study/"
WPD = "https://en.wikipedia.org/wiki/Dothraki_language"
BLA = "https://openlibrary.org/search/inside?q=%22George+R.+R.+Martin%22+adverbs"

sources = [
 {"title":"Dimitris Spathis, 'Exploring linguistic patterns in best-selling book series'","url":SP,"kind":"measurement","substantive":True,"date":"2015-03-29","route":"live Medium blocked by Cloudflare; Wayback raw capture 20250828164038id_"},
 {"title":"WordsRated (Danny McLoughlin), 'Game of Thrones Book Stats - A Song of Ice and Fire Series'","url":WR,"kind":"measurement","substantive":True,"date":"published 2021-10-19, updated 2025-07-08","route":"live blocked by WAF (454); Wayback raw capture 20260210045808id_"},
 {"title":"Nicolangelo Becce, 'Adapting George R. R. Martin's A Game of Thrones. A Corpus Linguistics Analysis from a Gender Perspective', Anglistica AION 22.2 (2018), 83-94","url":BEC,"kind":"measurement","substantive":True,"date":"issue dated 2018; posted 2021-11-20","route":"journal landing page -> galley viewer -> PDF binary -> pypdf text extraction"},
 {"title":"A. R. Rivera, 'A Brief Linguistic Exam of A Song Of Ice And Fire'","url":RIV,"kind":"analysis","substantive":True,"date":"2023-09-10","route":"direct fetch, browser user agent"},
 {"title":"David J. Peterson, 'The Header Script', Dothraki.com","url":DH,"kind":"own-words","substantive":True,"date":"2011-09-21","route":"direct fetch, browser user agent"},
 {"title":"David J. Peterson, 'Developing Canon', Dothraki.com","url":DC,"kind":"own-words","substantive":True,"date":"2012-03-18","route":"direct fetch, browser user agent"},
 {"title":"'About David J. Peterson', Dothraki.com","url":DA,"kind":"own-words","substantive":False,"date":"c. 2015 (pre-dates 29 Sept 2015 book release)","route":"direct fetch, browser user agent"},
 {"title":"HBO, 'Official HBO Press Release' on the Dothraki language, dothraki.conlang.org","url":HBO,"kind":"vendor","substantive":True,"date":"2010-04-12","route":"dead link; Wayback raw capture 20190719045742id_"},
 {"title":"Wikipedia, 'Dothraki language' (relay to the HBO press release and to Dothraki.com)","url":WPD,"kind":"relay","substantive":True,"date":"fetched 2026-09-06","route":"action=raw wikitext"},
 {"title":"DeAnna Knippling, 'A Song of Ice and Fire: Structure/Word Count Case Study', Wonderland Press","url":WON,"kind":"analysis","substantive":True,"date":"undated post; site copyright 2025","route":"direct fetch, browser user agent"},
 {"title":"Ben Blatt, Nabokov's Favorite Word Is Mauve (2017) - full-text probe via Open Library Search Inside","url":BLA,"kind":"measurement","substantive":False,"date":"2017","route":"archive.org lending item: BookReaderSearch/inside.php/FTS all refused; Open Library Search Inside returns front-matter snippets only"},
 {"title":"A Song of Ice and Fire Wiki, 'Statistical analysis'","url":"https://iceandfire.fandom.com/wiki/A_Song_of_Ice_and_Fire/Statistical_analysis","kind":"measurement","substantive":False,"date":"n/a","route":"blocked: Cloudflare interstitial ('Just a moment...')"},
]

claims = [
 # --- Spathis: adverbs (the angle asks for -ly and adverb scarcity counted separately) ---
 {"feature":"adjective and adverb discipline","claim":"Spathis's text-mining comparison of four best-selling series reports that A Song of Ice and Fire lacks -ly adverbs relative to the other three series.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"the lack of -ly adverbs in Game of Thrones","page":"section 4) Adverbs","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw: https://web.archive.org/web/20250828164038id_/<url>","registerHint":"none","confidence":"high"},
 {"feature":"adjective and adverb discipline","claim":"Spathis's key-takeaway list states that Game of Thrones contains significantly fewer -ly adverbs than the other series analysed.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"significantly fewer -ly adverbs","page":"section 'Key takeaways'","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"adjective and adverb discipline","claim":"Spathis's adverb finding is stated only for the -ly suffixed form of the adverb, never for adverbs as a whole class.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"significantly fewer -ly adverbs","page":"sections 4) Adverbs and Key takeaways","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"medium — the limb rests on the wording of both adverb sentences naming '-ly adverbs'; the page carries no sentence about adverbs in general"},
 {"feature":"stylometry","claim":"Spathis reports no numeric adverb rate in the article's running text; the adverb comparison is carried entirely by a chart image.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"","page":"section 4) Adverbs","kind":"measurement","polarity":"mentions","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"medium — an absence claim; verified against the full text as fetched, in which the only adverb sentences are prose and the figure is an image placeholder"},
 {"feature":"stylometry","claim":"Spathis removed character names, along with very frequent words and phrases, as stopwords before ranking parts of speech.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"as well as character names","page":"section 'Technical'","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"stylometry","claim":"Spathis's corpus is 3,896,568 words drawn from nineteen books by four authors.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"3,896,568","page":"introduction","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"stylometry","claim":"Spathis's Automated Readability Index result places Game of Thrones at the comprehension level of 11-year-olds.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"Game of Thrones to 11-year-olds","page":"section 7) Understandability","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"concrete sensory noun","claim":"Spathis reports that Martin's most frequent colour adjectives across the series are red, white and grey.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"Notable is the usage of colors by author","page":"section 5) Adjectives","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"naming and forms of address","claim":"Spathis reports that lady and queen are among the most frequent nouns in the Game of Thrones books.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"is probably apparent in Game of Thrones","page":"section 2) Nouns","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"adjective and adverb discipline","claim":"Spathis offers Stephen King's advice against adverbs only as speculation about why Martin's -ly count is low, not as anything Martin said.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"Perhaps George Martin follows Stephen King","page":"section 4) Adverbs","kind":"measurement","polarity":"mentions","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"plainness and economy","claim":"Spathis reports that the largest books in his four-series analysis score low on lexical density.","source":"Dimitris Spathis, Medium, 29 March 2015","url":SP,"quote":"the largest books of our analysis behave poorly","page":"section 6) Lexical Density","kind":"measurement","polarity":"asserts","date":"2015-03-29","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},

 # --- WordsRated ---
 {"feature":"other: book and chapter length","claim":"WordsRated's length table totals 344 chapters across the five published A Song of Ice and Fire novels.","source":"WordsRated (Danny McLoughlin), 'Game of Thrones Book Stats'","url":WR,"quote":"344","page":"section 'Length of A Song of Ice and Fire books', table Total row","kind":"measurement","polarity":"asserts","date":"page updated 2025-07-08","routeHint":"Wayback raw: https://web.archive.org/web/20260210045808id_/<url>","registerHint":"none","confidence":"high"},
 {"feature":"other: book and chapter length","claim":"WordsRated's length table totals 1,736,054 words across the five published novels.","source":"WordsRated (Danny McLoughlin), 'Game of Thrones Book Stats'","url":WR,"quote":"1,736,054","page":"section 'Length of A Song of Ice and Fire books', table Total row","kind":"measurement","polarity":"asserts","date":"page updated 2025-07-08","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"other: book and chapter length","claim":"WordsRated's length table gives A Storm of Swords 414,604 words in 82 chapters.","source":"WordsRated (Danny McLoughlin), 'Game of Thrones Book Stats'","url":WR,"quote":"414,604","page":"section 'Length of A Song of Ice and Fire books'","kind":"measurement","polarity":"asserts","date":"page updated 2025-07-08","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"point of view and distance","claim":"WordsRated states that the A Song of Ice and Fire novels are written in third person limited.","source":"WordsRated (Danny McLoughlin), 'Game of Thrones Book Stats'","url":WR,"quote":"The books are written in 3rd person limited.","page":"section 'Characters, narrative device and perspective'","kind":"measurement","polarity":"asserts","date":"page updated 2025-07-08","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"point of view and distance","claim":"WordsRated counts nine point-of-view characters in the first novel.","source":"WordsRated (Danny McLoughlin), 'Game of Thrones Book Stats'","url":WR,"quote":"The first book takes place from the perspective of 9 different characters","page":"section 'Characters, narrative device and perspective'","kind":"measurement","polarity":"asserts","date":"page updated 2025-07-08","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},

 # --- Becce ---
 {"feature":"dialogue register","claim":"Becce's LIWC measurement of the dialogue in Martin's A Game of Thrones gives 11,02 words per sentence for male characters and 10,59 for female characters.","source":"Nicolangelo Becce, Anglistica AION 22.2 (2018), 83-94","url":BEC,"quote":"Words/sentence 11,02 10,59","page":"Tab. 1, p. 88","kind":"measurement","polarity":"asserts","date":"2018 issue, posted 2021-11-20","routeHint":"PDF binary via journal galley download link, text extracted with pypdf","registerHint":"none","confidence":"high"},
 {"feature":"dialogue register","claim":"Becce measures the male characters' dialogue in Martin's novel at 81890 words, 84% of all dialogue in the book.","source":"Nicolangelo Becce, Anglistica AION 22.2 (2018), 83-94","url":BEC,"quote":"81890 (84%)","page":"Tab. 1, p. 88","kind":"measurement","polarity":"asserts","date":"2018 issue, posted 2021-11-20","routeHint":"PDF binary, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"per-speaker register","claim":"Becce finds that in every one of the three versions of the story the male characters' utterances have longer sentences and longer words than the female characters'.","source":"Nicolangelo Becce, Anglistica AION 22.2 (2018), 83-94","url":BEC,"quote":"the male characters’ utterances are characterized by having longer","page":"section 3, Data analysis, p. 88","kind":"measurement","polarity":"asserts","date":"2018 issue, posted 2021-11-20","routeHint":"PDF binary, pypdf extraction","registerHint":"none","confidence":"high"},
 {"feature":"per-speaker register","claim":"Becce reports that among the eight viewpoint characters the one exception to the pattern is words per sentence in the novel, where the female viewpoint characters lead.","source":"Nicolangelo Becce, Anglistica AION 22.2 (2018), 83-94","url":BEC,"quote":"the female characters have a slight advantage","page":"discussion of Tab. 2, p. 89","kind":"measurement","polarity":"asserts","date":"2018 issue, posted 2021-11-20","routeHint":"PDF binary, pypdf extraction","registerHint":"none","confidence":"high"},

 # --- Rivera ---
 {"feature":"per-speaker register","claim":"Rivera observes that the high-born and low-born characters of the novels are given different speech, a dialect ruled by rank rather than region.","source":"A. R. Rivera, 'A Brief Linguistic Exam of A Song Of Ice And Fire', 10 September 2023","url":RIV,"quote":"high-born characters also speak differently than the characters of lower birth","page":"body, paragraph on forms of address","kind":"analysis","polarity":"asserts","date":"2023-09-10","routeHint":"direct fetch with a browser user agent","registerHint":"dossier-archivist","confidence":"high"},
 {"feature":"repetition and refrain","claim":"Rivera counts the insult against Jon Snow repeated five times within a few paragraphs of A Game of Thrones and calls it lexical cohesion.","source":"A. R. Rivera, 'A Brief Linguistic Exam of A Song Of Ice And Fire', 10 September 2023","url":RIV,"quote":"the insult is repeated five times for emphasis","page":"body, paragraph on repetition","kind":"analysis","polarity":"asserts","date":"2023-09-10","routeHint":"direct fetch with a browser user agent","registerHint":"chronicle-line","confidence":"high"},
 {"feature":"plainness and economy","claim":"Rivera reports a lexical density score of between 4 and 4.5 for A Game of Thrones, which she calls quite low.","source":"A. R. Rivera, 'A Brief Linguistic Exam of A Song Of Ice And Fire', 10 September 2023","url":RIV,"quote":"A Game of Thrones has a score between 4 and 4.5","page":"body, paragraph on lexical density","kind":"measurement","polarity":"asserts","date":"2023-09-10","routeHint":"direct fetch with a browser user agent","registerHint":"none","confidence":"medium — Rivera gives no unit or source for the 4 to 4.5 figure, which is not the percentage formula Spathis uses"},
 {"feature":"archaism","claim":"Rivera argues Martin's archaic diction works because each old term sits in a context that lets the reader decipher its older meaning without disruption.","source":"A. R. Rivera, 'A Brief Linguistic Exam of A Song Of Ice And Fire', 10 September 2023","url":RIV,"quote":"archaic diction, but synonymy and antonymy, semantic shifts","page":"opening paragraph and the paragraph on 'elsewise' and 'without'","kind":"analysis","polarity":"asserts","date":"2023-09-10","routeHint":"direct fetch with a browser user agent","registerHint":"dossier-archivist","confidence":"medium — the quotation is from the thesis sentence; the 'decipher without disruption' limb is stated a paragraph later in the same page"},

 # --- Peterson / coinage ---
 {"feature":"compounds and coinages","claim":"Peterson states that as of 21 September 2011 the Dothraki he built had reached 3,163 words.","source":"David J. Peterson, 'The Header Script', Dothraki.com, 21 September 2011","url":DH,"quote":"Dothraki is now up to 3,163 words","page":"body of the post","kind":"own-words","polarity":"asserts","date":"2011-09-21","routeHint":"direct fetch with a browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"compounds and coinages","claim":"Peterson treats the spellings of the Dothraki words printed in Martin's books as canon that his own language had to accommodate.","source":"David J. Peterson, 'Developing Canon', Dothraki.com, 18 March 2012","url":DC,"quote":"The spellings in the books are canon.","page":"list of principles, body of the post","kind":"own-words","polarity":"asserts","date":"2012-03-18","routeHint":"direct fetch with a browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"compounds and coinages","claim":"Peterson reports that in Martin's Dothraki material the letters p and b occur only in the two names Pono and Bharbo.","source":"David J. Peterson, 'Developing Canon', Dothraki.com, 18 March 2012","url":DC,"quote":"In the names Pono and Bharbo","page":"body of the post","kind":"own-words","polarity":"asserts","date":"2012-03-18","routeHint":"direct fetch with a browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"compounds and coinages","claim":"Peterson describes the Dothraki in Martin's books as a body of material that already existed before he began work on the language.","source":"David J. Peterson, 'Developing Canon', Dothraki.com, 18 March 2012","url":DC,"quote":"the Dothraki that existed in the books before I took","page":"opening of the post","kind":"own-words","polarity":"asserts","date":"2012-03-18","routeHint":"direct fetch with a browser user agent","registerHint":"none","confidence":"high"},
 {"feature":"compounds and coinages","claim":"HBO's 2010 press release credits the Dothraki language with a vocabulary of more than 1,800 words at the time of the announcement.","source":"HBO official press release, dothraki.conlang.org, 12 April 2010","url":HBO,"quote":"extensive vocabulary of more than 1,800 words","page":"press release body","kind":"vendor","polarity":"asserts","date":"2010-04-12","routeHint":"dead link; Wayback raw: https://web.archive.org/web/20190719045742id_/<url>","registerHint":"none","confidence":"high"},
 {"feature":"compounds and coinages","claim":"HBO's press release says Peterson drew on Martin's description of the language rather than on a vocabulary Martin had supplied.","source":"HBO official press release, dothraki.conlang.org, 12 April 2010","url":HBO,"quote":"drew inspiration from George R.R. Martin’s description of the language","page":"press release body","kind":"vendor","polarity":"asserts","date":"2010-04-12","routeHint":"Wayback raw capture","registerHint":"none","confidence":"high"},
 {"feature":"compounds and coinages","claim":"Wikipedia, relaying the HBO press release, states Peterson delivered over 1700 words to HBO before the initial shooting, a figure the press release itself puts at more than 1,800.","source":"Wikipedia 'Dothraki language' relaying the HBO press release of 12 April 2010","url":WPD,"quote":"He delivered over 1700 words to HBO before the initial shooting.","page":"section 'Development'","kind":"relay","polarity":"asserts","date":"fetched 2026-09-06","routeHint":"en.wikipedia.org action=raw, then the cited primary via Wayback","registerHint":"none","confidence":"high"},

 # --- Wonderland ---
 {"feature":"other: chapter architecture","claim":"Knippling argues Martin's main point-of-view character in each book holds an undistinguished share of chapters in the first half and dominates the second.","source":"DeAnna Knippling, Wonderland Press, 'A Song of Ice and Fire: Structure/Word Count Case Study'","url":WON,"quote":"comes to dominate the number of chapters in the latter half","page":"body of the post","kind":"analysis","polarity":"asserts","date":"undated; site copyright 2025","routeHint":"direct fetch with a browser user agent","registerHint":"none","confidence":"medium — the author calls her own reading tentative on the page"},
]

data = {"complete": False,
        "coverage": "in progress",
        "sourcesRead": sources,
        "claims": claims}
json.dump(data, open(OUT,'w'), indent=1, ensure_ascii=False)
print("wrote", OUT, len(claims), "claims", len(sources), "sources")
