import json
HIST="https://proceedings.neurips.cc/paper_files/paper/2024/file/38cc5cba8e513547b96bc326e25610dc-Paper-Datasets_and_Benchmarks_Track.pdf"
ASIC="https://www.aph.gov.au/DocumentStore.ashx?id=b4fd6043-6626-4cbe-b8ee-a5c7319e94a0"
CSH="https://csh.ac.at/news/can-chatgpt-pass-a-phd-level-history-test/"
TC="https://techcrunch.com/2025/01/19/ai-isnt-very-good-at-history-new-paper-finds/"
ACS="https://ia.acs.org.au/article/2024/humans-outperform-ai-in-australian-govt-trial.html"

S_HIST="Hauser, Kondor, Reddish, Benam, Cioni, Villa, Bennett, Hoyer, Francois, Turchin & del Rio-Chanona, 'HiST-LLM', NeurIPS 2024 Datasets and Benchmarks Track (Dec 2024)"
S_ASIC="ASIC answer to Question on Notice No. 001, Senate Select Committee on Adopting Artificial Intelligence, attaching AWS Professional Services draft report 'ASIC Gen AI Document Summarisation PoC' (21 May 2024)"
S_CSH="Complexity Science Hub press release, quoting Peter Turchin and R. Maria del Rio-Chanona (21 January 2025)"
S_TC="Kyle Wiggers, TechCrunch, reporting and quoting co-author Maria del Rio-Chanona (19 January 2025)"
S_ACS="Information Age (Australian Computer Society), reporter's account of the ASIC trial (September 2024)"

R_PDF="PDF binary fetched with browser user agent, text extracted with pypdf"
R_CURL="live URL with browser user agent, HTML stripped to text"

claims=[
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="On the HiST-LLM four-choice benchmark of graduate-level global history, GPT-4-Turbo scored a balanced accuracy of 46.0 percent, the best of the seven models tested.",
  source=S_HIST, url=HIST, quote="GPT-4-turbo 46.0", page="Table 1, p.7", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="GPT-4-turbo, observed 2024 (published Dec 2024); register measured: structured expert historical fact, archival/encyclopedic"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="The weakest model tested on HiST-LLM, Llama-3.1-8B, scored a four-choice balanced accuracy of 33.6 percent.",
  source=S_HIST, url=HIST, quote="Llama-3.1-8B (FP8) 33.6", page="Table 1, p.7", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama-3.1-8B (FP8), observed 2024; register measured: structured expert historical fact, archival/encyclopedic"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="The authors state that the benchmarked models beat the 25 percent random-guessing baseline but do not reach expert comprehension.",
  source=S_HIST, url=HIST, quote="random guessing (25%) but falling short of expert comprehension", page="Abstract", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Gemini-1.5-flash, GPT-3.5-turbo, GPT-4-turbo, GPT-4o, Llama-3/3.1 family, observed 2024; register measured: expert historical fact"),
 dict(feature="model era drift",
  claim="The paper reports that model accuracy on historical facts falls as the period tested approaches the present day.",
  source=S_HIST, url=HIST, quote="declines as the time frame approaches the present day", page="Section 5, p.8", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="GPT-4-turbo and Llama-3-70B most affected, observed 2024; register measured: expert historical fact by period"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="GPT-4-Turbo's balanced accuracy fell from 55.3 percent for the period 8,000 BCE to 6,000 BCE to 38.7 percent for the period 1,500 CE to 2,000 CE.",
  source=S_HIST, url=HIST, quote="", page="Table 2 and following text, p.8", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="GPT-4-turbo, observed 2024; register measured: expert historical fact binned by period"),
 dict(feature="homogenisation",
  claim="Across the four headline models the benchmark's worst regional performance falls on Oceania or Sub-Saharan Africa, which the authors read as a training-data bias.",
  source=S_HIST, url=HIST, quote="Worst performance Oceania Oceania Oceania Sub-Sah. Africa", page="Table 3, p.8", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Gemini-1.5-flash, GPT-4-turbo, GPT-4o, Llama-3.1-70B, observed 2024; register measured: expert historical fact by region"),
 dict(feature="other: evidenced versus inferred fact",
  claim="The benchmark's questions explicitly test whether a model can tell a fact recorded as evidenced from one recorded as inferred, because every Seshat variable carries that marking.",
  source=S_HIST, url=HIST, quote="are recorded as \"evidenced\" or \"inferred\"", page="Section 3, p.2", kind="measurement", polarity="applies",
  date="2024-12", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="seven models of the Gemini, OpenAI and Llama families, observed 2024; register measured: expert historical fact"),
 dict(feature="counter-evidence",
  claim="The authors caution that their first benchmark result should be read as a lower bound on model historical-knowledge performance.",
  source=S_HIST, url=HIST, quote="this first benchmark should be taken as a lower bound", page="Section 6 Discussion, p.10", kind="measurement", polarity="asserts",
  date="2024-12", routeHint=R_PDF, registerHint="none", confidence="high",
  modelEra="seven models benchmarked 2024; register measured: expert historical fact"),
 dict(feature="steerability",
  claim="Del Rio-Chanona attributes the models' weakness to their extrapolating from prominent historical data rather than retrieving obscure knowledge.",
  source=S_TC, url=TC, quote="LLMs tend to extrapolate from historical data that is very prominent", page="body, paragraph beginning 'Why are LLMs bad'", kind="analysis", polarity="asserts",
  date="2025-01-19", routeHint=R_CURL, registerHint="dossier-archivist", confidence="high",
  modelEra="GPT-4 Turbo, Llama and Gemini as benchmarked in 2024; reported January 2025; register measured: expert historical fact"),
 dict(feature="steerability",
  claim="Del Rio-Chanona illustrates the mechanism as a model recalling frequently seen items and extrapolating when asked about a rarely seen one.",
  source=S_TC, url=TC, quote="get told A and B 100 times, and C 1 time", page="body, quoted illustration", kind="analysis", polarity="asserts",
  date="2025-01-19", routeHint=R_CURL, registerHint="dossier-archivist", confidence="high",
  modelEra="GPT-4 Turbo, Llama and Gemini benchmarked 2024, quoted January 2025; register measured: expert historical fact"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="TechCrunch reports the best-performing model achieved about 46 percent accuracy on the history benchmark.",
  source=S_TC, url=TC, quote="only achieved about 46% accuracy", page="body, third paragraph", kind="reception", polarity="asserts",
  date="2025-01-19", routeHint=R_CURL, registerHint="none", confidence="high",
  modelEra="GPT-4 Turbo, benchmarked 2024, reported January 2025; register measured: expert historical fact"),
 dict(feature="reader and expert judgment",
  claim="Del Rio-Chanona says the models are good for basic facts but not for nuanced PhD-level historical inquiry.",
  source=S_TC, url=TC, quote="They're great for basic facts", page="body, quoted co-author", kind="analysis", polarity="asserts",
  date="2025-01-19", routeHint=R_CURL, registerHint="dossier-archivist", confidence="high",
  modelEra="GPT-4 Turbo, Llama, Gemini benchmarked 2024, quoted January 2025; register measured: expert historical fact"),
 dict(feature="reader and expert judgment",
  claim="Turchin says the benchmark shows machine intelligence is domain-specific, strong in some contexts and very poor in others compared with humans.",
  source=S_CSH, url=CSH, quote="artificial 'intelligence' is quite domain-specific", page="pull quote", kind="analysis", polarity="asserts",
  date="2025-01-21", routeHint=R_CURL, registerHint="none", confidence="high",
  modelEra="ChatGPT-4, Llama and Gemini as benchmarked 2024; statement January 2025; register measured: expert historical fact"),
 dict(feature="other: evidenced versus inferred fact",
  claim="Del Rio-Chanona says history is often viewed as facts but that interpretation is sometimes needed to make sense of it.",
  source=S_CSH, url=CSH, quote="History is often viewed as facts, but sometimes interpretation is necessary", page="body", kind="analysis", polarity="asserts",
  date="2025-01-21", routeHint=R_CURL, registerHint="dossier-archivist", confidence="high",
  modelEra="commentary on the 2024 benchmark of ChatGPT-4, Llama, Gemini; January 2025; register measured: expert historical fact"),
 dict(feature="reader and expert judgment",
  claim="Del Rio-Chanona says she expected the chatbots to perform considerably better than the benchmark showed.",
  source=S_CSH, url=CSH, quote="I thought the AI chatbots would do a lot better", page="body", kind="analysis", polarity="asserts",
  date="2025-01-21", routeHint=R_CURL, registerHint="none", confidence="high",
  modelEra="ChatGPT-4, Llama, Gemini benchmarked 2024; statement January 2025; register measured: expert historical fact"),

 dict(feature="other: measured accuracy on archival summarisation",
  claim="In ASIC's proof of concept the aggregated human summaries scored 61 of 75 and the aggregated generative AI summaries scored 35 of 75.",
  source=S_ASIC, url=ASIC, quote="human summaries scored 61 (81%) and the Gen AI summaries scored 35 (47%)", page="Section 6 Discussion of the AWS report", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial run 15 January to 16 February 2024; register measured: archival summarisation of public inquiry submissions"),
 dict(feature="other: measured accuracy on archival summarisation",
  claim="ASIC reports the AI summaries scored lower than the human summaries on every assessment criterion.",
  source=S_ASIC, url=ASIC, quote="AI summaries performed lower on all criteria", page="Answers, p.2", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="uniform rhythm (low burstiness)",
  claim="On the coherency and consistency criterion the AI summaries scored 10 against the human summaries' 12, the narrowest margin of the five criteria.",
  source=S_ASIC, url=ASIC, quote="Coherency/Consistency 10 12", page="Table 4, ASIC Scoring Summary by Assessment Criteria", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, January-February 2024; register measured: archival summarisation"),
 dict(feature="abstraction over the concrete",
  claim="ASIC chair Joe Longo told the Senate committee the AI summary of the submissions was bland rather than misleading.",
  source="Joe Longo, ASIC Chair, Hansard extract of 21 May 2024 reproduced in ASIC's answer to Question on Notice No. 001", url=ASIC, quote="It wasn't misleading but it was bland.", page="Questions, Hansard extract, p.1", kind="own-words", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024, testimony May 2024; register measured: archival summarisation"),
 dict(feature="abstraction over the concrete",
  claim="ASIC's Greg Jefferson told the committee the AI-generated summaries were quite generic.",
  source="Greg Jefferson, ASIC, Hansard extract of 21 May 2024 reproduced in ASIC's answer to Question on Notice No. 001", url=ASIC, quote="the summaries were quite generic", page="Questions, Hansard extract, p.1", kind="own-words", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024, testimony May 2024; register measured: archival summarisation"),
 dict(feature="discourse-level tells",
  claim="An ASIC assessor recorded that the model made strange choices about what to highlight in a summary.",
  source="Unnamed ASIC assessor, rubric comment quoted in the AWS draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="Made strange choices about what to highlight.", page="Section 5.1 Key Themes, p.17", kind="reader", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="no subtext",
  claim="An ASIC assessor recorded that the model missed nuance, context and reading between the lines.",
  source="Unnamed ASIC assessor, rubric comment quoted in Appendix C of the AWS draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="missed nuance, context and reading between the lines", page="Appendix C, qualitative analysis", kind="reader", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="no subtext",
  claim="The AWS report attributes a class of summary failures to the model's limited ability to handle content needing deep understanding of context, subtle nuance or implicit meaning.",
  source="AWS Professional Services draft report 'ASIC Gen AI Document Summarisation PoC', attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="a deep understanding of context, subtle nuances, or implicit meaning", page="Section 6 Discussion, p.18", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="gloss and over-explaining",
  claim="An ASIC assessor described one AI summary's handling of references as wordy and pointless.",
  source="Unnamed ASIC assessor, rubric comment quoted in the AWS draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="wordy and pointless", page="Section 5.1 Key Themes, p.17", kind="reader", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="gloss and over-explaining",
  claim="The AWS report lists waffliness and wordiness among the recurring themes assessors recorded about the AI summaries.",
  source="AWS Professional Services draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="AI summaries were waffly, wordy", page="Section 5.1 Key Themes, p.18", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="other: fabricated content in an archival summary",
  claim="An ASIC assessor recorded that the model included analysis that did not come from the source document.",
  source="Unnamed ASIC assessor, rubric comment quoted in the AWS draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="Included analysis which did not come from the document", page="Section 5.1 Key Themes, p.17", kind="reader", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="other: fabricated content in an archival summary",
  claim="The AWS report defines the hallucination risk it observed as text that was grammatically correct but on occasion factually inaccurate.",
  source="AWS Professional Services draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="grammatically correct, but on occasion factually inaccurate", page="Section 6.1 Limitations of the PoC, p.19", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="other: output instability under repetition",
  claim="The AWS report records that testing was hampered because asking the model the same question twice might not yield the same answer.",
  source="AWS Professional Services draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="Asking the same question twice may not yield the same answer.", page="Section 6.1 Limitations of the PoC, p.19", kind="measurement", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="none", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="discourse-level tells",
  claim="An ASIC assessor described an AI summary as dense and repetitive.",
  source="Unnamed ASIC assessor, rubric comment quoted in Appendix C of the AWS draft report attached to ASIC's answer to Question on Notice No. 001", url=ASIC, quote="dense and repetitive", page="Appendix C, qualitative analysis", kind="reader", polarity="asserts",
  date="2024-05-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024; register measured: archival summarisation"),
 dict(feature="reader and expert judgment",
  claim="Information Age reports that ASIC assessors found the AI output made strange choices about what to highlight.",
  source=S_ACS, url=ACS, quote="made strange choices about what to highlight", page="body", kind="reception", polarity="asserts",
  date="2024-09", routeHint=R_CURL, registerHint="dossier-archivist", confidence="high",
  modelEra="Llama2-70B, trial January-February 2024, reported September 2024; register measured: archival summarisation"),
]
sources=[
 dict(title="Large Language Models' Expert-level Global History Knowledge Benchmark (HiST-LLM)", url=HIST, kind="measurement", substantive=True, date="2024-12", route="PDF binary + pypdf extraction"),
 dict(title="ASIC answer to Question on Notice No. 001, Senate Select Committee on Adopting AI, with AWS draft report attached", url=ASIC, kind="measurement", substantive=True, date="2024-05-21", route="aph.gov.au DocumentStore PDF, browser user agent, pypdf extraction"),
 dict(title="Can ChatGPT pass a PhD-level history test? (Complexity Science Hub)", url=CSH, kind="analysis", substantive=True, date="2025-01-21", route="live URL, browser user agent (WebFetch returned a summary, so raw HTML was curled)"),
 dict(title="AI isn't very good at history, new paper finds (TechCrunch)", url=TC, kind="reception", substantive=True, date="2025-01-19", route="live URL, browser user agent"),
 dict(title="Humans outperform AI in Australian government trial (Information Age, ACS)", url=ACS, kind="reception", substantive=True, date="2024-09", route="live URL, browser user agent"),
]
out=dict(complete=False, coverage="in progress: named roster fetched (HiST-LLM primary, ASIC Senate QoN primary, Jan 2025 reporting x2); ABC article not found; expansion under way", sourcesRead=sources, claims=claims)
json.dump(out, open('found-ai-arch-historical-fact-measured.json','w'), indent=1)
print("claims",len(claims),"sources",len(sources))
