import json,subprocess
subprocess.run(['python3','mkfound_hist.py'],check=True)
d=json.load(open('found-ai-arch-historical-fact-measured.json'))
EBU="https://www.ebu.ch/Report/MIS-BBC/NI_AI_2025.pdf"
BBC="https://www.bbc.co.uk/aboutthebbc/documents/bbc-research-into-ai-assistants.pdf"
LEG="https://arxiv.org/pdf/2401.01301"
SQA="https://arxiv.org/pdf/2411.04368"
S_EBU="BBC and European Broadcasting Union, 'News Integrity in AI Assistants', October 2025"
S_BBC="BBC, 'Representation of BBC News content in AI Assistants', February 2025"
S_LEG="Matthew Dahl, Varun Magesh, Mirac Suzgun and Daniel E. Ho, 'Large Legal Fictions: Profiling Legal Hallucinations in Large Language Models', Journal of Legal Analysis (arXiv v2, 21 June 2024)"
S_SQA="Jason Wei, Nguyen Karina, Hyung Won Chung, Yunxin Joy Jiao, Spencer Papay, Amelia Glaese, John Schulman and William Fedus (OpenAI), 'Measuring short-form factuality in large language models' (SimpleQA), arXiv, 7 November 2024"
R_PDF="PDF binary fetched with browser user agent, text extracted with pypdf"
new=[
 dict(feature="other: measured accuracy on archival summarisation",
  claim="BBC journalists judged 51 percent of the AI assistants' answers to news questions to have significant issues of some form.",
  source=S_BBC, url=BBC, quote="51% of all AI answers to questions about the news", page="Executive summary, p.2", kind="measurement", polarity="asserts",
  date="2025-02", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT (GPT-4o Enterprise), Copilot Pro, Gemini Standard, Perplexity Pro; responses collected 5-6 December 2024; register measured: news"),
 dict(feature="other: fabricated content in an archival summary",
  claim="Of the AI answers that cited BBC content, 19 percent introduced factual errors such as incorrect statements, numbers and dates.",
  source=S_BBC, url=BBC, quote="19% of AI answers which cited BBC content introduced factual errors", page="Executive summary, p.2", kind="measurement", polarity="asserts",
  date="2025-02", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT (GPT-4o), Copilot, Gemini, Perplexity; December 2024; register measured: news"),
 dict(feature="other: fabricated content in an archival summary",
  claim="Thirteen percent of the quotations the assistants sourced from BBC articles were altered from the original or absent from the article cited.",
  source=S_BBC, url=BBC, quote="13% of the quotes sourced from BBC articles were either altered", page="Executive summary, p.2", kind="measurement", polarity="asserts",
  date="2025-02", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT (GPT-4o), Copilot, Gemini, Perplexity; December 2024; register measured: news"),
 dict(feature="detection and its failures",
  claim="Ninety-one percent of the AI responses in the BBC study were flagged as containing at least some issues.",
  source=S_BBC, url=BBC, quote="91% of responses contained at least 'some issues'", page="High level findings, p.4", kind="measurement", polarity="asserts",
  date="2025-02", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT (GPT-4o), Copilot, Gemini, Perplexity; December 2024; register measured: news"),
 dict(feature="reader and expert judgment",
  claim="The BBC study's ratings were made by 45 journalists reviewing 362 AI responses in their own areas of expertise.",
  source=S_BBC, url=BBC, quote="45 journalists reviewed 362 AI responses", page="Appendix, Journalist reviews, p.14", kind="measurement", polarity="applies",
  date="2025-02", routeHint=R_PDF, registerHint="none", confidence="high",
  modelEra="ChatGPT (GPT-4o), Copilot, Gemini, Perplexity; responses collected 5-6 December 2024; register measured: news"),
 dict(feature="other: measured accuracy on archival summarisation",
  claim="In the BBC-EBU multi-market study 45 percent of AI responses contained at least one significant issue of any type.",
  source=S_EBU, url=EBU, quote="45% of responses contained at least one significant issue", page="Foreword, p.3", kind="measurement", polarity="asserts",
  date="2025-10", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="free/consumer ChatGPT (default GPT-4o), Copilot, Perplexity, Gemini; responses generated late May and early June 2025; register measured: news"),
 dict(feature="other: sourcing and attribution failure",
  claim="Sourcing was the single biggest cause of significant issues in the BBC-EBU study, affecting 31 percent of all responses.",
  source=S_EBU, url=EBU, quote="Sourcing is the single biggest cause of significant issues (31%)", page="Foreword, p.3", kind="measurement", polarity="asserts",
  date="2025-10", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="free/consumer ChatGPT, Copilot, Perplexity, Gemini; May-June 2025; register measured: news"),
 dict(feature="model era drift",
  claim="On a like-for-like BBC-to-BBC comparison the share of responses with significant issues of any type fell from 51 percent to 37 percent between the two rounds.",
  source=S_EBU, url=EBU, quote="improved from 51% to 37%", page="Foreword, p.3", kind="measurement", polarity="asserts",
  date="2025-10", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="December 2024 round (ChatGPT Enterprise GPT-4o, Copilot Pro, Gemini, Perplexity Pro) versus May-June 2025 round (free/consumer versions); register measured: news"),
 dict(feature="counter-evidence",
  claim="The BBC-EBU authors conclude that AI assistants remain an unreliable way to access and consume news despite measured improvement.",
  source=S_EBU, url=EBU, quote="still not a reliable way to access and consume news", page="Foreword, p.3", kind="measurement", polarity="asserts",
  date="2025-10", routeHint=R_PDF, registerHint="none", confidence="high",
  modelEra="free/consumer ChatGPT, Copilot, Perplexity, Gemini; May-June 2025; register measured: news"),
 dict(feature="other: measured accuracy on archival summarisation",
  claim="Accuracy accounted for 20 percent and insufficient context for 14 percent of significant issues in the BBC-EBU study.",
  source=S_EBU, url=EBU, quote="Accuracy (20%) and providing sufficient context (14%)", page="High-level findings, p.10", kind="measurement", polarity="asserts",
  date="2025-10", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="free/consumer ChatGPT, Copilot, Perplexity, Gemini; May-June 2025; register measured: news"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="Asked direct verifiable questions about randomly selected federal court cases, the models hallucinated between 58 percent and 88 percent of the time.",
  source=S_LEG, url=LEG, quote="LLMs hallucinate between 58% (ChatGPT 4) and 88% (Llama 2)", page="Section 1 Introduction, p.6", kind="measurement", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record"),
 dict(feature="model era drift",
  claim="Hallucination rates on Supreme Court cases were highest for the oldest and the newest cases, a non-linear relationship with case age.",
  source=S_LEG, url=LEG, quote="are most common among the Supreme Court's oldest and newest cases", page="Section 5.1.5, p.27", kind="measurement", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record by case year"),
 dict(feature="model era drift",
  claim="Hallucinations were least common among the Supreme Court's post-war Warren Court cases of 1953 to 1969.",
  source=S_LEG, url=LEG, quote="among its post-war Warren Court cases (1953-1969)", page="Section 5.1.5, p.27", kind="measurement", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record by case year"),
 dict(feature="counter-evidence",
  claim="Dahl and colleagues report that the models performed better on cases that are newer and more salient, the opposite temporal direction to the HiST-LLM history result.",
  source=S_LEG, url=LEG, quote="LLMs perform better on cases that are newer, more salient", page="Section 1 Introduction, p.6", kind="measurement", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="chronicle-line", confidence="medium",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record. Medium: the comparison to HiST-LLM is the finder's juxtaposition of two separately measured corpora, not a claim either paper makes"),
 dict(feature="other: uncritical acceptance of a false premise",
  claim="The authors report that the models often uncritically accept a user's incorrect legal assumptions.",
  source=S_LEG, url=LEG, quote="often uncritically accept users' incorrect legal assumptions", page="Abstract", kind="measurement", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record"),
 dict(feature="detection and its failures",
  claim="The authors report that the models struggle to gauge their own level of certainty without post-hoc recalibration.",
  source=S_LEG, url=LEG, quote="struggle to accurately gauge their own level of certainty", page="Section 1 Introduction, p.6", kind="measurement", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="none", confidence="high",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record"),
 dict(feature="steerability",
  claim="The authors warn that a model's peak performance may lag several years behind the current state of legal doctrine.",
  source=S_LEG, url=LEG, quote="LLMs' peak performance may lag several years behind the current state", page="Section 5.1.5, p.27", kind="analysis", polarity="asserts",
  date="2024-06-21", routeHint=R_PDF, registerHint="chronicle-line", confidence="high",
  modelEra="ChatGPT 4, ChatGPT 3.5, PaLM 2, Llama 2; observed 2023-2024; register measured: archival legal record"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="On OpenAI's SimpleQA benchmark of short fact-seeking questions GPT-4o answered 38.2 percent correctly.",
  source=S_SQA, url=SQA, quote="GPT-4o 38.2", page="Table 3, p.6", kind="measurement", polarity="asserts",
  date="2024-11-07", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="GPT-4o, observed 2024; register measured: short-form encyclopedic fact"),
 dict(feature="other: measured factual accuracy on dated historical facts",
  claim="OpenAI o1-preview answered 42.7 percent of SimpleQA questions correctly, the highest of the models reported.",
  source=S_SQA, url=SQA, quote="OpenAI o1-preview 42.7", page="Table 3, p.6", kind="measurement", polarity="asserts",
  date="2024-11-07", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="OpenAI o1-preview, observed 2024; register measured: short-form encyclopedic fact"),
 dict(feature="detection and its failures",
  claim="The SimpleQA authors report that models consistently overstate their stated confidence relative to their measured accuracy.",
  source=S_SQA, url=SQA, quote="models consistently overstate their confidence", page="Section 4 Measuring calibration, p.6", kind="measurement", polarity="asserts",
  date="2024-11-07", routeHint=R_PDF, registerHint="none", confidence="high",
  modelEra="GPT-4o, GPT-4o-mini, o1-preview, o1-mini, observed 2024; register measured: short-form encyclopedic fact"),
 dict(feature="register measured",
  claim="History is one of SimpleQA's tagged topics, with 173 of the benchmark's 4,326 questions.",
  source=S_SQA, url=SQA, quote="History (n=173)", page="Figure 1, p.4", kind="measurement", polarity="applies",
  date="2024-11-07", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="benchmark constructed adversarially against GPT-4o, 2024; register measured: short-form encyclopedic fact including history"),
 dict(feature="other: evidenced versus inferred fact",
  claim="SimpleQA questions were built so that each has only a single indisputable answer, excluding facts on which sources disagree.",
  source=S_SQA, url=SQA, quote="there exists only a single, indisputable answer", page="Abstract", kind="measurement", polarity="applies",
  date="2024-11-07", routeHint=R_PDF, registerHint="dossier-archivist", confidence="high",
  modelEra="benchmark design, 2024; register measured: short-form encyclopedic fact"),
]
d['claims']+=new
d['sourcesRead']+=[
 dict(title="Representation of BBC News content in AI Assistants (BBC)", url=BBC, kind="measurement", substantive=True, date="2025-02", route="PDF binary, browser user agent, pypdf"),
 dict(title="News Integrity in AI Assistants (BBC / European Broadcasting Union)", url=EBU, kind="measurement", substantive=True, date="2025-10", route="PDF binary, browser user agent, pypdf"),
 dict(title="Large Legal Fictions: Profiling Legal Hallucinations in Large Language Models", url=LEG, kind="measurement", substantive=True, date="2024-06-21", route="arXiv PDF binary, pypdf"),
 dict(title="Measuring short-form factuality in large language models (SimpleQA)", url=SQA, kind="measurement", substantive=True, date="2024-11-07", route="arXiv PDF binary, pypdf"),
]
d['coverage']="in progress: named roster fetched except the ABC article (not found); four archival/encyclopedic-register measurements added by lateral search"
json.dump(d, open('found-ai-arch-historical-fact-measured.json','w'), indent=1)
print("claims",len(d['claims']),"sources",len(d['sourcesRead']))
