import json
V="https://www.theverge.com/24065145/ai-obituary-spam-generative-clickbait"
WM="https://www.wired.com/story/morbid-war-online-obituaries/"
WY="https://www.wired.com/story/youtube-obituary-pirates/"
LG="https://www.legalgenealogist.com/2026/05/12/ai-meets-tos/"
WTS="https://www.wikitree.com/g2g/1665597/should-wikitree-have-a-style-guide-for-ai-generated-content"
WTP="https://www.wikitree.com/g2g/2021670/should-become-official-wikitree-policy-generated-enhanced"
VA="https://vitabrevis.americanancestors.org/-ai-in-genealogical-research"
AJC="https://www.amyjohnsoncrow.com/using-chatgpt-for-genealogy-accurately/"
FL="https://familylocket.com/can-chatgpt-help-with-genealogy-citations/"
WPS="https://en.wikipedia.org/wiki/Wikipedia:Signs_of_AI_writing"
FSB="https://www.familysearch.org/en/blog/ai-developments-genealogy"
UA="curl with a desktop browser user agent on the live URL"
GB="curl with a Googlebot user agent (the site blocks a normal browser agent with an HTTP 202 challenge)"
SATO="Mia Sato, 'The unsettling scourge of obituary spam', The Verge, 12 Feb 2024"
prev=json.load(open("found-ai-arch-biographical-record.json"))
claims=prev["claims"]; sources=prev["sourcesRead"]
add=[
 # --- WikiTree G2G style-guide thread, Nov 2023 ---
 dict(feature="other: fabricated fact in the record", claim="Brad Foley, opening WikiTree's style-guide question, states that Bing and ChatGPT easily generate attractive genealogical biographies full of false facts.", source="Brad Foley, quoted in Mags Gaulden's question 'Should WikiTree have a style guide for AI generated content?', WikiTree G2G, 22 Nov 2023", url=WTS, quote="easily generate lovely bios with lots of false", page="question body", kind="reader", polarity="asserts", date="2023-11-22", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="Bing Chat and ChatGPT as of Nov 2023; register measured: genealogical biography (WikiTree profile)"),
 dict(feature="other: hedged non-statement", claim="Brad Foley asks what counts as adequate sourcing for a thirty-line generated biography carrying forty-five separate statements behind a single footnote.", source="Brad Foley, quoted in Mags Gaulden's WikiTree G2G question, 22 Nov 2023", url=WTS, quote="a single footnote meets current standards, but is clearly not enough", page="question body", kind="reader", polarity="asserts", date="2023-11-22", routeHint=GB, registerHint="dossier-archivist", confidence="medium", modelEra="Bing Chat and ChatGPT as of Nov 2023; register measured: genealogical biography. Confidence medium: quotation to be re-checked against the page's exact casing", modelEraNote=""),
 dict(feature="other: eulogy register in the record", claim="M Ross writes a parody line of generated biography prose in which the subject is a loving mother who always looked after her children.", source="M Ross, answer on WikiTree G2G, 23 Nov 2023", url=WTS, quote="was a loving mother, she always looked after her children", page="answer, +18 votes", kind="reader", polarity="asserts", date="2023-11-23", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class tools as of Nov 2023; register measured: genealogical biography, compared by the writer against the obituary register"),
 dict(feature="other: eulogy register in the record", claim="M Ross judges that generated biographical content reads like obituary filler written by somebody who knew nothing about the dead person.", source="M Ross, answer on WikiTree G2G, 23 Nov 2023", url=WTS, quote="by someone who knew little if anything about the deceased", page="answer, +18 votes", kind="reader", polarity="asserts", date="2023-11-23", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class tools as of Nov 2023; register measured: genealogical biography against the obituary register"),
 dict(feature="abstraction over the concrete", claim="Stephanie Ward characterises AI-generated WikiTree biographies as pretty words carrying no content.", source="Stephanie Ward, answer on WikiTree G2G, 23 Nov 2023", url=WTS, quote="pretty words for a lot of nothing", page="answer, +21 votes", kind="reader", polarity="asserts", date="2023-11-23", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT / Bing as of Nov 2023; register measured: genealogical biography"),
 dict(feature="steerability", claim="M Cole reports that ChatGPT keeps adding lofty summary statements about a subject's achievements whatever prompt is used to forbid opinion.", source="M Cole, answer on WikiTree G2G, 23 Nov 2023", url=WTS, quote="adding lofty summary statements about people's achievements no matter what", page="answer, +19 votes", kind="reader", polarity="asserts", date="2023-11-23", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT as of Nov 2023; register measured: genealogical biography merged from existing sourced text"),
 dict(feature="other: circular sourcing", claim="Chase Ashley reports that ChatGPT 4, asked for a cited profile of Aquila Chase, summarised the existing WikiTree profile and cited that profile for every statement.", source="Chase Ashley, comment on WikiTree G2G, 26 Nov 2023", url=WTS, quote="summarized it, and cited the WikiTree profile for each statement", page="comment thread under the +19 answer", kind="reader", polarity="asserts", date="2023-11-26", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT 4 with live web search, Nov 2023; register measured: genealogical biography with citations"),
 dict(feature="other: fabricated fact in the record", claim="M Cole reports that a ChatGPT profile of Thomas Dudley cited real reference works but asserted facts absent from them, such as his arriving on the Mayflower in 1630.", source="M Cole, comment on WikiTree G2G, 26 Nov 2023", url=WTS, quote="included information not in those sources that seemed to be hallucinations", page="comment thread under the +19 answer", kind="reader", polarity="asserts", date="2023-11-26", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT 4, Nov 2023; register measured: genealogical biography with citations"),
 dict(feature="other: false intimacy in the record", claim="Brad Foley writes a parody line of generated family-history prose in the first person, recalling the smell of a great uncle's pipe.", source="Brad Foley, comment on WikiTree G2G, 23 Nov 2023", url=WTS, quote="I remember the smell of his pipe and the sound", page="comment under Eric Weddington's answer", kind="reader", polarity="asserts", date="2023-11-23", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class tools as of Nov 2023; register measured: genealogical biography"),
 dict(feature="other: person and distance in the record", claim="Eric Weddington states that a genealogical biography belongs in the third person and not the first.", source="Eric Weddington, comment on WikiTree G2G, 23 Nov 2023", url=WTS, quote="supposed to be in the 3rd person, not the first person", page="comment under his +24 answer", kind="reader", polarity="asserts", date="2023-11-23", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="written about ChatGPT-class output, Nov 2023; register measured: genealogical biography"),
 dict(feature="other: platform policy", claim="WikiTree's draft AI-image policy, put to a community vote by Brad Foley, gives as its reason that the site is committed to accurate sources and records.", source="Brad Foley, draft policy in WikiTree G2G, 13 Apr 2026", url=WTP, quote="WikiTree is committed to accurate sources and records", page="question body, Draft Policy", kind="reader", polarity="applies", date="2026-04-13", routeHint=GB, registerHint="none", confidence="high", modelEra="AI image generation and enhancement tools generally, Apr 2026; register governed: genealogical profile images, not text"),
 dict(feature="other: platform policy", claim="That same draft states the risk it addresses is that AI reconstructions of past people can be taken as fact.", source="Brad Foley, draft policy in WikiTree G2G, 13 Apr 2026", url=WTP, quote="there is a real risk that they can be taken as fact", page="question body, Draft Policy", kind="reader", polarity="applies", date="2026-04-13", routeHint=GB, registerHint="none", confidence="high", modelEra="AI image generation and enhancement tools generally, Apr 2026; register governed: genealogical profile images"),
 # --- American Ancestors ---
 dict(feature="other: fabricated or absent citation", claim="American Ancestors' Research Services reports that ChatGPT supplied a patron with a Boston marriage record that did not exist.", source="Anjelica Oswald, 'Limitations of Artificial Intelligence (AI) in Genealogical Research', Vita Brevis, American Ancestors, 11 May 2026", url=VA, quote="it made up a record that didn’t exist", page="section 'Lessons in AI'", kind="analysis", polarity="asserts", date="2026-05-11", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, incident in summer 2025, written up May 2026; register measured: archival record citation"),
 dict(feature="other: fabricated or absent citation", claim="In that case ChatGPT named three specific repositories where the non-existent record could be found.", source="Anjelica Oswald, Vita Brevis, American Ancestors, 11 May 2026", url=VA, quote="described three very specific sources where the patron could find", page="section 'Lessons in AI'", kind="analysis", polarity="asserts", date="2026-05-11", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, summer 2025; register measured: archival record citation"),
 dict(feature="other: fabricated or absent citation", claim="Staff checked the city commissioner record books at the exact pages ChatGPT specified and found no record there.", source="Anjelica Oswald, Vita Brevis, American Ancestors, 11 May 2026", url=VA, quote="the exact pages ChatGPT said the record would be with no record located", page="section 'Lessons in AI'", kind="measurement", polarity="asserts", date="2026-05-11", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, summer 2025; register measured: archival record citation"),
 dict(feature="other: transcription error in the record", claim="Oswald reports an OCR transcription that rendered a Harvard College record as Harman Collens.", source="Anjelica Oswald, Vita Brevis, American Ancestors, 11 May 2026", url=VA, quote="a record for Harvard College that was transcribed as", page="section 'When to use AI'", kind="measurement", polarity="asserts", date="2026-05-11", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="OCR/handwriting recognition (the author notes OCR is 'technically not considered AI'), observed by 2026; register measured: archival record transcription"),
 dict(feature="detection and its failures", claim="Oswald, relaying LiveScience's report of OpenAI research, states that two of OpenAI's most advanced models hallucinated 33% and 48% of the time.", source="Anjelica Oswald, Vita Brevis, relaying Roland Moore-Colyer, LiveScience, 21 June 2025", url=VA, quote="hallucinated” 33% and 48% of the time", page="section 'Lessons in AI', footnote 1", kind="relay", polarity="asserts", date="2026-05-11", routeHint=GB, registerHint="none", confidence="medium", modelEra="two unnamed advanced OpenAI models, figures reported June 2025; register measured: not stated. RELAY: the primary is LiveScience relaying OpenAI, not read here"),
 # --- Amy Johnson Crow ---
 dict(feature="other: mechanism (register expects a citation shape)", claim="Amy Johnson Crow explains the fabricated legal citations as ChatGPT producing the kind of language its training set showed a legal brief expects.", source="Amy Johnson Crow, 'Using ChatGPT for Genealogy — Accurately', 7 Jul 2023", url=AJC, quote="That was the type of language that was expected", page="section 'The Biggest Mistake in Using ChatGPT'", kind="analysis", polarity="asserts", date="2023-07-07", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT (pre-GPT-4 era usage), July 2023; register measured: legal brief citations, applied by the author to genealogical citation"),
 dict(feature="other: fabricated fact in the record", claim="Crow reports that a ChatGPT biography of her obscure great-great-grandfather, prompted with only his name, contained nothing correct.", source="Amy Johnson Crow, 7 Jul 2023", url=AJC, quote="There’s nothing in this biography that’s correct", page="section 'Getting Accuracy in ChatGPT Results'", kind="measurement", polarity="asserts", date="2023-07-07", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, July 2023; register measured: genealogical biography from a bare name prompt"),
 dict(feature="steerability", claim="Crow reports that when she supplied the verified facts, ChatGPT's biography still contained editorializing and embellishment she was not comfortable with.", source="Amy Johnson Crow, 7 Jul 2023", url=AJC, quote="There’s some editorializing and a little bit of embellishment", page="section 'Getting Accuracy in ChatGPT Results'", kind="measurement", polarity="asserts", date="2023-07-07", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, July 2023; register measured: genealogical biography written from supplied facts"),
 dict(feature="other: identity conflation", claim="Crow states that even for a subject present in its training set, ChatGPT has no good way to tell apart people who share a name.", source="Amy Johnson Crow, 7 Jul 2023", url=AJC, quote="differentiating between people who have the same name", page="section 'Getting Accuracy in ChatGPT Results'", kind="analysis", polarity="asserts", date="2023-07-07", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, July 2023; register measured: genealogical biography"),
 # --- Family Locket (counter-evidence) ---
 dict(feature="counter-evidence", claim="Nicole Elder Dyer reports that ChatGPT 4 gave the correct Chicago format for a book citation, matching the Chicago Manual of Style 17th edition at p. 799, section 14.101.", source="Nicole Elder Dyer, 'Can ChatGPT Help with Genealogy Citations?', Family Locket, 17 Nov 2023", url=FL, quote="ChatGPT did a great job with providing the accurate format", page="section 'Book Citation'", kind="measurement", polarity="rejects", date="2023-11-17", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT 4, Nov 2023; register measured: genealogical citation formatting (Evidence Explained / Chicago)"),
 dict(feature="counter-evidence", claim="Dyer concludes that ChatGPT had a much harder time with the census citation when she did not supply the details herself.", source="Nicole Elder Dyer, Family Locket, 17 Nov 2023", url=FL, quote="without me providing the details for the 1850 census", page="section 'Conclusion'", kind="measurement", polarity="asserts", date="2023-11-17", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT 4, Nov 2023; register measured: genealogical citation formatting"),
 # --- Wikipedia:Signs of AI writing (the ENCYCLOPEDIC / biographical record register) ---
 dict(feature="lexical tells", claim="Wikipedia's WikiProject AI Cleanup field guide lists 'indelible mark' among the words to watch for LLM-written claims of legacy and significance.", source="Wikipedia:Signs of AI writing (WikiProject AI Cleanup advice page), retrieved 6 Sep 2026", url=WPS, quote="indelible mark", page="§ Undue emphasis on significance, legacy, and broader trends — Words to watch", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class chatbots, page maintained 2023-2026 with a banner saying the most recent models need updating; register measured: encyclopedic articles, drafts and comments"),
 dict(feature="abstraction over the concrete", claim="That field guide states LLM writing inflates a subject's importance by adding statements about how arbitrary aspects of it contribute to a broader topic.", source="Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="LLM writing often puffs up the importance of the subject matter", page="§ Undue emphasis on significance, legacy, and broader trends", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class chatbots, 2023-2026; register measured: encyclopedic articles"),
 dict(feature="other: hedged non-statement", claim="The field guide records that when an LLM cannot find information about a person's private life it often asserts instead that the person maintains a low profile.", source="Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="often claims that the person \"maintains a low profile\"", page="§ Knowledge-cutoff disclaimers and speculation about gaps in sources", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="retrieval-augmented chatbots, 2023-2026; register measured: encyclopedic biography"),
 dict(feature="other: hedged non-statement", claim="The field guide states that such claims of undocumented information, including the claim that it is undocumented, are entirely speculative.", source="Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="This information is entirely speculative", page="§ Knowledge-cutoff disclaimers and speculation about gaps in sources", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="retrieval-augmented chatbots, 2023-2026; register measured: encyclopedic articles"),
 dict(feature="other: hedged non-statement", claim="A December 2024 revision to the Wikipedia biography 'Throwing Curves: Eva Zeisel' is given as an example, hedging that the details of the subject's resistance efforts are not widely documented.", source="a Wikipedia revision quoted as a demonstration passage in Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="Though the details of these resistance efforts aren't widely documented", page="§ Knowledge-cutoff disclaimers — Examples, 2023-2025", kind="analysis", polarity="applies", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="an unnamed LLM, revision dated Dec 2024; register measured: encyclopedic biography"),
 dict(feature="other: fabricated or absent citation", claim="The field guide states that LLMs generate references to non-existent scholarly articles carrying DOIs that look valid but belong to unrelated articles.", source="Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="Both Proceedings of the IEEE citations are completely made up", page="§ Citations — DOIs that lead to unrelated articles", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT, example passage undated on the page; register measured: encyclopedic citations"),
 dict(feature="other: fabricated or absent citation", claim="The field guide states that LLMs often produce book citations with no page number, which cannot verify the prose they support.", source="Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="LLMs often generate book citations that do not include page numbers", page="§ Citations — Book citations without page numbers or URLs", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class chatbots, 2023-2026; register measured: encyclopedic citations"),
 dict(feature="other: vague attribution", claim="The field guide states that AI chatbots attribute opinions to a vague authority and exaggerate how many sources hold them.", source="Wikipedia:Signs of AI writing, retrieved 6 Sep 2026", url=WPS, quote="attribute opinions or claims to some vague authority", page="§ Vague attributions and overgeneralization of opinions", kind="analysis", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="ChatGPT-class chatbots, 2023-2026; register measured: encyclopedic articles"),
 dict(feature="detection and its failures", claim="The field guide relays a 2025 study finding that human ability to tell LLM text from human text is no better than chance.", source="Wikipedia:Signs of AI writing relaying a 2025 study (its reference 4), retrieved 6 Sep 2026", url=WPS, quote="no better than random chance", page="§ Caveats — Your detection ability", kind="relay", polarity="asserts", date="2026-09-06", routeHint=UA, registerHint="none", confidence="medium", modelEra="unspecified models, study dated 2025; register measured: not stated on this page. RELAY: the underlying study was not read here"),
 # --- FamilySearch (vendor) ---
 dict(feature="other: platform policy", claim="FamilySearch's own AI guidance tells users that historical facts and stories generated by AI should be checked against original or reputable sources.", source="Abby Tanner, 'AI Developments in Genealogy', FamilySearch Blog, 19 Feb 2026", url=FSB, quote="should be checked against original or reputable sources to ensure accuracy", page="§ Concerns and Ethics with AI Genealogy — Accuracy of Information", kind="vendor", polarity="applies", date="2026-02-19", routeHint=UA, registerHint="none", confidence="high", modelEra="generative AI generally, Feb 2026; register governed: genealogical facts and stories"),
 dict(feature="other: platform policy", claim="The same FamilySearch page markets generative AI as able to turn dry details into a biographical format.", source="Abby Tanner, FamilySearch Blog, 19 Feb 2026", url=FSB, quote="transform dry details into a story or biographical format", page="§ How Can AI Be Used for Genealogy? — Telling stories", kind="vendor", polarity="asserts", date="2026-02-19", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="generative AI generally, Feb 2026; register governed: family-history narrative"),
]
claims.extend(add)
sources.extend([
 dict(title="Should WikiTree have a style guide for AI generated content? (WikiTree G2G, 13 answers)", url=WTS, kind="reader", substantive=True, date="2023-11-22", route="curl + Googlebot user agent"),
 dict(title="Should this become the official WikiTree policy on AI generated or enhanced images of people (WikiTree G2G)", url=WTP, kind="reader", substantive=True, date="2026-04-13", route="curl + Googlebot user agent"),
 dict(title="Limitations of Artificial Intelligence (AI) in Genealogical Research — Vita Brevis, American Ancestors", url=VA, kind="analysis", substantive=True, date="2026-05-11", route="curl + Googlebot user agent"),
 dict(title="Using ChatGPT for Genealogy — Accurately (Amy Johnson Crow)", url=AJC, kind="analysis", substantive=True, date="2023-07-07", route="curl + Googlebot user agent (a normal browser agent returns HTTP 412)"),
 dict(title="Can ChatGPT Help with Genealogy Citations? (Nicole Elder Dyer, Family Locket)", url=FL, kind="measurement", substantive=True, date="2023-11-17", route="curl + Googlebot user agent"),
 dict(title="Wikipedia:Signs of AI writing (WikiProject AI Cleanup field guide)", url=WPS, kind="analysis", substantive=True, date="2026-09-06", route="curl + desktop browser user agent"),
 dict(title="AI Developments in Genealogy — FamilySearch Blog (vendor)", url=FSB, kind="vendor", substantive=True, date="2026-02-19", route="curl + desktop browser user agent"),
 dict(title="Artificial Intelligence — FamilySearch Help Center (a class index, NOT a policy: FamilySearch publishes no restrictive AI-content policy)", url="https://www.familysearch.org/en/help/helpcenter/artificial-intelligence", kind="vendor", substantive=False, date="2026-09-06", route="curl + Googlebot user agent"),
])
json.dump(dict(complete=False, coverage="checkpoint 2", sourcesRead=sources, claims=claims), open("found-ai-arch-biographical-record.json","w"), indent=1, ensure_ascii=False)
print("claims",len(claims),"sources",len(sources))
