import json,sys
V="https://www.theverge.com/24065145/ai-obituary-spam-generative-clickbait"
WM="https://www.wired.com/story/morbid-war-online-obituaries/"
WY="https://www.wired.com/story/youtube-obituary-pirates/"
LG="https://www.legalgenealogist.com/2026/05/12/ai-meets-tos/"
SATO="Mia Sato, 'The unsettling scourge of obituary spam', The Verge, 12 Feb 2024"
UA="curl with a desktop browser user agent on the live URL"
claims=[
 dict(feature="other: fabricated fact in the record", claim="Sato reports that AI-hallmarked obituaries that reached the top of Google Search announced the death of Brian Vastag, who was alive.", source=SATO, url=V, quote="Except Brian Vastag was very much alive", page="body, third paragraph", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools inferred by the reporter from stylistic hallmarks, observed Dec 2023-Feb 2024; register measured: obituary / biographical record"),
 dict(feature="homogenisation", claim="Sato describes the dozen-plus spam obituaries about one dead woman as detached and near-identical to each other, differing only by a few reordered words.", source=SATO, url=V, quote="The obituaries are detached and nearly identical to one another", page="body, section on the Vastag/Mazur obituaries", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="other: fabricated fact in the record", claim="Sato reports that the near-identical generated obituaries each repeated the same wrong statement of where the deceased had lived.", source=SATO, url=V, quote="repeating inaccurate details, like where Mazur lived", page="body, section on the Vastag/Mazur obituaries", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="lexical tells", claim="Sato characterises the generated obituary articles as written in a nondescript gravitas built out of unnatural phrasing.", source=SATO, url=V, quote="written with a nondescript gravitas, using unnatural phrasing", page="body, section on The Thaiger", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="lexical tells", claim="Sato names the phrases 'indelible mark' and 'untimely demise' as the unnatural phrasing carrying that gravitas.", source=SATO, url=V, quote="the “indelible mark” a person has left, or their “untimely demise,”", page="body, section on The Thaiger", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="abstraction over the concrete", claim="Sato reports that the generated obituaries carry that elevated phrasing while containing no actual detail about the dead person's life.", source=SATO, url=V, quote="but without any actual detail about their life", page="body, section on The Thaiger", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="other: missing testimony", claim="Sato reports the generated obituary articles carry no quotations from family or friends of the deceased.", source=SATO, url=V, quote="they lack quotes from family or friends of the deceased", page="body, section on The Thaiger", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="other: fabricated or absent citation", claim="Sato reports the generated obituary articles cite no outside reporting although they are written in the form of news articles.", source=SATO, url=V, quote="do not cite outside reporting", page="body, section on The Thaiger", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="other: hedged non-statement", claim="A generated obituary of a Calgary woman, quoted by Sato as a demonstration passage, ends by advising the public to await verified information instead of stating a fact.", source="a spam obituary quoted verbatim by Mia Sato, The Verge, 12 Feb 2024", url=V, quote="the curious and concerned public is advised to stay tuned", page="body, section on The Thaiger", kind="analysis", polarity="applies", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="homogenisation", claim="Sato reports that one site's death stories follow a shared structure and sometimes reuse identical vague phrases about different deceased people.", source=SATO, url=V, quote="sometimes using identical vague phrases about the deceased", page="body, section on The Thaiger", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI tools, observed Feb 2024; register measured: obituary / biographical record"),
 dict(feature="other: mechanism (scrape then summarise)", claim="Sato reports that one article announcing Vastag's death appears to be an AI summary of an op-ed he co-authored with the woman who had actually died.", source=SATO, url=V, quote="appears to be an AI summary of the op-ed", page="body, paragraph on hallmarks of AI generation", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="unnamed generative-AI summarisation, observed Dec 2023; register measured: obituary / biographical record"),
 dict(feature="counter-evidence", claim="Sato writes that of all the obituaries published for Beth Mazur only the one written by a person who knew her captures who she actually was.", source=SATO, url=V, quote="only Vastag’s obituary captures the actual person Mazur was", page="body, closing section", kind="analysis", polarity="asserts", date="2024-02-12", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="comparison of unnamed generative-AI obituaries against a human-written one, Feb 2024; register measured: obituary / biographical record"),
 dict(feature="other: kin relation corrupted", claim="Weiss reports that Echovita's automated summary of a family-written obituary turned the dead woman's granddaughter into a grandson.", source="Ben Weiss, 'The Morbid War Over Online Obituaries', WIRED, 26 Dec 2021", url=WM, quote="Her granddaughter became a grandson", page="body, opening section", kind="analysis", polarity="asserts", date="2021-12-26", routeHint=UA, registerHint="dossier-archivist", confidence="medium", modelEra="an unnamed automated summariser at Echovita, observed Aug-Dec 2021 (PRE-LLM: the widower calls it 'their algorithm, or whatever program they use'; the article never says a language model); register measured: obituary / biographical record"),
 dict(feature="other: kin omitted", claim="Weiss reports that the same automated summary left the dead woman's children out of the list of survivors.", source="Ben Weiss, 'The Morbid War Over Online Obituaries', WIRED, 26 Dec 2021", url=WM, quote="her children weren’t mentioned as survivors", page="body, opening section", kind="analysis", polarity="asserts", date="2021-12-26", routeHint=UA, registerHint="dossier-archivist", confidence="medium", modelEra="an unnamed automated summariser at Echovita, observed 2021 (pre-LLM); register measured: obituary / biographical record"),
 dict(feature="other: relation category error", claim="Weiss reports that the automated summary called the dead woman's two dogs her close friends without recording that they were dogs.", source="Ben Weiss, 'The Morbid War Over Online Obituaries', WIRED, 26 Dec 2021", url=WM, quote="failing to note that they were dogs", page="body, opening section", kind="analysis", polarity="asserts", date="2021-12-26", routeHint=UA, registerHint="dossier-archivist", confidence="medium", modelEra="an unnamed automated summariser at Echovita, observed 2021 (pre-LLM); register measured: obituary / biographical record"),
 dict(feature="reader and expert judgment", claim="The widower Joel Thompson's verdict on the machine-summarised obituary of his wife, in his own words to WIRED, was that it read as a child's work.", source="Joel Thompson, quoted by Ben Weiss, WIRED, 26 Dec 2021", url=WM, quote="It looks like a fourth grader did it", page="body, opening section", kind="reader", polarity="asserts", date="2021-12-26", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="an unnamed automated summariser at Echovita, judged Dec 2021 (pre-LLM); register measured: obituary / biographical record"),
 dict(feature="other: garbled record register", claim="Knibbs reports that MSN published an obituary of the former NBA player Brandon Hunter that was incoherent and oddly hostile.", source="Kate Knibbs, 'The Bizarre Cottage Industry of YouTube Obituary Pirates', WIRED, 22 Sep 2023", url=WY, quote="an incoherent and oddly hostile obituary for former NBA player", page="body, penultimate section", kind="reception", polarity="asserts", date="2023-09-22", routeHint=UA, registerHint="dossier-archivist", confidence="high", modelEra="MSN's algorithmically generated news content, observed Sep 2023; register measured: obituary / biographical record"),
 dict(feature="other: garbled record register", claim="Knibbs reports that critics assumed that garbled MSN obituary had been written by AI, and that Microsoft never confirmed it.", source="Kate Knibbs, WIRED, 22 Sep 2023", url=WY, quote="critics assumed the garbled article was written by AI", page="body, penultimate section", kind="reception", polarity="mentions", date="2023-09-22", routeHint=UA, registerHint="dossier-archivist", confidence="medium", modelEra="MSN content of unconfirmed provenance, Sep 2023; register measured: obituary / biographical record. Attribution to AI is critics' assumption, never confirmed by Microsoft"),
 dict(feature="other: platform policy", claim="MyHeritage's amended terms, quoted by Russell, narrow the licence to use its records to personal, non-commercial and human use.", source="MyHeritage terms and conditions, quoted by Judy G. Russell, 'AI meets TOS', The Legal Genealogist, 12 May 2026", url=LG, quote="personal, non-commercial, and human use", page="body, MyHeritage section", kind="vendor", polarity="applies", date="2026-05-12", routeHint=UA, registerHint="none", confidence="high", modelEra="AI agents generally, policy dated Apr 2026; register governed: genealogical records databases"),
]
sources=[
 dict(title="The unsettling scourge of obituary spam", url=V, kind="reporting", substantive=True, date="2024-02-12", route="curl + desktop browser user agent"),
 dict(title="The Morbid War Over Online Obituaries", url=WM, kind="reporting", substantive=True, date="2021-12-26", route="curl + desktop browser user agent"),
 dict(title="The Bizarre Cottage Industry of YouTube Obituary Pirates", url=WY, kind="reporting", substantive=True, date="2023-09-22", route="curl + desktop browser user agent"),
 dict(title="Obituary piracy (Wikipedia) — used as a relay only, to reach the two WIRED primaries", url="https://en.wikipedia.org/wiki/Obituary_piracy", kind="relay", substantive=False, date="2026-09-06", route="curl + desktop browser user agent"),
 dict(title="AI meets TOS — The Legal Genealogist (Judy G. Russell)", url=LG, kind="analysis", substantive=True, date="2026-05-12", route="curl + desktop browser user agent"),
 dict(title="The Legal Genealogist — all 192 posts dated 2023-2026, scanned for chatgpt/artificial intelligence/generative ai/large language (NEGATIVE RESULT: no post on ChatGPT-fabricated citations exists)", url="https://www.legalgenealogist.com/wp-sitemap-posts-post-2.xml", kind="measurement", substantive=True, date="2026-09-06", route="wp-sitemap enumeration + curl of every post"),
]
out=dict(complete=False, coverage="checkpoint 1 of N", sourcesRead=sources, claims=claims)
json.dump(out, open("found-ai-arch-biographical-record.json","w"), indent=1, ensure_ascii=False)
print("claims",len(claims),"sources",len(sources))
