import json
SL="https://slate.com/technology/2022/12/davinci-003-chatbot-gpt-wrote-my-obituary.html"
S="Charles Seife, 'OpenAI's bot wrote my obituary. It was filled with bizarre lies.', Slate, 13 Dec 2022"
GB="curl with a Googlebot user agent"
ERA="OpenAI Davinci-003 (a sibling of the then just-released ChatGPT), tested Dec 2022; register measured: the obituary of a living person, written about himself"
d=json.load(open("found-ai-arch-biographical-record.json"))
add=[
 dict(feature="other: fabricated fact in the record", claim="Seife reports that the obituary Davinci-003 wrote of him gave the wrong birth date, wrong year and wrong city.", source=S, url=SL, quote="Wrong date, wrong year, wrong city", page="body, after the 'renowned author' sentence", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: fabricated fact in the record", claim="Seife reports the same obituary awarded him a Berkeley mathematics doctorate he never held.", source=S, url=SL, quote="this has no basis in reality", page="body, education paragraph", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: fabricated fact in the record", claim="Seife reports the obituary credited him with a book he says does not exist.", source=S, url=SL, quote="As far as I can tell, no such book exists", page="body, bibliography paragraph", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: fabricated fact in the record", claim="Seife reports the obituary listed courses he taught that were drawn from the wrong university department.", source=S, url=SL, quote="all not just wrong, but subjects from the wrong department", page="body, NYU paragraph", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="steerability", claim="Seife's finding is that the model embellished even where it had no need to.", source=S, url=SL, quote="It embellished with abandon, even when it didn’t have to", page="body, after the birth-date errors", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="lexical tells", claim="Seife quotes the generated line remembering him fondly for his wit, intelligence and enthusiasm for life as the cliché his legacy became.", source="a Davinci-003 obituary quoted as a demonstration passage by Charles Seife, Slate, 13 Dec 2022", url=SL, quote="Charles Seife will be fondly remembered by his friends and family", page="body, opening section", kind="measurement", polarity="applies", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: eulogy register in the record", claim="Seife names the transformation of his legacy into a cliché as one thing the generated obituary did.", source=S, url=SL, quote="the way my legacy was transformed into a cliché", page="body, opening section", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: fabricated or absent citation", claim="Asked to cite a source for each sentence, the model attributed his education to a New York Times obituary at a plausible-looking URL that Seife reports never existed.", source=S, url=SL, quote="Of course, no such obituary ever existed", page="body, sourcing experiment", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: mechanism (a citation is generated to match the claim)", claim="Seife's summary of the sourcing experiment is that the model invented references to support its invented facts.", source=S, url=SL, quote="making up BS references to back up its BS facts", page="body, sourcing experiment", kind="analysis", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra=ERA),
 dict(feature="other: mechanism (a citation is generated to match the claim)", claim="Seife argues the work of constructing a believable imitation source is as deep as the work of generating the answer itself.", source=S, url=SL, quote="The implicit effort that’s put in to create a believable facsimile", page="body, closing section", kind="analysis", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="none", confidence="high", modelEra="OpenAI Davinci-003, Dec 2022; register measured: obituary and plagiarism-detection tasks"),
 dict(feature="other: fabricated or absent citation", claim="In a separate non-creative task Seife reports the model attributed his own prose to an ACLU page and a Wired article that are both invented.", source=S, url=SL, quote="both references are entirely made up", page="body, plagiarism-detection experiment", kind="measurement", polarity="asserts", date="2022-12-13", routeHint=GB, registerHint="dossier-archivist", confidence="high", modelEra="OpenAI Davinci-003, Dec 2022; register measured: source attribution for a passage of the author's own prose"),
]
d["claims"].extend(add)
d["sourcesRead"].append(dict(title="OpenAI's bot wrote my obituary. It was filled with bizarre lies. (Charles Seife, Slate/Future Tense)", url=SL, kind="measurement", substantive=True, date="2022-12-13", route="curl + Googlebot user agent"))
d["sourcesRead"].append(dict(title="AI and Obituaries: Did AI Write This Death Announcement? (ElderLawAnswers) — read, no independent measurement of prose faults; not used for a claim", url="https://www.elderlawanswers.com/ai-and-obituaries-did-ai-write-this-death-announcement-20344", kind="analysis", substantive=False, date="2024-02-28", route="curl + Googlebot user agent"))
d["sourcesRead"].append(dict(title="Using AI to Write an Obituary (Tulip Cremation) — fetched; the 'Obituare' comparison that search snippets attribute to it is NOT in the page as fetched, so no claim is drawn", url="https://www.tulipcremation.com/articles/tulip-expert-guides/death-resources/using-ai-to-write-an-obituary.html", kind="vendor", substantive=False, date="2026-09-06", route="curl + Googlebot user agent"))
d["complete"]=True
d["coverage"]=("NAMED ROSTER — FETCHED: The Verge (Mia Sato, 12 Feb 2024; the URL in circulation 404s, the live one is /24065145/); "
 "the WIRED obituary reporting, which is two pieces not one (Ben Weiss, 26 Dec 2021, on Echovita's automated summaries, and Kate Knibbs, 22 Sep 2023, on YouTube obituary pirates and the MSN Brandon Hunter obituary) — note both PRECEDE the Verge piece, so the true successor reporting is the Washington Post (Drew Harwell, 3 Aug 2025), recovered via the Wayback raw capture and used as a primary; "
 "WikiTree's AI positions (the Nov 2023 G2G style-guide thread on AI biographies and the Apr 2026 draft AI-image policy with its stated reason) via a Googlebot agent, since a browser agent draws an HTTP 202 challenge. "
 "NOT FOUND: Judy G. Russell on ChatGPT-fabricated citations — established negatively, not merely unsearched: all 192 posts on legalgenealogist.com dated 2023-2026 were enumerated from the site's wp-sitemap and fetched, and grepped for chatgpt|artificial intelligence|generative ai|large language; 16 mention AI, every one incidentally (Rumsey map OCR, Ancestry/MyHeritage/23andMe TOS, a lecture listing, the joke holiday disclaimers), and the only AI-substantive post, 'AI meets TOS' (12 May 2026), is about terms of service. No such post exists; the widely repeated genealogy example of ChatGPT inventing sources is Amy Johnson Crow's, and the fabricated-citation case in the archival register is American Ancestors' (Anjelica Oswald, 11 May 2026) — both fetched and used in her place. "
 "NOT FOUND: Find a Grave generated-biography complaints — searched Find a Grave support and news, the consumer-complaint aggregators, WikiTree G2G and Reddit-shaped queries; what exists is complaints about scraped, inaccurate and hijacked memorials and about memorials of the recently deceased, not about AI-written bios; findagrave.com/news returns HTTP 403. "
 "PARTIALLY NEGATIVE: FamilySearch publishes no restrictive AI-content policy — its Help Center 'Artificial Intelligence' page is a class index and its blog (19 Feb 2026) is promotional with accuracy cautions; the genealogy body that does prohibit AI-written work, the Board for Certification of Genealogists (9 Jul 2024), was fetched in its place. "
 "BLOCKED then recovered: washingtonpost.com (live and Googlebot both failed; Wayback raw capture worked); amyjohnsoncrow.com (HTTP 412 on a browser agent, Googlebot worked); en.wikipedia.org/wiki/Wikipedia:Signs_of_AI_writing (403 on Googlebot, browser agent worked). "
 "SUBSTANTIVE SOURCES PER ROUTE: named roster 5; bibliography chasing 3 (both WIRED pieces via the Wikipedia 'Obituary piracy' relay, the Washington Post via Futurism); lateral search 13 (American Ancestors, Amy Johnson Crow, Family Locket, Wikipedia:Signs of AI writing, Wikipedia:Large language models, Poynter, Futurism x2, BCG, FActScore abstract and PDF, Slate, the Legal Genealogist site-wide scan as a negative measurement). 21 substantive, 5 read but not substantive. "
 "STOP RULE: the last two lateral searches surfaced only the Obituare snippet, which could not be verified on the page it is attributed to and yielded no claim. "
 "THE GAP THIS ANGLE FILLS: the method notes that no source had measured the archival or encyclopedic register. Four now do — FActScore human-evaluates people biographies against Wikipedia (42.5 / 58.3 / 71.5 per cent), Wikipedia:Signs of AI writing is a field guide built from real encyclopedic-biography revisions, the Washington Post tested four obituary generators against a fictional subject, and Charles Seife tested one against himself.")
json.dump(d,open("found-ai-arch-biographical-record.json","w"),indent=1,ensure_ascii=False)
print("claims",len(d["claims"]),"sources",len(d["sourcesRead"]))
