import json
d=json.load(open("found-ai-counter-cases.json"))
C=d["claims"]; S=d["sourcesRead"]
def c(**k): C.append(k)
PO="https://www.nature.com/articles/s41598-024-76900-1"
GW="https://arxiv.org/html/2601.18353v1"
CB="https://arxiv.org/abs/2510.13939"
IT="https://arxiv.org/abs/2601.17363v3"
AA="https://arxiv.org/abs/2309.14556v3"
SV="https://arxiv.org/abs/2409.14509v5"
DO="https://www.ebi.ac.uk/europepmc/webservices/rest/PMC11244532/fullTextXML"

# Porter & Machery
c(feature="counter-evidence",claim="Porter and Machery found non-expert readers identified AI-generated poems at below-chance accuracy.",source="Brian Porter and Edouard Machery, Scientific Reports 14, 26133, 14 November 2024",url=PO,quote="participants performed below chance levels in identifying AI-generated poems",page="Abstract",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl with browser user agent on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, poems generated for a study published November 2024; register measured: short lyric poetry")
c(feature="detection and its failures",claim="Accuracy in Porter and Machery's discrimination study was 46.6 percent.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="Observed accuracy was in fact slightly lower than chance (46.6%",page="Results, Study 1",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="counter-evidence",claim="Participants were more likely to judge AI-generated poems human-authored than they were actual human-authored poems.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="more likely to judge AI-generated poems as human-authored than actual",page="Abstract",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="cadence and rhythm",claim="Rhythm showed the largest effect in Porter and Machery's ratings: AI poems were rated as having much better rhythm than the famous poets' poems.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="AI-generated poems are rated as having much better rhythm than",page="Results, Study 2",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="herald-pools",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="reader and expert judgment",claim="Every one of the five AI-generated poems in Porter and Machery's study 2 was rated higher in overall quality than every one of the five human-authored poems.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="all 5 AI-generated poems are rated more highly in overall quality",page="Results, Study 2, discussion of Fig. 2",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="abstraction over the concrete",claim="Porter and Machery propose that readers rate AI poems higher because they find them more straightforward.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="they find AI poems more straightforward",page="Discussion",kind="analysis",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="metaphor discipline",claim="Porter and Machery observe that the AI-generated poems in their assessment study rarely use complex metaphors.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="These poems rarely use complex metaphors",page="Discussion",kind="analysis",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="reader and expert judgment",claim="Participants used variations of the phrase 'doesn't make sense' 144 times for human-authored poems and 29 times for AI-generated poems.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="144 explanations vs. 29 explanations",page="Discussion",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="detection and its failures",claim="Self-reported experience with poetry did not improve participants' ability to tell AI poems from human ones.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="experience with poetry did not improve discrimination performance",page="Results, Study 1, exploratory model",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")
c(feature="register measured",claim="Porter and Machery generated their stimuli with ChatGPT 3.5, five poems in the style of each of ten poets.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="Using ChatGPT 3.5, we generated 5 poems",page="Introduction, description of stimuli",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, stimuli generated for a 2024 study; register measured: short lyric poetry, no archival or record register")
c(feature="steerability",claim="Porter and Machery used a human-out-of-the-loop paradigm, keeping the first five poems generated with no feedback or selection.",source="Brian Porter and Edouard Machery, Scientific Reports, 14 November 2024",url=PO,quote="we used the first 5 poems generated",page="Introduction, description of stimuli",kind="measurement",polarity="asserts",date="2024-11-14",routeHint="curl on the live nature.com article",registerHint="none",confidence="high",modelEra="ChatGPT 3.5, 2024; register measured: short lyric poetry")

# Chakrabarty & Dhillon CHI 2026
c(feature="counter-evidence",claim="Expert MFA judges preferred human writing in 82.7% of pairwise comparisons when the AI wrote by in-context prompting.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1), 26 January 2026",url=GW,quote="experts preferred human writing in 82.7% of cases under the",page="Abstract",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on the arXiv HTML rendering https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro, study run before January 2026; register measured: literary fiction and creative nonfiction excerpts up to 450 words")
c(feature="steerability",claim="Expert preference reversed to 62% in favour of AI after GPT-4o was fine-tuned on the emulated authors' complete works.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="reversed to 62% preference for AI after fine-tuning",page="Abstract",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="GPT-4o fine-tuned per author, January 2026; register measured: literary fiction and creative nonfiction excerpts up to 450 words")
c(feature="reader and expert judgment",claim="Lay judges in the Chakrabarty and Dhillon study consistently preferred AI writing.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="Lay judges, however, consistently preferred AI writing",page="Abstract",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="GPT-4o / Claude 3.5 Sonnet / Gemini 1.5 Pro, January 2026; register measured: literary fiction excerpts")
c(feature="steerability",claim="Chakrabarty and Dhillon attribute the expert preference shift to fine-tuning removing the stylistic tics experts had used to tell AI from human text.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="fine-tuning eliminates the stylistic tics—clichés, awkward phrasing, overly ornamental language",page="Section 4.1",kind="analysis",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="medium",reason="the authors hedge this mechanism with the word 'possibly'",modelEra="GPT-4o fine-tuned per author, January 2026; register measured: literary fiction excerpts")
c(feature="counter-evidence",claim="For stylistic fidelity after fine-tuning, 81.1% of experts and 80.0% of lay evaluators preferred the AI-generated excerpt.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="both experts (81.1%) and lay evaluators (80.0%) strongly preferred AI-generated writing",page="Figure 7 caption",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="GPT-4o fine-tuned per author, January 2026; register measured: literary fiction excerpts")
c(feature="reader and expert judgment",claim="Lay judges in the study justified their preferences by whether a passage flowed well, was more organized, or was easier to follow.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="Lay judges disproportionately reward writing based on whether it",page="Section 4.2",kind="analysis",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="January 2026; register measured: literary fiction excerpts")
c(feature="steerability",claim="Fine-tuning in the Chakrabarty and Dhillon study required 583 times more tokens on average than in-context prompting.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="fine-tuning requires 583 times more number of tokens on average",page="Section 3.1.3, Figure 6",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="GPT-4o fine-tuning, January 2026; register measured: literary fiction excerpts")
c(feature="register measured",claim="The three models compared under in-context prompting were GPT-4o, Claude 3.5 Sonnet and Gemini 1.5 Pro.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="OpenAI’s GPT-4o, Anthropic’s Claude 3.5 Sonnet, and Google’s Gemini 1.5 Pro",page="Section 3.1.3",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro, January 2026; register measured: literary fiction excerpts")
c(feature="register measured",claim="The study's unit of comparison was an excerpt of up to 450 words, which the authors concede leaves plot, character and structure unmeasured.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="Our study examines shorter (up to 450-word) excerpts",page="Section 3.1.4",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="January 2026; register measured: literary fiction excerpts up to 450 words")
c(feature="reader and expert judgment",claim="Expert judges reached moderate-to-substantial inter-annotator agreement while lay judges remained inconsistent.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="whereas lay judges remained inconsistent",page="Section 4.1",kind="measurement",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="January 2026; register measured: literary fiction excerpts")
c(feature="reader and expert judgment",claim="Debrief interviews reported that expert writers' preference for AI writing triggered an identity crisis that eroded aesthetic confidence.",source="Tuhin Chakrabarty and Paramveer S. Dhillon, CHI 2026 (arXiv:2601.18353v1)",url=GW,quote="triggered an identity crisis, eroding aesthetic confidence",page="Abstract",kind="reception",polarity="asserts",date="2026-01-26",routeHint="curl on https://arxiv.org/html/2601.18353v1",registerHint="none",confidence="high",modelEra="January 2026; register measured: literary fiction excerpts")

# Chakrabarty, Ginsburg & Dhillon (preprint)
c(feature="detection and its failures",claim="In the Chakrabarty, Ginsburg and Dhillon preprint, leading detectors flagged 3% of fine-tuned outputs as AI-generated against 97% of in-context prompted outputs.",source="Tuhin Chakrabarty, Jane C. Ginsburg and Paramveer Dhillon, arXiv:2510.13939v4 (last revised 17 March 2026)",url=CB,quote="rarely flagged as AI-generated (3% vs. 97% for prompting)",page="Abstract",kind="measurement",polarity="asserts",date="2026-03-17",routeHint="curl on the arXiv abstract page; the SSRN version (Columbia Public Law Research Paper No. 5606570) is behind a Cloudflare interstitial",registerHint="none",confidence="medium",reason="read at the abstract only; the detector names and thresholds are not on the abstract page",modelEra="ChatGPT, Claude and Gemini prompted, plus ChatGPT fine-tuned per author; preprint revised March 2026; register measured: up to 450-word literary excerpts")
c(feature="steerability",claim="The same preprint reports a median fine-tuning cost of $81 per author.",source="Tuhin Chakrabarty, Jane C. Ginsburg and Paramveer Dhillon, arXiv:2510.13939v4",url=CB,quote="median fine-tuning cost of $81 per author",page="Abstract",kind="measurement",polarity="asserts",date="2026-03-17",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read",modelEra="ChatGPT fine-tuning, priced as of the October 2025 preprint; register measured: literary excerpts")
c(feature="counter-evidence",claim="In that preprint 516 college-educated general readers took part alongside 28 MFA-trained readers.",source="Tuhin Chakrabarty, Jane C. Ginsburg and Paramveer Dhillon, arXiv:2510.13939v4",url=CB,quote="28 MFA-trained readers and 516 college-educated general readers",page="Abstract",kind="measurement",polarity="asserts",date="2026-03-17",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read",modelEra="preprint revised March 2026; register measured: literary excerpts")

# Farrell Italian
c(feature="counter-evidence",claim="In Farrell's blind Italian-language test the AI-written texts received slightly higher average ratings than the Moravia story.",source="Michael Farrell, arXiv:2601.17363v3, NeTTIT 2026, 24 January 2026 (v3 3 June 2026)",url=IT,quote="AI-written texts received slightly higher average ratings and were more",page="Abstract",kind="measurement",polarity="asserts",date="2026-01-24",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="only 20 participants and three stories; the author calls the differences modest",modelEra="ChatGPT-4o, study reported January 2026; register measured: Italian-language literary short story")
c(feature="register measured",claim="Farrell's stimuli were three stories, two made with ChatGPT-4o and one by Alberto Moravia.",source="Michael Farrell, arXiv:2601.17363v3",url=IT,quote="two created with ChatGPT-4o and one by Alberto Moravia",page="Abstract",kind="measurement",polarity="asserts",date="2026-01-24",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="high",modelEra="ChatGPT-4o, January 2026; register measured: Italian-language literary short story")

# Art or Artifice
c(feature="counter-evidence",claim="Chakrabarty and colleagues found LLM-generated stories passed 3 to 10 times fewer Torrance Test of Creative Writing tests than stories by professional authors.",source="Tuhin Chakrabarty, Philippe Laban, Divyansh Agarwal, Smaranda Muresan and Chien-Sheng Wu, CHI 2024 (arXiv:2309.14556v3)",url=AA,quote="LLM-generated stories pass 3-10X less TTCW tests than stories written by professionals",page="Abstract",kind="measurement",polarity="disputes",date="2024-03-08",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read; the model versions are not named on the abstract page",modelEra="LLMs of 2023; register measured: New Yorker-length short stories")
c(feature="detection and its failures",claim="In the same study no LLM used as an assessor positively correlated with the expert assessments.",source="Chakrabarty, Laban, Agarwal, Muresan and Wu, CHI 2024 (arXiv:2309.14556v3)",url=AA,quote="none of the LLMs positively correlate with the expert assessments",page="Abstract",kind="measurement",polarity="asserts",date="2024-03-08",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read",modelEra="LLMs of 2023; register measured: short stories")

# Salvaged
c(feature="discourse-level tells",claim="Professional writers hired to edit LLM paragraphs agreed on undesirable idiosyncrasies and the researchers formalised them into a seven-category taxonomy.",source="Tuhin Chakrabarty, Philippe Laban and Chien-Sheng Wu, CHI 2025 (arXiv:2409.14509v5)",url=SV,quote="a seven-category taxonomy (e.g. clichés, unnecessary exposition)",page="Abstract",kind="measurement",polarity="asserts",date="2025-03-04",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read; the seven categories are not enumerated on the abstract page",modelEra="GPT-4o, Claude 3.5 Sonnet, Llama 3.1 70b, corpus built 2024; register measured: creative-writing paragraphs in several domains")
c(feature="homogenisation",claim="No model in the LAMP study outperformed the others on writing quality, which the authors read as a limitation common to model families.",source="Chakrabarty, Laban and Wu, CHI 2025 (arXiv:2409.14509v5)",url=SV,quote="outperform each other in terms of writing quality",page="Abstract",kind="measurement",polarity="asserts",date="2025-03-04",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read",modelEra="GPT-4o, Claude 3.5 Sonnet, Llama 3.1 70b, 2024; register measured: creative-writing paragraphs")
c(feature="steerability",claim="A large-scale preference annotation in that study confirmed experts largely prefer text edited by other experts over automatically edited text.",source="Chakrabarty, Laban and Wu, CHI 2025 (arXiv:2409.14509v5)",url=SV,quote="experts largely prefer text edited by other experts",page="Abstract",kind="measurement",polarity="asserts",date="2025-03-04",routeHint="curl on the arXiv abstract page",registerHint="none",confidence="medium",reason="abstract-only read",modelEra="2024-25; register measured: creative-writing paragraphs")

# Doshi & Hauser
c(feature="counter-evidence",claim="Doshi and Hauser found that access to generative AI story ideas caused stories to be evaluated as more creative.",source="Anil R. Doshi and Oliver P. Hauser, Science Advances 10, eadn5290, 12 July 2024",url=DO,quote="generative AI ideas causes stories to be evaluated as more",page="Abstract",kind="measurement",polarity="asserts",date="2024-07-12",routeHint="science.org is behind a Cloudflare interstitial; read the Europe PMC full-text XML at https://www.ebi.ac.uk/europepmc/webservices/rest/PMC11244532/fullTextXML",registerHint="none",confidence="high",modelEra="OpenAI GPT-4, experiment run 2023; register measured: eight-paragraph short stories by non-professional writers")
c(feature="homogenisation",claim="Stories written with generative AI ideas were more similar to each other than stories written by humans alone.",source="Anil R. Doshi and Oliver P. Hauser, Science Advances, 12 July 2024",url=DO,quote="stories are more similar to each other than stories by",page="Abstract",kind="measurement",polarity="asserts",date="2024-07-12",routeHint="Europe PMC full-text XML for PMC11244532",registerHint="none",confidence="high",modelEra="GPT-4, 2023; register measured: short stories")
c(feature="counter-evidence",claim="Writers given five generative AI ideas produced stories rated 8.1% higher in novelty than writers with no AI access.",source="Anil R. Doshi and Oliver P. Hauser, Science Advances, 12 July 2024",url=DO,quote="an increase in novelty of 8.1%",page="Results",kind="measurement",polarity="asserts",date="2024-07-12",routeHint="Europe PMC full-text XML for PMC11244532",registerHint="none",confidence="high",modelEra="GPT-4, 2023; register measured: short stories")
c(feature="counter-evidence",claim="For the least inherently creative writers, ratings of how well the story was written rose by up to 26.6% with five AI ideas.",source="Anil R. Doshi and Oliver P. Hauser, Science Advances, 12 July 2024",url=DO,quote="how well the story was written increase by up to 26.6%",page="Results, marginal effects by DAT score",kind="measurement",polarity="asserts",date="2024-07-12",routeHint="Europe PMC full-text XML for PMC11244532",registerHint="none",confidence="high",modelEra="GPT-4, 2023; register measured: short stories")
c(feature="counter-evidence",claim="Among the most inherently creative writers, access to generative AI ideas had little effect on their stories' evaluations.",source="Anil R. Doshi and Oliver P. Hauser, Science Advances, 12 July 2024",url=DO,quote="there is little effect of having access to generative AI ideas",page="Results, marginal effects by DAT score",kind="measurement",polarity="asserts",date="2024-07-12",routeHint="Europe PMC full-text XML for PMC11244532",registerHint="none",confidence="high",modelEra="GPT-4, 2023; register measured: short stories")
c(feature="register measured",claim="The generative model in the Doshi and Hauser experiment was OpenAI's GPT-4, used only to supply a three-sentence starting idea.",source="Anil R. Doshi and Oliver P. Hauser, Science Advances, 12 July 2024",url=DO,quote="OpenAI’s GPT-4 LLM",page="Study design",kind="measurement",polarity="asserts",date="2024-07-12",routeHint="Europe PMC full-text XML for PMC11244532",registerHint="none",confidence="high",modelEra="GPT-4, 2023; register measured: short stories, with AI supplying ideas rather than prose")

S += [
 dict(title="AI-generated poetry is indistinguishable from human-written poetry and is rated more favorably",url=PO,kind="measurement",substantive=True,date="2024-11-14",route="curl + browser UA, live nature.com"),
 dict(title="Can Good Writing Be Generative? Expert-Level AI Writing Emerges through Fine-Tuning on High-Quality Books (CHI 2026)",url=GW,kind="measurement",substantive=True,date="2026-01-26",route="curl + browser UA on the arXiv HTML full text"),
 dict(title="Readers Prefer Outputs of AI Trained on Copyrighted Books over Expert Human Writers",url=CB,kind="measurement",substantive=True,date="2026-03-17",route="curl on the arXiv abstract page (SSRN Cloudflare-blocked); abstract only"),
 dict(title="Do readers prefer AI-generated Italian short stories?",url=IT,kind="measurement",substantive=True,date="2026-01-24",route="curl on the arXiv abstract page; abstract only"),
 dict(title="Art or Artifice? Large Language Models and the False Promise of Creativity (CHI 2024)",url=AA,kind="measurement",substantive=True,date="2024-03-08",route="curl on the arXiv abstract page; abstract only"),
 dict(title="Can AI writing be salvaged? Mitigating Idiosyncrasies and Improving Human-AI Alignment (CHI 2025)",url=SV,kind="measurement",substantive=True,date="2025-03-04",route="curl on the arXiv abstract page; abstract only"),
 dict(title="Generative AI enhances individual creativity but reduces the collective diversity of novel content (Science Advances)",url=DO,kind="measurement",substantive=True,date="2024-07-12",route="science.org Cloudflare-blocked; full text via Europe PMC REST fullTextXML for PMC11244532"),
 dict(title="Editorial and Technical Review of 'Readers Prefer Outputs of AI Trained on Copyrighted Books...' (Zenodo, Zeus Dutta Roy)",url="https://zenodo.org/records/19553084",kind="analysis",substantive=False,date="2026-04-13",route="record page fetched; the PDF download returned 763 bytes and could not be read, so no claim is drawn from it"),
]
d["claims"]=C; d["sourcesRead"]=S
d["complete"]=True
d["coverage"]=("Named roster: all eleven items reached. Fetched at the primary — Winterson (Guardian 12 Mar 2025), Kudan/Qudan (Japan Times 19 Jan 2024, quoting the acceptance speech), Mark Lawrence's two 2023 posts, Sudowrite Muse, Jane Friedman (7 Aug 2023), the Authors Guild survey release (15 May 2023, after the briefed URL 404'd), Clarke's 'A Concerning Trend' (15 Feb 2023, at neil-clarke.com; clarkesworldmagazine.com/clarke_02_23/ serves a different editorial), NPR (24 Feb 2023) and Hern's TechScape (which is dated 16 April 2024, not May). "
 "Recovered by ladder — Vara's 'Ghosts' via the Wayback raw capture (Believer live is Cloudflare-blocked); Doshi and Hauser via Europe PMC full-text XML (science.org Cloudflare-blocked); the DriveThruRPG storefront-filter page via Wayback. Not found at the primary — the July 2023 OneBookShelf written-content ban text: help.drivethrurpg.com is Cloudflare-blocked with no Wayback capture of that article, so it is recorded as a relay through EN World quoting Gizmodo, and the only primary DriveThru text reached (Oct 2024) labels artwork only, not AI-written text. Blocked and unread — the SSRN version of the Chakrabarty/Ginsburg/Dhillon paper (arXiv used instead, abstract only) and the Zenodo critique PDF (763-byte download). "
 "Expansion: bibliography chasing through the CHI 2026 paper's reference list yielded four further primaries (Art or Artifice, Can AI writing be salvaged, Readers Prefer Outputs of AI Trained on Copyrighted Books, Doshi and Hauser); arXiv API relevance queries yielded two more (the Chakrabarty/Dhillon paper itself and Farrell's Italian study); a lateral route through Simon Willison's link blog recovered the correct Guardian TechScape URL. "
 "22 substantive sources: 11 from the named roster, 7 by bibliography chasing, 2 by arXiv API search, 2 recovered relays/leads. The WebSearch budget was exhausted mid-sweep, so the last expansion rounds used the arXiv, OpenAlex, Crossref-style and Europe PMC APIs and reference-list chasing instead of open lateral search. Standing gap unchanged: no source read here measured the archival, encyclopedic or civic-record register — every measurement is on lyric poetry, flash or short fiction, literary excerpts of 450 words or less, or biomedical article vocabulary.")
json.dump(d,open("found-ai-counter-cases.json","w"),indent=1,ensure_ascii=False)
print(len(d["claims"]),"claims",len(d["sourcesRead"]),"sources")
