import json,os
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/ai-04.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-ai-i314-328.json"
d=json.load(open(src))
V=[
{"index":314,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"arxiv.org/html/2503.02879v1 fetched raw (200, 397KB; header stamp arXiv:2503.02879v1 [cs.CL] 04 Mar 2025). Sec 5.2.2: 'the accuracy of responses based on ChatGPT-processed pages shows little change and responses based on Gemini-processed pages show a clear drop in accuracy' - quote verbatim, and Gemini-worse-than-GPT limb supported. Sec 5.2.3 bullet: 'Keyword Replacement and Omission: LLM might replace or omit key terms, altering the original meaning and causing misinterpretation.' Finding 5 generalises: 'LLM-processed content could perform less effectively in RAG systems compared to human-created texts.'"},
{"index":315,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"arxiv.org/html/2410.08044 fetched raw (200; stamp arXiv:2410.08044v1 [cs.CL] 10 Oct 2024, Brooks/Eggert/Peskoff, Princeton). Table 2 English row: footnotes per sentence 0.667 (AI-detected) vs 0.972 (all new); outgoing links per word 0.383 vs 1.77. Quote verbatim: 'AI-generated ones use fewer references and are less integrated into the Wikipedia nexus.' Note the four figures are the English row specifically (French/German/Italian rows differ); thresholds set to a 1% FPR."},
{"index":316,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Same page, Sec 5.2 Advertisement: 'Of the 45 flagged pages, we identify eight that were created to promote organizations such as small businesses, restaurants, or websites.' The estate page is one of them; moderator note quoted verbatim: 'Reference links are all dead apart from one for the town council, which makes no mention of the estate.' 45 = the articles flagged independently by both GPTZero and Binoculars, manually inspected."},
{"index":317,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Same page, abstract: 'With thresholds calibrated to achieve a 1% false positive rate on pre-GPT-3.5 articles, detectors flag over 5% of newly created English Wikipedia articles as AI-generated... Flagged Wikipedia articles are typically of lower quality and are often self-promotional...' Figure 1 pins the sample: 5% of 2,909 English articles created in August 2024. Quote verbatim."},
{"index":318,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"arxiv.org/html/2504.05711 fetched raw (200, 345KB; stamp arXiv:2504.05711v2). Sec 3.3: 'different LLMs could adopt different ways to tag these elements, and even the same LLM might use various tags at different time.' Quote verbatim. 'these elements' = descriptive elements of archival description standards generally; ISAD(G) is the standard the system and its evaluation use throughout (Table 1 lists the ISAD(G) areas/elements), so the ISAD(G) framing is fair but is the paper's context rather than that sentence's own words."},
{"index":319,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Same page, next sentence: 'although we use the LLMs, which are familiar with the archival description standards, they do not always strictly follow them, and the metadata descriptions created by LLMs could have different structures and elements at different times.' Quote verbatim; the LLM Instructor agent retrieves the standard's spec and builds the instructions (Sec 3.1), so 'they were prompted with' is supported."},
{"index":320,"verdict":"PARTIAL","trueWording":"federated output more complete than ground truth, scored lower","unsupportedLimb":"'more than the record asked for' - the paper says ISAD(G)'s Extent element asks for size AND format, so the extra was beyond the archivist ground truth, not beyond the standard","note":"Sec 4: 'according to the ISAD(G) specification, the element Id:Extent describes the physical or digital size and format of the unit. For the element, our federated approach creates its content as \"3 pages, digital document (PDF)\", while the ground truth is only \"3 pages\". Obviously, the content created by the federated approach is more complete than the ground truth.' Quote verbatim and the ground-truth contrast verbatim, but the paper's own reading is the opposite of 'unasked-for detail': it says the federated approach 'adheres to the archiving standards more strictly' and was penalised by the metric for it."},
{"index":321,"verdict":"VERIFIED_SUBSTANCE","trueWording":"tendency for slightly decreasing scores for larger documents","note":"Same page, Sec 4 (Figure 5 discussion): 'Looking at the overall score for the whole metadata descriptions, we see a tendency for slightly decreasing scores for larger documents (ignoring the outliers with low scores for smaller documents).' Claim carries no quote string, so graded on substance; wording matches almost word for word."},
{"index":322,"verdict":"VERIFIED_SUBSTANCE","trueWording":"55% of GPT-3.5 and 18% of GPT-4 citations fabricated","note":"pmc.ncbi.nlm.nih.gov/articles/PMC10484980/ fetched raw with a browser UA (200, 175KB; Sci Rep 2023;13:14045, Walters & Wilder). Abstract: '55% of the GPT-3.5 citations but just 18% of the GPT-4 citations are fabricated.' Table 3 chapters row: 70% (10) for GPT-3.5 and 70% (23) for GPT-4; text: 'Even with GPT-4, however, 70% of the cited book chapters are fabricated.' Claim carries no quote string, so graded on substance."},
{"index":323,"verdict":"VERIFIED_SUBSTANCE","trueWording":"43% GPT-3.5, 24% GPT-4 real citations had substantive errors","note":"Same page, abstract: '43% of the real (non-fabricated) GPT-3.5 citations but just 24% of the real GPT-4 citations include substantive citation errors.' Results: 'More than a third of the articles have incorrect volume, issue, or page numbers, and 22% of the cited works have incorrect dates (years)'; Table 4 confirms volume/issue/page (34% / 13%) and date (22% / 16%) as the two largest error categories, so 'mostly volume/issue/pages and years' holds. No quote string supplied."},
{"index":324,"verdict":"PARTIAL","trueWording":"fabricated citations include names of real journals and publishers","unsupportedLimb":"'authentic-sounding authors and plausible titles' - the paper never assesses author or title plausibility in fabricated citations","note":"Same page. Supported: 'most of the fabricated article, book, and website citations include the names of real journals, publishers, and organizations' (Table 3: journal fabricated in only 2% of fabricated article citations). Also supported, though hedged: 'Bibliographic problems may persist to the extent that citations are treated as regular text rather than a type of text for which special processing is required.' Not supported: the authors/titles limb. The nearest text is 'ChatGPT's fabricated citations tend to look legitimate at first glance', which the paper attributes to refs 13 and 28, not to its own data; its own author/title figures (Table 4) cover only the REAL citations. The paper's own conjecture also runs the other way - it suspects ChatGPT 'may attempt to recognize bibliographic citations and to treat them differently than regular text'."},
{"index":325,"verdict":"VERIFIED_SUBSTANCE","trueWording":"64 of 141 real citations (45.4%) contained errors","note":"pmc.ncbi.nlm.nih.gov/articles/PMC12658395/ fetched raw with a browser UA (200, 162KB; JMIR Ment Health 2025;12:e80371, Linardon et al.). Abstract: 'Among the 141 real citations, 64 (45.4%) contained errors, most frequently incorrect or invalid digital object identifiers.' Table 1 'Error type' block, combined column: DOI 51/135 (37.8), Page 39/131 (29.8) - denominators vary because elements absent from a citation were excluded. No quote string supplied."},
{"index":326,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"arxiv.org/html/2602.05930 fetched raw (200, 141KB; stamp arXiv:2602.05930v1 [cs.DL] 05 Feb 2026, Ansari). Table 1 (primary codes, N=100): Total Fabrication 66 (66.0%), Partial Attribute Corruption 27 (27.0%), Identifier Hijacking 4 (4.0%), Placeholder Hallucination 2 (2.0%), Semantic Hallucination 1 (1.0%). Quote appears as 'The citation has zero overlap with any real scholarly work' (capitalisation of the leading word aside). Citations are the hallucinated ones found in 53 NeurIPS 2025 accepted papers."},
{"index":327,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Same page, Sec 2.2 category 2: 'Partial Attribute Corruption (PAC): The citation blends real and fabricated elements. This includes: real authors attributed to papers they did not write; real paper titles with fabricated authors; correct venues with wrong publication years...' Quote verbatim (leading capital aside); both halves of the claim - real authors on papers they did not write, real titles with fabricated authors - are the first two items."},
{"index":328,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Same page, Sec 2.2 category 5: 'Placeholder Hallucination (PH): The citation contains obvious generation failures such as template variables (\"Firstname Lastname\"), incomplete identifiers (\"arXiv:2305.XXXX\"), or placeholder text (\"To appear\").' Table 2 gives the live instance: 'Firstname Lastname and Others. Drivlme: A large-scale multi-agent driving benchmark, 2023. URL or arXiv ID to be updated.' These citations are drawn from ACCEPTED NeurIPS 2025 papers, so 'survive into the submitted record' is supported. Quote verbatim."},
]
assert [v["index"] for v in V]==d["indices"], "index mismatch"
json.dump({"name":"ai","chunk":4,"claims":d["claims"],"verdicts":V},open(out,"w"),indent=1)
print("wrote",out,os.path.getsize(out))
