import json
src="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/chunks/dnd-04.json"
out="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-dnd-i109-123.json"
d=json.load(open(src,encoding='utf-8'))
V=[
 {"index":109,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Rule 8: Write without assumption of perspective.",
  "note":"Raw HTML fetched (200) from baatag.blogspot.com, Misha F, Tue 28 Apr 2026. Quote is the verbatim Rule 8 heading. Entry-point limb: 'I have no way of knowing which door the players are entering a room from'. Direction limb: 'When I do describe a door, I describe it as being on the east or north wall, not the far or right one' - i.e. 'east or north wall' / 'the far or right one', not literally 'east wall'/'far side'. Author's own caveat, on the same page: the GM 'will probably need to strip out all of that directional information', and in a later retrospective he admits describing a throne as being at the 'far end'."},
 {"index":110,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Keep the descriptions short and punchy.",
  "note":"Raw HTML fetched (200) from dungeons.hismajestytheworm.games chapter 10; authorship (Josh McCrowell & Warren D.) confirmed from chapter 1's 'Who are the authors?'. All four limbs present as axiom headings: 'Keep the descriptions short and punchy'; \"Don't tell the players what to feel\"; \"Don't assume the players' pathing\" - \"Writing down terms like 'the door to the right' will become confusing... Instead, use cardinal directions\" (page says 'cardinal directions', not literally 'east/west'); 'Let the map work for you' - 'assuming each exit on the map is standard, you can avoid repetitive descriptions of all the doors in a room'."},
 {"index":111,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"\"Don't address the party directly in read-aloud\" (noisician comment).",
  "note":"Raw HTML fetched (200) from into-the-dark-rpg.blogspot.com. Claim carries no quote field; all three limbs appear near-verbatim in the comment by 'noisician', 30 Dec 2022: 'Don't give conclusions, just describe and let the players come to their own conclusions'; \"Don't use 'if/then' constructs. I think this is mainly because it tends to be filler... 'if/then' phrasing could be used to pad almost anything, but shouldn't\"; \"Don't address the party directly in read-aloud, this typically takes decision making away from the players.\" Accurately located in the comments, not the post body (matches the claim's page field); it is one commenter, not 'readers' plural, and post author Jon Miller only replies 'thanks for the suggested additions'."},
 {"index":112,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"If the agents reach the safe house, Keletny burns the car.",
  "note":"Raw HTML fetched (200) from pelgranepress.com; byline 'By Robin D. Laws', posted February 1, 2012. Section 'Deprecation of the \"will\"' gives the before/after pair verbatim: 'Keletny will burn the car' -> 'Keletny burns the car', with 'In this construction, \"will\" is totally unnecessary, and thus deadens the sentence's impact.' Passive limb: section 'Passive Voice' - 'Avoid the passive voice'. 'to be' + verb limb: section 'Weak Verbs' - 'reconfigure to drop the \"to be\" and rely entirely on the more vivid paired verb.'"},
 {"index":113,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Covers 'avoiding rampant capitalization', 'using present tense instead of future tense'.",
  "note":"Raw HTML fetched (200) from rayvallese.com. Both quoted strings appear word for word in one sentence: 'It covers such topics as using gender-neutral language, ... avoiding rampant capitalization, ... using present tense instead of future tense, changing passive voice to active voice...'. The 'editor corrects common RPG-manuscript habits' limb is supported ('the most common and easily fixable issues... in more than 20 years of editing and writing games'). Framing caveat: the page lists these as topics the 45-page guide 'covers', never as named 'sections'; a quoted five-star review on the same page does refer to 'Each section', so section structure is inference, not statement."},
 {"index":114,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Tip 3. Describe everything the characters can sense, but not what they cannot.",
  "note":"Raw HTML fetched (200) from critical-hits.com; byline 'August 27, 2010 by Shawn Merwin'. Quote is the verbatim Tip 3 heading. Chasm limb: 'the boxed text fails to mention something apparent, like the 50-foot-wide chasm between the doorway and the altar' (page says '50-foot-wide'). Crate limb: 'They enter a room full of closed crates, and the boxed text describes... the \"large crates full of mining equipment.\" The characters couldn't know that without opening them.'"},
 {"index":115,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"If something \"appears to be\" to the characters, it \"is\" to the characters.",
  "note":"Same raw page as 114. Tip 4 heading is 'Avoid \"seems to be\" or \"appears to be.\"' Telegraphing limb verbatim: 'Nothing triggers meta-gaming like the words \"seems\" or \"appears\"... Those words generally mean that some trick or diversion is in the offing.' Perception limb verbatim: 'Let those Perception or Spot checks separate the \"seems\" from the \"is\".' Note the claim's quotation is a truncation - the page's sentence ends 'it \"is\" to the characters', and the following sentence ('perception has to equal reality for the characters') is the point the truncation clips."},
 {"index":116,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Unless you happen to be DMing for a party comprised solely of elves or florists.",
  "note":"Same raw page as 114 (Tip 2a, 'It was a dark and stormy night'). Quote verbatim in: 'The smell of flowers in the sunny glade can probably be left out, unless you happen to be DMing for a party comprised solely of elves or florists.' Relevance-filter limb verbatim: 'My rule of thumb when writing or editing is to leave in only the details about the environment that the PCs need to know about because they will have to interact with them.' The Chekhov framing is corroborated in the same page's comments, where Merwin endorses a reader's 'Checkov's gun' paraphrase."},
 {"index":117,"verdict":"PARTIAL",
  "unsupportedLimb":"the flat bans - 'no evil soliloquies, no coronation cutscenes'; Merwin explicitly permits both, reworked as interactive scenes, rather than prohibiting them",
  "trueWording":"'I can give this one a bit of a pass sometimes'; 'If your players are into it, great. Let 'er rip.'",
  "note":"Same raw page as 114. The quotation is verbatim - 'Tip 2. Avoid the novelist/dramatist urge.' - and 2b 'The villain's soliloquy' and 2c 'The action in progress' (the saved prince's coronation) are the page's own named sub-problems, so the subject matter is right. The final limb is verbatim too: 'find a way to keep the passages short, and give the PCs the chance to interact with the scene in some way'. But the claim converts caveated discouragement into prohibition. On the soliloquy the page says 'I can give this one a bit of a pass sometimes' and prescribes a compromise ('instead of having the evil guy do the soliloquy, let him talk with the characters interactively'); on the coronation it says 'If your players are into it, great. Let 'er rip.' Restate as: keep the novelist's urge out of boxed text - make the soliloquy interactive and the ceremony short and playable."},
 {"index":119,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Go for the telltale sensory detail, rather than the generic abstract trait.",
  "note":"Raw HTML fetched (200) from into-the-dark-rpg.blogspot.com. Quote verbatim in tip 21, which continues 'Show, don't tell.' Example verbatim: 'Instead of stating \"One of the guards in the camp is a cruel bully,\" say \"The burly Manfred takes a leak on Tobias's bedroll, and then snatches Tobias's roasted chicken from his hand and quickly gobbles it down.\"' Specificity limb is on the page but in the comments, not the numbered list: Clever Munkey, 22 Apr 2021 - 'Things should be specific not abstract. Try for specificity not simply detail' - which Jon Miller endorses ('Bryce talks a lot about this'). Only unsupported word is the claim's own flourish 'most-cited', a superlative about the wider hobby that this page neither states nor could state; it attributes nothing extra to the source."},
 {"index":120,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Language: 4 - Succinct and evocative; 'Boxed text is usually not a good thing.'",
  "note":"Raw HTML fetched (200) from tenfootpole.org 'Review Standards', bylined Bryce Lynch. The Language rubric has exactly four rungs - '4 - Succinct and evocative / 2 - Conversational but clear / 1 - You should have hired an English Major to edit this / 0 - Very wordy/ incomprehensible'. 'Evocative atmosphere.' and 'Terse writing style' are consecutive verbatim bullets, and 'Boxed text is usually not a good thing.' is a verbatim bullet in the same list. Framing caveat: the page introduces that list as 'What I'm looking for in an adventure module', and opens 'I try to avoid giving a module a rating' - 'requirements' is the claim's word, not Lynch's."},
 {"index":121,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"it's not the overwritten fantasy drivil that is present in most read aloud",
  "note":"Raw HTML fetched (200) from tenfootpole.org ?p=5395, page title '(5e) Death in the Wood'. Quote verbatim, including Lynch's misspelling 'drivil'. Social-scene limb verbatim: 'The read-aloud tends to be describing a social interaction though, as if you just walked up on something happening. It's also pretty well written, which I don't think I've said more than three or four times?... It does a good job of communicating the social vibe going on.' The praise is qualified in the same sentence - 'It's still too long and the players are almost certainly going to be playing with their phones' - so 'praises' should not be read as an unqualified recommendation of the adventure."},
 {"index":122,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"Every sentence needs to fight for its life in a dungeon key.",
  "note":"Raw HTML fetched (200) from coinsandscrolls.blogspot.com, 2019/09/05, 'Posted by Skerples'. Quote verbatim, continuing 'Evoke. Make it visceral. Make it real.' Filler limb verbatim, from the copy-editing section later in the same post: 'Use find and replace to locate common \"filler\" words: little, big, grand, tall, dark, etc. Everyone has their own bugbears. Replace with evocative choices.' The two halves of the claim come from different sections of the one post."},
 {"index":123,"verdict":"VERIFIED_VERBATIM",
  "trueWording":"An idol shouldn't be described as \"evil\"... rather it has a \"toothy glare\" or is \"sharp edged obsidian\".",
  "note":"Raw HTML fetched (200) from alldeadgenerations.blogspot.com, Monday 19 Dec 2022, Gus L. Quote verbatim under \"a. Don't generalize: Describe specifics.\" Senses limb: 'there is advice to remember that senses other than sight exist: smells, sounds, and sensation etc. This old advice to include other senses is still good' - with the page's own qualifier that following it too far yields bloated keys. Prohibitions limb: section 7 gives \"a. Don't describe the room's past\" and \"b. Don't describe the room's future\" verbatim; emotions come from a separate heading, section 10, \"Don't Tell the Characters How to Feel!\" ('the referee, let alone the designer, doesn't get to control the internal mental state of the characters'). Section 7's third item is \"Don't describe what might be happening\", not emotions."},
]
byidx={v["index"]:v for v in V}
order=[c["index"] for c in d["claims"]]
assert sorted(order)==sorted(byidx), (order, sorted(byidx))
res={"name":"dnd","chunk":4,"claims":d["claims"],"verdicts":[byidx[i] for i in order]}
json.dump(res,open(out,'w',encoding='utf-8'),indent=1,ensure_ascii=False)
print("wrote",out,len(res["verdicts"]))
