# -*- coding: utf-8 -*-
COMPLETE = False
COVERAGE = "In progress after 13 sources: named roster partly fetched (Guardian/Flood primary, Tolkien Society relay, Pembroke lecture report, Olley's two Oxford talks with their .srt transcripts, Locus Dunnett attribution, Slightly Foxed Dunnett criticism). Still owed: the Tolkien Lecture's own text, reviews of Beyond This Dark House, and Dunnett Society material."
SOURCES = [
 dict(title="Guy Gavriel Kay: 'I learned a lot about false starts from JRR Tolkien' (interview by Alison Flood)", url="https://www.theguardian.com/books/2014/oct/29/guy-gavriel-kay-jrr-tolkien-interview-fionovar-tapesty-the-summer-tree", kind="own-words", substantive=True, date="2014-10-29", route="live URL, browser user agent (curl)"),
 dict(title="Interview with Alison Flood for The Guardian (authorized reproduction of the same interview)", url="https://brightweavings.com/interview-with-alison-flood-for-the-guardian/", kind="own-words", substantive=True, date="2017-07-11 (posting of the 2014 interview)", route="live URL, browser user agent (curl)"),
 dict(title="Guy Gavriel Kay describes working on The Silmarillion as 'quietly exhilarating'", url="https://www.tolkiensociety.org/2014/10/guy-gavriel-kay-describes-working-on-the-silmarillion-as-quietly-exhilarating/", kind="relay", substantive=False, date="2014-10-29", route="live URL (relay of the Guardian; primary fetched separately)"),
 dict(title="Just Enough Light: Guy Gavriel Kay Delivers JRR Tolkien Lecture", url="https://www.pmb.ox.ac.uk/news/just-enough-light-guy-gavriel-kay-delivers-jrr-tolkien-lecture", kind="reception", substantive=True, date="2021-05-20", route="live URL, browser user agent (curl)"),
 dict(title="'Just Enough Light: Some Thoughts on Fantasy and Literature,' the 2021 Tolkien Lecture by Guy Gavriel Kay", url="https://apilgriminnarnia.com/2021/05/20/2021-tolkien-lecture-by-guy-gavriel-kay/", kind="reception", substantive=False, date="2021-05-20", route="live URL (announcement and framing only; no lecture content)"),
 dict(title="Guy Gavriel Kay Lecture Recording", url="https://tolkienlecture.org/2021/05/14/guy-gavriel-kay-lecture-recording/", kind="reception", substantive=False, date="2021-05-14", route="live URL (pointer to the YouTube recording; no text)"),
 dict(title="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction' (University of Oxford / Great Writers Inspire)", url="https://writersinspire.org/content/guy-gavriel-kay-short-introduction", kind="analysis", substantive=True, date="2020-12-16", route="page, then the linked auto-generated .srt at media.podcasts.ox.ac.uk/engfac/fantasy_lit/introduction-guy-gavriel-kaydefault.srt"),
 dict(title="Katherine Olley, 'Verse and Prose in Fantasy Literature' (University of Oxford / Great Writers Inspire)", url="https://writersinspire.org/content/verse-prose-fantasy-literature", kind="analysis", substantive=True, date="2020-12-16", route="page, then the linked .srt at media.podcasts.ox.ac.uk/engfac/fantasy_lit/verse-and-prose-fantasy-literaturedefault.srt"),
 dict(title="Questions and Answers on Beyond this Dark House (Penguin Canada Q&A with Guy Gavriel Kay)", url="https://brightweavings.com/books/books/beyond-this-dark-house/", kind="own-words", substantive=True, date="2003", route="live URL, browser user agent (curl)"),
 dict(title="Christine Fischer Guy, 'The Fantastic Worlds of Guy Gavriel Kay'", url="https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/", kind="own-words", substantive=True, date="2016-08-14", route="live URL, browser user agent (curl)"),
 dict(title="Guy Gavriel Kay: Margins of History (Locus interview)", url="https://locusmag.com/feature/guy-gavriel-kay-margins-of-history/", kind="own-words", substantive=True, date="2025", route="live URL, browser user agent (curl)"),
 dict(title="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81", url="https://foxedquarterly.com/niall-allsopp-dorothy-dunnett-literary-review/", kind="analysis", substantive=True, date="2024", route="live URL, browser user agent (curl)"),
 dict(title="BrightWeavings: Professional Scholarship index", url="https://brightweavings.com/scholarship/professional-scholarship/", kind="analysis", substantive=False, date="accessed 2026-09-06", route="live URL (bibliography chasing; no Silmarillion, verse or Dunnett entry)"),
]

SOURCES += [
 dict(title="John D. Rateliff, 'Kay and Christopher' (Sacnoth's Scriptorium)", url="http://sacnoths.blogspot.com/2020/02/kay-and-christopher.html", kind="analysis", substantive=True, date="2020-02-06", route="live URL, browser user agent (curl)"),
 dict(title="John D. Rateliff, 'Charles Noad comments (was Christopher's Masterpiece)' (Sacnoth's Scriptorium), with Noad's letter and comment thread", url="https://sacnoths.blogspot.com/2020/01/charles-noad-comments-was-christophers.html", kind="analysis", substantive=True, date="2020-01-27", route="live URL, browser user agent (curl)"),
 dict(title="Douglas C. Kane interviewed about Arda Reconstructed (TheOneRing.net)", url="https://www.theonering.com/douglas-kane-talks-about-arda-reconstructed/", kind="analysis", substantive=True, date="2009", route="live URL, browser user agent (curl)"),
 dict(title="Interview with Douglas C. Kane about Arda Reconstructed (Tolkien Library)", url="https://tolkienlibrary.com/press/873-arda-reconstructed-interview.php", kind="analysis", substantive=False, date="2009", route="live URL (names Kay's assisting role; no further detail)"),
 dict(title="Holly Ordway, review of Arda Reconstructed (The Mythopoeic Society)", url="https://www.mythsoc.org/reviews/arda-reconstructed-ordway.htm", kind="reception", substantive=True, date="2009", route="live URL, browser user agent (curl)"),
 dict(title="Matthew Rettino, 'Fantasies of History: Guy Gavriel Kay's Synthesis of the Historical Fantasy Novel' (2012 McGill honours thesis)", url="https://brightweavings.com/fantasies-of-history-guy-gavriel-kays-synthesis-of-the-historical-fantasy-novel/", kind="analysis", substantive=True, date="2012 (posted 2015-07-19)", route="live URL, browser user agent (curl)"),
 dict(title="Holly Ordway, 'The World-Building of Guy Gavriel Kay'", url="https://brightweavings.com/worldbuilding/", kind="analysis", substantive=True, date="1998", route="live URL, browser user agent (curl)"),
 dict(title="Matthew Rettino, review of Beyond this Dark House", url="https://matthewrettino.com/2014/02/07/beyond-this-dark-house-by-guy-gavriel-kay/", kind="reception", substantive=True, date="2014-02-07", route="live URL, browser user agent (curl)"),
 dict(title="The Writers' Writer (Dorothy Dunnett Centenary, Dorothy Dunnett Society) - contributions by Marie Macpherson, Ellen Kushner, Gwyneth Hughes, Guy Gavriel Kay and others", url="https://dunnettcentral.org/centenary/the-writers-writer/", kind="analysis", substantive=True, date="2023 centenary collection", route="live URL 403; Wayback raw capture https://web.archive.org/web/20240616085027id_/https://dunnettcentral.org/centenary/the-writers-writer/"),
]
COVERAGE = "In progress after 22 sources across all three angles."

SOURCES += [
 dict(title="Guy Gavriel Kay, 'In Memoriam - Dorothy Dunnett' (Locus Magazine, December 2001)", url="https://brightweavings.com/dunnett/", kind="own-words", substantive=True, date="2001-12", route="live URL, browser user agent (curl)"),
 dict(title="Guy Gavriel Kay, 'The Fionavar Tapestry Afterword' (HarperPerennial Canada 20th anniversary edition)", url="https://brightweavings.com/fionavarafterword/", kind="own-words", substantive=True, date="2003-12", route="live URL, browser user agent (curl)"),
 dict(title="Dorothy Dunnett Society, 'Dorothy Dunnett' biography page", url="https://dunnettcentral.org/dorothy", kind="vendor", substantive=True, date="accessed via Wayback capture 2025-08-19", route="live URL 403; Wayback raw capture 20250819090027id_"),
 dict(title="Dorothy Dunnett Society, Whispering Gallery (magazine contents, Issue 166)", url="https://dunnettcentral.org/whisperinggallery", kind="vendor", substantive=True, date="2025-06 issue description", route="live URL 403; Wayback raw capture 20250814193009id_"),
 dict(title="Lisa L. Spangenberg, 'The Books of Dorothy Dunnett' (Digital Medievalist / Celtic Studies Resources)", url="https://www.digitalmedievalist.com/reading-lists/dorothy-dunnett/", kind="reader", substantive=True, date="undated, post-2001", route="live URL, browser user agent (curl)"),
 dict(title="bill, 'The Play for Jonathan Crouch - III. More Blindfold Play' (Bill's Dunnett Blog)", url="https://www.dorothydunnett.co.uk/blog/lymond-reading-notes/the-play-for-jonathan-crouch-iii-more-blindfold-play.php", kind="reader", substantive=True, date="2026-07-09", route="live URL, browser user agent (curl)"),
 dict(title="bill, 'The Play for Jonathan Crouch - IV: Several Moves by a Knight' (Bill's Dunnett Blog)", url="https://www.dorothydunnett.co.uk/blog/lymond-reading-notes/the-play-for-jonathan-crouch-iv-several-moves-by-a-knight.php", kind="reader", substantive=True, date="2026-08-05", route="live URL, browser user agent (curl)"),
 dict(title="bill, 'The Play for Jonathan Crouch - V: Castling' (Bill's Dunnett Blog)", url="https://www.dorothydunnett.co.uk/blog/lymond-reading-notes/the-play-for-jonathan-crouch-v-castling.php", kind="reader", substantive=True, date="2026-08-21", route="live URL, browser user agent (curl)"),
 dict(title="The Dorothy Dunnett Society (dorothydunnett.co.uk society page)", url="https://www.dorothydunnett.co.uk/dds.php", kind="vendor", substantive=False, date="accessed 2026-09-06", route="live URL (society description only)"),
 dict(title="Cheryl Morgan, 'Guy Kay's Tolkien Lecture' (Cheryl's Mewsings)", url="https://www.cheryl-morgan.com/?p=28717", kind="reception", substantive=False, date="2021-05", route="live URL (three sentences plus the embedded video; no lecture content)"),
 dict(title="Guy Gavriel Kay Lecture Recording / May 2021 archive (tolkienlecture.org)", url="https://tolkienlecture.org/2021/05/", kind="reception", substantive=False, date="2021-05-14", route="live URL (used for bibliography chasing to the write-ups)"),
 dict(title="Guy Gavriel Kay, 'Just Enough Light: Some Thoughts on Fantasy and Literature' (2021 Tolkien Lecture recording)", url="https://www.youtube.com/watch?v=z1TgX0alFuM", kind="own-words", substantive=False, date="2021-05-11", route="BLOCKED: caption track located in the page payload but every fetch of the timedtext endpoint returned HTTP 429; no published transcript found. Lecture content reached only through the Pembroke College report."),
 dict(title="Andrew Liptak write-up of the Kay Tolkien Lecture (Tor.com)", url="https://www.tor.com/2021/05/13/jrr-tolkien-guy-gavriel-kay-lecture-just-enough-light-some-thoughts-on-fantasy-and-literature-watch/", kind="reception", substantive=False, date="2021-05-13", route="BLOCKED: HTTP 403 on the live URL"),
 dict(title="'That Private Labyrinth': The Books that made Dorothy Dunnett's Lymond, Whispering Gallery 134", url="https://www.academia.edu/30197812/That_Private_Labyrinth_The_Books_that_made_Dorothy_Dunnetts_Lymond_Whispering_Gallery_134_March_2017_20_27", kind="analysis", substantive=False, date="2017-03", route="BLOCKED: HTTP 403 (academia.edu login wall)"),
 dict(title="Matthew Rettino, 'History as Fantasy' / brightweavings essay and category indexes used for bibliography chasing", url="https://brightweavings.com/category/ggks-words/essays/", kind="analysis", substantive=False, date="accessed 2026-09-06", route="live URL (index paged 1-6 to find the Dunnett memorial and the Fionavar afterword)"),
]
COMPLETE = True
COVERAGE = ("Named roster: FETCHED - the Guardian/Alison Flood interview at the primary (the Tolkien Society page proved a relay of it); Pembroke College's report of the 2021 Tolkien Lecture; "
 "Katherine Olley's two Oxford talks, both read as their linked .srt transcripts rather than as page blurbs; the Locus 'Margins of History' interview carrying Kay's Dunnett attribution; "
 "Dorothy Dunnett Society material (the centenary 'Writers' Writer' collection, the Society biography, the Whispering Gallery contents) via Wayback raw captures after 403s; and Kay's own Locus 'In Memoriam - Dorothy Dunnett', "
 "which turned out to join angles 1 and 3 - he met Dunnett in spring 1975 through a letter found inside the Tolkien correspondence he was editing. "
 "NOT FOUND: no published text or transcript of 'Just Enough Light' exists that I could locate; no review of Beyond This Dark House in a national outlet survives online beyond Rettino's. "
 "BLOCKED: the lecture's own YouTube caption track (HTTP 429 on every timedtext fetch, twice, spaced apart), Tor.com's write-up (403), and the academia.edu Whispering Gallery paper (403 login wall); "
 "the WebSearch budget for this session was exhausted mid-sweep and DuckDuckGo served a CAPTCHA, so the last third of discovery ran on bibliography chasing alone. "
 "Substantive sources per route: 12 by the named roster, 11 by bibliography chasing (Sacnoth's Scriptorium from a Kane search, then Noad from Rateliff; the brightweavings essay index paged to depth 6, which yielded the Dunnett memorial and the Fionavar afterword; "
 "tolkienlecture.org's write-up list; Olley's .srt files from her page), 5 by Wayback recovery, 3 by lateral search. 31 sources read, 25 substantive, 113 claims, every quotation checked verbatim against the fetched text by script. "
 "Angle 1's third limb is the thinnest: no source I found argues explicitly that the Quenta and the Annals are the ancestor of Kay's historian-narrator; the nearest real connectors are Charles Noad's claim that Kay's contribution was the making of a finished narrative out of annalistic materials, "
 "and Rettino's independent finding that Kay's narrator speaks as a chronicler. I have not bridged them myself.")
