# -*- coding: utf-8 -*-
COMPLETE = False
COVERAGE = "In progress after 13 sources: named roster partly fetched (Guardian/Flood primary, Tolkien Society relay, Pembroke lecture report, Olley's two Oxford talks with their .srt transcripts, Locus Dunnett attribution, Slightly Foxed Dunnett criticism). Still owed: the Tolkien Lecture's own text, reviews of Beyond This Dark House, and Dunnett Society material."
SOURCES = [
 dict(title="Guy Gavriel Kay: 'I learned a lot about false starts from JRR Tolkien' (interview by Alison Flood)", url="https://www.theguardian.com/books/2014/oct/29/guy-gavriel-kay-jrr-tolkien-interview-fionovar-tapesty-the-summer-tree", kind="own-words", substantive=True, date="2014-10-29", route="live URL, browser user agent (curl)"),
 dict(title="Interview with Alison Flood for The Guardian (authorized reproduction of the same interview)", url="https://brightweavings.com/interview-with-alison-flood-for-the-guardian/", kind="own-words", substantive=True, date="2017-07-11 (posting of the 2014 interview)", route="live URL, browser user agent (curl)"),
 dict(title="Guy Gavriel Kay describes working on The Silmarillion as 'quietly exhilarating'", url="https://www.tolkiensociety.org/2014/10/guy-gavriel-kay-describes-working-on-the-silmarillion-as-quietly-exhilarating/", kind="relay", substantive=False, date="2014-10-29", route="live URL (relay of the Guardian; primary fetched separately)"),
 dict(title="Just Enough Light: Guy Gavriel Kay Delivers JRR Tolkien Lecture", url="https://www.pmb.ox.ac.uk/news/just-enough-light-guy-gavriel-kay-delivers-jrr-tolkien-lecture", kind="reception", substantive=True, date="2021-05-20", route="live URL, browser user agent (curl)"),
 dict(title="'Just Enough Light: Some Thoughts on Fantasy and Literature,' the 2021 Tolkien Lecture by Guy Gavriel Kay", url="https://apilgriminnarnia.com/2021/05/20/2021-tolkien-lecture-by-guy-gavriel-kay/", kind="reception", substantive=False, date="2021-05-20", route="live URL (announcement and framing only; no lecture content)"),
 dict(title="Guy Gavriel Kay Lecture Recording", url="https://tolkienlecture.org/2021/05/14/guy-gavriel-kay-lecture-recording/", kind="reception", substantive=False, date="2021-05-14", route="live URL (pointer to the YouTube recording; no text)"),
 dict(title="Katherine Olley, 'Guy Gavriel Kay: A Short Introduction' (University of Oxford / Great Writers Inspire)", url="https://writersinspire.org/content/guy-gavriel-kay-short-introduction", kind="analysis", substantive=True, date="2020-12-16", route="page, then the linked auto-generated .srt at media.podcasts.ox.ac.uk/engfac/fantasy_lit/introduction-guy-gavriel-kaydefault.srt"),
 dict(title="Katherine Olley, 'Verse and Prose in Fantasy Literature' (University of Oxford / Great Writers Inspire)", url="https://writersinspire.org/content/verse-prose-fantasy-literature", kind="analysis", substantive=True, date="2020-12-16", route="page, then the linked .srt at media.podcasts.ox.ac.uk/engfac/fantasy_lit/verse-and-prose-fantasy-literaturedefault.srt"),
 dict(title="Questions and Answers on Beyond this Dark House (Penguin Canada Q&A with Guy Gavriel Kay)", url="https://brightweavings.com/books/books/beyond-this-dark-house/", kind="own-words", substantive=True, date="2003", route="live URL, browser user agent (curl)"),
 dict(title="Christine Fischer Guy, 'The Fantastic Worlds of Guy Gavriel Kay'", url="https://lareviewofbooks.org/article/fantastic-worlds-guy-gavriel-kay/", kind="own-words", substantive=True, date="2016-08-14", route="live URL, browser user agent (curl)"),
 dict(title="Guy Gavriel Kay: Margins of History (Locus interview)", url="https://locusmag.com/feature/guy-gavriel-kay-margins-of-history/", kind="own-words", substantive=True, date="2025", route="live URL, browser user agent (curl)"),
 dict(title="Niall Allsopp, 'Dorothy Dunnett's Lymond Chronicles', Slightly Foxed Issue 81", url="https://foxedquarterly.com/niall-allsopp-dorothy-dunnett-literary-review/", kind="analysis", substantive=True, date="2024", route="live URL, browser user agent (curl)"),
 dict(title="BrightWeavings: Professional Scholarship index", url="https://brightweavings.com/scholarship/professional-scholarship/", kind="analysis", substantive=False, date="accessed 2026-09-06", route="live URL (bibliography chasing; no Silmarillion, verse or Dunnett entry)"),
]

SOURCES += [
 dict(title="John D. Rateliff, 'Kay and Christopher' (Sacnoth's Scriptorium)", url="http://sacnoths.blogspot.com/2020/02/kay-and-christopher.html", kind="analysis", substantive=True, date="2020-02-06", route="live URL, browser user agent (curl)"),
 dict(title="John D. Rateliff, 'Charles Noad comments (was Christopher's Masterpiece)' (Sacnoth's Scriptorium), with Noad's letter and comment thread", url="https://sacnoths.blogspot.com/2020/01/charles-noad-comments-was-christophers.html", kind="analysis", substantive=True, date="2020-01-27", route="live URL, browser user agent (curl)"),
 dict(title="Douglas C. Kane interviewed about Arda Reconstructed (TheOneRing.net)", url="https://www.theonering.com/douglas-kane-talks-about-arda-reconstructed/", kind="analysis", substantive=True, date="2009", route="live URL, browser user agent (curl)"),
 dict(title="Interview with Douglas C. Kane about Arda Reconstructed (Tolkien Library)", url="https://tolkienlibrary.com/press/873-arda-reconstructed-interview.php", kind="analysis", substantive=False, date="2009", route="live URL (names Kay's assisting role; no further detail)"),
 dict(title="Holly Ordway, review of Arda Reconstructed (The Mythopoeic Society)", url="https://www.mythsoc.org/reviews/arda-reconstructed-ordway.htm", kind="reception", substantive=True, date="2009", route="live URL, browser user agent (curl)"),
 dict(title="Matthew Rettino, 'Fantasies of History: Guy Gavriel Kay's Synthesis of the Historical Fantasy Novel' (2012 McGill honours thesis)", url="https://brightweavings.com/fantasies-of-history-guy-gavriel-kays-synthesis-of-the-historical-fantasy-novel/", kind="analysis", substantive=True, date="2012 (posted 2015-07-19)", route="live URL, browser user agent (curl)"),
 dict(title="Holly Ordway, 'The World-Building of Guy Gavriel Kay'", url="https://brightweavings.com/worldbuilding/", kind="analysis", substantive=True, date="1998", route="live URL, browser user agent (curl)"),
 dict(title="Matthew Rettino, review of Beyond this Dark House", url="https://matthewrettino.com/2014/02/07/beyond-this-dark-house-by-guy-gavriel-kay/", kind="reception", substantive=True, date="2014-02-07", route="live URL, browser user agent (curl)"),
 dict(title="The Writers' Writer (Dorothy Dunnett Centenary, Dorothy Dunnett Society) - contributions by Marie Macpherson, Ellen Kushner, Gwyneth Hughes, Guy Gavriel Kay and others", url="https://dunnettcentral.org/centenary/the-writers-writer/", kind="analysis", substantive=True, date="2023 centenary collection", route="live URL 403; Wayback raw capture https://web.archive.org/web/20240616085027id_/https://dunnettcentral.org/centenary/the-writers-writer/"),
]
COVERAGE = "In progress after 22 sources across all three angles."
