import json,os
D=os.path.dirname(os.path.abspath(__file__))
S=[
 dict(title="Review Standards (tenfootpole.org)",url="https://tenfootpole.org/ironspike/?page_id=1201",kind="craft-criticism",substantive=True,date="undated page; comments 2016-2026",route="direct curl, browser UA"),
 dict(title="The Art of the Key",url="https://thealexandrian.net/wordpress/36903/roleplaying-games/the-art-of-the-key",kind="craft-criticism",substantive=True,date="2014-05-19",route="direct curl, browser UA"),
 dict(title="The Art of the Key - Part 2: The Essential Key",url="https://thealexandrian.net/wordpress/35201/roleplaying-games/the-art-of-the-key-part-2-the-essential-key",kind="craft-criticism",substantive=True,date="2014-05-21",route="direct curl, browser UA"),
 dict(title="The Art of the Key - Part 3: Hierarchy of Reference",url="https://thealexandrian.net/wordpress/38497/roleplaying-games/the-art-of-the-key-part-3-hierarchy-of-reference",kind="craft-criticism",substantive=True,date="2016-05-02",route="direct curl, browser UA"),
 dict(title="GM Don't List #13: Boxed Text Pitfalls",url="https://thealexandrian.net/wordpress/48312/roleplaying-games/gm-dont-list-13-boxed-text-pitfalls",kind="craft-criticism",substantive=True,date="2022-08-01",route="direct curl, browser UA"),
 dict(title="Picturing the dungeon - boxed text (DMDavid)",url="https://dmdavid.com/tag/picturing-the-dungeon-boxed-text/",kind="craft-criticism",substantive=True,date="2012-11-15",route="direct curl, browser UA"),
 dict(title="Design & Development: Undercover at Gen Con, Part 1 (Wizards of the Coast)",url="https://web.archive.org/web/20161031220137/http://archive.wizards.com/default.asp?x=dnd/dd/20050916a",kind="designer-observation",substantive=True,date="2005-09-16",route="Wayback capture 20161031220137 of archive.wizards.com (live URL dead)"),
 dict(title="GROGNARDIA: High Gygaxian",url="http://grognardia.blogspot.com/2009/02/high-gygaxian.html",kind="craft-criticism",substantive=True,date="2009-02-19",route="direct curl, browser UA"),
 dict(title="GROGNARDIA: Trent Foster Makes It Plain",url="http://grognardia.blogspot.com/2009/07/trent-foster-makes-it-plain.html",kind="blog-post",substantive=False,date="2009-07-30",route="direct curl; post is a bare link to knights-n-knaves.com thread t=5969, no prose content"),
 dict(title="GROGNARDIA: White Dwarf Interviews Gary Gygax",url="http://grognardia.blogspot.com/2021/10/white-dwarf-interviews-gary-gygax.html",kind="relay",substantive=False,date="2021-10-26",route="direct curl; relays White Dwarf #14 (late 1979) but on inspirations/players, nothing on prose or keys"),
 dict(title="The Dreaded Boxed Text (Dyson's Dodecahedron)",url="https://dysonlogos.blog/2013/09/29/the-dreaded-boxed-text/",kind="craft-criticism",substantive=True,date="2013-09-29",route="direct curl, browser UA"),
]
def c(feature,claim,source,url,quote,page="",kind="analysis",polarity="asserts",date="",routeHint="direct curl (browser UA)",registerHint="dm-page",confidence="high"):
    return dict(feature=feature,claim=claim,source=source,url=url,quote=quote,page=page,kind=kind,polarity=polarity,date=date,routeHint=routeHint,registerHint=registerHint,confidence=confidence)
TFP="https://tenfootpole.org/ironspike/?page_id=1201"
AK1="https://thealexandrian.net/wordpress/36903/roleplaying-games/the-art-of-the-key"
AK2="https://thealexandrian.net/wordpress/35201/roleplaying-games/the-art-of-the-key-part-2-the-essential-key"
AK3="https://thealexandrian.net/wordpress/38497/roleplaying-games/the-art-of-the-key-part-3-hierarchy-of-reference"
AB="https://thealexandrian.net/wordpress/48312/roleplaying-games/gm-dont-list-13-boxed-text-pitfalls"
DMD="https://dmdavid.com/tag/picturing-the-dungeon-boxed-text/"
WOTC="https://web.archive.org/web/20161031220137/http://archive.wizards.com/default.asp?x=dnd/dd/20050916a"
HG="http://grognardia.blogspot.com/2009/02/high-gygaxian.html"
DY="https://dysonlogos.blog/2013/09/29/the-dreaded-boxed-text/"
C=[
c("boxed text form","Bryce Lynch's own list of what he looks for in an adventure module states that boxed text is usually not a good thing.","Bryce Lynch, 'Review Standards', tenfootpole.org",TFP,"Boxed text is usually not a good thing.","Review Standards, bullet list",polarity="rejects"),
c("plainness and economy","Bryce Lynch lists a terse writing style among the qualities he looks for in an adventure module.","Bryce Lynch, 'Review Standards', tenfootpole.org",TFP,"Terse writing style","Review Standards, bullet list"),
c("concrete sensory noun","Bryce Lynch lists evocative atmosphere among the qualities he looks for in an adventure module.","Bryce Lynch, 'Review Standards', tenfootpole.org",TFP,"Evocative atmosphere.","Review Standards, bullet list"),
c("other: backstory economy","Bryce Lynch's standards reject epic backstory in an adventure module and ask only for enough to start play.","Bryce Lynch, 'Review Standards', tenfootpole.org",TFP,"I don’t care about your epic backstory.","Review Standards, bullet list",polarity="rejects"),
c("plainness and economy","The phrase 'succinct and evocative' on tenfootpole.org is the top grade for Language on a second reviewer's rating scale (signed 'The Pretty Girl'), not a line of Bryce Lynch's own standards.","'The Pretty Girl' (second reviewer), rating scale on tenfootpole.org 'Review Standards'",TFP,"Succinct and evocative","Review Standards, 'The Pretty Girl' scale, Language 4",confidence="high"),
c("plainness and economy","On that same Language scale the lowest grade is reserved for writing that is very wordy or incomprehensible.","'The Pretty Girl' (second reviewer), rating scale on tenfootpole.org 'Review Standards'",TFP,"Very wordy/ incomprehensible","Review Standards, 'The Pretty Girl' scale, Language 0",polarity="rejects"),
c("other: backstory economy","In a comment on his own standards page Bryce Lynch says he loathes overly long backstory and fiction introductions.","Bryce Lynch, comment of 19 April 2016 on tenfootpole.org 'Review Standards'",TFP,"I LOATHE the overly long backstory","Review Standards, comments, 2016-04-19",kind="own-words",polarity="rejects",date="2016-04-19"),
c("other: key format","Justin Alexander judges the location keys of published adventures to be almost universally terrible.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"almost universally terrible","Art of the Key, opening",date="2014-05-19",polarity="rejects"),
c("boxed text form","Justin Alexander defines boxed text as prewritten text designed to be read aloud by the GM.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"prewritten text designed to be read aloud by the GM","Art of the Key, 'The Era of Boxed Text'",date="2014-05-19",polarity="mentions"),
c("boxed text form","Justin Alexander dates the first appearance of read-aloud boxed text to Lost Tamoachan and hedges between 1979 and 1980.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"In either 1979 or 1980","Art of the Key, 'The Era of Boxed Text'",date="2014-05-19",confidence="high"),
c("other: information sequencing","Justin Alexander argues a room key must sequence information by what the players meet first, so a room with an ogre in the middle of it leads with the ogre.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"should talk about the ogre first","Art of the Key, 'Adventure Formatting Guides'",date="2014-05-19"),
c("edition and house style","Justin Alexander argues that a rigid adventure format defeats its own aim of making information easy to parse and reference.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"a rigid format ends up having the opposite effect","Art of the Key, closing of Part 1",date="2014-05-19",polarity="rejects"),
c("edition and house style","Justin Alexander says the standardized 3rd Edition adventure format encourages writers to fill the format with text that is not needed.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"it tends to encourage writers to “fill the format”","Art of the Key, 'Adventure Formatting Guides'",date="2014-05-19",polarity="rejects"),
c("other: key format","Justin Alexander labels the dense undifferentiated paragraph key that TSR used for most of a decade the Gygax wall of text.","Justin Alexander, 'The Art of the Key', The Alexandrian, 2014",AK1,"the Gygax “wall of text” key","Art of the Key, 'A Brief History of the Key'",date="2014-05-19"),
c("other: seen in a glance","Justin Alexander's prescribed key opens with the information a character perceives on entering, which he calls seen in a glance.","Justin Alexander, 'The Art of the Key - Part 2', The Alexandrian, 2014",AK2,"seen in a glance","Part 2, 'Boxed Text'",date="2014-05-21"),
c("other: information sequencing","Justin Alexander's alternative to a fixed key format is to order the entry by the sequence in which information will be wanted at the table.","Justin Alexander, 'The Art of the Key - Part 2', The Alexandrian, 2014",AK2,"focus on the sequencing of information","Part 2, opening",date="2014-05-21"),
c("other: information sequencing","Justin Alexander tells key writers to move from the general to the specific as the players investigate.","Justin Alexander, 'The Art of the Key - Part 2', The Alexandrian, 2014",AK2,"move from the general to the specific","Part 2, 'Developing Significant Elements'",date="2014-05-21"),
c("dm-facing sentence","Justin Alexander bolds the name of each significant element in a room so the GM can find the matching information quickly.","Justin Alexander, 'The Art of the Key - Part 2', The Alexandrian, 2014",AK2,"the bold title makes it easy to find the information","Part 2, 'Significant Elements'",date="2014-05-21"),
c("other: background and history in a key","Justin Alexander confines a location's history and former use to a GM Background tag that must be brief and infrequently needed.","Justin Alexander, 'The Art of the Key - Part 2', The Alexandrian, 2014",AK2,"It should be brief, to the point, and infrequently needed.","Part 2, 'GM Background Tag'",date="2014-05-21",registerHint="dm-page"),
c("other: reference layout","Justin Alexander credits the delve format with the single good idea that everything the GM needs is on the page.","Justin Alexander, 'The Art of the Key - Part 3', The Alexandrian, 2016",AK3,"Everything you need is on the page.","Part 3, opening",date="2016-05-02",polarity="applies"),
c("boxed text form","Justin Alexander grants that boxed text virtually guarantees essential information is not accidentally omitted in play.","Justin Alexander, 'GM Don't List #13: Boxed Text Pitfalls', The Alexandrian, 2022",AB,"will virtually guarantee that it’s not accidentally omitted","GM Don't List #13, advantages",date="2022-08-01",polarity="asserts"),
c("boxed text form","Justin Alexander counts inflexibility as an inherent cost of prewritten boxed text, since one passage must serve every approach and condition.","Justin Alexander, 'GM Don't List #13: Boxed Text Pitfalls', The Alexandrian, 2022",AB,"The result is inherently less flexible.","GM Don't List #13, 'So why wouldn't you use boxed text?'",date="2022-08-01",polarity="rejects"),
c("other: reaction point","Justin Alexander names freeze-frame boxed text as the failure in which the world keeps moving while the characters stand frozen.","Justin Alexander, 'GM Don't List #13: Boxed Text Pitfalls', The Alexandrian, 2022",AB,"PCs are frozen in place while a bunch of stuff happens","GM Don't List #13, 'Sins of the Box'",date="2022-08-01",polarity="rejects"),
c("other: reaction point","Justin Alexander names the reaction point as the place in a description past which the world must not move without the players.","Justin Alexander, 'GM Don't List #13: Boxed Text Pitfalls', The Alexandrian, 2022",AB,"What we’ve identified here is the reaction point","GM Don't List #13, 'Sins of the Box'",date="2022-08-01"),
c("point of view and distance","Justin Alexander condemns remote-control boxed text, which declares the thoughts, feelings or actions of the player characters.","Justin Alexander, 'GM Don't List #13: Boxed Text Pitfalls', The Alexandrian, 2022",AB,"declaring the thoughts or feelings or (worse yet!) actions of the PCs","GM Don't List #13, 'Remote-Control Boxed Text'",date="2022-08-01",polarity="rejects"),
c("point of view and distance","Justin Alexander's rule for read-aloud text is to show the scene and never to tell the players how they are reacting to it.","Justin Alexander, 'GM Don't List #13: Boxed Text Pitfalls', The Alexandrian, 2022",AB,"Don’t tell them how they’re reacting to it.","GM Don't List #13, 'Remote-Control Boxed Text'",date="2022-08-01"),
c("boxed text form","A reader commenting on the Alexandrian recalls a lost Wizards devblog article whose thesis was that GM description should never run past three sentences.","Reader comment by 'mellonbread', 2 August 2022, on The Alexandrian",AB,"should never be longer than three sentences","GM Don't List #13, comments, 2022-08-02",kind="reader",date="2022-08-02",confidence="medium: a reader's recollection of an article he says was deleted; the surviving 2005 Wizards article gives two sentences, not three"),
c("boxed text form","David Hartlage dates the introduction of boxed text descriptions read by the DM on entry to Hidden Shrine of Tamoachan in 1979.","David Hartlage, 'Picturing the dungeon - boxed text', DMDavid, 2012",DMD,"In 1979, Hidden Shrine of Tamoachan introduced boxed text descriptions","Picturing the dungeon - boxed text",date="2012-11-15"),
c("boxed text form","David Hartlage attributes the original purpose of boxed text to giving every table the same play experience in tournament competition.","David Hartlage, 'Picturing the dungeon - boxed text', DMDavid, 2012",DMD,"a consistent play experience in a competitive environment","Picturing the dungeon - boxed text",date="2012-11-15"),
c("omission as information","David Hartlage reports that in a tournament the significant detail was placed among less important ones in the boxed text and his team missed it.","David Hartlage, 'Picturing the dungeon - boxed text', DMDavid, 2012",DMD,"the text mentioned the runes alongside other, less important details","Picturing the dungeon - boxed text",date="2012-11-15",kind="reception"),
c("other: read-aloud delivery","David Hartlage says a reader's voice takes a different tone and cadence from extemporaneous speech, and that monotony lets players' attention wander.","David Hartlage, 'Picturing the dungeon - boxed text', DMDavid, 2012",DMD,"their voice takes a different tone and cadence","Picturing the dungeon - boxed text",date="2012-11-15"),
c("boxed text form","David Hartlage defends boxed text as still the best available summary of what players must learn on entering a room.","David Hartlage, 'Picturing the dungeon - boxed text', DMDavid, 2012",DMD,"No one has shown a better way to summarize","Picturing the dungeon - boxed text",date="2012-11-15",polarity="asserts"),
c("other: read-aloud delivery","David Hartlage says that when he knows the material well he paraphrases the boxed text rather than reading it.","David Hartlage, 'Picturing the dungeon - boxed text', DMDavid, 2012",DMD,"I paraphrase boxed text","Picturing the dungeon - boxed text",date="2012-11-15",kind="own-words"),
c("boxed text form","David Noonan reports that from watching Gen Con 2005 tables a DM reading aloud holds attention for two sentences.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"If you’re the DM, you get two sentences. Period.","Undercover Insight #1: Boxed Text = MEGO",kind="measurement",date="2005-09-16",routeHint="Wayback raw capture 20161031220137",confidence="high"),
c("boxed text form","The same Wizards article labels its own Gen Con observation qualitative rather than a controlled measurement.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"this kind of “research” is pretty qualitative","Here's the Plan: We're Going Undercover!",kind="own-words",date="2005-09-16",routeHint="Wayback raw capture 20161031220137"),
c("other: read-aloud delivery","David Noonan's explanation for the attention loss is that boxed text substitutes oration for the conversation that a game normally is.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"Boxed text replaces that conversation with oration.","Undercover Insight #1: Boxed Text = MEGO",date="2005-09-16",routeHint="Wayback raw capture 20161031220137"),
c("dialogue register","David Noonan describes a D&D game as at heart a conversation between the DM and the players.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"At its heart, a D&D game is a conversation.","Undercover Insight #1: Boxed Text = MEGO",date="2005-09-16",routeHint="Wayback raw capture 20161031220137"),
c("boxed text form","David Noonan's prior hypothesis, which the watching exceeded, was that boxed text longer than a paragraph is not worth reading.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"boxed text longer than a paragraph probably isn’t worth reading","Undercover Insight #1: Boxed Text = MEGO",date="2005-09-16",routeHint="Wayback raw capture 20161031220137"),
c("boxed text form","Writing for Wizards of the Coast in 2005, David Noonan advises DMs to ditch the boxed text and describe the room in their own words.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"ditch the boxed text and use your own words","Beyond the door, you see a format change",date="2005-09-16",routeHint="Wayback raw capture 20161031220137",polarity="rejects"),
c("edition and house style","David Noonan observes that boxed text in Wizards adventures had become markedly shorter by 2005 than in earlier products.","David Noonan (with Jesse Decker), 'Undercover at Gen Con, Part 1', Wizards of the Coast Design & Development, 2005",WOTC,"Boxed text in adventures used to be a lot longer","Undercover Insight #1, Tangent Alert",kind="measurement",date="2005-09-16",routeHint="Wayback raw capture 20161031220137"),
c("diction (native vs latinate)","James Maliszewski reports that Gygax attributed his own voice to the old fashioned books he read as a boy rather than to Jack Vance.","James Maliszewski relaying a private conversation with Gary Gygax, 'High Gygaxian', Grognardia, 2009",HG,"old fashioned","High Gygaxian",kind="relay",date="2009-02-19",registerHint="none",confidence="medium: a blogger's paraphrase of a private conversation; only the two quoted words are Gygax's"),
c("diction (native vs latinate)","In the same account Gygax credited a lifelong love of dictionaries and thesauruses for his vocabulary.","James Maliszewski relaying a private conversation with Gary Gygax, 'High Gygaxian', Grognardia, 2009",HG,"his lifelong love of dictionaries and thesauruses","High Gygaxian",kind="relay",date="2009-02-19",registerHint="none",confidence="medium: paraphrase, not transcribed speech"),
c("other: authorial voice in rulebooks","James Maliszewski reports that Gygax demurred when told his voice was a dialect of Jack Vance's.","James Maliszewski, 'High Gygaxian', Grognardia, 2009",HG,"I once told Gary my opinion on this and he demurred","High Gygaxian",kind="relay",date="2009-02-19",registerHint="none"),
c("other: authorial voice in rulebooks","James Maliszewski contrasts Gygax's florid prose with modern game books, which he says read like technical manuals.","James Maliszewski, 'High Gygaxian', Grognardia, 2009",HG,"Modern game books read like what they are: technical manuals.","High Gygaxian",date="2009-02-19",polarity="rejects",registerHint="none"),
c("place and institution description","James Maliszewski holds up Gygax's description of the Vault of the Drow as more evocative than the place descriptions in contemporary adventures.","James Maliszewski, 'High Gygaxian', Grognardia, 2009",HG,"you'll find few passages in contemporary adventures that are as evocative","High Gygaxian",date="2009-02-19",registerHint="dossier-archivist"),
c("boxed text form","Dyson Logos tells OSR adventure writers to get rid of boxed text.","Dyson Logos, 'The Dreaded Boxed Text', Dyson's Dodecahedron, 2013",DY,"So, OSR adventure writers, get rid of the boxed text.","The Dreaded Boxed Text",date="2013-09-29",polarity="rejects"),
c("dm-facing sentence","Dyson Logos proposes replacing read-aloud prose with a point-form list of the things seen in the room, so the DM can present them conversationally.","Dyson Logos, 'The Dreaded Boxed Text', Dyson's Dodecahedron, 2013",DY,"replace it with a point-form list of things seen in the room","The Dreaded Boxed Text",date="2013-09-29"),
c("boxed text form","Dyson Logos traces the arrival of read-aloud text in the 1e era to the tournament use of the early published adventures.","Dyson Logos, 'The Dreaded Boxed Text', Dyson's Dodecahedron, 2013",DY,"I tend to blame this on the tournament usage","The Dreaded Boxed Text",date="2013-09-29",confidence="medium: the author frames it as his own supposition"),
]
out=dict(complete=False,coverage="in progress",sourcesRead=S,claims=C)
p=os.path.join(D,'found-dnd-usability-school.json')
json.dump(out,open(p,'w'),indent=1,ensure_ascii=False)
print(p,len(C),"claims",len(S),"sources")
