import json,os
D=os.path.dirname(os.path.abspath(__file__))
p=os.path.join(D,'found-dnd-usability-school.json')
prev=json.load(open(p)); S=prev['sourcesRead']; C=prev['claims']
DIR="direct curl, browser UA"
S.append(dict(title="The Lions of Tell Arn Part 2 - The City & The City (tenfootpole.org review)",url="https://tenfootpole.org/ironspike/?p=10550",kind="review",substantive=True,date="2026-07-06",route=DIR))
S.append(dict(title="How much description should a dungeon key include? (DMDavid)",url="https://dmdavid.com/tag/how-much-description-should-a-dungeon-key-include/",kind="craft-criticism",substantive=True,date="2016-11-21",route=DIR))
S.append(dict(title="The Alexandrian: Advanced Gamemastery: Boxed Text (video page)",url="https://thealexandrian.net/wordpress/50680/roleplaying-games/advanced-gamemastery-boxed-text",kind="video-page",substantive=False,date="2024-02-28",route="direct curl; page carries only a promo blurb for a video, no argument text"))
S.append(dict(title="Knights & Knaves Alehouse thread t=5969 (the Trent Foster posting Grognardia praised)",url="http://www.knights-n-knaves.com/phpbb/viewtopic.php?t=5969",kind="forum",substantive=False,date="2009",route="NOT FOUND: forum offline and archive.org/wayback/available returns no snapshot"))
def c(**k): C.append(k)
def mk(feature,claim,source,url,quote,page="",kind="analysis",polarity="asserts",date="",routeHint="direct curl (browser UA)",registerHint="dm-page",confidence="high"):
    c(feature=feature,claim=claim,source=source,url=url,quote=quote,page=page,kind=kind,polarity=polarity,date=date,routeHint=routeHint,registerHint=registerHint,confidence=confidence)
LN="https://tenfootpole.org/ironspike/?p=10550"; BL="Bryce Lynch, review of 'The Lions of Tell Arn Part 2', tenfootpole.org, 2026"
DM="https://dmdavid.com/tag/how-much-description-should-a-dungeon-key-include/"; DH="David Hartlage, 'How much description should a dungeon key include?', DMDavid, 2016"
mk("place and institution description","Bryce Lynch praises a keying pattern in which each room opens with a short vibe overview before its bulleted details.",BL,LN,"The rooms start with a kind of vibe overview.","Lions of Tell Arn Part 2 review",date="2026-07-06",registerHint="dossier-archivist")
mk("concrete sensory noun","The room text Bryce Lynch holds up as the model is a string of verbless sensory noun phrases, quoted in his review.","module text by Nikoline quoted in Bryce Lynch's review, tenfootpole.org, 2026",LN,"Sickly stench; grease and putrescence.","Lions of Tell Arn Part 2 review, quoted room 28",kind="reception",date="2026-07-06",registerHint="dossier-archivist",confidence="high")
mk("place and institution description","Bryce Lynch's test of a good room description is that it reads as if the writer had lived the room and got the mental image onto paper.",BL,LN,"someone called up a mental image in their head","Lions of Tell Arn Part 2 review",date="2026-07-06",registerHint="dossier-archivist")
mk("other: transfer of an imagined place","Bryce Lynch states that transferring the writer's imagined room into the reading DM's head is the goal of good writing.",BL,LN,"That IS the goal of good writing.","Lions of Tell Arn Part 2 review",date="2026-07-06")
mk("edition and house style","Bryce Lynch praises bolding and italics used sparingly to draw the eye rather than overused.",BL,LN,"Bolding and italics are used to effect to draw the eye","Lions of Tell Arn Part 2 review",date="2026-07-06")
mk("plainness and economy","Bryce Lynch praises treasure descriptions that stay terse while being more interesting than a plus-one sword.",BL,LN,"terse but much more interesting than a Sword, +1","Lions of Tell Arn Part 2 review",date="2026-07-06")
mk("other: key format","David Hartlage reports that Gygax's own Castle Greyhawk key usually gave each room a one-line note.",DH,DM,"he usually wrote a 1-line note for each room","How much description, opening",date="2016-11-21")
mk("edition and house style","David Hartlage says Gygax's generous location descriptions in G1 set the pattern for virtually every adventure that followed.",DH,DM,"Gary’s longer descriptions set the pattern for virtually every adventure to follow.","How much description, 'Gary Gygax sets the standard'",date="2016-11-21")
mk("place and institution description","David Hartlage argues longer descriptions spare the DM inventing details, whose first ideas tend toward the obvious.",DH,DM,"the ideas that spring to mind first will steer toward the obvious","How much description, 'Longer descriptions'",date="2016-11-21",polarity="asserts",registerHint="dossier-archivist")
mk("other: padding","David Hartlage says an expanded room description pads a good middle sentence like a school paper stretched to length.",DH,DM,"pads it like a school paper stretched to an assigned length","How much description, 'Longer descriptions'",date="2016-11-21",polarity="rejects")
mk("edition and house style","David Hartlage says the custom of long descriptions makes authors write even when they have nothing to add.",DH,DM,"encourages authors to write something even when they have little","How much description, 'Longer descriptions'",date="2016-11-21",polarity="rejects")
mk("omission as information","David Hartlage says an avalanche of description buries the details that would actually reach play.",DH,DM,"An avalanche of description does more than squander page count.","How much description, 'Matching description to a location's purpose'",date="2016-11-21",polarity="rejects")
mk("place and institution description","David Hartlage says a location's description should be as long as the way players will actually engage that location.",DH,DM,"The length of descriptions should match the way players will engage","How much description, 'The ideal dungeon description'",date="2016-11-21",registerHint="dossier-archivist")
mk("adjective and adverb discipline","David Hartlage tells writers to keep the evocative details out from under lavish description of pallets and rubbish.",DH,DM,"Don’t bury the evocative bits in lavish descriptions","How much description, 'The ideal dungeon description'",date="2016-11-21")
mk("concrete sensory noun","David Hartlage says descriptions should carry telling details and information he can use in play.",DH,DM,"Descriptions should focus on telling details and plot-critical information","How much description, 'The ideal dungeon description'",date="2016-11-21",registerHint="dossier-archivist")
mk("place and institution description","David Hartlage's test for cutting a description is whether it is the first thing a typical DM would imagine anyway.",DH,DM,"the first thing a typical DM would imagine at the table","How much description, 'The ideal dungeon description'",date="2016-11-21")
mk("boxed text form","David Hartlage grants that the boxed descriptions in Curse of Strahd are evocative while faulting their use in every empty room.",DH,DM,"The descriptions are evocative","How much description, 'Boxed, read-aloud text'",kind="reception",polarity="disputes",date="2016-11-21")
mk("edition and house style","David Hartlage quotes Bob Bledsaw in Dragon 27 saying judges regarded describing dungeons as their own domain.",'Bob Bledsaw in Dragon #27, quoted by David Hartlage, DMDavid, 2016',DM,"judges felt that the actual description of dungeons was their ‘domain’","How much description, 'Tegel Manor and minimal descriptions'",kind="relay",date="2016-11-21",confidence="medium: quoted at second hand; Dragon #27 not read directly")
mk("plainness and economy","David Hartlage quotes Michael Curtis describing the Stonehell style as the minimum information needed to run the dungeon.",'Michael Curtis, quoted by David Hartlage, DMDavid, 2016',DM,"the minimum amount of information needed to run the dungeon","How much description, 'The influence of one-page dungeons'",kind="relay",date="2016-11-21",confidence="medium: quoted at second hand")
prev['sourcesRead']=S; prev['claims']=C
json.dump(prev,open(p,'w'),indent=1,ensure_ascii=False)
print(len(C),"claims",len(S),"sources")
