import re,html,sys
t=open(sys.argv[1],encoding='utf-8',errors='replace').read()
t=re.sub(r'(?is)<(script|style|nav|footer|head).*?</\1>',' ',t)
t=re.sub(r'(?is)<br\s*/?>','\n',t)
t=re.sub(r'(?is)</(p|div|li|h1|h2|h3|tr)>','\n\n',t)
t=re.sub(r'(?s)<[^>]+>',' ',t)
t=html.unescape(t)
t=re.sub(r'[ \t]+',' ',t)
t=re.sub(r'\n\s*\n+','\n\n',t)
print(t.strip())
