import json
base="/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/"
src=json.load(open(base+"chunks/kay-07.json",encoding="utf-8"))
V=[
(625,"VERIFIED_VERBATIM","And it's layered up, sometimes ten or fifteen times for a scene.","Raw HTML fetched with a browser UA (HTTP 200, 72KB). Quote is verbatim in GGK's answer describing his 'painterly' layering method; speaker label 'GGK:' confirms Kay. Page header confirms Peter Halasz interviewed GGK for NYRSF during 2000."),
(627,"VERIFIED_VERBATIM","PH: Reading your work, the punctilious choice of word and image","Verbatim, and spoken by the interviewer: the line is prefixed 'PH:' and the page's introduction states 'This interview appears courtesy of Peter Halasz, who interviewed GGK for the New York Review of Science Fiction during 2000.' It is indeed the question preceding the answer on rewriting ('A tremendous amount')."),
(629,"VERIFIED_VERBATIM","I don't like books, as a reader, where I feel hammered on the head with the author's didactic or pedantic point","Verbatim (curly apostrophe matches). In Kay's answer, not the interviewer's question — the following paragraph switches to second person ('your plotting technique'). Page header confirms Jean-Louis Trudel, Solaris, 1995. The claim's 'didactic point' drops 'or pedantic', which narrows but does not misstate."),
(632,"VERIFIED_VERBATIM","readers would...probably not pick up on the specific myths...but my hope was that an ambience, a generally mythic flavour and realm would emerge","Verbatim, in Kay's answer within the Tolkien/mythic-sources exchange. Both limbs supported: he expected readers to miss the specific sources, and hoped for ambience. Minor nuance: the sentence continues 'so that one reader might know that the ravens...are in fact the ravens of Odin', so 'hoped only' is a shade stronger than the page — the substance still holds."),
(640,"VERIFIED_VERBATIM","(Guy Gavriel Kay, The Summer Tree, Toronto, 1984; ... The Wandering Fire, New York, 1986; ... The Darkest Road, New York, 1986)","Verbatim and it is the entry's last line — only WordPress chrome ('This entry was posted in...') follows. All three Fionavar novels are listed, each with city and year. Page header confirms the entry is from The Dictionary of Imaginary Places by Alberto Manguel and Gianni Guadalupi, reprinted with permission."),
(656,"VERIFIED_VERBATIM","his choice of tense, depending on which character the novel is following at the time","Verbatim. Page title is 'Review by Desi Stern for Petrichor Machine'; the sentence sits in the paragraph beginning 'Another way that Kay's mastery of craft is working at its best', exactly as the claim's page field says."),
(657,"VERIFIED_VERBATIM","Most sections are written in the past tense, except for those following the character of Shan","Verbatim, and the present-tense limb is explicit further on: 'her present-tense tale' and 'The present-tense narration really enhances the reader's experience of Shan's awareness'. The review names the book: 'I just finished reading River of Stars'."),
(658,"VERIFIED_VERBATIM","a male character...decides to purposefully think in a more feminine state of mind...and his narration shifts to present tense for the scene","Verbatim, and it is indeed the parenthetical paragraph immediately after the Shan discussion, as the claim's page field states."),
(659,"VERIFIED_VERBATIM","The language in River of Stars is formal and poetic","Verbatim. Page title confirms 'Review by Natalie Zina Walschots for National Post'; the sentence opens the paragraph the claim names."),
(660,"VERIFIED_VERBATIM","the sentences laid out like layers of diaphanous fabric","Verbatim, in the same sentence as index 659: 'The language in River of Stars is formal and poetic, the sentences laid out like layers of diaphanous fabric, becoming a solid narrative through the interplay of their layers.'"),
(665,"VERIFIED_VERBATIM","This is narration of a high quality, indeed.","Verbatim, including the comma and 'indeed'. Page title confirms 'Review by Doug Barbour, for The Edmonton Journal'; the review is of Sailing to Sarantium. The sentence follows Barbour's point that Kay 'represents the ways many of them think as they act', so 'the telling of the novel' is a fair gloss."),
(666,"VERIFIED_VERBATIM","he has quietly but consistently moved his narratives ever further away from the easy magic","Verbatim as quoted. One connective differs in the claim's paraphrase — the page reads 'quietly but consistently', the claim says 'quietly and consistently' — but both limbs (quietly; consistently; away from easy magic) are supported by the page."),
(671,"VERIFIED_VERBATIM","to have figures emote or react as we might, ourselves...feels like a betrayal (even a large one) of the characters and the culture","Verbatim, in a first-person entry by Kay ('as a writer, if I'm developing characters in a setting meant to evoke a...much more controlled society'), inside the Under Heaven tour journal on the craft-of-emotion topic. The page adds 'and the culture' after 'the characters'; the claim's 'of them' is narrower but not wrong."),
(676,"VERIFIED_VERBATIM","he forges his own rules when it comes to punctuation","Verbatim. The guest post opens 'As Guy Gavriel Kay's production editor at Penguin Group (Canada), I am responsible for overseeing the copyediting...'; Kay's own preamble names her ('Sandra Tooze, the production editor for Under Heaven takes the podium'), confirming both the role and the venue."),
(678,"VERIFIED_VERBATIM","It's exactly as he wants it when he submits the manuscript.","Verbatim, two sentences after the punctuation line in the same production editor's guest post; the surrounding sentences ('Most authors leave that “small stuff” to editors to fix—not Guy') confirm the punctuation referent."),
]
verdicts=[{"index":i,"verdict":v,"trueWording":w,"note":n} for (i,v,w,n) in V]
assert [x["index"] for x in verdicts]==src["indices"], "index order mismatch"
out={"name":"kay","chunk":7,"claims":src["claims"],"verdicts":verdicts}
p=base+"verdicts-kay-i625-678.json"
json.dump(out,open(p,"w",encoding="utf-8"),ensure_ascii=False,indent=1)
print("WROTE",p)
d=json.load(open(p,encoding="utf-8"))
print("claims",len(d["claims"]),"verdicts",len(d["verdicts"]))
print([ (x["index"],x["verdict"]) for x in d["verdicts"]])
