# Brief — the REWRITE train, cars 8b: THE DEFENSE DESK SECTION REWRITTEN WITH ITS FACES — one writing workflow per block (DS-DEF-1 … DS-DEF-11; 121 pools · 383 variants → 383 rewritten variants with three faces each = 1,149 faces), staffed as the owner signed at SITTING §T.12 (Opus drafts · Opus refines · Fable refutes EVERY set), the two phases of Part B §21, keep-or-revert on the refuters' CONFIRMED findings, Shift 1 declared per block on the classifier's print (chartered by the chair under the total delegation of 2026-09-09; ARCH §8, §12 row 8a…8n; SITTING §T)

Seat of the workflows: `$SC/rewrite/rewrite-block.workflow.js` (the chair's script, derived from `taste/taste-write.workflow.js`), args `{block: 'DS-DEF-n', dock: 'laneRW-DEFn'}`; three block workflows at a time at most (the four-lane cap with one implementation lane); each block in ITS OWN dock cut at the §919 CAS (`sh $SC/mkdock.sh laneRW-DEFn <cas>`), so the gates' vitest runs serialise under the runner-count law and a dead workflow leaves its block's commits in its dock. Nothing here lands until the block's fold: the chair lands the blocks as a consist (cars 8b-1 … 8b-11) with a skeptic pass and the §920 chain.

## The unit and the law
- THE UNIT IS THE POOL (a wording set = one pool's k existing variants, each rewritten in place under the SAME `vid`, each given a `[plain]` line and three `[face]` sub-rows in the ARCH §2.5 grammar); NO variant is added or removed (NEVER TRIM; the variant ratchet and the face-count ratchet of 8a red on any fall); the typed lines of the pool are NOT touched (ROLE · READS · RELATION · ATTACH · FORM · MOVE); a row's `[grammar: Vn]` and slots are the card's.
- EVERY writer, refiner and refuter reads the VOICE documents whole (the list is the taste workflow's `VOICE` string: REGISTER-CARD with S2 + S3; Part B §1, §16–§16.2, §18, §20–§23; MOVE-GRAMMAR §1–§3, §4.4.1–§4.4.3; CLERK-LAWS §2.4.1, §2.6.1; ARCH §2.5 + §8.3) and the pool's LICENCE CARD printed from the census in the dock (`node scripts/prose-licence-card.mjs <block> '<pool>'`), and the block's own annex section for the spines beside it.
- THE GATE is 8a's `scripts/prose-wave-gate.mjs` (read its header for the usage line before writing a prompt that calls it; the flags are the taste harness's `--arm draft --round N` / `--arm A --base <cells.json>` unless the header says otherwise): the projector `generate-dossier-state-prose.mjs --check` must accept every row or name the refusal; the composed walker at N (owned grain; the spine's inherited findings listed, never charged); the classifier over the DRIFT run against the block's base cells — every cell of the block WORDING-ONLY (or RE-INDEXED under the index-stable draw, printed and counted), nothing REPLACED, no STOP; the band figures at BOTH grains (8a item 5a); sibling swaps 0 and the distance figure; provenance ≤ 1 per unit on a licensed holder; the duplicate-unit rate on VARIETY for the block before and after; the round counters per pool.
- PHASE 1 (the draft, Opus): one Opus writer per pool per round; rounds continue while a failing OWNED measure moves; two consecutive dry rounds → the pool is a REFUSAL row (banked, never trimmed; its last packet kept); hard cap 6 rounds logged. PHASE 2 (the refinement, Opus, a DIFFERENT agent than the drafter): every pool refined ONCE toward the CEILING (Part B §21.1–§21.4: the sharpest licensed fact, the strongest rhythm inside the voice, the four faces as far apart as the voice allows, zero tics, the clerk's ear; the density law; never plainer with no law behind it); the gate re-runs; the keep-or-revert rule per pool (lawful stays lawful → keep; unlawful with failures fallen and none new → keep; else revert from `git show <draft>:annex`). PHASE 3 (the refute, FABLE, EVERY pool, never a sample): one Fable refuter per pool over the kept rows, blind to nothing (there is one arm now), with the refuters' grounds of SITTING §T.5 named in the prompt (tails as qualifications; sibling paraphrase; forecast or perfect aspect on a standing fact; a claim opened by an ambiguity after the spine; a restatement; costume in the syntax; a positive share on a gated `< 1`; a same-page contradiction; an unlicensed particular; a citation with no licensed source; a regression against the draft on a named target); default FAIL when uncertain; each finding names its LAW. PHASE 4 (the judgment, FABLE): one Fable JUDGE per block applies the chair's rules per VARIANT — a FAIL that names a law and quotes the face → that face REVERTS to its draft face (one for one; the variant keeps its other faces); a WITHHELD → keep, listed; a FAIL naming no law → WITHHELD; a face reverted to a draft face that the refuter also failed → the pool is a REFUSAL row for the chair; the judge writes `rewrite/<block>/JUDGMENT.md` with every ruling and its ground, and commits the resulting annex + regenerated leaves in the block's dock as `REWRITE 8b <block>: <kept variants>/<n> · <reverted faces> · <refusals>`. The chair reads every JUDGMENT.md (a sample re-derived by hand) at the block's fold.
- SHIFT 1 IS DECLARED PER BLOCK on the classifier's print (WORDING-ONLY per cell; RE-INDEXED where the index-stable draw moved a pick; the counts into the block's receipt and the shift register's declared row) — signed by the chair under the delegation of §T.12, vetoable, and the manifest fixture is re-recorded ONCE at the REWRITE's last car (the freeze act), never per block.
- FENCES for every agent: writers, refiners and refuters write ONLY their packet under `$SC/rewrite/<block>/<pool dir>/`; they never enter, edit, commit or run tests in any dock; they may READ the dock and run the read-only licence-card script there. The gate and the judge work ONLY in the block's dock; explicit staging; never stash/amend/rebase/checkout/reset --hard; no register `--write` beyond the lighting census by its own ritual (the corpus-pinning walkers RED in a never-landed dock are DECLARED for the block, never re-frozen there — the landing consist re-freezes them once, at the chair's register car); the runner count in its own shell before every vitest.
- COST AND CLOCK are measured per phase per block from the workflow's budget counter and printed in the block's receipt (the owner's row 26 is a report; the numbers keep flowing).

## The blocks, in order (the workflow takes one `block` arg; three at a time)
| block | pools | variants | note |
|---|---|---|---|
| DS-DEF-11 | 5 | 12 | the taste's home; its four pools' typed lines and candidate functions land here with their rows (from laneTASTE M-2/M-3 by name; the taste's OWN rows are re-authored, never copied) |
| DS-DEF-2 | 26 | 78 | the largest; the two stock pools' typed lines + candidates land here; T-F12 re-cut at 8a decides the `granary AND hospital` attach |
| DS-DEF-1 | 9 | 26 | the readiness header; the `ADEQUATE` composition fence (§0h V1-g) kept |
| DS-DEF-3 | 7 | 23 | |
| DS-DEF-4 | 7 | 28 | the capture consequence; the state's organs INTERESTED at birth (§R c-22) |
| DS-DEF-5 | 11 | 33 | |
| DS-DEF-6 | 20 | 64 | 13 of 18 rung-4 pools BLOCKED (`DEF6_C3_BLOCKED_POOLS`) — its wiring folds into this car (SITTING §T.8) |
| DS-DEF-7 | 10 | 34 | |
| DS-DEF-8 | 4 | 12 | |
| DS-DEF-9 | 3 | 10 | |
| DS-DEF-10 | 19 | 63 | the five arms and the badges; the `ADEQUATE` fence with DS-DEF-1 |

## After the eleven blocks
The chair's consist over the block docks (cherry-pick by block commit, in the order above, onto `laneREWRITE` at the §919 CAS) → the skeptic pass (one dock per plant-driving lens; the lenses: the classifier's print per block · the judge's rulings re-derived on a sample · the fences and the registers) → cures → the §920 chain (predict · HOLD · proof · registers · register car · ratchet · after-ratchet · texts · gate · after-cas) → then the GENERAL desk (18 blocks, 71 pools, 258 variants) on the same pattern, then economy, power, stressors, and warFaith after its two wiring cars.

## ADDENDUM 1 (chair, 2026-09-09 08:2x, after the 8a fold and SITTING §U) — three rules for every block gate
- NEVER call the wave gate bare: its default roster composes zero units; pass `--pools` (the block's census keys) or `--section <desk>`.
- ALWAYS pass `--out <the block dock>/.packets/<arm>` (cure a-2 namespaces packets by dock and refuses a foreign packet; the workflow passes `--out` anyway, belt and braces) — two arms or two docks never share a packet file.
- The gate runs `tests/copy/voiceMechanics.test.js` and the projection contract after EVERY commit (the acceptance-gap hazard); the judge runs `check-domain-strict` and `typecheck:ratchet` once at the block's final commit.
- THE PEN LINE (SITTING §U c-7 ii): an INTERESTED fact's DM face is a pen line beside the block, never an inline replacement; a fact the player never reads at all (a covert fact) stays a `dm-only` variant. Writers of DS-DEF-4 (the capture consequence) and any block with a state-organ holder write the pen line as its own row kind per ARCH §2.5's pen grammar (the projector names the line) — if the grammar lacks a pen row kind at 8b's first block, the gate REFUSES the pen rows and the chair charters it as 8b-0.
- THE JUDGE RULES, THE GATE COMMITS (chair, 08:5x): the seat vocabulary the landing verifier accepts is closed (`Seat: Opus 5 — Fable-unvalidated` for a lane car; `Seat: Fable 5.1 — validated` for a chair act with no `Lane:` trailer), so the Fable judge writes `JUDGMENT.md` with a machine `--- REVERTS` section and commits nothing; an Opus APPLY gate restores each listed face from the draft packet one for one, re-runs the projector, the wave gate and the two per-commit tests, and commits under the Opus seat with the block's `Lane:` trailer. The chair's fold over the judgments is the validation.
- `tests/ui` WHOLE at the block's final commit (the apply gate): a rewritten sentence moves what every seed draws, so the UI flow tests' liveness anchors on drawn text are re-seeded or key-anchored in the block's own commit, never deleted (the §919 proof's nine, car 8a-12).

## ADDENDUM 2 (chair, 2026-09-09 11:5x) — THE CONSIST PROCEDURE and the three blocks' run ids
- Blocks DS-DEF-11 (`wf_7e1abdf4-c9a`), DS-DEF-2 (`wf_183dda09-702`), DS-DEF-1 (`wf_b6204819-335`) launched 11:4x in `laneRW-DEF11/2/1` at f73bdbf16. Then 3/4/5, 6/7/8, 9/10.
- THE CONSIST (`rewrite/consist-defense.sh <dock>…`): a block's leaf commits cannot be cherry-picked (every block regenerates the six leaves wholesale, so two blocks conflict on every line); the consist applies each block's ANNEX diff (disjoint sections) and its tests diff, regenerates the leaves once by the projector, checks, and commits one car per block under the Opus seat with a `Lane:` trailer (the consist is lane work; the chair's fold validates). Then the chair's register car (the census re-take, the lighting ritual, OSR shrink-only, the DRIFT manifest amendment on the classifier's WORDING-ONLY print per block — Shift 1's second amendment), then `skeptic-rewrite-8b` (lenses: the classifier's print per block against the block's JUDGMENT; the judge's rulings re-derived on a sample of variants against the refuters' findings; the fences, the registers and the receipts; the wave gate re-run on `--section defense`), cures, then the §920 chain (kit stamped: `*-920.*`, dock `laneRW-DEF`, seal `landing-rewrite-8b-defense-2026-09-09`).
- A block whose dock is at a draft or refine commit when its workflow dies is NOT consisted; it is re-run (its dock's history stands) or finished by hand (refute + judge + apply) by the chair's judgment.

## ADDENDUM 3 (chair, 2026-09-09 13:4x) — THE FIRST ATTEMPT AT THREE BLOCKS REFUSED BY THE CHAIR: three defects in the workflow's rules, all the chair's, and the interleaved WIRING cars
DS-DEF-1's first run (sealed `refs/preserve/rw-def1-attempt1-2026-09-09`; DEF11 and DEF2 likewise `rw-def11-…`, `rw-def2-…`; the packets under `rewrite/DS-DEF-n.attempt1/`) banked five of eight pools and left three at the OLD shipped rows. The judgment (`rewrite/DS-DEF-1.attempt1/JUDGMENT.md`) and the refuters' findings show three systematic causes, none of them the writers':
1. **THE ROW GRAMMAR.** The rules told writers to add a `[plain]` line; `[plain]` is the MODIFIER placeholder marker (SITTING §T.3 row 16), and a SPINE variant carries its own angle tag (`[ledger]`, `[visitor]`, `[street]`, …). A row with two bracketed tags is refused by the projector, so drafts were refused wholesale and the pools stayed faceless. CURED: the numbered line keeps its one angle tag; three `- [face]` sub-rows follow (`FACE_ROW_RE`); a second tag is malformed.
2. **THE CLAIMS.** The rules said "keep every claim the variant carried and add none"; the old sentences carry UNLICENSED claims (a cause, a second fact, a forecast, a standpoint) that the rewrite exists to drop, so the refuters convicted the draft and the refinement alike ("inherited on the old row and the draft face alike") and the judge's rule 4 banked the pool. CURED: the rewritten variant carries exactly the LICENSED claim set of the old sentence; an unlicensed old claim is dropped (the cure, never a finding); the four faces are claim-equal to EACH OTHER (A6 reads across the faces, not back to the old row); never add a claim.
3. **THE UNRESOLVED POOLS.** Four of DEF-1's eight pools (the readiness bands), all seven of DEF-3's (the safety labels), five of DEF-4's nine (the capture states) are `WIRING-UNRESOLVED` in the census: their licence card licenses nothing beyond the reading, so every face fails "unlicensed" by construction. ARCH §8.2's own rule — `UNRESOLVED → NO-LIST-ROW: wiring first` — applies to the rewrite too. CURED: `rewrite/block-args.mjs` now lists only RESOLVED pools for a block and prints the rest as `wiringDebt`; a WIRING car per affected block (the SEAM 3h shape: the key table exposed, key identity proven over 768 + the exhaustive sweep, zero drift) lands BEFORE those pools are rewritten in a second pass. The defense desk's wiring car (8b-W) covers DEF-1 (readiness bands via `scoreBand`), DEF-3 (the safety labels), DEF-4 (the capture states) and whatever DEF-6…10 print — chartered as ADDENDUM 4.
The three blocks are RE-RUN from fresh docks cut at f73bdbf16 under the corrected rules (the first attempts stand sealed as history, never trimmed). The taste's own pools (DEF-11) were never at risk on defect 3 (all RESOLVED) but ran under defects 1 and 2.

## ADDENDUM 4 (chair, 2026-09-09 13:5x) — CAR 8b-W: THE DEFENSE DESK'S WIRING CAR (an Opus seat in `laneRW-DEFW` at f73bdbf16; the SEAM car 3h shape; lands FIRST in the defense consist)
THE DEBT, from `rewrite/block-args.mjs` at f73bdbf16 (RESOLVED / UNRESOLVED per block): DS-DEF-1 4 / 4 (the readiness bands STRONG · ADEQUATE · WEAK · CRITICAL); DS-DEF-3 0 / 7 (the safety labels Very Safe … Dangerous, the COMPOUND override, the First-Survey qualification); DS-DEF-4 4 / 5 (capture none · adversarial · equilibrium · corrupted · capture); DS-DEF-6 3 / 18; DS-DEF-7 0 / 11; DS-DEF-8 3 / 1; DS-DEF-10 0 / 21; (DS-DEF-2, -5, -9, -11: 0 debt). 62 pools in seven blocks cannot be gated until their key functions are RESOLVED by the census.
THE JOB (read first, whole: `receipt-seam.md` § CAR 3h — the shape; `src/domain/prose/wiringCensus.js` (the four-rung ladder LITERAL · TEMPLATE · TABLE · UNRESOLVED and the `reason` per row); `docs/content/wiring-census.json` rows for the seven blocks with their `reason`; the desks `src/domain/display/stateProse/defenseStateProse.js` and its candidates leaf; ARCH §3.1–§3.3 and §8.2; SITTING §T.8): for each of the seven blocks, EXPOSE the key table the desk selects the pool by (a `scoreBand` for the readiness bands, the safety-label table for DS-DEF-3, the capture-state ladder for DS-DEF-4, DS-DEF-6's `DEF6_C3_BLOCKED_POOLS` (13 are BLOCKED by ruling — they stay listed as blocked, never wired around), and the tables behind DS-DEF-7, -8, -10) as a named, frozen export the census's TABLE rung can read — the 3h idiom: the table exposed, key identity proven over the 768 RATE towns AND the 1,050 DRIFT rows AND an exhaustive input sweep (every key function's output equals the table's row for every input; zero drift on the manifest classifier — UNCHANGED 73,284 — because a wiring car moves NO rendered byte), the census re-taken and stamped by the census rule (`--dry` first: rows and sections printed; the RESOLVED count per block before and after), `readsCount` on the newly resolved rows, and the licence card printed for one newly resolved pool per block (`node scripts/prose-licence-card.mjs <block> '<pool>'` must now print a predicate and a `may claim` line). Pools no key function produces stay UNRESOLVED with their `reason` (print them: they are WAVE-time debt, never forced). One commit per block ('REWRITE car 8b-W-<n>: <block> wired — <k> pools RESOLVED'), then the register rituals as the receipt's three-commit shape (the wiring census re-take; the lighting census by ritual if a test title moved; OSR shrink-only). ACCEPTANCE at the last commit: `tests/lint` whole green; `tests/copy/voiceMechanics.test.js` at its inherited two files; the projection contract; `check-domain-strict` on its ceiling; `typecheck:ratchet` 173/173; the manifest classifier UNCHANGED 73,284 from f73bdbf16; `tests/ui` whole green. Receipt: `receipt-rewrite.md` § CAR 8b-W (PARTIAL header first). Return: the RESOLVED count per block before and after, the tables exposed by name, the pools left UNRESOLVED with reasons, every acceptance figure, the shas and the tip. The seven blocks' second writing pass runs on docks cut at the consist tip AFTER this car is consisted.

## ADDENDUM 5 (chair, 2026-09-09 14:5x) — CAR 8b-W LANDED (`laneRW-DEFW` tip 290f86ee0, seven commits: DS-DEF-1 · -3 · -4 · -6 wired, RESOLVED 340 → 361, keyTables 33 → 38; the census re-take; the OSR re-freeze; the prose byte ratchet's declared row for the 525 `readsCount` bytes); THE CHAIR'S RULINGS; and CAR 8b-W-5
1. **The DS-DEF-3 narrowing ACCEPTED**: the exposed table answers silence for eight nonsense inputs the old `CORPUS[...]` lookup answered with a pool key; unreachable over 768 RATE towns (30 distinct labels, none of the eight); pinned by its arm; a declared narrowing, never a rendered byte.
2. **The false attribution (`DS-GEN-6 :: isolated` resolving on rung 1 against the defence desk's comparison literal) is RECORDED, the cure CHARTERED to the 8b consist's cure car**: rung 1 takes a literal only where it is RETURNED by the key function, never where it is compared; the cross-desk scan (1 at f73bdbf16 → 0 at the tip) becomes an arm.
3. **⭐ THE LICENCE CARD IS BROKEN FOR EVERY TABLE-RUNG POOL** (`may claim: that \`js)\` (=== STRONG) holds` — the card names the read's last dot-segment and a table-rung label ends in `defenseStateProse.js)`; inherited from SEAM 3h's tables, now on 38 tables): CONFIRMED by the chair on DS-DEF-2 and DS-DEF-1 (DS-DEF-11's dotted read prints correctly). CONSEQUENCE: DS-DEF-2's and DS-DEF-1's second-attempt writers read that card — both workflows STOPPED at 14:4x; their docks are sealed as attempt 2 and re-cut at the cured tip; DS-DEF-11 (dotted reads) continues. CAR 8b-W-5 (an Opus seat in laneRW-DEFW) cures the expression with a 708-pool sweep arm; it lands in the consist before any block's second launch.
4. **The 41 pools left UNRESOLVED are not wiring debt**: 32 in UNMOUNTED blocks (DS-DEF-7 × 11, DS-DEF-10 × 21 — no composer exists; a SURFACES-train question, never a rewrite), 13 `DEF6_C3_BLOCKED_POOLS` by ruling, 1 `DEF8_UNREACHABLE_POOLS`. DS-DEF-7 and DS-DEF-10 are struck from the defense desk's REWRITE (their sentences stay shipped; listed in the §920 row); DS-DEF-6's 8 resolved pools are its rewrite.
5. **The block docks from here are cut at the CURED 8b-W tip** (the consist dock IS laneRW-DEFW's lineage: 8b-W and 8b-W-5 land first); `rewrite/consist-defense.sh` takes each block dock's base as the merge-base with the consist dock, so DS-DEF-11's dock (cut at f73bdbf16, annex section untouched by 8b-W) still applies.

## ADDENDUM 6 (chair, 2026-09-09 18:5x) — THE DENSITY FLOOR against the SHIPPED sentence
DS-DEF-11's apply commit `159d6d285` (attempt 3: 12 variants, 10 faces reverted, 3 refusal rows) reads lawful and flatter than the shipped exemplar: `WALLED-STRAINED` v1 shipped as "{settlement}'s {defwork} stands better than the watch that should man it; stone keeps itself, and wages do not." and stands rewritten as "The {defwork} at {settlement} is the town's. Its muster is paid short of upkeep." — every claim licensed, the owner's turn gone. The rules compared density only against the DRAFT, so the shipped line's compression was never a floor. RULED (the owner's density law, Part B §21.4, applied to the shipped sentence as well): a rewrite may not state the same licensed fact more plainly than the shipped sentence with no law behind the change; a shipped clause lawful under the card may stand verbatim as ONE of the four faces; only the unlicensed part of a shipped sentence is dropped. Landed in `RULES` of both workflow scripts (future launches) and in the refuters' grounds; the consist skeptic's judgments lens (e) now reads every kept face against the shipped sentence and lists lawful shipped clauses dropped rather than kept — a chair cure at the consist restores each as a face. DS-DEF-11 (the owner's exemplar block) is the first such cure; the blocks in flight (DEF-2, DEF-1, DEF-5) ran their drafts under the old rule and are read by the same lens. JUDGMENT: chose the floor over accepting the flattening because the density law is the owner's word twice over — say "veto" to accept plainer licensed lines.

## ADDENDUM 7 (chair, 2026-09-09 19:1x) — THE COMPOSITION GOT WORSE: attempt 3's rewrite read as INVENTORY LINES; the SKELETON phase and three more rules
The chair read DS-DEF-11's apply commit (`159d6d285`, sealed `rw-def11-attempt3-2026-09-09`) against the shipped rows. Shipped: "{settlement} keeps its {defwork} because the country requires it; the threat is on the town's books as plainly as the grain." Rewritten: "{settlement} has the {defwork} standing to its name." Shipped WALLED-QUIET: "The town pays little for its {defwork} now that it asks little of it; built work stands on its own patience." Rewritten: "Set down as standing, the {defwork} stands." Every claim licensed, every sentence empty: the writers dropped even the LICENSED second read (the live threat is on the card), ignored the angle tags, and wrote twelve near-identical faces per pool; the refuters passed most of them. The licensing rule was read as "at most" and the safest output under a strict gate is a tautology. All three running blocks (DEF-2, DEF-1, DEF-5) STOPPED at 19:0x; their and DEF-11's third attempts sealed; the docks re-cut at f2da5a3ee.
THE FIX, landed in `rewrite/rewrite-block.workflow.js` (parse ok): (1) a MARK phase before the draft — a Fable MARKER per pool writes `<pool dir>/skeleton.md`: every shipped variant's claims tagged LICENSED (with the card field) or UNLICENSED (with the law), THE READS THE REWRITE MUST STATE (every read the card names plus every licensed claim of the shipped sentence), the ANGLE's stance for this pool, the shipped turns worth keeping verbatim, and what would make the rewrite a regression; the drafter writes TO the skeleton; (2) THE SKELETON RULE in RULES: all of the card's reads stated, in the angle's stance, the weight of each dropped unlicensed clause replaced with licensed specificity, never with nothing; (3) AN INVENTORY LINE IS NOT A REWRITE — a variant stating only the key fact with no angle and no second read is REFUSED by the gate (compared against the skeleton) and failed by the refuters; (4) the four faces differ in CONSTRUCTION, not vocabulary alone; (5) ADDENDUM 6's density floor stands. VALIDATION before any other block: DS-DEF-11 alone (attempt 4) is run and READ by the chair against the shipped rows; the desk continues only if the rewrite is at least as rich as the shipped text where the card allows and richer in truth everywhere.
THE HONEST LIMIT (told to the owner): where the card licenses two facts and the shipped sentence's richness was unlicensed invention ("recently attended to"; "the town checks it"), a faithful rewrite is plainer by design; richness must come from the world (the holder table, the pay gate, the tier) and from the angle, not from the sentence. The taste's modifier pools did not show this because a modifier ADDS a fact; the spine rewrite REPLACES prose that was written before the licence discipline.

## ADDENDUM 8 (chair, 2026-09-09 20:1x) — THE VALIDATION BLOCK'S FIRST ROUND, and two rulings the marker asked for
DS-DEF-11 attempt 4 (`wf_dc0e55ca-00d`): the skeletons landed for all five pools and round-1 drafts for four. The marker found THREE licensed reads on `WALLED-THREATENED` (the wall; the live threat; the pay gate at identity), tagged every unlicensed clause with its law, and kept "{settlement} keeps its {defwork}" as the turn to carry; the round-1 draft states all three reads in each face with an angle ("Danger stands in the country, and {settlement} keeps its {defwork} at full charge." · "The threat is live. At {settlement} a {defwork} stands, and its upkeep wants nothing."). The chair's reading: the inventory-line defect is gone at the draft; the density is fair; the gate, the refinement and the refuters follow; the chair reads the whole block before any other block launches.
RULINGS on the marker's three fences (vetoable): (1) THE THREE READS ARE ONE KEYED CONDITION — a face stating the wall, the live threat and the paid keeping states the state the key names; that is not "a second fact" under the card, and the skeleton rule requires all three. (2) THE CARD BINDS ON CAUSE — the block's title "why the wall" is its name, not a licence; a face never says the wall stands BECAUSE of the threat (no event-provenance field; S2's clause seat needs a relation row the engine computed, and a conjunction key is not one); the reader draws the why from three standing facts placed together, which is the design. (3) THE GATE READ IS STATED — the card prints `economicGates.military` as a read, so the keeping-paid fact is part of every face at this key (ARCH §6.3's proposed `NARROWS: gate` stays un-ruled; the census stands un-narrowed).
RECORDED for the fold: the census row says `{defwork}` has no provider (`slotsWithoutProvider`) while the desk mints and fills it at render (the annex's SLOTS line) — a census reading to correct or a real gap; the consist skeptic's fences lens checks a rendered unit for an unfilled `{defwork}`.

## ADDENDUM 9 (chair, 2026-09-09 23:3x) — THE OWNER'S PRINCIPLE FOR THE REFINEMENT JUDGE, the exact licences "stone keeps itself" lacked, and the chair's pre-read of the validation block
THE OWNER (23:3x, a reflection on the 20:1x state; binding as the owner's stated view): the plainer floor is a BETTER floor precisely because it is less literary than the strongest shipped sentence, and that is not a regression; the order of the work is TRUE → COMPETENT → VARIED → REFINED → MEMORABLE WHERE LICENSED; the refinement judge's question is **"what is the most memorable sentence that can be written without increasing the claim set?"**; the prose may be more elegant than the data structure but never more knowledgeable than the simulation; the shipped sentences are NOT an unconditional benchmark, since some are memorable because they cheat (the memorability of an unlicensed line is evidence that the old system bought effect with unsupported information, not that the new line is inferior); some facts will generate magnificent prose and some plain prose, and the richness of the prose is indirectly the richness and coupling of the world; the block is read WHOLE, because the voice exists at the level of the record, not the sentence. Two refinement targets the owner named: a face that "sounds like a writer satisfying a stylistic instruction rather than someone keeping a record" (the UNWALLED-LARGE misparse below), and a repeated phrase across a face family ("no live threat") as a corpus-level mannerism, not a truth fault.
THE OWNER'S QUESTION, answered exactly — which claim in "{settlement}'s {defwork} stands better than the watch that should man it; stone keeps itself, and wages do not" lacked a licence (the STRAINED skeleton, §1 (3) and §3): FOUR, and one of them is the whole rhetorical move. (i) "stone" — the MATERIAL: the card's wall read is `forces.walls.present` (presence) and the slot fills with the RECORDED wall name, which is `palisade` or `earthwork` on many towns, so "stone" is false there; (ii) "stands better than" — a CONDITION of the wall (sound, whole, holding) compared against the muster's: no field reads the wall's condition on this branch, only its presence; (iii) "the watch that should man it" — the WATCH is a different institution from the muster the gate measures (the holder table's walls row is the muster; the watch is `watch: bought`'s holder), and "should" is a duty the record does not hold; (iv) "stone keeps itself, and wages do not" — a MAXIM about the world in the maxim's form. What is NOT missing a licence is the asymmetry itself: the generator's own recorded law is that BUILT WALLS KEEP STANDING while unpaid soldiers desert slowly (the block's PROVENANCE line quotes it as "the generator's own recorded rule, not an authored flourish"), and the chapter law (CT-0 §2, R-DST-W4-a) is that STRUCTURAL cause is licensed and HISTORICAL cause is record-gated. So the compression the owner is pointing at survives if it is written as the engine's structure in this town's terms and nothing else: the wall's presence needs no pay to stand, and the muster's does — no material, no watch, no condition word, no maxim form. THE CHAIR'S PROPOSED RULING FOR THE FOLD (fence 2 of the THREATENED skeleton, open row 1; the STRAINED skeleton §3 second bullet), vetoable: on WALLED-STRAINED the structural asymmetry is LICENSED as a clause because both its halves are fields on the key (`walls.present` true; `economicGates.military` below one) and the asymmetry is the generator's recorded rule; on WALLED-THREATENED "because the country requires it" stays UNLICENSED because no engine rule joins the threat to the wall (the key is a conjunction of two reads, not a computed relation). The register car after the consist may re-open STRAINED's faces under that ruling as a cure; the drafters do not act on it until it is ruled at the fold.
THE CHAIR'S PRE-READ OF THE VALIDATION BLOCK (kept.md ×5 at 44b8b7a50, read against the shipped rows and the skeletons BEFORE the refuters reported, so the refute phase can be measured against an independent reading): lawful and claim-equal across every face; six findings the refuters should catch, listed in the RESUME-NOTE entry of 23:2x as (a)–(f) — the UNWALLED-LARGE misparse ("The town of {settlement}'s weight stands…", the article change that the drafter made on R-DA-12 turned the shipped generic frame into a wrong parse; the cure is another frame), the "has standing" idiom, the roll named as source on all four faces of QUIET v3 and one face there with no threat read, the condition words "holds"/"whole" grazing THREATENED faces, the intent frame "holds nothing live against", and "is a village at the most". Whatever the judge does not revert is the chair's cure at the register car, recorded there by finding letter.
OWNER 23:4x, on the material: "maybe an elegant solution to this is just a synonym for stone, which would be rampart or something similar that is devoid of material." THE CHAIR'S ANSWER (recorded so the STRAINED refiner and the fold both see it): the material-free noun already exists and it is the SLOT — `{defwork}` fills with the settlement's RECORDED wall-class name (wall · citadel · palisade · earthwork · inner citadel · massive walls), which is exactly a noun devoid of a baked material; the class words the skeletons already license (the wall, the work, the circuit, the enclosure) are the other lawful spellings. "Rampart" specifically is NOT in the recorded name class, so baked into a face it would name the same object twice, once by a noun the record never wrote (the SLOTS law: "by its RECORDED name, never a baked or invented noun"). The reconstruction the owner is reaching for is therefore "The {defwork} keeps itself, and the muster's wages do not." — the material (i) and the watch (iii) are gone by the slot and by naming the muster; what remains is ONE ruling, fence 2 on STRAINED: "keeps itself" is read as the generator's recorded rule (a built wall stands without pay) and not as a condition read, and "the muster's wages do not" is THIS town's gate read and not a maxim about wages. Under the chair's proposed fold ruling (above) that sentence is LAWFUL on WALLED-STRAINED; "keeps itself" is the idiom of durability (as food keeps), not an intent for an inanimate thing, and the ruling says so in words so a refuter does not fail it on R-DA-11. The refiner does not write it until the fold rules; the register car may seat it as the cure.

## ADDENDUM 10 (chair, 2026-09-09 23:5x) — THE ENTAILMENT LAW (draft for ratification at the 8b fold; the survey `rewrite/entailment/` builds its table)
THE OWNER (23:5x): "I do want to add a bit of flexibility where appropriate. A wall is made of stone. Palisades is specifically made of wood. That can just be assumed this common sense. The watch is the guard/military power. The other things that you have mentioned as false in that statement, I agree with. But think about … counterparts to all the other variations in other situations."
THE LAW, as the chair drafts it (vetoable; binding on the remaining 8b blocks once the table is ratified; the drafters read it as an ADDENDUM until the licence card prints it):
1. **A recorded noun licenses what the word MEANS, never what the thing typically HAS.** A palisade is timber; a wall of the stone class is stone; an earthwork is earth; a citadel is a stronghold; a mill grinds; a well holds water; a ferry crosses water; a watch keeps watch. These DEFINITIONAL attributes ride with the recorded name and a face may say them without a second field. Age, height, condition, manning, prosperity, a cause, a history, a count, a season, what the thing is usually for elsewhere: NOT entailed; each still needs its own read.
2. **The entailment attaches to the RECORDED MEMBER, not to the class word.** The slot renders the town's recorded name, so an attribute that varies across the class (the wall's material: stone for wall · citadel · inner citadel · massive walls; timber for palisade; earth for earthwork) may only be spoken through a DERIVED FILL computed from the recorded name (a `{defmaterial}` slot, minted by the desk from the name class, is the wiring the register car owes), never baked into a face as a constant. An attribute constant across the class (a wall encloses; a watch keeps watch) may be baked.
3. **An entailment is licensed only where the ENGINE'S OWN MODEL is consistent with it** (the owner's principle: the prose is never more knowledgeable than the simulation). The generator's recorded rule is that built walls keep standing whatever they are made of and unpaid soldiers desert slowly (`src/generators/defenseGenerator.js:182-192`, the upkeep gate on "garrison wages, wall maintenance"). So "the {defwork} keeps itself, and the muster's wages do not" is the engine's own asymmetry and is LICENSED on WALLED-STRAINED (ADDENDUM 9's fence-2 ruling); "timber rots" or "stone endures" is real-world knowledge the model does not hold and is REFUSED even where common sense agrees, because it predicts a decay the world never runs.
4. **LABEL TRAPS: an engine value is not an English word.** `config.monsterThreat = plagued` means plagued by MONSTER activity (`src/components/new/SummaryTab.jsx:37`), never disease; `settled` means no live threat, never founded. A face renders the engine MEANING of a label and never its dictionary sense; the survey lists every label the desks read with its engine meaning quoted from code.
5. **ALIAS TRAPS: a generic English word may name a class the engine splits into rows.** The engine has a Watch (`inst.hasWatch`), a militia (the muster; the Citizen militia), mercenaries, a charter hall and a garrison as distinct institution flags all feeding the military score and all gated by the same upkeep multiplier (`defenseGenerator.js:178-192`). The owner's "the watch is the guard/military power" is right as English and the law adopts it AS A CLASS WORD: "the guard", "the muster", "the men on the wall" are always-safe spellings of the paid military the gate measures; "the watch" as the institution's NAME follows the holder-table row this town resolves (S3: the source of each construction), so it is CONDITIONAL on `hasWatch` and the derived holder fill is the wiring that makes it safe. The same rule reaches every desk: "the temple" vs the recorded faith-house class, "the market" vs the recorded market band, "the council" vs the recorded ruling structure.
6. **The gate does not walk semantics; the refuters do.** The mechanical gate cannot tell an entailment from an added claim (the taste's blind spot), so the table is the REFUTERS' instrument: a Fable refuter passes an attribute in the ENTAILS column, fails one in NOT ENTAILED, and fails a face that uses a CONDITIONAL entailment without its condition resolved. The licence card prints `entails:` lines per read once the table is ratified (a REWRITE instrument car at the consist, alongside the `{defmaterial}` derived fill).
WHAT THE SURVEY (`wf_8ca05b10-e44`: one Opus surveyor + one Fable refuter per desk, a Fable folder → `rewrite/entailment/ENTAILMENT-TABLE.draft.md`) OWES: the table per desk (noun · class members · ENTAILS with the refuter's verdict · NOT ENTAILED · ENGINE CONTRADICTS · source), the merged label-trap and alias-trap tables, and the CONDITIONAL rows that need a wiring decision. The chair ratifies the table into this brief and into the workflow's RULES before DEF-2 / DEF-1 / DEF-5 launch, so no block is drafted under one law and judged under another.

## ADDENDUM 11 (chair, 2026-09-10 00:1x) — THE REFERENT LAW (draft; a sibling of ADDENDUM 10; the referent survey follows the entailment survey)
THE OWNER (00:0x): "words can also be related to both the power and/or faction or individual institution or both, and so laws must be made to decide which one it attributes and that situation."
THE ENGINE ALREADY TYPES THE LAYERS, so the law is a mapping and not an invention (all cites in laneRW-DEFW at f2da5a3ee):
- **BODY** — an institution row (`settlement.institutions[]` by recorded name), bucketed for defense by `src/domain/institutions/defenseInstitutionBuckets.js:83-104` (walls · garrison · militia · watch · mercenary · charter). The engine's own alias overlap is on the record: "professional city watch" sits in BOTH the garrison and the watch buckets.
- **HOLDER (the record's keeper)** — `src/domain/prose/holderTable.js:78` HOLDER_KINDS (treasury · muster · census · parish · toll-bar · market · watch · court · elders · tradition · road · office); the paid military the upkeep gate measures is the MUSTER kind (walls · garrison · militia · mercenary · charter, lines 188-192); the WATCH kind is a STATE ORGAN (line 115: office · court · treasury · watch) that keeps the order records (`criminalCaptureState`, `blackMarketCapture`, `safetyProfile`, lines 210-212). So in THIS engine "the watch" is two things by table: a defense BODY (`forces.watch.present`, DS-DEF-5) and the state's order ORGAN (a holder). The owner's "the watch is the guard/military power" is English; the engine splits it, and the chair's earlier sentence ("the watch is a class word for the paid military") is CORRECTED here: the class word for the paid military is THE MUSTER; "the guard" is a body word (garrison bucket: professional guard); "the watch" names the watch bucket or the order organ and never the muster as a whole.
- **POWER** — a typed standing over an organ: the settlement-wide capture ladder `powerStructure.criminalCaptureState` (none · adversarial · equilibrium · corrupted · capture) and the per-faction `captureState` (`holderTable.js:129-143`, `factionCapture.js:136`), which make the four state organs INTERESTED in their own records (SITTING §R c-22); a per-institution corruption impairment on a SECURITY body (`corruption.js:630` SECURITY_INSTITUTION_RE = watch · garrison · constab · guard · magistrate · court · barracks; `impairments[].type === 'corruption'`, `covert` true = the DM's hidden channel, else a public scandal, lines 655-680); a brokerage house's PATRON (`brokeragePatronage.js:60` genesis · captured). The power is a FACTION or the ruling structure, and a faction is a NAME the engine records (a `proper`-typed slot), never a baked noun.
- **PERSON** — NEVER a referent: `COLUMN_SOURCES.holderRole` is a measured null (no typed NPC-to-institution edge exists; `holderTable.js:32-36`), the DM face names the office and never the officer, and product scope forbids a named character's fate. An individual appears only as a ROLE word (the captain, the reeve) in a standing state.
THE LAW, as the chair drafts it (vetoable):
1. **A word's referent is fixed by the layer of the READ the sentence carries, never by the word.** A body read (presence · pay · upkeep · muster · service rows · walls) refers to the INSTITUTION AS A BODY and uses body words (the muster, the garrison, the militia, the watch as a bucket name, the men on the wall). A standing read (capture · corruption impairment · patronage · INTERESTED) refers to the ORGAN UNDER A POWER and names the power only through the typed slot the engine records (the faction's name; "the ruling structure" as the class word), with the institution as the OBJECT of the sentence ("the watch is bought", "the house has a patron"). A role read (an office that exists) refers to the ROLE and states a standing condition, never a fate.
2. **The marker's skeleton tags every claim's REFERENT LAYER beside its licence** (BODY / ORGAN-UNDER-POWER / ROLE), and the licence card prints the layer per read once ratified; a refuter fails a face whose noun's layer does not match its read's layer ("the bought watch" on a pay read; "the muster's wages" on a capture read; a captain doing anything on any read).
3. **SAME WORD, SAME REFERENT inside a composed unit.** The thread rule (the owner, 09-08: adjacent sentences carry a noun forward) carries the REFERENT forward, not the spelling: a unit may not say "the watch" as a body in one sentence and "the watch" as a captured organ in the next without the layer change being stated in words. Where a town holds BOTH (a corruption impairment on a security body AND a pay shortfall on the muster), they are TWO facts with two referents, seated as two units; a fused agent ("the bought watch is paid short") asserts a relation no field computes and is refused unless a relation row exists (S2's clause seat).
4. **Visibility follows the power layer.** A covert corruption impairment or a birth capture is the DM face (the pen line beside the passage, SITTING §T); the player face says what the state's organs would admit, which is the body read alone. A revealed impairment is a public scandal and both faces may name it.
5. **The alias overlap inside the engine is a wiring fact, not a writer's.** "professional city watch" in two buckets, and the WATCH holder kind that is not the watch bucket, go to the register car as a census/holder finding; until cured, a face never uses "the watch" for a pay-gate read (the muster kind does not contain the watch bucket).
WHAT THE REFERENT SURVEY OWES (queued to run after the entailment survey `wf_8ca05b10-e44` completes, same shape: one Opus surveyor + one Fable refuter per desk, a Fable folder → `rewrite/entailment/REFERENT-TABLE.draft.md`): for every institution-class noun each desk can render, its layers (body / holder kind / power / role), the reads that resolve to each layer, the engine's own overlaps, and the typed slot that names the power where one exists. The chair ratifies both tables together before DEF-2 / DEF-1 / DEF-5 launch.

## ADDENDUM 12 (chair, 2026-09-10 00:4x) — THE VALIDATION BLOCK JUDGED: the eight rulings closed, THE CURE ROUND chartered, rule 4 re-cut to the face, ten writer rules from the refuters' findings
THE RESULT (`wf_dc0e55ca-00d` resumed; dock laneRW-DEF11 at 7acc5ff1c = the refinement's 48 wordings committed, 0 reverted): the five Fable refuters read 48 wordings and returned PASS 18 · WITHHELD 5 · FAIL 25, every FAIL with a law and a quote; the gate's owned arms read FAIL 0 on every pool at every commit (the taste's blind spot, measured again); the judge applied the rules honestly and reverted NOTHING, because in every pool at least one failed face stands in the draft too (rule 4 froze the pool), so the block went forward with 25 refuter failures standing. THE CHAIR'S PRE-READ (ADDENDUM 9, six findings) against the refuters: (a) the UNWALLED-LARGE misparse CAUGHT; (c) QUIET's threat read unstated and the roll as source CAUGHT; (d) "holds"/"whole" CAUGHT; (b) "has standing" not charged but its face failed on another ground; (e) and (f) read the other way by the refuter, and the chair lets those two stand. The refuters found what the chair did not: the POSSESSOR BINDING across STRAINED (a sentence-initial "Its" after a {defwork} subject makes the wall's muster, the shipped watch by another route), the TOWN-SCOPED threat negation (C7 against DS-DEF-2's war pressures on the same page), the CONSTRUCTION COLLAPSE in SMALL (the refiner moved variant 2 onto variant 1's grammar), the doubled beat, the dangling "it", the band marker dropped. The refute phase is doing the semantic gate's work; it stays exhaustive.
THE EIGHT RULINGS THE JUDGE OWED (vetoable; they bind this block's cure round and every block after):
R-i THE THREAD AT k = 0: YES — a spine's own second sentence carries a noun forward from its first REGARDLESS of k, because a face is written once and composed under every k the census later rules, and "sits last" is a property of the passage the writer cannot see. WT 1-f1 and 3-f1 convert to FAIL and become cure targets (3-f1 keeps the shipped floor "{settlement} is enclosed").
R-ii A NEGATED SURFACE ON A PRESENT READ IS NOT AN ABSENCE OPENER under MOVE-GRAMMAR wall 3 — the typed move vocabulary governs and the instrument agrees (the owned arms did not red). WT 2-f1 and UL 1-f2 convert to PASS. At most one such opener per variant.
R-iii "asks little of its {defwork}" IS NOT the monsterThreat read: it is a usage frame (the town's demand on the wall), a standpoint the card refuses; the ledger states the threat read in the COUNTRY's terms (the country is quiet; the country carries no live threat). The skeleton's §3.6 was wrong and its §2.3 right. WQ 3-f0 and 3-f2 are cure targets.
R-iv ORDER ALONE DOES NOT CARRY THE [unfolding] ANGLE: the unfolding variant realises the OPEN move (the shortfall as a matter standing open now — "stands open", "stands unmet", "is owed") after the wall's presence (V6, PRESENT then OPEN); a face built as the ledger's measure-against-the-roll under the unfolding tag is a dropped angle. WS 2-f0 converts to FAIL and is a cure target; its own 2-f2 ("stands open") is the model once the possessor is cured.
R-v CLOSED at ADDENDUM 8 (1): the reads of a key are one keyed condition, never "a second fact".
R-vi THE ROLL: the office's own formula ("entered", "on the roll", "carried standing") is the ledger's SURFACE and lawful; the roll as an AGENT-SOURCE ("The roll shows …", "The roll sets down …") is a citation of a source the budget does not license (§24 reads zero here; the instrument's F25 finding takes the same side). WQ 3-f2 and 3-f3 are cure targets on this word class.
R-vii `NARROWS: gate` stays a wiring ruling for the register car; every face of THREATENED and QUIET states the gate as instructed (unchanged).
R-viii THE STRUCTURAL JOINT (ADDENDUM 9): LICENSED on WALLED-STRAINED as the engine's own recorded asymmetry (built walls keep standing whatever their material; unpaid soldiers desert slowly: `defenseGenerator.js:186`) — the cure round may seat "The {defwork} keeps itself, and the muster's wages do not." (or the writer's own words on exactly that asymmetry: the wall's standing needs no pay, the muster's does) as ONE face of STRAINED variant 2, and the refuter passes it under this ruling ("keeps itself" is the idiom of durability, not an intent; "the muster's wages do not" is this town's gate read, not a maxim). NOT licensed on THREATENED (nothing in the engine joins the threat to the wall).
THE CURE ROUND — CHARTERED (JUDGMENT, vetoable: the owner's arc is "iterate into the bands by evidence, then ONE refinement round"; the refuters' FAILs are the band at the semantic grain, and rule 4 proved a revert does not reach them, so the iteration at that grain is a CURE round, not a second refinement): after the refute phase, every FAIL face and every WITHHELD a ruling converts is a CURE TARGET carrying the refuter's quote and named cure; an Opus curer per pool rewrites ONLY the targeted faces (every other face byte-identical; the variant count, tags, slots and order untouched) under the rules, the skeleton and the chair's rulings; the Opus gate applies the packet verbatim, runs the projector and the wave gate (owned lawful; the face-count ratchet) and commits 'REWRITE 8b <BLOCK> cure round N: <targets cured>/<targets>'; a Fable refuter per pool re-refutes the CURED faces on every ground and re-reads the pool WHOLE for spread (A5, A11, the construction contract, the same-page C7); a cured face that still FAILs goes to a second cure round; after TWO cure rounds a face still failing is a FACE-LEVEL REFUSAL ROW (it stands as it is, banked, listed for the register car with its finding); the judge then applies the face-grain rules and the APPLY gate runs tests/ui whole. The ten "clean carve-outs" the judge listed (WQ v1 f2, v1 f3, v2 f1, v2 f3, v3 f1; WS v2 f1; US v1 f1, v1 f2, v2 f0, v2 f1) are AVAILABLE to the curer as the cure where the draft face is lawful, with each hazard the judge noted on it fixed in the same stroke.
RULE 4 RE-CUT TO THE FACE (for every block from here): a face whose revert would restore the same breach is a CURE TARGET, never a pool freeze; the pool's other rule-1 reverts proceed. The block workflow gains the cure phase after Refute and before Judge; `rewrite-block-cure.workflow.js` runs it on DS-DEF-11 now from 7acc5ff1c with `rewrite/cure-DEF11.json` (29 targets: WT 6 · WQ 8 · WS 7 · US 6 · UL 2).
TEN WRITER RULES (from the refuters' finding classes; folded into the workflow RULES for every block): W1 POSSESSOR BINDING — a possessive pronoun after a clause whose subject is the {defwork} or any object binds to that object; seat the town as the possessor ("the town's muster") or drop the possessive ("the muster"). W2 THE THREAT IS COUNTRY-SCOPED — the monsterThreat read is stated over the country, never as a totality over the town ("nothing threatens {settlement}"), because DS-DEF-2 carries war and other pressures on the same page (C7). W3 THE BAND MARKER — a tier band carries its marker ("village size or under", "a town or larger"); the bare value is a value and contradicts the head record on the other tiers of the band. W4 THE CONSTRUCTION CONTRACT — the draft's declared grammar per variant is the refiner's to keep; moving a variant onto its sibling's construction is a regression. W5 THE NAMING-FORM ARTICLE — "the town of {settlement}" is the naming form; a frame that needs the generic article to carry a band ("a town of X's weight") is a maxim frame; state the band as a band. W6 NO DOUBLED BEAT — a clause that restates the read it follows is the summarising beat. W7 THE ROLL — R-vi. W8 THE ANGLES — the unfolding realises OPEN (R-iv); the visitor carries the gate only as the wall's standing state ("kept at full cost"), never as the town's act or an accounts fact; the ledger enters and measures, and cites nothing. W9 ENTAILMENTS ARE MAY, NEVER MUST — the density floor counts the card's reads, not the entailment table's attributes (ADDENDUM 10 does not raise the floor). W10 A NEGATED SURFACE ON A PRESENT READ is not an absence opener, one per variant (R-ii).
INSTRUMENT ROWS carried to the register car: the walk-figure gap (top-level WITHHELD 11 / PASS 37 against per-pool sums 7 / 41 on the same 48 units, the attempt-3 shape again); the per-pool `rounds` object carries no counter; `{defwork}` NAMED BUT NEVER FILLED against the desk's `defworkFill`; the `inner citadel` and `massive walls` fill hazards; the C7 town-scoped threat class to sweep estate-wide.

### ADDENDUM 12 — AMENDMENT (chair, 2026-09-10 01:1x): R-viii CORRECTED on the owner's reading of the gate — BOTH the wall's keeping and the muster's wages sit under ONE purse
THE OWNER (01:0x): "you are separating the fact that muster wages and the wall upkeep are both not affected by the economy and finances. We're looking at things at a macro level so there can be some variations between the wall is stronger than the muster in terms of pay for upkeep but both are suffering."
THE ENGINE, re-read (`src/generators/defenseGenerator.js:182-192`): the economic-upkeep gate is ONE multiplier (`milUpkeepMult = min(1, 0.6 + econOutput/50 × 0.4)`) over "garrison wages, wall maintenance" TOGETHER, applied to the whole funded portion of the military score above the unpaid community baseline. There is NO per-institution split of the purse at birth: when the gate reads below one, the wall's maintenance and the muster's wages are short by the same measure. The generator's asymmetry is in the CONSEQUENCE, not in the pay: a built wall keeps standing (its presence survives the shortfall) while unpaid soldiers desert slowly (the muster's strength falls). So R-viii as written ("the wall's standing needs no pay and the muster's does"; "The {defwork} keeps itself, and the muster's wages do not") OVERSTATES the engine: it says the wall is kept while the muster is not, which is false — both are short.
R-viii′ (replaces R-viii; binds the cure round's re-refuters, who read this addendum whole): on WALLED-STRAINED a face may say (a) the shortfall lies on the wall's keeping AND the muster's wages alike (one purse), and (b) the {defwork} STANDS THROUGH the shortfall (the generator's recorded rule: built walls keep standing), as a standing fact; it may NOT say the wall needs no pay, keeps itself, or is kept whole while the muster is short; and it may NOT say the muster thins, deserts or is undermanned, because that consequence is the military SCORE, which is DS-DEF-5's cell (R-DST-A: DS-DEF-11 composes BESIDE the armed-forces surface, never over the same cell twice; the STRAINED skeleton bars a headcount). A face already written as "The {defwork} keeps itself, and the muster's wages do not" (or any wording that pays the wall and not the muster) FAILS under R-viii′ with the cure: the shortfall stated over both, the wall's standing stated as surviving it (e.g. "The {defwork} at {settlement} stands through the shortfall that lies on its keeping and on the muster's wages alike." — the writer's own words, at the same compression).
THE COUNTERPART, for every desk (the same ONE-GATE-MANY-THINGS pattern): the birth generators gate whole classes with one multiplier (`econHealthMult` over institutions generally; the upkeep gate over the paid defenses), so at BIRTH a face never splits a purse between two institutions of one class. Per-institution variation ("the wall is kept and the watch is not") is licensed ONLY where a per-institution field exists — the world-run layer's `institutionStatusModel` carries per-institution impairments with TYPED causes (a cause the table names, on one institution), so a world-run cell may say one institution is impaired while its sibling stands, citing that row; a birth cell may not. The owner's "the wall stronger than the muster in pay" variation at birth would need a per-bucket allocation of the shortfall in the generator (a policy: walls kept first, or wages first) — a NEW engine capability, owner-gated, recorded here as an option and NOT built. The entailment and referent surveys carry this pattern as a LABEL/ALIAS-class entry: "one gate over a class" is a fact about the class, never about a member.
THE MACHINERY THE OWNER ASKED ABOUT, verified (`defenseGenerator.js`): (1) TWO PURSES AT BIRTH, not one — the MILITARY purse (garrison wages + wall maintenance, `milUpkeepMult`, floor 0.6, lines 182-192) and the ORDER purse (watch wages, court and gaol funding, `internalUpkeepMult`, floor 0.65, lines 244-252) — both deterministic functions of the SAME `econOutput`, so they differ in DEGREE only and never in direction; the watch's pay is under the order purse and the muster's under the military purse (the referent law's split, confirmed by the generator). (2) THE CHAIN MODIFIERS are the per-thing variation the owner is reaching for (lines 589-601): the FORTIFICATION chain (healthy +6 "walls maintained", impaired −4), the GARRISON chain (healthy +5, vulnerable/impaired −5 "no provisions"), the MERCENARY chain (+4) — three independent supply-chain states from the economy's `activeChains`, so a town CAN have its wall maintained by a sound fortification chain while its garrison chain stands vulnerable, or the reverse, at birth. They are ENGINE FIELDS and they are NOT WIRED to the prose: no census row reads `chainModifiers` or a chain status (the DS-DEF-11 cards read `economicGates.military` alone). WIRING ROW for the register car (vetoable; a wiring car, not a new capability): add the fortification-chain and garrison-chain statuses as reads on WALLED-STRAINED (and on DS-DEF-5's surface), so a face MAY say the wall's keeping is provisioned while the muster's wages are short, or the reverse, exactly when the fields say so; until wired, no face says it. (3) THE WORLD-RUN counterpart: per-institution impairments with four typed causes (`institutionStatusModel.js:118`: supply_shortage · corruption_exposed · damage · siege_occupation) — a world-run cell may split two institutions by a named cause; none of the four is "unpaid", so pay never splits per institution in the world-run either.

## ADDENDUM 13 (chair, 2026-09-11 06:1x) — PART A: THE ENTAILMENT LAW RATIFIED AS CORRECTED; the writer bars W11–W19 until the wiring rows land; the disagreements ruled; the table adopted as the refuters' instrument (PART B, the REFERENT LAW, follows this addendum when `rewrite/entailment/REFERENT-TABLE.draft.md` lands; no block launches under part A alone)
THE TABLE: `rewrite/entailment/ENTAILMENT-TABLE.draft.md` (346 KB, 717 lines; six desks; 155 nouns; HOLDS 227 · CONDITIONAL 162 · REFUSED rows 80; 135 label traps; 41 alias traps; 20 wiring decisions O-1…O-20; 33 disagreements X-1…X-33), folded by a Fable folder from twelve packets (`wf_a8b0a386-355`, the fold phase of the dead run `wf_8ca05b10-e44`) and READ WHOLE by the chair on 09-11 between 05:5x and 06:1x. It is RATIFIED as the refuters' instrument for every desk, as the folder wrote it, with the corrections in section A; the chair re-rules nothing else in it. Every row keeps its `file:line` in `laneRW-DEFW` at f2da5a3ee.

### A. THE LAW, as ratified (ADDENDUM 10's six items re-cut; the numbering is kept)
1. STANDS. A recorded noun licenses what the word MEANS, never what the thing typically HAS. Age, height, condition, manning, prosperity, a cause, a history, a count, a season, what the thing is usually for elsewhere: NOT entailed; each needs its own read.
2. STANDS, SHARPENED. An attribute that varies across the recorded class is spoken only through a DERIVED FILL computed from the recorded name. The `{defmaterial}` fill is chartered with the value table of O-1: `Palisade` → timber; `Town walls` · `City walls and gates` · `Massive walls and fortifications` → stone; `Citadel` · `Gates (if walled)` · `Palisade or earthworks` → NO FILL (a variant naming the slot drops). UNTIL it is minted, no face names a wall's material (writer bar W11); a material SOURCE ("cut from its own woods", "the stone of the country") is NEVER licensed, because the fortification chain feeds every wall row quarried stone (`supplyChainData.js:873-884`). The two `{defwork}` residuals ("palisade or earthworks" and "gates (if walled)" reach the page as literals) are a wiring row for CAR 8b-W-2; until then a writer treats `{defwork}` as an opaque recorded name and writes no sentence whose grammar breaks on either literal.
3. CORRECTED. The sentence "the {defwork} keeps itself, and the muster's wages do not" is STRUCK from the law (X-31): R-viii′ of ADDENDUM 12 replaces it — ONE purse over wall maintenance and garrison wages; the wall STANDS THROUGH the shortfall; never "keeps itself", never the wall paid and the muster not, never the muster thinning. The rest of item 3 stands: the engine's own model bounds every entailment; "timber rots" and "stone endures" are refused even where common sense agrees (walls never decay; the one decay clock over built fabric is the calamity-scar half-life, keyed on the calamity kind, not on any material).
4. CORRECTED (X-33, O-20). `settled` is the producer token `heartland` = the LOW monster-and-raider tier of the country (the stress roll multiplies siege and monster by 0.3 and occupation by 0.4; `stressGenerator.js:121`, `:168`); never "no live threat", never "the centre of a realm", never founded. W2 of ADDENDUM 12 already bars a totality over the town. `frontier` is the DEFAULT of an unmeasured town (`normalizeMonsterThreat(undefined) === 'frontier'`) and is never read as a fact unless the raw value is measured (the desk already refuses it). `plagued` = monster activity, never disease (stands).
5. CORRECTED (X-32, O-2, O-3). The always-safe class words for the paid military are "the muster" and "the town's force"; below town the engine's own generic is "the community". STRUCK from the always-safe list: "the guard" (the power generator's FALLBACK label when NO force row matches, `governanceNarrative.js:506`, on which town the safety profile prints "no meaningful guard presence"; safe only where `hasMilitaryInst`) and "the men on the wall" (asserts manning, NOT ENTAILED, and a wall). "The muster roll" as a citation only where a `Citizen militia` with an instantiated `Muster training` service resolves. "The watch" as a NAME only where the town resolves `Town watch` or `Professional city watch` (town and up; `hasWatch` is town-plus); "keeps watch" as an activity HOLDS; the watch's pay sits under the ORDER purse and never under the military gate the pay-gate read measures (the referent law's rule 5 stands: the muster kind does not contain the watch bucket).
6. STANDS, WIDENED. The gate does not walk semantics; the refuters do, and the table is their instrument: a refuter passes an item in ENTAILS, fails one in NOT ENTAILED, fails a CONDITIONAL used without its condition resolved on THIS town's record, and now also fails a LABEL read as English (section 3) and an ALIAS word used where the row it names does not resolve (section 4). The licence card prints `entails:` lines per read once CAR 8b-W-2 lands; until then the refuters read the table's desk section directly.

### B. THE WRITER BARS W11–W19 (bind every writer, gate, refuter and judge from DEF-2 on; a breach is a FAIL with the bar named; each bar stands until its wiring row lands and the chair lifts it here)
W11 THE MATERIAL BAR: no wall material and no material source in any face until `{defmaterial}` is minted; a shipped "stone" or "timber" clause is the corpus's known breach and is dropped by the rewrite, never kept as a floor.
W12 THE GARRISON BAR: "the garrison" only where a `Garrison` or `Multiple garrisons` row resolves on the roster (city tier), never from a `Barracks` (a housing row) or the watch; where an occupation is on the page the face says WHOSE ("{counterpart}'s garrison", "the occupier's men") or uses "the soldiers"; an occupation never entails a garrison present.
W13 THE WATCH BAR: as item 5; the pay-gate read never uses "the watch"; a corpus row that asserts a watch off a key that reads no watch row is a breach the rewrite cures.
W14 THE LABEL BAR: an engine label is rendered at its ENGINE meaning as section 3 states it, never at its dictionary sense. The defense desk's own ten: `plagued` (monsters); `settled` (the low tier); `hasGranary` (a tier proxy: every town-plus, no village-and-below, whatever it stores); `hasChurch` (true on every hamlet from a church in another settlement); `hasCourtSystem` (every town and city, from a meeting hall; a civil arbitration is recorded, a criminal trial is not); `hasPort` (never the sea; the sea only off a `Shipyard` row or `maritimeSupported`); `hasGates` (fires on a palisade); the `Town watch`'s gate duty (recorded on gateless towns); `scores.magical` (reads a world, not a town); the readiness label (moves with tier and country while no works move). The other desks' labels bind their blocks when those desks come up.
W15 THE ALIAS BAR: a generic English word is used only where the row it names resolves on this town's record; otherwise the always-safe spelling of section 4: "the works" or "what the town has built" (any wall-class member); "the muster" / "the town's force"; "the stores" / "what the town holds back"; "the way in by water"; "the approach" / "the country outside"; "the land" / "what the town raises"; "a house of the faith" / "the parish"; "those tending the sick"; "the {seat}" filled from its own name or "the governing body" (never "the hall", "the council", "the chamber" baked); "the town's own reckoning" (never "the rolls" or "the clerks" as a citation); "the instrument" / "the document" and `{term}` (never "the tribute" or "the cap on arms" for a family); "a working plurality" (never "a majority"); "the mill" only where the resolved row is a grain mill.
W16 THE GATE'S WORD: "upkeep" and "the keeping" are the always-safe words for the military gate (the engine names it the economic-UPKEEP gate over "garrison wages, wall maintenance", `defenseGenerator.js:186`); "wages" and "pay" of the muster are the engine's own words and stay licensed under R-viii′, but never a sum, a rate, a share, a season, arrears or desertion, and never WHOSE beyond the class word (X-1: the gate fires on a wage-less village with a part-time militia; that is a wiring finding, section D, not a writer's fault).
W17 THE CRISIS BAR (cross-desk, from the stressors and war tables): a siege entails a besieger, never walls, gates, a watch or an army at the walls; an occupation entails a foreign writ and taxed revenue, never a garrison present or the town's own hall; wartime never entails hardship (the record's own profit coin) and never a garrison; a famine never entails a harvest failure or a season; a disease outbreak is "illness" or "sickness", never "the plague" and never "not yet a plague" (the two records contradict); an insurgency is never armed on the generation record.
W18 THE STRESS-RECORD BAR: a generation-built stress licenses the type's static definition AND the factions, the safety sentence and the deltas the same token minted; an `APPLY_STRESSOR` entry licenses the static definition only; a world stressor's stage, age and severity are the ORIGIN's; a birth-time origin variant licenses past tense only; `unattributed` and `palace_coup` license nothing beyond the type.
W19 THE FAITH BAR: the creed by the deity's NAME with nothing predicated of the deity (the deity doctrine, constitutional); `rank`, `standing`, `legitimacy` and `contested` each at its own engine sense (L-122, L-123), never one for another; `live: false` is "no measured standing yet", never "newly founded".

### C. THE DISAGREEMENTS X-1…X-33, RULED
The refuter's verdict STANDS as the table prints it wherever its evidence is code, which is every row except these five: X-1 (the word "wages": ruled at W16 — the engine's own word survives; the gate's firing on a wage-less roster is the wiring finding of section D, item (e)); X-16 (the power survey's "small tiers have no office-kind institution" is PLAUSIBLE and unverified — not a rule; a writer treats the office holder as CONDITIONAL on the printed card); X-31 (ruled by R-viii′ and item 3); X-32 (ruled at item 5); X-33 (ruled at item 4). The three places where the packets corrected the chair's own draft law are accepted with thanks; the chair's earlier sentence was the more knowledgeable one.

### D. THE WIRING ROWS O-1…O-20 — DISPOSITIONS (nothing here is a writer's task; the bars above keep the writers off the unwired ground)
CAR 8b-W-2 (the defense wiring car, part 2; an Opus seat in `laneRW-DEFW`; ONE lane, launched AFTER DEF-2 has returned and been read, in the one-lane order) is CHARTERED for the defense desk's rows: (a) O-1 the `{defmaterial}` derived fill with the value table of item 2, and the `{defwork}` residuals (the disjunction and the parenthesis: resolve or drop the variant); (b) O-3 a `{watchname}` fill from the resolved watch holder row, tier-scaled as `safetyProfile.js:30-35` already does; (c) O-15 the FORTIFICATION / GARRISON / MERCENARY chain statuses as reads on WALLED-STRAINED and DS-DEF-5 (ADDENDUM 12's wiring row); (d) O-14 the census token lists (the four mis-filings; the covert column reading the read path) and whether the restatement guard walks the variants' nouns; (e) the STRAINED key's firing on a wage-less roster (X-1) — RECORDED AS A PROPOSAL for the owner, not an act: gating the key on a paid force row changes what prints on shipped towns (a behaviour change on a live surface); the chair recommends it and does not do it; (f) the licence card's `entails:` lines per read (item 6). The rows of the other desks — O-4 (whose garrison, with `occupierStillPresent` wired), O-5 (`{reason}` and the provenance pools), O-6 (the exploitation lens's `{institution}`), O-7 (the market holder), O-8 (the water words and a `portKind` read), O-9 and O-10 (the treaty side arm; the `At war` residue; the covert pool), O-11, O-12, O-13 (the stressors desk's anaphora, direction lens and family door), O-16 (the general desk's frozen booleans and custom rows), O-17 (the power desk's joins), O-18 (the faith producers), O-19 (`{good}` and `{chain}`) — are RECORDED here and chartered with each desk's own wiring car when that desk comes up (general, economy, power, stressors, warFaith, in the trains' order); until then W11–W19 bar every face that would need them. O-20 is ruled at item 4. Nothing in D is a push, a walk, a migration or a schema change; a key change on a shipped surface is flagged as owner-gated.

### E. THE FOLD INTO THE WORKFLOW
`rewrite/rewrite-block-v2.workflow.js` requires `args.tables`; PART A's text for it is sections A and B of this addendum verbatim (the chair pastes them), plus the line: "READ BEFORE WRITING: `rewrite/entailment/ENTAILMENT-TABLE.draft.md` section 2.<your desk>, section 3 (label traps) and section 4 (alias traps); a CONDITIONAL entailment is used only where its condition resolves on THIS town's record as the licence card prints it; a refuter fails a breach of any bar W11–W19 with the bar named." PART B appends the referent law's ratified text the same way. No block launches until both parts stand here.
