import json
claims = json.loads(open('/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/wolfe16/claims.json',encoding='utf-8').read())
verdicts = [
 {"index":978,"verdict":"VERIFIED_VERBATIM","trueWording":"it encourages misreadings, demands thoughtful reflection","note":"Raw Cambridge Core Preface page (pp. xi-xii summary) fetched live, HTTP 200, browser UA. Quote contiguous and verbatim in the sentence beginning 'His fiction is intricately wrought...'. 'By the reader' is carried by the same sentence's continuation about involving the reader in interpretation; 'actively' is the claim's intensifier, not Wright's word, but adds no content."},
 {"index":979,"verdict":"PARTIAL","unsupportedLimb":"'rather than plain' — the page never opposes these qualities to plainness, and Wright elsewhere calls The Wizard Knight's prose spare","trueWording":"intricately wrought, densely allusive, and conceptually elusive","note":"Quote verbatim on the raw Preface page. The positive characterisation is fully supported, but the contrast with plainness is the claim's own gloss: dense allusion and conceptual elusiveness are not sentence-level plainness, and the same critic's Shadows introduction (index 982) calls Wolfe's Wizard Knight prose spare. Do not cite this as Wright denying plainness of style."},
 {"index":980,"verdict":"VERIFIED_VERBATIM","trueWording":"complex and wily writer, ambiguous, subtle and playful","note":"Verbatim on the raw Preface page, introduced by 'as the majority of critics and reviewers who have approached his oeuvre would admit'. Claim's 'critics' narrows the page's 'critics and reviewers'; 'would call him' matches the page's 'would admit'."},
 {"index":981,"verdict":"VERIFIED_VERBATIM","trueWording":"only the second book-length study of his fiction","note":"Verbatim on the raw Preface page; 'this' in the sentence is the present volume, Attending Daedalus, and the page continues 'and the first to address any material published after 1983'. Page range 'pp. xi - xii' confirmed on the same page."},
 {"index":982,"verdict":"VERIFIED_VERBATIM","trueWording":"the spare prose of The Wizard Knight","note":"Raw Cambridge Core Introduction page for Shadows of the New Sun fetched live, HTTP 200. Quote verbatim, with '(2004)' following, inside the stylistic-ingenuity contrast. Page range 'pp. 1 - 8' confirmed on the page."},
 {"index":983,"verdict":"VERIFIED_VERBATIM","trueWording":"the baroque richness of The Book of the New Sun","note":"Verbatim on the raw Introduction page, with '(1980-83)' following. The sentence frames it as a prose contrast ('his stylistic ingenuity - demonstrated, for example, in the contrast between the spare prose of The Wizard Knight and...'), so the claim's 'prose' limb is supported."},
 {"index":984,"verdict":"VERIFIED_VERBATIM","trueWording":"a phantom haunting his own memories in Peace","note":"Verbatim on the raw Introduction page, with '(1975)' following, inside the parenthesis illustrating 'his notable narrative versatility' (the other pole being narrating as a high school girl in Pandora by Holly Hollander)."},
 {"index":985,"verdict":"VERIFIED_VERBATIM","trueWording":"most stylistically distinct, structurally complex and intellectually invigorating","note":"Verbatim on the raw Introduction page; the full sentence reads 'he remains the author of some of the most ... imaginative fiction of recent years', so the claim's 'among' and 'imaginative fiction of recent years' limbs both hold."},
 {"index":986,"verdict":"VERIFIED_VERBATIM","trueWording":"agents of estrangement to render the fictional Urth alien","note":"Raw Cambridge Core 'Cues' chapter page fetched live, HTTP 200; page range 'pp. 126 - 144' confirmed. Quote verbatim; the sentence adds the irony that the archaisms 'function as neologisms', and continues that they may be as much gibberish 'to the reader', supporting the reader limb."},
 {"index":987,"verdict":"VERIFIED_VERBATIM","trueWording":"he has no fondness for 'gibberish' (by which he means neologisms)","note":"The claim's short quote 'Wolfe admits that he has no fondness for' is contiguous and verbatim on the raw 'Cues' page; the parenthetical gloss 'by which he means neologisms' is Wright's own, and the sentence attributes the admission to The Castle of the Otter, matching the claim's source line."},
 {"index":988,"verdict":"VERIFIED_VERBATIM","trueWording":"used odd words to convey the flavour of an odd place","note":"Verbatim on the raw 'Cues' page, inside Wright's quotation of Wolfe: the sentence closes 'at an odd time', and continues that these odd words substitute for SF's usual neologistic invention. Attribution to The Castle of the Otter is on the page; the page does not itself date that book to 1982."},
 {"index":989,"verdict":"VERIFIED_VERBATIM","trueWording":"a great deal of knowledge can be intuited","note":"Verbatim on the raw 'Cues' page. Wright names 'his interview with Larry McCaffery for Science-Fiction Studies' two sentences earlier and then quotes Wolfe; the page's full clause conditions on 'if you know something about the words people use', slightly tighter than the claim's 'from the words people use'. The page carries no date for the interview."},
 {"index":990,"verdict":"VERIFIED_VERBATIM","trueWording":"the notion of recycling, of social, linguistic and creative exhaustion","note":"Verbatim on the raw 'Cues' page; the subject of 'conveys' is 'Wolfe's replacement of neologistic experimentation with archaic reappropriations', so the claim's 'archaic reappropriations' limb is the page's own phrase."},
 {"index":991,"verdict":"VERIFIED_VERBATIM","trueWording":"references function both deflectively and candidly","note":"Verbatim on the raw 'Cues' page; the full sentence begins 'Paradoxically, Wolfe's Classico-medieval references function both deflectively and candidly on this intuitive, allusionary level', which supports both the 'Classico-medieval' and the simultaneity ('at once') limbs."},
 {"index":992,"verdict":"VERIFIED_VERBATIM","trueWording":"willing to question their own literary assumptions, pause, reflect and reread","note":"Raw Cambridge Core 'A Solar Labyrinth' chapter page fetched live, HTTP 200; page range 'pp. 166 - 182' confirmed. Quote verbatim; the page says the text is organised to be 'understood, or at least appreciated, only by those readers who are willing to...', which the claim compresses to 'rewards only readers'. The page names The Urth Cycle in the next sentence, supporting the work limb."},
]
out = {"name":"wolfe","chunk":16,"claims":claims,"verdicts":verdicts}
p='/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep/verdicts-wolfe-i978-992.json'
open(p,'w',encoding='utf-8').write(json.dumps(out,ensure_ascii=False,indent=1))
d=json.loads(open(p,encoding='utf-8').read())
print("claims",len(d["claims"]),"verdicts",len(d["verdicts"]))
print("indices ok:",[c["index"] for c in d["claims"]]==[v["index"] for v in d["verdicts"]])
for v in d["verdicts"]:
    w=len(v["trueWording"].split())
    print(v["index"],v["verdict"],"words=",w,"OK" if w<=12 else "OVER")
