import sys, re, html
raw = open(sys.argv[1], 'rb').read().decode('utf-8', 'ignore')
raw = re.sub(r'(?is)<(script|style|noscript|svg)\b.*?</\1>', ' ', raw)
raw = re.sub(r'(?is)<!--.*?-->', ' ', raw)
raw = re.sub(r'(?i)<(br|/p|/div|/h\d|/li|/tr)[^>]*>', '\n', raw)
raw = re.sub(r'(?s)<[^>]+>', ' ', raw)
raw = html.unescape(raw)
raw = re.sub(r'[ \t\xa0]+', ' ', raw)
raw = re.sub(r'\n\s*\n\s*\n+', '\n\n', raw)
print(raw.strip())
