-- ────────────────────────────────────────────────────────────────────────────
-- 075_account_identity_columns.sql — account identity foundation.
--
-- OPERATOR NOTE (mirror the 057/059/060 account-status discipline)
--   This migration is ADDITIVE, IDEMPOTENT and RLS-SAFE. It introduces two
--   distinct identifiers plus the private name parts, and it is the
--   security-critical foundation the gallery (076) and ticket (077) surfaces
--   build on. Apply order: after 074. Run the backfill off-peak — the two
--   UPDATEs are O(rows) with per-row generation; both are resumable
--   (`where … is null`).
--
--   TWO identifiers, intentionally kept separate:
--     • account_number — IMMUTABLE, PRIVATE, globally UNIQUE, format
--       `SF-XXXXXXX` (7 Crockford-base32 chars, ambiguous chars removed).
--       Auto-generated by the SECURITY DEFINER signup trigger ONLY. End users
--       CANNOT change it (RLS pins it in the self-UPDATE policy). There is NO
--       admin RLS UPDATE policy on profiles (the old 033 "Developers update any
--       profile" bypass was dropped at 062 and never recreated), so it is
--       changeable only via a service-role / SECURITY DEFINER path — a dev with
--       direct DB access, never an end-user. Surfaced on support tickets so an
--       operator can identify the writer without PII. Also the future referral code.
--     • external_name — PUBLIC, MUTABLE, globally UNIQUE (case-insensitive),
--       AUTO-ASSIGNED on creation so sharing works with zero setup. The gallery
--       AUTHOR shown on each shared settlement/map. Owner-editable via the
--       `update_external_name` RPC (server-side uniqueness + reserved-word
--       guard). CRITICAL: gallery shares resolve the CURRENT external_name BY
--       user_id at display time (migration 076), NOT denormalized — a rename
--       reflects everywhere automatically.
--     • first_name / last_name / preferred_name — PRIVATE profile fields,
--       owner-writable (NOT RLS-pinned).
--
-- SECURITY POSTURE
--   account_number must NEVER be a column default (a default is user-spoofable
--   on a permissive INSERT path). It is generated INSIDE the definer trigger
--   only. The self-UPDATE policy is forked VERBATIM from the NET-CURRENT 061
--   body (keep all nine existing pins + account_is_active) and ADDS one pin for
--   account_number. external_name / name parts are intentionally left writable.
--   NOTE: 062 dropped the old 033 "Developers update any profile" RLS bypass and
--   it was never recreated, so NO admin RLS UPDATE policy on profiles exists —
--   account_number (like role/tier/credits) is changeable only via a service-role
--   / SECURITY DEFINER path. That is the intended "immutable, dev-only" posture.
--
-- Depends on: 001 (profiles), 057 (account_is_active), 061 (the net-current
--             self-UPDATE policy this forks), 064 (the net-current
--             handle_new_user this forks — keeps OAuth enrichment + welcome
--             credit). NB: 062 dropped the old 033 admin-override policy.
-- ────────────────────────────────────────────────────────────────────────────

-- ── 1. Columns (additive, idempotent) ───────────────────────────────────────
alter table public.profiles add column if not exists account_number text;
alter table public.profiles add column if not exists external_name  text;
alter table public.profiles add column if not exists first_name      text;
alter table public.profiles add column if not exists last_name       text;
alter table public.profiles add column if not exists preferred_name  text;

-- Unique indexes are the REAL race backstop (the RPC pre-checks are UX only).
-- account_number: plain unique. external_name: case-insensitive unique so
-- `quietfox` and `QuietFox` can never both exist.
create unique index if not exists idx_profiles_account_number on public.profiles(account_number);
create unique index if not exists idx_profiles_external_name_ci on public.profiles(lower(external_name));

-- ── 2. Generation + normalization helpers (SECURITY DEFINER, fail-closed) ────

-- normalize_external_name — the canonical form used for the case-insensitive
-- uniqueness check (lower + trim). Immutable so it can back an index expression
-- if ever needed; kept plain here.
create or replace function public.normalize_external_name(p_name text)
returns text
language sql
immutable
set search_path = public
as $$
  select lower(btrim(coalesce(p_name, '')))
$$;

-- gen_account_number — `SF-` + 7 Crockford-base32 chars. The Crockford alphabet
-- omits the ambiguous 0/O/1/I/L/U so a support agent can read the handle aloud
-- without confusion. Retries on the (vanishingly rare) unique collision; raises
-- if the bounded retry budget is exhausted rather than returning a dup.
create or replace function public.gen_account_number()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTVWXYZ'; -- Crockford-base32 minus ambiguous chars
  candidate text;
  i int;
  attempt int := 0;
begin
  loop
    attempt := attempt + 1;
    candidate := 'SF-';
    for i in 1..7 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    -- Fail-closed: only return a value proven free of the unique index.
    if not exists (select 1 from public.profiles where account_number = candidate) then
      return candidate;
    end if;
    if attempt >= 8 then
      raise exception 'could not generate a unique account_number after % attempts', attempt;
    end if;
  end loop;
end;
$$;

-- gen_external_name — adjective + noun + 3-digit number from two small CURATED
-- word lists (e.g. `QuietCartographer418`). Curated lists keep auto-assignment
-- clean by construction (no profanity). Retries on a case-insensitive
-- collision; raises if the bounded retry budget is exhausted.
create or replace function public.gen_external_name()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  adjectives constant text[] := array[
    'Quiet','Amber','Hollow','Distant','Gilded','Weathered','Patient','Hidden',
    'Northern','Ember','Silent','Wandering','Steady','Verdant','Ashen','Bright',
    'Stoic','Wry','Candid','Tidal','Lonely','Mossy','Cobalt','Russet'];
  nouns constant text[] := array[
    'Cartographer','Archivist','Steward','Lantern','Compass','Chronicle','Warden',
    'Beacon','Ledger','Harbor','Almanac','Cairn','Sentinel','Marsh','Foundry',
    'Atlas','Vellum','Quill','Meridian','Bastion','Thicket','Hearth','Spire','Glade'];
  candidate text;
  attempt int := 0;
begin
  loop
    attempt := attempt + 1;
    candidate :=
      adjectives[1 + floor(random() * array_length(adjectives, 1))::int]
      || nouns[1 + floor(random() * array_length(nouns, 1))::int]
      || (100 + floor(random() * 900))::int::text;
    if not exists (
      select 1 from public.profiles
      where lower(external_name) = lower(candidate)
    ) then
      return candidate;
    end if;
    if attempt >= 12 then
      raise exception 'could not generate a unique external_name after % attempts', attempt;
    end if;
  end loop;
end;
$$;

-- ── 3. Reserved-name guard seed (user-edit path only) ────────────────────────
-- Auto-assigned names are clean by construction; this table guards the
-- owner-edit path (update_external_name). Idempotent seed.
create table if not exists public.reserved_external_names (
  name text primary key
);

insert into public.reserved_external_names (name) values
  ('admin'),('administrator'),('system'),('support'),('settlement'),
  ('settlements'),('moderator'),('mod'),('official'),('anonymous'),
  ('deleted'),('null'),('undefined'),('root'),('staff'),('team'),
  ('settlement-engine'),('settlementengine'),('owner'),('developer'),
  -- small profanity guard (best-effort; the curated generator never emits these)
  ('fuck'),('shit'),('bitch'),('cunt'),('nigger'),('faggot'),('rape'),('nazi')
on conflict (name) do nothing;

-- ── 4. handle_new_user — fork from NET-CURRENT 064 body + identity assignment ─
-- VERBATIM from 064 (keeps OAuth name/avatar enrichment AND the welcome-credit
-- block), with two additions:
--   • the INSERT now also generates account_number + external_name, and
--   • the `do update` branch COALESCEs onto the EXISTING values so a number
--     already issued to a row is NEVER reissued (immutability across re-signup).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id, email, display_name, avatar_url, tier, credits,
    account_number, external_name
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture'),
    'free',
    0,
    public.gen_account_number(),
    public.gen_external_name()
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = coalesce(public.profiles.display_name, excluded.display_name),
        avatar_url   = coalesce(public.profiles.avatar_url, excluded.avatar_url),
        -- Immutability across re-signup: keep an already-issued identifier.
        account_number = coalesce(public.profiles.account_number, excluded.account_number),
        external_name  = coalesce(public.profiles.external_name,  excluded.external_name),
        updated_at = now();

  -- Welcome-credit block, copied verbatim from migration 064 (unchanged).
  if not exists (
    select 1
    from public.credit_ledger
    where user_id = new.id
      and kind = 'grant'
      and source = 'welcome'
  ) then
    insert into public.credit_ledger (user_id, kind, amount, source, metadata)
    values (
      new.id,
      'grant',
      1,
      'welcome',
      jsonb_build_object('trigger', 'handle_new_user')
    );

    insert into public.credit_transactions (user_id, amount, reason)
    values (new.id, 1, 'welcome');

    update public.profiles
      set credits = coalesce(credits, 0) + 1,
          updated_at = now()
      where id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

comment on function public.handle_new_user() is
  'Creates a profile (email + display_name + avatar_url enriched from raw_user_meta_data; account_number + external_name auto-generated) and grants the one-time welcome credit. COALESCEs name/avatar/account_number/external_name on conflict so an already-issued identifier is never reissued (account_number immutability).';

-- ── 5. Backfill existing profiles (idempotent, per-row collision-safe) ────────
-- A per-row loop so one (vanishingly rare) collision can't abort the whole
-- batch — the set-based form would re-raise and roll back. Both passes are
-- resumable: re-running only touches rows still null.
do $$
declare
  r record;
begin
  for r in select id from public.profiles where account_number is null loop
    update public.profiles set account_number = public.gen_account_number() where id = r.id;
  end loop;
  for r in select id from public.profiles where external_name is null loop
    update public.profiles set external_name = public.gen_external_name() where id = r.id;
  end loop;
end;
$$;

-- ── 6. RLS — account_number end-user-immutable ───────────────────────────────
-- Drop+recreate the NET-CURRENT (061) self-UPDATE policy by name, carrying its
-- body VERBATIM (all nine pins + account_is_active) and ADDING the
-- account_number pin. external_name / first_name / last_name / preferred_name
-- are intentionally NOT pinned — they stay owner-writable. No admin RLS UPDATE
-- policy on profiles exists (033 was dropped at 062), so account_number is
-- writable only via a service-role / SECURITY DEFINER path, never an end-user.
drop policy if exists "Users update own profile (safe preferences only)" on public.profiles;
create policy "Users update own profile (safe preferences only)"
  on public.profiles
  for update
  using (auth.uid() = id and public.account_is_active(auth.uid()))
  with check (
    auth.uid() = id
    and public.account_is_active(auth.uid())
    and role               is not distinct from (select role               from public.profiles where id = auth.uid())
    and tier               is not distinct from (select tier               from public.profiles where id = auth.uid())
    and credits            is not distinct from (select credits            from public.profiles where id = auth.uid())
    and is_founder         is not distinct from (select is_founder         from public.profiles where id = auth.uid())
    and stripe_customer_id is not distinct from (select stripe_customer_id from public.profiles where id = auth.uid())
    and email              is not distinct from (select email              from public.profiles where id = auth.uid())
    and banned_at          is not distinct from (select banned_at          from public.profiles where id = auth.uid())
    and disabled_at        is not distinct from (select disabled_at        from public.profiles where id = auth.uid())
    and deleted_at         is not distinct from (select deleted_at         from public.profiles where id = auth.uid())
    -- 075: pin account_number so an end-user self-UPDATE can NEVER change its own
    -- immutable, private identifier. Writable only via a service-role / SECURITY
    -- DEFINER path (no admin RLS UPDATE policy on profiles exists post-062).
    and account_number     is not distinct from (select account_number     from public.profiles where id = auth.uid())
  );

-- ── 7. update_external_name(new_name) — owner-edit RPC (mirror 009 pattern) ──
-- SECURITY DEFINER, fail-closed. Server-side validation is AUTHORITATIVE; the
-- client mirrors it for UX only. Enforces charset, length, the reserved-name
-- guard, and case-insensitive uniqueness; the unique index is the race backstop
-- (catch unique_violation → friendly raise).
create or replace function public.update_external_name(new_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  trimmed text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  trimmed := btrim(coalesce(new_name, ''));

  if length(trimmed) < 3 or length(trimmed) > 24 then
    raise exception 'Display author name must be 3 to 24 characters';
  end if;
  if trimmed !~ '^[A-Za-z0-9_]+$' then
    raise exception 'Display author name may use only letters, numbers, and underscores';
  end if;
  if exists (
    select 1 from public.reserved_external_names
    where name = public.normalize_external_name(trimmed)
  ) then
    raise exception 'That name is reserved';
  end if;
  if exists (
    select 1 from public.profiles
    where lower(external_name) = public.normalize_external_name(trimmed)
      and id <> auth.uid()
  ) then
    raise exception 'That name is taken';
  end if;

  update public.profiles
    set external_name = trimmed,
        updated_at    = now()
    where id = auth.uid();

  return trimmed;
exception
  when unique_violation then
    -- The unique index is the authoritative race backstop; translate to the
    -- same friendly message the pre-check would have raised.
    raise exception 'That name is taken';
end;
$$;

grant execute on function public.update_external_name(text) to authenticated;

comment on function public.update_external_name(text) is
  'Owner-edit path for the public gallery author name (external_name). Validates charset/length, rejects reserved + profane names, enforces case-insensitive uniqueness (unique index is the race backstop). SECURITY DEFINER; server-side validation is authoritative.';

-- ── 8. update_profile_names(...) — owner-edit RPC for the private name parts ─
-- first/last/preferred are owner-writable and NOT RLS-pinned, but a single RPC
-- keeps the client write surface consistent (and trims/null-empties uniformly).
create or replace function public.update_profile_names(
  p_first     text default null,
  p_last      text default null,
  p_preferred text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  update public.profiles
    set first_name     = nullif(btrim(coalesce(p_first, '')), ''),
        last_name      = nullif(btrim(coalesce(p_last, '')), ''),
        preferred_name = nullif(btrim(coalesce(p_preferred, '')), ''),
        updated_at     = now()
    where id = auth.uid();
end;
$$;

grant execute on function public.update_profile_names(text, text, text) to authenticated;

comment on function public.update_profile_names(text, text, text) is
  'Owner-edit path for the PRIVATE name parts (first_name/last_name/preferred_name). Trims and null-empties. SECURITY DEFINER, owner-scoped via auth.uid().';
