import json
base = "/private/tmp/claude-502/-Users-cstokes-Desktop-settlement-engine/26b2203a-14d7-409e-a7aa-8d0f3b0517db/scratchpad/prose-research/sweep"
chunk = json.load(open(base + "/chunks/tolkien-14.json", encoding="utf-8"))
verdicts = [
 {"index":838,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Collier: 'tolkien's language is left intact in the mouths of the proper characters'; separately 'still highly trained in diction ... while still retaining all subtle differences in accents', and 'subtle varieties in accents, which one also finds in the books'. Every limb on the raw page."},
 {"index":839,"verdict":"PARTIAL","trueWording":"Nighy sings Gil-galad; Le Mesurier sings Bilbo's Last Song","note":"Verified: 'putting many of the poems and songs to music'; 'William Nighy as Sam singing a part of the fall of Gil-Galad'; 'Douglas Livingstone does a splendid job with Gimli's Khazad-dum poem'. But the page attributes Bilbo's Last Song to John Le Mesurier ('a demo version of John Le Mesurier singing Bilbo's Last Song'); its own sentence names Nighy's second song as 'his song in the tower of Minas Morgul', not Bilbo's Last Song.","unsupportedLimb":"that Bill Nighy sings Bilbo's Last Song - the page credits John Le Mesurier"},
 {"index":840,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Brunstrom: 'the rusticity of Strider remains a leitmotif that interrupts the steady majesty of King Elessar', after 'When you hear him for the first time in the Prancing Pony, he sounds rustic'; and 'His dramatisation keeps as much of Tolkien's dialogue as possible.' Quoted phrase 'remains a leitmotif' word for word."},
 {"index":841,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Brunstrom: 'a tendency not to want to work the narrator (Gerard Murphy) too hard, and to attempt to transfer some of the descriptions into dialogue'; 'Sam (Bill Nighy) is rather awkwardly forced to narrate the process of his battle with Shelob in real time.' Quoted phrase present verbatim."},
 {"index":842,"verdict":"VERIFIED_SUBSTANCE","trueWording":"singing the Rohan lay written in its wake, battle dialogue between verses","note":"Brunstrom: 'The Battle of the Pelennor Fields is developed cleverly by singing the Rohan lay written in its wake and inserting battle dialogue in between its verses.' Claim carries no quote field; 'written afterwards' is the page's 'written in its wake' in other words, hence SUBSTANCE not VERBATIM."},
 {"index":843,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Brundige, Appendix A: 'Sibley and Bakewell use Tolkien's words almost exclusively, except for stage directions (e.g. Frodo exclaiming, \"the river is rising!\")'; 'The radio play shuns flashback and the narrator's voice as much as possible.' Both limbs and the quote on the raw page; page label 'Appendix A' correct."},
 {"index":844,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Brundige: 'Sibley and Bakewell meticulously combed through Tolkien's narrative of the battle and adapted lines of its description, in meter, with appropriate alliteration ... lines had been added ... which in fact were not originally part of these songs'; the example 'crashed to the ground with the king crushed beneath him' appears verbatim, and narrative there 'is provided by stanzas of the ballad'."},
 {"index":845,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Brundige: 'a Faramir whose voice and courtly speech \"show his quality\" as much as his deeds: proof that one can capture Tolkien's larger-than-life heroes faithfully yet have them sound like flesh-and-blood people. Aragorn, too, is both human and hero, his manner of speech altered not a jot.' Quote verbatim."},
 {"index":846,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Brundige: 'Language is part of what makes the Lord of the Rings stand out, and radio gives it full wings to fly.' Quoted phrase word for word."},
 {"index":847,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Lee PDF (fetched as binary, text extracted with pypdf), footnote 7: Sibley 'used one in 1981 (Gerard Murphy) as it allowed you to \"capture the authorial voice of the book\", convey a sense of place and passing of time, move you across scenes (especially useful when the Fellowship splits up)', cited '(Sibley, 2019)'. Every limb, in footnote 7 as claimed."},
 {"index":848,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Roger Edwards: 'Great care was taken with pronunciation of words and the delivery of dialogue spoken in Elvish and the Black Speech.' and 'The characterisations and dialogue were extremely well realised'. Quote verbatim; the fetched page is the 24 Nov post itself, not a snippet."},
 {"index":849,"verdict":"PARTIAL","trueWording":"Tolkien wanted the threads NOT interwoven but on individual chronology","note":"Verified on Sibley's blog: 'Gerard Murphy, who gave the series its strong narrative voice'; Christopher Tolkien's help 'included recording an audiocassette of the acceptable pronunciation of Middle-earth words and names'. But the chronology sentence reads: Tolkien 'had been adamant that the two main threads ... should not be interwoven, but should follow their own individual chronology, as they do in the book', which Sibley concluded could not 'be applied to a dramatic presentation'. The page's word is un-interwoven/individual, the opposite of the claim's 'interlaced'.","unsupportedLimb":"calling the chronology Sibley rejected 'interlaced' - the page says Tolkien insisted the threads NOT be interwoven, each on its own chronology"},
 {"index":850,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Wikipedia quotes Tolkien to Tiller, November 1956: 'it requires rather the older art of the reading \"mime\", than the more nearly dramatic, which results in too great an emphasis on dialogue (mostly with its setting removed)'. Quote verbatim; date and addressee both on the page (ref #194 to Terence Tiller, 6 November 1956)."},
 {"index":851,"verdict":"VERIFIED_VERBATIM","trueWording":"","note":"Wikipedia: 'Replying to Rayner Unwin in 1957 ... he wrote: \"I think I should find vulgarization less painful than the sillification achieved by the B.B.C.\"' Quoted word 'sillification' verbatim; year and sense exact (page spells vulgarization with a z)."},
 {"index":852,"verdict":"VERIFIED_SUBSTANCE","trueWording":"first series welcomed, 64/100 by last episode; second compressed, criticised","note":"Wikipedia: 'audience appreciation had by the last episode reached 64 out of 100 from an initial score of 56'; listeners 'enjoyed the first series, where Tiller had followed Tolkien's advice to make a selection of scenes and cut the rest. They were far more critical of the second series, where Tiller had compressed many scenes, resulting in what a self-described \"Civil Servant\" called \"a footling and ridiculous sounding adventure story\"'. Two caveats short of VERBATIM: 64 is the last-episode score (initial 56), and the footling phrase is one named listener's, quoted by the page as the result of the compression, not a general verdict."}
]
out = {"name":"tolkien","chunk":14,"claims":chunk["claims"],"verdicts":verdicts}
assert len(out["claims"]) == 15 and len(verdicts) == 15
assert [c["index"] for c in out["claims"]] == [v["index"] for v in verdicts]
p = base + "/verdicts-tolkien-i838-852.json"
json.dump(out, open(p,"w",encoding="utf-8"), indent=1, ensure_ascii=False)
print("wrote", p)
