# -*- coding: utf-8 -*-
RT="Wayback raw capture of DePauw SFS page"
SOURCES=[
 dict(title="George Slusser, 'Le Guin and the Future of SF Criticism', Science Fiction Studies #53 (March 1991)", url="https://web.archive.org/web/20250524105632id_/https://www.depauw.edu/sfs/review_essays/sluss53.htm", kind="analysis", substantive=True, date="1991-03", route=RT),
 dict(title="Fredric Jameson, 'World Reduction in Le Guin', Science Fiction Studies #7 (Nov 1975)", url="https://web.archive.org/web/20250607182307id_/https://www.depauw.edu/sfs/backissues/7/jameson7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="Darko Suvin, 'Parables of De-Alienation: Le Guin's Widdershins Dance', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20260206193435id_/https://www.depauw.edu/sfs/backissues/7/suvin7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="Donald F. Theall, 'The Art of Social-Science Fiction', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20251222093314id_/https://www.depauw.edu/sfs/backissues/7/theall7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="Judah Bierman, 'Ambiguity in Utopia: The Dispossessed', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20251219192652id_/https://www.depauw.edu/sfs/backissues/7/bierman7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="John Huntington, 'Public and Private Imperatives in Le Guin's Novels', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20250317044239id_/https://www.depauw.edu/sfs/backissues/7/huntington7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="Douglas Barbour, 'Wholeness and Balance: An Addendum', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20251225062058id_/https://www.depauw.edu/sfs/backissues/7/barbour7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="Ursula K. Le Guin, 'American SF and the Other', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20251215080725id_/https://www.depauw.edu/sfs/backissues/7/leguin7art.htm", kind="own-words", substantive=True, date="1975-11", route=RT),
 dict(title="Ian Watson, 'The Forest as Metaphor for Mind', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20260107011510id_/https://www.depauw.edu/sfs/backissues/7/watson7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="Rafail Nudelman, 'An Approach to the Structure of Le Guin's SF', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20221202232531id_/https://www.depauw.edu/sfs/backissues/7/nudelman7art.htm", kind="analysis", substantive=True, date="1975-11", route=RT),
 dict(title="David L. Porter, 'The Politics of Le Guin's Opus', SFS #7 (Nov 1975)", url="https://web.archive.org/web/20251209040531id_/https://www.depauw.edu/sfs/backissues/7/porter7art.htm", kind="analysis", substantive=False, date="1975-11", route=RT),
 dict(title="Elizabeth Cummins, Understanding Ursula K. Le Guin (1990) — archive.org lending item understandingurs0000cumm", url="https://archive.org/details/understandingurs0000cumm", kind="analysis", substantive=False, date="1990", route="BLOCKED: lending-only; search-inside returns 'Item not available'; _djvu.txt returns HTTP 403"),
 dict(title="James W. Bittner, Approaches to the Fiction of Ursula K. Le Guin (1984) — archive.org approachestofict0000bitt", url="https://archive.org/details/approachestofict0000bitt", kind="analysis", substantive=False, date="1984", route="BLOCKED: lending-only; search-inside 'Item not available'"),
 dict(title="George Slusser, The Farthest Shores of Ursula K. Le Guin (1976) — archive.org farthestshoresof0000slus", url="https://archive.org/details/farthestshoresof0000slus", kind="analysis", substantive=False, date="1976", route="BLOCKED: lending-only; search-inside 'Item not available'"),
 dict(title="Harold Bloom ed., Ursula K. Le Guin: Modern Critical Views (1986) — archive.org ursulakleguin00bloo", url="https://archive.org/details/ursulakleguin00bloo", kind="analysis", substantive=False, date="1986", route="BLOCKED: lending-only; search-inside 'Item not available'"),
 dict(title="Mike Cadden, Ursula K. Le Guin Beyond Genre (2005) — archive.org ursulakleguinbey0000cadd", url="https://archive.org/details/ursulakleguinbey0000cadd", kind="analysis", substantive=False, date="2005", route="BLOCKED: lending-only; search-inside 'Item not available'"),
]
